### ISSUE TITLE
Feature Request: Plex Login

### ISSUE THREAD

**Issue by hongkongkiwi** [authelia/authelia#1008]
Hi there,

I would like to put in a feature request.

I imagine many people like myself are using Authelia to secure our range of docker based media services (plex, ombi, heimdall, tautulli etc).

I would love to be able to login using my Plex account in front of all the dockers so that my users don't need to remember another username and password combo for each service. This nicely matches some of the existing services which use plex oauth to check which user is logged in (e.g. Ombi).

Plex has an a way to login ([Ombi does it here](https://github.com/tidusjar/Ombi/blob/5ee25be669e0ae7f3b9754656530197e0237731b/src/Ombi/Controllers/External/PlexController.cs)), it would be great to see this as an option.

If not a specific plex login, it would be great to have a generic way to write some adapter code and delegate the login part to another server. E.g. I could write a node.js server to handle plex authentication and pass back the results.

**Comment by clems4ever** [comment]
Hello @hongkongkiwi,
If Plex supports OAuth2, which it seems, then the following issue would solve your problem: https://github.com/authelia/authelia/issues/189. It's a subject I'm working on right now.

Please follow #189 to keep being updated.

**Comment by priceaj** [comment]
Although I have long since moved to authentk, which does allow Plex to be an identity provider, I did prefer the ease of use of authelia, however, now #189 is complete I still cant understand how this is completing this request. 

Am I correct in saying that we need to wait for the [relaying party](https://www.authelia.com/roadmap/planning/openid-connect-1.0-relying-party/) roadmap item to be complete before we can do this?

**Comment by james-d-elliott** [comment]
> now #189 is complete

Technically not complete or out of beta, but very close to. It's just that we've passed official certification standards for multiple certification suites (unlike Authentik).

> Am I correct in saying that we need to wait for the [relaying party](https://www.authelia.com/roadmap/planning/openid-connect-1.0-relying-party/) roadmap item to be complete before we can do this?

Yep you're correct, separate feature. The correct issue to track is #2728

**Comment by james-d-elliott** [comment]
For reference, I plan to start work on the RP/Client role in the next 6 months, and it's unlikely to take too long. The key complexity will be adding configuration escape hatches to handle non-compliant providers.
