### ISSUE TITLE
documentation - traefik sso example

### ISSUE THREAD

**Issue by fredericrous** [authelia/authelia#1025]
Hello,

I would like some guidance with the example located here
https://docs.authelia.com/deployment/supported-proxies/traefik2.x.html

Should I be able to connect once with authelia to nextcloud? I mean what I am expecting is to login with authelia and be automatically logged in within nextcloud.

I defined the same username in users_database.yml and in nextcloud.

Should I do some extra configuration in nextcloud?

PS: Thanks for developing and making authelia FOOS, wonderful project

**Comment by nightah** [comment]
As it stands today Nextcloud does not allow/provide the means to perform Header based proxy authentication.

This effecitvely means that if you are protecting Nextcloud with Authelia you will need to login to both portals.

Nextcloud does support some level of OAuth2 but it looks like the backends are limited, your best bet is probably posting in their community forums to allow support of external OAuth backends as this is an element that we are working on currently and should hopefully be made available soon.

**Comment by fredericrous** [comment]
Thank you so much for your quick reply nightah. My confusion came from the fact the example was using nextcloud as the container being protected. If others get confused like me, now they will have this issue to refer to.
