### ISSUE TITLE
Out of Memory on invalid credentials

### ISSUE THREAD

**Issue by ViRb3** [authelia/authelia#1044]
## Update
After some research I managed to figure out my issue.

Since Authelia uses argon2 as the default hashing algorithm, all new and non-existent accounts' passwords will be hashed with it. Given the default memory difficulty is set to 1GB, that amount will be allocated _twice_ before starting to be reused for future hashing operations. This caused the out of memory situation on my Raspberry Pi 4, and ultimately killed it. After adjusting the memory difficulty or switching back to sha512, everything is fine. This is a bit of unexpected behavior, as pointed out in #845 Go should free argon2-related memory when the OS needs it, but that was not the case for me. Perhaps it will only start doing it after the first two allocations, which were already too much for my device.

### Raspberry Pi 4
- Ubuntu 20 arm64
- Template config with LDAP, redis and other external services turned off in favor of self-contained alternatives, download [here](https://bashupload.com/xHC7x/u85bf.yml)

## Issue
On Authelia versions 4.15.1-4.19 (latest), entering an invalid username or password allocates 1GB RAM on every attempt. After a few attempts, the system crashes with an Out of Memory exception.

On versions prior to 4.15.1, this only happens on correct username but incorrect password.

**Comment by ViRb3** [comment]
I managed to reproduce the issue a few more times, seems like it only triggers if you use a username that starts with an existing username but then has additional letters. For an example, if there is a real user called "admin", logging in as "admin1" or "admin123" etc. will trigger this bug.

**Comment by ViRb3** [comment]
## Update 2:
I was able to reproduce this issue on my amd64 laptop using unmodified config template, just by turning off LDAP and other unavailable services. I was able to mitigate this issue by reverting all the way back to version 4.15.1, on both machines.

**Comment by callumgare** [comment]
> but that was not the case for me

Same for me! How come you closed the ticket?

**Comment by james-d-elliott** [comment]
If this is still occurring we can reopen it. However I do remember us thoroughly testing it using stress-ng (it's even explained in the docs) and found that it releases the memory as expected per how Go manages memory allocations. https://www.authelia.com/docs/configuration/authentication/file.html

Considering the implementation we use is basically from the go x/cypto library it's highly unlikely that there is an actual issue that isn't part of the go x/cypto library. Feel free to respond if you think it should be reopened especially if you can replicate it using stress-ng to simulate pressure.

**Comment by callumgare** [comment]
Mmm, Maybe it’s not lack of memory which is causing my instance of Authelia to regularly die. I’ll keep experimenting and see if I can work out what is happening. Thanks for your detailed reply!

**Comment by nightah** [comment]
Also in this specific case it's recommended to tune down the memory allocation for a embedded device like a RPi per the [examples in the documentation](https://www.authelia.com/docs/configuration/authentication/file.html#examples-for-specific-systems).
