### ISSUE TITLE
Its looking for a directory for the config.yml file

### ISSUE THREAD

**Issue by shreyasajj** [authelia/authelia#1084]
I was attempting to mount the config.yml for the first time and It keeps telling me it wants a directory.

Error: ERROR: for authelia  Cannot start service authelia: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/user/docker/authelia/configuration.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/e40ef719b23e3596d165e6393d8f42e6d85496e7e393d5b5b06984559a0ff9cb/merged\\\" at \\\"/var/lib/docker/overlay2/e40ef719b23e3596d165e6393d8f42e6d85496e7e393d5b5b06984559a0ff9cb/merged/etc/authelia/configuration.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

File architecture:
/docker
----/authelia
--------configuration.yml
--------users_database.yml
--------/authelia

docker-compose file
authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - $USERDIR/docker/authelia/authelia:/var/lib/authelia
      - $USERDIR/docker/authelia/configuration.yml:/etc/authelia/configuration.yml:ro
      - $USERDIR/docker/authelia/users_database.yml:/etc/authelia/users_database.yml
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - t2_proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`login.$DOMAINNAME`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - "traefik.http.routers.oauth-rtr.middlewares=chain-oauth@file"
    expose:
      - 9091
    restart: unless-stopped

**Comment by clems4ever** [comment]
Hello @shreyasajj , please double check what USERDIR is set to. I don't know if the file architecture you mention is expressed relative to a root path or absolute but if it's relative, this error message makes me think your env variable is not set properly. You can confirm that by checking if `/docker/authelia/configuration.yml` (absolute path) exists on your system.

**Comment by shreyasajj** [comment]
The USERDIR is set to `USERDIR=/home/user.` 
This env variable is set properly as many other images in my docker-compose use it successfully such as Traefik. 
Also If I do delete the configuration.yml file, It creates a directory called configuration.yml/ and doesn't toss this error. 
I apologize if I did not format this right, this is my first time opening and issue, and I really appreciate any help I can get. :)

**Comment by james-d-elliott** [comment]
What happens when you do `ls -al $USERDIR/docker/authelia`?

**Comment by shreyasajj** [comment]
I get the error `ls: cannot access '/docker/authelia': No such file or directory`

**Comment by nightah** [comment]
That error seems to imply that the `$USERDIR` env variable doesn't seem to be set.

**Comment by james-d-elliott** [comment]
@benwalio you mean in your compose you are using $USERDIR in the volumes to tell docker where to mount the files? If so Authelia has no knowledge of that, docker mounts the volumes, not Authelia. It will happen with any container where you don't set your ENV correctly before running docker-compose up.

**Comment by nightah** [comment]
@shreyasajj can you please try surround your volume mappings with quotes?
```yaml
- $USERDIR/docker/authelia/authelia:/var/lib/authelia
- $USERDIR/docker/authelia/configuration.yml:/etc/authelia/configuration.yml:ro
- $USERDIR/docker/authelia/users_database.yml:/etc/authelia/users_database.yml
- "/etc/localtime:/etc/localtime:ro"
```

Sould become:
```yaml
- "$USERDIR/docker/authelia/authelia:/var/lib/authelia"
- "$USERDIR/docker/authelia/configuration.yml:/etc/authelia/configuration.yml:ro"
- "$USERDIR/docker/authelia/users_database.yml:/etc/authelia/users_database.yml"
- "/etc/localtime:/etc/localtime:ro"

**Comment by nightah** [comment]
@shreyasajj any updates? Is this still a problem, did you manage to sort this out?

**Comment by shreyasajj** [comment]
@nightah Still gave the same error

**Comment by nightah** [comment]
Can you confirm if there's an actual directory at said location?
`ls -lah $USERDIR/docker/authelia`
`ls -lah /docker/authelia`

Similar to @clems4ever's suggestions it appears that your mappings seem to be incorrect and your intial run without a configuration in the specified location has resulted in a folder being created automatically by Docker.

**Comment by shreyasajj** [comment]
@nightah 
ls -lah $USERDIR/docker/authelia: ls: cannot access '/docker/authelia': No such file or directory
ls -lah /docker/authelia: ls: cannot access '/docker/authelia': No such file or directory

however I do have this 
`  traefik:
    depends_on:
      - watchtower
#      - authelia
    container_name: traefik
    image: traefik:chevrotin # the chevrotin tag refers to v2.2.x
    restart: always
    command: # CLI arguments
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=true
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443
        # Allow these IPs to set the X-Forwarded-* headers - Cloudflare IPs: https://www.cloudflare.com/ips/
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      - --entryPoints.traefik.address=:8080
      - --api=true
#      - --api.insecure=true
#      - --serversTransport.insecureSkipVerify=true
      - --log=true
      - --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100 # Configuring a buffer of 100 lines
      - --accessLog.filters.statusCodes=400-499
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.$DOMAINNAME`)
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=t2_proxy
      - --providers.docker.swarmMode=false
      - --providers.file.directory=/rules # Load dynamic configuration from one or more .toml or .yml files in a directory.
#      - --providers.file.filename=/path/to/file # Load dynamic configuration from a file.
      - --providers.file.watch=true # Only works on top level files in the rules folder
#      - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory # LetsEncrypt Staging Server - uncomment when testing
      - --certificatesResolvers.dns-cloudflare.acme.email=$CLOUDFLARE_EMAIL
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
#    networks:
#      t2_proxy:
#        ipv4_address: 192.168.90.254 # You can specify a static IP
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - $USERDIR/docker/traefik2/rules:/rules 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $USERDIR/docker/traefik2/acme/acme.json:/acme.json 
      - $USERDIR/docker/traefik2/traefik.log:/traefik.log 
      - $USERDIR/docker/shared:/shared
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - CF_API_EMAIL=$CLOUDFLARE_EMAIL
      - CF_API_KEY=$CLOUDFLARE_API_KEY
    labels:
      - "traefik.enable=true"
      # HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME`)"
      - "traefik.http.routers.traefik-rtr.tls=true"
#      - "traefik.http.routers.traefik-rtr.tls.certresolver=dns-cloudflare" # Comment out this line after first run of traefik to force the use of wildcard certs
      - "traefik.http.routers.traefik-rtr.tls.domains[0].main=$DOMAINNAME"
      - "traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.$DOMAINNAME"
#      - "traefik.http.routers.traefik-rtr.tls.domains[1].main=$SECONDDOMAINNAME" # Pulls main cert for second domain
#      - "traefik.http.routers.traefik-rtr.tls.domains[1].sans=*.$SECONDDOMAINNAME" # Pulls wildcard cert for second domain
      ## Services - API
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      ## Middlewares
     # - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file" 
#WatchTower
      - "com.centurylinklabs.watchtower.enable=true"
#api
#      - 'traefik.http.routers.api.rule=Host(`traefik.$DOMAINNAME`)'
#      - 'traefik.http.routers.api.entrypoints=https'
#      - 'traefik.http.routers.api.service=api@internal'
#      - 'traefik.http.routers.api.tls=true'

#WatchTower Auto Update
  watchtower:
    command: --label-enable --cleanup --interval 300
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: none
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
`

**Comment by nightah** [comment]
The issue is clearly that those paths do not exist, Docker is trying to interpret an environment variable that is not set. Where is your $USERDIR environment variable actually set for the Traefik container?

Can I suggest you use a fully qualified path without your $USERDIR variable first to confirm this works?

Then you will need to figure out where your USERDIR environment variable is set and fix that.

**Comment by shreyasajj** [comment]
I put absolute path 
```
      - /home/mastermike/docker/authelia/authelia:/var/lib/authelia
      - /home/mastermike/docker/authelia/configuration.yml:/etc/authelia/configuration.yml
      - /home/mastermike/docker/authelia/users_database.yml:/etc/authelia/users_database.yml
      - "/etc/localtime:/etc/localtime:ro"
```

It still failed

**Comment by nightah** [comment]
Can you paste the full error log and the output to:
`ls -lah /home/user/docker/authelia`

**Comment by shreyasajj** [comment]
```
total 20K
drwxrwxr-x+ 3 user user 4.0K Jun  3 18:52 .
drwxrwxr-x+ 9 user user 4.0K Jun 11 01:07 ..
drwxrwxr-x+ 2 user user 4.0K Jun  3 18:33 authelia
-rw-rw-r--+ 1 user user 3.3K Jun  3 18:51 configuration.yml
-rw-rw-r--+ 1 user user  203 Jun  3 18:52 users_database.yml
```

**Comment by nightah** [comment]
Please try the following commands in the same directory as the `docker-compose.yml` for your Authelia service:
`docker rm -f authelia`
`docker-compose rm authelia`
`docker-compose up -d`

If it errors please provide the complete contents of the console.

**Comment by shreyasajj** [comment]
Same error, also because of the error the docker container failed to be created so there never was a container

**Comment by nightah** [comment]
I'm not asking for the logs of the container, I want to see the contents of your console when you issue the commands and when the error is logged to see if there's anything that might be able to help.

Alternatively I'd suggest you email the team your `docker-compose.yml` and look to only redact your secrets. This isn't an Authelia issue it's something to do with how you're specifying your volumes and the directory structure.

**Comment by nightah** [comment]
@shreyasajj did you manage to resolve your issue?

**Comment by shreyasajj** [comment]
@nightah I did. I had to reinstall the image.
