### ISSUE TITLE
Docker Image /authelia:4.20 not working properly

### ISSUE THREAD

**Issue by XabiAlonso86** [authelia/authelia#1125]
Hi,

I don't know exactly the changes but until yesterday my authelia docker was working properly but today the docker was updated to tag 4.20 and everything stop working. Log reports the following:

level=fatal msg="Unable to initialize SQL database: Unable to create table user_preferences: dial tcp 127.0.0.1:3306: connect: connection refused

I think that's exactly the issue. Authelia is trying to connect SQL Database on localhost and that's incorrect because I have a mariadb docker for this purpose. 

Returning to version 4.19 solved all the issues.

**Comment by nightah** [comment]
@XabiAlonso86 please refer to the `BREAKING.md` or the changelog on the [release page](https://github.com/authelia/authelia/releases).

**Comment by XabiAlonso86** [comment]
Thanks! Now it is solved!
