### ISSUE TITLE
Secure password including symbols issue

### ISSUE THREAD

**Issue by waynehaffenden** [authelia/authelia#1127]
When hashing a secure password with multiple symbols such as $%^;: this results in rejected login (says password is incorrect). I've tried resetting the password and entering via the reset UI which then results in a out of memory exception, are these symbols not supported?

**Comment by nightah** [comment]
You need to make sure that when you're using special characters that you enclose the password hash command with single quotes `''`.

So something like: `docker run authelia/authelia authelia hash-password '&a^$&V!Y^Z'`
If you don't, depending on the character that's passed in it could be intrepolated by the shell into something else.

The second point regarding out of memory exceptions have a read of [this](https://www.authelia.com/docs/configuration/authentication/file.html#password-hash-algorithm).
Essentially you should be tuning your argon2 parameters to your system, the default uses 1GB of RAM during hashes.

**Comment by nightah** [comment]
@waynehaffenden how'd you go with this? Did that resolve your issue, or is there something else that we can help you with?

**Comment by waynehaffenden** [comment]
@nightah Thank you for your advice, using the single quotes fixed this issue. Also, reducing the RAM fixed the reset password UI.
