### ISSUE TITLE
Quick Start Doesn't Work

### ISSUE THREAD

**Issue by ajanthan** [authelia/authelia#1129]
I cloned the master branch and tried according to [quick start](https://www.authelia.com/docs/getting-started.html). It didn't work. When I accessed https://secure.example.com, it was giving 404.

I checked the log of authelia and it was looking for LDAP, Redis and SMTP server.

**Comment by nightah** [comment]
Thanks for reporting this @ajanthan I missed something in an earlier PR and this regressed the local compose bundles, I'm pushing a PR to fix this now.

**Comment by AkgunFatih** [comment]
@nightah  Still the same issue !!!!!!!!!!!!!!!!!!!!!!
