### ISSUE TITLE
Send plaintext emails alongside HTML

### ISSUE THREAD

**Issue by vdot0x23** [authelia/authelia#1144]
Some users may prefer plaintext.

I am willing to implement this :)

**Comment by clems4ever** [comment]
I'm ok with the minimalist email for security purists.

**Comment by james-d-elliott** [comment]
Sounds good to me too. I don't have a whole lot of time, but if you need any help I'll attempt to keep an eye on this issue. I did a lot of work on SMTP. 

Additionally I think if we implement plaintext emails it logically should be the only method used by the filesystem mail provider.

**Comment by clems4ever** [comment]
> Additionally I think if we implement plaintext emails it logically should be the only method used by the filesystem mail provider.

I agree, we can certainly factorize.

**Comment by james-d-elliott** [comment]
@vdot0x23 feel free to try the authelia/authelia:feature-smtp-plaintext-emails image. It will send a multipart alternative email with both html and text portions. Additionally you can completely disable the HTML emails with the configuration option:
```yaml
notifier:
  smtp:
    disable_html_emails: true
```
