### ISSUE TITLE
authentication_traces: second factor authentication (and IPs) not logged

### ISSUE THREAD

**Issue by n4kre** [authelia/authelia#116]
Hi,

If I'm not mistaken, the second factor authentication is not logged.
Maybe it would be a good idea to replace “isAuthenticationSuccessful” by two distincts fields – one for each factor.
What's more, logging IP addresses would also be interesting, both for log analysis/forensics in a SIEM. and to trap bruteforce attempts.
My point is that bruteforce prevention could also be based on the originating IP address, rather than the username: as of now, if user `foobar` is subject to a bruteforce attack, it may be unable to *legitimately* log in – denial of service risk.

**P.-S.:** If anyone is interested in on how to prevent bruteforce attacks against Authelia's login page, one solution is to use Fail2Ban, with the following filter.
```fail2ban-filter
[Definition]

failregex = ^<HOST> -.*\] "POST /api/firstfactor.* HTTP/\d+\.\d+" [54]\d\d .*$
            ^<HOST> -.*\] "POST /api/totp.* HTTP/\d+\.\d+" 5\d\d .*$

ignoreregex =
```

This filter can be applied on an Nginx access log (default log format) dedicated to Authelia (to prevent false positives).

**Comment by clems4ever** [comment]
Nice! Good idea to use fail2ban to prevent bruteforce. I will definitely put it in the README.

**Comment by clems4ever** [comment]
You are right, second factor is not logged because I think the biggest threat is at first factor step.  But yes, it can be safer to regulate on second factor as well and that's why I put low priority on this issue.

For the IP part, I think Fail2ban is a better solution than implementing something at Authelia's level since it allows Authelia not to handle all the pressure of a DDOS from the same IP. I think it's better if caught early in the stack.

**Comment by n4kre** [comment]
I totally agree with you: dedicated solutions like Fail2Ban should handle this, not Authelia.

However, to “feed” solutions like Fail2Ban, “accurate” log files are required, to minimize the number of false positives or false negatives. Therefore, relying on Nginx log file is definitely not the best option, for at least three reasons:
• in case the Nginx server providing access to Authelia's backend does not have a dedicated log file, such a Fail2Ban filter may trigger false positives – e.g., considering another site being served by Nginx and which logfile is shared with Authelia (default is `/var/log/nginx/access.log` for every server), then if somebody sends an HTTP `POST /api/firstfactor` and which results in an HTTP error 4xx, the Fail2Ban would match.
• a `POST /api/firstfactor` to Authelia which results in an HTTP error 500, does not ensure 100% it was actually a login attempt – an error 500 may be sent back to the client for plenty of other reasons (not necessarily by Authelia's backend: Nginx could do it, for some reason) –, for instance.
• it depends on Nginx log format

This is why I think Authelia should – itself – log information about the login attempts (succes or failure, for both factors, and corresponding IPs), because there wouldn't be therefore any ambiguity on what actually happened. Provided directly by Authelia, such login details would be “reliable”.

Furthermore, not only such information is important for bruteforce prevention, but it is actually very important for audit purposes and forensics – it would be very useful to feed a SIEM (e.g., Splunk) with such logs.

**Comment by clems4ever** [comment]
Hello @n4kre , 
I see your points and I have a good news for you. I improved the logs with #125. Now we can clearly track a session, a request and an IP since each of them are now logged for each log message. I think it will help fail2ban to track potential attackers. 
Login attempts are not yet logged though but I can definitely do it. I'll update the thread once done.

Thanks.

**Comment by n4kre** [comment]
Thank you @clems4ever!

As you suggest, It would be nice to be able to track login attempts, maybe in a less verbose way (for a log level greater than or equal to `info`) – e.g., `<Date> - <IP> - <Username> - <Password|TOTP|U2F> validation: <success|failure>` –, and in to a dedicated log file, which path is customizable in Authelia's configuration file.

**Comment by n4kre** [comment]
In the same way, logging password reset and second factor registration request is a good idea – to prevent bruteforce and thus avoid mailboxes from being floode (potentially resulting in a denial of service).
