### ISSUE TITLE
OTP always wrong

### ISSUE THREAD

**Issue by sparx82** [authelia/authelia#1161]
Hi

I have a setup where Authelia is running in a docker container behind a Nginx proxy. This setup used to work fine before I pulled the latest authelia docker image. After the break with the config file in 4.20.0 (which is the version I'm using) I had to newly configure it and it is now starting up again finde. BUT: It always says my "One-time password might be wrong". I'm using Google Authenticator for that. I'm also using the YAML file for user database and a file for DB file storage

What I haver tried so far:
- Remove the DB file for a fresh start
- Log-In
- Register a new Google Authenticator instance
- And now it just doesn't work and always says that the OTP might be wrong. And no matter when within the lifetime of a OTP I'm trying.

Error message in the console is the following:

time="2020-06-26T10:38:14Z" level=error msg="Wrong passcode during TOTP validation for user xyz" method=POST path=/api/secondfactor/totp remote_ip= x.x.x.x

stack="github.com/authelia/authelia/internal/middlewares/authelia_context.go:64
(*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/handlers/response.go:94
handleAuthenticationUnauthorized\ngithub.com/authelia/authelia/internal/handlers/handler_sign_totp.go:36
SecondFactorTOTPPost.func1\ngithub.com/authelia/authelia/internal/middlewares/require_first_factor.go:15
RequireFirstFactor.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49
AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.2.2/router.go:348
(*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14
LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.14.0/server.go:2162
(*Server).serveConn\ngithub.com/valyala/fasthttp@v1.14.0/workerpool.go:223
(*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.14.0/workerpool.go:195
(*workerPool).getCh.func1\nruntime/asm_amd64.s:1373
goexit"

Any idea how I could get it working again?

BR,
Oliver

**Comment by clems4ever** [comment]
Hello @sparx82 , please check your clocks (computer running Authelia and mobile device) and make sure they are correctly synchronized.

**Comment by sparx82** [comment]
Indeed, 2 minutes apart. Synching the time solved the problem. Thanks very much!

**Comment by clems4ever** [comment]
Good, no problem. Cheers!

**Comment by lapd-viosoft** [comment]
Hello,
I got the same issue. Our users live on different timezone with Authelia instance. On the machine to run Authelia instance, I did get the host machine Time zone and pass it to Authelia docker instance via TZ variable.
Can you please tell me, how to sync timezone for this case?
Thank you!

**Comment by james-d-elliott** [comment]
> 
> 
> Hello,
> I got the same issue. Our users live on different timezone with Authelia instance. On the machine to run Authelia instance, I did get the host machine Time zone and pass it to Authelia docker instance via TZ variable.
> Can you please tell me, how to sync timezone for this case?
> Thank you!

The timezone should not affect this, can you confirm the time on the server and client matches to the second accounting for timezone? i.e. after converting it. One option to confirm if this behavior is to adjust the skew as per the documentation (I would recommend setting this to 3 for testing but 1 in production, which will mean in testing you have 90 seconds either side of the change point for a TOTP code to be valid in testing, and 30 seconds in production: https://www.authelia.com/docs/configuration/one-time-password.html#period-and-skew

**Comment by lapd-viosoft** [comment]
Hi James,
Thank for you reply. I have tried to change skew even to 10 but the issue is still remain
```yaml
# Authelia uses time-based one-time-passwords (TOTP).
# https://www.authelia.com/docs/configuration/one-time-password.html
totp:
  issuer: demo.site.com
  period: 30
  skew: 10
````

**Comment by lapd-viosoft** [comment]
Hi James,
After changing skew to 2000, it works. But this value is not expected for production environment :( 
(My timezone is ahead 14 hours to the server)

**Comment by james-d-elliott** [comment]
> 
> 
> Hi James,
> After changing skew to 2000, it works. But this value is not expected for production environment :(
> (My timezone is ahead 14 hours to the server)

I cannot replicate this at all. I changed my timezone on my phone to over 20 hours outside of my timezone, restarted the phone, attempted to authenticate and was successful.

TOTP relies on your time being accurate to be able to determine the seconds since the unix epoch or POSIX time. This is how Authelia calculates the validity of a TOTP pin. If your timezone is not set correctly it will not affect it unless your clock is not synced with a timeserver or your clock is not within 30 seconds of a valid time for the timezone.

It's possible the TOTP authenticator app you're using is not RFC6238 compliant, or something else is happening. If you can't figure out what's causing this from the information provided, can you please open another issue with replication steps including the application you're using and the exact time of the server and the client at a specific moment in time, as well as the associated timezones? This way we can accurately determine what's going on. The exact time of both the server and the client and their timezones are important for calculating what's actually going on.

**Comment by lapd-viosoft** [comment]
Hi James,
Thank you for your support.
There could be something wrong on my server. The issue is no longer happen when I switch to new server to deploy Authelia.

**Comment by cellulosa** [comment]
same here, I had to add:

```
totp:
  skew: 20000
```

to make it work

**Comment by Crowley723** [comment]
> same here, I had to add:
> 
> ```
> totp:
>   skew: 20000
> ```
> 
> to make it work.
> 
> Could it be because my server is on a different country with a different timezone? 

The timezone shouldn't affect this.

Have you verified that the server has the correct time? You can also try setting the ntp setting in the configuration.yaml to have authelia sync it's time. https://www.authelia.com/configuration/miscellaneous/ntp/

**Comment by cellulosa** [comment]
> The timezone shouldn't affect this.
> 
> Have you verified that the server has the correct time? You can also try setting the ntp setting in the configuration.yaml to have authelia sync it's time. https://www.authelia.com/configuration/miscellaneous/ntp/


Mh maybe there was something wrong with my docker instance? Anyway I added these two volumes to the `docker-compose.yml` for Authelia and OTP started working again without the need to set any `skew`:

```yml
services:
  authelia:
    image: docker.io/authelia/authelia:latest
    ...
    volumes:
      ...
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```
