### ISSUE TITLE
Any experience using Synology's LDAP Server with Authelia

### ISSUE THREAD

**Issue by Derever** [authelia/authelia#1175]
Hi. I would like to use **Synology's LDAP Server** ([https://www.synology.com/en-global/knowledgebase/DSM/help/DirectoryServer/ldap_desc](url)) for Authelia. Does anyone have experience in this matter? I'm always getting the error:

**level=error msg="config key not expected: authentication_backend.ldap.display_name_attribute"**

 I'm using this backend config but cant get it to work. 

> authentication_backend:
  disable_reset_password: false
  ldap:
    url: ldap://MY_SERVER_IP
    skip_verify: false
    base_dn: dc=LDAP
    username_attribute: uid
    additional_users_dn: ou=users
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectclass=groupOfNames))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    user: uid=root,cn=users,dc=LDAP
    password: MY_PASSWORD

**Comment by nightah** [comment]
@Derever the error isn't related to your Synology LDAP Server, that erorr is because you likely are not running the latest version of the binary/container.

Make sure you are running 4.21.0 to prevent that issue.

**Comment by Derever** [comment]
That was it!! Thanks a lot @nightah!!
