### ISSUE TITLE
Add fail2ban filter(s) in the documentation

### ISSUE THREAD

**Issue by alexw1982** [authelia/authelia#1176]
while authelia's restriction functions blocks users for a certain amount of time from retrying to login it does not prevent an IP to try a different username and password. This could result in unnecessary (and preventable) hammering of the application with login requests (3 per user x unlimited number of users)

fail2ban would be perfect to ban the IP on a ip tables level. Unfortunately I lack the skills (python regex) to create the appropriate filter.
fail2ban would simply monitor the log (either file or syslog) for failed logins and failed totp entries and ban the IP after x amounts of tries.
Should be pretty straight forward (in theory).

has anybody by any chance already created such as fail2ban filter or could create the appropriate regex lines?

**Comment by davama** [comment]
There used to be a fail2ban section in the docs...i cant find it now.
Would be good to see

**Comment by eklee** [comment]
I couldn't find it in the doc either, but here's a filter that should work (put in /etc/fail2ban/filter.d, then set it up in jail.local):

[Definition]
failregex = .*Error while checking password for.*remote_ip=<HOST> stack.*
            .* is banned until .*remote_ip=<HOST> stack.*
            .*Credentials are wrong for user .*remote_ip=<HOST> stack.*

**Comment by davama** [comment]
@eklee  thanks!

Possible put back in the doc?

**Comment by alexw1982** [comment]
I will work out a complete config (incl. content for jail.local and the filter) and will post it later for the doc...

**Comment by alexw1982** [comment]
This is my working config:

the filter is still missing other 2nd factor failures (duo and keys) as do not have that set up to create the log lines. If somebody can add that it would be great.

filter ( create as /etc/fail2ban/filter.d/authelia.conf)
```
# Fail2Ban filter for Authelia

# Make sure that the HTTP header "X-Forwarded-For" received by Authelia's backend
# only contains a single IP address (the one from the end-user), and not the proxy chain
# (it is misleading: usually, this is the purpose of this header).


[Definition]

# this counts every failed login (wrong username or password) and failed TOTP entry as a failure
failregex = ^.*Error while checking password for.*remote_ip=<HOST> stack.*
            ^.*Credentials are wrong for user .*remote_ip=<HOST> stack.*
            ^.*Wrong passcode during TOTP validation.*remote_ip=<HOST> stack.*
            # this would also count ever ban (as a result of too many failed logins as a failure) - remove # at beginning of the next line to enable
            #^.* is banned until .*remote_ip=<HOST> stack.*


# we can ignore debug, info and warning messages as all authentication failures are flagged as level=error by Authelia
ignoreregex = ^.*level=debug.*
              ^.*level=info.*
              ^.*level=warning.*
```
Paste this into  /etc/fail2ban/jail.local (if the file does not exist, create it)
```
# adopt logpath according to your log location
# remove chain line if you are not running Authelia in a docker container
# adapt maxretry, bantime and findtime to your needs
[authelia]
enabled = true
port = http,https,9091
filter = authelia
logpath = /path/to/authelia.log
maxretry = 3
bantime = 1d
findtime = 1d
chain = DOCKER-USER
```

Remeber to restart fail2ban after making those changes and verify that everything is working

**Comment by clems4ever** [comment]
@alexw1982 , you can create a PR to add it to the doc and explain what is currently supported and what is not. Other people will be able to extend the doc later and add more use cases.

I suggest you create a doc under https://www.authelia.com/docs/community/ for the time being.

**Comment by bbrendon** [comment]
How would this work when running authelia in docker? fail2ban runs on the parent host from my experience and the logs are not available.

**Comment by alexw1982** [comment]
I am running this with authelia in a docker container. Simply mount a host directory to the container and have authelia log into a file in this directory. Then put that file path in the fail2ban configuration posted above

**Comment by davama** [comment]
@alexw1982 
Trying to understand this fail2ban config that you posted....

Cant seem to get this to work...fail2ban does not ban, nor do I see any logs in fail2ban.log indicating that. The jail is created, I can see the fail2ban jail too..

Also the filter says ignore `:debug :info :warning` which are log levels in the authelia config... **so what log level should authelia be?** I placed it in `trace` since `warn` no longer exist, looks like...

Tried slight adjustments to the jail:
```
[DEFAULT]
destemail = <myemail>
sendername = Fail2Ban
mta = mail
action = %(action_mwl)s
banaction = firewallcmd-ipset


# adapt logpath according to your logfile location (or to systemd)
# remove line "chain = DOCKER-USER" if you are not running Authelia in a docker container
# adapt maxretry, bantime and findtime according to your needs
[authelia]
enabled = true
filter = authelia
port = http,https,9091
findtime = 3600
logpath = /var/log/authelia/authelia.log
maxretry = 6
bantime = 1d
```
But still no banning.... :disappointed: 

Any input is appreciated!

**Comment by bbrendon** [comment]
I was trying to figure this out.... Googled around a bit and I think I found a gem.

https://chlee.co/how-to-secure-and-protect-nginx-on-linux-with-fail2ban/

I'm going to have to get back to it later but I think that article will shortcut a solution.

**Comment by davama** [comment]
Update:
Got it working!!

Found the issue as i was testing the filter with `fail2ban-regex`

Had to remove the comment lines from `failregex` in the filter:
```
# this counts every failed login (wrong username or password) and failed TOTP entry as a failure
# this would also count ever ban (as a result of too many failed logins as a failure) - remove # at beginning of the next line to enable
#^.* is banned until .*remote_ip=<HOST> stack.*
failregex = ^.*Error while checking password for.*remote_ip=<HOST> stack.*
            ^.*Credentials are wrong for user .*remote_ip=<HOST> stack.*
            ^.*Wrong passcode during TOTP validation.*remote_ip=<HOST> stack.*

```
Then:

```
2020-08-13 15:47:15,351 fail2ban.filter         [10864]: INFO    [authelia] Found x.x.x.x - 2020-08-13 15:47:14
2020-08-13 15:47:22,565 fail2ban.filter         [10864]: INFO    [authelia] Found x.x.x.x - 2020-08-13 15:47:21
2020-08-13 15:47:22,691 fail2ban.actions        [10864]: NOTICE  [authelia] Ban x.x.x.x
```

And the client could not access the site!
yay!

**Comment by GeoCookie** [comment]
Hi there,

It works for me too. Thank you @davama!

**Comment by alexw1982** [comment]
sorry - my bad. I did not test the filter again after adding the comments...

**Comment by davama** [comment]
@clems4ever 
Would you welcome this in the doc?

**Comment by alexw1982** [comment]
I added a PR for the documentation...

**Comment by davama** [comment]
@alexw1982 
Thanks!
#1344

**Comment by wmd1942** [comment]
For me, the fail2ban was installed directly in ubuntu (not with container). The working filter is:

[Definition]
failregex = ^.*Unsuccessful.*authentication attempt.*remote_ip= stack
ignoreregex =

You can always test your filter with fail2ban-regex command:

fail2ban-regex "log-file-name" "filter-file-name"

My problem is authelia (one of containers) log file always shows the remote address 127.20.0.1, which is the docker's gateway address. It looks like Nginx Proxy Manger (one of containers) didn't forward the read IP to authelia. Has anybody seen this? What's the solution?

**Comment by tduong-cloud** [comment]
> For me, the fail2ban was installed directly in ubuntu (not with container). The authelia is one of the containers behind NPM (Nginx Proxy Manger, another container). I have 2FA enabled for all logins. I tested on both 1FA/2FA failed login and the working filter is:
> 
> [Definition] failregex = ^.*Unsuccessful.*authentication attempt.*remote_ip=<HOST> stack ignoreregex =
> 
> You can always test your filter with fail2ban-regex command:
> 
> fail2ban-regex "log-file-name" "filter-file-name"
> 
> My problem is authelia log file always shows the remote address 127.20.0.1, which is the docker's gateway address. It looks like NPM didn't forward the read IP to authelia. Has anybody seen this? What's the solution?

Hi, you need to have NPM installed in  network host mode so it cas forward the real IP to authelia.
