### ISSUE TITLE
public.example.com/static/js/ directory listable

### ISSUE THREAD

**Issue by alexw1982** [authelia/authelia#1178]
I ran a security scan with detectify and it flagged the listed potential risk below. Question is if the visibility of the directory content is necessary for authelia to work.

![authelia_1](https://user-images.githubusercontent.com/11628284/86578359-fd504400-bf7b-11ea-80e6-4d66fbfebde1.PNG)
![authelia_2](https://user-images.githubusercontent.com/11628284/86578362-fe817100-bf7b-11ea-8b06-4f0a16a480db.PNG)

**Comment by nightah** [comment]
The files specified are part of Authelia's javascript frontend, so yes you will need those files for Authelia to work.

I've never used detectify but it sounds like it arbitrarily marks any javascript as a potential risk?

**Comment by alexw1982** [comment]
It does not any flag any JS file but any directory that is fully listable. That was the point I was hinting at. Obviously you need the files...

**Comment by nightah** [comment]
I don't really see how a directory that is fully listable is a potential risk though.

Either way the directory listed is an embedded filesystem that's served directly from within the compiled Go binary and is necessary for Authelia to operate.

**Comment by alexw1982** [comment]
ok - I just wanted to raise the point. I am by no means an expert. Closing topic.
