### ISSUE TITLE
doesn't listen on IPv6

### ISSUE THREAD

**Issue by mbunkus** [authelia/authelia#1189]
authelia only listens on IPv4 addresses:

1. Setting `host: "::1"` or `host: "[::1]"` yields an error message about those addresses being invalid for IPv4.
2. Using `host: localhost` works but only listens on IPv4, even if `localhost` resolves to `::1`, too.
3. Using `host: "*"` (which several other programs use for indicating to listen on any address) doesn't work either due to "listen tcp4: lookup *: no such host".

Interesting enough authelia can connect to other services via IPv6 just fine. For example, the PostgreSQL and SMTP connections connect via IPv6 if the provided host name has an AAAA record.

**Comment by nightah** [comment]
Thanks for the report @mbunkus looks like fasthttp by default only listens on ipv4.

I've got a working change for IPv6 which I'll submit shortly.

**Comment by mbunkus** [comment]
Nice! Thanks!
