### ISSUE TITLE
Allow pasting TOTP token

### ISSUE THREAD

**Issue by Ambroisie** [authelia/authelia#1206]
I use a password manager with TOTP integration: when it fills my login information, it fills my clipboard with the TOTP token.

However I cannot paste the TOTP token directly onto Authelia's field, as the JS seem to only allow entering the first character of the token each time I try to paste it.

**Comment by nightah** [comment]
@Ambroisie Authelia does support pasting the TOTP code in the browser.
We had a similar report once before #952 

I'd suggest you turn off all of your extensions and just try copy and paste from the clipboard first to rule them out.
Then maybe try turn on your extensions one at a time probably starting with your password manager to find the actual cause of the issue.

**Comment by Ambroisie** [comment]
@nightah sorry I had not noticed that this issue was open beforehand, I'd have tried deactivating my extensions.

For future reference, it was Greasemonkey that caused the issue for me. More specifically it seems that a script to forcefully enable right-click copy and paste was interfering with Authelia.

**Comment by nightah** [comment]
@Ambroisie no problems, glad it was something simple and easily identifiable.
