### ISSUE TITLE
Getting Error:  "panic: Unable to parse hash of user admin"

### ISSUE THREAD

**Issue by rshamsz** [authelia/authelia#1222]
**I am using docker on a Centos host and gets the following error right after the docker is created, attached is the [configuration.yml which looks OK to me, maybe I am missing something**]

> goroutine 1 [running]:
> 
> 
> github.com/authelia/authelia/internal/authentication.NewFileUserProvider(0xc0000a6880, 0xb)
> 
> 
> 	github.com/authelia/authelia/internal/authentication/file_user_provider.go:62 +0x52e
> 
> 
> main.startServer()
> 
> 
> 	github.com/authelia/authelia/cmd/authelia/main.go:63 +0x9d3
> 
> 
> main.main.func1(0xc0000c8000, 0xc0001fc040, 0x0, 0x2)
> 
> 
> 	github.com/authelia/authelia/cmd/authelia/main.go:121 +0x20
> 
> 
> github.com/spf13/cobra.(*Command).execute(0xc0000c8000, 0xc00009a160, 0x2, 0x2, 0xc0000c8000, 0xc00009a160)
> 
> 
> 	github.com/spf13/cobra@v0.0.7/command.go:842 +0x29d
> 
> 
> github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c8000, 0xc00073ff58, 0x4, 0x4)
> 
> 
> 	github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
> 
> 
> github.com/spf13/cobra.(*Command).Execute(...)
> 
> 
> 	github.com/spf13/cobra@v0.0.7/command.go:883
> 
> 
> main.main()
> 
> 
> 	github.com/authelia/authelia/cmd/authelia/main.go:138 +0x166
> 
> 
> time="2020-07-22T21:07:42-04:00" level=info msg="Logging severity set to debug"
> 
> 
**> panic: Unable to parse hash of user admin: Hash key is not the last parameter, the hash is likely malformed (1234567)**

[configuration.txt](https://github.com/authelia/authelia/files/4967294/configuration.txt)

authelia:
    container_name: authelia
    # Check this before upgrading: https://github.com/authelia/authelia/blob/master/BREAKING.md
    # image: authelia/authelia:latest
    image: authelia/authelia:4.21.0
    restart: always
    networks:
      t2_proxy:
        ipv4_address: $AUTHELIA_IP_INTERNAL #192.168.90.200
    ports:
     - "$AUTHELIA_PORT:9091"
    volumes:
      - $USERDIR/authelia:/config
    environment:
      - TZ=$TZ

**Comment by nightah** [comment]
@rshamsz the error is suggesting that there's an issue with your users database `/config/users_database.yml`, can you please share the contents of this file?

**Comment by rshamsz** [comment]
How silly of me, totally forgot about that file; There was no hashed password for user admin. It is good now.
Thanks
