### ISSUE TITLE
Authelia crashing during login

### ISSUE THREAD

**Issue by chris13524** [authelia/authelia#1234]
When I click to login, Authelia logs this:

```
time="2020-07-25T16:04:16Z" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=xxx.xxx.xxx.xxx
```

But then after a variable amount of time (seems to be anywhere from 10-30 seconds) Authelia stops and my reverse proxy (Traefik) logs `'502 Bad Gateway' caused by: EOF`. Authelia logs nothing of the issue, even when in log_level trace, and just stops. (i.e. the "Request hit" log entry is the last thing I see before `kubectl logs -f` exits)

Obviously I am not seeing [this](https://github.com/authelia/authelia/blob/e43bc93047d4de5c049dd14ca7af297a70afda74/internal/handlers/handler_firstfactor.go#L37) log event, so I'm guessing this issue must happen in or before [`delayToPreventTimingAttacks`](https://github.com/authelia/authelia/blob/e43bc93047d4de5c049dd14ca7af297a70afda74/internal/handlers/handler_firstfactor.go#L70). Not a Go master, however :)

I have a relatively simple deployment: single user in a file auth backend, no second factors. It's deployed on k8s.

**Comment by james-d-elliott** [comment]
What authentication method are you using? File based or LDAP? I'm guessing file and using argon2id?

The argon2id provider will by default use 1GB of RAM for password generation. This means you should allow for at least this amount in your deployment/daemonset spec and have this much available on your node. I would recommend using LDAP as an auth backend if at all possible. I use ActiveDirectory, but @nightah uses an OpenLDAP provider, and here is a k8s helm chart: https://github.com/helm/charts/tree/master/stable/openldap

**Comment by chris13524** [comment]
I'm using file & argon2id. Indeed, looks like it was OOMing.

Switched to LDAP, and while a large learning curve, I think it'll pay off.

Thanks!

**Comment by james-d-elliott** [comment]
@chris13524 for reference you can alternatively use sha512 or tweak the memory usage of argon, but I agree that it will pay off. Not sure why I didn't mention this.

**Comment by gurre** [comment]
I hit this one too. Reserving 1gb of ram for a go application is not very common.

**Comment by chris13524** [comment]
@gurre Agreed, this should be mentioned somewhere. See #1252

**Comment by nightah** [comment]
@chris13524 and @gurre it is mentioned [here](https://www.authelia.com/docs/configuration/authentication/file.html#password-hash-algorithm) which is the documentation respective to you type of configuration.

Having said that we will review your PR accordingly, thanks!

**Comment by james-d-elliott** [comment]
Also to note, it's Go's lib that implements memory management in this way. We chose 1GB based on the article linked by Amir.

**Comment by gurre** [comment]
The key point to put in the docs is that authelia requires at least 1gb of ram using default settings.

As with many orchestration tools you configure with a set amount of ram for your container.

**Comment by chris13524** [comment]
I figure having more information is always better, and since the K8s page is under-construction there could be a section to just put notes on things people are figuring out for k8s usage. Once there is an official k8s Helm chart or something, these notes could, of course, be deleted.
