### ISSUE TITLE
Integrating into JavaScript/React Project | Latest npm version is 3.16.2

### ISSUE THREAD

**Issue by KeithSSmith** [authelia/authelia#1237]
What is the recommended approach to integrating Authelia authentication with a Java Script/React app?

When I search on npm it seems like the last available package is very old (3.16.2) - https://www.npmjs.com/package/authelia

Also, there isn't much in the way of documentation on this topic so not clear if it is supported or not. Looks like it might require the use of `useAutheliaState` but not sure where to start.

**Comment by clems4ever** [comment]
Hello @KeithSSmith , I think you misunderstood what is Authelia. It's a reverse proxy companion, not a library. It's not meant to be integrated into your applications but rather be deployed independantly and control access to your application. Please check the documentation: https://www.authelia.com/docs/.
