### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Muwahhidun** [authelia/authelia#1240]
I set up authelia, and I understood how it works. But there is a snag.

https://auth.mydomain.ru/?rd=http://deluge.mydomain.ru/

If I give a link to someone, for example radarr.myDomain.ru. THEN this person has an error 403. In the address bar, it can be seen that the redirect gives the authorization address of the hostel + secure point, but the address of the secure point does not come out 'https', but 'http'. To avoid this, he needs to first go through the authorization of the network, then the cookies are saved, and the errors are also ok.
Or he can manually attribute the letters 'S', go through authorization, and also, after saving cookies, there will be no 403 error in the future.

How to make it do the right redirect and return?
https://auth.mydomain.ru/?rd=httpS://deluge.mydomain.ru/

**Comment by nightah** [comment]
The redirect parameter `?rd=...` is constructed based on the site that was originally visited.

This means that even if a user is not authenticated with Authelia and they visit `https://deluge.mydomain.ru/` then they will be sent to `https://auth.mydomain.ru/?rd=https://deluge.mydomain.ru/`.

I believe you are using Traefik, is that right?

If so you can turn on [global http -> https redirection](https://docs.traefik.io/routing/entrypoints/#redirection) if you're using > v2.2, which also are included in our [documented example](https://www.authelia.com/docs/deployment/supported-proxies/traefik2.x.html#docker-composeyml):
```yml
      - '--entrypoints.http.http.redirections.entrypoint.to=https'
      - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
```

Or individual [redirection middlewares](https://docs.traefik.io/middlewares/redirectscheme/#scheme).

**Comment by Un1QExit** [comment]
But, if t use NPM? how i can change config?

location /authelia {
    internal;
    set $upstream_authelia http://192.168.31.100:9091/api/verify;
    proxy_pass_request_body off;
    proxy_pass $upstream_authelia;    
    proxy_set_header Content-Length "";

    # Timeout if the real server is dead
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
    client_body_buffer_size 128k;
    proxy_set_header Host $host;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr; 
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_redirect http:// $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;

    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}

    location / {
        set $upstream_lidarr http://192.168.31.100:8686;
        proxy_pass $upstream_lidarr;
		
		auth_request /authelia;
		auth_request_set $target_url $scheme://$http_host$request_uri;
		auth_request_set $user $upstream_http_remote_user;
		auth_request_set $groups $upstream_http_remote_groups;
		proxy_set_header Remote-User $user;
		proxy_set_header Remote-Groups $groups;
		error_page 401 =302 https://authelia.myunraid.ru/?rd=$target_url;
		
		client_body_buffer_size 128k;

		proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

		send_timeout 5m;
		proxy_read_timeout 360;
		proxy_send_timeout 360;
		proxy_connect_timeout 360;

		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-Host $http_host;
		proxy_set_header X-Forwarded-Uri $request_uri;
		proxy_set_header X-Forwarded-Ssl on;
		proxy_redirect  http://  $scheme://;
		proxy_http_version 1.1;
		proxy_set_header Connection "";
		proxy_cache_bypass $cookie_session;
		proxy_no_cache $cookie_session;
		proxy_buffers 64 256k;

		set_real_ip_from 192.168.1.0/16;
		real_ip_header X-Forwarded-For;
		real_ip_recursive on;
    }

**Comment by Muwahhidun** [comment]
I am using NPM.

My config in NPM.

1) for Authelia: 
![1-1](https://user-images.githubusercontent.com/68441226/88792694-4f177300-d1a4-11ea-9391-bdb74875b0ef.jpg)
![2-2](https://user-images.githubusercontent.com/68441226/88792707-5474bd80-d1a4-11ea-873f-ce06a4bcd873.jpg)
![3-3](https://user-images.githubusercontent.com/68441226/88792714-58084480-d1a4-11ea-9a66-e58e341c390e.jpg)
in advace full config:
```
    location / {
        set $upstream_authelia http://192.168.1.7:9091; # This example assumes a Docker deployment 
        proxy_pass $upstream_authelia;
		client_body_buffer_size 128k;

		#Timeout if the real server is dead
		proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

		# Advanced Proxy Config
		send_timeout 5m;
		proxy_read_timeout 360;
		proxy_send_timeout 360;
		proxy_connect_timeout 360;

		# Basic Proxy Config
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-Host $http_host;
		proxy_set_header X-Forwarded-Uri $request_uri;
		proxy_set_header X-Forwarded-Ssl on;
		proxy_redirect  https:// $scheme://;
		proxy_http_version 1.1;
		proxy_set_header Connection "";
		proxy_cache_bypass $cookie_session;
		proxy_no_cache $cookie_session;
		proxy_buffers 64 256k;

		# If behind reverse proxy, forwards the correct IP
		set_real_ip_from 10.0.0.0/8;
		set_real_ip_from 172.0.0.0/8;
		set_real_ip_from 192.168.0.0/16;
		set_real_ip_from fc00::/7;
		real_ip_header X-Forwarded-For;
		real_ip_recursive on;
    }
```

for PROTECT POINT:
![1](https://user-images.githubusercontent.com/68441226/88792899-a9183880-d1a4-11ea-9308-0a568a78a20c.jpg)
![2](https://user-images.githubusercontent.com/68441226/88792905-aa496580-d1a4-11ea-86ac-dff880a6da71.jpg)
![3](https://user-images.githubusercontent.com/68441226/88792908-aa496580-d1a4-11ea-88bc-bbe400c20b3b.jpg)
in advace full config:

```
location /authelia {
    internal;
    set $upstream_authelia http://192.168.1.7:9091/api/verify;
    proxy_pass_request_body off;
    proxy_pass $upstream_authelia;    
    proxy_set_header Content-Length "";

    # Timeout if the real server is dead
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
    client_body_buffer_size 128k;
    proxy_set_header Host $host;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr; 
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_redirect  httpd:// $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;

    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}

    location / {
        set $upstream_deluge http://192.168.1.7:8112;
        proxy_pass $upstream_deluge;
		
		auth_request /authelia;
		auth_request_set $target_url $scheme://$http_host$request_uri;
		auth_request_set $user $upstream_http_remote_user;
		auth_request_set $groups $upstream_http_remote_groups;
		proxy_set_header Remote-User $user;
		proxy_set_header Remote-Groups $groups;
		error_page 401 =302 https://auth.MYDOMAIN.ru/?rd=$target_url;
		
		client_body_buffer_size 128k;

		proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

		send_timeout 5m;
		proxy_read_timeout 360;
		proxy_send_timeout 360;
		proxy_connect_timeout 360;

		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-Host $http_host;
		proxy_set_header X-Forwarded-Uri $request_uri;
		proxy_set_header X-Forwarded-Ssl on;
		proxy_redirect  https:// $scheme://;
		proxy_http_version 1.1;
		proxy_set_header Connection "";
		proxy_cache_bypass $cookie_session;
		proxy_no_cache $cookie_session;
		proxy_buffers 64 256k;

		set_real_ip_from 192.168.1.0/16;
		real_ip_header X-Forwarded-For;
		real_ip_recursive on;

    }
```

**Comment by Muwahhidun** [comment]
> fsdfsdfsd

**Comment by Un1QExit** [comment]
> > fsdfsdfsd

хватит спамить)

**Comment by Muwahhidun** [comment]
I took the configs here https://github.com/ibracorp/authelia

**Comment by nightah** [comment]
So this is the important part in the configuration:

```nginx
auth_request_set $target_url $scheme://$http_host$request_uri;
error_page 401 =302 https://auth.MYDOMAIN.ru/?rd=$target_url;
```

This constructs the redirect link, as you can see there it is constructing it based on the scheme that the user is visiting the site on.
Which means that a redirect from http -> https isn't happening before it reaches Authelia.

In our examples you can see how this redirect is achieved [here](https://www.authelia.com/docs/deployment/supported-proxies/nginx.html#protected-endpoint) for the protected endpoint:

```nginx
server {
    server_name nextcloud.example.com;
    listen 80;
    return 301 https://$server_name$request_uri;
}
```

**Comment by dfortescue** [comment]
I have the same issue with NPM, just wondering would this solve it (change $scheme to https)?

`auth_request_set $target_url https://$http_host$request_uri;`

**Comment by Muwahhidun** [comment]
> I have the same issue with NPM, just wondering would this solve it (change $scheme to https)?
> 
> `auth_request_set $target_url https://$http_host$request_uri;`

It doesn't change anything. The problem remains. Apparently there is no solution to this problem yet.

**Comment by nightah** [comment]
> I have the same issue with NPM, just wondering would this solve it (change $scheme to https)?
> 
> `auth_request_set $target_url https://$http_host$request_uri;`

This will hardcode all requests to return `https` so it **should** work and is technically a workaround.
Ideally there should be a redirect from http -> https per the example provided in my last comment.

**Comment by nightah** [comment]
@Muwahhidun I'm closing this issue off since it's related specifically to NPM and not nginx.

If the configuration performs a http -> https redirection before authentication (like all the examples) this issue goes away.
I'd suggest an upstream ticket to NPM to see how this can be achieved or examining the output configuration to resolve.
