### ISSUE TITLE
haproxy on FreeBSD - Lua function 'auth-request': runtime error

### ISSUE THREAD

**Issue by djbobyd** [authelia/authelia#1247]
Hello,
I was very glad when I found your project. I was trying to get some form of 2FA on my OPNsense server using haproxy.
I read all the available documentation and created all config files. I have authelia running in a docker container and it is working fine. 
Unfortunately when I try to use it for authentication through the haproxy of my OPNsense firewall I got the following errors in the logs:

`haproxy[88090]: Lua function 'auth-request': runtime error: /usr/local/share/lua/5.3/socket/http.lua:116: bad argument #1 to 'settimeout' (number expected, got nil) from [C] field 'request', /tmp/haproxy/lua/5f0c562d689123.42728548.lua:86 C function line 44.`

And this error is repeating itself over and over.
I noticed that not all lua.socket versions are supported but since the one available in the FreeBSD is not listed I am not sure where the problem lies. 
here is some more info on the installed package

>lua53-luasocket-3.0.r1_5,1
Name           : lua53-luasocket
Version        : 3.0.r1_5,1
Installed on   : Fri Jul 31 14:11:12 2020 EEST
Origin         : net/luasocket
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : net
Licenses       : MIT
Maintainer     : lx@FreeBSD.org
WWW            : https://github.com/diegonehab/luasocket
Comment        : Socket support for the Lua language
Options        :
        DOCS           : off
        PIE            : on
        RELRO          : on
Shared Libs required:
        liblua-5.3.so
Annotations    :
        FreeBSD_version: 1201000
        flavor         : lua53
        repo_type      : binary
        repository     : OPNsense
Flat size      : 239KiB
Description    :
LuaSocket is a Lua extension library that provides support for the TCP and UDP
transport layers.
Extra Lua modules implementing SMTP, HTTP and FTP protocols are installed
to /usr/local/lib/lua/luasocket.
>WWW: https://github.com/diegonehab/luasocket

and this is the relevant section from haproxy.cfg:

>http-request set-header X-Forwarded-Host %[req.hdr(Host)]
    http-request set-header X-Forwarded-For %[src]
    http-request set-header X-Real-IP %[src]
    http-request add-header X-Forwarded-Port %[dst_port]
    http-request set-header X-Forwarded-URI %[path]%[var(req.questionmark)]%[query]
    http-request set-header X-Forwarded-Proto %[var(req.scheme)]
    http-request set-header X-Forwarded-URL %[var(req.scheme)]://%[base]%[var(req.questionmark)]%[query]
    http-request set-var(req.questionmark) str(?) if { query -m found }
    http-request lua.auth-request authelia /api/verify if acl_5d8e5955c45739.47559974
    http-response set-header Success %[var(txn.auth_response_code)]
    use_backend authelia if acl_5d8e5955c45739.47559974 !{ var(txn.auth_response_successful) -m bool }
>    use_backend %[req.hdr(host),lower,map_dom(/tmp/haproxy/mapfiles/5d8e5683b2e494.48239912.txt)] if acl_5d8e5955c45739.47559974

the names are  autogenerated by the haproxy UI in OPNsense but basically the ACLs match all hosts under my domain. I've also tried setting a response header to see if txn variable returns the correct value but unfortunately the header was empty.
Since I got out of ideas I am turning to you for some help.

Thanks you in advance, and thank you for making this project.

Best Regards,
Boby

**Comment by nightah** [comment]
@djbobyd looking at the ports package it doesn't appear to compile luasocket from HEAD @ master.
It utilises https://github.com/diegonehab/luasocket/releases/tag/v3.0-rc1 which does not have the commit that is required.

Not sure if you can petition upstream for a separate package that utilises HEAD @ master or the luasocket project to provide a new release.

Your alternative would be to compile the package from source yourself.

**Comment by djbobyd** [comment]
@nightah Thanks for your input. I will check what can be done. It is unfortunate that such changes are not available even with FreeBSD 12

**Comment by nightah** [comment]
@djbobyd I think you should be able to give this a try again when #1310 is merged if you're still interested.

**Comment by djbobyd** [comment]
Thanks a lot for your efforts!
I will test it as soon as I get some free time and get back to you.
