### ISSUE TITLE
Authelia TOTP mails contain no "Date" header field

### ISSUE THREAD

**Issue by Drakulix** [authelia/authelia#1262]
Mails send by authelia are getting rejected by my mail server with the standard configuration of [amavis-new](https://www.amavis.org/), because of `INVALID HEADER Missing required header field: "Date"`.

I do not think, that this is a configuration error on my side, but an issue of authelia, because [RFC 5322](https://tools.ietf.org/html/rfc5322#section-3.6) clearly states that "The only required header fields are the origination **date** field and the originator address field(s).  All other header fields are syntactically optional."

So IMO authelia should set the Date header.

**Comment by james-d-elliott** [comment]
Easily added. If you'd like to test it the authelia/authelia:feature-smtp-plaintext-emails docker image has the change.

**Comment by Drakulix** [comment]
Thanks for the quick fix!

I can confirm that authelia/authelia:feature-smtp-plaintext-emails works **and** that the date is in the correct timezone!
Is there any way to get notified, when this gets released, so I can switch back to a stable image tag?

**Comment by james-d-elliott** [comment]
I'll look at merging this in the coming days, this issue will also be closed once it's merged into the master tag, and it's only a matter of time before the release comes out. You can subscribe to notifications to #1266 for when it's released, you can also watch our repository for release notifications if you want at the top right (click watch -> releases only).
