### ISSUE TITLE
Non docker Nginx-Authelia connection

### ISSUE THREAD

**Issue by CMclarty** [authelia/authelia#1272]
Hi, thanks for the great work on authelia.

in my authelia.conf for my bare metal nginx I have the following line:

`        set $upstream_authelia http://172.20.0.3:9091;`

Unfortunately, the docker container for authelia changes on restarts. It would be great if the container mapped the port to localhost so I could use;

`        set $upstream_authelia http://localhost:9091;`

Apologies  if this is a ID10T error.

Also, I would suggest a slight rewording of the NGINX documentation to clarify the correct sequence, I would suggest something along the lines of:

>  The Authelia portal code should be saved as a virtual host and enabled, to provide the authentication portal at auth.example.com. authelia.conf, auth.conf and proxy.conf should be saved in your config folder. To protect a given site,  the _include /config/nginx/authelia.conf;_ directive should be used to activate the link to the portal, while _include /config/nginx/auth.conf;_ and _include /config/nginx/proxy.conf;_ directives should be used to protect a virtual domain, or included in a location block to protect a given location.

Just a suggestion, based on where I tripped up.

Thanks again,

**Comment by james-d-elliott** [comment]
Use docker host networking, and instead of listening on 0.0.0.0 listen on 127.0.0.1 should theoretically work.

**Comment by CMclarty** [comment]
Ah thanks, after an embarrassingly large amount of time spend fiddling, you can add the following section below the 'network' section in the docker-compose file to expose the port on localhost:

`    ports:
      - "9091:9091"`

**Comment by james-d-elliott** [comment]
Ah that's another alternative, good idea.
