### ISSUE TITLE
Support for newer haproxy-auth-request ?

### ISSUE THREAD

**Issue by sorano** [authelia/authelia#1273]
Greetings.

I'm wondering if there is any plan to support the new version of haproxy-auth-request that has replaced luasockets with haproxy-lua-http?

This would make it easier to run Authelia on platforms that has old luasockets in their package repos.

**Comment by nightah** [comment]
Thanks for the report @sorano, I'll try to make some time over this coming weekend to see what's involved in supporting this.

**Comment by sorano** [comment]
Sounds great @nightah 

For reference, this is the commit: https://github.com/TimWolla/haproxy-auth-request/commit/f5e7b395aa86050316e947147f5d66b20dcd8b1f

Ping me if you want help with testing

**Comment by TimWolla** [comment]
Hi :wave: While you are at it you might also be interested in this PR: https://github.com/TimWolla/haproxy-auth-request/pull/24. It automatically exposes all the response headers from the sub request, so there is no longer a need to patch the script to do so.

**Comment by nightah** [comment]
Thanks @TimWolla that's actually a super useful change!

I've just finished testing and making the required configuration changes to support the newer version, should see a PR shortly.

**Comment by sorano** [comment]
This is great news!

I'll give this a test once it gets merged.

**Comment by ntimo** [comment]
Already tested works like a charm 👍

**Comment by sorano** [comment]
> Already tested works like a charm 👍

Awesome. You're running OPNsense also right?
