### ISSUE TITLE
Always being redirected to default_redirection_url

### ISSUE THREAD

**Issue by ntimo** [authelia/authelia#1291]
Hello,
I am using HAProxy with the config below, when I log in I am always redirected to the url defined in `default_redirection_url`. And I don't really understand why? Can you maybe help me to debug the problem? I already tried to set the log mode to debug but that didn't helped in any way. 

HAProxy config:
```
  http-request set-var(req.scheme) str(https) if { ssl_fc }
  http-request set-var(req.scheme) str(http) if !{ ssl_fc }
  http-request set-var(req.questionmark) str(?) if { query -m found }
  http-request set-header X-Real-IP %[src]
  http-request set-header X-Forwarded-Proto %[var(req.scheme)]
  http-request set-header X-Forwarded-Host %[req.hdr(Host)]
  http-request set-header X-Forwarded-Port %[dst_port]
  http-request set-header X-Forwarded-Uri %[path]%[var(req.questionmark)]%[query]
  http-response set-header Server helloworld

  http-request set-header X-Original-URL %[var(req.scheme)]://%[req.hdr(Host)]
  acl protected-frontends hdr(host) -m reg -i ^(.*)\.example\.com
  http-request lua.auth-request auth.example.com /api/verify if protected-frontends
  use_backend auth.example.com if protected-frontends !{ var(txn.auth_response_successful) -m bool }
```

I followed this guide for setting up HAProxy:  https://www.authelia.com/docs/deployment/supported-proxies/haproxy.html and tried it with the `X-Original-URL` header set and unset both resulting in the same behaviour. 

Expected behaviour: I open webmail.example.com then login using credentials xy and stay on page webmail.example.com.

Thanks for your help.

**Comment by JulienSambre** [comment]
@ntimo Hi!

I have the exact same problem with a similar haproxy configuration : did you managed it? I've spent several hours onthis problem but found nothing ...

**Comment by nightah** [comment]
@JulienSambre can please lodge an issue with you respective reverse proxy configuration and we can assess accordingly.

The examples for haproxy were recently updated to work with haproxy-lua-http as opposed to lua-socket so depending on when you configured everything there could be some small differenences.
