### ISSUE TITLE
Extend the information stored in authentication_logs

### ISSUE THREAD

**Issue by ntimo** [authelia/authelia#1293]
Hello,
I would like to propose to extend the information that is stored in the authentication_logs sql table. Currently only the user, time and login success/failure is stored.

But I think it would be really awesome to also store for which website the user tried to authenticate and its IP. This way the database can be used to trace logins. Maybe another database table could be used to actually track when a user open page xy. 

Maybe a setting could be added to delete records older then xy days/weeks/... 

Thanks.

**Comment by james-d-elliott** [comment]
This is something I had planned on implementing. We could probably implement this with relative ease, it actually paves the way for another feature I was interested in investigating.

**Comment by james-d-elliott** [comment]
I will be implementing the auth logs enhancements soon. The compromise that I think is most viable is we record the users intended site. I can add some more verbose auditing logs at a later date in another issue if it's still not sufficient, though it'll likely be after a UI that can show such information.
