### ISSUE TITLE
Logs overwritten in log file after reboot

### ISSUE THREAD

**Issue by GeoCookie** [authelia/authelia#1294]
Hi there,

First of all, thank you for this great projet!

I am trying to use a log file instead of the docker stdout in order to parse the log with fail2ban. Everything works great except when I reboot the Authelia container. After restarting, logs are written at the beggining of the file, overwriting existing lines.
Here an example
![Image sans titre](https://user-images.githubusercontent.com/43962716/91643157-197ad980-ea31-11ea-86cc-f2477674e268.png)

I don't know if this is a normal behavior or if I'm missing something.

Here some info :
Docker version 19.03.12
Athelia container : authelia/authelia:latest
log_level: debug
log_file_path: /config/log/authelia.log

**Comment by james-d-elliott** [comment]
Would renaming the log file on start if it exists be suitable in your use case?

**Comment by GeoCookie** [comment]
Hi there,

Sorry for my late reply.
I think it can do the job. Maybe with the possibility to choose the number of log files we want to keep.

Thanks

**Comment by GeoCookie** [comment]
Hey,

For those who are in my situation, I wrote a little script to create a new log file and remove older ones (with my no/humble bash skills).

```
#!/bin/sh

logfile="/config/log/authelia.log"

if [ -f "$logfile" ];then
    date=$(date +"%y%m%d-%H%M%S")
    mv $logfile $logfile.$date
    touch $logfile
fi

find $logfile.* -mtime +90 -exec rm {} \;
```

I run this script on authelia startup with this line in my docker compose file
`command : /bin/sh -c "/config/log_rotate.sh && authelia --config /config/configuration.yml"`

**Comment by nightah** [comment]
I'm inclined to just make it append to the file instead of creating a new file each time, this way we can delegate any log file management to the administrator.

I'd prefer to keep specifics around log rotation or otherwise out of the application.

**Comment by GeoCookie** [comment]
Seems OK to me too. 

Should I close the request or leave it open until the change is made?

**Comment by nightah** [comment]
You can leave it open. It'll automatically get closed when the linked PR is merged.
