### ISSUE TITLE
Support Registering Multiple Security Keys Against One User

### ISSUE THREAD

**Issue by TheSpad** [authelia/authelia#1316]
I have two Yubikeys; one which I carry with me everywhere and a second at home as a backup in case I lose my first one. I'd like to be able to register both of them against my Authelia user but as far as I can tell it's not possible as registering a second overwrites the registration of the first.

**Comment by dginhoux** [comment]
This can be great.

At this time, I switch between OTP and the yubikey.

**Comment by nightah** [comment]
This is a duplicate of #275, please subscribe to that issue for updates.
