### ISSUE TITLE
Enhance api/verify to include user validation

### ISSUE THREAD

**Issue by mjharkin** [authelia/authelia#1322]
Currently api/verify validates only on:
authelia_session cookie
X-Forwarded-Host header
X-Forwarded-Proto

I've a use case where I'd like to use pam_exec to validate against api/verify but currently this would allow anyone with a valid authelia_session to login as any user.
e.g.
curl -b "authelia_session=<session_id>" -H "X-Forwarded-Host: <host>" -H "X-Forwarded-Proto: https" -s -o /dev/null -I -w "%{http_code}" -L http://<internal-authelia-service>:80/api/verify

If api/verify was extended to validate again a user value then this could work.

For example if api/verify validated on Remote-User header. This validation would only check authelia_session matches the correct user.

**Comment by james-d-elliott** [comment]
I think this is relatively easy to implement. Will take a shot at it tomorrow. @mjharkin

**Comment by james-d-elliott** [comment]
If you're using docker give `authelia/authelia:feature-extend-verify` a try. You need to set the Session-Username header to the value of the username expected to enable this feature.

**Comment by mjharkin** [comment]
@james-d-elliott Thanks, I've tested on authelia/authelia:feature-extend-verify and works exactly as expected.
 
I'll attach a sample script to work with pam-script in case anyone else is interested in it in the next few days.

**Comment by james-d-elliott** [comment]
@mjharkin thinking about this in depth. I have come up with a possible alternate solution that may suit your needs and solve another use case.

If you could inject the username/group into the resource section or domain section of an ACL, would that suffice your needs?

For example:

```
- domain: pam.example.com
   resources:
     - "^/{user}$"
   policy: two_factor
```
or

```
- domain: pam-{user}.example.com
   policy: two_factor
```

**Comment by mjharkin** [comment]
@james-d-elliott actually the original solution provides exactly what I want for my use case.

Specific use case for me is:
- user logs in to webpage with authelia and generates a connection file for an external app (Xpra)
- app retrieves authelia session cookie from browser (more details here https://www.xpra.org/trac/ticket/2874) and uses it as password for pam login (pam-script and pam-ldap combination)

Although I can see that what you propose could be useful in other scenarios.

**Comment by james-d-elliott** [comment]
I was just wondering if you could instead of inserting the username into the Session-Username header, if you could insert the X-Original-URL with a value like "https://pam-<pam_username>.example.com"? If you can, then theoretically we can squash these two ideas simplifying the maintainability. 

To test it all you'd need to do is emulate a configuration like I suggested but with two static usernames.

**Comment by mjharkin** [comment]
I think there's 2 issues with this for my specific use case:
- Xpra connection is over websocket so this rules out subdirectories.
- Also constrained to not using wildcards for ssl certs so this rules out subdomains per user.

**Comment by james-d-elliott** [comment]
Fair enough, we'll go with this then. Thanks for the feedback!

**Comment by nightah** [comment]
@mjharkin any chance of providing the sample script to work alongside PAM?

I'd be keen to see and understand this so it can be documented alongside the change if merged.

**Comment by mjharkin** [comment]
@nightah sure, sorry about the delay.

There can be any number of pam configurations but hopefully this is a good example.
This basically allows pam login with authelia_session as the password.
Assumption is that pam_ldap is correctly configured as a starting point.
Then in for example /etc/pam.d/common-auth
```
auth   [success=1 default=ignore]      pam_ldap.so use_first_pass
```
would be replaced by
```
auth    [success=1 default=ignore]      pam_exec.so expose_authtok /usr/bin/pam-authelia 
```
And script /usr/bin/pam-authelia (with execute permissions). <A_FORWARDED_HOST> and <LOCAL_AUTHELIA_HOST> need to be replaced with specific values. This also has curl as a dependency.
```
#!/bin/bash
# The password from stdin
PAM_PASSWORD=$(cat -)

# url from which authelia session key was created
FORWARDED_HOST=<A_FORWARDED_HOST>

# internal path to verify api
VERIFY_URL=http://<LOCAL_AUTHELIA_HOST>:80/api/verify

AUTH_RESULT=$(curl -b "authelia_session=${PAM_PASSWORD}" -H "Session-Username: ${PAM_USER}" -H "X-Forwarded-Host: ${FORWARDED_HOST}" -H "X-Forwarded-Proto: https" -s -o /dev/null -I -w "%{http_code}" -L "${VERIFY_URL}")

if [[ "$AUTH_RESULT" == 200 ]]; then
  echo "Auth verify ok"
  exit 0
else
  echo "Auth verify failed $AUTH_RESULT"
  exit 1
fi

```
