### ISSUE TITLE
unable to build authelia; fails @ 'go generate internal/server/*' -> " unrecognized import path "aletheia.icu/broccoli/fs": "

### ISSUE THREAD

**Issue by pgnd** [authelia/authelia#1325]
with
```
gcc --version
	gcc (GCC) 10.2.1 20200723 (Red Hat 10.2.1-1)
go version
	go version go1.14.7 linux/amd64
yarn -V
	yarn install v1.22.5
```

building
```
git clone https://github.com/authelia/authelia.git
cd authelia
git log -n1
      1 commit ed5e72508d3c7af7de0d189b37de06592f18daeb (HEAD -> master, origin/master, origin/HEAD)
      2 Author: dependabot-preview[bot] <27856297+dependabot-preview[bot]@users.noreply.github.com>
      3 Date:   Mon Sep 14 11:51:07 2020 +1000
      4
      5     [MISC] (deps): Bump @types/node from 14.10.0 to 14.10.1 in /web (#1318)
      6
      7     Bumps [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node) from 14.10.0 to 14.10      7 .1.
      8     - [Release notes](https://github.com/DefinitelyTyped/DefinitelyTyped/releases)
      9     - [Commits](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/node)
     10
     11     Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
     12
     13     Co-authored-by: dependabot-preview[bot] <27856297+dependabot-preview[bot]@users.noreply.github.com>

cd web
yarn install --frozen-lockfile
INLINE_RUNTIME_CHUNK=false yarn build
mv build ../public_html
cd ..
```

fails @
```
go generate internal/server/*

	go: aletheia.icu/broccoli/fs@v0.0.0-20200420200651-c5ac961a357a: unrecognized import path "aletheia.icu/broccoli/fs": reading https://aletheia.icu/broccoli/fs?go-get=1: 404 Not Found
```

**Comment by james-d-elliott** [comment]
This looks like maybe the broccoli fs has not been generated, @nightah set this up so maybe he understands. I don't think you can build just the web front end though.

**Comment by nightah** [comment]
aletheia.icu/broccoli seems to return a 404, lodged this upstream at https://github.com/aletheia-icu/broccoli/issues/14.

**Comment by nightah** [comment]
We should be dropping this dep come Go 1.16 and utilising the native method for embedding files https://github.com/golang/go/issues/41191.

@pgnd I'd suggest just grabbing the source from https://github.com/aletheia-icu/broccoli and compiling for now.

**Comment by james-d-elliott** [comment]
> 
> 
> with
> 
> ```
> gcc --version
> 	gcc (GCC) 10.2.1 20200723 (Red Hat 10.2.1-1)
> go version
> 	go version go1.14.7 linux/amd64
> yarn -V
> 	yarn install v1.22.5
> ```
> 
> building
> 
> ```
> git clone https://github.com/authelia/authelia.git
> cd authelia
> git log -n1
>       1 commit ed5e72508d3c7af7de0d189b37de06592f18daeb (HEAD -> master, origin/master, origin/HEAD)
>       2 Author: dependabot-preview[bot] <27856297+dependabot-preview[bot]@users.noreply.github.com>
>       3 Date:   Mon Sep 14 11:51:07 2020 +1000
>       4
>       5     [MISC] (deps): Bump @types/node from 14.10.0 to 14.10.1 in /web (#1318)
>       6
>       7     Bumps [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node) from 14.10.0 to 14.10      7 .1.
>       8     - [Release notes](https://github.com/DefinitelyTyped/DefinitelyTyped/releases)
>       9     - [Commits](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/node)
>      10
>      11     Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
>      12
>      13     Co-authored-by: dependabot-preview[bot] <27856297+dependabot-preview[bot]@users.noreply.github.com>
> 
> cd web
> yarn install --frozen-lockfile
> INLINE_RUNTIME_CHUNK=false yarn build
> mv build ../public_html
> cd ..
> ```
> 
> fails @
> 
> ```
> go generate internal/server/*
> 
> 	go: aletheia.icu/broccoli/fs@v0.0.0-20200420200651-c5ac961a357a: unrecognized import path "aletheia.icu/broccoli/fs": reading https://aletheia.icu/broccoli/fs?go-get=1: 404 Not Found
> ```

I had this issue too. Manually fixed it locally by setting the following export:

GOPROXY="https://goproxy.io,direct"
