### ISSUE TITLE
Haproxy configuration when authenticate application call

### ISSUE THREAD

**Issue by JulienSambre** [authelia/authelia#1336]
Hi,

I see that the example configuration for haproxy was missing the case when an application wanted to access a protected site.

Through the doc, it showed that we must use the `Proxy-Authorization`.

I have myself solved the case with the following configuration (copy the content of Authorization header to Proxy-Authorization for protected sites only) : 

`http-request set-header Proxy-Authorization %[req.hdr(Authorization)] if { req.hdr(Authorization) -m found } protected-frontends`

Is it the correct way to do this things? And should this case be added to the haproxy.cfg example?

**Comment by nightah** [comment]
@JulienSambre if your far end application that's attempting to authenticate stores the credentials in the Authorization header, then yes.

Realistically this depends entirely on the specific use case and how you are authenticating, this is primarily the reason why we don't have it included in the examples and rather per your initial commentary is documented at the following locations:
- https://www.authelia.com/docs/deployment/supported-proxies/#redirection-to-the-login-portal
- https://www.authelia.com/docs/features/single-factor.html#proxy-authorization-header

Another alternative depending on the use case could be to utilise network based whitelisting between the locations.

**Comment by nightah** [comment]
@JulienSambre I'm going to close off this issue since I believe your question has been answered.

If you have any other questions please don't hesitate to open another issue.
