### ISSUE TITLE
Multi-tenant app support? 

### ISSUE THREAD

**Issue by knnnrd** [authelia/authelia#1339]
Hi, I'm researching SSO solutions for a few applications we develop. They are multi-tenant "enabled". This means when a user makes a request for "foo.example.org", the application is configured to only fetch records for "foo" just for that request.
Users can belong to one or more tenants.

I was looking at the access control documentation but I think the thing I had in mind is not possible? E.g.:

- domain: "(*).example.com"
  subject:
       - "group:$1"
  policy: one_factor

So the tenant id would be a capture group that can be referenced later in the group.

Thanks in advance.

**Comment by james-d-elliott** [comment]
I had plans to do something like this (had some issues with unexpected results). I will try and invest some time this coming week into doing it again.

**Comment by james-d-elliott** [comment]
@knnnrd I've implemented this for test purposes in the `authelia/authelia:feature-acl-preload` docker image. Domain rules that start with `{user}` will only match if the user matches the prefix. For example `{user}.example.com`, when user john visits `john.example.com` the rule will match, but if he visits `jane.example.com` they will not. If you'd like a binary instead they can be found on [Buildkite](https://buildkite.com/authelia/authelia/builds/4065).

**Comment by james-d-elliott** [comment]
@all-contributors please add @knnnrd for ideas.

**Comment by james-d-elliott** [comment]
@knnnrd I've got a slightly better solution to this which uses regex named match groups instead. I think I personally like this over the previously implemented solution. 

See #2789
