### ISSUE TITLE
u2f support in MS Edge

### ISSUE THREAD

**Issue by lenaxia** [authelia/authelia#1360]
Are there plans to integrate with Microsoft's U2F support in Edge? It works in both Firefox and Chrome. I was not able to dig up any issues regarding this, and unfortunately I am not familiar with what exactly needs to go into adding this support.

**Comment by james-d-elliott** [comment]
I have done some basic research. There was no official plan to do this, but it is possible. I believe U2F is NOT supported by Edge, it only supports Webauthn. Webauthn is the future, and supported by all of the browsers I know that support U2F.

Duo Labs have a library supporting it: https://github.com/duo-labs/webauthn

So realistically I think our plan should be to attempt to migrate to webauthn without breaking existing functionality if possible as a test, and all being well we merge.

**Comment by lenaxia** [comment]
Thanks James, that makes sense. 

I don't know enough about these auth backends to be able to tell the difference. Thanks for the clarification.

**Comment by james-d-elliott** [comment]
This can realistically be addressed also in #241 which you can follow for updates.
