### ISSUE TITLE
Add config options for additional data passed back

### ISSUE THREAD

**Issue by benyanke** [authelia/authelia#1376]
Currently the /api/verify route returns `remote-user`, and a csv list of `remote-groups`.

I'd love to see optional providing of other fields as well, such as `remote-name` (Full name) and `remote-email`, or perhaps not even optional.

**Comment by nightah** [comment]
I think this is a great idea.

Hopefully I should have some free time this week to address this.

**Comment by nightah** [comment]
I just realised I already have a branch with most of this in there so I should something ready by this weekend.
