### ISSUE TITLE
Token based authorization

### ISSUE THREAD

**Issue by laurivosandi** [authelia/authelia#1387]
Hello, in many cases it would be useful to share an Authelia protected resource (eg path on a domain) with users outside primary authentication realm (eg users in AD).

If would be great if there was a way for me to issue a token outside Authelia a'la 'share' button on the accessed resource for users authenticated from primary realm. For databaseless design I suggest hash of expiration date, salt, resource address and secret shared with Authelia. This would be accompanied with relevant policy config in Authelia configuration to allow accessing the resource with the token. Alternatively have SQL table with tokens what could be read by Authelia, this way it would be possible to later 'unshare' the resource as well.

**Comment by modem7** [comment]
Sorry to hijack: 

Would this also be a similar feature to 2fa static passwords ala Google app passwords? As this would be mighty useful with 3rd party apps which are protected with 2fa.

**Comment by james-d-elliott** [comment]
See #2023
