### ISSUE TITLE
Unable to initialize SQL database: driver: bad connection

### ISSUE THREAD

**Issue by akrea** [authelia/authelia#1424]
Hi

My setup worked last time on the 29th of October 2020. When I tried to log in today, it did not work anymore. I did not change anything (except updated my ubuntu and maybe som docker containers (with watchtower)).

**Problem Description**
When I want to access an authelia protected page I get to the 1st factor page. Entering the credentials it remains there. When I check the log the moment I try to login I get:

```
time="2020-11-01T21:07:50+01:00" level=debug msg="Credentials validation of user myuser is ok" method=POST path=/api/firstfactor remote_ip=my.ip.se.cret
time="2020-11-01T21:07:50+01:00" level=debug msg="Mark authentication attempt made by user myuser" method=POST path=/api/firstfactor remote_ip=my.ip.se.cret
time="2020-11-01T21:07:50+01:00" level=debug msg="Required level for the URL https://lidarr.mydomain.com/ is 2" method=POST path=/api/firstfactor remote_ip=my.ip.se.cret
time="2020-11-01T21:07:50+01:00" level=warning msg="https://lidarr.mydomain.com/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=my.ip.se.cret
```

When I scroll to the beginning in the log I see:
```
level=fatal msg="Unable to initialize SQL database: driver: bad connection" 
stack="github.com/authelia/authelia/internal/storage/mysql_provider.go:77
NewMySQLProvider\ngithub.com/authelia/authelia/cmd/authelia/main.go:76              
startServer\ngithub.com/authelia/authelia/cmd/authelia/main.go:121              
main.func1\ngithub.com/spf13/cobra@v0.0.7/command.go:842
(*Command).execute\ngithub.com/spf13/cobra@v0.0.7/command.go:943
(*Command).ExecuteC\ngithub.com/spf13/cobra@v0.0.7/command.go:883
(*Command).Execute\ngithub.com/authelia/authelia/cmd/authelia/main.go:138              
main\nruntime/proc.go:204                                                
main\nruntime/asm_amd64.s:1374                                           
goexit"
```

**Environment:** 
Ubuntu server 18.04.2

_Docker_
Server:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  OS/Arch:          linux/amd64

_Docker Image Information on mariadb_
Order | Size | Layer
-- | -- | --
1 | 63.2 MB | COPY dir:0107f66453cc5fabffe516923ed005e225848586523ea0673a5be0d4fef87763 in /
-- | -- | --
2 | 0 B | ARG BUILD_DATE
3 | 0 B | ARG VERSION
4 | 0 B | LABEL build_version=Linuxserver.io version:- 714b55d6-ls56 Build-date:- 2020-10-28T17:15:23+00:00
5 | 0 B | LABEL maintainer=TheLamer
6 | 0 B | ARG OVERLAY_VERSION=v2.0.0.1
7 | 0 B | ARG OVERLAY_ARCH=amd64
8 | 0 B | ARG DEBIAN_FRONTEND=noninteractive
9 | 0 B | ENV HOME=/root LANGUAGE=en_US.UTF-8 LANG=en_US.UTF-8 TERM=xterm
10 | 848 B | COPY file:a0afddf6c2c99dee6409f51005a22f49cffa569aa0e8ad133ed14c730847fd57 in /etc/apt/
11 | 37.1 MB | \|5 BUILD_DATE=2020-10-28T17:15:23+00:00  DEBIAN_FRONTEND=noninteractive OVERLAY_ARCH=amd64  OVERLAY_VERSION=v2.0.0.1 VERSION=714b...
12 | 13.6 kB | COPY dir:d9b4fd1bacede18445a775aacdc628686177aef2dd4806f656a0a9c0982d98df in /
-- | -- | --
13 | 0 B | ENTRYPOINT ["/init"]
14 | 0 B | ARG BUILD_DATE
15 | 0 B | ARG VERSION
16 | 0 B | ARG MARIADB_VERSION
17 | 0 B | LABEL build_version=Linuxserver.io version:-  110.4.15mariabionic-ls85 Build-date:- 2020-10-31T11:19:29-04:00
18 | 0 B | LABEL maintainer=thelamer
19 | 0 B | ARG DEBIAN_FRONTEND=noninteractive
20 | 0 B | ENV MYSQL_DIR=/config
21 | 0 B | ENV DATADIR=/config/databases
22 | 255.5 MB | \|4 BUILD_DATE=2020-10-31T11:19:29-04:00  DEBIAN_FRONTEND=noninteractive MARIADB_VERSION=1:10.4.15+maria~bionic  VERSION=110.4.15mariabionic-ls85 RUN echo "**** install gnupg ****"  &&  apt-get update &&  apt-get install -y 	gnupg  &&  echo "add mariadb repository ****" &&  echo  "(redundant on armhf platform, but added for consistent dockerfile on  all platforms) ****" &&  apt-key adv --recv-keys --keyserver  hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8 &&  echo "deb  http://mirror.rackspace.com/mariadb/repo/10.4/ubuntu bionic main"  >> 	/etc/apt/sources.list.d/mariadb.list &&  echo "deb-src  http://mirror.rackspace.com/mariadb/repo/10.4/ubuntu bionic main"  >> 	/etc/apt/sources.list.d/mariadb.list &&  echo "****  install runtime packages ****" &&  if [ -z ${MARIADB_VERSION+x}  ]; then         MARIADB="mariadb-server";  else          MARIADB="mariadb-server=${MARIADB_VERSION}";  fi &&  apt-get  update &&  apt-get install -y 	${MARIADB} &&  echo "****  cleanup ****" &&  rm -rf 	/tmp/* 	/var/lib/apt/lists/* 	 /var/lib/mysql 	/var/tmp/* &&  mkdir -p 	/var/lib/mysql

Please let me know if I can provide any more information.

Thank you for the help

**Comment by james-d-elliott** [comment]
Can you access MariaDB with something like [phpmyadmin](https://hub.docker.com/r/bitnami/phpmyadmin/)?

**Comment by akrea** [comment]
Yes, I can access it with phpmyadmin (dockerized as well).

**Comment by james-d-elliott** [comment]
Does the Authelia DB look fine? Also do you have a lot of other services connecting to MariaDB?

**Comment by akrea** [comment]
Thank you for your response. Regarding Databases you have to break
everything down barney style. The only thing I use phpmyadmin for is the
user admin. How is it supposed to look like?

I also run nextcloud on the same mariadb-container - as mentioned before
this worked without any hickups so far.

Thank you

**Comment by james-d-elliott** [comment]
Just check the tables look like they have data.. I can't see why it would be an issue. You can theoretically just delete the tables and start over, though that error doesn't really indicate that as an issue.. and MariaDB 10.4 is compatible. Is nextcloud still working?

Maybe @nightah has an idea.

**Comment by james-d-elliott** [comment]
If you are using docker-compose it may be worth showing that too.

**Comment by nightah** [comment]
That error to me just suggests the database may not have been up when Authelia started. I don't think it's related to the issue you're experiencing.

Can you detail your specific workflow like, and what occurs at each steps?

Including full Authelia logs from the start and end of your workflow for both Authelia and your reverse proxy?
I suspect given you're using LSIO containers you're likely using this with SWAG?

**Comment by nightah** [comment]
@akrea any updates on this?

**Comment by akrea** [comment]
Hi

Sorry for the long silence.
Important message: it works again.
How: I don't know.
What happened: odd behaviour of authelia as reported. 3 days later one disk
in my raid 5 failed. created additional backup from the yet working system.
changed all disks as I wanted to upgrade anyway. One disk was doa which and
I had to wait for a replacement, which is why it took so long. Import
backup. Pull all new images. Start all containers. Everything is working
fine including authelia...

So I don't know what caused the problem or fixed it. Updates may have a
contribution.

Thank you anyway for your time and help!
yours sincerely

Am Di., 10. Nov. 2020 um 01:19 Uhr schrieb Amir Zarrinkafsh <
notifications@github.com>:

**Comment by nightah** [comment]
No problems at all @akrea I'm glad that you've resolved the issue.

If you happen to have a similar issue please don't hesitate to let us know and we can reopen this issue.
