### ISSUE TITLE
Lite deployment with nginx+docker 

### ISSUE THREAD

**Issue by eercanayar** [authelia/authelia#1434]
Hello everyone.

`authelia/compose/lite/docker-compose.yml` is a good starting point for authelia + traefik but my choice is on nginx side. I can prepare nginx configuration files but is there any reference to match traefik configuration to nginx in the compose file? If someone has a compose file of authelia + nginx, it would really help. I will share mine when I somehow managed to run it.

**Comment by james-d-elliott** [comment]
There are [https://www.authelia.com/docs/deployment/supported-proxies/nginx.html](docs) on usage with nginx. Additionally @nightah uses nginx.

**Comment by nightah** [comment]
Yep I would point you right at the docs example @james-d-elliott has suggested, alternatively if you use the LSIO (linuxserver.io) containers SWAG includes a number of pre-defined proxy configurations for apps which have Authelia pre-baked in.

You can read https://blog.linuxserver.io/2020/08/26/setting-up-authelia/ also which goes in to quite a bit of detail as a guide to setup with their SWAG container.

**Comment by nightah** [comment]
@eercanayar do you need any other help/information or can this issue be closed off?

**Comment by eercanayar** [comment]
> There are [docs](https://www.authelia.com/docs/deployment/supported-proxies/nginx.html) on usage with nginx. Additionally @nightah uses nginx.
> 
> The config required is relatively straight forward, are you using nginx in docker or outside?

Yes, I saw these but they are just nginx configuration files. docker-compose configuration confused me. I think I can manage it to wor in possible time and send a pull request!
