### ISSUE TITLE
Authelia crash when using v4.23 and 4.23.1

### ISSUE THREAD

**Issue by GeoCookie** [authelia/authelia#1451]
Hi there,

My Authelia container crashes on version 4.23 and 4.23.1. Everything works fine on version 4.22

Here the error
> panic: runtime error: index out of range [0] with length 0
> 
> goroutine 29 [running]:
> github.com/authelia/authelia/internal/handlers.setForwardedHeaders(0xc0002767c0, 0xc000edf7f0, 0xe, 0x0, 0x0, 0xc000ebe740, 0x4, 0x4, 0x0, 0x0, ...)
>         github.com/authelia/authelia/internal/handlers/handler_verify.go:162 +0x171
> github.com/authelia/authelia/internal/handlers.VerifyGet.func1(0xc0015b4000)
>         github.com/authelia/authelia/internal/handlers/handler_verify.go:454 +0x9ae
> github.com/authelia/authelia/internal/middlewares.AutheliaMiddleware.func1.1(0xc000276500)
>         github.com/authelia/authelia/internal/middlewares/authelia_context.go:49 +0x1ae
> github.com/fasthttp/router.(*Router).Handler(0xc000eab860, 0xc000276500)
>         github.com/fasthttp/router@v1.2.4/router.go:348 +0x829
> github.com/authelia/authelia/internal/middlewares.LogRequestMiddleware.func1(0xc000276500)
>         github.com/authelia/authelia/internal/middlewares/log_request.go:14 +0xe2
> github.com/authelia/authelia/internal/middlewares.StripPathMiddleware.func1(0xc000276500)
>         github.com/authelia/authelia/internal/middlewares/strip_path.go:20 +0x195
> github.com/valyala/fasthttp.(*Server).serveConn(0xc0000cdb00, 0x114a680, 0xc0000100e0, 0x0, 0x0)
>         github.com/valyala/fasthttp@v1.15.1/server.go:2162 +0x11c9
> github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000efe0a0, 0xc000f24200)
>         github.com/valyala/fasthttp@v1.15.1/workerpool.go:223 +0xc2
> github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc000efe0a0, 0xc000f24200, 0xe09b80, 0xc000f24200)
>         github.com/valyala/fasthttp@v1.15.1/workerpool.go:195 +0x35
> created by github.com/valyala/fasthttp.(*workerPool).getCh
>         github.com/valyala/fasthttp@v1.15.1/workerpool.go:194 +0x115

Here some information
- I am using four _ENV__FILE
  AUTHELIA_JWT_SECRET_FILE
  AUTHELIA_DUO_API_SECRET_KEY_FILE
  AUTHELIA_SESSION_SECRET_FILE
  AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
- OpenLDAP is used as backend
- I run a script before running the container
  command : /bin/sh -c "/config/log_rotate.sh && authelia --config /config/configuration.yml"
  I tried to remove this line, same result

I must admit I don't understand the error 🙃  Tell me if you need more information

**Comment by james-d-elliott** [comment]
I can see where the error is, we can fix this our end easy enough. Temporarily you can make sure you have correctly setup an email in LDAP and it should fix it.

**Comment by GeoCookie** [comment]
Hey,

Thank you for your reply. You are right, I added an email to my account and everything is working fine now.
I saw a similar case with the same problem but with a different error message. So I didn't think about adding an email address. 🤔

Thank you !

Do you want to close this case ?

**Comment by james-d-elliott** [comment]
We will close it once the fix is merged, regardless of it technically being a configuration issue, it should not crash.

**Comment by nightah** [comment]
This is now resolved in the `master` tagged container.
Will be released shortly with `4.23.2`.
