### ISSUE TITLE
Log format json

### ISSUE THREAD

**Issue by josephcomisi** [authelia/authelia#1456]
Hello,

Is there a way to format logs in json ? (I'm using it in a docker-compose file along with traefik so far)

Could not find anything on the docs.
if not, it would be great to have this option

Thank you

**Comment by nightah** [comment]
Is there a specific reason you want the log in a different format?

My recollection is that Docker's default log driver is to store in json, you should be able to see this at:
`/var/lib/docker/containers/<CONTAINERID>/<CONTAINERID>-json.log`.

**Comment by josephcomisi** [comment]
Hello nightah,
It is for parsing. It's easy to rename fields in and format data. 
This is option is available almost everywhere. I wondered what are your thoughts on this and if it is something that will implement in the (hopefully near) futur.
