### ISSUE TITLE
 Question: Connect to LDAP via StartTLS

### ISSUE THREAD

**Issue by GeoCookie** [authelia/authelia#1458]
Hi,

I would like to connect to my LDAP server through StartTLS instead of LDAPS.

I saw that it is already implemented here # 240 but I can't find how to activate it. If I use the "ldap://" prefix in the url, Authelia will use an insecure connection.

Thanks for your work !

**Comment by Ornias1993** [comment]
Did you try ldaps with a StartTLS ldap server?
I added TLS to an ldap connection using a proxy before, which I think also uses StartTLS and ldaps worked fine.

**Comment by GeoCookie** [comment]
Hi,

Thank you for your reply.
LDAPS works fine. Authelia successfully communicates with my OpenLDAP server via LDAPS on port 636 But I would like to use LDAP with StartTLS (port 389), which is different from LDAP over SSL / TLS.

Some solutions, like Portainer, offer a choice between these options
![image](https://user-images.githubusercontent.com/43962716/99077500-1ff30900-25bd-11eb-8cb2-b2bdb06abb3c.png)

**Comment by nightah** [comment]
I believe the library that we use does support LDAP with StartTLS.
We need to investigate to see if/how an LDAP server responds with it's capabilities, if it's similar to a mail server we should be able to implement this relatively easily.

Since LDAPS is available today though, this is likely to be lower in the list of priorities.

**Comment by GeoCookie** [comment]
Hi,

Thank you for your feedback

**Comment by james-d-elliott** [comment]
@GeoCookie can you try this docker image for me (will be pushed in probably 10 mins): authelia/authelia:feature-ldap-starttls

**Comment by GeoCookie** [comment]
Hi,

It's working for me 👍

- I changed the image by the one you told me
- Added this line in the configuration file
![image](https://user-images.githubusercontent.com/43962716/100889109-128fb700-34b7-11eb-92fa-c93588012512.png)
- Restarted authelia
- Checked openldap logs
![image](https://user-images.githubusercontent.com/43962716/100889265-3a7f1a80-34b7-11eb-8bb4-0240efdc6d8c.png)

It might be worth trying with the skp_verify option set to false. But I am not sure to know how to install root ca on Authelia

**Comment by james-d-elliott** [comment]
@GeoCookie if you're using Docker you just need to add the certificate to the docker hosts trust chain. Currently in Authelia's LDAP there is no way, there is only a way in SMTP Notifier. I plan to remove that from SMTP and make it global with some improvements in time.
