### ISSUE TITLE
API documentation missing?

### ISSUE THREAD

**Issue by adyah-cisco** [authelia/authelia#1470]
I needed to fetch the current logged in user from a front end application, and could not find the api endpoint from the docs.

Found the code [here](https://github.com/authelia/authelia/blob/master/internal/handlers/handler_user_info.go) and the relevant API endpoint by looking at requests made while accessing /authenticated. 

If there is a dedicated documentation for all the endpoints that other apps can use, it can be pretty helpful.

**Comment by adyah-cisco** [comment]
The endpoint I needed was /api/user/info, if anyone else is looking for it.

**Comment by nightah** [comment]
All the backend API endpoints and their applicable methods can be found here:
https://github.com/authelia/authelia/blob/73a19140d166110c1c7e960d60617884c3902755/internal/server/server.go#L45-L116

They do need to be documented and it's on the backlog at #450, if you're up to the task you're more than welcome to contribute!
