### ISSUE TITLE
Cannot parse garbled log output for fail2ban filter

### ISSUE THREAD

**Issue by openscallion** [authelia/authelia#1480]
Good evening--

I am attempting to set up fail2ban with authelia using the[ documentation here](https://www.authelia.com/docs/security/measures.html#additional-security) and in issue #1176 .

This would usually be a straightforward process, however, the authelia log file has what appears to be quite a bit of cruft/is garbled. Adapting the regex to recognize the different format was easy, but I'm unable to peg the remote IP (<HOST>, should be 1.2.3.4 here) despite significant experimenting. The documented fail2ban format appears to suggest that the log should be quite a bit simpler: Error while checking password for user test: user not found <HOST> stack..

Did I bork my install somehow? Any insight here would be appreciated.

Here is an example line from my log (docker install, log level=info, log mapped to /config/authelia.log)
`[31mERRO[0m[0078] Error while checking password for user test: user not found  [31mmethod[0m=POST [31mpath[0m=/api/firstfactor [31mremote_ip[0m=1.2.3.4 [31mstack[0m="github.com/authelia/authelia/internal/middlewares/authelia_context.go:64  (*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/handlers/response.go:94             handleAuthenticationUnauthorized\ngithub.com/authelia/authelia/internal/handlers/handler_firstfactor.go:100 FirstFactorPost.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49  AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.2.4/router.go:348                           (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14       LogRequestMiddleware.func1\ngithub.com/authelia/authelia/internal/middlewares/strip_path.go:20        StripPathMiddleware.func1\ngithub.com/valyala/fasthttp@v1.15.1/server.go:2162                        (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.15.1/workerpool.go:223                     (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.15.1/workerpool.go:195                     (*workerPool).getCh.func1\nruntime/asm_amd64.s:1374                                                  goexit"
`

**Comment by nightah** [comment]
That garbled text that's showing up are terminal coloring outputs.
Our [logging library](https://github.com/sirupsen/logrus) performs this when it detects a TTY, so this is intended behaviour.

Can you provide the output of either your `docker-compose.yml` for Authelia or the respective `docker run/create` command?

Including an output of `docker inspect <autheliacontainer>` would also be helpful.

**Comment by openscallion** [comment]
Thanks @nightah . Should have thought of that but it was quite late!

It looks like the [logrus issue #1069](https://github.com/sirupsen/logrus/issues/1069) may be relevant (using a different formatter for different outputs) but appears to be dependent on [this only-waiting-to-be-merged pull.](https://github.com/sirupsen/logrus/pull/1184). A 'right now' solution is [offered here](https://github.com/sirupsen/logrus/issues/1069#issuecomment-706534620).

I expect it would be preferable to omit the colors when writing to a file if that is feasible to include.

**Comment by nightah** [comment]
@openscallion the issue here is that a TTY is being detected, while those solutions could be utilised they should not be necessary.

For example if I set my Docker based deployment to output to a logfile here's the output I get:
```
cat authelia.log                                                                                                                                                                                                                                                            

time="2020-11-24T16:01:48+11:00" level=info msg="Logging severity set to info"
time="2020-11-24T16:01:48+11:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
```

As there is no TTY detected it outputs with the correct format (uncolored) to the specified file.

**Comment by nightah** [comment]
@openscallion just reaching out to see if you either have sorted this?
If not can you please provide the outputs of the files requested earlier so that we can assist you.

**Comment by nightah** [comment]
@openscallion I'm going to close this issue, if you are still running into the same problem please let provide the outputs of the requested files and I can reopen this issue.

**Comment by bobokun** [comment]
Hi I am having the same issue and it is causing the regex to fail in fail2ban. When I run docker exec -it Authelia /bin/bash and do the same cat authelia.log command it shows up with colours.
![image](https://user-images.githubusercontent.com/12660469/103419033-3d753580-4b5f-11eb-94f6-390c0a0e2647.png)

**Comment by nightah** [comment]
@bobokun what OS are you running into that issue with?

Is it Unraid?

**Comment by bobokun** [comment]
Yes Unraid
