### ISSUE TITLE
Question about 2FA methods. Can others be added?

### ISSUE THREAD

**Issue by algsupport** [authelia/authelia#1497]
Hello,

Thank you everyone for your efforts to make this software. I don't know if this is the right place for my questions, so please excuse me if I made a mistake.

I 'd like to ask the forllowing:

Except for duo is it possible to include alternative 2nd factors? For example scan QR code to authenticate.
Are there open source alternatives to duo? If I create something how would I go integrating it with authelia?

Thank you for your time.
Best regards.

**Comment by nightah** [comment]
Hi @algsupport Duo isn't the only 2FA method that Authelia supports today per our [README.md](https://github.com/authelia/authelia#features-summary).

* Several kind of second factor:
  * **[Security Key (U2F)](https://docs.authelia.com/features/2fa/security-key)** with [Yubikey].
  * **[Time-based One-Time password](https://docs.authelia.com/features/2fa/one-time-password)** with [Google Authenticator].
  * **[Mobile Push Notifications](https://docs.authelia.com/features/2fa/push-notifications)** with [Duo](https://duo.com/).

There are a handful of other authentication methods like [WebAuthn](https://github.com/authelia/authelia/issues/241), [SAML](https://github.com/authelia/authelia/issues/493) and [OpenID Connect](https://github.com/authelia/authelia/issues/189) which can provide varying degrees of first/second factor authentication.

If you plan to integrate something we would ideally like to discuss those plans in an issue here, or on [Matrix](https://github.com/authelia/authelia#matrix) just to ensure that it's a change that we would merge.

I hope this helps and if you have any other questions please don't hesitate to reach out!

**Comment by algsupport** [comment]
Hello @nightah,

Apologies, I meant for alternative Mobile Push Notifications methods. I also meant if you know of other Mobile Push Notifications services preferably something open source or free. Especially something self hosted that doesn't require me to send any data to 3rd parties.

Thank you.

**Comment by nightah** [comment]
@algsupport I'm aware of Duo and Authy, both of which have Free plans.

[Duo supports up to 10 users for free](https://duo.com/pricing/duo-free) and [Authy supports 100 auths per month for free](https://www.twilio.com/authy/pricing).

https://medevel.com/15-os-push-notification/ also lists a number of open source push notification servers but that's only half of the solution. You then would need to develop your own application and the required elements to provide the push based notification services for your mobile platform.

I'm not entirely certain if any of those existing applications also provide their own mobile apps, but even if they do it's unlikely that they would work for your use-case out of the box.

**Comment by algsupport** [comment]
@nightah Thank you again for your response.
I am aware of authy. Authy was my first considerations. But the amount they charge for the push notifications is outrageous.
With that money, I prefer to hire an additional developer :P
Duo is more reasonable, but I would still prefer something self hosted that is also an out of the box solution.
Anyway thank you for your time.

**Comment by nightah** [comment]
No problems if you have any other questions please feel free to reach out.
