### ISSUE TITLE
config key not expected: authentication_backend.ldap.implementaion

### ISSUE THREAD

**Issue by jinro79** [authelia/authelia#1499]
I'm trying to configure qauthelia to work with out ldap servers and I cannot get past this error: "config key not expected: authentication_backend.ldap.implementation" 

I am running the authelia/authelia:4.23.3 image and used the minimal configuration.yaml

[configuration.yml.txt](https://github.com/authelia/authelia/files/5626069/configuration.yml.txt)

if I comment out the "implementation: activedirectory" line out the error disappears.

Thanks.

**Comment by james-d-elliott** [comment]
Implementation is a new key available in the master branch. It will be released with Authelia 4.24, you can optionally use the following image to get access to the new features `authelia/authelia:master`.

**Comment by james-d-elliott** [comment]
It's expected to release tomorrow.

**Comment by jinro79** [comment]
Thanks for the clarification.
