### ISSUE TITLE
Bug TOTP registration, and feature request

### ISSUE THREAD

**Issue by schklom** [authelia/authelia#1505]
Hi everyone !

First, I'm glad to be able to use Authelia, it will be very useful for me so thank you for that !

Second, I'm trying to register my phone for TOTP, but no matter which browser I try to open the link with, I always get a blurred QRcode with a red X on it, and the error message

    Failed to generate the code to register your device

It seems strange for Authelia to forbid the use of a TOTP seed (some sites call it "secret").
Would you allow to print it ?
Most websites allow this, including GitHub Google Facebook Reddit Deezer LinkedIn etc...

I personally use KeePass, which lets me retrieve TOTP passwords on almost any device including my computer. But I can't make it work with a QRcode, even less when the picture refuses to appear x)

In case it helps, here is the relevant part of my `configuration.yml`
```
totp:
  issuer: authelia.com
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 128
      parallelism: 8
```
and the docker logs for `authelia` (opened the webpage with Edge on my phone after receiving the email)
```
time="2020-12-03T06:29:45+01:00" level=trace msg="Second factor enabled: true" method=GET path=/api/configuration remote_ip=10.2.0.5
time="2020-12-03T06:29:45+01:00" level=trace msg="Available methods are [totp u2f]" method=GET path=/api/configuration remote_ip=10.2.0.5
time="2020-12-03T06:29:45+01:00" level=trace msg="Replied (status=200)" method=GET path=/api/configuration remote_ip=10.2.0.5
time="2020-12-03T06:29:45+01:00" level=trace msg="Replied (status=200)" method=GET path=/api/user/info remote_ip=10.2.0.5
time="2020-12-03T06:29:57+01:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip=127.0.0.1
time="2020-12-03T06:29:57+01:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=127.0.0.1
time="2020-12-03T06:30:03+01:00" level=trace msg="Request hit" method=POST path=/api/secondfactor/totp/identity/start remote_ip=10.2.0.5
time="2020-12-03T06:30:03+01:00" level=debug msg="Sending an email to user schklom (MYEMAIL@gmail.com) to confirm identity for registering a device." method=POST path=/api/secondfactor/totp/identity/start remote_ip=10.2.0.5
time="2020-12-03T06:30:03+01:00" level=debug msg="Notifier SMTP client attempting connection to smtp.gmail.com:587"
time="2020-12-03T06:30:03+01:00" level=debug msg="Notifier SMTP client connected successfully"
time="2020-12-03T06:30:03+01:00" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: smtp.gmail.com), attempting"
time="2020-12-03T06:30:03+01:00" level=debug msg="Notifier SMTP STARTTLS completed without error"
time="2020-12-03T06:30:03+01:00" level=debug msg="Notifier SMTP server supports authentication with the following mechanisms: LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH"
time="2020-12-03T06:30:03+01:00" level=debug msg="Notifier SMTP client attempting AUTH PLAIN with server"
time="2020-12-03T06:30:03+01:00" level=debug msg="Notifier SMTP client authenticated successfully with the server"
time="2020-12-03T06:30:03+01:00" level=debug msg="Notifier SMTP client attempting to send email body to MYEMAIL@gmail.com"
time="2020-12-03T06:30:04+01:00" level=debug msg="Notifier SMTP client successfully sent email"
time="2020-12-03T06:30:04+01:00" level=trace msg="Replied (status=200)" method=POST path=/api/secondfactor/totp/identity/start remote_ip=10.2.0.5
time="2020-12-03T06:30:27+01:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip=127.0.0.1
time="2020-12-03T06:30:27+01:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=127.0.0.1
time="2020-12-03T06:30:35+01:00" level=trace msg="Request hit" method=GET path=/one-time-password/register remote_ip=10.2.0.3
time="2020-12-03T06:30:35+01:00" level=trace msg="Replied (status=200)" method=GET path=/one-time-password/register remote_ip=10.2.0.3
time="2020-12-03T06:30:35+01:00" level=trace msg="Request hit" method=POST path=/api/secondfactor/totp/identity/finish remote_ip=10.2.0.3
time="2020-12-03T06:30:35+01:00" level=trace msg="Replied (status=403)" method=POST path=/api/secondfactor/totp/identity/finish remote_ip=10.2.0.3
time="2020-12-03T06:30:57+01:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip=127.0.0.1
```

Many thanks for the software, and any help you can provide :)

**Comment by james-d-elliott** [comment]
Let's deal with the initial issue first then we can look at the printing part.

The first time you click on the link it expires the link. Additionally if your browser does not have the session cookie for Authelia it will assume you got the link improperly and fail to generate it; i.e. you must open the link the first time with the same browser. 

This is the only time I've ever seen this, let me know if this helps you at all.

**Comment by schklom** [comment]
Okay, I got it to work :) The key part was "with the same browser". I was trying to login from my computer, and the email said I needed to register my mobile so I switched devices to open the link.
When I open the link from my computer browser, then it works !
Thank you for the explanation 👍 

I don't understand why the registration mentions a mobile when it doesn't need to be a mobile at all. Wouldn't the word "device" or "browser" fit better ?

From the QRcode, I managed to retrieve the secret. However I still think it would be great to have a small text box underneath with the secret :P

**Comment by nightah** [comment]
> I don't understand why the registration mentions a mobile when it doesn't need to be a mobile at all. Wouldn't the word "device" or "browser" fit better ?

We could definitely adjust the wording.



> From the QRcode, I managed to retrieve the secret. However I still think it would be great to have a small text box underneath with the secret :P

We also used to do this with Authelia v3, I don't see why we couldn't do it again, please lodge a new issue with that specific request and we can address accordingly.
