### ISSUE TITLE
Feature request: make TOTP secret explicit during registration

### ISSUE THREAD

**Issue by schklom** [authelia/authelia#1509]
Hi everyone !

I would like to request adding the TOTP secret in a little text box near the QRcode during the registration process.
I personally prefer to register from my computer, and simply copy-pasting a sequence of characters is easier than scanning a QRcode.

It was done in v3, and it should be doable to implement it again:

> We also used to do this with Authelia v3, I don't see why we couldn't do it again, please lodge a new issue with that specific request and we can address accordingly.

_Originally posted by @nightah in https://github.com/authelia/authelia/issues/1505#issuecomment-738001209_

What do you guys think ? :)

Edit: just found out that the link of the QRcode image contains the secret, so it's even less of a hassle now since I don't need to scan the picture.

**Comment by james-d-elliott** [comment]
Correct on the secret being in the QR, it's basically a special URL that OTP apps understand. Still no reason we can't add a button to show the settings somewhere on the page. #773 and #1271 would need to be considered in implementing this, we currently have more features than were available in v3.

**Comment by nightah** [comment]
@schklom it'd be great if you had the opportunity to test the following container: `docker pull authelia/authelia:feature-display-totp-secret` and provide any feedback you have.

**Comment by schklom** [comment]
I erased my database, pulled `authelia/authelia:feature-display-totp-secret`, and it works perfectly well, thanks ! :D

I do have some minor feedback if you want:
The key icon on the left has a clear job to me: copy the character sequence (the key) of the secret.
The icon on the right seems a little harder to understand. I needed to paste in notepad to see what was being copied.
Working out that the buttons copy information, and which button copies what took me about 30 seconds in total. Pretty easy to understand, but I like computers so I might not be the most typical user.

Suggestion:
After the user clicks on one of these 2 icons, add a small text with messages such as "Full secret copied" and "Secret key copied".


I want to emphasize again that the main feature of displaying the key is (to me at least) the most useful.
The rest I mentioned and my suggestion are just small details :)

**Comment by nightah** [comment]
Thanks @schklom that's really good feedback. The notifications are a great idea. I can add that in later today.

Just to be clear we actually aren't displaying just the secret anymore (probably is a little hard to tell because of the focus), we are displaying the full OTP URL.

This is to ensure that when we merge in some TOTP algo changes users more than likely will need/want the full OTP URL.

**Comment by schklom** [comment]
That sounds perfect ! Thanks for the hard work :)
I think I should keep this issue open until the changes are merged.
If you would like any more feedback, feel free to ask.

**Comment by nightah** [comment]
This has now been merged into the `master` tagged container, I'd expect it to be in a tagged release very soon.

I've included notifications on the button clicks with some meaningful messages for the user.

I've also removed the autofocus on the TextField so a user can see that the field actually stores the full OTP URL.
