### ISSUE TITLE
Reset Password: Your supplied password does not meet the password policy requirements.

### ISSUE THREAD

**Issue by bbros-dev** [authelia/authelia#1521]
On resetting a password with the file back-end, the user is greeted by this error message without any information about twhat the policy requirements are.

This also does not appear to be documented - apologies if I missed the docs.

Versions as of this date:

```bash
$ sudo docker-compose images                                                  
Container      Repository        Tag       Image Id       Size                                                             
----------------------------------------------------------------
authelia    authelia/authelia   latest   0d744416d5aa   26.85 MB
public      containous/whoami   latest   0f6fbbedd377   7.373 MB
secure      containous/whoami   latest   0f6fbbedd377   7.373 MB
traefik     traefik             v2.2     f965f5a1fff8   79.38 MB
```

**Comment by nightah** [comment]
The incorrect error message will be fixed in #1508, you should be getting a generic error message instead.

Can you provide an output of your Authelia logs when attempting to reset the password? This should tell us why you're getting an error when attempting to reset your password.

**Comment by bbros-dev** [comment]
Okay, are you able to share what the default policy is for the file backend?
I'm working on getting Authelia back into in a functioning state to catch the error log.

**Comment by nightah** [comment]
There is no enforced password policy for the file based backend.

The error you're seeing so related to an LDAP based backend which will be fixed in the aforementioned PR.

**Comment by bbros-dev** [comment]
You'll have to give some hint about the logging you'd like to see.

I've configured Authelia:
```yaml
log_level: debug
log_file_path: /config/authelia.log
```

That log file does not show logging with incorrect password, nor does the log show anything when the reset process breaks (the UI pop-up says 'There was an issue initiating the password reset process', but `authelia.log` is silent). 

The last entry is:

```
time="2020-12-15T15:02:05+11:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091
```

**Comment by nightah** [comment]
You should certainly see a lot more in the logs if you have it set to debug and you're attempting a password reset.

Per my other comment if you can try the use case again this time don't redirect your logging away from stdout and see what `docker logs -f authelia` tells you, we might be able to see what's going on.

**Comment by nightah** [comment]
Closing this in favour of #1535 as #1508 has been merged and I don't believe you would be receiving this specific error message anymore.
