### ISSUE TITLE
Reset password LDAP stores in plain text

### ISSUE THREAD

**Issue by Arnaud-Trouche** [authelia/authelia#1526]
Hello,

I have searched on the issues and in the documentation, I cannot see any information on that:

I have noticed that when using the reset password function, the new password of the user is stored in plain text in LDAP, is there a way to store it with any encryption ?

For information, I use the latest tagged version of Authelia on docker and using openLDAP.

**Comment by davama** [comment]
which ldap?

at least with openldap I dont see that issue but it is a different hash from what we have configured.
See end of comment https://github.com/authelia/authelia/issues/361#issuecomment-737299130

**Comment by Arnaud-Trouche** [comment]
LDAP is an openldap (on docker).

If it can help, here are the logs of a successful password change (but stored in clear):

authelia:
````
time="2020-12-11T15:48:33+01:00" level=debug msg="Notifier SMTP client successfully sent email"
time="2020-12-11T15:49:02+01:00" level=debug msg="Password of user username has been reset" method=POST path=/api/reset-password remote_ip=XXX
````
openldap
````
op=0 BIND dn="cn=bindusername,ou=users,dc=example,dc=com" method=128
op=0 BIND dn="cn=bindusername,ou=users,dc=example,dc=com" mech=SIMPLE ssf=0
op=0 RESULT tag=97 err=0 text=
op=1 SRCH base="ou=users,dc=example,dc=com" scope=2 deref=0 filter="(&(cn=username)(objectClass=inetOrgPerson))"
op=1 SRCH attr=dn displayName mail cn
op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
op=2 MOD dn="cn=username,ou=users,dc=example,dc=com"
op=2 MOD attr=userPassword
op=2 RESULT tag=103 err=0 text=
````

**Comment by james-d-elliott** [comment]
Which version are you running?

**Comment by nightah** [comment]
Authelia doesn't perform the hashing on the LDAP end, this is likely due to misconfiguration on the LDAP component.

Authelia will submit the password to the attribute as plain text and your LDAP `ppolicy` overlay should be taking care of hashing.

**Comment by davama** [comment]
@nightah 
Thanks to your comment i figured out the hashing issue on our openldap
See: https://github.com/authelia/authelia/issues/361#issuecomment-744482335

**Comment by Arnaud-Trouche** [comment]
Thank you very much for your feedback.

Indeed, setting the olcPPolicyHashCleartext to TRUE resolved this issue.
If people are in the same case than me, here is a good and well explained method : [https://kifarunix.com/implement-openldap-password-policies/](https://kifarunix.com/implement-openldap-password-policies/) 

May I suggest to add a small note in the otherwise very complete documentation of Authelia, for example on the LDAP page ? Something as short as your message is informative enough to know that when Authelia can reset password, the LDAP server must hash clear text password.
