### ISSUE TITLE
API DOC attempt

### ISSUE THREAD

**Issue by davama** [authelia/authelia#1527]
Hello,

Saw https://github.com/authelia/authelia/issues/1470 and thought that it was totally needed.

Here is my attempt...:

### Endpoints and their results

**/api/verify**
```
{
  "status": "OK",
  "data": {
    "username": "",
    "authentication_level": 0,
    "default_redirection_url": "https://authelia.com"
  }
}
```

**/api/firstfactor**

note: (`-v` switch will allow you to see the `Set-Cookie` session variable which you'll need to query other endpoints)
```
curl -v -d '{"username": "myusername", "password": "mypassword"}' -k -XPOST https://authelia.com/api/firstfactor
```
```
{
  "status": "OK"
}
```
**/api/reset-password/identity/start**
```
curl -d '{"username": "myusername"}' -k -XPOST https://authelia.com/api/reset-password/identity/start
```
```
{
  "status": "OK"
}
```
`/api/reset-password/identity/start` will also send an email to the user, so that they can reset their password

**/api/configuration**
```
curl -L -b "<my-set-cookie-session-var>" -k -XGET https://authelia.com/api/configuration
```
```
{
  "status": "OK",
  "data": {
    "available_methods": [
      "totp",
      "u2f"
    ],
    "second_factor_enabled": true,
    "totp_period": 30
  }
}
```

**/api/user/info**
```
curl -L -b "<my-set-cookie-session-var>" -k -XGET https://authelia.com/api/user/info
```
```
{
  "status": "OK",
  "data": {
    "display_name": "FirstName LastName",
    "method": "totp",
    "has_u2f": false,
    "has_totp": true
  }
}
```

**/api/secondfactor/totp/identity/start**
```
curl -L -b "<my-set-cookie-session-var>" -k -XPOST https://authelia.com/api/secondfactor/totp/identity/start
```
```
{
  "status": "OK"
}
```
`/api/secondfactor/totp/identity/start` will send an email to get user's totp QR code but it will not work unless the user is already logged in on their personal browser (would be nice if it did)

**/api/secondfactor/totp**

```
curl -L -b "<my-set-cookie-session-var>" -d '{"Token": "123456"}' -k -XPOST https://authelia.com/api/secondfactor/totp
```
```
{
  "status": "OK",
  "data": {
    "redirect": "https://authelia.com"
  }
}
```

I dont use U2F or DUO so cant help with that.

Let me know what you think.

Regards,
Dave

**edit:
Added `Token` to query `/api/secondfactor/totp`

**Comment by clems4ever** [comment]
Hello @davama , thanks for the attempt but fortunately for us @nightah is working on a swagger documentation instead. We'll go in that direction instead for maintainability. Are you ok with that?

Thanks.

**Comment by davama** [comment]
Perfectly fine!
Ill close this then.
Thanks!
