### ISSUE TITLE
Log file silent when UI shows 'There was an issue initiating the password reset process'

### ISSUE THREAD

**Issue by bbros-dev** [authelia/authelia#1535]
I've configured Authelia:
```yaml
log_level: debug
log_file_path: /config/authelia.log
```

That log file does not show logging when the reset process breaks (the UI pop-up says 'There was an issue initiating the password reset process', but `authelia.log` is silent). 

The last entry is:

```
time="2020-12-15T15:02:05+11:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091
```

Versions as of this date:

```bash
$ sudo docker-compose images                                                  
Container      Repository        Tag       Image Id       Size                                                             
----------------------------------------------------------------
authelia    authelia/authelia   latest   0d744416d5aa   26.85 MB
public      containous/whoami   latest   0f6fbbedd377   7.373 MB
secure      containous/whoami   latest   0f6fbbedd377   7.373 MB
traefik     traefik             v2.2     f965f5a1fff8   79.38 MB
```

**Comment by nightah** [comment]
That log doesn't look like it has `debug` logging turned on so I suspect something else is going on here.
Here's an example of start up with debug logging turned on with a recent container:
```
time="2020-12-15T22:58:53+11:00" level=info msg="Logging severity set to debug"
time="2020-12-15T22:58:53+11:00" level=debug msg="Storage schema is being checked to verify it is up to date"
time="2020-12-15T22:58:53+11:00" level=debug msg="Storage schema is up to date"
time="2020-12-15T22:58:53+11:00" level=debug msg="Notifier SMTP client initializing TLS configuration"
time="2020-12-15T22:58:53+11:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
```

Just for the time being to can you leave `log_file_path` commented so your logs go to stdout and check the logs with `docker logs -f authelia`?

**Comment by bbros-dev** [comment]
No, debug was on. I just showed the last line.

Inferring from behavior... it seems there might be some UI errors that don't have a corresponding backend log entry, even in debug mode.

Is that possible?

**Comment by nightah** [comment]
I'm not going to say it isn't possible but certainly the first step of the password reset process will generate logs.
```
time="2020-12-16T10:27:45+11:00" level=debug msg="Sending an email to user john (john@example.com) to confirm identity for registering a device." method=POST path=/api/reset-password/identity/start remote_ip=10.10.10.254
```

Tokens for password resets and device enrolment self destruct after initial use, so even if you visit the link with the token in question and reload the page it will not work anymore.

Can you try a password reset process from cradle to grave and include all of the logging including when the error occurs?
Happy for you to redact any sensitive information but please don't remove the entire log line.

**Comment by nightah** [comment]
@bbros-dev is there any update here? Have you managed to resolve your issue?

**Comment by bbros-dev** [comment]
Closing until I can reproduce.
