### ISSUE TITLE
[WIP] Design: Storage / Internal Authentication Provider

### ISSUE THREAD

**Issue by james-d-elliott** [authelia/authelia#1538]
### Abstract

Adding an easy to use authentication provider that exists in storage (i.e. SQL) is a long term beneficial thing. It will allow us a lot of things in the future specifically some additional api endpoints, a web admin portal, and a non-LDAP backend that allows new users to be added without reloading Authelia.

### Key Points
1. Full Access to the tooling via the API (temporarily restricted to an API key with a strong minimum length and must be manually generated by the sys-admin).
2. Adjust the docker image to use an ENV var for the location of the config file. This will allow the binary to be executed from `docker exec -it authelia_container authelia &lt;cli syntax&gt;` with full access to the storage backend. Additionally it means people can easily move the config file as they desire (minor).
3. Allow adding and modifying the users via the CLI and API.
4. Should return a 403 status code when the API endpoints are not enabled (i.e. not using internal auth). 

### API

The suggested endpoints are documented below. We only allow password operations on specific endpoints for additional security.

| Endpoint|Method|Parameters| Description                                                    |
|:----------|:--------:|:-----------:|:------------------------------------------------|
| /v1/users |GET       |N/A           |Provides a YAML format user file|
| /v1/users |POST|YAML File      |Replaces the user DB with the contents of the YAML file|
| /v1/user |GET       |N/A           |Provides a list of users (returns a []user)        |
| /v1/user/detailed |GET       |N/A           |Provides a list of users (returns a []user_detailed)|
|/v1/user  |POST    |JSON (user)          |Adds a new user (disabled/blank password)|
|/v1/user/{id}|GET     |N/A            |Gets user details    (returns a user)           |
|/v1/user/{id}/detailed|GET     |N/A            |Gets user details    (returns a user_detailed)           |
|/v1/user/{id}|PUT|JSON (user) |modifies a user (not the password)|
|/v1/user/{id}|DELETE|N/A|Deletes a user|
|/v1/user/{id}/group|POST|JSON (user_groups)|Adds user to the groups specified|
|/v1/user/{id}/group|PUT|JSON (user_groups)|Replaces user groups|
|/v1/user/{id}/password|PUT|JSON (password)|Sets a user password and hashes it if not hashed|
|/v1/group|GET|N/A|Provides a list of groups (returns a []group)|
|/v1/group/detailed|GET|N/A|Provides a list of groups (returns a []group_detailed)|
|/v1/group|POST|JSON (group)|Adds a group|
|/v1/group/{id}|GET|N/A|Gets group details (returns a group)|
|/v1/group/{id}/detailed|GET|N/A|Gets group details (returns a group_detailed)|
|/v1/group/{id}|DELETE|N/A|Deletes a group|
|/v1/group/{id}|POST|JSON (group_users)|Adds users to a group|
|/v1/group/{id}|PUT|JSON (group)|Modifies a group|

Data Structs (id values are only valid for GET):
|Name|Object Definition|
|:------:|:-----------------:|
|user|{id: int, name: string, email: string, display_name: string}|
|user_detailed|{id: int, name: string, email: string, display_name: string, groups: []group}|
|user_groups|{groups: []int}|
|password|{value: string, hashed: boolean}|
|group|{id: int, name: string, description: string}|
|group_detailed|{id: int, name: string, description: string, users: []user}|
|group_users|{users: []int}|

### CLI

The following commands can be implemented:

|Command|Description|
|:-----------:|:-----------:|
|authelia users import &lt;filename&gt;|Imports a User Provider file into the DB|
|authelia users export &lt;filename&gt;|Exports a User Provider file from the DB|
|authelia user add &lt;name&gt; &lt;display_name&gt; &lt;email&gt;|Creates a user|
|authelia user group add &lt;user&gt; &lt;group&gt;|Adds a user to a group|
|authelia user group delete &lt;user&gt; &lt;group&gt;|Removes a user from a group|
|authelia user info [--detailed] &lt;name&gt;|Shows a user|
|authelia user list [--detailed]|Shows a list of users|
|authelia user delete [--id=&lt;id&gt;] [&lt;name&gt;]|Deletes a user|
|authelia user password [--hashed,-h] &lt;name&gt; &lt;password&gt;|Sets a users password|
|authelia group add &lt;name&gt; &lt;description&gt;|creates a group|
|authelia group delete [--id=&lt;id&gt;] [&lt;name&gt;]|deletes a group|
|authelia group info [--detailed] &lt;name&gt;|Shows a group|
|authelia group list [--detailed]|Shows a list of groups|
|authelia group user add &lt;group&gt; &lt;user&gt;|Adds a user to a group|
|authelia group user delete &lt;group&gt; &lt;user&gt;|Removes a user from a group|

**Comment by kghxkgh** [comment]
Hi James, i think you missed the /detailed off the endpoint for user_detailed. (7th entry under API).

**Comment by james-d-elliott** [comment]
> Hi James, i think you missed the /detailed off the endpoint for user_detailed. (7th entry under API).

Correct, nice spot thanks!

**Comment by smcardle** [comment]
It would be better if the id were a token that could also be a string or a MongoDB ObjectId

**Comment by james-d-elliott** [comment]
Closing this as part of #3069 which can act as the sole issue for tracking this.

**Comment by main1byte** [comment]
Hello! When can we expect this discussion thread to take place? I wanted to store users in a database, and not in a strange way in a file
