### ISSUE TITLE
Converting config from nginx to haproxy

### ISSUE THREAD

**Issue by mamema** [authelia/authelia#1558]
because of redesign issues (implementing pfsense), i'm trying to switch from a working nginx config to a (partly) not working haproxy config

My issue is, that i can login with authelia, but don't get forwarded to the backend service, i'm staying on the authelia login page. 

I've tried almost everything which i can find here in github as a haproxy reference

The working redirection in NGINX was/is: error_page 401 =302 https://login.example.com/?rd=$target_url;

Enabled syslogging and i'm suprised (meh, not really) founding this:
Dec 23 17:21:46 172.17.0.1 Dec 23 18:21:46 haproxy haproxy[40179]: Unknown auth-request backend 'be_authelia'  

...because this is configured... huh?!
 
Authelia log shows:

time="2020-12-24T08:37:22+01:00" level=warning msg="https://movie.example.com/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=xx.xx.xx.xx

Newer debug snippet: 
time="2020-12-24T13:26:50+01:00" level=debug msg="Required level for the URL https://movie.example.com/ is 2" method=POST path=/api/firstfactor remote_ip=x.x.x.x

i'm not that deep into haproxy to convert this

Any hints which point me in  the right direction?

Here is my haproxy.cfg

`# Automaticaly generated, dont edit manually.
# Generated on: 2020-12-24 09:42
global
	maxconn			1000
	log			192.168.0.30:25516	syslog	debug
	stats socket /tmp/haproxy.socket level admin  expose-fd listeners
	uid			80
	gid			80
	nbproc			1
	nbthread			1
	hard-stop-after		15m
	chroot				/tmp/haproxy_chroot
	daemon
	tune.ssl.comfault-dh-param	2048
	log-send-hostname		haproxy
	server-state-file /tmp/haproxy_server_state
	lua-load		/var/etc/haproxy/luascript_http.lua
	lua-load		/var/etc/haproxy/luascript_auth-request.lua

listen HAProxyLocalStats
	bind 127.0.0.1:2200 name localstats
	mode http
	stats enable
	stats admin if TRUE
	stats show-legends
	stats uri /haproxy/haproxy_stats.php?haproxystats=1
	timeout client 5000
	timeout connect 5000
	timeout server 5000

frontend fe_http
	bind			xx.xx.xx.xx:443 name xx.xx.xx.xx:xx   ssl crt-list /var/etc/haproxy/fe_http.crt_list  
	mode			http
	log			global
	option			log-separate-errors
	option			httplog
	option			http-keep-alive
	option			forwardfor
	acl https ssl_fc
	http-request set-header		X-Forwarded-Proto http if !https
	http-request set-header		X-Forwarded-Proto https if https
	timeout client		30000
	acl			protected-frontends	hdr(host) -m reg -i ^(?i)(movie|organizr)\.example\.com
	acl			host-authelia	hdr(host) -i login.example.com
	acl			host-movie	hdr(host) -i movie.example.com
	acl			host-organizr	hdr(host) -i organizr.example.com
	acl			aclcrt_fe_http	var(txn.txnhost) -m reg -i ^([^\.]*)\.example\.com(:([0-9]){1,5})?$
	http-request set-var(txn.txnhost) hdr(host)
	http-request set-var(req.scheme) str(http)  if  !{ ssl_fc } aclcrt_fe_http
	http-request set-var(req.scheme) str(https)  if  { ssl_fc } aclcrt_fe_http
	http-request set-var(req.questionmark) str(?)  if  { query -m found } aclcrt_fe_http
	http-request set-header X-Real-IP %[src]  if   aclcrt_fe_http
	http-request set-header X-Forwarded-Proto %[var(req.scheme)]  if   aclcrt_fe_http
	 http-request set-header X-Forwarded-Host %[req.hdr(Host)]  if   aclcrt_fe_http
	http-request set-header X-Forwarded-Uri %[path]%[var(req.questionmark)]%[query]  if   aclcrt_fe_http
	 http-request lua.auth-request be_authelia /api/verify  if  protected-frontends aclcrt_fe_http
	http-response set-header Success %[var(txn.auth_response_code)]  if   aclcrt_fe_http
	http-request redirect location https://login.example.com/?rd=%[var(req.scheme)]://%[base]%[var(req.questionmark)]%[query]  if  protected-frontends !{ var(txn.auth_response_successful) -m bool } aclcrt_fe_http
	use_backend be_authelia_ipvANY  if  host-authelia aclcrt_fe_http
	use_backend be_movie_ipvANY  if  host-movie aclcrt_fe_http
	use_backend be_organizr_ipvANY  if  host-organizr aclcrt_fe_http
	use_backend be_organizr_ipvANY  if  host-organizr aclcrt_fe_http
	use_backend be_organizr_ipvANY  if  host-organizr aclcrt_fe_http

backend be_authelia_ipvANY
	mode			http
	id			102
	log			global
	timeout connect		30000
	timeout server		30000
	retries			3
	option			httpchk OPTIONS / 
	server			authelia 192.168.0.30:9091 id 103 check inter 1000  

backend be_movie_ipvANY
	mode			http
	id			104
	log			global
	timeout connect		30000
	timeout server		30000
	retries			3
	option			httpchk OPTIONS / 
	acl			remote_user_exist	var(req.auth_response_header.remote_user) -m found
	acl			remote_groups_exist	var(req.auth_response_header.remote_groups) -m found
	acl			remote_name_exist	var(req.auth_response_header.remote_name) -m found
	acl			remote_email_exist	var(req.auth_response_header.remote_email) -m found
	http-request set-header Remote-User %[var(req.auth_response_header.remote_user)]  if  remote_user_exist 
	http-request set-header Remote-Groups %[var(req.auth_response_header.remote_groups)]  if  remote_groups_exist 
	http-request set-header Remote-Name %[var(req.auth_response_header.remote_name)]  if  remote_name_exist 
	http-request set-header Remote-Email %[var(req.auth_response_header.remote_email)]  if  remote_email_exist 
	server			movie 192.168.0.30:8310 id 101 check inter 1000  

backend be_organizr_ipvANY
	mode			http
	id			105
	log			global
	timeout connect		30000
	timeout server		30000
	retries			3
	server			organizr 192.168.0.30:3000 id 106  
`

**Comment by nightah** [comment]
> Enabled syslogging and i'm suprised (meh, not really) founding this:
> Dec 23 17:21:46 172.17.0.1 Dec 23 18:21:46 haproxy haproxy[40179]: Unknown auth-request backend 'be_authelia'

This error is occurring because of the following line in your configuration:
`http-request lua.auth-request be_authelia /api/verify if protected-frontends aclcrt_fe_http`

The above based on what you have provided should be:
`http-request lua.auth-request be_authelia_ipvANY /api/verify if protected-frontends aclcrt_fe_http`

**Comment by mamema** [comment]
Woah!
Working!
Thank you very much!
