### ISSUE TITLE
2FA enrollment is difficult to understand.

### ISSUE THREAD

**Issue by jtagcat** [authelia/authelia#1560]
Related: #135

 - Rename OTP to TOTP. OTP can mean a wide variety of things.
 - Specify to the user, what security key standards are meant. U2F iirc, maybe it was WebAuthn?
Maybe subtexts explaining on what it is?
 - #1559 allow multiple tokens, and make it clear what tokens (name them!) are added, etc. I discovered multiple tokens weren't available only through testing. If a user registers 2 tokens, they could lock themselves out for some period.

The process of registering a new token was quite finicky as well. It's like buttons without any context.

**Comment by jtagcat** [comment]
Bug from downstream: git.k-space.ee/k-space/overnode-cluster/issues/30

**Comment by jtagcat** [comment]
Bug from downstream: https://git.k-space.ee/k-space/overnode-cluster/issues/30

**Comment by nightah** [comment]
Thanks for lodging the issue @jtagcat.
 
> * Rename OTP to TOTP. OTP can mean a wide variety of things.

I think perhaps part of the confusion here is that the animation on the method selection page for whatever reason isn't working anymore. Hopefully #1604 should provide a little more visual context to help the user identify this is a time based password and not HOTP.

While most advanced users know of/may understand the differences between HOTP and/or TOTP we need to keep in mind that Authelia's user base is extremely varied I'd prefer to keep things simple where possible.

Also I think it's very clear in our documentation regarding what types of [One Time Passwords](https://www.authelia.com/docs/features/2fa/one-time-password.html) currently are supported.

> * Specify to the user, what security key standards are meant. U2F iirc, maybe it was WebAuthn?
>   Maybe subtexts explaining on what it is?

While this is called out in our [README](https://github.com/authelia/authelia#features-summary) I'm not particularly averse to changing the Security Key option to indicate it currently only supports U2F.
Probably worth also updating the [Security Keys](https://www.authelia.com/docs/features/2fa/security-key.html) section in our docs to mention the standard in a little more detail.

Thoughts @clems4ever and @james-d-elliott?

> * #1559 allow multiple tokens, and make it clear what tokens (name them!) are added, etc. I discovered multiple tokens weren't available only through testing. If a user registers 2 tokens, they could lock themselves out for some period.

Supporting multiple tokens is definitely something that we plan to do, I agree that it isn't clear today to a user that only a single token can be associated with a user. We'll update our documentation to address this concern until the feature request has been addressed.

> The process of registering a new token was quite finicky as well. It's like buttons without any context.

I'd love if you could elaborate on this a little more, what would your recommendation be on how we should be addressing your concern? If the process/workflow isn't intuitive enough I'm all ears for how you think we can improve it.

Just out of curiosity, I'm assuming that you probably haven't seen the [OTP section](https://www.authelia.com/docs/features/2fa/one-time-password.html) of our documentation?

**Comment by jtagcat** [comment]
> I think perhaps part of the confusion here is that the animation on the method selection page for whatever reason isn't working anymore. Hopefully #1604 should provide a little more visual context to help the user identify this is a time based password and not HOTP.

The visual would help, but adding additional context (it's not replacing anything) would still be preferred. Multiple queues for the user, the higher chance they'll understand one of them.

> we need to keep in mind that Authelia's user base is extremely varied

Exactly. OTP (current is the base), adding a 'Time-based' to the front is just additional context. They might not know what OTP is, but when selecting, and they somewhere heard 'time something something' from the admin.

> Also I think it's very clear in our documentation regarding what types of One Time Passwords currently are supported.

Great, but the user (I mostly belong that group for Authelia), does not read the docs when pressing a button in the UI, they shouldn't have to as well. Having a reference manual next to you expected at all times isn't a reasonable asking.

> Supporting multiple tokens is definitely something that we plan to do, I agree that it isn't clear today to a user that only a single token can be associated with a user. We'll update our documentation to address this concern until the feature request has been addressed.

Thanks.

> Just out of curiosity, I'm assuming that you probably haven't seen the OTP section of our documentation?

No I'm a user, regarding Authelia for the time being.

I have critique looking at that page right away. The QR code is the only way to set up TOTP. Offer the actual details as a small text between the button and the image:
 - Authelia open on desktop
   - What if I don't have a camera? Maybe the user holds TOTP on a company, restricted, device with say no cam and mic.
     - While 'blame the admin' is a valid response, they might've not remembered that that was a thing.
 - Authelia open on phone
   - The user just goes 'I can't scan it with my phone'.
   - A screenshot or save image, and then load to qr code scanner / auth app is possible, but what normal user thinks of that? I have had users not knowing how to screenshot.
   - They would probably also think the QR code is not an image (as in you can't save it).

> I'd love if you could elaborate on this a little more, what would your recommendation be on how we should be addressing your concern? If the process/workflow isn't intuitive enough I'm all ears for how you think we can improve it.

Well when we set up 2FA, others reported the same.

Step 0 have a demo site to.. demo the product, and for people to test it out. I don't want to spin up an instance, figure out how to set it up for a bug report. Some users don't know (more often, instead they're afraid to press buttons and do things (thank you school for optimizing for helplessness)). In this case I'll re-enroll my yubis.

**Comment by jtagcat** [comment]
![image](https://user-images.githubusercontent.com/38327267/104757034-75ca6580-5754-11eb-8561-a532267f4055.png)
While logging in (I have 2fa set up), it is unsure whether I have 2FA set up. It is prompting for a token, indicating quite confidently I have it set up, yet the text below says otherwise.

**Comment by jtagcat** [comment]
![image](https://user-images.githubusercontent.com/38327267/104757705-4e27cd00-5755-11eb-995f-1cb9844f9485.png)

1) the blue button has very bad contrast, this is bad for a11y
2) "Please ignore this email if you did not initiate the process." No do not ignore this e-mail. Someone setting up 2FA for you means they have your first factor. Definitely do notify the administrator and change your password, the first factor!

**Comment by jtagcat** [comment]
While logged in, the `METHODS` button is useless. Using it you can switch between security key and OTP, yet it shows `Authenticated` for both. This is just false, unless its switching between u2f registered in the past and OTP to be used on next auth..? Is it?

Also, same thing as before, the `Not registered yet?` should be changed to `re-register, replacing your current method` or something.

**Comment by jtagcat** [comment]
I don't have a demo user or instance to test on atm, and won't set a test instance up today. I remember the experience being different on first register.

**Comment by jtagcat** [comment]
Overall, there should be more verbosity, with what a button does; and 'You are currently registering a new token'. You want to make it as self-service as possible, making sense to even an idiot.

Then they build a better idiot.

Though seriously, especially some older generations (stereotyping, sorry), will not click any buttons if not prompted or guided.

An idea on how to do this would to dedicate a space for help info. An example of this seen in use is the right bar in Migadu:
![image](https://user-images.githubusercontent.com/38327267/104768339-60aa0280-5765-11eb-8a12-fa9f2fe400aa.png)
![image](https://user-images.githubusercontent.com/38327267/104768519-bbdbf500-5765-11eb-8e63-4d316b775965.png)

**Comment by nightah** [comment]
So I've had the opportunity to come back and look at this issue, firstly to address some of your points.

> Exactly. OTP (current is the base), adding a 'Time-based' to the front is just additional context. They might not know what OTP is, but when selecting, and they somewhere heard 'time something something' from the admin.

While I don't completely agree that users might be prompted otherwise if they heard "time something something" or the likes from at admin at some point (which they also would happen to have to remember) this is simple enough to address.

![Screenshot_2021-02-02-09-36-17](https://user-images.githubusercontent.com/3339418/106596580-567f6500-65a9-11eb-8f56-80141deedf4d.png)


> I have critique looking at that page right away. The QR code is the only way to set up TOTP. Offer the actual details as a small text between the button and the image:
> 
> * Authelia open on desktop
>   
>   * What if I don't have a camera? Maybe the user holds TOTP on a company, restricted, device with say no cam and mic.
>     
>     * While 'blame the admin' is a valid response, they might've not remembered that that was a thing.
> * Authelia open on phone
>   
>   * The user just goes 'I can't scan it with my phone'.
>   * A screenshot or save image, and then load to qr code scanner / auth app is possible, but what normal user thinks of that? I have had users not knowing how to screenshot.
>   * They would probably also think the QR code is not an image (as in you can't save it).
> 
> >

I believe even at the time of your post that this may have been a dated view of the OTP registration page, here's what it actually looks like and the two buttons you'll see below allow you to copy either the OTP secret or the full OTP URL:

![Screenshot_2021-02-02-10-28-31_2560x1440](https://user-images.githubusercontent.com/3339418/106596770-97777980-65a9-11eb-9bd6-6be5d5189e8f.png)


> While logging in (I have 2fa set up), it is unsure whether I have 2FA set up. It is prompting for a token, indicating quite confidently I have it set up, yet the text below says otherwise.

Valid point, this will be adjusted as the following two examples, this shows a user that has a registered TOTP device and no registered U2F devices:

![Screenshot_2021-02-02-10-24-54](https://user-images.githubusercontent.com/3339418/106597038-f2a96c00-65a9-11eb-9557-b2e326aaed78.png)
![Screenshot_2021-02-02-10-25-11](https://user-images.githubusercontent.com/3339418/106597053-f63cf300-65a9-11eb-9a43-0a15cf1e5e19.png)


> * the blue button has very bad contrast, this is bad for a11y
> * "Please ignore this email if you did not initiate the process." No do not ignore this e-mail. Someone setting up 2FA for you means they have your first factor. Definitely do notify the administrator and change your password, the first factor!

I'll look to match the button colours with our primary buttons like on the portal (blue button/white text).
I'll adjust the footer to emphasise that the user should get in contact with an administrator, realistically it's just re-iterating what's in the body of the message.

Regarding your further point to disable the account I think that's a valid feature to be added down the track, there's a little complexity to this depending on the type of user backend so we will need to discuss and design this feature.



> While logged in, the `METHODS` button is useless. Using it you can switch between security key and OTP, yet it shows `Authenticated` for both. This is just false, unless its switching between u2f registered in the past and OTP to be used on next auth..? Is it?
> 
> Also, same thing as before, the `Not registered yet?` should be changed to `re-register, replacing your current method` or something.

Once you have authenticated with any form of 2FA, be it TOTP, Security Key or Push based notifications that session is now authenticated. The method selector is utilised at that point to change your preferred method so that next time you log back in your preferred method is presented initially.

> Overall, there should be more verbosity, with what a button does; and 'You are currently registering a new token'. You want to make it as self-service as possible, making sense to even an idiot.

I think there's a very fine line between a verbosity and a inelegant aesthetic and UX.

Whether it's surprising to you or not, this is actually the first instance where we have had a report that the 2fa enrolment process is difficult to understand. Thanks for your feedback!

**Comment by jtagcat** [comment]
> I believe even at the time of your post that this may have been a dated view of the OTP registration page, here's what it actually looks like and the two buttons you'll see below allow you to copy either the OTP secret or the full OTP URL:

Nitpicking, but `s/QRCode/QR code/`

The key left of the copy button. No idea what that does, not even playing dumb here. I'd have to try it out to see.

Now what I notice about the screenshot. I full screened the image on my 16:9 1080p 14" display. The text must be readable to a person with not the best eyesight, often sleepy, or even somewhat drunk. Right now, I don't identify with any of the mentioned, yet I can't comfortably read the text without getting closer, zooming in, or hissing eyes.

***
> While logged in, the `METHODS` button is useless. Using it you can switch between security key and OTP, yet it shows `Authenticated` for both. This is just false, unless its switching between u2f registered in the past and OTP to be used on next auth..? Is it?

> Also, same thing as before, the `Not registered yet?` should be changed to `re-register, replacing your current method` or something.

> Once you have authenticated with any form of 2FA, be it TOTP, Security Key or Push based notifications that session is now authenticated. The method selector is utilised at that point to change your preferred method so that next time you log back in your preferred method is presented initially.

I think you might've understood that wrong; The not registered button should be rephrased when conditions are met.

(As an example, not related to 2fa) It's like you'd ask the user 'don't have an account?' right after they just signed in/up.

The button there should instead say 'manage/re-register/replace 2fa/security key' or related.
