### ISSUE TITLE
Error when reading request headers: EOF

### ISSUE THREAD

**Issue by shan52** [authelia/authelia#1562]
Hi, I am getting those error in Authelia:

`error when serving connection "172.18.0.2:9091"<->"192.168.7.1:56278": error when reading request headers: EOF. Buffer size=175, contents: "....."`

I am not sure how to reproduce the error.

**Comment by james-d-elliott** [comment]
Which reverse proxy are you using? Are you using TLS inside Authelia or doing that entirely at the proxy side?

**Comment by james-d-elliott** [comment]
I'm closing since no response, if you continue to have issues feel free to reopen.
