### ISSUE TITLE
Problem using certificates_directory instruction (.pem / .cer files accepted, .crt is not)

### ISSUE THREAD

**Issue by GeoCookie** [authelia/authelia#1588]
Hi,

First, best wishes for this new year!

I am trying to use the certificate directory instruction to import my root CA certificate to Authelia but no luck.
[https://www.authelia.com/docs/configuration/miscellaneous.html#certificates-directory](url)
My goal is to have Authelia accept my private LDAP TLS certificate.

What I tried :
- I copied the root CA certificate on Authelia in the folder /config/certs/
![image](https://user-images.githubusercontent.com/43962716/104088842-fd523900-5269-11eb-91af-e4c235041010.png)
- Authelia can read the certificate
![image](https://user-images.githubusercontent.com/43962716/104088859-0d6a1880-526a-11eb-9440-770942f114b0.png)
- On the configuration file, I added these lines
  certificates_directory instruction
![image](https://user-images.githubusercontent.com/43962716/104088872-24106f80-526a-11eb-8dec-9d588ee3e7c9.png)
  skip_verify instruction
![image](https://user-images.githubusercontent.com/43962716/104088882-2ecb0480-526a-11eb-9150-3e537f62a9ab.png)
- After restarting Authelia, I cannot log on Authelia. I got an LDAP error in the logs
![image](https://user-images.githubusercontent.com/43962716/104088894-51f5b400-526a-11eb-977b-c7f2602ebba3.png)
  There is no error about the certificate import in the logs.

Some other points:
- The logs are in verbose mode
- I tried to add a “/” at the end of the certificate directory
- I tried to add the OpenLDAP certificate with the root CA cert in the directory
![image](https://user-images.githubusercontent.com/43962716/104088991-65ede580-526b-11eb-8f02-4fb1dc45f784.png)
- I cannot find the certificate on the authelia certificate store
- If I put a wrong path in the instruction, Authelia is unhappy, so the instruction seems to be correctly read
![image](https://user-images.githubusercontent.com/43962716/104089018-8fa70c80-526b-11eb-875c-b9b13f154d00.png)

I think I am missing something obvious :/ Any help appreciated

Cheers

**Comment by james-d-elliott** [comment]
Was the OpenLDAP cert signed by the RootCA? Or a SubordinateCA signed by the RootCA?

**Comment by GeoCookie** [comment]
The OpenLDAP cert is directly signed by the root ca. I have no sub ca.

Cordialement

Geoffroy Breton
Envoyé depuis un périphérique mobile, veuillez excuser les éventuelles fautes de frappes

Le 9 janv. 2021 à 20:52, James Elliott <notifications@github.com> a écrit :

﻿

Was the OpenLDAP cert signed by the RootCA? Or a SubordinateCA signed by the RootCA?

**Comment by james-d-elliott** [comment]
It's a small bug with the search logic. For now change the extension to .pem and it should work. I'll update the docs and provide a fix.

**Comment by GeoCookie** [comment]
Hey,

I changed the root ca cert with .pem : it works.
I try to declare the root ca in Docker secrets and set the certificates_directory to /run/secrets : it works too

Thank you for you help.

**Comment by james-d-elliott** [comment]
No worries, I've pushed a fix which will be merged into a patch version soon. :)
