### ISSUE TITLE
Support/Documentation for Apache Reverse Proxies?

### ISSUE THREAD

**Issue by dohlin** [authelia/authelia#1594]
I'm assuming I know the answer for this, but is there any official documentation or support for Apache reverse proxy setups?  Looking at the reverse proxy documentation section I don't see anything mentioned to this effect.  Does this mean it's not supported/documented by Authelia?  Thanks!

https://www.authelia.com/docs/deployment/supported-proxies/#:~:text=How%20Authelia%20integrates%20with%20proxies,verify%20endpoint%20exposed%20by%20Authelia.&text=The%20session%20cookie%20or%20a,used%20primarily%20for%20access%20control).

**Comment by james-d-elliott** [comment]
For authelia to work with it there must be a forward auth or module similar to ngx_http_auth_request_module. On initial inspection I can't see that documented for Apache2, will look into it further though.

**Comment by dohlin** [comment]
@james-d-elliott Gotcha...that makes sense.  Would something like this possibly work?

https://stackoverflow.com/questions/11352643/does-apache-allow-to-authorize-an-http-request-based-on-a-result-of-a-subrequest
https://metacpan.org/pod/release/CHANSEN/Authen-Simple-HTTP-0.2/lib/Authen/Simple/HTTP.pm

Thanks!

**Comment by james-d-elliott** [comment]
> @james-d-elliott Gotcha...that makes sense. Would something like this possibly work?
> 
> https://stackoverflow.com/questions/11352643/does-apache-allow-to-authorize-an-http-request-based-on-a-result-of-a-subrequest
> https://metacpan.org/pod/release/CHANSEN/Authen-Simple-HTTP-0.2/lib/Authen/Simple/HTTP.pm
> 
> Thanks!

That's what I saw that may work. But it hasn't been updated since 2006 so it's unlikely it's the same standard is the only issue.

**Comment by dohlin** [comment]
> > @james-d-elliott Gotcha...that makes sense. Would something like this possibly work?
> > https://stackoverflow.com/questions/11352643/does-apache-allow-to-authorize-an-http-request-based-on-a-result-of-a-subrequest
> > https://metacpan.org/pod/release/CHANSEN/Authen-Simple-HTTP-0.2/lib/Authen/Simple/HTTP.pm
> > Thanks!
> 
> That's what I saw that may work. But it hasn't been updated since 2006 so it's unlikely it's the same standard is the only issue.

Ahhh... somehow I missed that important detail lol.  Alright well if it’s not possible it’s not possible not the end of the world! :)

**Comment by james-d-elliott** [comment]
What we're probably going to have to do is develop a module to handle it. Going to add help wanted and some tags for this. It's a nice to have but sadly not a priority.

**Comment by james-d-elliott** [comment]
I'm closing this as I don't think Apache is really something we can realistically support. If someone wants to try to take this up and get it working please feel free to let us know.

Our suggestion for getting this working with Apache only websites is to position a compatible reverse proxy in front of them.

**Comment by roubert** [comment]
I see that this issue was closed nearly 4 years ago, but just in case someone else wonders about the same thing and finds this, it might be worth adding that I'm running Authelia (4.39.15) behind an Apache (2.4.66) proxy with just this configuration:

```
<VirtualHost *:443>
    # …
    RequestHeader set X-Forwarded-Proto "https"
    ProxyPass / http://[::1]:9091/
    # …
</VirtualHost>
```

I only use a small subset of all Authelia functionality, but for just providing OpenID Connect logins this configuration seems to work perfectly fine for me. (Maybe it'll be of value for someone else too.)
