### ISSUE TITLE
ssl_client zombie processes when using https

### ISSUE THREAD

**Issue by bartjashworth** [authelia/authelia#1605]
I run authelia in a docker container on a raspberry pi 4 (standard raspian) and the container healthcheck is causing ssl_client zombie processes to appear which crash the container and seem to make the system slow after a few days.

This seems to be caused by docker doing the healthcheck over https, when switching back the container to http the problem disappears.

Is it possible to change the healthcheck to be run over http even though the container uses https?

Thanks.

**Comment by nightah** [comment]
Authelia only binds to the specified port either with TLS on or off.

You can't have Authelia running with TLS but the healthcheck probing over http.

**Comment by nightah** [comment]
You can alternatively start the container with `--no-healthcheck` and just disable the healthcheck and run over https.

**Comment by bartjashworth** [comment]
Ok thanks, disabling the container healthcheck is a valid workaround until that docker issue gets sorted.

**Comment by nightah** [comment]
Are we okay to close this issue off then?
