### ISSUE TITLE
Authelia and Bitwarden

### ISSUE THREAD

**Issue by RefineryX** [authelia/authelia#1622]
Hi,

I use Authelia along with traefik and over the past couple of weeks have been struggling to get Authelia working with Bitwarden. 

I have managed to overcome the issues with the desktop app not being able to login by adding the following to be log file:
```access_control:
  default_policy: deny
  rules:
    # Required so Bitwarden apps can connect
    - domain: pw.mydomain.com
      policy: bypass
      resources:
        - ^/api.*$
        - ^/identity.*$
  ```

However, I am unable to get my Safari web extension working. Upon trying to login, I get the following error:
<img width="363" alt="Screenshot 2021-01-21 at 23 22 48" src="https://user-images.githubusercontent.com/46373533/105424630-95bfc480-5c3f-11eb-88be-2c95fce9f60a.png">

while inspecting the application, I see three errors:
```
[Error] Origin file:// is not allowed by Access-Control-Allow-Origin.
[Error] Fetch API cannot load https://pw.mydomain.com/api/accounts/prelogin due to access control checks.
[Error] Failed to load resource: Origin file:// is not allowed by Access-Control-Allow-Origin. (prelogin, line 0)
```
When disabling Authelia, it allows me to login. Anyone know how I am able to overcome this particular issue and help me login?

**Comment by james-d-elliott** [comment]
This sounds like you're setting the `Access-Control-Allow-Origin` header (we don't set this) with a rule preventing the file:// type, can you use your browser dev tools to confirm the existence of this header and its value?

**Comment by james-d-elliott** [comment]
@nightah uses Bitwarden with Authelia I believe, and he mentioned these issues may be related:

https://github.com/dani-garcia/bitwarden_rs/issues/629
https://github.com/dani-garcia/bitwarden_rs/pull/639

**Comment by RefineryX** [comment]
Thanks for your reply, really appreciate it.

Ahh yes, that is the same error. So it seems perfectly without Authelia but when I enable Authelia it has an issue logging in. I initially thought it might have been my traefik and have previously reported the issue via https://community.traefik.io/t/cors-error-bitwarden-safari-extension/9372.

> This sounds like you're setting the `Access-Control-Allow-Origin` header (we don't set this) with a rule preventing the file:// type, can you use your browser dev tools to confirm the existence of this header and its value?

I have posted my traefik config at https://community.traefik.io/t/cors-error-bitwarden-safari-extension/9372.

I have checked the web browser and found this screen. Hope this is the information you requested.

<img width="597" alt="Screenshot 2021-01-22 at 19 21 59" src="https://user-images.githubusercontent.com/46373533/105536388-2c47c080-5ce8-11eb-8e73-5bf716c61c81.png">

Thanks in advance :) Really appreciate your direction.

**Comment by nightah** [comment]
I think some of the other CORS headers are set through pre-flight options per the PR above:

> Changed to only add Allow-Origin to all requests and move the others to preflight OPTIONS request.

https://github.com/authelia/authelia/issues/648 is seems relevant too.

In attempts to isolate the issue I would try bypassing all OPTIONS request entirely (this needs to be done at the Traefik level per my above link).

**Comment by RefineryX** [comment]
Thanks. I just read 648 and seems similar. 
From what I understand, there seems to be a PR pending as part of 648 that will potentially fix my issue?

Within my treafik config, I have ``GET``, ``OPTIONS`` and ``PUT`` under ``accessControlAllowMethods`` without the authelia middleware enabled and it works perfectly. ([Full config part of this link](https://community.traefik.io/t/cors-error-bitwarden-safari-extension/9372)).

However, as soon as I enable the authelia middleware, I am unable to login via the safari browser. To enable the middleware, I am using ``traefik.http.routers.bitwarden-ui.middlewares=chain-authelia@file`` in the docker-compose file.

Hoping this is the info you asked for? Apologies for my lack of knowledge, I'm still trying to piece everything together at this stage. So far, everything is working fine between traefik and authelia but just this issue.

**Comment by nightah** [comment]
The WIP PR is looking to give you more flexibility to provide all the configuration in one place.

As it's not finished right now what you need to do is have an additional rule for Bitwarden in Traefik where you use the Method matcher [here](https://doc.traefik.io/traefik/v2.0/routing/routers/) to exclude the Authelia middleware for the `OPTIONS` method.

**Comment by nightah** [comment]
How'd you go with this @RefineryX?

If you're still having issues can I suggest perhaps getting in touch over on Matrix or Discord?
