### ISSUE TITLE
infinite redirects

### ISSUE THREAD

**Issue by mikensan** [authelia/authelia#1624]
[configuration.yml.txt](https://github.com/authelia/authelia/files/5853533/configuration.yml.txt)
[docker-compose.yml.txt](https://github.com/authelia/authelia/files/5853534/docker-compose.yml.txt)
[middlwares.yml.txt](https://github.com/authelia/authelia/files/5853535/middlwares.yml.txt)

**Issue:** When browsing to a website protected by authelia, it infinitely redirects to itself resulting in a very long URL / Header. This of course errors chrome out.
**Environment**: Docker / Traefik 2 / Authelia / middleware files / secrets

Within the configuration file, if I add authelia.example.com with bypass, this fixes the issue.
However in the examples, I do not see this done - yet I assume it works as intended?

What lead me here was my original config has authelia set to bypass and whenever I went to a site protected by authelia it would let me regardless of what user I used. In my files I have plexpy restricted to subject: "user:bob" however I can access the site with another user account.
I thought possibly this bypass I set for authelia was allowing this behavior, since technically the redirect URL contains authelia in it.

**Comment by james-d-elliott** [comment]
Disable the Authelia middleware for the Authelia container. What's happening is:

Visit app.example.com -> check authelia for auth (fowardAuth middleware) -> KO -> redirect to authelia -> check authelia for auth (forwardAuth middleware) -> KO - redirect to authelia -> repeat.

**Comment by james-d-elliott** [comment]
By the way, you can define the middleware as part of the docker labels if you want. I can share my configuration as an example when I get home.

**Comment by mikensan** [comment]
> 
> 
> Disable the Authelia middleware for the Authelia container, your middleware only should exist on containers that need protecting, authelia is protected by default. What's happening is:
> 
> Visit app.example.com -> check authelia for auth (fowardAuth middleware) -> KO -> redirect to authelia -> check authelia for auth (forwardAuth middleware) -> KO - redirect to authelia -> repeat.

Perfect! I was following a guide from Serve The Home and that's how I ended up this way. I had questions exactly that, but when I saw the configuration example in this github I was a little confused. I saw the middlware defined within the authelia service in docker-compose.yml, and my issue was I assume that by defining it there, also meant it was being used for authelia.

Cool. And now I properly get Forbidden, happy days! So I wasn't crazy in that the bypass for authelia defeats using Subject:.

**Comment by james-d-elliott** [comment]
Yeah there is no point using bypass with a subject, we should maybe add a log warning about it. You have to have already done 1FA for a subject to work.
