### ISSUE TITLE
Remember 2FA authentication method preference on a per-device/browser basis.

### ISSUE THREAD

**Issue by ddimick** [authelia/authelia#1699]
My use case is that some devices (like a phone) I want to use DUO push, but other devices (like a desktop) I want to use a hardware token. It's an extra step to change the 2FA method every time I switch between those devices.

Perhaps Authelia could set a cookie or use some other method to remember which 2FA method the user most recently used on that device, and offer it by default.

**Comment by james-d-elliott** [comment]
Thanks for suggesting this idea.

It's a low priority as we have other things on our table at this time. However we've got a brief design idea that should suffice:

## Design

1. New cookie :
  * has a suffix added to the main cookie name (i.e. `_user`, `_local`, `_alt`, `_browser`)
  * has a value of a json struct representing browser specific settings
2. New API endpoint
  * similar to `/api/user/info` that resolves browser specific settings vs user settings and merges them (browser takes precedence)
  * remove method from `/api/user/info`
  * endpoint something like `/api/user/browser` or `/api/user/info/browser` or `/api/user/info/local`
  
Remove method field from /api/user/info

**Comment by pbek** [comment]
I'm waiting very eagerly for such a feature. 😁 

A configurable lifetime for that cookie would also be great to get something like "Remember this device for 30days".

**Comment by joggs** [comment]
This! It would simplify things alot!
