### ISSUE TITLE
Use config for hash-password

### ISSUE THREAD

**Issue by ThinkChaos** [authelia/authelia#1709]
It would be nice to be able to pass `--config` to hash-password to avoid having to duplicate the info in the config on the CLI.

**Comment by nightah** [comment]
This would be possible to do and not overly difficult, I envisage that you would need to pass in both the config and the specific username that you're passing the hash in so it knows what to replace.

**Comment by ThinkChaos** [comment]
Sorry I wasn't clear, I was thinking of reading the config.yml's `authentication_backend.file.password` section to avoid having to pass `-i`, `-k`, `-m`, etc. to `authelia hash-password`.

**Comment by AlexGustafsson** [comment]
@ThinkChaos could you take a look at #2047 to see if that would fit your use case?

I might be mistaken, but I think you should be able to test it out using Docker once the pipeline passes:

```sh
docker run authelia/authelia:PR2047 hash-password --help
docker run authelia/authelia:PR2047 hash-password --config ./my-config.yml 'password'
```

**Comment by ThinkChaos** [comment]
I can confirm your PR works, I just had to adjust the command to:

    docker run -v "$PWD"/authelia/data:/data:ro authelia/authelia:PR2047 -- authelia hash-password --config /data/configuration.yml badpassword
