### ISSUE TITLE
Rewritten url via firefox plugin privacy redirect is not properly redirect

### ISSUE THREAD

**Issue by alexw1982** [authelia/authelia#1711]
I am having a strange issue when hitting authelia from a url that was rewritten with [privacy redirect](https://github.com/SimonBrazell/privacy-redirect).
I run [invidious](https://github.com/iv-org/invidious) on yt.mydomain.com and privacy redirect rewrites all youtube.com urls to yt.mydomain.com urls. 
When I access yt.mydomain.com directly the page opens as expected. When I open youtube.com that is rewritten into yt.mydomain.com the following behaviour can be reproduced on my machine every time:
- first visit via the rewritten url: I am asked to login and provide my 2FA totp and get redirected to yt.mydomain.com.
- On the second visit to a rewritten url from the same environment I get again redirected to `/2fa/one-time-password?rd=https%3A%2F%2Fyt.mydomain.com%2F%3Fquality%3Ddash` and am greeted with the green checkmark / authenticated message but I am not redirect anymore.
Setup Notes: 
- I have two policies setup one_factor for LAN access and two_factor for non-LAN access. However, i am asked to the 2FA totp regardless of the network I am on. When I disable 2FA in authelia the behavior is similar but I get redirect to `/authenticated` instead of `/2fa/one-time-password?rd=https%3A%2F%2Fyt.mydomain.com%2F%3Fquality%3Ddash`
- Authelia and invidious run via docker containers and are reverse proxied via nginx (following the example from the authelia documentation)

relevant authelia.log entries:

```
time="2021-02-09T23:28:13+01:00" level=debug msg="Mark authentication attempt made by user alexw1982" method=POST path=/api/firstfactor remote_ip=87.123.280.69
time="2021-02-09T23:28:13+01:00" level=debug msg="Credentials validation of user alexw1982 is ok" method=POST path=/api/firstfactor remote_ip=87.123.280.69
time="2021-02-09T23:28:13+01:00" level=debug msg="Required level for the URL https://yt.mydomain.com/results?search_query=authelia is 2" method=POST path=/api/firstfactor remote_ip=87.123.280.69
time="2021-02-09T23:28:13+01:00" level=warning msg="https://yt.mydomain.com/results?search_query=authelia requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=87.123.280.69
time="2021-02-09T23:31:28+01:00" level=info msg="Access to https://yt.mydomain.com/results?search_query=authelia&quality=dash&autoplay=1 is not authorized to user , sending 401 response" method=GET path=/api/verify remote_ip=192.168.180.4
time="2021-02-09T23:31:46+01:00" level=info msg="Access to https://yt.mydomain.com/results?search_query=authelia&quality=dash&autoplay=1 is not authorized to user , sending 401 response" method=GET path=/api/verify remote_ip=192.168.180.4
```

I hope there is a way to fix this...

**Comment by alexw1982** [comment]
Additional note: yt.mydomain.com has the policy set to one_factor by default

**Comment by nightah** [comment]
```
time="2021-02-09T23:31:28+01:00" level=info msg="Access to https://yt.mydomain.com/results?search_query=authelia&quality=dash&autoplay=1 is not authorized to user , sending 401 response" method=GET path=/api/verify remote_ip=192.168.180.4
time="2021-02-09T23:31:46+01:00" level=info msg="Access to https://yt.mydomain.com/results?search_query=authelia&quality=dash&autoplay=1 is not authorized to user , sending 401 response" method=GET path=/api/verify remote_ip=192.168.180.4
```

Implies that you're not logged in/authenticated, is there a session cookie for Authelia in that scenario?

Can you provide your Authelia ACLs?

**Comment by alexw1982** [comment]
Sure - see full config below
Note: `AUTHELIA_JWT_SECRET_FILE` and `AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE` are passed as env variables...

```
###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug
log_file_path: /config/authelia.log
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
#jwt_secret: a-super-secret
#default_redirection_url: https://auth.mydomain.com
totp:
  issuer: mydomain.com

#duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
 # Disable both the HTML element and the API for reset password functionality
  disable_reset_password: true
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny

  networks:
    - name: LAN
      networks:
        - 192.168.178.0/24
    - name: VPN
      networks:
        - 192.168.180.0/24
    - name: HL
      networks:
        - 192.168.179.0/24

  rules:

    - domain:
      - auth.mydomain.com
      policy: bypass

    - domain:
      - yt.mydomain.com
      - search.mydomain.com
      - home.mydomain.com
      - docs.mydomain.com
      policy: bypass
      networks:
        - LAN
        - VPN
      
    - domain:
      - search.mydomain.com
      - yt.mydomain.com
      - home.mydomain.com
      - docs.mydomain.com
      policy: one_factor
      subject:
        - user:alexw1982

    - domain: "*.mydomain.com"
      policy: two_factor
      subject:
        - user:alexw1982

session:
  # The name of the session cookie. (default: authelia_session).
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  #  secret: unsecure_session_secret
  # The time in seconds before the cookie expires and session is reset.
  expiration: 60m # 1 hour
  # The remember me duration.
  # Value of 0 disables remember me.
  # Value is in seconds, or duration notation. See: https://docs.authelia.com/configuration/index.html#duration-notation-format
  # Longer periods are considered less secure because a stolen cookie will last longer giving attackers more time to spy
  # or attack. Currently the default is 1M or 1 month.
  remember_me_duration:  1M
  # The inactivity time in seconds before the session is reset.
  inactivity: 5m # 5 minutes

  # The domain to protect.
  # Note: the login portal must also be a subdomain of that domain.
  domain: mydomain.com # Should match whatever your root protected domain is

  # The redis connection details (optional)
  # If not provided, sessions will be stored in memory
  #redis:
  #  host: redis
  #  port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  # The number of failed login attempts before user is banned.
  # Set it to 0 to disable regulation.
  max_retries: 3
  # The time range during which the user can attempt login before being banned.
  # The user is banned if the authentication failed `max_retries` times in a `find_time` seconds window.
  # Find Time accepts duration notation. See: https://docs.authelia.com/configuration/index.html#duration-notation-format
  find_time: 120
  # The length of time before a banned user can sign in again.
  # Find Time accepts duration notation. See: https://docs.authelia.com/configuration/index.html#duration-notation-format
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: mail@mydomain.com
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    host: smtp.mydomain.org
    port: 465
    sender: root@mydomain.com
```

**Comment by james-d-elliott** [comment]
Can you try without one_factor regardless of network? These entries indicate something is wrong with your NAT hairpin setup or the plugin is doing something odd (note the IP is `87.123.280.69`):

```
time="2021-02-09T23:28:13+01:00" level=debug msg="Mark authentication attempt made by user alexw1982" method=POST path=/api/firstfactor remote_ip=87.123.280.69
time="2021-02-09T23:28:13+01:00" level=debug msg="Credentials validation of user alexw1982 is ok" method=POST path=/api/firstfactor remote_ip=87.123.280.69
time="2021-02-09T23:28:13+01:00" level=debug msg="Required level for the URL https://yt.mydomain.com/results?search_query=authelia is 2" method=POST path=/api/firstfactor remote_ip=87.123.280.69
time="2021-02-09T23:28:13+01:00" level=warning msg="https://yt.mydomain.com/results?search_query=authelia requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=87.123.280.69
```

**Comment by alexw1982** [comment]
With two_factor completely disabled in the policies, the behavior is the same but I dont't end up on the `/2fa/one-time-password?rd=https%3A%2F%2Fyt.mydomain.com%2F%3Fquality%3Ddash` page of authelia on the second time I access the url but on the ´/authenticated´ page as a logged-in user (no redirect - note that the ´?rd=https%3A%2F%2Fyt.mydomain.com%2F%3Fquality%3Ddash´ part of the URL is missing with one_factor. 

Regarding the IP - that is my mistake - I did not want to put my IP on github. I modified from a proper IP address that ends with ´.221´

my network setup is relativly common - normal https / 443/tcp - NAT is done via pfsense to my internal server without any special configuration

**Comment by alexw1982** [comment]
I've looked further into this. The issue seems to be isolated to firefox only. The plugin is also available for chrome and with firefox / chrome having only the plugin installed, there is no issue with chrome...

**Comment by james-d-elliott** [comment]
At least we've eliminated browser and the possible network issue as a possibility. The issue likely is with the plugin, but may be with Authelia. If you visit https://youtube.com what happens? Does it send you to URLs like `/2fa/one-time-password?rd=https%3A%2F%2Fyt.mydomain.com` or does it have the query string at the end too?

**Comment by alexw1982** [comment]
When I am logged out of authelia and visit youtube.com for the first time, I am redirected to `https://auth.mydomain.com/?rd=https%3A%2F%2Fyt.mydomain.com%2F%3Fquality%3Ddash`. After a successful login into the authelia account I am redirected to `https://yt.mydomain.com/feed/popular` (a redirect happens automatically from `/quality/dash` to `/feed/popular` and is the expected behavior). Overall the behavior is 100% as expected.

when I open youtube.com again after that process I end up at `https://auth.mydomain.com/2fa/one-time-password?rd=https%3A%2F%2Fyt.mydomain.com%2F%3Fquality%3Ddash`. Once I type in the correct TOTP, I am redirected to `https://yt.mydomain.com/feed/popular`. This behavior is not expected as only one_factor is set for the subdomain yt.mydomain.com.

When I visit the URL youtube.com for a third time I end up at `https://auth.mydomain.com/2fa/one-time-password?rd=https%3A%2F%2Fyt.mydomain.com%2F%3Fquality%3Ddash` with the message 'authenticated' (see screenshot below) and this is where it ends. This behavior is obviously also not expected ;-).

<img src="https://user-images.githubusercontent.com/11628284/107705393-ef576400-6cbe-11eb-8104-6a68041a0412.png" width="350" >

**Comment by james-d-elliott** [comment]
I have a feeling it's plugin related, I'll try to set aside some time this weekend to test.

**Comment by alexw1982** [comment]
Thanks a lot - this is so much appreciated!

**Comment by james-d-elliott** [comment]
This is most likely a bug with nginx stripping & chars from URLs. Can be overcome using the Set Misc modules set_escape_uri. If this is not the case if FetchAPI is being used it's not configured to appropriately follow redirects, if XHR's are being used then the only resolution is to use FetchAPI instead of XHRs.
