### ISSUE TITLE
Reset Active Directory password not working due to insufficient access rights

### ISSUE THREAD

**Issue by Chrisiesmit93** [authelia/authelia#1715]
I am trying to setting up Authelia with Active Direcotry integration for my Traefik proxy.
All is working fine, except that AD users cannot change their own password via password reset, I'll get the following error:
`msg="Unable to update password. Cause: LDAP Result Code 50 \"Insufficient Access Rights\": 00000005: SecErr: DSID-031A11B9, problem 4003 (INSUFF_ACCESS_RIGHTS), data 0\n\x00"`

In my AD I created user "Authelia" with (for testing) _full access_ on top domain level, including:
(as per: https://support.microfocus.com/kb/doc.php?id=7023371)
- Replicating Directory Changes
- Replicating Directory Changes All
- Replicating Directory Changes in Filtered Set
- Replication synchronization
- Create, delete, and manage user accounts
- Reset user passwords and force password change at next logon
- Read all user information

The password change process is working when I am using the Administrator account, so the process is okay, only the Authelia needs more permissions than "Full Access" ??

**my authelia configuration.yml file**
```host: 0.0.0.0
port: 9091
log_level: info

default_redirection_url: https://www.<DOMAIN.COM>

totp:
  issuer: authelia.com
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  refresh_interval: always

  ldap:
    implementation: activedirectory
    url: ldaps://dc-01.<DOMAIN.COM>:636
    base_dn: dc=<DOMAIN>,dc=<COM>
    username_attribute: sAMAccountName
    additional_users_dn: OU=Personal,OU=Account,OU=<DOMAIN>
    users_filter: (&({username_attribute}={input})(objectCategory=person)(objectClass=user))
    additional_groups_dn: OU=Personal,OU=Account,OU=<DOMAIN>
    groups_filter: (&(member={dn})(objectclass=group))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    user: CN=Authelia,OU=Service,OU=Account,OU=<DOMAIN>,DC=<DOMAIN>,dc=<COM>
    start_tls: false
    tls:
      server_name: dc.<DOMAIN.COM>
      skip_verify: true
      minimum_version: TLS1.2

access_control:
  default_policy: deny
  rules:
    - domain: "login.<DOMAIN.COM>"
      policy: bypass
    - domain: "*.<DOMAIN.COM>"
      policy: bypass
      networks:
        - 192.168.1.0/24
    - domain: "*.<DOMAIN.COM>"
      policy: two_factor

session:
  name: authelia_session
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  domain: <DOMAIN.COM>

  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 5m

storage:
  mysql:
    host: mariadb
    port: 3306
    database: authelia
    username: authelia

notifier:
  disable_startup_check: false
  smtp:
    host: mail.<DOMAIN.COM>
    port: 587
    username: authelia@<DOMAIN.COM>
    startup_check_address: authelia@<DOMAIN.COM>
    sender: authelia@<DOMAIN.COM>
    subject: "{title}"
    tls:
      server_name: mail.<DOMAIN.COM>
      skip_verify: true```

**Comment by Chrisiesmit93** [comment]
Extra info:
If I remove all delegations from user "Authelia" and add it to the group "Domain Admins", it works as expected.

But that is not how it should work, delegations for password change should be sufficient for this task.

**Comment by james-d-elliott** [comment]
> 
> 
> I am trying to setting up Authelia with Active Direcotry integration for my Traefik proxy.
> All is working fine, except that AD users cannot change their own password via password reset, I'll get the following error:
> `msg="Unable to update password. Cause: LDAP Result Code 50 \"Insufficient Access Rights\": 00000005: SecErr: DSID-031A11B9, problem 4003 (INSUFF_ACCESS_RIGHTS), data 0\n\x00"`
> 
> In my AD I created user "Authelia" with (for testing) _full access_ on top domain level, including:
> (as per: https://support.microfocus.com/kb/doc.php?id=7023371)
> 
>     * Replicating Directory Changes
> 
>     * Replicating Directory Changes All
> 
>     * Replicating Directory Changes in Filtered Set
> 
>     * Replication synchronization
> 
>     * Create, delete, and manage user accounts
> 
>     * Reset user passwords and force password change at next logon
> 
>     * Read all user information
> 
> 
> The password change process is working when I am using the Administrator account, so the process is okay, only the Authelia needs more permissions than "Full Access" ??
> 
> **my authelia configuration.yml file**
> 
> ```
> port: 9091
> log_level: info
> 
> default_redirection_url: https://www.<DOMAIN.COM>
> 
> totp:
>   issuer: authelia.com
>   period: 30
>   skew: 1
> 
> authentication_backend:
>   disable_reset_password: false
>   refresh_interval: always
> 
>   ldap:
>     implementation: activedirectory
>     url: ldaps://dc-01.<DOMAIN.COM>:636
>     base_dn: dc=<DOMAIN>,dc=<COM>
>     username_attribute: sAMAccountName
>     additional_users_dn: OU=Personal,OU=Account,OU=<DOMAIN>
>     users_filter: (&({username_attribute}={input})(objectCategory=person)(objectClass=user))
>     additional_groups_dn: OU=Personal,OU=Account,OU=<DOMAIN>
>     groups_filter: (&(member={dn})(objectclass=group))
>     group_name_attribute: cn
>     mail_attribute: mail
>     display_name_attribute: displayName
>     user: CN=Authelia,OU=Service,OU=Account,OU=<DOMAIN>,DC=<DOMAIN>,dc=<COM>
>     start_tls: false
>     tls:
>       server_name: dc.<DOMAIN.COM>
>       skip_verify: true
>       minimum_version: TLS1.2
> 
> access_control:
>   default_policy: deny
>   rules:
>     - domain: "login.<DOMAIN.COM>"
>       policy: bypass
>     - domain: "*.<DOMAIN.COM>"
>       policy: bypass
>       networks:
>         - 192.168.1.0/24
>     - domain: "*.<DOMAIN.COM>"
>       policy: two_factor
> 
> session:
>   name: authelia_session
>   expiration: 1h
>   inactivity: 5m
>   remember_me_duration: 1M
>   domain: <DOMAIN.COM>
> 
>   redis:
>     host: redis
>     port: 6379
> 
> regulation:
>   max_retries: 5
>   find_time: 2m
>   ban_time: 5m
> 
> storage:
>   mysql:
>     host: mariadb
>     port: 3306
>     database: authelia
>     username: authelia
> 
> notifier:
>   disable_startup_check: false
>   smtp:
>     host: mail.<DOMAIN.COM>
>     port: 587
>     username: authelia@<DOMAIN.COM>
>     startup_check_address: authelia@<DOMAIN.COM>
>     sender: authelia@<DOMAIN.COM>
>     subject: "{title}"
>     tls:
>       server_name: mail.<DOMAIN.COM>
>       skip_verify: true```
> ```

Can you login as that user and change other user passwords? That's probably the next thing to test. The DSID-031A11B9 error is from MSAD, not Authelia itself.

**Comment by james-d-elliott** [comment]
Also since you linked that article I'm assuming you checked the adminCount attribute?

**Comment by Chrisiesmit93** [comment]
My fault, I didn't reset the adminCount value, I changed it to 0 and now it works as expected.
Sorry for the inconvenience.

**Comment by james-d-elliott** [comment]
> 
> 
> My fault, I didn't reset the adminCount value, I changed it to 0 and now it works as expected.
> Sorry for the inconvenience.

No worries! Glad it's solved.
