### ISSUE TITLE
No indication when typing TOTP on OTP page

### ISSUE THREAD

**Issue by davama** [authelia/authelia#1720]
Using v4.26.1

Looks like this was introduced in v4.26.0

On v2.25.2
![image](https://i.imgur.com/AOCDJpR.png)

After:
![image](https://i.imgur.com/DZLGG8u.png)

Is that normal? I can see it being highlighted as you type, but faintly (especially if using dark/grey theme).
Any change to show at least a * dot ?

Thanks!

**Comment by davama** [comment]
Although seeing the actual TOTP digits as you type would be helpful too :)

**Comment by nightah** [comment]
Thanks for the report @davama, PR to fix this should be merged soon.
