### ISSUE TITLE
pihole admin URL with traefik 2 reverse proxy - infinite authentication

### ISSUE THREAD

**Issue by CharlesGillanders** [authelia/authelia#1730]
I have a traefik 2 reverse proxy setup and working with Authelia for a variety of services.  All of them work except for pihole's administrative URL.

I can access the pihole service using https://pihole.example.com/ but attempting to connect to https://pihole.example.com/admin  keeps returning to the authelia screen - it shows authenticated but I'm still unable to connect to the pihole admin service.

When connecting to a non admin URL I see the authelia_session coookie in the request headers; when connecting to the admin URL I don't see the session cookie.

I can provide authelia and traefik configurations if it would help.

**Comment by james-d-elliott** [comment]
Probably the traefik configuration.. but that wouldn't explain why your browser is not sending a cookie that it should be sending. If session domain is setup to `example.com` then this is very strange. Cookies are meant to be sent by your browser when a domain that matches the cookie is visited. The only other possible explanation is `http://` URL's, any request over http will never be sent the Authelia cookie for obvious security concerns.

**Comment by james-d-elliott** [comment]
Did you end up solving this Charles?
