### ISSUE TITLE
TOTP code cannot be entered on Android Chrome

### ISSUE THREAD

**Issue by ViRb3** [authelia/authelia#1735]
After the 4.26 update, both of my Android devices running latest Chrome cannot enter the TOTP code. The boxes on this update don't look square anymore, they look like tall rectangles. Initially the first rectangle is selected, and no matter how much I type in it, no text appears, and the selection does not move to the next boxes. There is virtually no way to enter the TOTP so I had to downgrade to 4.25.2.

Device specs:
- OnePlus 5T, Android 11, Chrome 88.0
- Xiaomi Mi A3, Android 11, Chrome 88.0

**Comment by davama** [comment]
https://github.com/authelia/authelia/issues/1720

PR already resolved this

**Comment by ViRb3** [comment]
Thanks for the heads up! @nightah can you please make a release? In my case it's not only a visual issue, but also practically prevents me from entering the code.

**Comment by james-d-elliott** [comment]
Released!
