### ISSUE TITLE
Authelia should show factors that have already been registered

### ISSUE THREAD

**Issue by clems4ever** [authelia/authelia#176]
When the user authenticate for the first time, he can see the instructions to touch the token or get a one-time password while he did not even register any secret yet.

It might be a bit confusing to be told to touch the token while the security does not even blink...

What I propose is the following: 
- If first authentication, the user should be proposed to register at least one of the two available second factors.
- After registration, the user can authenticate only with the option(s) he registered.
- He can always register a new secret for any type of second factors whatever he has already.
- He can use several types of second factors: like today.

**Comment by jmccoy555** [comment]
Should there also be an option to remove already registered devices, or may easier to implement an option to reset all?

**Comment by naggie** [comment]
This would be very useful, particularly the part about the first time.

**Comment by clems4ever** [comment]
The original purpose of the issue has been solved and now the user gets a message telling no device has been registered.

@jmccoy555 , being able to remove a registered device is not yet possible from the portal. I'll file a dedicated issue for that.
