### ISSUE TITLE
Docker Container Unhealthy

### ISSUE THREAD

**Issue by natpuch** [authelia/authelia#1781]
Hello everyone!

I am trying to install Authelia without luck. I am following the "Lite Deployment" method but the Docker container is in an unhealthy state and starts and stops in a loop.

I tried figuring out what is the problem so I checked the `healthcheck.sh` as in #1461.
I get the following error:
> wget: can't connect to remote host (127.0.0.1): Connection refused

Here is the address "wgeted":
> http://localhost:9091/api/state

Is it due to a problem with my configuration?

**Comment by james-d-elliott** [comment]
What's your host and port value set to in the config?

**Comment by natpuch** [comment]
I have let the defaults:


```
host: 0.0.0.0
port: 9091
```

**Comment by nightah** [comment]
Can you paste your Authelia logs please?
Usually a restart loop might indicate incorrect configuration, the logs should help us identify what's going on.

**Comment by james-d-elliott** [comment]
If you continue to have the issue please reopen this or create another issue. I'm pretty sure you mentioned you decided to go a different route.
