### ISSUE TITLE
Errors in the log when failing auth

### ISSUE THREAD

**Issue by jclendineng** [authelia/authelia#1782]
I am not sure if this is expected behavior, when I am testing auth I get the below error in the log when I fail to auth.  Everything works as expected minus this log entry:

time="2021-03-06T16:06:51-05:00" level=error msg="Credentials are wrong for user XXXX" method=POST path=/api/firstfactor remote_ip="" stack="github.com/authelia/authelia/internal/middlewares/authelia_context.go:64  (*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/handlers/response.go:110            handleAuthenticationUnauthorized\ngithub.com/authelia/authelia/internal/handlers/handler_firstfactor.go:115 FirstFactorPost.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49  AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.3.5/router.go:414                           (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14       LogRequestMiddleware.func1\ngithub.com/authelia/authelia/internal/middlewares/strip_path.go:20        StripPathMiddleware.func1\ngithub.com/valyala/fasthttp@v1.19.0/server.go:2166                        (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.19.0/workerpool.go:223                     (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.19.0/workerpool.go:195                     (*workerPool).getCh.func1\nruntime/asm_amd64.s:1374 goexit"

**Comment by james-d-elliott** [comment]
That's expected except the goexit and stack trace. You're using the File Auth provider, have you checked your argon2id settings are tuned for your system?

https://www.authelia.com/docs/configuration/authentication/file.html#password-hash-algorithm-tuning

**Comment by james-d-elliott** [comment]
Oh never mind that's expected if the credentials are wrong.
