### ISSUE TITLE
Feature request: Support HTTP headers for access_control

### ISSUE THREAD

**Issue by dchidell** [authelia/authelia#1787]
The networks directive as part of access_control looks to use source IP address. This works great, until you have something sitting in the way (in my case, CloudFlare). 

It would be great to be able to check other HTTP headers (like X-Forwarded-For) for this information. User agent would be useful too.

**Comment by james-d-elliott** [comment]
We currently support X-Forwarded-For if present, then fall back to the connection IP. Are you having issues with it?

**Comment by dchidell** [comment]
I tried it briefly and it didn't work - however I couldn't find anything in the docs to show that X-Forwarded-For was supported so assumed it wasn't. I checked here: https://www.authelia.com/docs/configuration/access-control.html#networks

I'll give it another go and actually verify these headers are in place, An error my end combined with my lack of finding it in the docs may have lead me to an early conclusion.

**Comment by james-d-elliott** [comment]
Can you run this container and have a look at the X-Forwarded-For header it outputs? https://hub.docker.com/r/traefik/whoami/tags?page=1&ordering=last_updated

**Comment by dchidell** [comment]
```
Hostname: 496ba117203e
IP: 127.0.0.1
IP: 172.18.0.49
RemoteAddr: 172.18.0.21:48808
GET / HTTP/1.1
Host: whoami.dchidell.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip
Accept-Language: en-GB,en;q=0.5
Cdn-Loop: cloudflare
Cf-Connecting-Ip: 86.165.102.97
Cf-Ipcountry: GB
Cf-Ray: 62d4e00ffdf7e5ec-LHR
Cf-Request-Id: 08b8ea5df80000e5ec9bb77000000001
Cf-Visitor: {"scheme":"https"}
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 162.158.158.206
X-Forwarded-Host: whoami.dchidell.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: 0e1790178efe
X-Real-Ip: 162.158.158.206
```

This is interesting - and caused me to dig more into CloudFlare. It seems that they mask the real client IP unless you toggle a particular setting (which is an enterprise feature I do not have access to). Good shout to actually check that!

While it appears that authelia is working as expected in this case, I'd still like to see more flexibility around the headers in this case. If I did have that feature enabled, there would be no way for authelia to read it. Or if I want to do something basic based on user agent that's currently not an option.

**Comment by james-d-elliott** [comment]
Yeah I can see that being useful. However there is something else going on, for me Cloudflare adds the IP to the X-Forwarded-For header, their docs indicate the same:

https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

```
Maintains proxy server and original visitor IP addresses. If there was no existing X-Forwarded-For header in the request sent to Cloudflare, X-Forwarded-For has an identical value to the CF-Connecting-IP header:
```

**Comment by james-d-elliott** [comment]
No worries and thanks for the PR!
