### ISSUE TITLE
Incorrect redirect if already authenticated

### ISSUE THREAD

**Issue by mardom1** [authelia/authelia#1788]
If the user is already authenticated, the redirection parameter (`?rd=...`) gets ignored and the user gets redirected to the authenticated page. The correct behavior would be a redirect to the URL specified by `?rd`.

Steps to reproduce:

1. Make sure you are logged out
2. Open a protected site. You should get redirected to authelia with a redirection parameter in the URL.
3. Copy URL and paste in new tab
4. Authenticate in one tab
5. Refresh the other tab

Without a deep understanding of the authelia code, I suspect that the following line should differentiate wether a redirection parameter is set or not:

https://github.com/authelia/authelia/blob/d7484bd7e20f87dd9e158060001567ef0cd60570/web/src/views/LoginPortal/LoginPortal.tsx#L98

**Comment by james-d-elliott** [comment]
I think I understand, and pretty sure I know why this is happening. The backend go code should know to forward the user in this instance.

**Comment by james-d-elliott** [comment]
@all-contributors please add @mardom1 for bug.
