### ISSUE TITLE
User being blocked from using git push http/s

### ISSUE THREAD

**Issue by alxsch** [authelia/authelia#1791]
I have a gitea instance behind cloudflare. 
Does that basically block http git pushes? Should I add the cloudflare ips to a white list?

```
level=info msg="Access to https://giteainstance/repo.git/info/refs?service=git-receive-pack is not authorized to user , sending 401 response" method=GET path=/api/verify remote_ip=<cloudflare_ip>
```

**Comment by james-d-elliott** [comment]
That's relatively expected if you're protecting it with Authelia. Depending on the specific URLs used in git push/pull etc you may be able to craft rules that allow it and don't allow browsing.

**Comment by alxsch** [comment]
I'll have to look that up. Thanks for the idea.

**Comment by alxsch** [comment]
I cant find the discord. Is there a place with links that has a discord invite link?

**Comment by james-d-elliott** [comment]
https://discord.authelia.com it's on the main page of the repo but may not be overly obvious.
