### ISSUE TITLE
Authelia redirect not working with home-assistant but others

### ISSUE THREAD

**Issue by henne49** [authelia/authelia#1798]
Hi, 

my authelia is working in general with DUO Push and I can also use it to access home-assistant, but not as it should work I think. 

My setup
Traefik 2.3 as reverse proxy
Authelia as authenticator
Home-assistant behind traefik version 2021.3.3
Cloudflare as DNS Firewal and Proxy in front

When I want to access traefik2 page, I have to authenticate using authelia and once succesfull I get redirected to the right traefik dashboard. 

With home-assistant I get first this URL: 

https://authelia.ehennrich.com/?rd=https%3A%2F%2Fha.somedomain.com%2Flovelace-frw%2Fdashboard&rm=GET

then after successful authentication this URL: 

https://authelia.ehennrich.com/2fa/push-notification?rd=https%3A%2F%2Fha.somedomain.com%2Fconfig%2Fautomation%2Fdashboard&rm=GET

But no redirect happens. It seems that home-assistant is doing some js script magic and somehow caching. But I'm not sure. I cannot see any thing obvious in the logs. 

what would you need to review the problem? 
docker-compose file?
authelia config?

Thank you very much

**Comment by james-d-elliott** [comment]
Generally the best place to start is the browser console and see if there are any errors. But but the compose would be the most other useful thing.

**Comment by henne49** [comment]
I have uploaded my compose file with authelia and traefik sections. Also added the toml files for traefik middleware files where authelia config is stored as well. 

[http-middlewares.txt](https://github.com/authelia/authelia/files/6121121/http-middlewares.txt)
[chains-middlewares.txt](https://github.com/authelia/authelia/files/6121122/chains-middlewares.txt)
[authelia.txt](https://github.com/authelia/authelia/files/6121123/authelia.txt)

If you have a quick guid with with which browser and how to trace this best, I would do for you, but was a little bit unsure, what to do. 

Rgds

**Comment by james-d-elliott** [comment]
Most browsers the shortcut is Shift + F12 to get the developer tools, and usually there is a tab called console, it should show errors if there are any strange things happening with js hopefully. If you can't find this let me know what browser and I can give you a guide, though I jst did this on Firefox.

**Comment by henne49** [comment]
![06AAF69E-23B2-4B3C-A2A5-10DE593699BE_1_201_a](https://user-images.githubusercontent.com/4662326/110757196-67c42d00-824b-11eb-9a0e-5e1666c02667.jpeg)

I have done a debug, maybe that is helpful with my config files. Can it be caused by the method home-assistnat is using javascript?

**Comment by james-d-elliott** [comment]
We have a matrix chat and discord, it may be easier to help you on there, I can't see anything super obvious. The CSP errors are problematic but they're likely (based on their names) browser extensions. I can't find anything about Home Assistant and inject.js.

**Comment by henne49** [comment]
Hi James, thank you for your excellent support so far. Hopefully you could use the logs and insights shared in Chat. Can you let me know, if there is any progress? Appreciate the effort.

**Comment by james-d-elliott** [comment]
Hey Henne, I'm pretty sure since I can replicate it I can possibly narrow down where the issue is. As it's a single app I have a feeling it's an issue with home-assistant but not entirely sure what's causing it. I will make some reproduction instructions and see if the other maintainers can figure it out.

I also noticed the issue seems intermittent, sometimes it works fine, but mostly it does what you've described. Do you find this too?

**Comment by henne49** [comment]
Hey, I have used it for 2 weeks and it never worked. BUT I will not say that is has never worked or maybe as you say rarely. So yes it seems very intermittend.

**Comment by james-d-elliott** [comment]
@clems4ever do you have time to investigate this? Pretty sure it's a js router issue and I'm not super knowledgeable about javascript.

**Comment by nightah** [comment]
I believe #1842 covers what's necessary to allow Authelia to work with Home Assistant.
Please follow the feedback in that issue and if you continue to have problems please lodge a new issue with the respective logs for us to assist.
