### ISSUE TITLE
Possibility of a timing attack on password hash comparison

### ISSUE THREAD

**Issue by except** [authelia/authelia#1799]
I'm not sure whether this is a big concern but it's probably a better idea to use `subtle.ConstantTimeCompare` and compare the hashes in constant time.

https://github.com/authelia/authelia/blob/c4864ca64c5ef6172e96b705b0e162ea41a84a70/internal/authentication/password_hash.go#L154

**Comment by james-d-elliott** [comment]
Most likely a very low impact for us due to our expected + random delay to the user on successful/unsuccessful auth based on the last 10 successful attempts. But easy to implement and can only be a benefit as far as I can tell.

**Comment by james-d-elliott** [comment]
@all-contributors please add @except for security.
