### ISSUE TITLE
Use SQL DB as authentication backend

### ISSUE THREAD

**Issue by BlueAlder** [authelia/authelia#1807]
I would like to be able to use a SQL DB as a backend for authentication as opposed to LDAP or a flat file. I don't really want to setup a full LDAP server, but since I already have a SQL DB running it would be great to support that aswell :)

**Comment by james-d-elliott** [comment]
It's something that's planned! You can see it in this issue: #1538

I am planning to work on that in the next week or so. Basically if we were to implement something like this it would hook into the storage configuration already available.

I would ideally like to have both a working API and the actual provider working at the same time so there is both an easy way to manage it and actual functionality at the same time.

**Comment by james-d-elliott** [comment]
Oh I'm going to close this and you can subscribe to/comment on that other issue. @BlueAlder
