### ISSUE TITLE
Authelia and Redis Issues - Authentication

### ISSUE THREAD

**Issue by evakq8r** [authelia/authelia#1815]
Host OS: **Unraid**
Docker Containers: **authelia/authelia:latest** & **redis/redis:latest**

Hello,

I've been trying to setup Authelia for the last few days and have been having a lot of problems with Authelia talking to Redis. I've been following https://github.com/ibracorp/authelia as a guide.

Logs:

`level=fatal msg="Redis connection error: **WRONGPASS invalid username-password pair or user is disabled**." stack="github.com/authelia/authelia/cmd/authelia/main.go:118 startServer\ngithub.com/authelia/authelia/cmd/authelia/main.go:137 main.func1\ngithub.com/spf13/cobra@v1.1.3/command.go:856 (*Command).execute\ngithub.com/spf13/cobra@v1.1.3/command.go:960 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.1.3/command.go:897 main\ngithub.com/authelia/authelia/cmd/authelia/main.go:154 main\nruntime/proc.go:225 main\nruntime/asm_amd64.s:1371 goexit"`

I can manually authenticate into the Redis docker container via console:

```
# redis-cli
127.0.0.1:6379> AUTH "password" (without the quotes)
OK
127.0.0.1:6379>
```

I have also set the Redis container with Post Arguments of: `redis-server --requirepass <password>` , as I have read this seems to be required in Redis v6 due to ACL implementation.

The Authelia config file has the secret set in the file:

```
  # The secret to encrypt the session data. This is only used with Redis.
  # Secret can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
  secret: <password>
```

I have also read that Redis doesn't seem to like certain characters in its passwords, so I have minimised it to just alphanumeric without any luck.

Any help would be appreciated, and for the life of me I cannot find any clear answers as to how to get around this error. If someone else does, apologies for not finding it first. :(

**Comment by nightah** [comment]
The secret field is used to encrypt the session you'll notice there's a username and password field that's what is actually used for authentication in Redis:

https://github.com/authelia/authelia/blob/5a5efa5e027cf7a83a19c01e91bf853678aacbb7/config.template.yml#L369

**Comment by james-d-elliott** [comment]
If your auth mechanism is "AUTH mypass", your configuration should look like this:

```yaml
# username: authelia
password: mypass
```

Basically Redis in v6 added RBAC but it's optional. You can still auth with the single password method.

**Comment by evakq8r** [comment]
Interesting... The config file I was using from Ibracorps repo has a much shorter file than the Authelia repo (by ~160 lines), but I overlooked line 265 in their config file (vs line 369 in yours) with the PASSWORD placeholder.

Lo and behold, it now authenticates. Thanks very much for the help, I knew it was something simple.

**Comment by james-d-elliott** [comment]
Glad it worked! Also yeah, generally it is we put a lot of effort into testing. Never the less we appreciate you reaching out because if there is an issue we need to know about it.

I am going to refactor several areas of documentation regarding configuration, so this will be on my list. :)

**Comment by evakq8r** [comment]
I appreciate your efforts @james-d-elliott :)
