### ISSUE TITLE
Resources ACL settings no longer working per documentation in 4.27.x

### ISSUE THREAD

**Issue by craSH** [authelia/authelia#1817]
It seems that resource (path) based ACLs are not entirely working in 4.27.x any longer. I have verified that such configurations work with the `4.26.2` docker image tag, but not in either of `4.27.0` or `4.27.1`

An example ACL configuration which works in 4.26.2 but not later versions:

```
    - domain: "myhost.example.com"
      policy: bypass
      resources:
        - '^/api/v[0-9]+$'
```

This results in 302 redirects to authelia in current versions, vs. a proper bypass in `4.26.2` and below.

However, changing the resource value to the following does work:

`'^/api/v[0-9]+.*$'` (Adding a greedy `.*` at the end)

An HTTP request example for the application in question looks similar to the following:

```
GET /api/v2?apikey=decafc0ffeebadecafc0ffeebadddecafc0f&other_param=yes&one_more_param=action
```

I wonder if this was introduced in 4dce8f94962d3bd0099bbb202f76696a551d099b for the ACL preload work (#1640) ? Is it possible that URL query parameters are now also being evaluated in resources, where they were not before? If so, that may just require a documentation update.

**Comment by james-d-elliott** [comment]
That indeed is what's happened! I can update the docs. Nice spot. Before they were never evaluated, which can make crafting rules for specific situations more problematic. 

https://github.com/authelia/authelia/commit/4dce8f94962d3bd0099bbb202f76696a551d099b#diff-3257acd5ea608565cc4a3196c2165a7970451996f23e1667ca760e364f72bbe3R53-R57

**Comment by james-d-elliott** [comment]
PR will close this issue, feel free to comment or reopen if it's not sufficient. Sorry for the inconvenience @craSH we didn't consider this specific scenario.

**Comment by james-d-elliott** [comment]
@all-contributors please add @craSH for doc.

**Comment by craSH** [comment]
Solid, thanks! I think I have seen notes for breaking changes before, I would consider this one of those if you want to make a note in a future release or other notification channel.

**Comment by james-d-elliott** [comment]
Yeah I will probably talk with the team and decide what to do specifically.
