### ISSUE TITLE
U2F registration fails when not using a reverse proxy

### ISSUE THREAD

**Issue by frebib** [authelia/authelia#1841]
Steps to reproduce:
1. Configure Authelia at https://somedoma.in to serve TLS natively, set the port to 443
2. Navigate to https://somedoma.in, log in and try to configure U2F
3. See a generic error in the client, and the error below in the server logs. It seems that authelia assumes that it is always behind a reverse proxy when in fact it's perfectly capable of standing up on it's own with TLS.

Seems to be due to this change? https://github.com/authelia/authelia/pull/631
```
time="2021-03-19T15:32:26Z" level=error msg="Missing header X-Forwarded-Proto" method=POST path=/api/secondfactor/u2f/identity/start remote_ip="2a02:8010:64b4:3::f7e:b1b" stack="
github.com/authelia/authelia/internal/middlewares/authelia_context.go:64      (*AutheliaCtx).Error
github.com/authelia/authelia/internal/middlewares/identity_verification.go:55 IdentityVerificationStart.func1
github.com/authelia/authelia/internal/middlewares/require_first_factor.go:15  RequireFirstFactor.func1
github.com/authelia/authelia/internal/middlewares/authelia_context.go:49      AutheliaMiddleware.func1.1
github.com/fasthttp/router@v1.3.9/router.go:414                               (*Router).Handler
github.com/authelia/authelia/internal/middlewares/log_request.go:14           LogRequestMiddleware.func1
github.com/valyala/fasthttp@v1.22.0/server.go:2193                            (*Server).serveConn
github.com/valyala/fasthttp@v1.22.0/workerpool.go:223                         (*workerPool).workerFunc
github.com/valyala/fasthttp@v1.22.0/workerpool.go:195                         (*workerPool).getCh.func1
runtime/asm_amd64.s:1371                                                      goexit"
```

**Comment by nightah** [comment]
Authelia does indeed assume that it is always behind a reverse proxy because that's the intended deployment method.

Can you tell us a little bit more about your specific use case? How are you actually intending to utilise Authelia if it's not going to sit behind a reverse proxy?

**Comment by frebib** [comment]
I set up Authelia to listen on port 443 and serve it's own certificates. I gave it it's own IP address, and it worked perfectly fine standalone. Even the TLS implementation in Go is solid. It is quite happy with TLS1.3 and modern crypto. Other services that were behind nginx use the `auth_request` functionality to redirect the user to the auth domain, which after Authelia redirects them back with the auth headers. I didn't see any need or reason to put it behind a reverse proxy, so I didn't; at least not until I discovered that the 2FA registration doesn't work without it. I guess I'm trying to say that it's 99% of the way to being standalone so I don't see why it couldn't be fixed to work without those headers.

**Comment by clems4ever** [comment]
Hello @frebib , perhaps we can avoid the issue you're facing with 2FA but I cannot imagine a working workflow of authentication without using a reverse proxy (at least without big changes in the way Authelia works).

First, how can the user be redirected to the auth portal when a request is unauthenticated? Is the service configured to redirect to Authelia portal? If that's the case, it means that your app already do some kind of access granting somehow so I assume that you would like to augment that with 2FA. But even if it's the case the logic for computing the permissions of access is triggered by a call to the /api/verify endpoint. Who would call this endpoint in the workflow if there is no proxy involved?

**Comment by frebib** [comment]
So I am using a reverse proxy to make the authentication checks on various domains but it's entirely independent from the Authelia setup. From what I can tell there is no requirement to have Authelia on the same host or even the same domain.
I suppose for most users they would have a single nginx instance on a single IP address and everything would go through the proxy, but that's an overly broad assumption IMO.
Please do correct me if I'm wrong, but I don't see any security or otherwise requirement to put Authelia behind a proxy

**Comment by clems4ever** [comment]
@frebib , Authelia allows to authenticate only what's under the same top domain. So the first issue you will face is the cookie. It won't be transmitted if Authelia and your apps are not under the same top domain.

Then regarding the requirements, it's not a problem of security, rather a problem of authentication workflow as I've just explained above. Authelia is not designed to work without proxy and quite honestly I think it would be hard make it work without it except for rather specific use cases (the app detecting an unauthenticated request doing the redirect to the authentication portal itself for instance).

**Comment by nightah** [comment]
@frebib just revisiting this, while you're correct that it would be a trivial change to not require said headers and Authelia could be deployed in the fashion you have described, assuming that Authelia is deployed behind a reverse proxy is a conscious decision due to how some of the other factors within the app like OIDC function.

I understand that you have worked around the issue for now anyway due to this shortcoming, can I suggest that you follow/subscribe to #467 as when we tackle the aforementioned issue we'll be in a position to address this problem you have described here.
