### ISSUE TITLE
public_html build failure: File '/portdistfiles/authelia-4.27.2/web/node_modules/typescript/lib/lib.dom.d.ts' not found.

### ISSUE THREAD

**Issue by yurivict** [authelia/authelia#1843]
I am getting this failure on FreeBSD:
```
TypeScript error in undefined(undefined,undefined):
File '/portdistfiles/authelia-4.27.2/web/node_modules/typescript/lib/lib.dom.d.ts' not found.
  The file is in the program because:
    Library 'lib.dom.d.ts' specified in compilerOptions  TS6053
```

Why would this file not be found?

This only happens in the package builder (poudriere), but doesn't happen on a local computer.

```
$ INLINE_RUNTIME_CHUNK=false yarn build
[...skipped...]
yarn run v1.22.10
$ react-scripts build
Creating an optimized production build...
Failed to compile.

TypeScript error in undefined(undefined,undefined):
File '/portdistfiles/authelia-4.27.2/web/node_modules/typescript/lib/lib.dom.d.ts' not found.
  The file is in the program because:
    Library 'lib.dom.d.ts' specified in compilerOptions  TS6053


error Command failed with exit code 1.
```

Could you please publish the list of dependencies of the public_html build process in README?

I have yarn, gmake, perl installed, but these are apparently not sufficient and build on my local system with all sorts of things installed does succeed, but it doesn't in a controlled package builder environment.

**Comment by nightah** [comment]
@yurivict you will need the following packages to build the frontend and backend:

- gcc
- git
- go
- nodejs
- yarn

An alternative to avoid having to build the frontend from source would be to retrieve the assets which we publish on GitHub: https://github.com/authelia/authelia/releases/download/v4.27.2/authelia-public_html.tar.gz

You could follow the steps in our PKGBUILD for AUR packages pretty closely. Just replace the build folder with the extracted assets (make sure you don't forget to copy the api folder into the end destination of the extracted assets `internal/server/public_html` too).

**Comment by yurivict** [comment]
> you will need the following packages to build the frontend and backend:
> 
>     gcc
>     git
>     go
>     nodejs
>     yarn

These aren't sufficient. Some other dependency is missing.

---------------------

But rather than debugging this I would just use your ```authelia-public_html.tar.gz```.

Thanks!

**Comment by nightah** [comment]
@yurivict are you happy for me to close this off or did you want support in understanding why the assets could not be built?

If the latter what's the best way to reproduce your build environment so we can test?

**Comment by yurivict** [comment]
Please close it, thank you!
