### ISSUE TITLE
Two domains via SWAG, authelia continually redirects subdomains under secondary root domain to authelia login

### ISSUE THREAD

**Issue by SyRaza** [authelia/authelia#1844]
I have two domains I'm running through SWAG that are directed to my home IP. 

My issue is this:

When I'm using the main domain, everything works, like so:
sub.example01.com --> authelia.example01.com --> sub.example01.com

However, when I use the secondary domain to the same service, I have issues, like so:
sub.exp02.com --> authelia.example01.com --> authelia.example01.com. It just keeps repeated this.

The way I'd like it however, if it's possible, is like this:
sub.example01.com --> authelia.example01.com --> sub.example01.com
sub.exp02.com --> authelia.exp02.com --> sub.exp02.com

I don't know if I have to run two instances of authelia to accomplish this or if it's possible with just one instance.

**Comment by james-d-elliott** [comment]
authelia.example01.com cannot write cookies for exp02.com to identity the users session is the issue. Current functionality requires you have a separate instance in this situation. We do intend to eventually consider this scenario and the best way to support it.

**Comment by SyRaza** [comment]
Gotcha. Thank you very much. I'll run  separate instance then.
