### ISSUE TITLE
Allow passwords to be stored in the database

### ISSUE THREAD

**Issue by sgrimm** [authelia/authelia#1849]
### Description

Currently Authelia (optionally) stores per-user 2FA data in Postgres or MySQL and the database is shared across servers in a high-availability configuration, but if you use a file-based user database, password changes are only written to the local filesystem. LDAP is required if you want to let users change their passwords in a high-availability configuration.

Proposal is to treat the password in the user database file as an initial password. When a new user is added to the user database file, the hashed password gets copied to the database. When the user changes their password, the database is updated.

A refinement (definitely not a requirement!) might be to store both the current password and, separately, the password that was copied from the user database file. If the password in the user database file doesn't match the one that was in the file previously, the new password from the file becomes the new current password. That would allow an admin to reset a user's password by editing the file, but wouldn't overwrite any user-modified passwords in the database.

### Use Case

I'm setting up a portal for a small organization where the list of users doesn't change very often and isn't very large. LDAP is overkill for this situation; I'd prefer to maintain the list of users in a file and push it to the Authelia hosts using Ansible when it changes.

**Comment by james-d-elliott** [comment]
Thanks for your interest and the suggestion. Incidentally it's something already being designed. Realistically our current #1 priority is OpenID connect and internal auth is a close behind I think. You will see in the design that the intention is to have an API which will be necessary when we add an admin interface. I think this realistically would satisfy your use case?

https://github.com/authelia/authelia/issues/1538

**Comment by nightah** [comment]
Closing as this can be tracked through #1538 once moved out of design.
