### ISSUE TITLE
Tag GHCR images with latest

### ISSUE THREAD

**Issue by TheCatLady** [authelia/authelia#1870]
### Description

The GHCR Docker image is not being tagged with `latest`, so when you try to pull the image without explicitly specifying a tag, you get the following result:
```bash
# docker pull ghcr.io/authelia/authelia
Using default tag: latest
Error response from daemon: manifest unknown
```

### Expected Behaviour

GHCR image built off of the `master` branch is tagged with `latest`

### Reproduction Steps

1. `docker pull ghcr.io/authelia/authelia`

### Additional Information

_N/A_

**Comment by nightah** [comment]
The latest tag along with `4.*` tags will all be pushed on the next tagged release.
If you're planning to swap fom DockerHub to GHCR just wait til you see the next release.
