### ISSUE TITLE
Using Authelia to protect WebSockets-based application servers

### ISSUE THREAD

**Issue by Duckwhale** [authelia/authelia#1875]
I've toyed around with Authelia a bit by now, and I think it might be a great solution for my use case. However, I don't really know how it works internally (all the LDAP/nginx stuff is basically a black box for me currently). Here's what I wanted to do:

* Users log in from my app (i.e., not using the custom login screen Authelia provides). Same goes for registration etc. - probably using the ``api``?
* The login/password should be submitted to Authelia for validation, and the session itself managed by it, too - I think this works with the session cookie that it sets?
* When authentication succeeds, users should be allowed access to the application server (which uses WebSockets) - not sure how to do this currently
* My app needs to somehow access the user data, or at least uniquely identify each user in Authelia's database so that application-specific data can be kept for it - ideally this would also work with the ``api`` or at least without having to access the database directly, which would complicate the application logic
* Finally, when users drop the WebSocket connection, they should be logged out in Authelia, too (session cookie cleared?)

Perhaps you could point me in the right direction? I haven't found anything in the docs relating to forwarding the requests in such a fashion, though I believe it might be possible to use the ``api`` somehow to accomplish this?

---

I'm also not really sure if I can use the reverse proxy Authelia uses to offload encryption. This would mean users would somehow have to connect to Authelia directly using the ``wss`` protocol (instead of ``https``). Some research I did suggests nginx could maybe handle this, but I don't know how the interaction would work with Authelia.

Is there a way to do this and still use Authelia for authentication (i.e., users must log in before being allowed access to the application server)? I'm a bit confused because they're two different protocols and I currently implement the http/ws transition on the application server (handshake, upgrade, etc.)

**Comment by james-d-elliott** [comment]
We don't technically support this but it could be possible, I've never seen anyone do this. The solution the open source community decided on was OpenID Connect and SAML. Basically similar to those webapps that allow you to login via GitHub or Google etc. Authelia is working on an implementation of this.

The part regarding logging out when the websocket session ends is not a good fit for OpenID Connect in the state we plan to implement it early on. 

Are you able to initiate HTTPS requests via your app? If so you can realistically utilize the API in exactly the same way as Authelia uses it and proxies use it.

**Comment by james-d-elliott** [comment]
Hey I'm closing this for now, if you want help in the future let us know!

**Comment by Duckwhale** [comment]
Oh, sorry I haven't looked into this further. I guess I didn't really see a way to do what I was planning and forgot about this issue.

I can do whatever I want in my app, including HTTPS requests, but I'm not sure what you're referring to with the last part. My client application is just a browser/Electron client and the application servers are essentially NodeJS with custom logic, so in theory anything is possible.

If there's any way to use Authelia for what I'm imagining then I'll be happy to outsource the account management to it. I do need to link accounts to application data somehow for the business logic, but that doesn't require any information other than some ID Authelia provides I think (so personal/sensitive data isn't kept by the application itself).

The session itself would normally live in the application and be identical to the socket connection's lifetime, so I essentially would like Authelia to become the "login server" and work with the app itself to make sure connections and logged in accounts are synchronized, so to speak. This would allow my app to not deal with login and account security issues, privacy concerns and similar things that I don't feel confident implementing myself and are pretty much unrelated to the actual application logic.
