### ISSUE TITLE
Case Sensitive Headers

### ISSUE THREAD

**Issue by paranoyed** [authelia/authelia#1892]
### Description

I was wondering why authelia is displaying the wrong ip in the logs in the field `remote_ip` and my ACL filters based on networks are not working. 
Example log message: 
```json
{"level":"info","method":"HEAD","msg":"Access to https://service.domain.tld/ (method GET) is not authorized to user \u003canonymous\u003e, sending 401 response","path":"/api/verify","remote_ip":"127.0.0.1","time":"2021-04-06T22:15:36+02:00"}
```
I was not sure why Authelia only knows of the remote_ip 127.0.0.1 when the headers are set correctly (or so I thought).
In my case where haproxy runs on the same server and uses localhost to comunicate to authelia so the message originates from `127.0.0.1` which is expected. 
So next I stopped Authelia and started a netcat listener on the port where Authelia listens. 
And sure the requests is the following:
```
GET /?rd=https://service.domain.tld/ HTTP/1.1
host: auth.domain.tld
user-agent: ****
accept-language: en,de;q=0.7,en-US;q=0.3
accept-encoding: gzip, deflate, br
dnt: 1
upgrade-insecure-requests: 1
pragma: no-cache
cache-control: no-cache
x-forwarded-proto: https
x-forwarded-method: GET
x-forwarded-host: auth.domain.tld
x-real-ip: 45.135.xxx.xxx
x-forwarded-uri: /?rd=https://service.domain.tld/
x-forwarded-for: 45.135.xxx.xxx
```
So I looked around the Code and noticed the code checks for [Camel Case (internal/middlewares/authelia_context.go#L172)](https://github.com/authelia/authelia/blob/4dce8f94962d3bd0099bbb202f76696a551d099b/internal/middlewares/authelia_context.go#L172=) headers and to my non Go developer eyes it looks like it checks for the string `X-Forwarded-For` in a case sensitive maner.  

I tryed to force haproxy to not rewrite the headers to lower case and it worked.
To change the headers to Camel Case I set the following global option:
```
global
    h1-case-adjust x-forwarded-for X-Forwarded-For
    h1-case-adjust x-real-ip X-Real-IP
```

When I started a netcat listener again i got the following headers:
```
[....]
x-forwarded-proto: https
x-forwarded-method: GET
x-forwarded-host: auth.domain.tld
X-Real-IP: 87.147.xxx.xxx
x-forwarded-uri: /?rd=https://service.domain.tld/
X-Forwarded-For: 87.147.xxx.xxx
```

Autelia now logs the correct ip adress:
```json
{"level":"debug","method":"POST","msg":"Redirection URL https://service.domain.tld/ is safe","path":"/api/firstfactor","remote_ip":"87.147.xxx.xxx","time":"2021-04-06T23:09:19+02:00"}
```

### Expected Behaviour

HTTP headers to be caseinsensitive.

### Reproduction Steps
Se description.

### Additional Information

My reverse proxy is a haproxy in a docker container with network mode host.
Authelia in a docker container with network mode host.

Configured and working, exept the IP bug as described above, like described in the Wiki.

Edit: fixed formatting

**Comment by james-d-elliott** [comment]
I can't replicate this. I actually use haproxy to configure headers for Authelia, all of the headers coming from haproxy are lowercase by default from what I can tell, and are lowercase once Authelia receives them. Would need some more information. I am not using haproxy to forward auth with Authelia, just as a frontend proxy/load balancer in front of it. So it's possible the issue is with the LUA side of things; though if you're using the provided configuration it should be working as it is tested in CI/CD.

Also I made a test server using exactly the same logic as Authelia does with fasthttp, to just print the headers after using Header.Peek(), as well as the raw headers. I'll include the haproxy config as well as the results. You can see the server here: https://gist.github.com/james-d-elliott/8dfa0bb18cd48b2ec1a50b5bc1bc10e5#file-main-go-L26-L32


```
X-Forwarded-For: 3.4.5.6
X-Real-IP: 1.2.3.4

Raw Headers: 


host: 192.168.2.31:1234
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-language: en-US,en;q=0.5
accept-encoding: gzip, deflate
dnt: 1
upgrade-insecure-requests: 1
x-real-ip: 1.2.3.4
x-forwarded-for: 3.4.5.6
```

```
frontend test
        bind            *:1234
        mode            http

        http-request    set-header      X-Real-IP                       1.2.3.4
        http-request    set-header      x-forwarded-for                 3.4.5.6
        use_backend     testbk

backend testbk
        balance         static-rr
        server          desktop        192.168.1.200:8080         check   maxconn 5000
```

**Comment by james-d-elliott** [comment]
Hey @paranoyed did you manage to figure this out?

**Comment by paranoyed** [comment]
Hi James, 
Sorry I did not se your comment.
I will get back to you in a few days.
Thank you for the help.

**Comment by james-d-elliott** [comment]
Hi @paranoyed I'm going to assume this is fixed since you didn't get back to us and all of my testing indicated it wasn't an issue. If not that is fine too we'd really love to solve it, I'm happy for you to reopen this or ping me to let me know.
