### ISSUE TITLE
Authelia subject AD nested group issue

### ISSUE THREAD

**Issue by lavih** [authelia/authelia#1909]
### Description
im using LDAP integration to work with Authelia and everything works well. Im using "subject:" as an access control to a domain like the following config example:
access_control:
  default_policy: deny
  rules:  
    - domain:
      - www.example.com
      subject:
        - "group:test-ad-group"

On the ActiveDirectory group named "tes-ad-group" only the user objects that are directly in the group have access but the users inside groups (nested groups) in "test-ad-group" get "Forbidden".
Example:
AD object "Test-ad-group" content:
  user1
  user2
  group1
  group2

Only user1 and 2 can access the domain. All the users in group1 and 2 get "Forbidden".

### Expected Behaviour
Allow the users in nested group access via the Subject stanza

### Reproduction Steps
try to set in the "Subject" an AD group with nested groups in it.

### Additional Information
important part of the config file on ldap section:
authentication_backend:
  ldap:
    group_name_attribute: cn
    groups_filter: (&(member={dn})(objectclass=groupOfNames))

Thanks!

**Comment by james-d-elliott** [comment]
Are you by chance using Microsoft ActiveDirectory?

**Comment by lavih** [comment]
Hey James,
Thanks for the fast response.
Yes we're using Microsoft Active Directory
I changed the authelia config of 
groups_filter: (&(member={dn})(objectclass=groupOfNames))
to
groups_filter: (&(member:1.2.840.113556.1.4.1941:={dn})(objectclass=groupOfNames))

seems like only users directly under the group can access. users in the nested groups (1 level down ) get "Forbidden"
note - im using the "latest" tag with my container.
is there any config / log I can provide for further checking?
Thanks !

**Comment by james-d-elliott** [comment]
Trace logging will reveal the groups associated with users when they log in, you will have to log out and log back in. I can dedicate some time to seeing if I can get it to work tomorrow. The way we search is we look at the objects where the user is a member of, we don't look at the group down, if that makes sense.

**Comment by lavih** [comment]
cool, it makes sense. 
I really do see in the logs only the groups my user is direcly MemberOf and not the "group of the groups" per se
Thanks for your time, I will keep follow the thread, this feature will be of great use

**Comment by james-d-elliott** [comment]
It's working flawlessly for me. Are all of the groups inside your additional_groups_dn + baseDN?

**Comment by lavih** [comment]
Hey James,
Thanks!
using this version makes it work:
`groups_filter: (&(member:1.2.840.113556.1.4.1941:={dn})(objectClass=group)(objectCategory=group))`
Closing the thread :)

**Comment by james-d-elliott** [comment]
Glad that worked! Also yeah I tested it and it's going into the docs! Thanks for your contribution.

@all-contributors please add @lavih for docs
