### ISSUE TITLE
Customize Reset Password URL

### ISSUE THREAD

**Issue by deeztek** [authelia/authelia#1934]
Is there a way currently or any plans to be able to customize the reset password URL on the login page? 

Thanks

**Comment by james-d-elliott** [comment]
What about the URL do you want to customize exactly?

**Comment by deeztek** [comment]
Hi thanks for answering. I would like to customize the actual URL.  We are utilizing the haveibeenpawned api when users create accounts in the app so utilizing the reset password function in authelia is a not an option. We would like to be able to direct users to our own portal to reset their password.

**Comment by james-d-elliott** [comment]
https://www.authelia.com/docs/configuration/authentication/#disable_reset_password

**Comment by deeztek** [comment]
I knew the option was to disable the reset password. I was hoping to leave a reset password link in the login page which makes it convenient for users to click on it but simply customize the reset password URL. It doesn't look like it's possible. Maybe feature request?

**Comment by james-d-elliott** [comment]
Yeah correct, we'd need to implement such a feature. We'd have to figure out the best way to do such a customization in a reusable way.

**Comment by you1996** [comment]
Hello @james-d-elliott
As a simple solution for this, i suggest to add in configuration :
```yaml
  disable_reset_password: false
  external_reset_link: true (default is false)
  redirect_reset_link: simple redirect link to a custom reset portal (default is empty string)
```
we can simply obtain those parameters in the same way we do with resetPassword, duo, and other boolean configurations vars, in the frontend by passing it to `ServeTemplatedFile` function...am i right?
It's easy, simple and, in my opinion, can provide more flexibility to authelia administrators, and @deeztek is an example.
If confirmed i can contribute for this one.
Thank you

**Comment by nightah** [comment]
The best way would be to accept a string value and if said value isn't blank to pass that across to the frontend for use.

Should be straight forward to validate if the address is a URL too.

**Comment by bdben** [comment]
I'd really like to see this feature as well. My authentication server immediately expires passwords reset by an admin (e.g. authelia), which means that the user has to change their password twice if they use Authelia's link. However, the server does have its own self-service password reset portal, so the UX would be a lot better if Authelia's password reset link could simply redirect to that portal.
