### ISSUE TITLE
/api/verify endpoint behavior

### ISSUE THREAD

**Issue by deeztek** [authelia/authelia#1939]
The **/api/verify** endpoint does not seem to behave according to the following docs:

[https://www.authelia.com/docs/deployment/supported-proxies/#how-can-the-backend-be-aware-of-the-authenticated-users](https://www.authelia.com/docs/deployment/supported-proxies/#how-can-the-backend-be-aware-of-the-authenticated-users)

Making a request to the **/api/verify** endpoint when user is authenticated, it generates a 403 instead of a 200 and if the user is not authenticated it generates a 401.

Am I missing something?

**Comment by nightah** [comment]
How are you testing the behaviour, with curl or something else?
Can you please share the specific method/use case.

**Comment by nightah** [comment]
@deeztek just a gentle ping to see if you can answer the previous question so that we can help you.

**Comment by deeztek** [comment]
@nightah thanks for the reminder. Actually, I was able to solve the issue. Closing.
