### ISSUE TITLE
ldap: date time restriction

### ISSUE THREAD

**Issue by bfd69** [authelia/authelia#1964]
Authelia is awesome, 
I have a suggestion :
Is it possible to add a date time restriction based on a ldap field?, there is no support for date time Restriction auth on openldap so this might be a good idea.
You could use Unix time stamp or a date time schema defined in rules like d/MM/yyyy h:m, the data could be retrieved on ldap groups or users with a preference for the most restrictive date time.
You could eventually implement a start and end date validation as ldap fields...

thanks for reading

**Comment by nightah** [comment]
Thanks for the report @bfd69 I'm struggling to understand what this feature request is looking to actually achieve.
Are you looking to regulate when users are allowed to access specific endpoints based on specific dates/times?

Also in future please utilise the provided issue templates.

**Comment by bfd69** [comment]
Sorry I’m just not used to report issues, and didn’t know how to ask for enhancement/functionality.
the goal is to make the authentification based on an ldap group/user only available for an amount of time, as an example a coworker contracted for updating a service should ave access to your website only for the contracted time.
With active directory you would just have to add a date limit on the user object but the same property doesn’t exist in openldap.

An another use case is a website for an exam where candidates  should have access only for a period of time while the examiner group will not be limited.

Thé whole purpose is to complete openldap functionality, because there is no time limit on accounts nor groups.

Thanks a lot for your concern
Best regards

Envoyé de mon iPhone

Le 5 mai 2021 à 01:20, Amir Zarrinkafsh ***@***.***> a écrit :

﻿

Thanks for the report @bfd69<https://urldefense.com/v3/__https://github.com/bfd69__;!!FdBFez6_0g!z-yE428GGz4C6iRPa6qTd_FasSNVlasPGTdHuxIC8VtvOKllolyLl8n6HH3VO1EAZYl2NgcK7-qxAg$> I'm struggling to understand what this feature request is looking to actually achieve.
Are you looking to regulate when users are allowed to access specific endpoints based on specific dates/times?

Also in future please utilise the provided issue templates.

**Comment by nightah** [comment]
@bfd69 what LDAP implementation are you using?

#2182 will provide the ability to achieve your outcome however from my research this isn't natively available in OpenLDAP.
We avoid the creation of custom attributes to manage features because it becomes a significant support burden when not aligned to a known standard/implementation.
