### ISSUE TITLE
Authelia OpenLDAP authentication

### ISSUE THREAD

**Issue by a0930xxx11** [authelia/authelia#1965]
Dear team:

Currently, I want to try use compose defining and running container Docker applications, Each running Authelia and traefik, two containers, traefik good run, but the state has been maintained Authelia restart, I do not know am I doing wrong?

I check the log, it should be ldap configuration error, but the format is in accordance with the example settings:
https://www.authelia.com/docs/configuration/authentication/ldap.html

I have been stuck with this problem for a week, I feel defeated.

Provide configuration files for your reference.

Best Regards,

---Authelia configuration.yml---
# The host and port to listen on
host: 0.0.0.0
port: 9091
 
# Level of verbosity for logs: info, debug, trace
log_level: info
 
# The secret used to generate JWT tokens when validating user identity by
# email confirmation.
jwt_secret: change_this_secret
 
# Default redirection URL
default_redirection_url: http://example.com
 
# TOTP Issuer Name
totp:
issuer: example.com
period: 30
skew: 1

duo_api:
  hostname: duosecurity.com
  integration_key: abcdefg
  # Secret can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
  secret_key: abcdefg
 

# There are two supported backends: `ldap` and `file`.
authentication_backend:

ldap:
implementation: custom
url: ldap://192.168.1.222
base_dn: ou=Corp,dc=example,dc=com
username_attribute: uid
users_filter: (objectClass=inetOrgPerson)
user: cn=admin,dc=example,dc=com
password: 123456
 
# Access Control
access_control:
  default_policy: deny
  rules:
    - domain: '*.example.com'
      policy: two_factor
 
# Configuration of session cookies
session:
  secret: change_this_secret
  expiration: 3600 
  inactivity: 300
  domain: example.com
 
# Configuration of the authentication regulation mechanism.

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300
 
# Configuration of the storage backend used to store data and secrets.
storage:
  local:
    path: /config/db.sqlite3
 
# Configuration of the notification system.
notifier:
  filesystem:
    filename: /tmp/authelia/config/notification.txt

---Authelia Log---
time="2021-05-04T04:00:59Z" level=error msg="Please provide `ldap` or `file` object in `authentication_backend`"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: start_tls"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: implementation"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: minimum_version"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: refresh_interval"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: ldap"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: base_dn"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: authentication_backend"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: users_filter"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: user"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: password"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: skip_verify"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: disable_reset_password"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: url"
time="2021-05-04T04:00:59Z" level=error msg="config key not expected: tls"

**Comment by james-d-elliott** [comment]
Hey could you please upload your configuration as a gist instead? 

https://gist.github.com/

**Comment by james-d-elliott** [comment]
@a0930xxx11 did you miss my message?

**Comment by nightah** [comment]
@a0930xxx11 we're going to close of this issue due to inactivity, if you are still experiencing issues can you please upload your configuration to gist and ask for this ticket to be reopened.
