### ISSUE TITLE
OTP and KeePass ( Copy & Paste)

### ISSUE THREAD

**Issue by cam100in1** [authelia/authelia#1966]
### Description
Edit: Copy & Paste is working....

OTP entry field doesn't accept KeePass OTP.

### Use Case
While using KeePass, i allways have to type the OTP numbers with the keyboard. It seems to be related to the authelia OTP entry field behavior. So please make KeePass possible.... 
Regards

**Comment by nightah** [comment]
Thanks for the report @cam100in1.

For us to be able to help could you perhaps detail your use-case with specific steps detailing what actually doesn't work and include the version of KeePass and any plugins that you may be utilising with KeePass?

**Comment by schklom** [comment]
The easiest is to copy the TOTP secret instead of copying the `otp://...` link. It's one of the 2 available buttons, i forgot which one.

**Comment by cam100in1** [comment]
Hello,
Thanks for responding. My KeePass Version is 2.6.4. Windows 10 Version. Browser is firefox 88.0
In "normal" single OTP entry fields, KeePass is showing a small icon. The user has to click on the icon an KeePass is generating the 6 numbers and the entry field will show these 6 numbers. The authelia otp entry field has 6 separated number fields. KeePass is NOT filling these number fields. Just the first one. I think, authelia is just using a otp field from a library w/o own implementation. Maybe authelia can use a different field type.
New finding: In IOS browser during entering the OTP numbers, i always have to activate the number keyboard mode. After entering a number, ios touchscreen keyboard switches back to letter mode. Also not helpfull.

regards

**Comment by schklom** [comment]
Oh that's what you meant.
Yes, the field doesn't get filled automatically, I'm sure the devs could implement a textbox instead of 6 individual boxes.
I guess it is this way for security purposes.

What I do is configure AutoType for Authelia's Keepass entry and add `{TOTP}` in the `Override default sequence:` box. Then Ctrl+Alt+A when I'm on the page and it gets filled automatically.

**Comment by nightah** [comment]
@cam100in1, does @schklom's workaround work for you?

I don't personally utilise KeePass however I am able to copy and paste TOTP keys without any issues with both Chrome/Firefox.

**Comment by cam100in1** [comment]
I just checked it out and is working as a workaround.
It is not as comforable as a mouseklick :)

**Comment by trallnag** [comment]
Are you sure this is KeepPass what you are using? Vanilla KeePass doesn't have any integration with browsers. You are probably talking about a plugin and / or extension?

**Comment by cam100in1** [comment]
h++ps://github.com/keepassxreboot/keepassxc

**Comment by nightah** [comment]
Closing as I do not believe this is specifically an issue with Authelia not being able to copy and paste TOTP keys.
