### ISSUE TITLE
Issue with multi factor authentication!

### ISSUE THREAD

**Issue by lsultana98** [authelia/authelia#1968]
Whenever I try multi factor authentication, I get these errors below. One for Duo and one for the other options. It always fails in the UI also. I'm confused by what is going wrong as there wasnt an issue before.

time="2021-05-04T09:11:29+10:00" level=debug msg="Sending an email to user lsultana (lsultana98@gmail.com) to confirm identity for registering a device." method=POST path=/api/secondfactor/totp/identity/start remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:11:29+10:00" level=debug msg="Notifier SMTP client attempting connection to 127.0.0.1:1025"
time="2021-05-04T09:11:29+10:00" level=error msg="dial tcp 127.0.0.1:1025: connect: connection refused" method=POST path=/api/secondfactor/totp/identity/start remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b" stack="github.com/authelia/authelia/internal/middlewares/authelia_context.go:64 (*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/middlewares/identity_verification.go:107 IdentityVerificationStart.func1\ngithub.com/authelia/authelia/internal/middlewares/require_first_factor.go:15 RequireFirstFactor.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.3.11/router.go:414 (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14 LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.23.0/server.go:2207 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.23.0/workerpool.go:223 (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.23.0/workerpool.go:195 (*workerPool).getCh.func1\nruntime/asm_amd64.s:1371 goexit"

time="2021-05-04T09:11:49+10:00" level=info msg="Logging severity set to debug"
time="2021-05-04T09:11:49+10:00" level=debug msg="Storage schema is being checked to verify it is up to date"
time="2021-05-04T09:11:49+10:00" level=debug msg="Storage schema is up to date"
time="2021-05-04T09:11:49+10:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
time="2021-05-04T09:20:02+10:00" level=debug msg="Mark authentication attempt made by user lsultana" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:20:02+10:00" level=error msg="Credentials are wrong for user lsultana" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b" stack="github.com/authelia/authelia/internal/middlewares/authelia_context.go:64 (*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/handlers/response.go:112 handleAuthenticationUnauthorized\ngithub.com/authelia/authelia/internal/handlers/handler_firstfactor.go:115 FirstFactorPost.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.3.11/router.go:414 (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14 LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.23.0/server.go:2207 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.23.0/workerpool.go:223 (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.23.0/workerpool.go:195 (*workerPool).getCh.func1\nruntime/asm_amd64.s:1371 goexit"

time="2021-05-04T09:20:06+10:00" level=debug msg="Mark authentication attempt made by user lsultana" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:20:06+10:00" level=debug msg="Credentials validation of user lsultana is ok" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:20:10+10:00" level=debug msg="Sending an email to user lsultana (lsultana98@gmail.com) to confirm identity for registering a device." method=POST path=/api/secondfactor/totp/identity/start remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:20:10+10:00" level=debug msg="Notifier SMTP client attempting connection to 127.0.0.1:1025"
time="2021-05-04T09:20:10+10:00" level=error msg="dial tcp 127.0.0.1:1025: connect: connection refused" method=POST path=/api/secondfactor/totp/identity/start remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b" stack="github.com/authelia/authelia/internal/middlewares/authelia_context.go:64 (*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/middlewares/identity_verification.go:107 IdentityVerificationStart.func1\ngithub.com/authelia/authelia/internal/middlewares/require_first_factor.go:15 RequireFirstFactor.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.3.11/router.go:414 (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14 LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.23.0/server.go:2207 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.23.0/workerpool.go:223 (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.23.0/workerpool.go:195 (*workerPool).getCh.func1\nruntime/asm_amd64.s:1371 goexit"

time="2021-05-04T09:23:02+10:00" level=info msg="Logging severity set to debug"
time="2021-05-04T09:23:02+10:00" level=debug msg="Storage schema is being checked to verify it is up to date"
time="2021-05-04T09:23:03+10:00" level=debug msg="Storage schema is up to date"
time="2021-05-04T09:23:03+10:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
time="2021-05-04T09:23:12+10:00" level=debug msg="Mark authentication attempt made by user lsultana" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:23:12+10:00" level=debug msg="Credentials validation of user lsultana is ok" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:23:16+10:00" level=debug msg="Save new preferred 2FA method of user lsultana to mobile_push" method=POST path=/api/user/info/2fa_method remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:23:16+10:00" level=debug msg="Starting Duo Push Auth Attempt for lsultana from IP 2001:8003:220c:a00:d1f2:ac30:7723:ab0b" method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:23:17+10:00" level=warning msg="Duo Push Auth failed to process the auth request for lsultana from 2001:8003:220c:a00:d1f2:ac30:7723:ab0b: Invalid request parameters (username), error code 40002. This error often occurs if you've not setup the username in the Admin Dashboard." method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"

time="2021-05-04T09:25:40+10:00" level=debug msg="Mark authentication attempt made by user lsultana" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:25:40+10:00" level=debug msg="Credentials validation of user lsultana is ok" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:25:41+10:00" level=debug msg="Starting Duo Push Auth Attempt for lsultana from IP 2001:8003:220c:a00:d1f2:ac30:7723:ab0b" method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:25:41+10:00" level=warning msg="Duo Push Auth failed to process the auth request for lsultana from 2001:8003:220c:a00:d1f2:ac30:7723:ab0b: Invalid request parameters (username), error code 40002. This error often occurs if you've not setup the username in the Admin Dashboard." method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"

time="2021-05-04T09:25:44+10:00" level=debug msg="Starting Duo Push Auth Attempt for lsultana from IP 2001:8003:220c:a00:d1f2:ac30:7723:ab0b" method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:25:44+10:00" level=warning msg="Duo Push Auth failed to process the auth request for lsultana from 2001:8003:220c:a00:d1f2:ac30:7723:ab0b: Invalid request parameters (username), error code 40002. This error often occurs if you've not setup the username in the Admin Dashboard." method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"

time="2021-05-04T09:25:44+10:00" level=debug msg="Starting Duo Push Auth Attempt for lsultana from IP 2001:8003:220c:a00:d1f2:ac30:7723:ab0b" method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:25:44+10:00" level=warning msg="Duo Push Auth failed to process the auth request for lsultana from 2001:8003:220c:a00:d1f2:ac30:7723:ab0b: Invalid request parameters (username), error code 40002. This error often occurs if you've not setup the username in the Admin Dashboard." method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"

time="2021-05-04T09:25:45+10:00" level=debug msg="Starting Duo Push Auth Attempt for lsultana from IP 2001:8003:220c:a00:d1f2:ac30:7723:ab0b" method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:25:45+10:00" level=warning msg="Duo Push Auth failed to process the auth request for lsultana from 2001:8003:220c:a00:d1f2:ac30:7723:ab0b: Invalid request parameters (username), error code 40002. This error often occurs if you've not setup the username in the Admin Dashboard." method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"

time="2021-05-04T09:25:45+10:00" level=debug msg="Starting Duo Push Auth Attempt for lsultana from IP 2001:8003:220c:a00:d1f2:ac30:7723:ab0b" method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:25:45+10:00" level=warning msg="Duo Push Auth failed to process the auth request for lsultana from 2001:8003:220c:a00:d1f2:ac30:7723:ab0b: Invalid request parameters (username), error code 40002. This error often occurs if you've not setup the username in the Admin Dashboard." method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"

time="2021-05-04T09:26:48+10:00" level=debug msg="Save new preferred 2FA method of user lsultana to totp" method=POST path=/api/user/info/2fa_method remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:26:50+10:00" level=debug msg="Sending an email to user lsultana (lsultana98@gmail.com) to confirm identity for registering a device." method=POST path=/api/secondfactor/totp/identity/start remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:26:50+10:00" level=debug msg="Notifier SMTP client attempting connection to 127.0.0.1:1025"
time="2021-05-04T09:26:50+10:00" level=error msg="dial tcp 127.0.0.1:1025: connect: connection refused" method=POST path=/api/secondfactor/totp/identity/start remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b" stack="github.com/authelia/authelia/internal/middlewares/authelia_context.go:64 (*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/middlewares/identity_verification.go:107 IdentityVerificationStart.func1\ngithub.com/authelia/authelia/internal/middlewares/require_first_factor.go:15 RequireFirstFactor.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.3.11/router.go:414 (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14 LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.23.0/server.go:2207 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.23.0/workerpool.go:223 (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.23.0/workerpool.go:195 (*workerPool).getCh.func1\nruntime/asm_amd64.s:1371 goexit"

time="2021-05-04T09:28:07+10:00" level=info msg="Logging severity set to debug"
time="2021-05-04T09:28:07+10:00" level=debug msg="Storage schema is being checked to verify it is up to date"
time="2021-05-04T09:28:07+10:00" level=debug msg="Storage schema is up to date"
time="2021-05-04T09:28:07+10:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
time="2021-05-04T09:28:16+10:00" level=debug msg="Mark authentication attempt made by user lsultana" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:28:16+10:00" level=debug msg="Credentials validation of user lsultana is ok" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:28:46+10:00" level=info msg="Logging severity set to debug"
time="2021-05-04T09:28:46+10:00" level=debug msg="Storage schema is being checked to verify it is up to date"
time="2021-05-04T09:28:46+10:00" level=debug msg="Storage schema is up to date"
time="2021-05-04T09:28:46+10:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
time="2021-05-04T09:28:57+10:00" level=debug msg="Save new preferred 2FA method of user lsultana to mobile_push" method=POST path=/api/user/info/2fa_method remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:28:57+10:00" level=debug msg="Starting Duo Push Auth Attempt for lsultana from IP 2001:8003:220c:a00:d1f2:ac30:7723:ab0b" method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:28:57+10:00" level=warning msg="Duo Push Auth failed to process the auth request for lsultana from 2001:8003:220c:a00:d1f2:ac30:7723:ab0b: Invalid request parameters (username), error code 40002. This error often occurs if you've not setup the username in the Admin Dashboard." method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"

time="2021-05-04T09:32:23+10:00" level=error msg="Network [internal VPN 192.168.1.0/24 10.0.0.1] for rule #1 domain: [*.lukesultana.com] is not a valid network or network group"

time="2021-05-04T09:32:23+10:00" level=error msg="Network [internal VPN 192.168.1.0/24 10.0.0.1] for rule #1 domain: [*.lukesultana.com] is not a valid network or network group"

time="2021-05-04T09:32:34+10:00" level=info msg="Logging severity set to debug"
time="2021-05-04T09:32:34+10:00" level=debug msg="Storage schema is being checked to verify it is up to date"
time="2021-05-04T09:32:34+10:00" level=debug msg="Storage schema is up to date"
time="2021-05-04T09:32:34+10:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
time="2021-05-04T09:33:29+10:00" level=debug msg="Starting Duo Push Auth Attempt for lsultana from IP 2001:8003:220c:a00:d1f2:ac30:7723:ab0b" method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:33:29+10:00" level=warning msg="Duo Push Auth failed to process the auth request for lsultana from 2001:8003:220c:a00:d1f2:ac30:7723:ab0b: Invalid request parameters (username), error code 40002. This error often occurs if you've not setup the username in the Admin Dashboard." method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"

time="2021-05-04T09:33:35+10:00" level=debug msg="Mark authentication attempt made by user lsultana" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:33:35+10:00" level=debug msg="Credentials validation of user lsultana is ok" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:33:36+10:00" level=debug msg="Starting Duo Push Auth Attempt for lsultana from IP 2001:8003:220c:a00:d1f2:ac30:7723:ab0b" method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T09:33:36+10:00" level=warning msg="Duo Push Auth failed to process the auth request for lsultana from 2001:8003:220c:a00:d1f2:ac30:7723:ab0b: Invalid request parameters (username), error code 40002. This error often occurs if you've not setup the username in the Admin Dashboard." method=POST path=/api/secondfactor/duo remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"

time="2021-05-04T10:54:36+10:00" level=info msg="Logging severity set to debug"
time="2021-05-04T10:54:36+10:00" level=debug msg="Storage schema is being checked to verify it is up to date"
time="2021-05-04T10:54:36+10:00" level=debug msg="Storage schema is up to date"
time="2021-05-04T10:54:36+10:00" level=info msg="Authelia is listening for non-TLS connections on 0.0.0.0:9091"
time="2021-05-04T10:54:44+10:00" level=debug msg="Mark authentication attempt made by user lsultana" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"
time="2021-05-04T10:54:44+10:00" level=debug msg="Credentials validation of user lsultana is ok" method=POST path=/api/firstfactor remote_ip="2001:8003:220c:a00:d1f2:ac30:7723:ab0b"

**Comment by james-d-elliott** [comment]
Your SMTP server is not configured correctly; note the errors about connecting to the SMTP server, and you have not setup the user in the DUO dashboard or have not setup the user correctly.

**Comment by lsultana98** [comment]
Ended up being the username in DUO being slightly different to the username of the local Authelia account. Thanks mate.

**Comment by james-d-elliott** [comment]
No worries glad you got it sorted, let us know if you have any other issues.
