### ISSUE TITLE
Update secrets.md with OIDC secrets

### ISSUE THREAD

**Issue by klatka** [authelia/authelia#1977]
I want to use docker secrets for the OIDC secrets but don't know the env names:

This doesn't work:
- AUTHELIA_HMAC_SECRET_FILE
- AUTHELIA_ISSUER_PRIVATE_KEY_FILE

**Comment by james-d-elliott** [comment]
Thanks for spotting this, I'll fix that now.

**Comment by james-d-elliott** [comment]
Values should be:

|Configuration Key                                |Environment Variable                                    |
|:-----------------------------------------------:|:------------------------------------------------------:|
|identity_providers.oidc.issuer_private_key       |AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE|
|identity_providers.oidc.hmac_secret              |AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE       |

**Comment by klatka** [comment]
Works!

**Comment by RandomExplosion** [comment]
Is it possible to do this with oidc client secrets?

**Comment by james-d-elliott** [comment]
No. But in 4.37 we will allow using hashes instead of plaintext.
