### ISSUE TITLE
OIDC Invalid Signature while verifying ID Token

### ISSUE THREAD

**Issue by klatka** [authelia/authelia#1979]
### Description

I set up a test client to try OIDC on https://openidconnect.net/

The workflow works fine but at step 3: Verify User Token the validation of the JWT's signature fails.

From https://openidconnect.net/:
This token is cryptographically signed with the RS256 algorithim. We'll use the public key of the OpenID Connect server to validate it. In order to do that, we'll fetch the public key from https://authelia/api/oidc/jwks, which is found in the discovery document or configuration menu options.

### Expected Behaviour

Successful validation of ID Token

### Reproduction Steps

1. Request an access code from client that is configured in config
2. Turn that access code into an access token, by having the client make a request to your token endpoint
3. Verify the ID Token

### Additional Information

At https://jwt.io/ the id token has also an invalid signature

**Comment by james-d-elliott** [comment]
Thanks for reporting this so early in the beta! I'll take a look at fixing this todayish if I can confirm it.

**Comment by james-d-elliott** [comment]
Hey @klatka using a site like: https://8gwifi.org/jwkconvertfunctions.jsp

I was able to generate the PEM which validated the JWT signature. Also the integration testing validates the key signature. What we can consider doing is adding an endpoint that provides a plain text list of public keys and their ID's in PEM format for the testing phase if it's desired.

**Comment by klatka** [comment]
From where is the public key provided in api/oidc/jwks?

I only set a private key in the configuration.

**Comment by james-d-elliott** [comment]
The public key is extracted from the provided private key. Now that I think of it, we should really provide docs on how to generate the private key.

**Comment by james-d-elliott** [comment]
You can use `authelia rsa generate --dir /path/where/you/want/the/keys`. The output of key.pem is the correct format for the input key, Authelia can derive the public key from the private key.

**Comment by klatka** [comment]
I generated a key pair with `authelia rsa generate --dir /path` and provided the private as docker secret.

Unfortunately, I can reproduce the issue if I try to validate the JWT signature. If I use this site: https://8gwifi.org/jwkconvertfunctions.jsp I can generate the PEM from the jwks endpoint (without the keys array) and then I paste it at JWT to successfully validate the id token.

I don't know why the test client at  https://openidconnect.net/ cannot verify it

**Comment by james-d-elliott** [comment]
I'm giving that a shot now to see what the results are like for me.

**Comment by james-d-elliott** [comment]
Apologies I never clicked on the URL above, I jumped to conclusions about what it was. Not working for me either which is odd.

**Comment by james-d-elliott** [comment]
I figured out what causes this. Basically the JWT we're generating doesn't include the KID which is required to match the sig key in the JWKS.

**Comment by james-d-elliott** [comment]
Just tried `authelia/authelia:fix-key-id-not-in-jwt` and it fixes the issue. :)

**Comment by klatka** [comment]
Just pulled `authelia/authelia:fix-key-id-not-in-jwt`. The token is now valid! 

Thank you for the great work!
I will try to set up some services like Grafana, Gitlab, Nextcloud with Authelia OIDC.

**Comment by james-d-elliott** [comment]
Great thanks for the confirmation. Will release to 4.29.1 soon provided it passes peer review.

**Comment by cazzoo** [comment]
Hi there.
I wonder if the fix has been pushed to master branch since latest docker image doesn't generate any KID for public clients
