### ISSUE TITLE
Yubikeys not working on mobile browsers (Opera, Chrome tested on Android)

### ISSUE THREAD

**Issue by afonsoc12** [authelia/authelia#2064]
### Description
When using U2F in a mobile browser, the key browser does not ask to tap the key. If I tap the key when it asks, it opens the Yubico Authenticator App, meaning the key was read, but not by the browser, because it isn't making that request

### Expected Behaviour
Yubikeys NFC to be read by browser

### Reproduction Steps
Login with U2F in Chrome/Opera on Android and try to tap key

### Additional Information
Tested on Samsung S10 and iPhone 12 Pro Max. In iOS, it does not even have the option for U2F

**Comment by clems4ever** [comment]
Hello @afonsoc12 , this issue is known and will be solved by https://github.com/authelia/authelia/issues/241. Please follow that one. For information, I'm currently testing the yubico implementation of webauthn and I'm having good results so far. Stay tuned.
