### ISSUE TITLE
Add a time desync detection for TOTP

### ISSUE THREAD

**Issue by clems4ever** [authelia/authelia#2068]
### Description

Many users fail to authenticate with TOTP and this is usually because of time desync between the browser and the client. We should be able to detect this case and log it for the user to fix it before retrying.

### Implementation Proposal

When validating the TOTP, the date and time retrieved by the browser could be added to the payload and the server could validate the time received is not too far from the current time on the server. If it's the case, it would probably make sense to display a message to the user saying something like: "Synchronize you local clock before retrying".

**Comment by james-d-elliott** [comment]
I agree with most of this approach. I think we can likely make the threshold configurable and set a sane default.

Regarding displaying the error, we have to decide between two viable approaches: either sending the error message if TOTP fails and the time difference is too great, or sending the message regardless. We could also opt for a combination of these I suppose with a lower threshold and upper threshold.

**Comment by clems4ever** [comment]
Or a 3rd alternative could also be to display the server time in the page and add a note telling the user that the local time should be in sync. This would not involve any error handling then.

**Comment by nightah** [comment]
> Or a 3rd alternative could also be to display the server time in the page and add a note telling the user that the local time should be in sync. This would not involve any error handling then.

I don't particularly like this approach because I don't think Authelia should need to display the time at least not in its current state, I could see this as a more patable solution in the administrative UI but not as it stands today.

> Regarding displaying the error, we have to decide between two viable approaches: either sending the error message if TOTP fails and the time difference is too great, or sending the message regardless. We could also opt for a combination of these I suppose with a lower threshold and upper threshold.

I feel like we should only display the error if it fails and is out of the threshold, also do we even need anything configurable why wouldn't we just use the period and skew to determine the threshold?

**Comment by AlexGustafsson** [comment]
The RFC contains some discussion on this (I happen to have implemented the RFC before): https://datatracker.ietf.org/doc/html/rfc6238#section-6.

Basically, one may validate the given code towards the current time step's TOTP, the the previous time step's TOTP and the next time step's TOTP. If it matches the current time step, everything's good, if it doesn't match any, the code gets rejected as usual. If the code matches one of the other tested codes, one has the choice to detect the time skew and use it for future validations. The number of steps could easily be configurable to allow, say, one historic code and one future code (+-1 time step).

**Comment by nightah** [comment]
> The RFC contains some discussion on this (I happen to have implemented the RFC before): https://datatracker.ietf.org/doc/html/rfc6238#section-6.
> 
> Basically, one may validate the given code towards the current time step's TOTP, the the previous time step's TOTP and the next time step's TOTP. If it matches the current time step, everything's good, if it doesn't match any, the code gets rejected as usual. If the code matches one of the other tested codes, one has the choice to detect the time skew and use it for future validations. The number of steps could easily be configurable to allow, say, one historic code and one future code (+-1 time step).

We actually already have implemented this in the form of the [period and skew](https://www.authelia.com/docs/configuration/one-time-password.html#period-and-skew).

This issue is more pertaining to the fact that sometimes users host/clients that are running Authelia are not synchronized to a NTP server and they aren't running a lax skew/period which results in rejection.

So identifying those specific use cases where there seems to be a time sychronization issue and notifying the end user.

**Comment by you1996** [comment]
> ## Feature Request
> ### Description
> Many users fail to authenticate with TOTP and this is usually because of time desync between the browser and the client. We should be able to detect this case and log it for the user to fix it before retrying.
> 
> ### Implementation Proposal
> When validating the TOTP, the date and time retrieved by the browser could be added to the payload and the server could validate the time received is not too far from the current time on the server. If it's the case, it would probably make sense to display a message to the user saying something like: "Synchronize you local clock before retrying".

Hi....so to understand this issue...you like to retrieve date and time from the browser, send the token and the retrieved time to the server, calculate the difference between the two dates(server and browser), check if it's greater than ``` period + (period * skew * 2) ```, check token validity and decide am I right?

**Comment by clems4ever** [comment]
@you1996 , you get the point, if `abs(servertime - clienttime) > period * (1 + 2*skew)`, we should send an error message to the user saying the clock is out-of-sync.

**Comment by you1996** [comment]
ok thanks @clems4ever, i'll be happy if i could take care of this, as first contribution !

**Comment by clems4ever** [comment]
sure, I'd be happy to review it. You can reach us on Matrix or Discord if you need some assistance.

**Comment by james-d-elliott** [comment]
We have discussed internally and identified a potential issue with the idea as previously detailed. Primarily we cannot ensure that the browser connecting to Authelia is the same device that is generating the TOTP. This presents two issues, the most important of which is if the users phone is correct, and generating the correct codes, we are detecting from their desktop browser the incorrect time thus is unreliable as a measure.

It probably makes more sense to devise a way to detect if the servers time is desync'd and having it fail on startup if it's more than x seconds out.

**Comment by james-d-elliott** [comment]
Yes, that's what we're thinking is the best option. Here is a rough implementation of a very basic NTP module in go: https://gist.github.com/james-d-elliott/fc7d7e0d6b767715a8891bf69c79873a

We have not decided on if we want to use a basic implementation like that or yet another library (https://github.com/beevik/ntp).

What we discussed in the group chat was the following design roughly:

1. Making the NTP config configurable, see below for an example.
2. Setting some sane defaults (see the config).
3. Making sure that if the NTP query fails on startup that we only display a warning and continue as everything is fine.
4. Potentially adding a periodic check to make sure the time has not drifted too much during normal operation.

```yaml
time:
  ntp_address: "time.cloudflare.com:123"
  maximum_desync: 3s
  disable_startup_check: false
```

**Comment by you1996** [comment]
Yes make sense, but still hard work for such minimal gain (NTP client implementation from scratch, making changes in many places, make the whole thing configurable..)...i feel this can be done with minimum work:
- if not valid, so we have this cases:
        - The server is not sync, so we need to execute this command(timedatectl -p NTPSynchronized show) and check the 
          output (we can here display a warning in case of non-synchronization or fail on startup) 
        - If the server is sync then the device that generating codes is not sync with the server (in this case we 
          check for the browser if it's ok then the message will be "synchronize your passcode generator (registered device)" the 
          problem then is the device time. If the browser is also not sync the message can be standard.
I think no other cases to check...true?
Making the NTP configurable is useless, especially for this little need (unless you have another use case).

**Comment by james-d-elliott** [comment]
The actual intent is to spit out an error if out of sync and make the admin fix it or disable the check entirely. The NTP client is purely to get a rough estimation of if the clock is too far away from the actual time.
