### ISSUE TITLE
Authelia reports nginx ip instead of device ip 

### ISSUE THREAD

**Issue by CMBoii** [authelia/authelia#2073]
### Description

Whenever I try to access to a service behind nginx, authelia will always report nginx ip instead of device ip. I'm running both on docker. It doesn't matter wether I access from my lan or remote ip since authelia will always think that the requests are coming from the same ip. 

### Expected Behaviour

Authelia should report each device ip like 192.168.1.X so that I can create specific rules for my lan. 

### Reproduction Steps

1.- Go to example.domain.com
2.- Authelia login shows up. 
3,- Check logs. 

### Additional Information

level=info msg="Access to https://example.domain.com/ (method unknown) is not authorized to user <anonymous>, sending 401 response" method=GET path=/api/verify remote_ip=172.x.x.x (nginx network ip)

**Comment by james-d-elliott** [comment]
You will need to ensure the `/authelia` nginx location is configured correctly, It needs the X-Forwarded-For header to identify the users IP.

https://www.authelia.com/docs/deployment/supported-proxies/nginx.html#autheliaconf

**Comment by CMBoii** [comment]
@james-d-elliott I'm using this header but it still shows the wrong ip.

```
location /authelia {
internal;
set $upstream_authelia http://192.168.1.28:9091/api/verify;
proxy_pass_request_body off;
proxy_pass $upstream_authelia;    
proxy_set_header Content-Length "";

# Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
client_body_buffer_size 128k;
proxy_set_header Host $host;
proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr; 
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 4 32k;

send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;
}

location / {
set $upstream_mealie $forward_scheme://$server:$port;
proxy_pass $upstream_mealie;

auth_request /authelia;
auth_request_set $target_url https://$http_host$request_uri;
auth_request_set $user $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
proxy_set_header Remote-User $user;
proxy_set_header Remote-Groups $groups;
error_page 401 =302 https://example.domain.com/?rd=$target_url;

client_body_buffer_size 128k;

proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

send_timeout 5m;
proxy_read_timeout 360;
proxy_send_timeout 360;
proxy_connect_timeout 360;

proxy_set_header Host $host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection upgrade;
proxy_set_header Accept-Encoding gzip;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 64 256k;

set_real_ip_from 192.168.1.0/24;
real_ip_header X-Forwarded-For;
real_ip_recursive on;

```

**Comment by james-d-elliott** [comment]
What is the IP nginx is seeing? Is it seeing the correct one when you turn on logging or an incorrect one?

**Comment by CMBoii** [comment]
> What is the IP nginx is seeing? Is it seeing the correct one when you turn on logging or an incorrect one?



I've read that the issue might be related to ngnix not working in the host network. Therefore, the issue is not related with authelia at all. 

Feel free to close th eissue if you want to. I'll fix my nginx setup and try again.

**Comment by nightah** [comment]
Are you running this on a Synology/DSM?

**Comment by CMBoii** [comment]
> Are you running this on a Synology/DSM?

Yes, I am.

**Comment by nightah** [comment]
It's an issue with their implementation of Docker, see the [following link](https://gist.github.com/pedrolamas/db809a2b9112166da4a2dbf8e3a72ae9#gistcomment-3422195).

That should resolve your issue, otherwise if that doesn't work your best bet is to use macvlan for the Docker networking.
