### ISSUE TITLE
Duo Push Notification TYPE PARAMETER - Allow passing through of requesting application/site

### ISSUE THREAD

**Issue by poldim** [authelia/authelia#2080]
### Description
This is what a basic request looks like from the Admin panel when logging in to Duo.  The login request appears to be a field that you can pass through the API.  
![image](https://user-images.githubusercontent.com/16869713/121792562-73592400-cbab-11eb-9f6a-8d320cc24148.png)
![image](https://user-images.githubusercontent.com/16869713/121792572-a6031c80-cbab-11eb-984f-2f8b68a705fc.png)

`type - This string is displayed in the Duo Mobile app push notification and UI. The default is "Login Request", so the phrase "Login Request" appears in the push notification text and on the request details screen. You may wish to specify some alternate phrase for this parameter.`

### Use Case

By being able to set this parameter through Authetlia, you would be able to specify which of your applications/services is requesting authentication.  Ideally, you can leverage this as a pass through from nginx so that when nginx requests authelia auth, it can pass along who the requestor is and Authelia would in turn send that to Duo.  This is my current config: https://blog.linuxserver.io/2020/08/26/setting-up-authelia/

**Comment by nightah** [comment]
Thanks for filing the FR @poldim, however, I don't think this is actually necessary as we implement something very similar today.

Both the organisation and application names are customisable within the Duo admin interface, which you can see represented in the below example:

**Org Name:** Tokyo-3
**Application:** Authelia

We also provide the actual site/application that the user is being authenticated/redirected for as the **Target URL**.

![IMG_5877](https://user-images.githubusercontent.com/3339418/121792948-1c505f00-cc3e-11eb-9bfa-9c06380f1563.PNG)

**Comment by poldim** [comment]
While the target URL is nice, that doesn't show when you get the DUO notification on the watch or phone without opening up the full notification to fully open the Duo app.  The key part from https://duo.com/docs/authapi - _The default is "Login Request", so the phrase "Login Request" appears in the push notification text and on the request details screen._.   This means it's visible on both the watch and phone, with lock screen locked.  

Nginx could set a header that Authelia would pass or it could add the parameter to the URL.

**Comment by nightah** [comment]
While that's true the application name is visible on both the phone/watch while locked.
Which tells you that the login request is for Authelia (or whatever you decide to name the application in Duo).

If you receive a request which you did not initiate I would so it's extremely likely that you would want to open up the notification to identify IP address it originated from and what target URL was specified. Unless I'm mistaken what's the benefit for a request that you're expecting?

**Comment by poldim** [comment]
> While that's true the application name is visible on both the phone/watch while locked.
> Which tells you that the login request is for Authelia (or whatever you decide to name the application in Duo).
> 
> If you receive a request which you did not initiate I would so it's extremely likely that you would want to open up the notification to identify IP address it originated from and what target URL was specified. Unless I'm mistaken what's the benefit for a request that you're expecting?

Just to be clear, the default duo notification includes the application name as defined for that site in the duo admin panel.  So in my case, I have named the duo application _Synology_.  My docker host has one nginx container and one authelia container which provide RP/2FA for about a dozen services.  On every notification, Duo just says Synology.  Duo currently doesn't know which of these dozen services is making the request.  It's happy to provide the auth without really caring about what is asking. I would like to be able to configure it to say _VSCode_, or _SyncThing_, or _Node-Red_.

Ideally, I'd like it to simulate the experience I have at work where my company (large enterprise) uses PingID for 2FA.  The 2FA request from pingID carries the name of the actual application requesting the auth where I'm logging in.  This is absolutely not required, but in my mind, a very nice thing to have as it makes any false requests easy to spot.  I know this isn't a large functional feature request, but I think it helps eliminate some risk and makes the 2FA feel closely integrated.

**Comment by nightah** [comment]
> Duo currently doesn't know which of these dozen services is making the request. It's happy to provide the auth without really caring about what is asking.

Well no not really, it does by virtue of the target URL, it's just not present in the notification without opening it.
Also from a configuration standpoint you actively configuring Duo with the secret and integration keys should be a sign that Duo and Authelia's is trusted and should not need to care about what is making the request, rather that it should just be making them.

> I would like to be able to configure it to say _VSCode_, or _SyncThing_, or _Node-Red_.

The lowest barrier to entry would be to allow a customisation of the `type` parameter with some placeholders from the ACLs that could be utilised.

Having said that Authelia is not aware of the applications names and only the target URL is available without modifications to the ACLs. We could consider adding a `name` key into the ACL struct.
I don't really like the idea of having nginx or any other proxy passing this information across via a header or query parameter.

> This is absolutely not required, but in my mind, a very nice thing to have as it makes any false requests easy to spot.

Honestly I'm quite confused by this statement, what do you mean by false requests? I believe the only thing this type of change will improve is providing more information to the end user at a glance. It will not help identify false requests any more than without the change.

A false request would imply that your 1FA is already compromised and a user then is attempting 2FA with Duo.
Without the proposed feature the user would be aware of a false request by vitue of the fact that the 2FA prompt is showing up on their phone without them making an actual request, not by virtue of some additional information that could be provided.

Even with the change the user can visit the auth portal directly and authenticate with 2FA, which wouldn't have a target URL or a named app (assuming we modify the ACL struct) present. A potential alternative in that scenario might be to provide a default `name`.

The fact that you can't redact the Application Name in the request means that you'll always end up seeing it which I don't think is great.
For example in your scenario if you had the `type` configured to display `Authelia login request for {targetURL}` you would end up seeing the following on the notification:

Authelia login request for https://app.example.com
Authelia login request for https://app.example.com: Synology

**Comment by clems4ever** [comment]
I fully agree with @nightah , Authelia is an SSO provider meaning that what's important is whether or not the request should be approved, but not really from which application the request came from because it makes no sense. The URL is already an additional information that could be leverage as suggested in the previous comment.

Moreover, @nightah , is right, there is no concept of protected application in Authelia except with OIDC now, but it does not change the fact that Authelia is an SSO system and the push notif is there to only approve access to ALL apps or no app.

I'm closing the issue as there is no more action on our side but we stay open to comments and reactions that might be added later.
