### ISSUE TITLE
Is Authelia Lite sufficient for "production" home server environments?

### ISSUE THREAD

**Issue by trallnag** [authelia/authelia#2103]
The documentation contains a section on why Authelia Lite is not suited for production here: <https://www.authelia.com/docs/deployment/deployment-lite.html>.

>[...] will make Authelia non resilient to failures and non scalable by preventing you from running multiple instances of the application. This means that Authelia won’t be able to distribute the load across multiple servers and it will prevent failover in case of a crash or an hardware issue.

Is HA the only reason for not going with HA? Or are there other disadvantages like every increasing memory consumption or missing support for OIDC?

**Comment by james-d-elliott** [comment]
The issue is the sessions will be lost on restart. If you can live with that it's sufficient.
