### ISSUE TITLE
PCI compliant autocomplete html input's

### ISSUE THREAD

**Issue by james-d-elliott** [authelia/authelia#2128]
### Description

Add a method to set `autocomplete="off"` on all input fields which contain sensitive information for PCI compliance. #2125 adds the normal expected field values, prior to this we were not technically PCI compliant, and we are still not after this PR. It would be nice to have an option which adjusts some of the current settings to be *more* PCI compliant. This is one such example.

### Use Case

_N/A_

**Comment by mind-ar** [comment]
Hi, according to [this](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#the_autocomplete_attribute_and_login_fields), 
> Modern browsers implement integrated password management: when the user enters a username and password for a site, the browser offers to remember it for the user. When the user visits the site again, the browser autofills the login fields with the stored values.

The browsers still  will ask to save password, but you can disable the autofill, setting `autocomplete="new-password"`

And according to [this](https://www.pcisecuritystandards.org/pdfs/best_practices_securing_ecommerce.pdf):
> Web forms should disable autocomplete for fields accepting payment details, as this may cause the web
browser to store a copy of those details after submission

They only suggests to disable autocomplete for  fields with payment information, they do not make suggestions about login pages.
we can implement this anyway, if you agree. 
I can implement something like the following

Add a new field to the response from `/api/state` 
```js
{
  "status":"OK",
  "data":
    {
      "username":"",
      "authentication_level":0,
      "default_redirection_url":"",
      "pci": true
      }
}
```

Or create a new endpoint `/api/pci`
```js
{
  "status":"OK",
  "pci": true
}
```

And use that info for change the `autoComplete` property of sensitive fields

**Comment by james-d-elliott** [comment]
After doing some more research it's not necessary for us to think about PCI compliance. It's specifically related to sites that involve financial transactions. I was dealing with a lot of PCI compliance issues at work, and one of the ways it was described was inaccurate.
