### ISSUE TITLE
Is Authelia modifying LDAP entries?

### ISSUE THREAD

**Issue by trallnag** [authelia/authelia#2170]
Ignoring the feature to change passwords (which can be disabled) are there any other situations where Authelia modifies LDAP entries? For example changing attributes or adding new ones?

I couldn't find any information on that and it is relevant for cases where the LDAP service is immutable without any persistent storage.

Thanks in advance

**Comment by james-d-elliott** [comment]
Currently there are no instances of this other than what you've mentioned, and this can be disabled.

**Comment by trallnag** [comment]
Alright, thank you
