### ISSUE TITLE
banned user web portal message banner different from API message

### ISSUE THREAD

**Issue by davama** [authelia/authelia#2195]
## Bug Report

Noticed that on the web portal if a user is banned, the message they receive is

![image](https://i.imgur.com/dqf0sm7.png)

VS 

when they try from the api they get:
```
{"status":"KO","message":"Please retry in a few minutes."}
```

### Description

Log from web portal:
```
time="2021-07-22T14:46:21Z" level=error msg="User davetest is banned until 2021-07-22 14:49:33 +0000 UTC" method=POST path=/api/firstfactor remote_ip=xxxx stack="github.com/authelia/authelia/internal/middlewares/authelia_context.go:65 (*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/handlers/response.go:148           handleAuthenticationUnauthorized\ngithub.com/authelia/authelia/internal/handlers/handler_firstfactor.go:85 FirstFactorPost.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:50 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.3.12/router.go:414                         (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14      LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.24.0/server.go:2219                       (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.24.0/workerpool.go:223                    (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.24.0/workerpool.go:195                    (*workerPool).getCh.func1\nruntime/asm_amd64.s:1371                                                 goexit"
```
Log from api:

```
time="2021-07-22T14:59:09Z" level=error msg="User davetest is banned until 2021-07-22 15:02:34 +0000 UTC" method=POST path=/api/firstfactor remote_ip=xxx stack="github.com/authelia/authelia/internal/middlewares/authelia_context.go:65 (*AutheliaCtx).Error\ngithub.com/authelia/authelia/internal/handlers/response.go:148           handleAuthenticationUnauthorized\ngithub.com/authelia/authelia/internal/handlers/handler_firstfactor.go:85 FirstFactorPost.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:50 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.3.12/router.go:414                         (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14      LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.24.0/server.go:2219                       (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.24.0/workerpool.go:223                    (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.24.0/workerpool.go:195                    (*workerPool).getCh.func1\nruntime/asm_amd64.s:1371                                                 goexit"
```

### Expected Behaviour

Would be nice if both were the same. 
The web portal one is misleading. 
The API one is more accurate.

### Reproduction Steps

Running: `Authelia version v4.29.4, build 9d6ad5aa943d9e50f72d09c41fd496d2d66f7088`

Ban myself with multiple curls:
```
curl -4 -v -d '{"username": "davetest", "password": "wrongpassword", "keepMeLoggedIn": true}' -k -XPOST https://login.domain.com/api/firstfactor
```

Then try to authenticate via the web portal vs the API

### Additional Information

Let me know if you need more information from me.

Thank you,
Dave

**Comment by james-d-elliott** [comment]
The one which is wrong in this instance is the API one, it should be less accurate. This is because we should not give information to attackers that could be utilized to figure out how the system is configured/secured.

**Comment by davama** [comment]
I see
That makes sense.
Can the gui one say something similar to the user?
“Temporarily banned. Wait until <time>”

**Comment by james-d-elliott** [comment]
> “Temporarily banned. Wait until ”

A design decision we had previously discussed is the reason for failed authentication should be indistinguishable to attackers, implementing a change like that would break that. However I can ask the team what they think.

**Comment by davama** [comment]
I guess perhaps, instead of some visible banner, maybe some email to the user? This would at least tell the user if someone is trying to access as themselves and also that they have been temporary banned for fail auth attempts.

From a security perspective, i guess having fail2ban/ppolicy on backend/authelua ban would help in this case. But thats outside of this…

guess this was not a bug report :/

**Comment by nightah** [comment]
> A design decision we had previously discussed is the reason for failed authentication should be indistinguishable to attackers, implementing a change like that would break that. However I can ask the team what they think.

Agreed I still believe this is the right approach and agree with @james-d-elliott's previous commentary around the API response being changed.

**Comment by james-d-elliott** [comment]
> I guess perhaps, instead of some visible banner, maybe some email to the user? This would at least tell the user if someone is trying to access as themselves and also that they have been temporary banned for fail auth attempts.

I think this is a decent idea. Notifying the user via email of attempts to sign in which failed enough to ban from the same IP. I think it should be something we look into when we enhance regulation more. We'd have to ensure only one email is sent to a given user for a given IP (assuming it triggered a ban).

**Comment by nightah** [comment]
Definitely a good idea for a feature request for the regulator.

I agree that there's probably significant improvements we can achieve with not too much work with the regulator.

Given that the regulator bans based only on the username right now it probably doesn't make a lot of of sense right now though.

**Comment by davama** [comment]
Thank you for the input!
Should i close this a reopen another issue as a feature request?

**Comment by nightah** [comment]
You can leave this open for now and we'll fix up the API response against this issue.
