### ISSUE TITLE
Failed to generate QRCode

### ISSUE THREAD

**Issue by balajeek** [authelia/authelia#2206]
## Bug Report
Last night, I setup authelia:latest docker and at first i set one-factor and everything worked fine.  moved on to two-factor.
then i click 'Not registered yet' and got notification 'an email sent' (for me actually its file based) so i looked at notification.txt and took the link and pasted in the same browser window where i requested.  I got 'Failed to generate QRCode' error message, tried couple for time and same thing, tried different browser and different computer and also tried on iphone, nothing worked for me, i got same message everywhere.

Then i searched thru the Issues and found one thread mentioning, and somehow the user manged to get it working by work around and another thread that a changes where done and updated to master.  But it still happening to me and i couldn't get the two-factor working.

FYI:  I looked at the sqlite2 database and see the table with tokens generated for everytime i clicked register and all token are same and its the same in the link too.

What can I do? and what can i check?
thank for the great program.

**Comment by balajeek** [comment]
to followup, I tried again now while at work, did the same, looked in the link on generated notification.txt and I notice the token is around 20 char long only, immediately check the record in the database and found a very long token, copied and pasted into the url instead of that small string, and it worked, i was able to authenticate it.

**Comment by james-d-elliott** [comment]
Hmm, this is good information, I suspect I know what is happening. Let me see if my theory is correct by devising a fix for that scenario.

**Comment by james-d-elliott** [comment]
I'd be interested in the first char after the token is cut off if you had it.

**Comment by james-d-elliott** [comment]
Can you try the following image tag: authelia/authelia:fix-url-escape-emails

**Comment by balajeek** [comment]
Sorry after i wrote i left work and was commuting my home.

I did see the email you asked for token info, since i have file based two-factor, the file that generated notifications.txt contains the link, i opened with nano, then click on the link and it opens in the browser like this:
https://<mydomain>/register?token=eyJhbGciOiJIUz31NiIsInR5aCI6IkpXVCJ9.eyJleHAiOjE2Mjc
This is clearly not the token as you can see the database table have a very long string. so we get error.

But here is what i found, in linux nano editor when you click on the link or right click copy link it only copies what you see on the screen.  There is more to this if you keep your cursor moving right it keep going until the end of the long string token.

So my conclusion its the nano editor problem.  to copy correctly you need to select from the beginning of 'http' to keep pressing the shift+right arrow until end of the text is reached.  then you get to copy the whole string.

Sorry i caused this confusion and i had to learn it the hard way.

**Comment by james-d-elliott** [comment]
That makes sense. This is likely because it wraps the string, if it's not selecting the entire string when you normally click it may be because of the chars in which case my fix may resolve it anyway.

**Comment by balajeek** [comment]
> Can you try the following image tag: authelia/authelia:fix-url-escape-emails

I hardly doubt you should be able to fix chars not showing up in nano editor, but I still gave it a try to this image too, and generated a token and it still not showing fully on nano editor.

**Comment by james-d-elliott** [comment]
Yeah I doubt it fixes it either, I'm pretty sure based on your description the chars are wrapped off the screen.

**Comment by balajeek** [comment]
Thanks for all your support. 

One more question, after the login with two factor, how long a session stays on and where in the config I can change so it can be longer for me. I had to login back in just a few min. and was wondering.

**Comment by nightah** [comment]
These are the areas in configuration which can be adapted for session durations:

https://github.com/authelia/authelia/blob/e77f79853a20d219f0d760b38c33946a79d1f209/config.template.yml#L370-L380

There's also more information in the [session docs](https://www.authelia.com/docs/configuration/session/#configuration).

**Comment by james-d-elliott** [comment]
I'm closing this just because the original and subsequent questions are answered, but feel free to reopen or open a new issue, or contact us via any of our other contact methods.

**Comment by balajeek** [comment]
thank you so much for your support.
