### ISSUE TITLE
Authelia docker service keeps restarting with level=error msg="config key not expected: log.level"

### ISSUE THREAD

**Issue by arminus** [authelia/authelia#2216]
I'm trying to set up Authelia and Traefik based on this: https://www.authelia.com/docs/deployment/deployment-lite.html
Docker is 20.10.6, build 370c289 on an Ubuntu 20.04.2 LTS

Problem is, the authelia container keeps restarting with
`time="2021-07-30T14:14:36+02:00" level=error msg="config key not expected: log.level"`
(nothing else in that log)

So far, I've only changed the domain names in the config files as needed, the only place I see log.level as a param in those files is for traefik, though, that shouldn't affect the authelia container.

Obviously, without Authelia up and running, nothing else works, i.e. the traefik container logs this:
`time="2021-07-30T12:20:40Z" level=error msg="service \"authelia-lite\" error: unable to find the IP address for the container \"/authelia\": the server is ignored" providerName=docker container=authelia-lite-69e09dc9ddb466888a370b0ce28263d597bb36944f52d6d93abb06c2d57d1ac6
`

Any idea what's going on here?

**Comment by james-d-elliott** [comment]
This is due to a inconsistency with our docs and the files in that folder, basically we're changing the path for the log level key in the next version. The fix is to do this after the second command `cd`:

`git checkout v4.29.4`

We have a PR pending that intends to fix this.

**Comment by arminus** [comment]
Thanks, that solves this issue but brings up the next: https://github.com/authelia/authelia/issues/2219
