### ISSUE TITLE
Lite example can't start letsencrypt: unable to get ACME account: read acme.json: is a directory

### ISSUE THREAD

**Issue by arminus** [authelia/authelia#2219]
Using https://www.authelia.com/docs/deployment/deployment-lite.html - "Port 80 is utilised by LetsEncrypt for certificate challenges, this will automatically provision up-to-date certificates for your domain(s)."

Doesn't work for me:

`traefik     | time="2021-07-31T11:02:52Z" level=error msg="The ACME resolver \"letsencrypt\" is skipped from the resolvers list because: unable to get ACME account: read acme.json: is a directory"
`
Tried deleting traefik/acme.json (gets recreated), putting a 600 traefik/acme.json file in place, also not working.

After that, I get self signed certs and 404s on anything being served by that setup.

**Comment by arminus** [comment]
Resolved this by deleting traefik/acme.json (the dir), deleting the container. At that point, running docker-compose up again, it just recreated the traefik/acme.json directory but this time said the 755 permission was wrong.

So I again deleted the dir and the container and put a 0 byte 600 traefik/acme.json in place before running docker-compose up again. This time, it succeeded.

**Comment by nightah** [comment]
Fixed by #2199.
