### ISSUE TITLE
Provide option to enable autopush for duo

### ISSUE THREAD

**Issue by harleypig** [authelia/authelia#2233]
## Feature Request

Add an option that triggers Duo's autopush.

### Description

Allow Duo's autopush function on a per-user and/or per-group and/or per-path basis.

### Use Case

I have family members who are continually confused by the post-login screen. I do not have TOTP or device key configured. There is an open issue for not showing unconfigured options, but it appears to be on hold (#82 -- it's 4 years old at this point).

I have to walk these family members through selecting the method, selecting the push notification, etc, on a weekly basis.

Having the autopush would reduce that area of support quite a bit as the instructions for ok'ing the login is built into the system.

**Comment by nightah** [comment]
The 2FA preference is stored when selected so it should only have to be selected once, in theory.

The only time a user would have to keep selecting the push 2fa method would be if they're actually choosing a different method and that's being set as the preference.

You should be able to confirm this through testing yourself. If that isn't occurring then it sounds like there may be a bug.

**Comment by harleypig** [comment]
Thank you for the pointer. You are correct, autopush is being activated after the first login. What I'm thinking is that  people are choosing methods on logout and then getting confused from there.

This is another point in not showing methods that aren't configured.
