### ISSUE TITLE
OIDC: Path issues

### ISSUE THREAD

**Issue by BCNelson** [authelia/authelia#2260]
### Description

As discussed in chat, there are some issues with OIDC when using the path middleware 

### Expected Behaviour

_N/A_

### Reproduction Steps

_N/A_

### Additional Information

_**Note 1 (james-d-elliott):** Currently the only known fix is to configure Authelia and NGINX to use subdomain configuration. This will work for the user in question, but other users will experience issues in the future. It would be good if we fix this to get as much information from Bradley as possible in order to replicate it. I believe currently he's using a fairly stock swag configuration, with the path set to `authelia`. We should make sure in his case that the sections we change are commented out and replaced so reverting to his old configuration if he desires is a very simple adjustment._

**Comment by james-d-elliott** [comment]
Hey Bradley, just letting you know we've played with several solutions to this. Will likely take a bit longer than initially thought but we'll stay on it!

**Comment by BCNelson** [comment]
@james-d-elliott Let me know what I can do to help.

**Comment by james-d-elliott** [comment]
@BCNelson the 4.30.3 version which is about 20 mins from releasing should fix it for you, you can test master if you see this sooner.
