### ISSUE TITLE
/usr/local/bin/healthcheck.sh: not found

### ISSUE THREAD

**Issue by RoboMagus** [authelia/authelia#2269]
## Bug Report
Since the update to 4.30.2 the health check for authelia fails due to the healt check script not being found:
```
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 24127,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-08-07T08:18:39.99447137Z",
            "FinishedAt": "2021-08-07T08:18:38.120520623Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 17,
                "Log": [
                    {
                        "Start": "2021-08-07T10:25:44.007021364+02:00",
                        "End": "2021-08-07T10:25:44.280582769+02:00",
                        "ExitCode": 127,
                        "Output": "/bin/sh: /usr/local/bin/healthcheck.sh: not found\n"
                    },
                    {
                        "Start": "2021-08-07T10:26:14.292270777+02:00",
                        "End": "2021-08-07T10:26:14.597836481+02:00",
                        "ExitCode": 127,
                        "Output": "/bin/sh: /usr/local/bin/healthcheck.sh: not found\n"
                    },
                    {
                        "Start": "2021-08-07T10:26:44.60945771+02:00",
                        "End": "2021-08-07T10:26:44.91252829+02:00",
                        "ExitCode": 127,
                        "Output": "/bin/sh: /usr/local/bin/healthcheck.sh: not found\n"
                    },
                    {
                        "Start": "2021-08-07T10:27:14.925561748+02:00",
                        "End": "2021-08-07T10:27:15.229459945+02:00",
                        "ExitCode": 127,
                        "Output": "/bin/sh: /usr/local/bin/healthcheck.sh: not found\n"
                    },
                    {
                        "Start": "2021-08-07T10:27:45.240402269+02:00",
                        "End": "2021-08-07T10:27:45.575536646+02:00",
                        "ExitCode": 127,
                        "Output": "/bin/sh: /usr/local/bin/healthcheck.sh: not found\n"
                    }
                ]
            }
        },
```

### Description
Authelia health check fails since update to latest (4.30.2)

### Expected Behaviour
Should just work after update

### Reproduction Steps
Update to 4.30.2 on RPi4

### Additional Information
This occurred after watchtower automatically updated Authelia's image. Previous version I expect to be 4.29.x, as I'm on a weekly update schedule

**Comment by james-d-elliott** [comment]
This is the healthcheck for v4.30.2:

https://github.com/authelia/authelia/blob/v4.30.2/Dockerfile#L47

As you can see we both use an absolute path, and that path is not the path you have. Can you please post your configuration?

**Comment by RoboMagus** [comment]
Thanks for the quick response @james-d-elliott, after incremental upgrades from 4.29 up to latest to find the last version that works for me I could no longer reproduce the issue. Even for 4.30.2.

My authelia config and docker-compose are pretty bare bones. Nothing there to overwrite the default CMD.
Seeing as in the [4.29.4 dockerfile](https://github.com/authelia/authelia/blob/v4.29.4/Dockerfile#L57) the healthcheck path is the same as what was failing for me, it seems that somehow the old one was still being used by docker...

**Comment by james-d-elliott** [comment]
> My authelia config and docker-compose are pretty bare bones. Nothing there to overwrite the default CMD.
> Seeing as in the [4.29.4 dockerfile](https://github.com/authelia/authelia/blob/v4.29.4/Dockerfile#L57) the healthcheck path is the same as what was failing for me, it seems that somehow the old one was still being used by docker...

Super strange! Docker weirdness. I suppose it's fixed then. If it isn't feel free to ping me or reopen.

**Comment by tehniemer** [comment]
I had this same issue, had to delete the container and recreate it to fix the problem.
