### ISSUE TITLE
Trying to access authelia gui on localhost:9091 returns error 'Request header too large'

### ISSUE THREAD

**Issue by BackedUpBooty** [authelia/authelia#2270]
### Description

Trying to access the container gui returns an error of 'Request header too large' . After this an error pops up in logs `error when reading request headers: cannot find http request method`. See pastebin link below.

### Expected Behaviour

localhost:9091 in the browser address bar takes me to the authelia login page

### Reproduction Steps

1. Create LDAP account on Synology NAS
2. Create mysql container and create db and user:pass
3. Create redis container 
4. Spin up authelia container to pull a sample configuration.yml, stop authelia container, modify configuration.yml to my requirements including LDAP, mysql and redis IP:port and credentials, start authelia container
5. Navigate to localhost:9091 to access authelia gui

### Additional Information

Logs: https://pastebin.com/rtnABPq9
Configuration.yml: https://pastebin.com/fsMvcvXu

**Comment by james-d-elliott** [comment]
You need to tweak the buffer sizes most likely:

https://www.authelia.com/docs/configuration/server.html#read_buffer_size

But those logs are blank so there's no information to go off.

**Comment by BackedUpBooty** [comment]
Hey, thanks for the reply and edit. I'd posted all the logs I had access to from Portainer and bashing into the container and `--help` didn't show any other commands I could use for more detailed logs. 

I'm using Chrome, here's a screenshot with console open:
![image](https://user-images.githubusercontent.com/53868636/128621672-1c507bd4-b415-421b-9e1e-4eb7ba5ca9da.png)

**Comment by james-d-elliott** [comment]
> Edit: I doubled the buffer read and write sizes, and I'm now able to access the gui. To be honest I don't know enough about this kind of stuff to comment, but it seems to be working for the moment!

That's strange, it sounds like maybe you have a really large cookie in your browser being sent to Authelia potentially?

**Comment by BackedUpBooty** [comment]
Yeah I'm wondering if it's got something to do with the uBlock Origin or Canvas Fingerprint Defender extensions I have in chrome, otherwise I'm at a loss.

**Comment by james-d-elliott** [comment]
> Yeah I'm wondering if it's got something to do with the uBlock Origin or Canvas Fingerprint Defender extensions I have in chrome, otherwise I'm at a loss.

That could be it, only time I've seen request header too large was when someone was visiting a URL with about 3900 characters and being redirected haha. You can view it in the browser dev tools, I'll consider this fixed, feel free to open another issue or reopen this one if your problems persist.
