### ISSUE TITLE
Authelia isn't registered in GoLang's indexing server

### ISSUE THREAD

**Issue by yurivict** [authelia/authelia#2271]
I use the script to download all registered Go projects:
```
cat go-retrieve-all-packages.sh
#!/bin/sh

SINCE=$1 # like 2021-08-01T00:00:00Z

while [ -n "${SINCE}" ]; do

        # download
        echo "downloading SINCE=${SINCE}"
        wget "https://index.golang.org/index?limit=2000&since=${SINCE}" -q -O output-${SINCE}.json

        # get last since
        SINCE_NEW=`tail -1 output-${SINCE}.json | sed -e 's|.*"Timestamp":"||; s|".*||'`

        # EOF?
        if [ "${SINCE_NEW}" = "${SINCE}" ] || [ -z "${SINCE_NEW}" ]; then
                echo "=== End of project list reached @ ${SINCE} ==="
                exit 0
        else
                SINCE=${SINCE_NEW}
        fi
done
```

Files that ```go-retrieve-all-packages.sh 2021-08-01T00:00:00Z``` save don't contain "authelia" even though 3 Authelia releases were made since this time.

**Comment by yurivict** [comment]
FreeBSD ports framework attempts to read Autelia dependencies from the indexing server but fails to find Authelia's record there.

**Comment by nightah** [comment]
Hi @yurivict I'm not really sure how this fits into the grand scheme of things and how it's meant to work.

https://pkg.go.dev/github.com/authelia/authelia seems to imply the last update was in July so I'm not sure if this warrants a bug being lodged upstream to golang per the instructions [here](https://index.golang.org/).

> Status: Launched
These services are ready for production use. Please file issues if you spot them, with the title prefix "proxy.golang.org": (or index.golang.org, or sum.golang.org).

Having said that I believe you would run into another issue during the build regarding a unsupported dep.
The SQLite library we now use doesn't support FreeBSD, not sure if perhaps that is contributing to whatever issues you're seeing (I did send you an email about this on 22/06).

**Comment by yurivict** [comment]
I filed the bug for the Golang indexing server https://github.com/golang/go/issues/47611

FreeBSD retrieves project versions based on this server's data.

If some library doesn't support FreeBSD a Bug should probably be created for this.

**Comment by yurivict** [comment]
Their answer:
```
One obvious issue is that the projects module path does not match its major version. It is currently at major version 4 but the module import path (see https://golang.org/doc/modules/gomod-ref#module) indicates a version 0/1. Because of this mismatch the Go infrastructure does not pick up any new releases.

```

**Comment by nightah** [comment]
We will look at fixing our module path, will keep this issue open to track the fix.

In regards to the library not supporting FreeBSD, you can actually work around this in your build process, if we controlled the FreeBSD build process we would do the following before a build:
```
go mod edit -replace=modernc.org/sqlite=github.com/mattn/go-sqlite3@v1.14.8
````
This replaces the unsupported FreeBSD library with a supported one.

The other large change since the last version released on Ports would be the build info being passed in with LDFLAGS, here's how we addressed it in our [AUR package](https://aur.archlinux.org/cgit/aur.git/commit/?h=authelia-git&id=0c7297a539f3f55b383120da6ee4a43d461700c3).

I think the following for your Ports build would suffice:
```
COMMIT=$(git rev-parse HEAD)
TAG=$(git describe --tags --abbrev=0)
CLEAN=$(git diff --quiet && echo "clean" || echo "dirty")
STATE="tagged ${CLEAN}"
DATE=$(date +"%a, %d %b %Y %R:%S %z")
XOPTIONS="-X 'github.com/authelia/authelia/internal/utils.BuildBranch=master' -X 'github.com/authelia/authelia/internal/utils.BuildTag=${TAG}' -X 'github.com/authelia/authelia/internal/utils.BuildCommit=${COMMIT}' -X 'github.com/authelia/authelia/internal/utils.BuildDate=${DATE}' -X 'github.com/authelia/authelia/internal/utils.BuildState=${STATE}' -X 'github.com/authelia/authelia/internal/utils.BuildNumber=Ports'"
```

**Comment by nightah** [comment]
@yurivict running the script now produces the following:

```
output-2021-08-11T00:00:00Z.json:885:21:{"Path":"github.com/authelia/authelia/v4","Version":"v4.30.4-0.20210811010435-27532f5ebd3c","Timestamp":"2021-08-11T01:11:21.722579Z"}
output-2021-08-11T00:00:00Z.json:1296:21:{"Path":"github.com/authelia/authelia/v4","Version":"v4.30.4","Timestamp":"2021-08-11T02:00:37.693432Z"}
```

The latter being the result of the release that was just pushed.
