### ISSUE TITLE
Documentation Update: Redirect URI's for Wekan, Nextcloud and Portainer

### ISSUE THREAD

**Issue by jasonmc1993** [authelia/authelia#2281]
Please update documentation to add Known OIDC Redirect URI's for the following applications:

Wekan (version 5.41) ---> https://wekan.example.com/_oauth_oidc
Portainer CE (version 2.6.1) ---> https://portainer.example.com
Nextcloud (Requires Add-on: [Here](https://github.com/pulsejet/nextcloud-oidc-login), Version 22.1.0) --> https://nextcloud.example.com/apps/oidc_login/oidc

**Comment by nreymundo** [comment]
I just sent a PR last night with a proposed update for Nextcloud -> https://github.com/authelia/authelia/pull/2298 <- didn't see this before. 

I don't use the other two but if they work I can update my PR later to include them.

**Comment by nightah** [comment]
Closed by #2298 and #2302.
