### ISSUE TITLE
Accessing Authelia with Cookies deactivated crashes authelia service

### ISSUE THREAD

**Issue by Tropaion** [authelia/authelia#2285]
Recently I accidently tried accessing authelia with cookies deactivated and the service stopped.
I didn't find anything in the logs and authelia is running in an Debian 10 LXC with NGINX Reverse Proxy and NGINX Proxy Manager in light mode.

**Comment by nightah** [comment]
Authelia will not work without cookies, you need cookies turned on otherwise you will constantly go through a login loop if it cannot be set.

Ensure cookies are turned on and if you're still experiencing issues please describe reproduction steps and provide your Authelia configuration and logs.

**Comment by Tropaion** [comment]
I know, and I normally always use cookies, but it would be nice if the authelia service doesn't exit with failure when someone tries to access it without cookies.
But this isn't the only weird behaviour, when someone tries to log in and failes (wrong username/password) authelia is not reachable anymore and I get an 502 Bad Gateway Openresty Error, the services don't exit. I can only get access again when I restart the container.

**Comment by james-d-elliott** [comment]
This is something we actively test which doesn't occur under normal circumstances. Which authentication backend are you using?

**Comment by Tropaion** [comment]
I have installed the light version and use a file for authentication, currently with one user which looks like this:
`# Generate password with: /usr/bin/authelia hash-password 'yourpassword' -i1 -k32 -l16 $
users:
  admin:
    displayname: "Max Mustermann"
    password: "$argon2id$v=19$m=262144,t=1,p=MY_HASH_CODE
    email: max.mustermann@gmail.com
    groups:
      - admins
      - dev`

**Comment by james-d-elliott** [comment]
What memory constraints does the system have, and what restrictions on memory usage are there? Authelia should not just exit without a message, it should at the very least provide a panic message unless it's being OOM killed by some supervisory service i.e. docker. The configuration in the lite compose does not have the `mem_limit` option enabled however.

**Comment by Tropaion** [comment]
I only installed authelia recently, started with v4.30.2 and updated to v4.30.4 two days ago. I had these problems with both versions.
The authelia log is empty and I attached the output from `journalctl -u authelia`.
What is also weird is that it says `level=info msg="Log severity set to info` even though I clearly set it to debug in the configuration.yml
[journalctl.log](https://github.com/authelia/authelia/files/6982539/journalctl.log)
[configuration.yml.txt](https://github.com/authelia/authelia/files/6982571/configuration.yml.txt)
Im not using docker, I'm running authelia in an Debian 10 LXC. 
I don't know much about memory constraints, I haven't set any, but the Container has maximum of 512MB RAM, but it never uses nearly that much.

**Comment by james-d-elliott** [comment]
Yeah the journalctl.log indicates either someone is running `kill -9` on the process or OOM killer is probably killing it. I'd suggest checking syslogs around that time maybe. I don't know a whole lot about LXC but doesn't the 512MB RAM constraint also account for system services?

**Comment by Tropaion** [comment]
Which syslog is relevant? Could it be that openresty is killing the process?
512MB is the constraint for the whole container and everything running in it. It is the available RAM to use for everything in the container, also for the system services.

**Comment by james-d-elliott** [comment]
> 
> 
> Which syslog is relevant? Could it be that openresty is killing the process?
> 512MB is the constraint for the whole container and everything running in it. It is the available RAM to use for everything in the container, also for the system services.

Can you check the amount of unused RAM without Authelia running?

**Comment by Tropaion** [comment]
Without Authelia I have 340MB unused RAM.
This is in /var/log:
![log](https://user-images.githubusercontent.com/6797663/129493269-116e8b95-faac-4530-8637-83c0c004ea2a.png)
I have searched syslog, and the only messages with authelia are these:
`Aug 15 11:21:05 ReverseProxy authelia[7242]: time="2021-08-15T11:21:05Z" level=info msg="Access to https://nas.flowerhouse.at/atom.xml (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=207.46.13.179
Aug 15 11:22:25 ReverseProxy authelia[7242]: time="2021-08-15T11:22:25Z" level=info msg="Access to https://ve.flowerhouse.at/robots.txt (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=40.77.167.60
Aug 15 11:22:27 ReverseProxy authelia[7242]: time="2021-08-15T11:22:27Z" level=info msg="Access to https://ve.flowerhouse.at/robots.txt (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=40.77.167.60
Aug 15 11:22:34 ReverseProxy authelia[7242]: time="2021-08-15T11:22:34Z" level=info msg="Access to https://ve.flowerhouse.at/ (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=157.55.39.107`

**Comment by james-d-elliott** [comment]
That's super strange.. what version and what does your authentication backend config look like?

**Comment by Tropaion** [comment]
Do you mean the configuration.yml? I posted it in a previous comment.
Or do you mean the nginx configuration? I am using NGINX Proxy Manager and according to this instruction: https://www.reddit.com/r/selfhosted/comments/i8lx8t/authelia_and_nginx_proxy_manager_help/g1aavb8?utm_source=share&utm_medium=web2x&context=3

**Comment by james-d-elliott** [comment]
Oh yep! I forgot about that. Try adjusting the memory to 128.

**Comment by Tropaion** [comment]
Sorry, but which memory do you mean? :)
Some configuration in NGINX or limiting the available RAM for Authelia itself (don't know how to do that with a systemctl service).

**Comment by james-d-elliott** [comment]
```yaml
authentication_backend:
  disable_reset_password: false
  file:
    path: /etc/authelia/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 128
      parallelism: 8

**Comment by Tropaion** [comment]
I changed it but it didn't solve the problem. When I login with false userdata or without cookies authelia dies.
![error](https://user-images.githubusercontent.com/6797663/129627590-89e0e99d-e046-4f5a-b058-2a31f837b3bd.png)
* authelia.service - Authelia authentication and authorization server
   Loaded: loaded (/etc/systemd/system/authelia.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Mon 2021-08-16 20:44:47 UTC; 1min 56s ago
  Process: 1210 ExecStart=/usr/bin/authelia --config /etc/authelia/configuration.yml (code=killed, signal=KILL)
 Main PID: 1210 (code=killed, signal=KILL)

> Aug 16 16:39:42 ReverseProxy authelia[1210]: time="2021-08-16T16:39:42Z" level=info msg="Access to https://nas.mydomain.at/sitemap_index.xml (method unknown) is not authorized to 
> Aug 16 17:17:58 ReverseProxy authelia[1210]: time="2021-08-16T17:17:58Z" level=info msg="Access to https://nas.mydomain.at/sitemap.txt (method unknown) is not authorized to user <
> Aug 16 19:19:48 ReverseProxy authelia[1210]: time="2021-08-16T19:19:48Z" level=info msg="Access to https://nas.mydomain.at/sitemaps.xml (method unknown) is not authorized to user 
> Aug 16 20:44:35 ReverseProxy authelia[1210]: [mysql] 2021/08/16 20:44:35 packets.go:123: closing bad idle connection: connection reset by peer
> Aug 16 20:44:35 ReverseProxy authelia[1210]: [mysql] 2021/08/16 20:44:35 connection.go:173: driver: bad connection
> Aug 16 20:44:35 ReverseProxy authelia[1210]: [mysql] 2021/08/16 20:44:35 packets.go:123: closing bad idle connection: connection reset by peer
> Aug 16 20:44:35 ReverseProxy authelia[1210]: [mysql] 2021/08/16 20:44:35 connection.go:173: driver: bad connection
> Aug 16 20:44:42 ReverseProxy authelia[1210]: time="2021-08-16T20:44:42Z" level=error msg="Credentials are wrong for user admin" method=POST path=/api/firstfactor remote_ip=192.168.44
> Aug 16 20:44:47 ReverseProxy systemd[1]: authelia.service: Main process exited, code=killed, status=9/KILL
> Aug 16 20:44:47 ReverseProxy systemd[1]: authelia.service: Failed with result 'signal'

**Comment by james-d-elliott** [comment]
Try with something substantially lower like 32, I doubt that'll fix it, but we've never seen this so it's rather strange.

**Comment by Tropaion** [comment]
If it is easier or more helpfull I can open SSH access for you to try and debug it, since it is only an container with backups I don't have an issue with it.

**Comment by james-d-elliott** [comment]
It reduces the hashing strength, which is used to store passwords, but not considerably. Also it's important if you change the argon2id settings you reset passwords (so the stored hashes are not using the old settings and still causing issues).

**Comment by Tropaion** [comment]
How do I reset passwords? I only changed them in the file.
BTW I tried mulitplying by 2 and it works with m=32,p=4 and m=64, p=8. m=128, p=16 and upwards it starts failing.
Is this an underlying issue in Authelia or is it my setup?

**Comment by james-d-elliott** [comment]
It's your setup, you have to tune it for what your system can cope with or use the sha512 option. That sounds fine, make sure to change multiple passwords.

**Comment by Tropaion** [comment]
Okay, thanks for your prolonged support ;)
