### ISSUE TITLE
docker container 4.30.4 still unhealthy (was an older issue)

### ISSUE THREAD

**Issue by mamema** [authelia/authelia#2312]
using 4.30.4

the command 

wget --quiet --tries=1 --spider http://localhost:9091/api/state; echo $?

gives back a 0
container runs, but stays unhealthy

**Comment by nightah** [comment]
That's not the command that the healthcheck should be running.
Have you manually overridden the healthcheck? I would suggest removing the container and recreating it to ensure there isn't some odd caching behaviour.

**Comment by mamema** [comment]
no, i have launched this command line in the console, it was mentioned by you in an earlier thread regarding the "old" unhealthy bug.
I've already recreated the container without success....

**Comment by james-d-elliott** [comment]
Please provide the container configuration - either run or compose. Additionally by recreate did you specifically delete the old container?

**Comment by mamema** [comment]
Yes, container is always deleted during recreate....

Here my config:

###############################################################
#                   Authelia configuration                    #
###############################################################
server:

# The port to listen on
  host: 0.0.0.0
  port: 9091
 
 ## Set the single level path Authelia listens on.
  ## Must be alphanumeric chars and should not contain any slashes.
  path: ""

  ## Buffers usually should be configured to be the same value.
  ## Explanation at https://www.authelia.com/docs/configuration/server.html
  ## Read buffer size adjusts the server's max incoming request size in bytes.
  ## Write buffer size does the same for outgoing responses.
  read_buffer_size: 4096
  write_buffer_size: 4096

  ## Enables the pprof endpoint.
  enable_pprof: false

  ## Enables the expvars endpoint.
  enable_expvars: false

  ## Disables writing the health check vars to /app/.healthcheck.env which makes healthcheck.sh return exit code 0.
  ## This is disabled by default if either /app/.healthcheck.env or /app/healthcheck.sh do not exist.
  disable_healthcheck: false

 
log:
# Log level
#
# Level of verbosity for logs
  level: info
  file_path: /var/log/authelia

# The secret used to generate JWT tokens when validating user identity by
# email confirmation.
jwt_secret: secret



# Default redirection URL
#
# If user tries to authenticate without any referer, Authelia
# does not know where to redirect the user to at the end of the
# authentication process.
# This parameter allows you to specify the default redirection
# URL Authelia will use in such a case.
#
# Note: this parameter is optional. If not provided, user won't
# be redirected upon successful authentication.
default_redirection_url: https://url

# TOTP Issuer Name
#
# This will be the issuer name displayed in Google Authenticator
# See: https://github.com/google/google-authenticator/wiki/Key-Uri-Format for more info on issuer names

#totp:
  # The issuer name displayed in the Authenticator application of your choice
    # See: https://github.com/google/google-authenticator/wiki/Key-Uri-Format for more info on issuer names
#	  issuer: authelia.com
totp:
  issuer: example.com
  period: 30
  skew: 1




# Duo Push API
#
# Parameters used to contact the Duo API. Those are generated when you protect an application
# of type "Partner Auth API" in the management panel.
duo_api:
  hostname: api-example.com
  integration_key: key
  secret_key: key

# The authentication backend to use for verifying user passwords
# and retrieve information such as email address and groups
# users belong to.
#
# There are two supported backends: `ldap` and `file`.
authentication_backend:
  # LDAP backend configuration.
  #
  # This backend allows Authelia to be scaled to more
  # than one instance and therefore is recommended for
  # production.
  ldap:
    # The url of the ldap server
    url: ldap://ldap

    # The base dn for every entries
    base_dn: dc=domain=com

    # An additional dn to define the scope to all users
    additional_users_dn: ou=users

    # The users filter used to find the user DN
    # {0} is a matcher replaced by username.
    # 'cn={0}' by default.
    users_filter: (&({username_attribute}={input})(objectClass=inetOrgPerson))

    username_attribute: uid

    # An additional dn to define the scope of groups
    additional_groups_dn: ou=groups

    # The groups filter used for retrieving groups of a given user.
    # {0} is a matcher replaced by username.
    # {dn} is a matcher replaced by user DN.
    # {uid} is a matcher replaced by user uid.
    # 'member={dn}' by default.
    groups_filter: (&(member={dn})(objectclass=groupOfNames))

    # The attribute holding the name of the group
    group_name_attribute: cn

    # The attribute holding the mail address of the user
    mail_attribute: mail

    # The username and password of the admin user.
    user: cn=admin,dc=domain=com
    password: password

  # File backend configuration.
  #
  # With this backend, the users database is stored in a file
  # which is updated when users reset their passwords.
  # Therefore, this backend is meant to be used in a dev environment
  # and not in production since it prevents Authelia to be scaled to
  # more than one instance.
  #
  ## file:
  ##   path: ./users_database.yml


# Access Control
#
# Access control is a list of rules defining the authorizations applied for one
# resource to users or group of users.
#
# If 'access_control' is not defined, ACL rules are disabled and the `bypass`
# rule is applied, i.e., access is allowed to anyone. Otherwise restrictions follow
# the rules defined.
#
# Note: One can use the wildcard * to match any subdomain.
# It must stand at the beginning of the pattern. (example: *.mydomain.com)
#
# Note: You must put patterns containing wildcards between simple quotes for the YAML
# to be syntaxically correct.
#
# Definition: A `rule` is an object with the following keys: `domain`, `subject`,
# `policy` and `resources`.
#
# - `domain` defines which domain or set of domains the rule applies to.
#
# - `subject` defines the subject to apply authorizations to. This parameter is
#    optional and matching any user if not provided. If provided, the parameter
#    represents either a user or a group. It should be of the form 'user:<username>'
#    or 'group:<groupname>'.
#
# - `policy` is the policy to apply to resources. It must be either `bypass`,
#   `one_factor`, `two_factor` or `deny`.
#
# - `resources` is a list of regular expressions that matches a set of resources to
#    apply the policy to. This parameter is optional and matches any resource if not
#    provided.
#
# Note: the order of the rules is important. The first policy matching
# (domain, resource, subject) applies.
access_control:
  # Default policy can either be `bypass`, `one_factor`, `two_factor` or `deny`.
  # It is the policy applied to any resource if there is no policy to be applied
  # to the user.
  default_policy: two_factor

  rules:
    # Rules applied to everyone
    - domain: public.frameworx.home
      policy: two_factor

    - domain: secure.frameworx.home
      policy: one_factor
      # Network based rule, if not provided any network matches.
      networks:
        - 192.168.0.0/24
    - domain: 'secure.domain.com'
      policy: two_factor

    - domain: singlefactor.domain.home
      policy: two_factor

    # Rules applied to 'admin' group
    - domain: 'mx2.mail.example.com'
      subject: 'group:admin'
      policy: deny
    - domain: '.*$.domain.home'
      subject: 'group:admin'
      policy: two_factor

    # Rules applied to 'dev' group
    - domain: dev.domain.home
      resources:
        - '^/groups/dev/.*$'
      subject: 'group:dev'
      policy: two_factor

    # Rules applied to user 'john'
    - domain: dev.domain.home
      resources:
        - '^/users/john/.*$'
      subject: 'user:john'
      policy: two_factor


    # Rules applied to user 'harry'
    - domain: dev.domain.home
      resources:
        - '^/users/harry/.*$'
      subject: 'user:harry'
      policy: two_factor

    # Rules applied to user 'bob'
    - domain: '*.mail.domain.home'
      subject: 'user:bob'
      policy: two_factor
    - domain: 'dev.domain.home'
      resources:
        - '^/users/bob/.*$'
      subject: 'user:bob'
      policy: two_factor


# Configuration of session cookies
#
# The session cookies identify the user once logged in.
session:
  # The name of the session cookie. (default: authelia_session).
  name: synissi.de.session.id

  # The secret to encrypt the session cookie.
  secret:secret

  # The time in ms before the cookie expires and session is reset.
  expiration: 3600000 # 1 hour

  # The inactivity time in ms before the session is reset.
  inactivity: 300000 # 5 minutes

  # The domain to protect.
  # Note: the authenticator must also be in that domain. If empty, the cookie
  # is restricted to the subdomain of the issuer.
  domain: domain.com


  ## The redis connection details
  redis:
    host: 192.168.0.1.100
    port: 6379
    password: password
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0

# Configuration of the authentication regulation mechanism.
#
# This mechanism prevents attackers from brute forcing the first factor.
# It bans the user if too many attempts are done in a short period of
# time.
regulation:
  # The number of failed login attempts before user is banned.
  # Set it to 0 to disable regulation.
  max_retries: 3

  # The time range during which the user can attempt login before being banned.
  # The user is banned if the authenticaction failed `max_retries` times in a `find_time` seconds window.
  find_time: 120

  # The length of time before a banned user can login again.
  ban_time: 300

# Configuration of the storage backend used to store data and secrets.
#
# You must use only an available configuration: local, mongo
storage:
  # The directory where the DB files will be saved
   local:
     path: /var/lib/authelia/db.sqlite3

  # Settings to connect to mongo server
  # mongo:
  # url: mongodb://192.168.1.100
  # database: admin
  # auth:
  #   username: authelia
  #   password: password

# Configuration of the notification system.
#
# Notifications are sent to users when they require a password reset, a u2f
# registration or a TOTP registration.
# Use only an available configuration: filesystem, gmail
notifier:
  disable_startup_check: true
  # For testing purpose, notifications can be sent in a file
#  filesystem:
#    filename: /etc/authelia/notification.txt

  # Use your email account to send the notifications. You can use an app password.
  # List of valid services can be found here: https://nodemailer.com/smtp/well-known/
# email:
#     username: user@mail.com
#     password: password
#     sender: user@mail.com
#     service: Outlook365

  # Use a SMTP server for sending notifications
  smtp:
    username: user@gmail.com
    password: password
    host: smtp.gmail.com
    port: 587
    sender: user@gmail.com
  # Subject configuration of the emails sent.
  #  {title} is replaced by the text from the notifier
  #  subject: "[Authelia] {title}"
#    ## disable_require_tls: false
#    ## disable_verify_cert: false
     ## trusted_cert: ""

**Comment by mamema** [comment]
container version 4.31.0 runs as healthy and doesn't have problems with openldap.

only odd thing is this in. the logs:
time="2021-09-17T15:17:30+02:00" level=debug msg="notification provider: startup check skipped as it is disabled"

and the config actually is:
 disable_healthcheck: false

**Comment by nightah** [comment]
That message has nothing to do with `disable_healthcheck` it's to do with [`disable_startup_check: true`](https://www.authelia.com/docs/configuration/notifier/#disable_startup_check) in your notifier section.

Portainer does funny thing with containers which are re-created, I'd suggest removing that out of the mix initially to see if you can get things talking perhaps with compose and our examples.

**Comment by mamema** [comment]
because of this thread i've created the container from scratch. No "re-creating" via portainer. Manually created by filling out the stuff in portainer

**Comment by james-d-elliott** [comment]
Looks like this is solved, feel free to reopen or ping us if not.
