### ISSUE TITLE
Return LDAP UUID in OIDC response

### ISSUE THREAD

**Issue by MaxG88** [authelia/authelia#2313]
Hi,

I was wondering if there were any way of returning the LDAP UID in the OIDC response. My use case would be [pulsejet/nextcloud-oidc-login](https://github.com/pulsejet/nextcloud-oidc-login), as I already have a Nextcloud instance set up with LDAP and did not know about the way it used the uid for creating the user's unique Id in Nextcloud at the time. Having the LDAP UID in the OIDC response would allow one to use the feature of nextcloud-oidc-login that uses Authelia for authentication with the existing LDAP configuration for existing users.
Quote from their README:
> it supports having LDAP as the primary user backend. This way, you can use OpenID Connect to login to Nextcloud while maintaining an LDAP backend with attributes with the LDAP plugin.

Thank you.

**Comment by nightah** [comment]
The LDAP UID is included in the OIDC JWT field/attribute `sub` per the [documentation](https://www.authelia.com/docs/configuration/identity-providers/oidc.html#openid).

**Comment by MaxG88** [comment]
I mistyped. I meant to say UUID.

**Comment by nightah** [comment]
I'm not really sure what you mean by UUID, I've had a read of the link you provided and I think all the details are available it's just a matter of mapping what's coming from the OIDC response back to the attributes.

**Comment by MaxG88** [comment]
For example, here is what my Nextcloud account looks like:
![image](https://user-images.githubusercontent.com/14253281/132286952-6d7596fd-0493-4899-97ea-a73c3c84d017.png)

The internal Nextcloud username is taken from here:
![image](https://user-images.githubusercontent.com/14253281/132287041-38572895-3bdd-4c9a-871e-4fddfeb219e4.png)

This happened because I didn't change some default value when configuring LDAP in Nextcloud.

The OIDC->Existing LDAP account mapping done by the nextcloud-oidc-login plugin maps a field from the OIDC response to the internal Nextcloud username, so in my case, I would need the entryUUID for it to work.

That being said, if there was a way to return this entryUUID field in the OIDC response, I would be able to use Authelia for authentication and use the Nextcloud plugin to map to the correct existing account.

I understand that what I'm asking is probably out of scope for Authelia, but I figured it wouldn't hurt asking in case it was already possible to get that value and/or configure custom fields in the response.

**Comment by nightah** [comment]
You can change this after the fact see the following screenshot:

![Screenshot_2021-09-07-04-12-46](https://user-images.githubusercontent.com/3339418/132293361-d2060300-93f2-478b-b414-2c2ee134ba41.png)

Just make sure you select the expert option and clear the mappings so they're regenerated based on whatever your new and correct configuration is (presumably `uid`).

**Comment by MaxG88** [comment]
Yes, you can change it after the fact, but unfortunately the change is not retroactive.

As for the alternative, that was my next option if sending the UUID through the OIDC response turned out to not be possible.

Thank you!

**Comment by nightah** [comment]
Yeah sorry @MaxG88 while we could figure out a way to provide the UUID through the OIDC response I just don't see any long term value of that.

This very much is a misconfiguration issue on the Nextcloud front, I would recommend fixing that problem so you've got it at the root instead of looking for a workaround via Authelia.

Best of luck!

**Comment by MaxG88** [comment]
Sounds good, thanks for your time!
