### ISSUE TITLE
Redirection loop when resource access is denied

### ISSUE THREAD

**Issue by ViRb3** [authelia/authelia#2316]
Following the [official nginx documentation](https://www.authelia.com/docs/deployment/supported-proxies/nginx.html), the following should be added to each service:
```nginx
error_page 401 =302 https://auth.example.com/?rd=$target_url;
```
Say I add this to `foo.example.com`. The user `John` is trying to access the endpoint, but he has no access as defined by the `resources` rule. `foo` will return a 401 due to Authelia's authentication subrequest, which will redirect to `auth`. But then `auth` succeeds, because the user is already logged in, redirecting back to `foo`. This cycle repeats forever. Is there any intended way to fix it?

Thanks

**Comment by danielwindit** [comment]
Hi,

I am running into the same exact thing. The user is authenticated by Active Directory but has not the right group which is required by the `resources` rule. In the Haproxy logs I see one `401` return code and then every time the loop runs I get `403`. I thought I could fix it by removing the required group in `resources` and make sure in the `ldap` config I only retrieve users from that OU but I cannot figure out the right `ldap` configuration to do that. This way users who are not in this OU will never be authenticated and the loop stops after one `401`

Thanks

**Comment by danielwindit** [comment]
Hi,

I figured my issue out. I had to change:
`http-request redirect location https://login.example.com:8080/?rd=%[var(req.scheme)]://%[base]%[var(req.questionmark)]%[query] if protected-frontends !{ var(txn.auth_response_successful) -m bool }`
to:
`http-request redirect location https://login.example.com:8080/?rd=%[var(req.scheme)]://%[base]%[var(req.questionmark)]%[query] if protected-frontends !{ var(txn.auth_response_successful) -m bool } !{ var(txn.auth_response_code) eq 403 }`
in my haproxy.cfg. Now if a users is authenticated but not authorized the user will not be redirected again and receive a 401.

**Comment by ViRb3** [comment]
The issue in my case was unrelated to Authelia, I was silently converting all 403s to 401s, thus why everything was handled as redirect. Apologies for the noise.

**Comment by dalloro** [comment]
@ViRb3 how did you end up fixing it in nginx?

**Comment by ViRb3** [comment]
It wasn't an issue with nginx but https://github.com/ViRb3/authelia-basic-2fa/commit/6d93ac7cb914f03a2beace117569c394429d6c72.
