### ISSUE TITLE
OIDC: public client - "Client authentication failed [...]. The requested OAuth 2.0 Client does not exist."

### ISSUE THREAD

**Issue by georglauterbach** [authelia/authelia#2329]
### Description

I'm using Authelia as my OIDC identity provider for ownCloud Infinite Scale (oCIS). oCIS is a public client, so my Authelia configuration looks like this:

``` YAML
 ...
    clients: 
      - id: owncloud
        description: ownCloud
        public: true
        secret: ''
        authorization_policy: one_factor
        audience:
          - user:mypersonaluser
        redirect_uris:
          - https://cloud.mydomain.tld/index.php/apps/openidconnect/redirect
          - https://cloud.mydomain.tld/oidc-callback.html
          # ! when OpenID Connect Front-Channel Logout 1.0 is implemented
          # - https://cloud.mydomain.tld/index.php/apps/openidconnect/logout
        scopes:
          - openid
          - email
          - profile
```

On login, I am directed to Authelia, but I'm getting a `HTTP 401` response code:

``` JSON
{
  "error" : "invalid_client",
  "error_description" : "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The requested OAuth 2.0 Client does not exist."
}
```

and this log output:

``` INI
Error occurred in NewAuthorizeRequest: invalid_client
github.com/ory/x/errorsx.WithStack
    github.com/ory/x@v0.0.250/errorsx/errors.go:38
github.com/ory/fosite.(*Fosite).NewAuthorizeRequest
    github.com/ory/fosite@v0.40.2/authorize_request_handler.go:288
github.com/authelia/authelia/v4/internal/handlers.oidcAuthorization
    github.com/authelia/authelia/v4/internal/handlers/handler_oidc_authorization.go:21
github.com/authelia/authelia/v4/internal/middlewares.NewHTTPToAutheliaHandlerAdaptor.func1
    github.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:113
github.com/authelia/authelia/v4/internal/middlewares.AutheliaMiddleware.func1.1
    github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:51
github.com/fasthttp/router.(*Router).Handler
    github.com/fasthttp/router@v1.4.1/router.go:414
github.com/authelia/authelia/v4/internal/middlewares.LogRequestMiddleware.func1
    github.com/authelia/authelia/v4/internal/middlewares/log_request.go:14
github.com/valyala/fasthttp.(*Server).serveConn
    github.com/valyala/fasthttp@v1.28.0/server.go:2239
github.com/valyala/fasthttp.(*workerPool).workerFunc
    github.com/valyala/fasthttp@v1.28.0/workerpool.go:223
github.com/valyala/fasthttp.(*workerPool).getCh.func1
    github.com/valyala/fasthttp@v1.28.0/workerpool.go:195
runtime.goexit
    runtime/asm_amd64.s:1371" stack="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_authorization.go:23          oidcAuthorization
github.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:113 NewHTTPToAutheliaHandlerAdaptorfunc1
github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:51                  AutheliaMiddleware.func1.1
github.com/fasthttp/router@v1.4.1/router.go:414                                              (*Router).Handler
github.com/authelia/authelia/v4/internal/middlewares/log_request.go:14                       LogRequestMiddleware.func1
github.com/valyala/fasthttp@v1.28.0/server.go:2239                                           (*Server).serveConn
github.com/valyala/fasthttp@v1.28.0/workerpool.go:223                                        (*workerPool).workerFunc
github.com/valyala/fasthttp@v1.28.0/workerpool.go:195                                        (*workerPool).getCh.func1
runtime/asm_amd64.s:1371                                                                     goexit"
```

I looked more than twice at my ownCloud configuration. The `client_id` matches, and I don't know what's wrong ATM. The request URI looks like this:

``` HTTP
https://auth.mydomain.tld/api/oidc/authorize?client_id=owncloud&redirect_uri=https://cloud.mydomain.tld/oidc-callback.html&response_type=code&scope=openid email profile&state=3902f8bfaf274d46925253fbb4854618&code_challenge=Z7UiTOYqCoTCM6vtuhcAVjDpXEyv95L0HxRZUmdxR10&code_challenge_method=S256&response_mode=query
```

As I'm running Authelia in K8s, I have restarted the pod several times (deleting it and letting the replica-set do its work), I have checked that all `ConfigMap`s are up-to-date, etc.

### Expected Behaviour

I should be able to see Authelia's log-in screen and log in.

### Reproduction Steps

I'm not sure whether this has to do with the public client type or not. For additional information have a look at owncloud/ocis#2445.

#### Versions

Authelia: `4.30.4`
oCIS: `1.11.0` (Technical Preview)
HTTP/3 was used for all requests (not sure if this was relevant).

The documentation on OIDC states that beta2 was not implemented as of yet, but version `4.30.X` is already released. There is some confusion about this as well....

**Comment by georglauterbach** [comment]
Is there anyone to help me here?

**Comment by james-d-elliott** [comment]
Looking at the trace this appears to be a unmatched ClientID:

https://github.com/ory/fosite/blob/d022bbc2b45fd603cb12575e28bbe884170bf788/authorize_request_handler.go#L286-L290

**Comment by georglauterbach** [comment]
I double-checked the clientID, and it _should_ match. oCIS is my third OIDC client in my Authelia configuration, and the only `public` client. There other two, that precede oCIS in my Authelia configuration are private clients. Unless I looked wrong more than seven or eight times, the clietID should match...

**Comment by james-d-elliott** [comment]
Can you provide the full URL with your domain replaced with example.com?

**Comment by james-d-elliott** [comment]
> The documentation on OIDC states that beta2 was not implemented as of yet, but version `4.30.X` is already released. There is some confusion about this as well....

I forgot to update the docs I can fix that today.

**Comment by georglauterbach** [comment]
Ping me if there is more you need.

**Comment by georglauterbach** [comment]
An news on this @james-d-elliott?

**Comment by georglauterbach** [comment]
Still encountering this bug with Authelia `1.31` and latest oCIS. Possibly a bug in the public client type?

**Comment by james-d-elliott** [comment]
Hey @georglauterbach I'm still investigating this, I have combed through the code to see if there was anything obvious but cannot see anything. Everything in fosite and authelia indicates what I suggested above. I have been rather busy lately and have yet had the chance to replicate it, however I will attempt to this week.

**Comment by georglauterbach** [comment]
@coucoulala I see. That's why I decided to back to OC Classic for the moment. Interestingly, the OIDC plugin for ownCloud is developed independently. After all, what you showed is one more problem to investigate and one step more to solving this issue 👍🏼

@james-d-elliott thanks for putting time into this.

**Comment by coucoulala** [comment]
I also looked at the specification and other certified providers integrations and my impression was aswell that it was'nt required.

I actually customized Ownlcoud to use the `email` claim for the username, so I opened an issue on there side.

**Comment by georglauterbach** [comment]
@coucoulala as the issue seems to be resolved on ownCloud's side, does it work for you now with the latest version? (or do we need to wait for a new ownCloud version to be released?)

**Comment by coucoulala** [comment]
Just tested the latest `owncloud/ocis:linux-amd64` and the account provisioning / login works.

**Comment by georglauterbach** [comment]
Alright. I'd then go ahead an close this. But before I do, can I ask for one more favor @coucoulala? Could you also show me your configuration of oCIS / Authelia that works for you? Just the relevant parts, of course :)

**Comment by georglauterbach** [comment]
Ping @coucoulala, see my comment above:)

**Comment by lairdm** [comment]
I found this tiket via googling about to try the same combination, @coucoulala, I too would very much appriciate if you could post your working config for myself and others stumbling upon this thread Thank you very much!

**Comment by helgeklein** [comment]
I published a full and detailed description of how to set up and configure ownCloud Infinite Scale (oCIS) OpenID Connect authentication to Authelia on my blog:

https://helgeklein.com/blog/owncloud-infinite-scale-with-openid-connect-authentication-for-home-networks/

**Comment by marzzzello** [comment]
If someone has this issue on the 4.38 beta while using `expand-env` make sure to properly escape the client secrets (replace $ with $$). Took me quite a while to figure it out. Some hint in the [docs](https://63d20934fa12200009e12cbf--authelia-staging.netlify.app/reference/guides/templating/) would be nice.

**Comment by james-d-elliott** [comment]
> If someone has this issue on the 4.38 beta while using `expand-env` make sure to properly escape the client secrets ~(replace $ with $$)~. Took me quite a while to figure it out. Some hint in the [docs](https://63d20934fa12200009e12cbf--authelia-staging.netlify.app/reference/guides/templating/) would be nice. Edit: for me it only worked when I put the secrets in env vars

This can't be replicated, I've added tests to prove this in https://github.com/authelia/authelia/pull/4870. Maybe it's your shell or something else unrelated to Authelia.

**Comment by marzzzello** [comment]
Yes, the way you did it in the test it works. But when the config is like this and expand-env is turned on it did not work:
```yml
identity_providers:
  oidc:
    clients:
      - id: abc
        secret: $pbkdf2-sha512$310000$foo$bar
[...]
```
I tried replacing the `$`'s with `$$` but that did not work for me. I used the docker image (master).
It's just something that can be easily overlooked while upgrading and turning on expand-env.

**Comment by james-d-elliott** [comment]
https://github.com/authelia/authelia/discussions/new/choose
