### ISSUE TITLE
Too large cookie header results in 431 status code

### ISSUE THREAD

**Issue by samip5** [authelia/authelia#2331]
### Description

I have an application where I use Traefik with ForwardAuth to Authelia to authenicate users to tvheadend, and tvheadend seems to use a very large cookie for dvr things which results in 431 response after a while of browsing dvr GUIDE on tvheadend.

### Expected Behaviour

I expected it to just work reliably.

### Reproduction Steps

1. Install tvheadend and configure it with guide data
2. Install authelia
2. Install Traefik with ForwardAuth to Authelia
3. Browse the guide for a while authenicated, and have it stop working and then return 431 status code.

### Additional Information

I'm not entirely sure what shouldn't be passed to Authelia to prevent this as tvheadend seems to use cookies for it.

Request headers:
![image](https://user-images.githubusercontent.com/1703002/131383713-e164bfac-ea22-4d6b-be3f-ccc61bdea4b1.png)

**Comment by james-d-elliott** [comment]
You just need to configure the read/write buffer sizes: https://www.authelia.com/docs/configuration/server.html#read_buffer_size

**Comment by nightah** [comment]
Correct in nginx or HAProxy you could strip it on the way to the forward auth and include it to the client, you do not have this luxury with Traefik so you need to ensure that the buffer sizes can handle passing said information through Authelia.
