### ISSUE TITLE
Changing a piece of the docs

### ISSUE THREAD

**Issue by erikthegamer1242** [authelia/authelia#2341]
Documentation regarding [Setting Authelia as OIDC provider](https://www.authelia.com/docs/configuration/identity-providers/oidc.html#openid-connect) has a flaw that I found in the [example](https://www.authelia.com/docs/configuration/identity-providers/oidc.html#configuration) configuration the line: 
```
 issuer_private_key: |
      --- KEY START
      --- KEY END
```
should look like this:
```
 issuer_private_key: |-
      -----BEGIN RSA PRIVATE KEY-----
      .........................
      -----END RSA PRIVATE KEY-----
```
I found that without the first dash Authelia wouldn't parse my RSA key, also adding BEGIN RSA KEY and END RSA KEY helps to a noob like me so maybe also adding that would help.

**Comment by nightah** [comment]
The beginning `-` is not necessary, you just need to make sure that you include the respective `BEGIN` and `END` lines.

Would be happy to accept a PR to change the docs example to reflect those lines per an actual real key.
