### ISSUE TITLE
validate-config with secret files fails 

### ISSUE THREAD

**Issue by ZyanKLee** [authelia/authelia#2363]
### Description

When running `validate-config` command with secret files being set via ENV variables, we get an error for `jwt_secrets` and the ldap server password:

```
docker run --rm -v $PWD/secrets/example.txt:/tmp/secret.txt -v $PWD/authelia/config/configuration.yml:/tmp/configuration.yml -e AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE='/tmp/secret.txt' -e AUTHELIA_JWT_SECRET_FILE='/tmp/secret.txt' -e AUTHELIA_SESSION_SECRET_FILE='/tmp/secret.txt' authelia/authelia:4.30.4 authelia validate-config /tmp/configuration.yml
time="2021-09-10T15:47:09Z" level=error msg="Errors occurred while loading the configuration:"
time="2021-09-10T15:47:09Z" level=error msg="  Provide a JWT secret using \"jwt_secret\" key"
time="2021-09-10T15:47:09Z" level=error msg="  Please provide a password to connect to the LDAP server"
time="2021-09-10T15:47:09Z" level=fatal msg="Can't continue due to errors"
```

This happens regardles of the jwt_secret or ldap.password variable being available (but empty) or commented out in the configuration.

### Expected Behaviour

validate-config should recognize the secret file env variables and read the secrets from the respective files.

### Reproduction Steps

```
docker run --rm -v $PWD/secrets/example.txt:/tmp/secret.txt -v $PWD/authelia/config/configuration.yml:/tmp/configuration.yml -e AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE='/tmp/secret.txt' -e AUTHELIA_JWT_SECRET_FILE='/tmp/secret.txt' -e AUTHELIA_SESSION_SECRET_FILE='/tmp/secret.txt' authelia/authelia:4.30.4 authelia validate-config /tmp/configuration.yml
time="2021-09-10T15:47:09Z" level=error msg="Errors occurred while loading the configuration:"
time="2021-09-10T15:47:09Z" level=error msg="  Provide a JWT secret using \"jwt_secret\" key"
time="2021-09-10T15:47:09Z" level=error msg="  Please provide a password to connect to the LDAP server"
time="2021-09-10T15:47:09Z" level=fatal msg="Can't continue due to errors"
```

### Additional Information

oddly enough, this seems to work for the session.secret with the exact same handling. this happens since `4.30.0`. With `4.29.4` the same setup works fine.

**Comment by Da-da2017** [comment]
I'm confused on how this all works

**Comment by MadLizard** [comment]
I need a termux code to hack the phone to find the number

**Comment by ZyanKLee** [comment]
@MadLizard Erm? what phone? what has a phone to do with the validator?

@Da-da2017 do you need explanation on how docker works? If you can write down some specific questions I can probably help you with them. If you are having trouble with the validator and how this is implemented, I can't help much.

**Comment by Da-da2017** [comment]
I don't under stand how these files and the formular is to view this.  It looks confusing and too many steps to take

**Comment by james-d-elliott** [comment]
I will try to tackle this when I spend some time reconciling the config upgrade.

**Comment by ZyanKLee** [comment]
Thanks @james-d-elliott , you made it great again. ;-)

**Comment by james-d-elliott** [comment]
No worries, there is also a new ACL validation command :)
