### ISSUE TITLE
Clarify the wildcard domain match behavior

### ISSUE THREAD

**Issue by the-maldridge** [authelia/authelia#2371]
In the docs there is discussion around the match behavior with respect to wildcards.  What I'd like to know is if Authelia supports wildcards matching fragments of a domain slug.  For example a policy targeting https://service-staging-*.secure.example.com would match any url as long as it started with service-staging- and was under the appropriate domain path.

Is this supported?

**Comment by nightah** [comment]
This currently is not supported, the only placeholders available today are the following three:

https://github.com/authelia/authelia/blob/b4e570358e8958f65a10ad2e6a2102926795b6fc/internal/authorization/util.go#L50-L59

These are all intended to be prefixes at the start of a domain string to denote either a wildcard or placeholder replacements.

Ideally #2111 would be the approach we would take to allow matching fragments or more complex domain matching behaviour.

**Comment by the-maldridge** [comment]
Hmm, good to know.  I'm subscribed to #2111 now as that's basically exactly what I need to deploy to prod.
