### ISSUE TITLE
Support TLS against LDAP Server

### ISSUE THREAD

**Issue by naggie** [authelia/authelia#240]
ldapjs supports http://ldapjs.org/client.html#starttls but this is not exposed as an option in the authelia configuration. I'd suggest the following options:

`require_starttls` -- see below as to why forcing is essential.
`ca_crt`-- location of certificate (optional, for self-signed chains)

If I can get some time to work on this I'll attempt a PR.

Thanks!

------

For those that want to know the difference between LDAP+STARTTLS and LDAPS:

* LDAPS (`ldaps://`) is an LDAP connection wrapped in SSL. It is deprecated in favour of STARTTLS (RFC2830) (port 636)
* LDAP + STARTTLS allows the (sometimes optional!) upgrade of a non-encrypted LDAP connection. It starts off like normal on port 389. The danger here is that is STARTTLS is not required on the server and client, LDAP queries including the password could be in clear text either by default or by a stripping MITM attack.

**Comment by clems4ever** [comment]
Hello @naggie , you are right I have not made it available yet in the configuration file. I'd be glad to review your PR :).

**Comment by naggie** [comment]
I'm happy to do one, hopefully this week.

**Comment by clems4ever** [comment]
Hello @naggie , have you started to do the change yet?

**Comment by naggie** [comment]
Not yet, I will when I can but it might be a while, sorry.

**Comment by clems4ever** [comment]
This was done in https://github.com/authelia/authelia/pull/477

**Comment by naggie** [comment]
Completely forgot about this, sorry!! A moot point now it's written in Go. Thanks!
