### ISSUE TITLE
4:30* manifests unknown

### ISSUE THREAD

**Issue by sitilge** [authelia/authelia#2400]
### Description

Getting manifests unknown when pulling 4.30* (minor, patch) from the ghcr, while merely specifying the major version works:

```
 docker pull ghcr.io/authelia/authelia:4.30
4.30: Pulling from authelia/authelia
manifest unknown

docker pull ghcr.io/authelia/authelia:4.30.5
4.30.5: Pulling from authelia/authelia
manifest unknown

docker pull ghcr.io/authelia/authelia:4.30.4              
4.30.4: Pulling from authelia/authelia
manifest unknown

docker pull ghcr.io/authelia/authelia:4
4: Pulling from authelia/authelia
Digest: sha256:6036f2b1fa3214fdcf189a8f28f40a856372413984b08f15ba4fb5891d77bc0a
Status: Image is up to date for ghcr.io/authelia/authelia:4
ghcr.io/authelia/authelia:4
```

### Expected Behaviour

Manifests can be found.

### Reproduction Steps

```
docker pull ghcr.io/authelia/authelia:4.30
docker pull ghcr.io/authelia/authelia:4.30.5
docker pull ghcr.io/authelia/authelia:4.30.4
docker pull ghcr.io/authelia/authelia:4
```

**Comment by Shazcarrera96** [comment]
[]()

**Comment by nightah** [comment]
Yep it looks like the older manifests on GHCR <`4.31.0` got removed in a cleanup.
`4` `4.31` and `4.31.0` all work as does `latest` and `master`.

For now I  recommend upgrading and I'll see if I can manually push those manifests back to GHCR when I have some time.

**Comment by nightah** [comment]
@sitilge I've manually pushed the broken tags back to GHCR, please let me know if you continue to have any issues.
