### ISSUE TITLE
HAProxy via Kubernetes might be possible

### ISSUE THREAD

**Issue by jcmoraisjr** [authelia/authelia#2411]
[HAProxy Ingress](https://haproxy-ingress.github.io/) is a community driven ingress controller implementation for HAProxy. Since its v0.13 a new group of configuration keys were added allowing external authentication, [here](https://haproxy-ingress.github.io/docs/configuration/keys/#auth-external) is the relevant doc. Headers can also be customized, doc [here](https://haproxy-ingress.github.io/docs/configuration/keys/#headers). Maybe these configuration options is enough to graduate HAProxy as Kubernetes Support in your [supported proxies page](https://www.authelia.com/docs/home/supported-proxies.html). Let me know if I can be of any help.

**Comment by nightah** [comment]
@jcmoraisjr we would be happy to review additions to the documentation for this.

I'd be hesitant to add yet another k8s test specifically just for HAProxy just because it takes up a significant amount of resources during the integration test with not a lot of benefit.

If there seems to be enough of a userbase to warrant having that added as an integration test we could revisit the topic.

**Comment by james-d-elliott** [comment]
See here regarding documentation contrib: https://www.authelia.com/contributing/prologue/documentation/

**Comment by SerialVelocity** [comment]
@jcmoraisjr Have you got an example of how to set this up?

**Comment by jcmoraisjr** [comment]
Hi, I didn't find the time to test Authelia myself in order to create an example doc, we just have the documentation provided in the first comment of this issue. HAProxy Ingress has a really flexible configuration, so you'll probably make it to work. Let us know on our slack if you have any problem.

**Comment by hans-fischer** [comment]
Any updates on this front?

**Comment by james-d-elliott** [comment]
Probably similar configuration options to this assuming the service is named `authelia` in the `example` namespace and the template doesn't mangle auth-signin or other values:

```haproxy
auth-url: svc://authelia.example.svc.kubernetes.local/api/authz/forward-auth
auth-method: HEAD
auth-signin: %[var(txn.auth_response_location)]
auth-headers-request: *
auth-headers-succeed: remote-user,remote-groups,remote-name,remote-email
auth-headers-fail: -
```

**Comment by hans-fischer** [comment]
I tried to work it out, but til now no luck here :/
I got another question about the endpoints. I've red that the endpoint I'm using is lagacy (/api/verify). I want to leave that path and use the new endpoint.
After some investigation I realised that /api/authz/forward-auth is provided by my authelia.

curl http://authelia.authelia.svc.cluster.local/api/authz/forward-auth -> 404 Not Found

What have I missed to configure?

**Comment by hans-fischer** [comment]
I got in running over the lagacy endpoint.

The example from @james-d-elliott did not work for some reasons:

1. auth-url: svc://authelia.example.svc.kubernetes.local/api/authz/forward-auth
That is not the correct usage of the svc:// Attribute. svc refferences a kubernetes service in the way `<namespace>/<service>:<port>`
So correct would be: 
`svc://authelia/authelia:80/api/authz/forward-auth`
**But you have to enable cross-namespace reading witch is disabled by default.**
I would prefer kubernetes URIs like: http://authelia.authelia.svc/api/authz/forward-auth

2. X-Forwarded-Proto  %[var(req.scheme)]
var(req.scheme) **was empty** while I was testing it and resulted in the following error:
`Unable to parse target URL: Unable to parse URL ://mail.example.de/webmail/: parse \"://mail.example.de/webmail/\": missing protocol scheme`
I also tested just X-Forwarded-Proto  %[req.scheme] witch was also empty. So I added the following lines to the haproxy-configMap below key config-frontend:

```
http-request set-var(txn.scheme) str(https) if { ssl_fc }
http-request set-var(txn.scheme) str(http) if !{ ssl_fc }
```

And used: 
`X-Forwarded-Proto  %[var(txn.scheme)]`
