### ISSUE TITLE
Possible feature: A docker option, without relying on Traefik

### ISSUE THREAD

**Issue by loftwah** [authelia/authelia#2417]
I am looking to play around with this application and the way I do things in Docker is slightly different than most, and it involves me usually gutting all of the system level parts of the application. Traefik seems to be a huge part of what we're running here, and also, what if I don't want to do Let's Encrypt for certs? Do you think this is a use case that others might also use? I'm going to be setting it up anyway so would you like me to share the docker-compose.yml file I come up with?

Cheers
Dean

**Comment by james-d-elliott** [comment]
So realistically Authelia can operate with nginx, traefik, or haproxy. There are examples which can be applied to all of these. Authelia is just a fairly standard web service. The certificates themselves are irrelevant to how Authelia works, it just needs to operate with HTTP over TLS `https://`.

It would be good to share, it's something we'd ideally want to improve in the future.

**Comment by loftwah** [comment]
Wicked, I'll paste a gist in here when I have it running and we can work out the best spot to put it.

**Comment by clems4ever** [comment]
If what you suggest is completing the documentation regarding theme customisation, there is indeed not much in the official doc. The only documentation we have is https://www.authelia.com/docs/configuration/theme.html as far as I know but it does not tell how to customize the resources.
Perhaps what you can do for now is to document this in the community section (https://github.com/authelia/authelia/tree/master/docs/community) and if other people report the issue later we'll migrate it to the official doc. What do you think?

**Comment by loftwah** [comment]
Sounds good to me, I am happy for you to assign it to me if you like. I will learn it and update, and hopefully improve the documentation. I might need to ask about how the current themeing system works (to save me going through the entire codebase) but it shouldn't take me long.

**Comment by nightah** [comment]
I'm going to close this issue as we have documented examples on how to integrate with reverse proxies other than Traefik, as far as replacing the favicon and such goes I would follow #1630.
