### ISSUE TITLE
Small typo in secret docs

### ISSUE THREAD

**Issue by kitforbes** [authelia/authelia#2425]
I've just implemented setting secrets through environment variables, and noticed an additional `_` in your docs which I believe is not intentional. It's a tiny change, so happy to do it myself or let someone else include it in other work.

https://github.com/authelia/authelia/blob/3d312cf3b94c98f5c17b6388fb257187f705dbbf/docs/configuration/secrets.md#L25

Mentioned in the table below as `AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE` (single `_` after `AUTHELIA`).

https://github.com/authelia/authelia/blob/3d312cf3b94c98f5c17b6388fb257187f705dbbf/docs/configuration/secrets.md#L31-L44

**Comment by nightah** [comment]
Thanks for the report @kitforbes!
