### ISSUE TITLE
Send Unauthenticated SMTP (Specifially through aspmx.l.google.com)

### ISSUE THREAD

**Issue by R0NAM1** [authelia/authelia#2438]
I'm currently attempting to send unauthenticated (But TLS Encrypted) SMTP through google's restricted Gmail SMTP server, as I currently don't wish to make an account specifically for just authelia, but whenever I do it gives a TCP I/O Timeout error, current relevant config is below:

notifier:
  disable_startup_check: false
  smtp:
    host: aspmx.l.google.com
    port: 25
    timeout: 5s
#    username: test
#    password: password
    sender: authelia@tester.com
    identifier: authtest
    subject: "[Authelia] {title}"
#    startup_check_address: test@authelia.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      server_name: aspmx.l.google.com
      skip_verify: false
      minimum_version: TLS1.2

**Comment by james-d-elliott** [comment]
Can you enable debug logging and show the output? My guess from the error is it never can connect, which is a network issue.

According to this article they recommend smtp-relay.gmail.com:

https://support.google.com/a/answer/176600?hl=en

**Comment by R0NAM1** [comment]
time="2021-10-04T16:32:22Z" level=debug msg="Notifier SMTP client attempting connection to aspmx.l.google.com:25"
time="2021-10-04T16:32:27Z" level=error msg="failed to check notification provider: dial tcp: i/o timeout" stack="github.com/spf13/cobra@v1.2.1/command.go:860            (*Command).execute\ngithub.com/spf13/cobra@v1.2.1/command.go:974            (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.2.1/command.go:902            main\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:11 main\nruntime/proc.go:255                                     main\nruntime/asm_amd64.s:1581                                goexit"
time="2021-10-04T16:32:27Z" level=fatal msg="Errors occurred provisioning providers." stack="github.com/authelia/authelia/v4/internal/commands/root.go:77 cmdRootRun\ngithub.com/spf13/cobra@v1.2.1/command.go:860                 (*Command).execute\ngithub.com/spf13/cobra@v1.2.1/command.go:974                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.2.1/command.go:902                 main\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:11      main\nruntime/proc.go:255                                          main\nruntime/asm_amd64.s:1581                                     goexit"
time="2021-10-04T16:32:28Z" level=info msg="Authelia v4.30.5 is starting"
time="2021-10-04T16:32:28Z" level=info msg="Log severity set to debug"

**Comment by james-d-elliott** [comment]
What is the timeout set to for your notifier @R0NAM1 ?

https://www.authelia.com/docs/configuration/notifier/smtp.html#timeout

This error occurring at that time usually indicates the SMTP server is taking a long time to respond.

**Comment by R0NAM1** [comment]
5s, like in the example documentation, I couldn't find anywhere online that stated what it should be so I assumed it was slandered for the protocol.

**Comment by james-d-elliott** [comment]
> 
> 
> 5s, like in the example documentation, I couldn't find anywhere online that stated what it should be so I assumed it was slandered for the protocol.

It indeed is, that's the default from the go standard library. We added the option to alter it because of issues like this. However the only people who've had issues that I can recall are people using Google's mail system. It's potentially grey listing which shouldn't occur when using the dedicated SMTP relay from an authorized address. However it could also potentially be issues on their end.

As pointed out the endpoint they document for this purpose is smtp-relay.gmail.com, and in several corp/enterprise environments this is the one I've configured in the past. I believe aspmx.l.google.com is an MX record which is intended for mail coming into Google Mail, not for sending mail out. If you're using G Suite and you have your public IP in your G Suite configuration as a permitted address, you can send unauthenticated email from any G Suite user via smtp-relay.gmail.com relatively easily in my experience.

**Comment by R0NAM1** [comment]
I'll tune the timeout to see if that fixes it then, if not then I'll just use smtp-relay.google.com, although I have had applications use aspmx and work perfectly fine before, so I'll look into if they have a different timeout or some other setting configured as well.

**Comment by R0NAM1** [comment]
Turns out it was unable to resolve the internet as a whole, issue is DNS, found fix in making /etc/docker/daemon.json, but side effect is Authelia does not work anymore,

Anyway I am able to set a DNS server for the Authelia docker container without borking Authelia completely?

**Comment by R0NAM1** [comment]
Am running Pihole on docker host, changed resolv.conf from local IP address to 1.1.1.1, seems to have solved all issue, going to close.
