### ISSUE TITLE
smtp notifier sender is treated as mandatory

### ISSUE THREAD

**Issue by mvadu** [authelia/authelia#2445]
### Description

Per documentation for [SMTP notifier](https://www.authelia.com/docs/configuration/notifier/smtp.html) `sender` is optional (`required: no`). However trying to start the container without it configured results in error
```
time="2021-10-04T00:50:16Z" level=error msg="Configuration: smtp notifier: the 'sender' must be configured"

time="2021-10-04T00:50:16Z" level=fatal msg="Can't continue due to the errors loading the configuration"
```

### Expected Behaviour

If documentation is correct, then this should be logged and container should come up.

### Reproduction Steps

Setup SMTP notifier without sender, and try to start Authelia

### Additional Information

v4.31.0

**Comment by nightah** [comment]
Thanks for the report this is an oversight with the documentation, the sender is a mandatory field.

I'll get that updated.
