### ISSUE TITLE
suite 'Standalone' fails because it wasn't compiled with 'CGO_ENABLED=1'

### ISSUE THREAD

**Issue by jrester** [authelia/authelia#2452]
### Description

When running the command `authelia-scripts suites setup Standalone` it failes with the following error

```
FATA[0000] Unable to initialize SQL database /tmp/db.sqlite3: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub  stack="/app/internal/storage/sqlite_provider.go:54
    NewSQLiteProvider\n/app/internal/commands/root.go:103                       
    getProviders\n/app/internal/commands/root.go:68                        
    cmdRootRun\n/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860
    (*Command).execute\n/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974
    (*Command).ExecuteC\n/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
    (*Command).Execute\n/app/cmd/authelia/main.go:11
    main\n/usr/local/go/src/runtime/proc.go:255                    
    main\n/usr/local/go/src/runtime/asm_amd64.s:1581               
    goexit"
```

### Expected Behaviour

_N/A_

### Reproduction Steps

1. Fetch newest changes from master
2. execute `authelia-scripts suites setup Standalone`

### Additional Information

This is probably due to [this](https://github.com/authelia/authelia/commit/e8a52f47942e3ebc8ee4eb4fc687f5e4f6d9a3c9) commit.

This can be fixed by setting `CGO_ENABLED=1` in `run-backend-dev.sh`.

**Comment by nightah** [comment]
Good catch thanks for the report @jrester, I've submitted a PR to fix this.
