### ISSUE TITLE
default_redirection_url not working for non-443 port

### ISSUE THREAD

**Issue by riggy2013** [authelia/authelia#2465]
### Description

I am following guide from https://www.smarthomebeginner.com/docker-authelia-tutorial/ to setup authelia for traefik2 reserse proxy for my other services. My little difference is, i am using port 8443 instead of default 443 as front-facing.

I tried to use default_redirection_url in configuration.yml to set as 
default_redirection_url: https://authelia.example.com:8443/

I can get authenticated with https://authelia.example.com:8443, but when I access my service protected by authelia, it will redirect to https://authelia.example.com/?rd=https%3A%2F%2Fguac.example.com%3A8443%2F instead of https://authelia.example.com:8443/...

### Expected Behaviour

_N/A_

### Reproduction Steps

redirect to https://authelia.example.com:8443

### Additional Information

I am using 4.21.0 per guide above:

  authelia:
    container_name: authelia
    # image: authelia/authelia:latest
    image: authelia/authelia:4.21.0

**Comment by james-d-elliott** [comment]
Default redirection URL is used when no URL is provided in the rd parameter. If you want the redirection to be `https://authelia.example.com:8443/?rd=https%3A%2F%2Fguac.example.com%3A8443%2F` you must configure this correctly in your RP. Can you show your RP configuration which forwards to Authelia for auth?
