### ISSUE TITLE
Authelia 4.32.0 does not start on Ubuntu 18.04

### ISSUE THREAD

**Issue by dmeulen** [authelia/authelia#2475]
## Bug Report
Authelia 4.32.0 does not start on Ubuntu 18.04 after upgrade

### Description

Authelia failed to start.

```
Oct 08 06:53:37 authelia001 authelia[5805]: /usr/bin/authelia: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/bin/authelia)
Oct 08 06:53:37 authelia001 systemd[1]: authelia.service: Main process exited, code=exited, status=1/FAILURE
Oct 08 06:53:37 authelia001 systemd[1]: authelia.service: Failed with result 'exit-code'.
```

This is a ubuntu 18.04 server running with the latest updates installed.

### Expected Behaviour

Authelia should start 

### Reproduction Steps

Install latest binary for Ubuntu.
A downgrade to 4.31.0 will bring back the authelia service

**Comment by james-d-elliott** [comment]
Yep, that's what I figured. I tested all versions 20.04 and above and they all work. The only supported version that it doesn't work on is 18.04. We're discussing what can be done.

How are you obtaining the binary out of curiosity?

**Comment by dmeulen** [comment]
I'm using the standalone binary from the apt repo:

```
[root@authelia001:/root] # cat /etc/apt/sources.list.d/authelia.list 
deb https://apt.authelia.com/stable/debian/debian all main
```

**Comment by dmeulen** [comment]
We have not planned to upgrade to 20.04 any time soon yet. 18.04 is supported until April 2023, so I guess a lot of other authelia users are still on 18.04.

**Comment by nightah** [comment]
This issue only affects LTS systems that have GLIBC <2.28 so Ubuntu Bionic, Debian Stretch.

We've identified a fix and are just finishing testing - we'll push a patch version of Authelia to resolve this issue shortly.
