### ISSUE TITLE
request for configuration example for simple local protection

### ISSUE THREAD

**Issue by rudiratlos** [authelia/authelia#2479]
my own app with included simple web server runs locally on 127.0.0.1 behind a nginx proxy. All parts (authelia, redis...) should run on 127.0.0.1. The HW is a rpi4B with latest debian.

The whole project is not using ldap at all. I also don't want a db (mariadb). It's just for about 5-10 users witg 2 groups only (admin&user).

I've successfully installed authelia and redis with apt-get. I tried to maintain configuration.yml, but at startup syslog says can not access jwt_secret... 

Can someone so kind to pass me a working configurationfile which addresses the following environment:

all processes will run locally on 127.0.0.1
only nginx is the door to the outside world, which needs auth by authelia.
local file (no mariadb) with user credentials
no ldap

best regards

**Comment by clems4ever** [comment]
Hello @rudiratlos , have you read this documentation yet? https://www.authelia.com/docs/deployment/deployment-lite.html

**Comment by rudiratlos** [comment]
had a real frustrating day. still not working.
configuration file is now accepted by authelia service. now I have probles with nginx, protecting the endpoint 127.0.0.1:4200 (shellinabox)

is there an example for nginx, to protect local ressource. I have no domain. Only the ip adress 10.8.81.166

can a kind person, supply setup for nginx. plz

**Comment by nightah** [comment]
The documentation we have provided makes some broad assumptions around how Authelia is deployed and how and it is integrated.

We don't provide examples for IP based deployments because they're few and far between.

If you want assistance with said configuration please seek support on either Matrix or Discord.
