### ISSUE TITLE
Question: Authentication against multiple backends?

### ISSUE THREAD

**Issue by tshayan** [authelia/authelia#2502]
Hello,

We are currently using LDAP backend (Active Directory) for authentication and have a situation where we need to authenticate a user that does not exist in AD and we cannot add it to AD either (logistics). I was wondering if either of the below scenarios would be possible in Authelia:

1. Create a file with the user details and configure Authelia to look in both LDAP and FILE backends (If not found in LDAP, then look in FILE). Correct me if I'm wrong but I don't believe this is possible at the moment since Authelia supports only a single authentication backend?

2. Create a local openldap server hosting the user and (somehow) configure Authelia to look in two different LDAP servers for a particular user.

Thanks in advance.

**Comment by nightah** [comment]
@tshayan you're absolutely correct that the first scenario isn't possible and it's unlikely that we would entertain the idea of adding a feature like this.

I believe the scenario @davama is detailing is an OpenLDAP proxy service, which is where you could potentially create/store and link a separate LDAP service with your AD, though this is definitely outside of the scope of Authelia.
