### ISSUE TITLE
Login Page base URL does not reflect non-standard ports

### ISSUE THREAD

**Issue by dzett** [authelia/authelia#2507]
### Description

I am running authelia in conjunction with a swag (nginx) setup, exposing it under path 'authelia' as is the default config for swag. This works fine as long as my server is running at the standard https port 443.
As soon as I configure nginx to expose the service under a non-standard port such as 17808, the loading of resouces on the login page fails.

The reason is, that while the request goes out to `https://myhost.name:17808/authelia/?rd=https://myhost.name:17808/`, with headers: 
```
Host: myhost.name:17808
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Sec-GPC: 1
Pragma: no-cache
Cache-Control: no-cache
TE: trailers
```
the returned html contains: `<!doctype html><html lang=en><head><base href="https://myhost.name/authelia/">...` which is missing the port in the URI and subsequently cannot load the further resources.

### Expected Behaviour
Logon page html contains a correct base tag including the port number.

### Reproduction Steps
Set up the Reverse Proxy to Authelia to run under a non-standard https port to observe the above.

### Additional Information
Using current latest authelia docker image 4.32.2

**Comment by james-d-elliott** [comment]
Could you please run the traefik/whoami container in the same environment and provide the output. We use the Host header to configure the base URL in the static assets I believe.
