### ISSUE TITLE
Authelia seems to be having some backend issues. 

### ISSUE THREAD

**Issue by katsie03** [authelia/authelia#2519]
Hiya.

[OS: Ubuntu 20.10
Proxy: Cloudflare (DNS Only)]

So trying to run Authelia Lite within docker, and following your official steps [here](https://www.authelia.com/docs/deployment/deployment-lite.html). I keep getting into issues which seem to be backend. With docker seeming to run fine, and authelis starting up fine, but when I try to load any pages. Such as traefik, secure, etc etc. I keep getting the same error that `404 Page not found`.

I found a similar thread to my issue (https://github.com/authelia/authelia/issues/1195), and found the hotfix and added that to my within my docker compose file with no such luck after restarting.

I have tried reinstalling, rebooting the docker containers, and trying a separate VPS with no luck, as I got the same errors. 

Please find attached screenshots down below.
If you require anything else, please let me know.

Thank You.
(All dependencies that are required are installed) 

![image](https://user-images.githubusercontent.com/50741678/137996929-c172f9a1-6ef6-4c59-b43d-b87918fb24a9.png)
![image](https://user-images.githubusercontent.com/50741678/137997126-0fde5626-368c-45ff-932c-914041b666ed.png)

**Comment by nightah** [comment]
I'm going to close this issue due to inactivity/staleness, if you are still having issues please ping us to reopen this and provide the output of the command requested above.
