### ISSUE TITLE
config files needed pls.

### ISSUE THREAD

**Issue by rudiratlos** [authelia/authelia#2527]
Hi, 

I have the following testing infrastructure:
single virtual node hosting (standalone) at linode, with LetsEncrypt certificate (e.g. linode@mycompany.com)
2. DNS entry auth.mycompany.com pointing (cname) to linode@mycompay.com

nginx
redis
authelia installed via apt on debian11
user file
storage on filesystem (sqlite)

no docker, kubernets. Just plain debian with nginx, redis and authelia.
Authelia is starting with no error in logs

I need help for nginx complete config.
auth portal is not coming up.

regards

**Comment by nightah** [comment]
@rudiratlos our examples @james-d-elliott has linked cover exactly that type of scenario.

If you are still having issues I would recommend speaking to someone on Discord/Matrix in our support channel explaining what you have configured and what your issue is so that we can help you resolve it.
