### ISSUE TITLE
Whenever I try to register my device it gives this error

### ISSUE THREAD

**Issue by khius** [authelia/authelia#2531]
<img width="1099" alt="Screen Shot 2021-10-23 at 7 22 11 PM" src="https://user-images.githubusercontent.com/6244107/138574317-9a049edd-c1fa-4d1f-b059-5f83a708bb7b.png">
### Description
I can't register my device, I get an error message and I don't get a notification in the notification.txt 
Part of my configuration.yml file
notifier:
   filesystem:
     filename: /config/notification.txt

### Expected Behaviour

_N/A_

### Reproduction Steps

_N/A_

### Additional Information

_N/A_

**Comment by khius** [comment]
These are the logs:
{"level":"debug","msg":"Storage schema is being checked to verify it is up to date","time":"2021-10-24T00:13:57Z"}
{"level":"debug","msg":"Storage schema is up to date","time":"2021-10-24T00:13:57Z"}
{"level":"info","msg":"Listening for non-TLS connections on '0.0.0.0:9091' path '/'","time":"2021-10-24T00:13:57Z"}
<com/valyala/fasthttp@v1.30.0/server.go","Line":2266,"Name":"(*Server).serveConn"},{"File":"github.com/valyala/fasthttp@v1.30.0/workerpool>
{"level":"debug","method":"POST","msg":"Mark authentication attempt made by user khius","path":"/api/firstfactor","remote_ip":"108.162.212>
{"level":"debug","method":"POST","msg":"Credentials validation of user khius is ok","path":"/api/firstfactor","remote_ip":"108.162.212.29">
{"level":"error","method":"POST","msg":"Missing header X-Forwarded-Host","path":"/api/secondfactor/totp/identity/start","remote_ip":"108.1>

**Comment by khius** [comment]
Nginx proxy manager

**Comment by james-d-elliott** [comment]
Here's the guide for setting up nginx: https://www.authelia.com/docs/deployment/supported-proxies/nginx.html

**Comment by khius** [comment]
Thank you, let me try this guide.
