### ISSUE TITLE
sub domains are exposed

### ISSUE THREAD

**Issue by dynamicat** [authelia/authelia#2566]
Recently I demonstrated authelia to a friend of whom is an IT guy.  He checked out one of my sub domains and stated that all my other sub domain names were exposed or rather visible.  I am running authelia in a docker container with traefik on the latest version.  Here is my config:

```  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: always
    expose:
      - 9091
    networks:
      - t2_proxy
    volumes:
      - ./authelia:/config
      - ./secrets:/config/secrets
    environment:
      - TZ=$TZ
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/authelia_storage_mysql_password
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia_notifier_smtp_password
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/run/secrets/authelia_duo_api_secret_key
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_mysql_password
      - authelia_notifier_smtp_password
      - authelia_duo_api_secret_key
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`authelia.mydomain.com`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.chrisgolden.cz/'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'
```

**Comment by james-d-elliott** [comment]
You have to apply the middleware to the routers which you wish to protect.

For example the nextcloud example has the following labels:

```yaml
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextcloud.rule=Host(`nextcloud.example.com`)'
      - 'traefik.http.routers.nextcloud.entrypoints=https'
      - 'traefik.http.routers.nextcloud.tls=true'
      - 'traefik.http.routers.nextcloud.middlewares=authelia@docker'
```

**Comment by dynamicat** [comment]
I have this, they are protected.  For example when I gave him my url https://portainer.mydomain.com it redirected to authelia.mydomain.com as it should.  Then he said oh I can see your other sub domains also at least the names of them.

**Comment by james-d-elliott** [comment]
I'm not sure what you mean by seeing your other sub domains. You'll need to elaborate.

**Comment by dynamicat** [comment]
Authelia is only being shown on pages that exist. that's a flaw, because i guess it only secures port 80 and 443, so if an app. like harbor for example also exposes other ports, they are still vulnerable.

**Comment by james-d-elliott** [comment]
It secures any https port that you configure with the middleware. Unless you have a concrete example where this is not the case?

**Comment by moritzj29** [comment]
if I understand correctly, you say that it is easy to find out all your subdomains you run services on by "brute forcing" or guessing the subdomain names. If a service is present Authelia will show up, if not you get a 404 or whatever.

Have you considered adding a low priority router in Traefik which catches every request to your domain? Which also shows authelia for example but routes to no service? This way every subdomain requested will show authelia, no matter if it actually protects a service or not...
https://doc.traefik.io/traefik/routing/routers/#priority

Or deploy fail2ban or the like to prevent "brute forcing" of subdomain names.

**Comment by james-d-elliott** [comment]
Ahh that maybe what he's saying - good spot. Also yes, that's the appropriate answer. A catchall domain which is secured. That being said, security through obscurity is a fairly small impact and only if you are already using a wildcard cert.

**Comment by james-d-elliott** [comment]
@dynamicat do you have any more information to add or any further questions?

**Comment by james-d-elliott** [comment]
I'm closing this due to lack of information/activity. If it's still an issue please respond/reopen.
