### ISSUE TITLE
why the domain name configuration and user configuration are not stored in mysql ?

### ISSUE THREAD

**Issue by dislazy** [authelia/authelia#2568]
Hello author, may I ask that we already have storage (mysql) now, why the domain name configuration and user configuration are not stored in mysql, is it more convenient to modify?

**Comment by james-d-elliott** [comment]
Domain name configuration? 

User Logins in DB are a planned feature, just a low priority: https://github.com/authelia/authelia/issues/1538

A better solution is generally going to be LDAP however.

**Comment by dislazy** [comment]
> Domain name configuration?
> 
> User Logins in DB are a planned feature, just a low priority: #1538
> 
> A better solution is generally going to be LDAP however.

Configure the list of domain names that require authelia
