### ISSUE TITLE
"Unable to initialize SQL database" error with NPM

### ISSUE THREAD

**Issue by Koliera** [authelia/authelia#2572]
Hi all,
I'm new to this so might be a silly thing, but I have NPM running well as a reverse proxy on docker via portainer on a OMV5 system. 
NPM works great and I can access the sites via SSL from the outside. So now I'd like to add a layer of access control on top of it, but sadly I've hit a wall and am getting the following message when trying to spin up a new docker with authelia - "level=fatal msg="Unable to initialize SQL database: dial tcp 127.0.0.1:3306: connect: connection refused".

This is the guide I used - https://thehomelab.wiki/books/dns-reverse-proxy/page/setup-authelia-to-work-with-nginx-proxy-manager

My initial thought is that the reason it's not gaining access is due to the fact that I created the NPM with a DB user & password, but looking at the Docker-compose examples online I cannot really find where to put in the necessary environments to allow authelia to access the DB that was created with NPM.

**Comment by james-d-elliott** [comment]
https://www.authelia.com/docs/configuration/storage/

This is the configuration guide for it.

Also you should create a secondary database for authelia in the database engine that only an authelia user has access to.

**Comment by james-d-elliott** [comment]
Less specific guides on environment: https://www.authelia.com/docs/configuration/#environment

**Comment by james-d-elliott** [comment]
Did you get the information you were looking for? If not feel free to reply here or jump on Matrix/Discord.

**Comment by Koliera** [comment]
Good day, thank you for checking up. I've put this on pause for a bit after realizing that my provider's router has blocked several ports and is the reason behind several issues I've had on my setup. 
Due to this I'm waiting for a new router and will try later. 
What would be the Discord server?

**Comment by james-d-elliott** [comment]
https://discord.authelia.com is a redirect to the join link. I'll close this for now but you're welcome to reopen or reply and/or ping me.
