### ISSUE TITLE
Store and implicitly allow consents for OIDC logins

### ISSUE THREAD

**Issue by rjmidau** [authelia/authelia#2598]
### Description

Add the ability allow bypassing the OpenID consent screen on a per-client basis (effectively implicitly accepting the Permissions Request screen).
This could be achieved though adding an additional attribute to the Client YAML (ie. consent_required, defaulting to true)

### Use Case

There are a number of OIDC Clients that I implicitly trust, and don't need users to Accept each time they attempt to login.

**Comment by james-d-elliott** [comment]
I feel like this in general as an idea is fine. This is somewhat appears to be part of the spec. Specifically the `prompt` parameter when set to `none`. 

https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

```
prompt
    OPTIONAL. Space delimited, case sensitive list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent. The defined values are:

        none
            The Authorization Server MUST NOT display any authentication or consent user interface pages. An error is returned if an End-User is not already authenticated or the Client does not have pre-configured consent for the requested Claims or does not fulfill other conditions for processing the request. The error code will typically be login_required, interaction_required, or another code defined in [Section 3.1.2.6](https://openid.net/specs/openid-connect-core-1_0.html#AuthError). This can be used as a method to check for existing authentication and/or consent. 
        login
            The Authorization Server SHOULD prompt the End-User for reauthentication. If it cannot reauthenticate the End-User, it MUST return an error, typically login_required. 
        consent
            The Authorization Server SHOULD prompt the End-User for consent before returning information to the Client. If it cannot obtain consent, it MUST return an error, typically consent_required. 
        select_account
            The Authorization Server SHOULD prompt the End-User to select a user account. This enables an End-User who has multiple accounts at the Authorization Server to select amongst the multiple accounts that they might have current sessions for. If it cannot obtain an account selection choice made by the End-User, it MUST return an error, typically account_selection_required. 

    The prompt parameter can be used by the Client to make sure that the End-User is still present for the current session or to bring attention to the request. If this parameter contains none with any other value, an error is returned.
```

**Comment by rjmidau** [comment]
I don't think the use of `prompt` is correct for this. Also `none` doesn't quite cover the use case I'm after as it also MUST NOT display authentication pages.
Using `none` would require users to be logged in to Authelia before attempting to access a Client. If they did not login first they wouldn't be prompted for a username/password/MFA, simply returned to the Client with login_required (which the RP would have to then handle, something I suspect a great number of them may not).

**Comment by james-d-elliott** [comment]
OpenID Relying Parties are responsible for this part of the flow. If the OpenID Provider replies with the mentioned error codes they must then adjust the prompt type accordingly. 

I can place this on a meeting agenda but I'm concerned that by implementing it outside of the spec is the incorrect choice as noted several of the prompt types indicate we should display consent/login. Several major implementations of OIDC use this method. There are other considerations as well for example if the scope `offline_access` is requested I believe it is REQUIRED to show the consent screen.

**Comment by james-d-elliott** [comment]
Thinking about this more in depth as I work on storage, a possible method that I believe complies with standards is to store consent information from users. In the instance where a client is configured to allow it, we could permit the end user to grant a consent that is remembered for a period of time.

For example:

```yaml
identity_providers:
  oidc:
    clients:
    - id: example
      remember_consent_duration: 7d
```

**Comment by Beanow** [comment]
I'm looking at Authelia as an alternative to [Keycloak](https://www.keycloak.org/) and this was a feature I happily used there. As OP suggested:
>  This could be achieved though adding an additional attribute to the Client YAML (ie. consent_required, defaulting to true)

This is exactly what Keycloak does. With a client-level consent required setting.
![image](https://user-images.githubusercontent.com/497556/160800846-7bf316ad-34e5-45de-a9c1-db74f44a45f1.png)

I don't know whether that means they break the spec, but I know the use-case is there.
It's especially useful for same organization SSO. For instance in a typical docker environment:
- `authelia.myorg.local`
- `portainer.myorg.local` (OAuth)
- `grafana.myorg.local` (OAuth)
- `traefik.myorg.local` (forward auth)

With such a setup it can't really be considered sharing data. As it's likely the same admins and the same servers hosting all of these apps. These clients also typically copy data from scopes like `email` into their internal user database. So while denying them consent later might hide an *updated* email, so long as you're not changing it, it provides a false sense of security anyway.

**Comment by james-d-elliott** [comment]
No comment on the idea to allow users to choose to remember their consent? I think it's a much nicer option regardless of specs personally. 

Flow:

1. User is sent to the authorization endpoint by an RP (with prompt=consent, or practically any other prompt type):
2. Authelia checks if the requested client has a configured consent remember duration:
  - If it's configured:
    - Authelia checks if a previous consent is recorded:
      - If no consent remembered:
          1. Prompt for consent, and allow the user to remember it.
          2. Redirect the user to the authorization endpoint.
          3. Perform scope mappings.
          4. Redirect the user to the redirect URI.
      - If consent is remembered:
          1. Perform scope mappings.
          2. Redirect the user to the redirect URI.
  - If it's not configured:
        1. Prompt for consent, and DO NOT allow the user to remember it.
        2. Redirect the user to the authorization endpoint.
        3. Perform scope mappings.
        4. Redirect the user to the redirect URI.

**Comment by james-d-elliott** [comment]
Side note, we also do not correctly handle prompt types. It's likely once we do this several OIDC compliant RP's will be able to negotiation consentless authentication (we'll probably have to add a option specifically to permit this). 

As I think I explained here, if an RP  utilizes prompt type none, the consent should not show as long as the user is logged in and has a pre-configured consent. If they receive a callback with an error of type login_required they can then utilize the prompt type login instead.

See the spec:

> prompt
>     OPTIONAL. Space delimited, case sensitive list of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent. The defined values are:
> 
>         none
>             The Authorization Server MUST NOT display any authentication or consent user interface pages. An error is returned if an End-User is not already authenticated or the Client does not have pre-configured consent for the requested Claims or does not fulfill other conditions for processing the request. The error code will typically be login_required, interaction_required, or another code defined in [Section 3.1.2.6](https://openid.net/specs/openid-connect-core-1_0.html#AuthError). This can be used as a method to check for existing authentication and/or consent. 
>         login
>             The Authorization Server SHOULD prompt the End-User for reauthentication. If it cannot reauthenticate the End-User, it MUST return an error, typically login_required. 
>         consent
>             The Authorization Server SHOULD prompt the End-User for consent before returning information to the Client. If it cannot obtain consent, it MUST return an error, typically consent_required. 
>         select_account
>             The Authorization Server SHOULD prompt the End-User to select a user account. This enables an End-User who has multiple accounts at the Authorization Server to select amongst the multiple accounts that they might have current sessions for. If it cannot obtain an account selection choice made by the End-User, it MUST return an error, typically account_selection_required.

**Comment by Beanow** [comment]
@james-d-elliott I think it's a nice idea to remember consent, though I feel like the duration still gives a false sense of security. Because clients can, and often will, save copies of the data locally.

The first time a user authenticates with a client, it's meaningful to ask consent. And I wouldn't be bothered with it even in "I own all of these applications" environments. (Though in a business environment I could totally imagine the "that's annoying, can't we turn that off?" conversation.) It might not scale well if you have absurd numbers of clients. But can't think of a use-case where you'd have both a high number of clients *and* don't want consent flows.

Perhaps rather than having a duration, we could invalidate consent when the underlying data has changed?
And have options per-client to behave differently.

```yml
identity_providers:
  oidc:
    clients:
    - id: internal-app
      remember_consent: forever # Only asks consent the first time
    - id: external-app
      remember_consent: until-update # Ask consent first time + every time the scope's data changed
    - id: back-compat
      remember_consent: never # Current behavior
```

**Comment by james-d-elliott** [comment]
Looking at the spec more closely, provided the user is logged in and has a pre-configured consent then prompt none will allow the functionality described. With the proposed option of allowing a user to remember consent provided the client is configured with a duration, admins can reasonably set a "forever" duration by setting an absurd amount of time since there is no proposed limit on this time.

For example:

```yaml
identity_providers:
  oidc:
    clients:
    - id: example
      remember_consent: 100y
```

Regarding asking for consent again for changed scope's you'll need to be more specific.. do you mean if the client is asking for different scopes? Or do you mean the claims have changed values?

**Comment by Beanow** [comment]
> Regarding asking for consent again for changed scope's you'll need to be more specific.. do you mean if the client is asking for different scopes? Or do you mean the claims have changed values?

I think (unlike `consent_required: false`) any remembering version would need to check the RP requests a subset of the remembered scopes. Applies to `remember_consent: <duration>|forever|until-update`.

1. First time `openid email`, requires consent.
1. Next `email`, subset so OK to remember.
1. Then `email profile`, profile is new, requires consent even when email is still within remember duration.

(This could skew the remember duration per scope. As after the 3rd request gains consent, `openid`'s consent will be older than the `email` and `profile` ones.)

---

What I meant with `until-update` was (on top of the above, subset of previous consent), when it's changed values. To be honest it's just throwing an idea out there, as a logical extension of "when it would be meaningful", don't know if anyone else implements it this way.

But the idea:

1. First time `email profile`, requires consent.
2. Next `email`, subset so OK to remember.
3. User configures a new email.
4. Again `email`, but requires consent as value is updated.

---

On a tangent, alternative naming that crossed my mind:

```yml
remember_consent: forever | until-update | never
# could be
ask_consent: once | when-changed | always

remember_consent(_duration): 1w
# could be
ask_consent_after: 1w
```

For the durations not a big difference, but these may be more intuitive
```yml
remember_consent: never
ask_consent: always
```

**Comment by Beanow** [comment]
In terms of what my own needs are though, by far the most pressing is less friction for internal apps. Any of these would cover the bulk of my usage.

```yml
consent_required: false
ask_consent: once
remember_consent: 100y
```

I rarely have a situation where I use external clients, let alone enough of them that I'd want to do granular consent management.

**Comment by james-d-elliott** [comment]
> I think (unlike `consent_required: false`) any remembering version would need to check the RP requests a subset of the remembered scopes. Applies to `remember_consent: <duration>|forever|until-update`.

Makes sense. I'm inclined to ensure the scopes are a 100% match initially then potentially introduce an option later per-client if there are no major issues with the idea of subset matching. 

> (This could skew the remember duration per scope. As after the 3rd request gains consent, `openid`'s consent will be older than the `email` and `profile` ones.)

This doesn't really have an impact because remembering consent would only affect if that consent can issue new grants, not when the grants expire etc.

> In terms of what my own needs are though, by far the most pressing is less friction for internal apps. Any of these would cover the bulk of my usage.

I've been working heavily on 4.35.0 which implements persistent storage for OIDC, part of that lead me towards implementing the necessary backend for pre-configured consent. It's possible but unlikely that I'll manage to do this for 4.35.0.

**Comment by james-d-elliott** [comment]
And it works :)  Just cleanup, testing, and some visual changes to go. See the related PR if interested, but there are database schema changes which are NOT final so you should only try it on a testing database, not your production one.

![image](https://user-images.githubusercontent.com/3903683/161403499-7fedc193-1fdb-4a79-a9a2-f34e7767d5e5.png)

**Comment by alphabet5** [comment]
@james-d-elliott here are a few resources I found when looking at 'no consent'

[Curity](https://curity.io/resources/learn/the-relationship-between-consent-and-claims/)

```
Consent is normally not used when the Client and the OpenID Connect Provider belong to the same organization. In that case, the user is often considered to have implicitly consented to the use of the information in question. Consent is more commonly involved when the Client is a Third Party.
```

[Dex](https://github.com/dexidp/dex) has configuration options both for upstream providers (promptType) and for itself as a provider (SkipApprovalScreen).

```
    # For offline_access, the prompt parameter is set by default to "prompt=consent". 
    # However this is not supported by all OIDC providers, some of them support different
    # value for prompt, like "prompt=login" or "prompt=none"
    # promptType: consent
 ```
 
 ```
 	// If enabled, the server won't prompt the user to approve authorization requests.
	// Logging in implies approval.
	SkipApprovalScreen bool
```

I would second the ability to add this for internal apps where consent isn't needed for the applications/clients authenticating.

**Comment by james-d-elliott** [comment]
Hi @alphabet5. Thanks for the links. I find it rather reassuring that the linked Dex example is regarding prompt types as a relying party which I already described above. I've noticed this is practically universal. If the relying party is implementing prompt types correctly when we properly implement prompt handling as described above it will operate like this. Other than the fact you can seemingly disable it for all clients (there is no individual client option).

You can see the dex clients configuration (OpenID Connect Provider) here: https://github.com/dexidp/dex/blob/master/api/api.pb.go#L24-L36

You can see the dex clients configuration (OpenID Connect Relying Party) here: https://github.com/dexidp/dex/blob/master/connector/oidc/oidc.go#L62

As you can see when dex acts as a relying party it asks the provider to provide a specific prompt type, it's not the provider configuring this. 

Regarding the global skipApprovalScreen option, this is only mentioned in the development docs as a means to make testing easier. I don't see any mention outside of this. Can you?

**Comment by alphabet5** [comment]
Thanks, and well put.

As an administrator I want to pre-configure consent for internal applications, mostly to prevent user questions (I don't want [Company] web app to have my [Company] AD email!) , and streamline their interaction with the app. Similar to how [Azure AD allows](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent) an admin to grant privileges for an entire tenant, or [Google allows](https://support.google.com/cloud/answer/9110914?hl=en#zippy=%2Chow-can-i-mark-my-app-as-internal-only-so-it-doesnt-require-verification) configuring an oidc client as internal-only. 

With both Google and Azure AD the OpenID clients are restricted based on the 'backends'. (Azure tenant, or workspace organization) rather than domain name. I'm not sure if that would be feasible with Authelia rather than basing it off of the redirect domain.

If users are providing consent, even if it's only the first time it's used, it's not really pre-configuring from an administrators perspective. It's definitely not the end of the world, but it would be nice to have.

Digging further into dex it does look like SkipApprovalScreen is only mentioned in the testing docs, and seems to disable it for all clients. Definitely not what I was looking for. 

I've definitely learned a lot from all your comments. Keep up the great work!

**Comment by james-d-elliott** [comment]
@all-contributors please add @Beanow for security

**Comment by james-d-elliott** [comment]
@all-contributors please add @alphabet5 for ideas

**Comment by james-d-elliott** [comment]
@all-contributors please add @rjmidau for ideas

**Comment by james-d-elliott** [comment]
See https://github.com/authelia/authelia/pull/4080 and the [blog](https://www.authelia.com/blog/4.37-pre-release-notes/).
