### ISSUE TITLE
Improper redirection when ?rd= is passed to the auth endpoint

### ISSUE THREAD

**Issue by qub1750ul** [authelia/authelia#2602]
### Description

Just updated my Authelia container from v4.30.0 to v4.32.2
Now when an unauthenticated user requests a protected resource, it is automatically redirected to the domain root without having
the possibility to authenticate.

Authenticated user requests are forwarded correctly.
Manual requests to the auth endpoint also work correctly.
I've identified the cause to be linked to the presence of `?rd=` query parameter in the initial redirection URL, when stripped the auth flow works as expected.

### Expected Behaviour

When an unauthenticated user requests a protected resource, Authelia triggers an HTTP 302 Redirection to the auth endpoint and then waits until further user action. 

### Reproduction Steps

Assuming example.com as the target domain

1. Open a clean browser session.
2. Navigate to a protected endpoint ( e.g. https://example.com/private )
3. Observe an HTTP 302 Redirection to https://example.com/auth?rd=https%3A%2F%2Fexample.com
4. Observe an immediate HTTP 301 Redirection to https://example.com/?rd=https%3A%2F%2Fexample.com

### Additional Information

Using Traefik v2.5 with ForwardAuth middleware on all protected routes, with full header forwarding to Authelia.
Authelia auth endpoint is reachable at https://example.com/auth

**Comment by qub1750ul** [comment]
Testing on rollback i noticed a detail in v4.30.0.
The first redirection is to `/auth/?rd=` not `/auth?rd=`
Notice the missing backslash.
Also if i manually request the second URL, it gets autocorrected to the first.

**Comment by james-d-elliott** [comment]
This is highly likely to be a configuration issue. Please provide the traefik configs for your middleware and the authelia route.  You can replace the domain as you have done with example.com.

**Comment by james-d-elliott** [comment]
Actually it would also be really good to get the server section of your config too, since that affects this.

**Comment by nightah** [comment]
This is likely due to #2272 and the fact that Authelia now accepts requests on both `/` and whatever path you have configured like `/auth` in your case.

What's likely is that your Authelia middleware for Traefik likely doesn't include the path, whereas before this would work because Authelia only accepted requests on the path.

```
- traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/auth/api/verify?rd=https://auth.example.com/auth/
```

The above is a working example of a middleware which includes the path correctly configured.

**Comment by qub1750ul** [comment]
> This is likely due to #2272 and the fact that Authelia now accepts requests on both / and whatever path you have configured like /auth in your case.

Indeed.
Actually my Authelia middleware is configured almost exactly like that, except for that backslash at the end.
In v4.32.2 that turns out to be important because, as i just verified, Authelia strips from the URL whatever parameter it doesn't like.
I assume `/auth?rd=` is a corner case.

However, adding a final backslash solves the issue.
```
- 'traefik.http.middlewares.authelia.forwardauth.address=https://example.com/auth/api/verify?rd=https://example.com/auth/'
```

**Comment by nightah** [comment]
Glad you got it sorted!
