### ISSUE TITLE
Unable to log into Authelia Portal

### ISSUE THREAD

**Issue by millsy2000** [authelia/authelia#2610]
Hi,

I'm having an issue with my Authelia deployment in that I am unable to log into the portal to register a device for a user.
On version v4.32.2 with NGINX. I can see the authentication attempt is successful however NGINX redirects me back to the login prompt.

Below is the code for NGINX and Authelia.

Any help appreciated!

Authelia Config

host: 0.0.0.0
port: 9091 
log:
  level: debug
  format: text
  file_path: /config/authelia.log
  keep_stdout: false
jwt_secret: REMOVED
default_redirection_url: https://millsyauth.theworkpc.com/
totp:
  issuer: authelia.com
  period: 30
  skew: 1

duo_api:     
  hostname: api-da6508f4.duosecurity.com
  integration_key: REMOVED
  secret_key: REMOVED

authentication_backend:
  disable_reset_password: false
  file:
    path: /config/users_database.yml # Make sure this file exists
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain:
        - "millsyauth.theworkpc.com"
      policy: bypass
      networks:
         - 0.0.0.0/0
    - domain: # Proxies needing 2 factor below
        - "millsyfrontend.theworkpc.com"
      policy: two_factor
      networks:
         - 0.0.0.0/0

session:
  name: authelia_session

  secret: REMOVED
  expiration: 3600 # 1 hour
  inactivity: 7200 # 2 hours
  domain: theworkpc.com # Needs to be your root domain

  redis:
    host: authelia_redis_1
    port: 6379

    #password: auth

regulation:
  max_retries: 5
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
 
  filesystem:
    filename: /config/notification.txt
  find_time: 2m
  ban_time: 10m

theme: dark   # options: dark, light

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

NGINX Config

server {
    server_name millsyauth.theworkpc.com;
    listen 80;
    return 301 https://$server_name$request_uri;
}

server {
    server_name millsyauth.theworkpc.com;
    listen 443;

    ssl_certificate           /etc/letsencrypt/live/millsyauth.theworkpc.com/cert.pem;
    ssl_certificate_key       /etc/letsencrypt/live/millsyauth.theworkpc.com/privkey.pem;

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    location / {
        set $upstream_authelia http://127.0.0.1:9091;
        proxy_pass $upstream_authelia;

        client_body_buffer_size 128k;

        #Timeout if the real server is dead
        proxy_next_upstream error timeout invalid_header http_500 http_502     http_503;

        # Advanced Proxy Config
        send_timeout 5m;
        proxy_read_timeout 360;
        proxy_send_timeout 360;
        proxy_connect_timeout 360;

        # Basic Proxy Config
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Uri $request_uri;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_redirect  http://  $scheme://;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_cache_bypass $cookie_session;
        proxy_no_cache $cookie_session;
        proxy_buffers 64 256k;

        # If behind reverse proxy, forwards the correct IP
        set_real_ip_from 10.0.0.0/8;
        set_real_ip_from 172.0.0.0/8;
        set_real_ip_from 192.168.0.0/16;
        set_real_ip_from fc00::/7;
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;
    }
}

**Comment by nightah** [comment]
Can you please provide the Authelia logs when you are simulating the scenario?

Do you have any addons that are preventing cookies from being set?

**Comment by millsy2000** [comment]
See below logs 
Nothing that I am aware of that would stop cookies, have tried on multiple devices.

``
time="2021-11-24T15:24:24+11:00" level=trace msg="Replied (status=401)" method=GET path=/api/verify remote_ip=165.225.232.86
time="2021-11-24T15:24:24+11:00" level=trace msg="Request hit" method=GET path=/ remote_ip=203.6.185.18
time="2021-11-24T15:24:24+11:00" level=trace msg="Replied (status=200)" method=GET path=/ remote_ip=203.6.185.18
time="2021-11-24T15:24:24+11:00" level=trace msg="Request hit" method=GET path=/static/js/index.829172be.js remote_ip=203.6.185.18
time="2021-11-24T15:24:24+11:00" level=trace msg="Replied (status=200)" method=GET path=/static/js/index.829172be.js remote_ip=203.6.185.18
time="2021-11-24T15:24:24+11:00" level=trace msg="Request hit" method=GET path=/static/css/index.393eb37d.css remote_ip=203.6.185.18
time="2021-11-24T15:24:24+11:00" level=trace msg="Replied (status=200)" method=GET path=/static/css/index.393eb37d.css remote_ip=203.6.185.18
time="2021-11-24T15:24:24+11:00" level=trace msg="Request hit" method=GET path=/static/js/vendor.d0bc79df.js remote_ip=203.6.185.18
time="2021-11-24T15:24:24+11:00" level=trace msg="Replied (status=200)" method=GET path=/static/js/vendor.d0bc79df.js remote_ip=203.6.185.18
time="2021-11-24T15:24:25+11:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip=203.6.185.18
time="2021-11-24T15:24:25+11:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=203.6.185.18
time="2021-11-24T15:24:25+11:00" level=trace msg="Request hit" method=GET path=/manifest.json remote_ip=203.6.185.18
time="2021-11-24T15:24:25+11:00" level=trace msg="Replied (status=200)" method=GET path=/manifest.json remote_ip=203.6.185.18
time="2021-11-24T15:24:34+11:00" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:24:34+11:00" level=debug msg="Mark authentication attempt made by user sean" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:24:34+11:00" level=debug msg="Credentials validation of user sean is ok" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:24:34+11:00" level=trace msg="Details for user sean => groups: [admins dev], emails [millsy2000@gmail.com]" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:24:34+11:00" level=debug msg="Check authorization of subject username=sean groups=admins,dev ip=203.6.185.18 and object https://millsyfrontend.freeddns.org/guacamole/ (method )."
time="2021-11-24T15:24:34+11:00" level=trace msg="ACL MISS Position 1 for subject username=sean groups=admins,dev ip=203.6.185.18 and object https://millsyfrontend.freeddns.org/guacamole/ (Method )"
time="2021-11-24T15:24:34+11:00" level=trace msg="ACL HIT Position 2 for subject username=sean groups=admins,dev ip=203.6.185.18 and object https://millsyfrontend.freeddns.org/guacamole/ (Method )"
time="2021-11-24T15:24:34+11:00" level=debug msg="Required level for the URL https://millsyfrontend.freeddns.org/guacamole/ is 2" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:24:34+11:00" level=warning msg="https://millsyfrontend.freeddns.org/guacamole/ requires 2FA, cannot be redirected yet" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:24:34+11:00" level=trace msg="Attempt successful: true, exec duration: 163, avg execution duration: 738, random delay ms: 0, total delay ms: 738, actual delay ms: 575" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:24:35+11:00" level=trace msg="Replied (status=200)" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:24:35+11:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip=203.6.185.18
time="2021-11-24T15:24:35+11:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=203.6.185.18


time="2021-11-24T15:24:35+11:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=203.6.185.18
time="2021-11-24T15:25:42+11:00" level=trace msg="Request hit" method=GET path=/ remote_ip=203.6.185.18
time="2021-11-24T15:25:42+11:00" level=trace msg="Replied (status=200)" method=GET path=/ remote_ip=203.6.185.18
time="2021-11-24T15:25:42+11:00" level=trace msg="Request hit" method=GET path=/static/js/vendor.d0bc79df.js remote_ip=203.6.185.18
time="2021-11-24T15:25:42+11:00" level=trace msg="Replied (status=200)" method=GET path=/static/js/vendor.d0bc79df.js remote_ip=203.6.185.18
time="2021-11-24T15:25:42+11:00" level=trace msg="Request hit" method=GET path=/static/js/index.829172be.js remote_ip=203.6.185.18
time="2021-11-24T15:25:42+11:00" level=trace msg="Replied (status=200)" method=GET path=/static/js/index.829172be.js remote_ip=203.6.185.18
time="2021-11-24T15:25:42+11:00" level=trace msg="Request hit" method=GET path=/static/css/index.393eb37d.css remote_ip=203.6.185.18
time="2021-11-24T15:25:42+11:00" level=trace msg="Replied (status=200)" method=GET path=/static/css/index.393eb37d.css remote_ip=203.6.185.18
time="2021-11-24T15:25:42+11:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip=203.6.185.18
time="2021-11-24T15:25:42+11:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=203.6.185.18
time="2021-11-24T15:25:42+11:00" level=trace msg="Request hit" method=GET path=/manifest.json remote_ip=203.6.185.18
time="2021-11-24T15:25:42+11:00" level=trace msg="Replied (status=200)" method=GET path=/manifest.json remote_ip=203.6.185.18
time="2021-11-24T15:25:47+11:00" level=trace msg="Request hit" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:25:47+11:00" level=debug msg="Mark authentication attempt made by user sean" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:25:47+11:00" level=debug msg="Credentials validation of user sean is ok" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:25:47+11:00" level=trace msg="Details for user sean => groups: [admins dev], emails [millsy2000@gmail.com]" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:25:47+11:00" level=trace msg="Attempt successful: true, exec duration: 82, avg execution duration: 647, random delay ms: 35, total delay ms: 682, actual delay ms: 600" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:25:47+11:00" level=trace msg="Replied (status=200)" method=POST path=/api/firstfactor remote_ip=203.6.185.18
time="2021-11-24T15:25:47+11:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip=203.6.185.18
time="2021-11-24T15:25:47+11:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=203.6.185.18

**Comment by nightah** [comment]
I can't see anything in the logs that would indicate the behaviour you're seeing.

Can you perhaps make a gif/video of what occurs?

Have you attempted a browser with all your plugins turned off, like in Private browsing or Incognito mode?

**Comment by clems4ever** [comment]
@millsy2000 , please reopen this issue with some kind of gif/video if you're still facing the issue.
