### ISSUE TITLE
Chrome - U2F API invalid after 02.2022, use Web Authentication API

### ISSUE THREAD

**Issue by Tropaion** [authelia/authelia#2615]
I don't know if its already known or in work but I think I should write it here.
Google Chrome says that the currently used U2F Api is invalid starting 02.2022.
It is neccessary to switch to the Web Authentication API.

**Comment by james-d-elliott** [comment]
We're working on *adding* the Web Authentication API.

Chrome is the only browser deprecating support at the moment. It was deprecated since version 95, will be disabled by default in February 2022 (version 98), and finally removed in March 2022 (version 100).

**Comment by james-d-elliott** [comment]
See #241

**Comment by james-d-elliott** [comment]
@Tropaion this feature is in heavy development, take a look at #241 if interested.
