### ISSUE TITLE
The config file name in documentation is not consistent with the Dockerfile

### ISSUE THREAD

**Issue by kaysond** [authelia/authelia#2625]
https://github.com/authelia/authelia/blob/a05b03a3d82a59b563fb76530f774a88cc07bc2d/Dockerfile#L31 uses `configuration.yml`, but 

https://github.com/authelia/authelia/blob/a05b03a3d82a59b563fb76530f774a88cc07bc2d/docs/configuration/index.md?plain=1#L30-L31

and 

https://github.com/authelia/authelia/blob/a05b03a3d82a59b563fb76530f774a88cc07bc2d/docs/configuration/index.md?plain=1#L35 

and https://github.com/authelia/authelia/blob/master/config.template.yml

use `config.yml`

This is a small documentation issue, but I named my file `config.yml` after the documentation, and it took a while to realize why my configuration was never changing despite updating the file!

**Comment by nightah** [comment]
`config.template.yml` is actually embedded into the Go binary and if a user points an Authelia instance to a non-existent configuration file it will generate the said file based on the template at the location the user has specified.

So for example, if you run `./authelia --config /config/config.yml` and it does not exist, it will be generated as such at said location.

The first example you have linked is intending to show how you could potentially split your configuration and also run Authelia with a split configuration.

**Comment by kaysond** [comment]
That all makes sense. Nonetheless, it was definitely a point of confusion for me!

I think you probably don't want to change the Dockerfile, since that would be a breaking change, but I'd suggest changing the other ones to also be `configuration.yml` (specifically, the first one in the docs example)

**Comment by nightah** [comment]
Would be happy to accept a PR if you think it'd help clarify the situation.

**Comment by kaysond** [comment]
> Would be happy to accept a PR if you think it'd help clarify the situation.

Thanks! Submitted #2626

**Comment by nightah** [comment]
Closed by #2626.
