### ISSUE TITLE
Missing icons on Synology DSM webpage if Authelia is enabled

### ISSUE THREAD

**Issue by GeoCookie** [authelia/authelia#2638]
### Description

Some icons are missing from Synology DSM webpage when accessed through Swag with Authelia enabled.
![image](https://user-images.githubusercontent.com/43962716/143688413-675eac81-8bbc-4c92-8532-78bc1582d981.png)

### Expected Behaviour

The icons should be displayed correctly. This is the case if I disable Authelia.
![image](https://user-images.githubusercontent.com/43962716/143688434-53f616c9-56cf-452a-a08b-43d818c33626.png)

### Additional Information

I use Swag as reverse proxy.

Without Authelia, I can reach an icon URL
![image](https://user-images.githubusercontent.com/43962716/143689289-4dfdfc2b-96ca-45ba-8318-fd707f12e17c.png)

With Authelia, if I try to reach the same URL, I got a 2FA prompt and I got redirected
![image](https://user-images.githubusercontent.com/43962716/143688528-e2ca4b34-04b5-474e-bfd0-642a5f851870.png)

The string "{0}" seems to be a problem because if I remove it from the URL, I can reach it correctly.

**Comment by GeoCookie** [comment]
I did not find anything in the logs but found the cause of this behavior.
On the file "authelia-server.conf", there is this block
`if ($request_uri ~ [^a-zA-Z0-9_+-=\!@$%&*?~.:#'\;\(\)\[\]]) {
return 401;
}`
If I add `\{\}` in the if condition, everything is working fine. 
It seems to be related to this CVE : [https://github.com/authelia/authelia/security/advisories/GHSA-68wm-pfjf-wqp6](url)

I'll try to see if I can add an exception for Synology only and if it's not too dangerous. I really don't want to add security holes for some missing icons!

Thank you for your help

**Comment by james-d-elliott** [comment]
Those don't fall into the security issue, itself just they are not *technically* valid for URL's. I can make a PR to fix that upstream.

**Comment by recklezz** [comment]
I'm seeing the same issue.  Any updates on this?

**Comment by james-d-elliott** [comment]
Closed by https://github.com/linuxserver/docker-swag/pull/233. Users can make the modification themselves tot he authelia-server.conf or wait to see the decision LSIO makes in that PR.

**Comment by GeoCookie** [comment]
Thank you James
