### ISSUE TITLE
Configuration: Consolidation

### ISSUE THREAD

**Issue by james-d-elliott** [authelia/authelia#2645]
Various things can be improved with the configuration as part of a consolidation effort post implementing koanf. This is a list:

- [x] Implement mapstructure hooks for additional types to avoid double handling configuration.
- [x] Include ENV in configuration checking.
- [ ] Attempt to implement an ACL / OIDC client custom parser.
- [x] Implement codegen for valid keys to prevent mistakes.

**Comment by clems4ever** [comment]
I understand the ACL parser but what do you mean by OIDC client custom parser?

**Comment by james-d-elliott** [comment]
It's because lists of structs can't easily be represented in ENV in a way that works well with mapstructure. Both have the same issue. I doubt we'll easily be able to solve it though so thinking that is the least important.
