### ISSUE TITLE
Small adjustment needed for Fail2ban filter documentation

### ISSUE THREAD

**Issue by AllowPing** [authelia/authelia#2649]
The Fail2ban filter for Authelia does not work for me when using this doc:
https://www.authelia.com/docs/security/measures.html#additional-security

Simply changing the filter from including this
`failregex = ^.*Error while checking password for.*remote_ip=<HOST> stack.*
            ^.*Credentials are wrong for user .*remote_ip=<HOST> stack.*
            ^.*Wrong passcode during TOTP validation.*remote_ip=<HOST> stack.*`
to including this resolved the issue for me
`failregex = ^.*error while checking password for.*remote_ip=<HOST> stack.*
            ^.*credentials are wrong for user .*remote_ip=<HOST> stack.*
            ^.*wrong passcode during TOTP validation.*remote_ip=<HOST> stack.*`

Also, I am getting these warnings, though it doesn't appear to affect Fail2ban's functionality
`2021-11-30 19:17:42,352 fail2ban.filter         [474]: WARNING [authelia] Simulate NOW in operation since found time has too large deviation None ~ 1638325062.3521326 +/- 60

2021-11-30 19:17:42,352 fail2ban.filter         [474]: WARNING [authelia] Please check jail has possibly a timezone issue. Line with odd timestamp: time="2021-11-30T19:17:41-07:00" level=debug msg="Mark authentication attempt mad
e by user sdfs" method=POST path=/api/firstfactor remote_ip=**redacted**`

If it matters for the warning, docker-compose.yml has environment variables from /etc/environment
`    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}`

OS/app info:
Ubuntu 18.04.6 LTS

image: authelia/authelia:4.32.2

Fail2ban via docker container
image: ghcr.io/linuxserver/swag
swag version 1.21.0-ls100

docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

Apologies for any formatting errors and please let me know if I should dig a bit further. Thanks for such a great app.

**Comment by nightah** [comment]
The fail2ban filters are going to change entirely as the messages have been homogenized in the upcoming 4.33.0 release.

You can see #2661 for the updated filters, but I would recommend waiting until 4.33.0 is release (imminently) and then updating your filters along with your version of Authelia.

**Comment by AllowPing** [comment]
That's great news, thank you!
