### ISSUE TITLE
Documentation: TOTP Support Matrix

### ISSUE THREAD

**Issue by james-d-elliott** [authelia/authelia#2650]
With the upcoming release of 4.33.0 we are adding support for various additional TOTP options such as digits/input length and algorithm. We are also looking for some help regarding figuring out which devices support what to help out the community.

As such for anyone who has the time, we would like to collect some works/doesn't work information from the community. It's vitally important if you wish to contribute to this that you carefully read these instructions, as it's possible for the information you have to be incorrect if you do not.

1. Update to 4.33.0 (once released).
2. Change either the `digits` option OR the `algorithm` option; do not change both. Make sure the other one is set to the default of 6 for digits or sha1 for algorithm.
3. Restart Authelia.
4. Register a new One Time Password; it _**must**_ be new, keys are validated based on what values were set when registered.
5. Logout of Authelia.
6. Login to Authelia and perform 2FA with the TOTP key you generated.
7. Report your findings.

We will setup a google form in order to collate results. We _**will not**_ be collecting any personal information. The name fields will relate to the section, for example in the application section the name refers to the application name.

**Comment by james-d-elliott** [comment]
1. Android (12)
2. Bitwarden (2.14.2)
3. digits: 8
4. success

1. Android (12)
2. Bitwarden (2.14.2)
3. algorithm: sha512
4. success

**Comment by james-d-elliott** [comment]
1. Android (12)
2. Bitwarden (2.14.2)
3. algorithm: sha512
4. success

**Comment by aureq** [comment]
Hi James,

I would like to report that `Yubico Authenticator v5.1.0` (Desktop app) works correctly with 8 digits. I was successfully able to enroll a TOTP device (a yubikey 4 NFC). The mobile version also works fine was also able to read the Yubikey and display the 8 digits.

I would also like to report that `Authenticator Plus` ([ref](https://play.google.com/store/apps/details?id=com.mufri.authenticatorplus)) does NOT support 8 digits. Only the last 6 digits are displayed.

**Comment by TheJeremyP** [comment]
Both 1Password, and [Raivo](https://github.com/raivo-otp/) correctly generate 6 digit, sha256 codes.

**Comment by pearlythepirate** [comment]
[Authy](https://play.google.com/store/apps/details?id=com.authy.authy) works for sha1 and 8 digits. It does NOT work with sha256 and 6 digits.

**Comment by NiNiyas** [comment]
https://github.com/beemdevelopment/Aegis works for sha512, sha1 and 6, 8 digits.

**Comment by james-d-elliott** [comment]
See here and check for any mistakes: https://www.authelia.com/reference/integrations/time-based-one-time-password-apps/
