### ISSUE TITLE
Default ingress-nginx rules does not work

### ISSUE THREAD

**Issue by rlex** [authelia/authelia#2654]
### Description

When installing from helm chart, authelia offers:

```
nginx.ingress.kubernetes.io/auth-url: http://authelia.authelia.svc.cluster.local/api/verify
nginx.ingress.kubernetes.io/auth-signin: https://authelia.domain.name
nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
nginx.ingress.kubernetes.io/auth-snippet: |
	proxy_set_header X-Forwarded-Method $request_method;
nginx.ingress.kubernetes.io/configuration-snippet: |
	proxy_set_header X-Forwarded-Method $request_method;You can also direct your ingress to use the following path for forward auth: http://authelia.authelia.authelia.svc.cluster.local/api/verify?rd=https://authelia.domain.name/.
```

However, this won't work as authelia reports:

```
time="2021-12-01T19:41:29Z" level=error msg="Scheme of target URL http://service.domain.name must be secure since cookies are only transported over a secure connection for security reasons" method=GET path=/api/verify remote_ip=10.0.2.155 stack="github.com/authelia/authelia/v4/internal/handlers/handler_verify.go:459     VerifyGet.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:51 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.3/router.go:414                             (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14      LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.30.0/server.go:2266                          (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.30.0/workerpool.go:223                       (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.30.0/workerpool.go:195                       (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581                                                    goexit"
```

What works is adding 

```
?rd=https://$host$request_uri
``` 
to api/verify endpoint. 
Apparently ingress-nginx redirects to http:// for some reason (because initial auth was called with in-kubernetes http://authelia.authelia.svc.cluster.local/api/verify url?

### Expected Behaviour

Redirect should work (or default rules need to be changed?)

### Reproduction Steps

Deploy ingress-nginx
Deploy authelia
Deploy anything with ingress
Annotate ingress with offered variables from helm chart
Observe the error

### Additional Information

Not quite sure if this is related to authelia or helm-chart. Logic behind annotations looks fine, but it's internal authelia error that causes redirect error.

**Comment by james-d-elliott** [comment]
This was tested with ingress-nginx about a year ago and it was working. The log message indicates:

- ingress-nginx is not setting the X-Original-URL/X-Forwarded-Scheme headers correctly.
- the domain you're navigating to has the scheme of `http` not `https`. 

You can attempt the following auth-snippet:

```yaml
nginx.ingress.kubernetes.io/auth-snippet: |
	proxy_set_header X-Forwarded-Method $request_method;
	proxy_set_header X-Forwarded-Scheme $scheme;
```

There is also this *hack* that should only be used for testing. Keeping in mind we set the secure attribute of cookies to true, so regardless of this setting if the browser see's the `http` scheme it will not transmit the session cookie:

```yaml
nginx.ingress.kubernetes.io/auth-snippet: |
	proxy_set_header X-Forwarded-Method $request_method;
	proxy_set_header X-Forwarded-Scheme https;
```

**Comment by rlex** [comment]
>the domain you're navigating to (not the Authelia URL, the URL of the service) has the scheme of http not https.

Might be before initial redirect? Always pointed to https before switch from oauth2-proxy to authelia.

I fixed it with setting 

```
force-ssl-redirect: "true"
```

in ingress-nginx config, since all my ingresses are https anyway.

I will try testing your solution a bit later, thanks!

**Comment by james-d-elliott** [comment]
Could very well be. I would attempt to navigate to https directly and see. If that is the case we can investigate if ingress-nginx has an option to force the redirect to occur before auth request, but I have a feeling that is not possible.

**Comment by clems4ever** [comment]
@rlex , did you manage to solve your issue eventually?

**Comment by rlex** [comment]
@clems4ever yes, there is multiple ways to achieve it
```
force-ssl-redirect: "true"
``` 
in ingress-nginx configmap worked.

Another way is adding protocol to rd, works too

i _think_ that solution proposed by James works too, but i forgot to post here when i was checking. Probably need to check again...

Way i'm doing it now is 

```
          global-auth-url: "http://authelia.authelia.svc.cluster.local/api/verify"
          global-auth-signin: "https://authelia_public_facing_ui/"
```
in configmap - this locks down all resources and you can exclude some from auth with ingress annotation.

**Comment by james-d-elliott** [comment]
Yeah what you posted as the solution is the global alternative to what I posted I believe. Advantage of yours is it applies to all ingresses, advantage of mine is it's per ingress so you can pick and choose what needs it (though you can do this with yours via ACL's). I should add this to the helm output.

**Comment by james-d-elliott** [comment]
If you still have issues feel free to ping us and reopen the issue (I think users can do that).
