### ISSUE TITLE
Cannot scan TOTP QR code in 4.33

### ISSUE THREAD

**Issue by ptoulouse** [authelia/authelia#2672]
### Description

I upgraded to 4.33 and set the storage:encryption_key, then set two factors auth on some of my subdomains. When accessing these domains, I get prompted to enter my username/password, then get send to the register device page. I click the Register Device link and receive an e-mail. Clicking on register in the e-mail bring me back to the (same) browser where a blurred QR code is displayed.

Log shows: "authelia token is not in db, it might have already been used".

When rolling back to 4.32, I can register the device.

### Expected Behaviour

I expect to be able to register for TOTP as I was able to prior to 4.33.

### Reproduction Steps

1. Start from scratch with no existing db.sqlite3 and no authelia docker image.
2. Start authelia/authelia:latest with two_factors set for some subdomains.
3. Access subdomain and follow through the TOTP registration process.
4. You will get a blurred QR code with error message "Authelia failed to register device ..."
5. Log will show "authelia token is not in db, it might have already been used".
6. Stop authelia, remove db, docker system prune -a --volumes.
7. Remove storage:encryption key and start authelia/authelia:4.32
8. Access subdomain and follow through the TOTP registration process.
9. Registration works.
10. Once registered in 4.32, you can upgrade to 4.33 and you will be able to access the two factors protected sites using the TOTP code.

### Additional Information

_N/A_

**Comment by james-d-elliott** [comment]
Could you provide logs? We actually test exactly this functionality in integration testing (i.e. basically a bot controlling the browser). So it seems very strange.

**Comment by james-d-elliott** [comment]
Also can you run the following on the database? You'll need to install the sqlite3 package.

`sqlite3 db.sqlite3 "SELECT * FROM identity_verification;" ".exit"`

**Comment by martabal** [comment]
Same issue. Here are my log
[log.txt](https://github.com/authelia/authelia/files/7652918/log.txt)
s

**Comment by james-d-elliott** [comment]
I manually tested this with my dev site using sqlite. I had no issues. Can you install sqlite3 and run this on the database?

`sqlite3 /path/to/db.sqlite3 "SELECT * FROM identity_verification;" ".exit"`

If you want to do it in the container you can do so like this:

```bash
docker exec -it authelia /bin/sh
apk add --no-cache sqlite
sqlite3 /config/db.sqlite3 "SELECT * FROM identity_verification;" ".exit"
```

**Comment by martabal** [comment]
With my previous config.yml, i was using only mysql as storage provider and the local storage with sqlite3 was disabled. I just uncommented  local:  path: /config/db.sqlite3 and now it works perfectly. Thank you for your work!

**Comment by james-d-elliott** [comment]
> With my previous config.yml, i was using only mysql as storage provider and the local storage with sqlite3 was disabled. I just uncommented local: path: /config/db.sqlite3 and now it works perfectly. Thank you for your work!

Oh, thought you were using sqlite3 too. It should work regardless of database, if you want me to help fix MySQL I can do that too.

**Comment by james-d-elliott** [comment]
@ptoulouse are you still having this issue? @martabal I tested with MySQL again now and it works as expected. Did you ever upgrade to the master branch? Also if you want to get it working I am willing to help either of you in our chat channels if you prefer.

[Discord](https://discord.authelia.com/) or [Matrix](https://matrix.to/#/#support:authelia.com).

**Comment by james-d-elliott** [comment]
I figured out the cause and a fix. You're welcome to try `authelia/authelia:fix-storage-idv`
