### ISSUE TITLE
Updating to latest docker image just broke my installation

### ISSUE THREAD

**Issue by tugdualenligne** [authelia/authelia#2685]
## Bug Report
Apparently this is linked to the 'encryption_key' newly used to protect storage (sqlite in my case), however, adding that key in the storage section of the configuration.yml does not resolve the case (I understand two spaces must be inserted before the 'encryption_key' field, but tried without, to no avail). A little painful that this option is made mandatory as it breaks the service, a log entry would have been better to alert on this subject

### Description

Authelia does not start when launched through a docker compose file (using Portainer in my case), and it doesn't join my usual network, but I suspect it is because it can't initiate

### Expected Behaviour

N/A

### Reproduction Steps

N/A

### Additional Information

N/A

**Comment by james-d-elliott** [comment]
Hey sorry about that. For most users it doesn't break, just adding it gets them up and running. I'd suggest providing logs and/or jumping on [Discord](https://discord.authelia.com)/[Matrix](https://matrix.to/#/#community:authelia.com).

You can also get yourself up and running almost instantly by renaming the sqlite3 db as a backup and restarting Authelia.

**Comment by shadow7412** [comment]
I've reverted to the `authelia/authelia:4.32` image for now. The errors I get are about the configuration file, telling me a bunch of options have apparently been renamed.

Is there a migration guide somewhere for the configuration file?

**Comment by james-d-elliott** [comment]
That would be the options that have been deprecated and been throwing warnings since the release back in August.

Read that: https://www.authelia.com/docs/configuration/migration.html#format
Then this: https://www.authelia.com/docs/configuration/migration.html#4300

**Comment by shadow7412** [comment]
Nice. Maybe it's worth putting a link to the migration docs in the FAQ? For someone less familiar with them, they're pretty buried. I'll give it a whirl tonight though, thanks.

**Comment by james-d-elliott** [comment]
Thanks for the suggestion!

**Comment by james-d-elliott** [comment]
@tugdualenligne did you see the responses?

**Comment by shadow7412** [comment]
All working now. I had to move the server and log config into their objects, and set an encryption key for the database.

Thanks for those links, @james-d-elliott. And thanks for bringing SSO to my humble home network :)

**Comment by james-d-elliott** [comment]
No worries! Glad it's fixed!

**Comment by shadow7412** [comment]
@james-d-elliott I've added a PR for updating the faq like I suggested earlier, in case that helps.

**Comment by tugdualenligne** [comment]
Hi James, thanks for your messages, and thanks for this great piece of work. I just relaunch the docker compose and get messages like if my config file was not seen, the first of which mentioning the encryption key. My error messages are as follow:
time="2021-12-06T12:27:42+01:00" level=error msg="Configuration: failed to load configuration from yaml file(/config/configuration.yml) source: yaml: line 567: did not find expected key",
time="2021-12-06T12:27:42+01:00" level=error msg="Configuration: Provide a JWT secret using \"jwt_secret\" key",
time="2021-12-06T12:27:42+01:00" level=error msg="Configuration: Please provide `ldap` or `file` object in `authentication_backend`",
time="2021-12-06T12:27:42+01:00" level=error msg="Configuration: Default Policy [deny] is invalid, access control rules must be provided or a policy must either be 'one_factor' or 'two_factor'",
time="2021-12-06T12:27:42+01:00" level=error msg="Configuration: Set domain of the session object",
time="2021-12-06T12:27:42+01:00" level=error msg="Configuration: storage: configuration for a 'local', 'mysql' or 'postgres' database must be provided",
time="2021-12-06T12:27:42+01:00" level=error msg="Configuration: storage: 'encryption_key' configuration option must be provided",
time="2021-12-06T12:27:42+01:00" level=error msg="Configuration: A notifier configuration must be provided",
time="2021-12-06T12:27:42+01:00" level=fatal msg="Can't continue due to the errors loading the configuration"

**Comment by james-d-elliott** [comment]
A couple people have had this issue, seems like a malformed yaml file. You can either hop on chat and I can help you fix it, or if you download VSCodium and add the YAML extension by RedHat via the app marketplace it should show you where it is broken.

**Comment by tugdualenligne** [comment]
Mmmh, sorry, tried to it myself installing VSCodium and the extension, but no idea how to proceed next.
When you on chat you mean Discord (which I looked yesterday and I renamed the DB to .bak following that). Will try ASAP
