### ISSUE TITLE
Two servers, each has its own authelia somehow conflicts

### ISSUE THREAD

**Issue by atropos112** [authelia/authelia#2689]
### Description
I have two devices each having some docker images with web frontends, each having its own traefik and authelia instance. In principle they are not connected at all as such I expect there to be no conflict. However if I log in via authelia on one device (and press Remember me) it logs me out of the other one, this is clearly undesirable. This I am certain happens because the browser overwrites first authelias cookies with the other ones. 

### Expected Behaviour
Be able to use two or more authelias without them wiping each others cookies.

### Reproduction Steps
Have two authelias running (ideally on two devices, but you can probably run two authelias on one device for testing purposes) and try logging on one then another.

**Comment by james-d-elliott** [comment]
You just need to change this: https://www.authelia.com/docs/configuration/session/#options

**Comment by atropos112** [comment]
Well then sir, you have kinda shut me up not gonna lie. Thank you !

**Comment by james-d-elliott** [comment]
No worries enjoy!
