### ISSUE TITLE
Using authelia with apps that have their own authentication

### ISSUE THREAD

**Issue by CuddlySheep** [authelia/authelia#2699]
What exactly does the process look like when authelia is used in front of applications with their own authentication?

Of course, I could turn off their authentication mechanism, but then the question is how to ensure app-specific authorization.

Is there perhaps a way for the app to get to the authenticated user (perhaps via a JWT token or similar) so that the app authorization continues to work?

**Comment by james-d-elliott** [comment]
Authelia responds to verify requests with several headers which the proxy can forward to the backend application. The headers of most interest to you are `Remote-User` and `Remote-Groups`. Additionally we have beta support as an OpenID Connect Provider which has claims available that will identify the user.

**Comment by CuddlySheep** [comment]
Thank you so much!
This is the answer I was looking for.

Now I have also found it in the documentation:
https://www.authelia.com/docs/deployment/supported-proxies/#how-can-the-backend-be-aware-of-the-authenticated-users
