### ISSUE TITLE
Create an example with HAProxy

### ISSUE THREAD

**Issue by clems4ever** [authelia/authelia#271]
Authelia is supposed to be able to run with any proxy. We can create an example with HAProxy which is one of the most famous and efficient proxies used in professional environments.

**Comment by SurinameClubcard** [comment]
I was wondering if such an example exists today. I would be very interested to see how HAProxy and Authelia interact.

**Comment by clems4ever** [comment]
Hello @SurinameClubcard , as you can see the ticket is still open and I have no draft yet. I'll let you know when I have something. You can also try on your side. There is no magick in the conf, all features used from nginx are also in HAProxy so it should not be complicated.

**Comment by SurinameClubcard** [comment]
> 
> 
> Hello @SurinameClubcard , as you can see the ticket is still open and I have no draft yet. I'll let you know when I have something. You can also try on your side. There is no magick in the conf, all features used from nginx are also in HAProxy so it should not be complicated.

Sounds great! Let me give it a try. What features of nginx are you referring to? Is there a nginx example?

**Comment by clems4ever** [comment]
Well, I was referring to common features like basic reverse proxy features, setting headers, redirecting but most importantly the question I have is what is the equivalent of http://nginx.org/en/docs/http/ngx_http_auth_request_module.html for HAProxy. I'm not an expert but somebody from the dev team of HAProxy told me that such things was possible.

There is an example of nginx configuration at https://github.com/clems4ever/authelia/blob/master/example/compose/nginx/portal/nginx.conf. It protects several domains of the test environment that can be set up following the documentation.

**Comment by SurinameClubcard** [comment]
> @SurinameClubcard , I was referring to common features like basic reverse proxy features, setting headers, redirecting but most importantly the question I have is what is the equivalent of http://nginx.org/en/docs/http/ngx_http_auth_request_module.html for HAProxy. I'm not an expert but somebody from the dev team of HAProxy told me that such things was possible.

Well, I found this: https://github.com/TimWolla/haproxy-auth-request. Can you confirm that this seems to be compatible? The source code states:

```
	-- 2xx: Allow request.
	if 200 <= c and c < 300 then
		txn:set_var("txn.auth_response_successful", true)
		txn:set_var("txn.auth_response_code", c)
	-- 401 / 403: Do not allow request.
	elseif c == 401 or c == 403 then
		txn:set_var("txn.auth_response_code", c)
	-- Everything else: Do not allow request and log.
	else
		txn:Warning("Invalid status code in auth-request backend '" .. be .. "': " .. c)
		txn:set_var("txn.auth_response_code", c)
	end
```

**Comment by clems4ever** [comment]
Hello @SurinameClubcard , this is exactly the type of contracts that Authelia meets so it is compatible! :)

**Comment by SurinameClubcard** [comment]
> Hello @SurinameClubcard , this is exactly the type of contract that Authelia meets so it is
> absolutely compatible! :)

Great. `haproxy-auth-request` requires haproxy v1.8 so I need to upgrade first from v1.7. I will test this module with authelia and report the results back here when finished.

**Comment by clems4ever** [comment]
Great!

**Comment by SurinameClubcard** [comment]
I migrated our haproxy to v1.8. Will start working on the `auth-request`. On https://github.com/TimWolla/haproxy-auth-request, it is mentioned (at "Known limitations"): **The backend must not be using TLS.** Is Authelia using TLS to access it?

**Comment by clems4ever** [comment]
@SurinameClubcard , great! Let me know about your progress. Regarding your question Authelia does not support TLS yet. It would be interesting to understand why `auth-request` would not work with TLS though.

**Comment by clems4ever** [comment]
@SurinameClubcard , I came up with a concept of suites to implement integration tests. That would be great if you could create one for HAproxy with the Single-Factor and Two-Factor authentication tests. I can help you with that if needed. Let me know about your progress.

**Comment by SurinameClubcard** [comment]
I would be happy to! But first I have to get it working. I have posted my progress so far on Gitter. You might want to take a look because I could use some help understanding a response from Authelia.

**Comment by SurinameClubcard** [comment]
> 
> 
> @SurinameClubcard , great! Let me know about your progress. Regarding your question Authelia does not support TLS yet. It would be interesting to understand why `auth-request` would not work with TLS though.

While researching on `auth-request` I found out it is in fact possible to use a TLS backend (`/api/verify`) with some changes on the `haproxy-auth-request` script from @TimWolla.

**Comment by TimWolla** [comment]
> It would be interesting to understand why `auth-request` would not work with TLS though.

Because it would be a pain to support within the Lua script. It's should be easy enough to do with a dedicated frontend that performs the encryption. Something like this should work (sending traffic through HAProxy instead of directly to Authelia):

```
backend auth_backend
  server auth_backend2 localhost:12345

listen auth_backend2
  listen 12345
  server authelia authelia:80 ssl
```

**Comment by TimWolla** [comment]
I know nothing about Authelia, but I know a bit about HAProxy. To reproduce the `Content-Length` issue in haproxy-auth-request I used this HAProxy configuration (it's missing quite a few important parts such as timeouts, it's the minimally viable thing that worked):

```
global
	lua-load /tmp/authelia/haproxy-auth-request/auth-request.lua

frontend fe_http
	mode http
	bind :8080 ssl crt /scratch/haproxy/ssl/haproxy.pem

	http-request set-var(req.scheme) str(https) if { ssl_fc }
	http-request set-var(req.scheme) str(http) if ! { ssl_fc }
	http-request set-var(req.questionmark) str(?) if { query -m found }

	http-request set-header X-Forwarded-Proto %[var(req.scheme)]
	http-request set-header X-Real-IP %[src]
	http-request set-header X-Original-URI %[path]%[var(req.questionmark)]%[query]
	http-request set-header X-Original-URL https://%[base]%[var(req.questionmark)]%[query]

	http-request lua.auth-request authelia    /api/verify
	http-response set-header Success %[var(txn.auth_response_code)] # this line can be removed, but was helpful for debugging
	use_backend authelia if ! { var(txn.auth_response_successful) -m bool } # this line forces the request to go to the authelia backend. Can be replaced by `http-request redirect` or `http-request deny` or whatnot.

	http-request set-header Host example.com # this line required for example.com to accept my request (I was using one of my own domains that I pointed to localhost)

	use_backend be_http

backend be_http
	mode http
	server example example.com:80

backend authelia
	mode http

	server authelia 172.17.0.2:9091
```

I was able to authenticate as `john` with password `john` and once I did so I was able to access example.com. This configuration needs an ACL that forces the request to go to Authelia to be able to sign-out.

**Comment by clems4ever** [comment]
@TimWolla , great news, I will package that in a suite very soon. Thanks.

**Comment by nightah** [comment]
@TimWolla I attempted to put together this suite yesterday based on the config you provided above and to fit within how the containers are distributed in the integration tests and seem to be having some trouble.

I'm not sure if this is related to haproxy-auth-request or just my haproxy configuration in general, is there any chance you might be able to have a look?
https://github.com/authelia/authelia/blob/35569d2fe91d473417e2a3aedd4d4877ea7f27ba/example/compose/haproxy/haproxy.cfg

Here's a example of what I'm seeing in the HAProxy logs:
```
192.168.240.1:38430 [10/Jan/2020:00:54:08.348] fe_http~ fe_authelia/authelia-frontend 0/0/1/18/20 200 1084 - - ---- 1/1/0/0/0 0/0 "GET /logout HTTP/1.1"
192.168.240.1:38430 [10/Jan/2020:00:54:08.382] fe_http~ fe_authelia/authelia-frontend 0/0/0/12/14 200 6653 - - ---- 3/3/2/2/0 0/0 "GET /static/js/bundle.js HTTP/1.1"
192.168.240.1:38436 [10/Jan/2020:00:54:08.383] fe_http~ fe_authelia/authelia-frontend 0/0/0/18/19 200 30753 - - ---- 3/3/1/1/0 0/0 "GET /static/js/main.chunk.js HTTP/1.1"
192.168.240.1:38434 [10/Jan/2020:00:54:08.382] fe_http~ fe_authelia/authelia-frontend 1/0/0/16/247 200 1118806 - - ---- 3/3/0/0/0 0/0 "GET /static/js/0.chunk.js HTTP/1.1"
192.168.240.1:38434 [10/Jan/2020:00:54:08.948] fe_http~ be_authelia/authelia-backend 0/0/1/0/1 200 145 - - ---- 3/3/0/0/0 0/0 "POST /api/logout HTTP/1.1"
192.168.240.1:38436 [10/Jan/2020:00:54:08.949] fe_http~ be_authelia/authelia-backend 0/0/0/0/0 200 155 - - ---- 3/3/0/0/0 0/0 "GET /api/configuration HTTP/1.1"
192.168.240.1:38436 [10/Jan/2020:00:54:08.966] fe_http~ fe_authelia/authelia-frontend 0/0/0/2/2 200 330 - - ---- 3/3/0/0/0 0/0 "GET /sockjs-node/info?t=1578617648965 HTTP/1.1"
192.168.240.1:38436 [10/Jan/2020:00:54:10.977] fe_http~ be_authelia/authelia-backend 0/0/0/1/1 200 222 - - ---- 4/4/0/0/0 0/0 "GET /api/state HTTP/1.1"
Invalid status code in auth-request backend 'be_authelia': 405
[warning] 009/005411 (6) : Invalid status code in auth-request backend 'be_authelia': 405
192.168.240.1:38462 [10/Jan/2020:00:54:11.239] fe_http~ be_authelia/authelia-backend 1/0/0/1/2 404 172 - - ---- 5/5/0/0/0 0/0 "GET / HTTP/1.1"
192.168.240.1:38456 [10/Jan/2020:00:54:08.981] fe_http~ fe_authelia/authelia-frontend 0/0/0/6/2267 101 301 - - ---- 5/5/0/0/0 0/0 "GET /sockjs-node/175/h0cl1c1z/websocket HTTP/1.1"
192.168.240.1:38436 [10/Jan/2020:00:54:11.262] fe_http~ fe_authelia/authelia-frontend 0/0/0/2/3 200 1084 - - ---- 4/4/0/0/0 0/0 "GET /?rd=https://singlefactor.example.com:8080/secret.html HTTP/1.1"
192.168.240.1:38436 [10/Jan/2020:00:54:11.271] fe_http~ fe_authelia/authelia-frontend 0/0/0/1/1 304 159 - - ---- 4/4/2/2/0 0/0 "GET /static/js/bundle.js HTTP/1.1"
192.168.240.1:38434 [10/Jan/2020:00:54:11.272] fe_http~ fe_authelia/authelia-frontend 1/0/0/9/10 304 161 - - ---- 4/4/1/1/0 0/0 "GET /static/js/0.chunk.js HTTP/1.1"
192.168.240.1:38430 [10/Jan/2020:00:54:11.273] fe_http~ fe_authelia/authelia-frontend 0/0/0/11/11 304 160 - - ---- 4/4/0/0/0 0/0 "GET /static/js/main.chunk.js HTTP/1.1"
192.168.240.1:38430 [10/Jan/2020:00:54:11.463] fe_http~ be_authelia/authelia-backend 1/0/0/0/1 200 222 - - ---- 4/4/0/0/0 0/0 "GET /api/state HTTP/1.1"
192.168.240.1:38434 [10/Jan/2020:00:54:11.464] fe_http~ be_authelia/authelia-backend 0/0/0/0/0 200 155 - - ---- 4/4/0/0/0 0/0 "GET /api/configuration HTTP/1.1"
192.168.240.1:38434 [10/Jan/2020:00:54:11.530] fe_http~ fe_authelia/authelia-frontend 0/0/0/1/1 200 329 - - ---- 4/4/0/0/0 0/0 "GET /sockjs-node/info?t=1578617651529 HTTP/1.1"
192.168.240.1:38434 [10/Jan/2020:00:54:12.123] fe_http~ be_authelia/authelia-backend 0/0/0/381/381 200 361 - - ---- 5/5/0/0/0 0/0 "POST /api/firstfactor HTTP/1.1"
Invalid status code in auth-request backend 'be_authelia': 405
[warning] 009/005412 (6) : Invalid status code in auth-request backend 'be_authelia': 405
```

To my untrained eye it seems like the authentication isn't actually working properly.

@clems4ever: I see the following in the authelia-backend logs, there's no actual reference to `http` so I suspect this is something to do with the redirect.
```
2020/01/10 01:53:05 0.000 #0000000400000001 - 192.168.240.50:9091<->192.168.240.100:51184 - GET http://home.example.com/ - cannot open file "./public_html": open ./public_html: no such file or directory
time="2020-01-10T01:53:06Z" level=debug msg="Credentials validation of user john is ok" method=POST path=/api/firstfactor remote_ip=192.168.240.1
time="2020-01-10T01:53:06Z" level=debug msg="Mark authentication attempt made by user john" method=POST path=/api/firstfactor remote_ip=192.168.240.1
time="2020-01-10T01:53:06Z" level=debug msg="Required level for the URL https://singlefactor.example.com:8080/secret.html is 1" method=POST path=/api/firstfactor remote_ip=192.168.240.1
time="2020-01-10T01:53:06Z" level=debug msg="Redirection is safe, redirecting..." method=POST path=/api/firstfactor remote_ip=192.168.240.1
2020/01/10 01:53:06 0.000 #0000000700000001 - 192.168.240.50:9091<->192.168.240.100:51200 - GET http://singlefactor.example.com/app/public_html/index.html - cannot open file "/app/public_html/index.html": open /app/public_html/index.html: no such file or directory
2020/01/10 01:53:17 12.767 #0000000400000002 - 192.168.240.50:9091<->192.168.240.100:51184 - GET http://home.example.com/ - cannot open file "./public_html": open ./public_html: no such file or directory
time="2020-01-10T01:53:19Z" level=debug msg="Mark authentication attempt made by user john" method=POST path=/api/firstfactor remote_ip=192.168.240.1
time="2020-01-10T01:53:19Z" level=debug msg="Credentials are wrong for user john" method=POST path=/api/firstfactor remote_ip=192.168.240.1
2020/01/10 01:53:21 16.625 #0000000400000003 - 192.168.240.50:9091<->192.168.240.100:51184 - GET http://home.example.com/ - cannot open file "./public_html": open ./public_html: no such file or directory
time="2020-01-10T01:53:22Z" level=debug msg="Credentials validation of user john is ok" method=POST path=/api/firstfactor remote_ip=192.168.240.1
time="2020-01-10T01:53:22Z" level=debug msg="Mark authentication attempt made by user john" method=POST path=/api/firstfactor remote_ip=192.168.240.1
time="2020-01-10T01:53:22Z" level=debug msg="Required level for the URL https://admin.example.com:8080/secret.html is 2" method=POST path=/api/firstfactor remote_ip=192.168.240.1
time="2020-01-10T01:53:22Z" level=debug msg="Available methods are [totp u2f]" method=GET path=/api/configuration/extended remote_ip=192.168.240.1
```

**Comment by nightah** [comment]
@clems4ever so I've confirmed that the current code in haproxy-auth-request alone does not support protecting a https endpoint.

I'll await @TimWolla's response to see if there's perhaps a workaround within the haproxy config, and in the interim I'll also lodge an issue upstream to see if @TimWolla can potentially add support for https.

Based on https://github.com/TimWolla/haproxy-auth-request/issues/3 and https://github.com/csawyerYumaed/hapvault it looks like there's a possibility.

**Comment by TimWolla** [comment]
> **EDIT:** Sorry for all the pings everybody after some more testing looks like I figured it out, it's because haproxy-auth-request is using the `HEAD` method instead of a `GET`. If I patch this back to `GET` it works fine.

For the record, this changed in TimWolla/haproxy-auth-request#10.
