### ISSUE TITLE
Redirection was determined to be unsafe and aborted. Ensure the redirection URL is correct.

### ISSUE THREAD

**Issue by Slyke** [authelia/authelia#2747]
### Description
This might be related to: https://github.com/authelia/authelia/issues/2654 When I try to setup Authelia with nginx reverse proxy I get the error `Redirection was determined to be unsafe and aborted. Ensure the redirection URL is correct.`

### Expected Behaviour
Can setup reverse proxy.

### Reproduction Steps
If I navigate to https://mydomain.xyz/pihole Authelia asks me to login. After I authenticate it sends me to a "loading" page with text up the top stating: "Redirection was determined to be unsafe and aborted. Ensure the redirection URL is correct." I notice that the URL is: `https://mydomain.xyz/authelia/?rd=http://mydomain.xyz/pihole/admin`, note that it doesn't have `https` in the redirect `?rd` URL even though I placed it in originally. Manually adding https in just redirects me back to this page after removing it. I can login to Authelia just fine when navigating to https://mydomain.xyz/authelia

If I change the line:
`auth_request_set $target_url $scheme://$http_host$request_uri;` to `auth_request_set $target_url https://$http_host$request_uri;` to force https, it gets stuck in a redirect loop.

### Additional Information

* My nginx version is: nginx:1.21-alpine
* I'm using the latest Authelia version
* This is on a bare-metal K8s cluster. There is an upstream nginx ingress controller for managing certificates for my domain, but I don't think it's affecting anything here.
* Nothing shows up in Authelia logs, and only the standard access logs for nginx.

Here are my nginx configs:

default.conf:
```
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name _;

  proxy_headers_hash_max_size 512;
  proxy_headers_hash_bucket_size 128; 

  location / { # Testing
    add_header Content-Type text/plain;
    return 200 "Hello world! Kubernetes + Let's encrypt demo. def";
  }

  location /health {
    access_log off;
    return 200 "Working";
  }

  location ~/authelia(.*)$ {
    proxy_pass http://authelia.auth.svc.cluster.local:9091;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location ~/pihole(.*)$ {
    location ~/pihole(/?)$ { # Pihole needs to be in the admin directory
      return 301 https://$host/pihole/admin;
    }

    proxy_pass http://pihole.home.svc.cluster.local;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    include conf.d/auth.config;
    include conf.d/proxy.config;
  }

  include conf.d/authelia.config;
```

Auth Config:
```
auth_request /authelia-auth; # Do note that this is changed from the example docs.

auth_request_set $target_url $scheme://$http_host$request_uri;

auth_request_set $user $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
auth_request_set $name $upstream_http_remote_name;
auth_request_set $email $upstream_http_remote_email;
proxy_set_header Remote-User $user;
proxy_set_header Remote-Groups $groups;
proxy_set_header Remote-Name $name;
proxy_set_header Remote-Email $email;

error_page 401 =302 https://$host/authelia/?rd=$target_url;
```

proxy.config:
```
client_body_buffer_size 128k;

proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 360;
proxy_send_timeout 360;
proxy_connect_timeout 360;

# Basic Proxy Config
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 64 256k;

set_real_ip_from 10.7.0.0/16;
real_ip_header X-Forwarded-For;
real_ip_recursive on;
```

authelia.config
```
location = /authelia-auth { # Do note that this is changed from the example docs.
    internal;
    set $upstream_authelia http://authelia.auth.svc.cluster.local:9091/api/verify;
    proxy_pass_request_body off;
    proxy_pass $upstream_authelia;
    proxy_set_header Content-Length "";

    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

    client_body_buffer_size 128k;
    proxy_set_header Host $host;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Method $request_method;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;

    # Advanced Proxy Config
    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}
```

**Comment by james-d-elliott** [comment]
> * This is on a bare-metal K8s cluster. There is an upstream nginx ingress controller for managing certificates for my domain, but I don't think it's affecting anything here.

This only occurs when the X-Forwarded-Scheme or X-Original-URL is incorrect when sending the request to the /api/verify endpoint. This either occurs due to reconfiguration or due to multiple proxies overriding the request headers. This could very well be the cause.

Why are you using multiple proxies exactly?

**Comment by Slyke** [comment]
Ohhh what should I set the upstream nginx to forward? Just `proxy_set_header X-Original-URL $scheme://$http_host$request_uri;`?

I use [cert-manager](https://cert-manager.io/) to handle all the letsencrypt certificates. It runs an nginx pod as an ingress controller and you expose services to the internet with an ingress config. I point it to a reverse proxy I have running in the same namespace (the way certificates and ingress controllers work requires everything to be in the same namespace), which just forwards it onto my auth namespace reverse proxy which does the actual handling of forwarding to the correct services.

**Comment by james-d-elliott** [comment]
> Ohhh what should I set the upstream nginx to forward? Just `proxy_set_header X-Original-URL $scheme://$http_host$request_uri;`?

Yep that seems accurate. The best way to debug this usually is a pod like whoami configured similarly to Authelia. It may quickly highlight which header is being incorrectly detected by nginx or overridden.

The issue is the request coming to your pihole is being detected as a http scheme request by nginx or communicated to Authelia as being a http scheme request. We are telling Authelia about that in the proxy_set_header lines in the authelia.conf. You could realistically change the file like so to confirm the issue is in the headers:


```nginx
    proxy_set_header X-Original-URL https://$http_host$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Method $request_method;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Ssl on;
```

**Comment by james-d-elliott** [comment]
Also for reference the `$scheme` var in nginx is based on the request that comes to that instance of nginx. So if that request is over `http`, but was over `https` on a proxy upstream of it, `$scheme` will be `http`. This is another potential pitfall with multiple proxies but you can always use a header from the upstream proxy instead of the `$scheme` var, like `$x_forwarded_proto` I think though don't quote me I'm not a regular nginx user.

**Comment by Slyke** [comment]
Giving this a try out. When setting `proxy_set_header X-Forwarded-Proto $scheme;` on the upstream RP, it causes Authelia to fail to load with `Refused to load the script 'http://mydomain.xyz/authelia/static/js/vendor.d0bc79df.js' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.` even though the URL is `http`.

Just trying to figure out how to switch it back to the original proto as it hits Authelia in the downstream reverse proxy.

**Comment by james-d-elliott** [comment]
You need to adjust that in the `location = /authelia-auth` section that has the `internal` directive, that's the section that makes the request to `/api/verify`. The `/api/verify` endpoint generates the final redirection URL which includes `?rd=http://` which means if the scheme is not correct at that exact moment it will fail.

Fixing it at the Authelia server will have no effect.

**Comment by Slyke** [comment]
Yup, finally figured it out after days of trying!

The trick was in `authelia.config` set
```
proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
```
To: 
```
proxy_set_header X-Original-URL https://$http_host$request_uri;
```

I also had some issues with adding trailing slashes and chrome doing infinite redirects. After trying rewrite and redirects, I just settled to have nginx return a basic redirect page:

```
location ~/your-service/?(.*)?$ {
    if ($request_uri ~ /your-service$ ) { # For stopping infinite redirects with adding or removing trailing spaces.
      add_header Content-Type text/html;
      return 200 '<meta http-equiv="refresh" content="0; URL=$uri/" />';
    }
    proxy_pass http://your-service.namespace.svc.cluster.local;
    rewrite /your-service/(.*) /$1 break;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    include conf.d/proxy.config;
    include conf.d/auth.config;
  }
```

I've also noticed that Authelia is no longer honoring the `?rd` param in the URL after logging in, and instead is going to the default redirect, but that's another issue and I'll play around with it a bit more and see if I can figure it out.

Thank you for your help!
