### ISSUE TITLE
Custom email attribute for OIDC Provider

### ISSUE THREAD

**Issue by laurivosandi** [authelia/authelia#2751]
## Feature Request

Please add option of forwarding custom email LDAP attribute via OIDC Provider interface

### Description

Currently the LDAP attribute `mail` is used for both password recovery and OIDC Provider. I would like to see option of configuring them differently.

### Use Case

We use Authelia to reset passwords in our AD/Samba deployment. The person's personal mailbox a'la at foo@gmail.com is stored in the `mail_attribute` which works nicely for password reset.

However in applications we want to show  `username@k-space.ee` which works nicely in most applications since we can just configure different attribute for that eg. `userPrincipalName`. I would like to use the same attribute for OIDC Provider

**Comment by clems4ever** [comment]
Are you requesting this for an application you are writting yourself or a known one?

**Comment by laurivosandi** [comment]
Our current Gitea and Nextcloud deployments use LDAP directly so I have control over which attribute is used for email and I prefer continuing to use the `userPrincipalName` LDAP attribute there where we store e-mail in the format `username@k-space.ee`. 

In order to make use password reset functionality of Authelia I need to use personal e-mail address a'la `first.last@gmail.com` which we store in the `mail` attribute.

I would want to switch Gitea and Nextcloud to OIDC login method, but in this case I would want those apps to continue using `username@k-space.ee` address instead of switching to and even more importantly exposing people's personal e-mail addresses. Gitea shows some of these bits in the explore view.

**Comment by james-d-elliott** [comment]
See https://github.com/authelia/authelia/issues/2868
