### ISSUE TITLE
Proposal: Notification after password reset

### ISSUE THREAD

**Issue by mind-ar** [authelia/authelia#2755]
### Description
This feature will allow to authelia to notify to the end user after a password change (and maybe any other profile change when implemented)

this can address https://github.com/authelia/authelia/pull/2057 if we allow password change with 2FA

let me know if it's worth it, and I can implement it

**Comment by clems4ever** [comment]
I'm not against the idea personally. Let see what others think. @nightah , @james-d-elliott ?

**Comment by nightah** [comment]
I think it's a nice to have for sure.

We could display pertinent information in the email template like Time of change, IP and a country code/flag associated with the IP.
