### ISSUE TITLE
Running authelia on a non standard HTTPs port. Base href is not valid.

### ISSUE THREAD

**Issue by GuiPoM** [authelia/authelia#2765]
Hello. I am not sure I am facing here a bug, but as I had similar issues with other services, I guess it could be or a bug, or a limitation due to default swag/nginx/authelia configuration files not dealing with these non standard ports.

### Description

I am running authelia with swag as a docker-compose configuration.
Authelia is configured and started, no error in the logs, it indicates it is serving.
I am using default configured path 'authelia'. And this setup works as long as I am running on the standard 443 port. Redirect and resources are loaded. 
But as soon as I use a non standard port for swag and its nginx server, the loading of resources fails from the redirect html page.

The returned html contains: 
```
<!DOCTYPE html>
<html lang="en">

<head>
  <base href="https://mydomain:443/authelia/">
  <meta property="csp-nonce" content="jvka8D49jnD4tQpuqbiwZLhZQUlxnSk7" />
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="theme-color" content="#000000" />
  <meta name="description" content="Authelia login portal for your apps" />
  <link rel="manifest" href="./manifest.json" />
  <link rel="icon" href="./favicon.ico" />
  <title>Login - Authelia</title>
  <script type="module" crossorigin src="./static/js/index.67e37718.js"></script>
  <link rel="modulepreload" href="./static/js/vendor.4a71d8d2.js">
  <link rel="stylesheet" href="./static/css/index.6d03b4c9.css">
</head>

<body data-basepath="/authelia" data-duoselfenrollment="false" data-logooverride="false" data-rememberme="true" data-resetpassword="true" data-theme="light">
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root"></div>
</body>
</html>
```
Of course then it tries to load from mydomain:443 and there is no server there. Server is on mydomain:5432 for example.
The root request was https://myservice.mydomain:5432
It is responsed with a 302 and response header `location: https://myservice.mydomain:5432/authelia/?rd=https://myservice.mydomain:5432/`

I also tried to inject a Host header from swag by setting it in the `authelia-server.conf` default configuration. It did not solved my issue, but maybe I did something wrong. Here is one example:
```
location ^~ /authelia {
    proxy_set_header Host $http_host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host:$server_port;
```

### Expected Behaviour
Authelia should work with any HTTPs port used, even if it is not a standard one. 

### Reproduction Steps
Use the standard docker-compose sample file, but maps swag/nginx port to something else that default 443 port. 

### Additional Information
I am using authelia 1.22.0-ls103, from docker image.

**Comment by wbsu2003** [comment]
我也遇到类似的问题，例如你访问的地址是 `https://apps.example.com:5443`，`html` 文件中的 `base href` 会截掉端口，变成 `https://apps.example.com`，浏览器中出现下面这样的错误

【google translate】
I also encountered similar problems. For example, what is the address you visited `https://apps.example.com:5443` , the `base href` in the HTML file will cut off the port and become `https://apps.example.com` , the following error appears in the browser

```text
Refused to load the image 'https://apps.example.com/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by mlojewski-me** [comment]
I encounter problem when running behind TLS termination proxy
the base href is missing http**s** protocol
<base href="http://mydomain.dev/auth/">
I'm using .dev domain which is on HSTS preload list, so HTTPS is required and browser reject downloading files (js scripts) and I only see white screen in browser.

**Comment by james-d-elliott** [comment]
Can't believe I didn't see this, my apologies. Those values are generated based on the X-Forwarded-* headers. Specifically:

X-Forwarded-Proto, X-Forwarded-Host, X-Forwarded-Uri, and X-Forwarded-For is recommended as well.

**Comment by mlojewski-me** [comment]
@james-d-elliott Thanks for answer but [Look here](https://github.com/authelia/authelia/blob/master/internal/server/template.go)


			var scheme = "https"

			if !https {
			proto := string(ctx.Request.Header.Peek(fasthttp.HeaderXForwardedProto))
			switch proto {
			case "":
				scheme = "http"
			default:
				scheme = proto
			}
		}

		baseURL := scheme + "://" + string(ctx.Request.Host()) + base + "/"`

scheme is taken from X-Forwarded-Proto, but hostname is taken from Host header I think It should be X-Forwarded-Host

**Comment by james-d-elliott** [comment]
That's a good spot, however you mentioned it's missing the https proto not having issues with the host portion?

**Comment by GuiPoM** [comment]
> Can't believe I didn't see this, my apologies. Those values are generated based on the X-Forwarded-* headers. Specifically:
> 
> X-Forwarded-Proto, X-Forwarded-Host, X-Forwarded-Uri, and X-Forwarded-For is recommended as well.

Hello James,
For the context of my initial post: I am not that very familiar with authelia, I was only activating it as a user of the docker-swag image. I identified there several issues when you are not running on a standard 443 port for HTTPS but some of the header you are mentionning are already in place. I don't know how familiar you are with the swag project.

In [proxy.conf:](https://github.com/linuxserver/docker-swag/blob/master/root/defaults/proxy.conf):
```
# Proxy Header Settings
proxy_set_header Connection $connection_upgrade;
proxy_set_header Early-Data $ssl_early_data;
proxy_set_header Host $host;
proxy_set_header Proxy "";
proxy_set_header Upgrade $http_upgrade;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header X-Real-IP $remote_addr;
```

In the dedicated [authelia configuration file](https://github.com/linuxserver/reverse-proxy-confs/blob/master/authelia.subdomain.conf.sample):
```
    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app authelia;
        set $upstream_port 9091;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
```

Only X-Forwarded-Uri is missing, I don't know how important it could be. I should give it a try, but I had to revert to a 443 port as I was spending days to debug why services were not behaving properly.

**Comment by james-d-elliott** [comment]
It's the least important one, the most important are the proto and host, I'm not personally very familiar with nginx but looking at the nginx docs and our docs this may need a small adjustment:

```
proxy_set_header X-Forwarded-Host $http_host;
````

**Comment by mlojewski-me** [comment]
> That's a good spot, however you mentioned it's missing the https proto not having issues with the host portion?

The Protocol is fine.

**Comment by james-d-elliott** [comment]
> I encounter problem when running behind TLS termination proxy the base href is missing http**s** protocol
> I'm using .dev domain which is on HSTS preload list, so HTTPS is required and browser reject downloading files (js scripts) and I only see white screen in browser.

Could you clarify this then? What do you mean it's missing the http**s** protocol?

**Comment by mlojewski-me** [comment]
> > I encounter problem when running behind TLS termination proxy the base href is missing http**s** protocol
> > I'm using .dev domain which is on HSTS preload list, so HTTPS is required and browser reject downloading files (js scripts) and I only see white screen in browser.
> 
> Could you clarify this then? What do you mean it's missing the http**s** protocol?

That was my misconfiguration.

**Comment by james-d-elliott** [comment]
Okay so my suggestions are to set the following in proxy.conf:

```nginx
proxy_set_header X-Forwarded-Host $http_host;
```

Then add this if the above doesn't work:

```nginx
proxy_set_header Host $http_host;
```

I'm working on a permanent fix in the codebase.

**Comment by james-d-elliott** [comment]
Feel free to try out the fix we've implemented either via master or wait for 4.34 to release.

**Comment by rsfurlan90** [comment]
Hello @james-d-elliott I am afraid that it might still be an issue, but manifesting at another point.

I have a swag setup bound to a non standard HTTPS port and I got stuck in the "Register your mobile" email because the Register button URL didn't have the port.

The workaround you suggested above is still valid though and it helped me to proceed with the registration.

**Comment by james-d-elliott** [comment]
Hi there. We can't really do anything magic to fix this particular part, we've fixed the bug on our end to the extent it can be fixed. If the header is incorrect ([per several standards](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host) it should match the `Host` header received by the server, which comes from `$http_host`, the `$host` var strips the port out) we have no way of knowing what port to forward the user to. 

While there is no *formal* specification regarding `X-Forwarded-Host` it stands to reason that this value would communicate useful information, and all related documentation and a [specification meant to replace it](https://datatracker.ietf.org/doc/html/rfc7239#section-5.3) claim it should be the original `Host` header. Which is not the case in this instance.
