### ISSUE TITLE
Authelia + Traefik in Docker --- Remote IP is always the docker gateway and not client IP

### ISSUE THREAD

**Issue by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [authelia/authelia#2771]
I've had Authelia successfully configured as a middleware in Traefik for months now. But I recently inspected the Authelia logs and discovered all connections appear "Remote-IP=172.18.0.1", which is the IP of the docker network gateway. So anytime an IP ban is initiated due to a number of bad login attempts, it's not banning the actual client IP but the docker gateway.

I've read the following, which has helped me in troubleshooting, but still have not solved my issue:

> Fail2Ban filter for Authelia
> Make sure that the HTTP header "X-Forwarded-For" received by Authelia's backend`
> only contains a single IP address (the one from the end-user), and not the proxy chain
> (it is misleading: usually, this is the purpose of this header).

Despite all I've tried, the Remote-IP still appears as the proxy chain gateway.

I've even tried setting my forwardedHeaders.insecure = true in my traefik.yml for troubleshooting purposes to no avail.

**Comment by james-d-elliott** [comment]
For the forwarded IP header to be correct locally it will require the proxy sees your remote IP accurately. This comes down to the path your TCP connection takes and is usually due to either DNS or nat hairpin issues.

**Comment by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [comment]
In this case, I'm running traefik on a vps, using authelia as a middleware for authenticating users. So there shouldn't be any NAT issues or DNS issues unless it's caused by docker, no?

If so, do you have any insight into how to resolve the issue?

**Comment by james-d-elliott** [comment]
That depends. I'm assuming the client appearing as the gateway only occurs for LAN clients for starters, as this usually is when it occurs, correct me if I'm wrong.

If I'm right then you need to ping the Authelia domain you have setup from an affected client to see what address it comes back as. If it comes back as a LAN IP, then something weird is going on. If it comes back as a Global IP such as your WAN IP, then the issue is as I described.

**Comment by nightah** [comment]
Do you happen to be running on a Synology NAS? Their iptables implementation for Docker causes this exact issue.

Other than that as James has suggested I would troubleshoot further up the chain first at the reverse proxy to see what's being received there first.

**Comment by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [comment]
After the most recent traefik update I no longer have this issue.

**Comment by Maypul** [comment]
@zsQ8ymRSY8B4owpdCvTRdkz8rQUK 
Could you share more detailed info about your configuration (maybe traefik middlewares with headers)? I am also using authelia and Traefik and getting ip of the socket proxy gateway (network that traefik is in to access socket proxy). I can only assume it would show first network ip if socket would be mounted. After upgrading both Traefik and authelai to the newest version I am still seeing local ip address.

I am on syynology dsm 7 and have found that using additional ip table rules fixes it and allows me to see real IP in logs:
iptables -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
iptables -t nat -A PREROUTING -m addrtype --dst-type LOCAL ! --dst 127.0.0.0/8 -j DOCKER

BUT I have also noticed, some, not all containers that have exposed ports, are accessible even if firewall blocks them. In my case it was phpmyadmin container on port 8080 and organizzer on port 82. Rest constainers with exposed ports in docker still needed rules for them to be accessible outside of the machine. So it is not ideal solution.
