### ISSUE TITLE
Add MongoDB as authentication backend

### ISSUE THREAD

**Issue by laurivosandi** [authelia/authelia#2784]
## Feature Request

Please add generic MongoDB driver that would allow referencing users in a MongoDB collection. Basic rationale is that we keep user objects primarily in MongoDB and only users who need to use services behind Authelia are created an AD account on-demand.

Adding MongoDB storage driver could potentially make AD account obsolete/optional for our deployment, which is definitely something we would want to pursue.

### Description

In the `storage` section add MongoDB section which would describe:
- Which database to use
- Which collection to use
- Which attribute to use for first name
- Which attribute to use for last name
- Which attribute to use for password recovery e-mail 
- Which attribute to use for OIDC clients as e-mail, see #2751 for distinction
- Which attribute to use to detect whether user account is active

### Use Case

This somewhat resonates with #2783 as we don't store any password hashes in MongoDB and we would like to keep it that way. Adding password hash storage in a separate attribute of course is easy.

**Comment by clems4ever** [comment]
Hello @laurivosandi , thanks for raising this issue. It relates to one already raised a long time ago: impelementing an SQL authentication backend. Even though, I think an AD would be the enterprise-grade way, I agree on the fact that it's not the most user-friendly interface for everyone despite it's probably the most secure one at the moment.

Adding mongo would probably not be difficult to implement thanks to the abstractions I put in place initiialy but I think it's best to wait for [this design](https://github.com/authelia/authelia/issues/1538) to be completed before we decide to implement and merge any new connector.

Does it make sense?

**Comment by james-d-elliott** [comment]
Thinking about this from a maintainability point of view. This may be a great candidate for go plugins and exposing our various provider types to the public portion of the module.

Then we can create a MongoDB example for people that matches this specific feature. It's going to require some work to get the configuration validation portion to work but it's possible to do if we make the plugin API robust enough and expose a validator interface. We will also either have to use reflection to scan the config struct into the valid keys var or include a method retrieve valid config keys from the plugins.

Considering we're using cgo now for additional benefits it provides in security we may as well take advantage of this.

**Comment by james-d-elliott** [comment]
I think after discussing this in depth we're unlikely to implement this specifically and will instead aim to implement SCIM 2.0.
