### ISSUE TITLE
Add documentation related to deployment on bare metal

### ISSUE THREAD

**Issue by clems4ever** [authelia/authelia#2794]
In the deployment section of the doc there is not much information about deployment on bare metal. We need to provide minimal information on that deployment flavor.

**Comment by chibbi** [comment]
Do you mean that for example:

![grafik](https://user-images.githubusercontent.com/68948051/150616815-06bb0eda-dae8-495f-a772-f9c28991195d.png)
This Should be explained what you are supposed to modify and why?
Because that is what confused me right now wanting to try out authelia.

**Comment by james-d-elliott** [comment]
Nope it's in relation to how to deploy it on a bare metal system, instead of in docker. If you're having issues with the docker-compose examples you can drop into the chat anytime and we can help or  you can create your own issue.

**Comment by james-d-elliott** [comment]
https://www.authelia.com/integration/deployment/bare-metal/
