### ISSUE TITLE
OIDC claim for preferred username

### ISSUE THREAD

**Issue by laurivosandi** [authelia/authelia#2798]
Looks like "standard" one is `name`, at least that's what Harbor suggests using.

Please add the username claim that would allow forwarding username from AD

**Comment by james-d-elliott** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

We already set the name claim as the users display name if the profile scope is requested. We can set the `preferred_username` claim as well, though `sub` is already set to this. If harbor really expects `name` to be the username it's ignoring the specification though as far as I can tell.

**Comment by laurivosandi** [comment]
Ah nice, maybe it's worth clarifying somewhere which claims Authelia supports out of the box? Maybe somewhere here? https://github.com/authelia/chartrepo/blob/master/charts/authelia/values.yaml#L975

**Comment by james-d-elliott** [comment]
It's already clearly outlined in the docs: https://www.authelia.com/docs/configuration/identity-providers/oidc.html#scope-definitions

**Comment by james-d-elliott** [comment]
@laurivosandi just letting you know we added the preferred_username claim which should be available in the next patch/minor release.

**Comment by laurivosandi** [comment]
I guess the root problem here was being newcomer to OIDC in general. Thanks for clarifying anyway :)

**Comment by james-d-elliott** [comment]
No drama at all! @laurivosandi just a forward warning, based on some intense reading of the spec, it's expected `sub` will change in the future.

**Comment by laurivosandi** [comment]
I noticed that `sub` seems to insert now some (user?) UUID?

**Comment by james-d-elliott** [comment]
Yes, it's an opaque identifier in the form of a UUID v4.
