### ISSUE TITLE
could not parse 'Authelia donotreply@blabla' as a RFC5322 address: mail: no angle-addr

### ISSUE THREAD

**Issue by davama** [authelia/authelia#2809]
Looking at template:
https://github.com/authelia/authelia/blob/6366e3452c7999ef84a4ba534bf9ae4e98707078/config.template.yml#L617

This does not work:

```
    sender: "Authelia donotreply@blalba.org"
```

Got the below logs:

```
ERRO[0000] Configuration: error occurred during unmarshalling configuration: 1 error(s) decoding:
* error decoding 'notifier.smtp.sender': could not parse 'Authelia donotreply@blabla.org' as a RFC5322 address: mail: no angle-addr 
ERRO[0000] Configuration: A notifier configuration must be provided 
FATA[0000] Can't continue due to the errors loading the configuration 
```

Setting it to this made authelia startup fine:
```
    sender: donotreply@blabla.org
```

Bug? ID10T error?

> authelia version v4.33.1

Thanks

**Comment by james-d-elliott** [comment]
What about this?

```
    sender: "Authelia <donotreply@blalba.org>"
```

**Comment by davama** [comment]
ok... thought the `<>` were not literal :disappointed: 
closing

**Comment by davama** [comment]
thank you btw

**Comment by james-d-elliott** [comment]
No worries! Also yeah we decided to use the exact format used in emails to standardize it and use go's standard parser for mail addresses.

Makes it easy to extract the portions we need for the `FROM` and `MAIL FROM` headers, while making it simple to maintain.
