### ISSUE TITLE
chrome based browsers : U2F API seem to be removed after February 2022

### ISSUE THREAD

**Issue by dginhoux** [authelia/authelia#2818]
### Description

** Used U2F factors :**
yubikey 5C
T-OTP

**Used servers :** 
traefik 2.4.7
authelia 4.33.1

**Tested browsers**
chrome 96
chromium 96
brave 1.33 (chromium 96)
firefox 95

**warning from all based chrome browsers ; nothing with firefox**
this message appear ONLY when using U2F/Security Keys as second factor
![image](https://user-images.githubusercontent.com/12201081/150502411-08c6c516-d3bf-4dde-8c07-07c708e4ce10.png)

### Expected Behaviour

no warning message

**Comment by james-d-elliott** [comment]
#2707
