### ISSUE TITLE
Storage migration fails using mysql

### ISSUE THREAD

**Issue by olivergrahl** [authelia/authelia#2822]
### Description

Cannot start Authelia when having configured `storage.mysql`.
Authelia 4.33
MySQL 5.7

### Expected Behaviour

Ability to start Authelia with mysql storage.

### Reproduction Steps

1. Run
```
docker run -d --name redis -v /data/redis:/data redis redis-server --appendonly yes
docker run -d --name mysql -v /data/mysql:/var/lib/mysql mysql:5.7
```
2. Create mysql user.
3. In `/data/authelia/configuration.yml`, along with other required options, configure `storage.mysql` to point to above `mysql` and user.
4. Run 
```docker run -d --name authelia -v /data/authelia:/config --link redis:redis --link mysql:mysql authelia/authelia:4.33```
5. `docker logs authelia` will reveal:
```Failure running the storage provider startup check: error during schema migrate: migration rollback complete. rollback caused by: schema migration 1 (Initial Schema) failed: Error 1067: Invalid default value for 'exp'```

### Additional Information

This line seems to be causing the issue:
https://github.com/authelia/authelia/blob/9ceee6c660ac240f68d83b515dac91835751b3b5/internal/storage/migrations/V0001.Initial_Schema.mysql.up.sql#L21
It should probably either be 
```exp TIMESTAMP NULL DEFAULT NULL,```
or
```exp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,```

**Comment by james-d-elliott** [comment]
`exp TIMESTAMP NOT NULL` is a  valid column definition for 5.7.37 at least in the community edition at least with a fairly default install.. is there any more context you can provide that may be useful like the exact version, collations, encoding?

**Comment by james-d-elliott** [comment]
Actually looks like this may shed some light: `SHOW VARIABLES LIKE 'sql_mode' ; `. Seems like some new/old versions may have a mode that prevents this common syntax.

**Comment by james-d-elliott** [comment]
This maybe sheds some light: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp

**Comment by james-d-elliott** [comment]
Looks like this option needs to be ON. Can be set via the CLI option or in my.cnf like so:

```
[mysqld]
explicit_defaults_for_timestamp = 1
```

**Comment by olivergrahl** [comment]
Setting `explicit_defaults_for_timestamp` worked! I know 5.7 is not the freshest, but still quite common. Would it make sense to still just add a default to the CREATE statement to avoid running into this issue? Thanks again!

**Comment by james-d-elliott** [comment]
> Setting `explicit_defaults_for_timestamp` worked! I know 5.7 is not the freshest, but still quite common. Would it make sense to still just add a default to the CREATE statement to avoid running into this issue? Thanks again!

Yep may make sense. What's infuriating is you can create it with the default then remove said default and it's happy with it. I think what may influence our decision is what other supported versions have this change as default. I think if every other version in the Oracle support list, and all supported versions of MariaDB have this on by default, then it'd make more sense to say we don't support it without that parameter configured in the docs.
