### ISSUE TITLE
Address bar authentication for uptime monitoring

### ISSUE THREAD

**Issue by Leopere** [authelia/authelia#2826]
I'm hoping that this is possible I'd like to build a URL with httpauth in it https://username:password@login.example.com/ so that I can check the uptime of something behind Authelia and not all just hitting Authelia

**Comment by james-d-elliott** [comment]
For things protected with `one_factor` you can use the Proxy-Authorization header. https://www.authelia.com/docs/features/single-factor.html#proxy-authorization-header

**Comment by Leopere** [comment]
<img width="937" alt="image" src="https://user-images.githubusercontent.com/1068374/151680358-40b3548d-f0cc-467f-81cd-d5356714e181.png">

I think that I can imagine how to do this but have you any suggestions on how that documentation translates to a setting in this uptime monitor?

**Comment by Leopere** [comment]
Like for example I'm looking to test the uptime for https://traefik.example.com is what I'm looking to prove is online I need to bypass auth from https://auth.example.com (authelia)

**Comment by Leopere** [comment]
Another instrumental use case for this would be to allow access to a Docker registry which with Træfik, I typically would impose simple HTTP auth, which is `docker login` compatible.

**Comment by james-d-elliott** [comment]
You set the Proxy-Authorization header the same as you would the Authorization header for HTTP basic auth. You can alternatively use `/api/verify?auth=basic` in the forwardAuth middleware to force the use of the Authorization header which is probably compatible with docker login, or change the header name from Authorization to Proxy-Authorization when received.

The format expected by the header for basic auth is `Proxy-Authorization: basic <credentials>` where credentials are <username>:<password> encoded in base64 URL encoding (the `simple HTTP auth` you describe).

**Comment by james-d-elliott** [comment]
Did you solve this?
