### ISSUE TITLE
Request to list Authelia as a user of makedeb

### ISSUE THREAD

**Issue by hwittenborn** [authelia/authelia#2830]
Hi!

I'm in the middle of creating a new website for [makedeb](/makedeb/makedeb), and I was wondering if y'all would be fine if I used Authelia as a group that's using makedeb.

I've got some rough sketches written for the website, and it would currently look something like this if you were to allow it (for the time being Authelia is indeed going to be the only group listed there, as there haven't been any other major groups to start using makedeb yet):

![image](https://user-images.githubusercontent.com/74838472/150634755-88ee709c-a8b0-42d9-9a1d-62a26af44529.png)

I haven't published anything yet, and this is all still local on my machine. I just wanted to check that this would be OK with you guys before I did anything.

**Comment by hwittenborn** [comment]
I got a footer going, and this is what the finished stuff looks like at the bottom:

![image](https://user-images.githubusercontent.com/74838472/150636157-aa0e3c0f-1b70-4397-8b72-ff4b64a11171.png)

**Comment by james-d-elliott** [comment]
Hey sorry for taking a while to get back to you, wanted to get the whole team to give their input. We'd be happy for you to do this!

**Comment by clems4ever** [comment]
Hey @hwittenborn , thanks for asking, you can proceed. It's a win-win for both projects :). Thanks for that.

**Comment by hwittenborn** [comment]
All good @james-d-elliott. Glad to see all y'all are in agreement with it!

I'll get those changes deployed shortly :)
