### ISSUE TITLE
Migrating from local backend storage to MySQL

### ISSUE THREAD

**Issue by shiggins8** [authelia/authelia#2836]
I wanted to change my original setup from a local db.sqlite3 backend storage to a true database (MySQL or PostgresQL). Is there a process to do that? or do I essentially need to set up the database and "restart" my setup for Authelia?

Thanks for the help!

**Comment by james-d-elliott** [comment]
Postgres is probably the easiest that I know of to migrate to due to [pgloader](https://github.com/dimitri/pgloader). We don't currently have any tooling to migrate internally.

**Comment by shiggins8** [comment]
@james-d-elliott thanks for the response, I appreciate it! from what I can tell, if I don't mind missing the historical authentication logs, the only real data I have that I need to move over would be the device id for duo and I can do that manually. thanks again.

**Comment by james-d-elliott** [comment]
No worries, that's probably what I'd do as well.
