### ISSUE TITLE
Seafile desktop application blocked by Authelia

### ISSUE THREAD

**Issue by ghostersk** [authelia/authelia#2840]
I am trying to run Seafile file hosting with Authelia, I can access the website from browser.
But I am getting blocked by authelia when i use the desktop app, and it tries to connect to the share drive
-- see the log file. I even whitelisted that url and it still blocks.
```   
    - domain: 
        - "seaf.mysite.com"
      policy: one_factor
    - domain: "seaf.mysite.com"
      resources:
        - "^/seafhttp/.*$"
        - "^/api.*$"
      policy: bypass
```
Previously I had problem with Authelia to let me to the Seafile page itself, when i used that default Nginx Config, but that I sorted by removing: `proxy_set_header X-Forwarded-Ssl on;`

Here is my whole Nginx Config:
```
location /authelia {
internal;
set $upstream_authelia http://authelia:9091/api/verify; 
proxy_pass_request_body off;
proxy_pass $upstream_authelia;    
proxy_set_header Content-Length "";

# Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
client_body_buffer_size 128k;
proxy_set_header Host $host;
proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr; 
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
#proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 4 32k;

send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;
}

location / {
set $upstream_homer $forward_scheme://$server:$port; 
proxy_pass $upstream_homer; 

auth_request /authelia;
auth_request_set $target_url https://$http_host$request_uri;
auth_request_set $user $upstream_http_remote_user;
auth_request_set $email $upstream_http_remote_email;
auth_request_set $groups $upstream_http_remote_groups;
proxy_set_header Remote-User $user;
proxy_set_header Remote-Email $email;
proxy_set_header Remote-Groups $groups;

error_page 401 =302 https://auth.mysite.com/?rd=$target_url; #change this to match your authentication domain/subdomain

client_body_buffer_size 128k;

proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

send_timeout 5m;
proxy_read_timeout 360;
proxy_send_timeout 360;
proxy_connect_timeout 360;

proxy_set_header Host $host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection upgrade;
proxy_set_header Accept-Encoding gzip;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
#proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 64 256k;

set_real_ip_from 192.168.0.0/16; 
set_real_ip_from 172.0.0.0/8; 
real_ip_header CF-Connecting-IP;
real_ip_recursive on;

}
```
[error.txt](https://github.com/authelia/authelia/files/7964043/error.txt)

**Comment by james-d-elliott** [comment]
Move the bypass rule above the one_factor rule. The bypass rule is ineffectual since the one_factor rule matches all requests to seafile.

**Comment by ghostersk** [comment]
I will try, but I have same way set up for blocking admin rout for vaultwarden and that works.
I am trying now to deploy Authelia with Traefik, rathern then NPM, as I had problems with some parts of other web apps, as it seems like there been missing headers or what. Hopefully with Traefik it will pass all needed stuff.

**Comment by james-d-elliott** [comment]
The first rule which has all criteria matching is the rule that is matched. This applies to all matching criteria. For resources it must match at least one of the resource rules or the rule is skipped, same for methods, subjects is mostly similar but it has an additional syntax which allows you to require a user be in multiple groups, networks operates the same.

Here's a matrix mapping configuration scenarios to requests and the outcome, this rule order takes precedence over everything if a rule has all of the criteria above matching:

Configuration Scenario 1:

|Rule #|Domain                  |Resources|Policy|
|-------:|:----------------------:|:-----------:|:------:|
|1        |app.example.com  |N/A          |1FA     |
|2        |app.example.com  |^/api.*    |Bypass|

Configuration Scenario 2:

|Rule #|Domain                  |Resources|Policy|
|-------:|:----------------------:|:-----------:|:------:|
|1        |app.example.com  |^/api.*    |Bypass|
|2        |app.example.com  |N/A          |1FA     |


Request Scenarios:

|Request #|Path|
|-------:|:--------------------------:|
|1        |app.example.com        |
|2        |app.example.com/api |


Matrix:

|Configuration Scenario|Request|Matched Rule|Policy|
|:----------------------------:|:---------:|:-----------------:|:-----:|
|1                                     |1            |1                       |1FA   |
|1                                     |2            |1                       |1FA   |
|2                                     |1            |2                       |1FA   |
|2                                     |2            |1                       |bypass|

**Comment by james-d-elliott** [comment]
Assuming by the lack of reply  you got it to work, if not let us know!

**Comment by travelr** [comment]
After spending some time to figure it out: 

`    - domain: seafile.xyz.com
      policy: bypass
      resources:
        - "^/(api2|seafhttp)([/?].*)?$"
    - domain: seafile.xyz.com
      policy: two_factor`

I hope that helps someone else in the future
