### ISSUE TITLE
Support for Signal gateway 2 factor authentication needed

### ISSUE THREAD

**Issue by hppyworld** [authelia/authelia#2846]
Hello ,

Its good to have signal gateway 2 factor authentication. May be this project can be integrated. 
https://gitlab.com/morph027/signal-cli-dbus-rest-api

Thanks.

**Comment by clems4ever** [comment]
Hello,

2FA is usually made for human interaction, not service-to-service interaction. I don't see what we can easily do about that except develop a completely new workflow for that that will eventually looks like an app password generated after 2FA authentication of the user (which is not really improving security of the service account itself).

I'm closing this issue as we won't do anything about this specifically but, in the future, you can expect app passwords to be generated upon 2FA though. I would not imagine this feature without the possibility to raise the level of security to 2FA anyway.
