### ISSUE TITLE
Content Security Policy error on 2FA one time password page

### ISSUE THREAD

**Issue by jamesmacwhite** [authelia/authelia#2847]
### Description

When requesting 2FA on the `/2fa/one-time-password` page, a Content Security Policy error is thrown in console.

```
vendor.e43a5c96.js:582 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-aj4EejmjNgLJn6CVZdsHB5DtalrZjWRL'". Either the 'unsafe-inline' keyword, a hash ('sha256-aqNNdDLnnrDOnTNdkJpYlAxKVJtLt9CtFLklmInuUAE='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

z.getIframePort_ @ vendor.e43a5c96.js:582
(index):6772 crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):6772
vendor.e43a5c96.js:582 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('chrome-extension://kmendfapggjehodndflmmgagdbamhnfd') does not match the recipient window's origin ('null').
(anonymous) @ vendor.e43a5c96.js:582
index.b4ae602a.js:1 U2F not supported
(anonymous) @ index.b4ae602a.js:1
```

It seems to be this related to this iframe being injected

```
<iframe src="chrome-extension://kmendfapggjehodndflmmgagdbamhnfd/u2f-comms.html" style="display:none"></iframe>
```

![image](https://user-images.githubusercontent.com/8067792/152596452-15c2e421-11d5-46d3-b96e-1053151d0615.png)

I am not using U2F, just Google Authenticator with TOTP.

### Expected Behaviour

No Content Security Policy violation should occur.

### Reproduction Steps

1. Enable domain/resource for policy `two_factor`
2. Login with valid credentials to trigger 2FA one-time-password prompt page
3. Observe blocked resource in the corner due to CSP violation

### Additional Information

Ubuntu 20.04 LTS
Google Chrome Version 98.0.4758.82 (Official Build) (64-bit)
Authelia version v4.33.2 (Standalone)

**Comment by jamesmacwhite** [comment]
[It looks like this due a API deprecation in Chrome 98](https://developer.chrome.com/blog/deps-rems-95/#deprecate-u2f-api-cryptotoken).

I should clarify though, I'm not using U2F at all.

**Comment by james-d-elliott** [comment]
It's not related to that API deprecation unless I'm missing something. It's a plugin which is injecting that content into the page most likely. Which we don't support for security reasons.

**Comment by jamesmacwhite** [comment]
@james-d-elliott I've just tested it with an incognito session, so no browser plugins should be running and it still happens, so I'm not sure it's related to any extensions.

If I enable the `U2fSecurityKeyApiEnabled` policy the CSP error goes away.

https://chromeenterprise.google/policies/#U2fSecurityKeyApiEnabled

![image](https://user-images.githubusercontent.com/8067792/152632533-4ab837da-34bf-47cb-aa71-217ca4283471.png)

**Comment by james-d-elliott** [comment]
Could be, in which case that's solved by #2707

**Comment by jamesmacwhite** [comment]
@james-d-elliott Absolutely, agree it's an extension but it's not a user one, it's a extension built into Chrome related to the mentioned U2F API which has been disabled by default in Chrome 98 by the looks of it, so it is more of a side effect of an upstream change.

With the PR you linked, it sounds like changing the U2F system will likely fix this error, given it's not using the deprecated API flagged.

**Comment by james-d-elliott** [comment]
We'll be removing the U2F in favor of Webauthn, and leverage the backwards compatibility assertion extension (appid). This will allow previously registered U2F FIDO compliant keys to authenticate.

**Comment by jamesmacwhite** [comment]
@james-d-elliott Great, thanks for the info! I don't personally use U2F currently, I assume it just triggered by the 2FA screen regardless, however it's good to know that this will be resolved by a future update.

The workaround at the moment is enabling the U2F policy in Chrome to restore the API.

**Comment by Tropaion** [comment]
I hope this gets fixed soon, currently authelia is unusable for me because of this.

**Comment by jamesmacwhite** [comment]
You can enable the legacy API until Authelia includes the newer U2F implementation.

https://developer.chrome.com/blog/deps-rems-95/#deprecate-u2f-api-cryptotoken

Set the [U2fSecurityKeyApiEnabled](https://chromeenterprise.google/policies/#U2fSecurityKeyApiEnabled) key to enable it.
