### ISSUE TITLE
access_control lists configuration

### ISSUE THREAD

**Issue by Maypul** [authelia/authelia#2851]
Hello there!
I am having issues with configuring correct access control lists in Authelia, I am unsure if that is because I am making somewhere an error or this is just not supported.

I have a vaultwarden server installation, and would like to restrict access to /admin to only local subnets. I have no problem with setting it though Traefik, by making a separate call for /admin and then using Traefik's ipwhitelists but that is not ideal.

Here is my code:

    - domain: "vaultwarden.example.com"
      policy: bypass
      resources:
        - "^/api.*$"
        - "^/identity.*$"

    - domain: "vaultwarden.example.com"
      policy: two_factor
      resources:
        - "^/admin.*$"
      networks:
        - 192.168.10.10
      subject: ["group:admins"]

    - domain: "vaultwarden.example.com"
      policy: two_factor
      subject: 
        - ["group:vaultwarden"]

    - domain:
        - "*.example.com"
        - "example.com"
      policy: two_factor
      subject: ["group:admins"]

It seems that I can't get a second block to work in any way. If I were to use bypass, It would probably work but then two factor would be dropped, am I correct? I am using account that has access to admins group. I would like to make it work, so /admin is available for admins account only that access it though specific ip address.

**Comment by james-d-elliott** [comment]
The logs will reveal what's occurring most likely, it's probably not the primary request but auxiliary requests being redirected.

**Comment by Maypul** [comment]
Sorry, by not working I mean Authelia would still let me login despite setting network to different one than my host, in logs it still show the correct ip (of my host). I would expect that It would throw at me 403 as I am logging in from not allowed IP. I have enabled trace logging, disabled Traefik block, restarted Authelia/Redis and tried to log in again:
I guess this would be revelant log:
time="2022-02-06T20:52:41+01:00" level=trace msg="Profile details for user 'USER' => groups: [admins dev], emails [USER@gmail.com]" method=POST path=/api/firstfactor remote_ip=192.168.10.11
time="2022-02-06T20:52:41+01:00" level=debug msg="Check authorization of subject username=USER groups=admins,dev ip=192.168.10.11 and object https://vaultwarden.example.com/admin (method GET)."
time="2022-02-06T20:52:41+01:00" level=trace msg="ACL MISS Position 1 for subject username=USER groups=admins,dev ip=192.168.10.11 and object https://vaultwarden.example.com/admin (Method GET)"
time="2022-02-06T20:52:41+01:00" level=trace msg="ACL MISS Position 2 for subject username=USER groups=admins,dev ip=192.168.10.11 and object https://vaultwarden.example.com/admin (Method GET)"
time="2022-02-06T20:52:41+01:00" level=trace msg="ACL MISS Position 3 for subject username=USER groups=admins,dev ip=192.168.10.11 and object https://vaultwarden.example.com/admin (Method GET)"
time="2022-02-06T20:52:41+01:00" level=trace msg="ACL HIT Position 4 for subject username=USER groups=admins,dev ip=192.168.10.11 and object https://vaultwarden.example.com/admin (Method GET)"

So it matches last ACL and allows me to log in.

**Comment by nightah** [comment]
According to your ACLs, this is the correct behaviour.

The IP address you've allowed in rule 2 doesn't match what's in your logs; `192.168.10.11` vs `192.168.10.10`.

If you don't want anybody to have access to the `/admin` path when not coming from the `.10` address your ACL's need to look like this so it doesn't trigger the final catch-all admin rule you have:

```yaml
- domain: "vaultwarden.example.com"
  policy: bypass
  resources:
    - "^/api.*$"
    - "^/identity.*$"

- domain: "vaultwarden.example.com"
  policy: two_factor
  resources:
    - "^/admin.*$"
  networks:
    - 192.168.10.10
  subject: ["group:admins"]

- domain: "vaultwarden.example.com"
  policy: deny
  resources:
    - "^/admin.*$"

- domain: "vaultwarden.example.com"
  policy: two_factor
  subject: 
    - ["group:vaultwarden"]

- domain:
    - "*.example.com"
    - "example.com"
  policy: two_factor
  subject: ["group:admins"]

- domain:
    - "*.example.com"
    - "example.com"
  policy: two_factor
  subject: ["group:admins"]

**Comment by Maypul** [comment]
@nightah thank you very much! It's working as I wanted. You also placed last rule twice.

I am closing this as it's solved, but do you know how can I escape "#" character in these access lists? I have tried few ways that seem to be valid as verified in other regex checkers but I can't get it to work, it either crashes or just does not match the rule. I was also trying to add rule to bypass 2fa for following link: vaultwarden.example.com/#/send/randomstring. /#/ is what I am having issue with, the string is "/#/send/" which needs to be matched.

As a side note, is it possible with Authelia to still ask for 2fa before it shows forbidden? Now it just asks for password before showing access denied, of course still asks for code when switched to different subdomain.
