### ISSUE TITLE
yubikey stopped working with chrome 98

### ISSUE THREAD

**Issue by loeken** [authelia/authelia#2866]
### Description

after upgrading my browser to chrome 98.0.4758.80-1 as its now the default in the arch user repos. I noticed that i cannot use my yubico security key anymore as the browser doesnt seem "to find it"

### Expected Behaviour

Browser to find my key and allow me to use it

### Reproduction Steps

- upgrade chrome to 98.0.4758.80-1
- use key to sign in

### Additional Information

Seems to be related with chrome decommisioning u2f
https://www.yubico.com/blog/google-chrome-u2f-api-decommission-what-the-change-means-for-your-users-and-how-to-prepare/

**Comment by james-d-elliott** [comment]
See #241
