### ISSUE TITLE
Starting with Authelia for my portals and please help me to understand below

### ISSUE THREAD

**Issue by Blason** [authelia/authelia#2870]
Hi Team,

Let me first describe my setup. I have 5 portals on my Apache server with IP address 192.168.5.10 and I have nginx reverse proxy with IP address of 192.168.5.11. All those vhosts are reverse proxied through Nginx. All those are bare-metal config and no docker involved. Till now I have used Nginx basic auth to maintain the authentication. However since I now want to try Authelia my; my queries are

Can I use other dedicate server for authelia, like 192.168.5.12 as auth.testmyserver.com
Are there any deb packages available for authelia? Or docker is de-facto standard?
I wanted to authenticate users with our Google apps and is that possible?
Is nginx-proxy manager mandatory to setup authelia?

Eventually  my setup would be,

test.testmyserver.com [192.168.5.11:443] --> 192.168.5.10:443 and authentication will be forwarded to auth.testmyserver.com?

Can that be achieved?

**Comment by jamesmacwhite** [comment]
You don't need Docker to run Authelia, there is a APT repository, I run it on Ubuntu without Docker: https://apt.authelia.com/stable/debian/packages/authelia/

NGINX Proxy Manager is not required, I use it with NGINX standalone. The docker setup is the most common but it's not required but potentially requires more configuration and experience with command line.

Providing NGINX is your front facing web server for apps, you should be able to use Authelia. It wouldn't work with Apache, but fine if NGINX is proxing an Apache hosted site.

The main authentication backends Authelia has currently are a user file list and LDAP. The identity providers supported is currently OpenID connect as a provider role only currently in beta.

I think you can run Authelia on a separate machine, but any NGINX configuration would need to change from localhost:9091 to the IP/domain of your Authelia server with port 9091 open.

Your Google apps question depends on how you'd authenticate users. If you mean by linking Google identities to Authelia, then probably not currently.

**Comment by Blason** [comment]
Thanks for the detailed explanation and here is my topology that I am
planning to use. However I am confused about nginx configuration since
there is not much documentation found.

And I am planning to use plain file since I have only around 15 users

**Comment by jamesmacwhite** [comment]
No worries, then you should be OK to use Authelia.

The best documentation for NGINX standalone is here: https://www.authelia.com/docs/deployment/supported-proxies/nginx.html. The docker configuration method uses virtually the same configuration.

The setup consists of few parts:

1. Site for Authelia Portal L .e. auth.domain.com
2. Main Authelia configuration (authelia.conf)
3. Auth config for each path or app being protected (auth.conf)
4. Proxy helper configuration for Authelia auth (proxy.conf)

Other than the main Authelia Portal site, you can save the confs as snippets to be included when needed so it's easy to re-use and maintain.

A site that has one or more paths being protected by Authelia needs to have the authelia.conf included in the main server block. The app being protected needs to have `auth.conf` added to the location block.
