### ISSUE TITLE
Unable to register the device and gets error

### ISSUE THREAD

**Issue by Blason** [authelia/authelia#2876]
Hi Team,

I have authelia server and I am trying to authenticate however my first authentication is successful however my other attempt shows an error
Failed to register your security key. The identity verification process might have timed out.

![image](https://user-images.githubusercontent.com/5461807/154117408-e1ab397e-4b81-4553-b82c-717dba53e176.png)

I am behind nginx reverse proxy.

**Comment by james-d-elliott** [comment]
What do the logs say?

**Comment by Blason** [comment]
Thats pretty weird - I enabled the logs
`log:
  level: debug
  format: text
  file_path: /var/log/authelia/authelia.log
  keep_stdout: false
`

And dang it started working fine. Not sure what was the issue.

**Comment by james-d-elliott** [comment]
Probably session related. The browser session that starts registration must finish it. So if you open in different browsers that issue can occur, or if using private browsing.
