### ISSUE TITLE
Unable to bypass two_factor for our nms system

### ISSUE THREAD

**Issue by Blason** [authelia/authelia#2877]
Hi Team,

I have portal test.example.com which is also being monitored by IP address 1.2.3.4 (e.g.). I am trying to bypass the authentication for 1.2.3.4 at the same time two_fa has to be enabled for other users.

Here is my config however debug log says both are not possible at the same time. Any other alternative?

authelia --config /etc/authelia/configuration.yml
ERRO[0000] Configuration: policy [bypass] for rule #2 domain [test.example.com] with subjects [[group:siemadmins]] is invalid. It is not supported to configure both policy bypass and subjects. For more information see: https://www.authelia.com/docs/configuration/access-control.html#combining-subjects-and-the-bypass-policy

    - domain: # Proxies only requiring username and password
        - "test.example.com"
      policy: two_factor
      subject:
        - "group:siemadmins"
            policy: bypass
          networks:
          - 10.122.0.5/32
          - 134.209.xx.xx/32

**Comment by james-d-elliott** [comment]
The appropriate rule if you're using subjects is `one_factor` since there is no way to identify a subject unless they have at least authenticated. Guess I forgot  to update the link: https://www.authelia.com/docs/configuration/access-control.html#bypass

**Comment by Blason** [comment]
I am sorry - If I am not wrong it can not be bypassed and at least I need to use one_factor?

**Comment by james-d-elliott** [comment]
It can, just you can't have subjects set. Subjects are information specific to users, Authelia can't know a users group or  username before they log in. If they're anonymous then their username is blank and groups are empty.

Thus if you want to bypass for anonymous users then set it to bypass, if you want to effectively `bypass` for users who are in specific groups or have specific usernames then set it to `one_factor`, which will absolve them from being required to perform 2FA.

**Comment by Blason** [comment]
Well then I tried for that and after logging in I directly 403 error from nginx reverse proxy and it does not allow to proceed with errors no subject match found.

e.g. This log when I did not have subject set
time="2022-02-16T08:45:32+05:30" level=debug msg="Required level for the URL https://test.example.com/ is 3" method=POST path=/api/firstfactor remote_ip=182.48.207.57
time="2022-02-16T08:45:32+05:30" level=debug msg="Redirection URL https://test.example.com/ is safe" method=POST path=/api/firstfactor remote_ip=182.48.207.57
time="2022-02-16T08:45:33+05:30" level=debug msg="Check authorization of subject username=testuser groups=admins,dev ip=182.48.207.57 and object https://test.example.com/ (method GET)."
time="2022-02-16T08:45:33+05:30" level=debug msg="No matching rule for subject username=testuser groups=admins,dev ip=182.48.207.57 and url https://test.example.com/... Applying default policy."
time="2022-02-16T08:45:33+05:30" level=info msg="Access to https://test.example.com/ is forbidden to user testuser" method=GET path=/api/verify remote_ip=182.48.207.57
time="2022-02-16T08:45:56+05:30" level=debug msg="Check authorization of subject username= groups= ip=134.209.158.117 and object https://test.example.com/login?next=%2F (method GET)."
time="2022-02-16T08:45:33+05:30" level=debug msg="No matching rule for subject username=testuser groups=admins,dev ip=182.48.207.57 and url https://test.example.com/... Applying default policy."
time="2022-02-16T08:45:33+05:30" level=info msg="Access to https://test.example.com/ is forbidden to user manishr" method=GET path=/api/verify remote_ip=182.48.207.57

**Comment by james-d-elliott** [comment]
Mind sharing your full list of rules?

**Comment by Blason** [comment]
This was set when I wanted to bypass nms and internal system so that resource can be monitored

access_control:
  default_policy: deny
  rules:
    - domain: # Proxies only requiring username and password
        - "test.example.com"
      policy: two_factor
      networks:
        - 10.122.0.5/32
        - 134.209.xx.xx/32
###############

And then I had to change it to this however one_factor is not working either

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: # Proxies only requiring username and password
        - "test.example.com"
      policy: two_factor
      subject:
        - "group:siemadmins"
      policy: one_factor
      subject:
        - "group:nms"

**Comment by james-d-elliott** [comment]
Try this instead:

```yaml
access_control:
  default_policy: deny
  - domain: "test.example.com"
    policy: one_factor
    subject:
    - "group:siemadmins"
  - domain: "test.example.com"
    policy: two_factor
```

**Comment by james-d-elliott** [comment]
Assuming your group is admins, and the  domain is test.eample.com. The rule order is important and ensuring the rule actually matches is (in this case siemadmins does not match group admins, and the network policy does not match the users IP so no rule matches).

**Comment by Blason** [comment]
Still no luck - 

time="2022-02-16T09:43:06+05:30" level=debug msg="Check authorization of subject username= groups= ip=134.209.xxx.xxx and object https://test.example.com/login?next=%2F (method GET)."
time="2022-02-16T09:43:06+05:30" level=info msg="Access to https://test.example.com/login?next=%2F (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=134.209.xxx.xxx
time="2022-02-16T09:44:06+05:30" level=debug msg="Check authorization of subject username= groups= ip=134.209.xxx.xxx and object https://test.example.com/login?next=%2F (method GET)."
time="2022-02-16T09:44:06+05:30" level=info msg="Access to https://test.example.com/login?next=%2F (method GET) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=134.209.xxx.xxx

**Comment by Blason** [comment]
Surprisingly - Even 2FA has stopped as well

time="2022-02-16T09:46:50+05:30" level=debug msg="Check authorization of subject username=testuser groups=admins,siemadmins,dev ip=182.48.207.57 and object https://test.example.com/ (method GET)."
time="2022-02-16T09:46:50+05:30" level=debug msg="No matching rule for subject username=testuser groups=admins,siemadmins,dev ip=182.48.207.57 and url https://test.example.com/... Applying default policy."
time="2022-02-16T09:46:50+05:30" level=info msg="Access to https://test.example.com/ is forbidden to user testuser" method=GET path=/api/verify remote_ip=182.48.207.57
time="2022-02-16T09:47:06+05:30" level=debug msg="Check authorization of subject username= groups= ip=134.209.xx.xx and object https://test.example.com/login?next=%2F (method GET)."

**Comment by james-d-elliott** [comment]
Looks to me like potentially the cookie is not being saved. What domain is configured for your cookie?

**Comment by Blason** [comment]
Nope James - I am not; its pretty straight forward config

**Comment by Blason** [comment]
I added subject and my 2fa started working fine.

**Comment by james-d-elliott** [comment]
Adjusting subjects to the two_factor policy I provided is not going to make it work if it wasn't previously. There's something else you changed, or something else wrong in your configuration and the problem will occur again and cause confusion.

> What domain is configured for your cookie?

With the provided examples this needs to be part of your config:

```yaml
session:
  domain: example.com
```
