### ISSUE TITLE
Authelia SSO shows blank page after hitting secure url 

### ISSUE THREAD

**Issue by david1412** [authelia/authelia#2880]
### Description
Authelia SSO shows blank page after changing the ingress manifest with path prefix

### Reproduction Steps

1. I'm working with helm, used the chart repo and configured authelia,LDAP, Traefik. When using root domain for authelia ingress, the SSO login works and re-directs the to secure url.

2. After changing the ingress manifest with path prefix, changed the auth forwarder accordingly but this time the SSO page shows up blank. I checked developer tools as well, as i'm using Firefox i changed the headers according but there is no effect.
-->  we have a domain: fqdn.de
with subpaths : fqdn.de/prometheus and fqdn.de/ grafana > ingress path prefix is set in manifest as /prometheus and / grafana.

3.  For authelia: I used root domain fqdn.de, so, in this case fqdn.de/prometheus and fqdn.de/ grafana is not reachable. As authelia configured without path prefix.( something like /auth) when i hit my secure url > I can see authelia login> provided lDAP user pass > redirects to secure url again - **IT WORKS!** 
  
4. **middleware forward auth address used:** 
_http://authelia.default.svc.cluster.local/api/verify?rd=https:/fqdn.de - IT works ( default=name space, authelia=name )_

5.  Now, i'm trying to configure authelia with path prefix  example : fqdn.de/auth ( as SSO), changed my authelia ingress with path prefix, updated **middleware auth forward and the address used** _http://authelia.default.svc.cluster.local/api/verify?rd=https:/fqdn.de/auth 
6. see middleware.yaml and middleware-regex.yaml below

7. when i hit my secure url > I can see authelia blank page - not worked as expected.
Firefox developer tool debug 
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/30881405/154711521-77262f1f-253d-4ea3-92e8-f4815579b365.png">

### Authelia container logs 

_**time="2022-02-18T15:21:35Z" level=info msg="Access to https://whoami.fqdn.de/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://fqdn.de/**auth/**?rd=https%3A%2F%2Fwhoami.fqdn%2F&rm=GET" method=GET path=/api/verify remote_ip=some IP**_ 

# middleware config
<
# Source: authelia/templates/traefikCRD/middlewares.yaml
kind: Middleware
metadata:
  name: auth
  namespace: default
spec:
  forwardAuth:
    address: http://authelia.default.svc.cluster.local/api/verify?rd=https://fqdn/auth/
    trustForwardHeader: true
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Groups"
      - "Remote-Name"
      - "Remote-Email"
    tls:
      insecureSkipVerify: true
>
---
<
# Source: authelia/templates/traefikCRD/middlewares.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: headers-authelia
  namespace: default
spec:
  headers:
    browserXssFilter: true
    customFrameOptionsValue: "SAMEORIGIN"
    contentTypeNosniff:
      X-Content-Type-Options: "nosniff"
    customResponseHeaders:
      Cache-Control: "no-store"
      Pragma: "no-cache"
> 
---
<
# Source: authelia/templates/traefikCRD/middlewares.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-authelia-auth
  namespace: default
spec:
  chain:
    middlewares:
      - name: auth
        namespace: default
>
---
<
# Source: authelia/templates/traefikCRD/middlewares.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-authelia
  namespace: default
spec:
  chain:
    middlewares:
      - name: headers-authelia
        namespace: default
>
---
<
 # Source: regex

 apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: regex
  namespace: default
spec:
  replacePathRegex:
    regex: ^/auth(.*)
    replacement: /$1
>
    I'm looking for help on this issue.
    Thanks

**Comment by james-d-elliott** [comment]
For authelia to listen on a path you have to change the path value to whatever that is, for example if you want it to listen on fqdn.de/auth then this value must be `auth` https://github.com/authelia/chartrepo/blob/master/charts/authelia/values.yaml#L415

**Comment by james-d-elliott** [comment]
If this doesn't fix it can you please provide your version, by the way.

**Comment by david1412** [comment]
Based on your suggestion i changed the configuration file with path: auth, it works when i hit the url fqdn.de/auth but the secure container is getting 404 error not found. I used pulled Authelia 4.33.2 version. Does this path impact the secure url?

**Comment by david1412** [comment]
I found the issue regarding 404 error or timed out error for secure url.
<
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: default
spec:
  forwardAuth:
    address: http://authelia.default.svc.cluster.local/api/verify?rd=https://fqdn/auth/
    trustForwardHeader: true
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Groups"
      - "Remote-Name"
      - "Remote-Email"
    tls:
      insecureSkipVerify: true
    **X-Content-Type-Options: nosniff** this should be added
>

the blank page error is resolved. We can close the issue. Thanks for your inputs :)

**Comment by david1412** [comment]
I have a query related to access control in configmap:
I have a end point with fqdn.de/prometheus , how can i define in the domain(below)
access_control:
  default_policy: deny
  rules:
    - domain: fqdn.de/prometheus ( does this work?) or i need to adopt different format.
      policy: one_factor
    - domain: fqdn.de
      policy: bypass

**Comment by david1412** [comment]
Solution: 
need to update the secure ingress manifest
<
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"traefik.ingress.kubernetes.io/router.entrypoints":"websecure","traefik.ingress.kubernetes.io/router.middlewares":"default-regex@kubernetescrd,default-auth@kubernetescd
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: **default-regex@kubernetescrd,default-auth@kubernetescrd** I'm using 2 middlewares
    traefik.ingress.kubernetes.io/router.tls: "true"
  creationTimestamp: "2022-02-21T08:57:46Z"
  generation: 1
  name: whoami
  namespace: default
  resourceVersion: "1254775"
  uid: 8b8a8f89-e937-4e37-a3a9-9da360ee2260
spec:
  rules:
  - host: fqdn.de
    http:
      paths:
      - backend:
          service:
            name: whoami
            port:
              number: 80
        path: /whoami
        pathType: Prefix
  tls:
  - secretName: m-tls
>

configuation.yaml

<
access_control:
  default_policy: deny
  rules:
    - domain: fqdn.de  >> fqdn.de/whoami ( whoami is my sub path)
      resources:
        - '^/whoami.*$'
      policy: one_factor
    - domain: fqdn.de
      policy: one_factor

>
@james-d-elliott  thanks for your help. 
Authelia with Integration works perfectly.

**Comment by david1412** [comment]
Syntax issue with access control for sub path & syntax format adopted for middle ware annotation for whoami ingress - Issues solved.
