### ISSUE TITLE
Authelia is not displaying the expected remote_ip in logs

### ISSUE THREAD

**Issue by keelerad** [authelia/authelia#2888]
We are deploying Authelia using helm into a Kubernetes cluster, that has traefik already installed, to allow Authelia to authenticate against Active Directory before it gets forwarded to the required service in the cluster

I have got the Authentication working with Active Directory OK and we were seeing the expected behaviour when trying to link to the required services
We use traefik in its auto discovery form where new services register themselves with traefik when they are added
To get the new service to use Authelia was pretty simple once we had enabled traefikCRD, we just had to add the annotation for the forwardauth middleware to the services helm deployment

e.g.
```
      ingress:
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: k8s-ingress-forwardauth-authelia@kubernetescrd 
```
So all was going great until I tried to use the network rules to define source IPs within the cluster should bypass Authelia (we have ansible that smoketests services by trying to access the entry URL for the service to see if its up, these got broken when rather than the expected 200 HTTP response, they got Authelia doing what its supposed to do and insisting on authentication)

So having defined a network rule that allowed a bypass if the remote_ip was in the cluster found that it worked as expected and bypassed Authelia
But then when checking an external access did use Authelia for authentication found that it also bypassed Authelia?

So looked at the IPs that the Authelia logs were reporting for the remote_ip and they never seem to change based on where the request came from, it is always the IP of the kubernetes node that Authelia/Traefik are running on

Is there possibly some config maybe enabling forwarding of original request headers that I need to do either in Traefik or Authelia?

I found the page https://www.authelia.com/docs/deployment/supported-proxies/traefik2.x.html that had the lines 
`     - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'` mentioned

Aaha I thought that will be it but when I go and check the config for the authelia forwardauth middleware it seems to already be set ?

```
spec:
  forwardAuth:
    address: http://authelia.k8s-ingress.svc.cluster.local/api/verify?rd=https://auth.<ourdomain>/
    authResponseHeaders:
    - Remote-User
    - Remote-Name
    - Remote-Email
    - Remote-Groups
    trustForwardHeader: true
```
Any tips on what else I might be missing ?

The core of the issue is that Authelia is seeing (at least its reporting in the logs) the same remote_ip for all connections

**Comment by keelerad** [comment]
This is the log output when I tried to connect (this is without the rules configured for networks) but it always shows the remote_ip as being 172.16.92.11 which is the IP of the kubernetes node that traefik/authelia are running on not the IP that I was trying to connect from
```
time="2022-02-21T16:41:31Z" level=trace msg="Computed user filter is (&(|(sAMAccountName=adk)(mail=adk))(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(pwdLastSet=0)))"
time="2022-02-21T16:41:31Z" level=debug msg="Mark 1FA authentication attempt made by user 'adk'" method=POST path=/api/firstfactor remote_ip=172.16.92.11
time="2022-02-21T16:41:31Z" level=debug msg="Successful 1FA authentication attempt made by user 'adk'" method=POST path=/api/firstfactor remote_ip=172.16.92.11
time="2022-02-21T16:41:31Z" level=trace msg="Computed user filter is (&(|(sAMAccountName=adk)(mail=adk))(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(pwdLastSet=0)))"
time="2022-02-21T16:41:31Z" level=trace msg="Profile details for user 'adk' => groups: [<My groups>], emails [<my e-mail>]" method=POST path=/api/firstfactor remote_ip=172.16.92.11
```

**Comment by keelerad** [comment]
I notice that the AUthelia helm deployment also deployed some other middleware including one called headres-authelia, does this need to configured to run before the forwardauth as well ? Can't seem to find any docs that list what each of these middleware provide

![image](https://user-images.githubusercontent.com/13383443/155007064-b1407c04-2a26-49ae-be66-d19647e8c62a.png)

**Comment by james-d-elliott** [comment]
The issue is traefik is not getting the correct IP to add to X-Forwareded-For. There are several causes for this, some of them listed below:

- Additional proxies in front of traefik that are not trusted by traefik
- NAT forwarding rules to traefik hiding the Remote IP (for k8s with metallb see [externalTrafficPolicy](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip))
- the request not going directly to the server due to DNS settings

**Comment by keelerad** [comment]
Thanks for the info I'll start looking at traefik

Alec

**Comment by keelerad** [comment]
Yep found that the traefik service had been deployed with externalTrafficPolicy set to `Cluster`, changed it to use `Local` and now Authelia can see the originator IP, thanks for the tip

Alec
