### ISSUE TITLE
[Feature Request] Possibility to disable U2F/TOTP

### ISSUE THREAD

**Issue by bkupidura** [authelia/authelia#2889]
### Description

In some environments (e.g home ;)) we have knowledge about second auth factor which will be used by users. It would be nice if we could disable any other factor.

Currently only DUO can be enabled/disabled from config file.

### Use Case

Im using Authelia to protect services in my home K8s cluster. We dont own any U2F token, so for sure nobody will be using it. I would like to have possibility to disable U2F completly.

I can image situation where all users owns U2F tokens, and Authelia owner would like to disable TOTP.

**Comment by james-d-elliott** [comment]
You can disable all 2FA methods already by only having one_factor policy rules.

**Comment by bkupidura** [comment]
@james-d-elliott I dont want to disable all 2FA. I want to use password+TOTP, but disable U2F only. Is this possible?

**Comment by james-d-elliott** [comment]
No that is not possible. I can look at adding that to the webauthn PR which will replace U2F.
