### ISSUE TITLE
Restarting  58 seconds ago

### ISSUE THREAD

**Issue by heikafeiylt** [authelia/authelia#2914]
CentOS Linux release 8.5.2111
Docker version 20.10.12, build e91ed57
docker-compose version 1.25.3, build d4d1b42b

Run：
git clone https://github.com/authelia/authelia.git
cd authelia/examples/compose/lite
git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
Modify the users_database.yml the default username and password is authelia
Modify the configuration.yml and docker-compose.yml with your respective domains and secrets
docker-compose up –d

But It’s not working, it’s Constant restarting

**Comment by james-d-elliott** [comment]
Could you provide logs please? It's a bit difficult to diagnose when the instructions were tested as working and you provide such little information.
