### ISSUE TITLE
Inconsistent Default Configuration File Name in Docker and `authelia` Command

### ISSUE THREAD

**Issue by LazyGeniusMan** [authelia/authelia#2939]
### Description

Default file name for configuration file in docker container and `authelia` command is not consistent, the docs said
> Docker
> By default, the container looks for a configuration file at /config/configuration.yml. This can be changed using the command setting.

but for example  `authelia storage totp export` command help output said:
> Usage:
> authelia storage totp export [flags]
>
>Flags:
>      --format string   sets the output format (default "uri")
>  -h, --help            help for export
>
>Global Flags:
>  -c, --config strings                         configuration file to load for the storage migration (default [config.yml])

This make user has to specify the config file in the export command eventhough they are using default file name for docker.

Not big of a deal but would be a nice QoL if it's consistent IMHO.

### Expected Behaviour

User can run `authelia storage totp export` command without specifying config file name when using docker default config filename

### Reproduction Steps
1. Deploy based on `Lite` Example
2. Go into container terminal
3. run `authelia storage totp export`

### Additional Information

```
/app # authelia build-info
Last Tag: v4.33.2
State: tagged clean
Branch: v4.33.2
Commit: 8d5a29117ea3111f8dab9cc1268671bee8eee63c
Build Number: 9043
Build OS: linux
Build Arch: amd64
Build Date: Fri, 21 Jan 2022 15:35:11 +1100
Extra:
/app # ls /config
configuration.yml   db.sqlite3          notification.txt    users_database.yml
/app # authelia storage totp export
Error: storage: configuration for a 'local', 'mysql' or 'postgres' database must be provided, storage: 'encryption_key' configuration option must be provided
```

**Comment by james-d-elliott** [comment]
This is not a bug, was done intentionally so the default is to look for a file in the PWD. A container is not the only potential way for someone to deploy authelia.

If someone can think of a reasonable way that can work for both containers and for a local bin then we can look at implementing it. I may have an idea but will just have to mull it over.

**Comment by LazyGeniusMan** [comment]
It's fine if it's stays search in PWD but make `authelia` command and docker deployment search the same default filename. Right now, docker deployment search for `configuration.yml` by default but `authelia` command search for `config.yml`. 

Well, I can just use command in docker compose to change config name so it's matched with `authelia` command but it's just kinda weird having different default config name. So my suggestion is either make docker deployment search for `config.yml` or make `authelia` command search for `configuration.yml`

As you can see if I make `config.yml`, the command automatically use the config file, but then I have to state the config file path in docker cli/compose. If the default filename is consistent this wouldn't be necessary.
```
/config # ls
configuration.yml           db.sqlite3                  users_database.yml
configuration.yml.example   notification.txt            users_database.yml.example
/config # authelia storage totp export
Error: storage: configuration for a 'local', 'mysql' or 'postgres' database must be provided, storage: 'encryption_key' configuration option must be provided
/config # cp configuration.yml config.yml
/config # authelia storage totp export
otpauth://...
```

Or I'm missunderstood something?
