### ISSUE TITLE
Unable to configure the MFA for one of my portal running behind Nginx

### ISSUE THREAD

**Issue by Blason** [authelia/authelia#2944]
Hi Team,

I already have few portals running with Authelia and those are working fine. However I am going to configure Authelia for one Portal which has Indexes enabled and whenever I disabled the proxy setting from my nginx.conf file the portal works fine and when I activate it gives me error 

Bad Request
Your browser sent a request that this server could not understand.

And here is my setting for Nginx and proxy.conf file

```nginx
server {
        listen 443 http2 ssl;
        server_name  fs.example.com;
        ssl_protocols  TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
        ssl_certificate           /etc/nginx/ssls/isncert/wild.crt;
        ssl_certificate_key   /etc/nginx/ssls/isncert/prv.key;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
        ssl_dhparam /etc/ssl/dhparams2048.pem;
        ssl_session_timeout 1d;
        ssl_session_tickets off;
        ssl_stapling on;
        ssl_stapling_verify on;
        resolver 8.8.8.8 8.8.4.4 valid=300s;
        include /config/nginx/authelia.conf;
        access_log /var/log/nginx/fs/access.log;
        error_log /var/log/nginx/fs/error.log;
location / {
        client_max_body_size    10m;
        #proxy_headers_hash_max_size 512;
        proxy_headers_hash_bucket_size 128;
        proxy_busy_buffers_size 256k;
        proxy_temp_file_write_size 256k;
        proxy_buffers     4 256k;
        proxy_buffer_size  16k;
        proxy_pass http://fs.example.com;
        proxy_set_header   Host   $host;
        proxy_set_header   X-Real-IP  $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
       add_header X-Content-Type-Options nosniff;
       add_header X-XSS-Protection "1; mode=block";
       add_header Referrer-Policy "no-referrer-when-downgrade";
       add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        include /config/nginx/auth.conf;
       include /config/nginx/restconfig.conf;
        }
}
```

```nginx
client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 360;
proxy_send_timeout 360;
proxy_connect_timeout 360;

# Basic Proxy Config
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
#proxy_buffers 64 256k;

# If behind reverse proxy, forwards the correct IP
set_real_ip_from 10.0.0.0/8;
set_real_ip_from 172.16.0.0/12;
set_real_ip_from 192.168.0.0/16;
set_real_ip_from fc00::/7;
real_ip_header X-Forwarded-For;
real_ip_recursive on;
```

**Comment by Blason** [comment]
Thanks James - Appreciate it for formatting. I was looking to format it correctly but didnt find the way.

**Comment by Blason** [comment]
Here is  portal looks like when Authelia is enabled.

![image](https://user-images.githubusercontent.com/5461807/156551015-9d6536ce-cca6-4af5-aaf3-1db8b3b5245b.png)

here are the logs from authelia

time="2022-03-03T16:24:05+05:30" level=debug msg="Check authorization of subject username=xxxxx groups=admins,siemadmins,employees ip=203.xxx.xx.xx and object https://fs.example.com/ (method GET)."

And Nginx logs

203.xxx.xx - - [03/Mar/2022:16:24:05 +0530] "GET / HTTP/2.0" 400 226 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
203.xxx.xxx - - [03/Mar/2022:16:28:39 +0530] "GET / HTTP/2.0" 200 401 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"

And here I disabled the Authelia

`server {
        listen 443 http2 ssl;
        server_name  fs.example.com;
        ssl_protocols  TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
        ssl_certificate           /etc/nginx/ssls/isncert/wild.crt;
        ssl_certificate_key   /etc/nginx/ssls/isncert/priv.key;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
        ssl_dhparam /etc/ssl/dhparams2048.pem;
        ssl_session_timeout 1d;
        ssl_session_tickets off;
        ssl_stapling on;
        ssl_stapling_verify on;
        resolver 8.8.8.8 8.8.4.4 valid=300s;
#        include /config/nginx/authelia.conf;
        access_log /var/log/nginx/fs/access.log;
        error_log /var/log/nginx/fs/error.log;
location / {
        client_max_body_size    10m;
        #proxy_headers_hash_max_size 512;
        proxy_headers_hash_bucket_size 128;
        proxy_busy_buffers_size 256k;
        proxy_temp_file_write_size 256k;
 `

And here is when Authelia is disabled

![image](https://user-images.githubusercontent.com/5461807/156551632-0b4d55a9-ef43-4c86-b9eb-7483e220ef82.png)

**Comment by james-d-elliott** [comment]
Which example are you using? Because there are missing parts from the official example. You're missing something, show me the content of `/config/nginx/authelia.conf`.

**Comment by Blason** [comment]
I fact rest of my portals are running fine with the same settings. This is the one is causing an issue

`set $upstream_authelia http://10.122.0.8:9091/api/verify;

# Virtual endpoint created by nginx to forward auth requests.
location /authelia {
    internal;
    proxy_pass_request_body off;
    proxy_pass $upstream_authelia;
    proxy_set_header Content-Length "";

    # Timeout if the real server is dead
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

    # [REQUIRED] Needed by Authelia to check authorizations of the resource.
    # Provide either X-Original-URL and X-Forwarded-Proto or
    # X-Forwarded-Proto, X-Forwarded-Host and X-Forwarded-Uri or both.
    # Those headers will be used by Authelia to deduce the target url of the user.
    # Basic Proxy Config
    client_body_buffer_size 128k;
    proxy_set_header Host $host;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Method $request_method;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;

    # Advanced Proxy Config
    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}
`

**Comment by james-d-elliott** [comment]
You never showed a config that includes this: https://www.authelia.com/docs/deployment/supported-proxies/nginx.html#authconf

**Comment by james-d-elliott** [comment]
What does `/config/nginx/auth.conf`  and  `/config/nginx/restconfig.conf` look like?

**Comment by Blason** [comment]
Well fs.example.com is on my Apache server which is 10.122.0.4 while my Nginx proxy is 10.122.0.3. 10.122.0.3 is my Reverse Prxy

**Comment by Blason** [comment]
```
# Basic Authelia Config
# Send a subsequent request to Authelia to verify if the user is authenticated
# and has the right permissions to access the resource.
auth_request /authelia;
# Set the `target_url` variable based on the request. It will be used to build the portal
# URL with the correct redirection parameter.
auth_request_set $target_url $scheme://$http_host$request_uri;
# Set the X-Forwarded-User and X-Forwarded-Groups with the headers
# returned by Authelia for the backends which can consume them.
# This is not safe, as the backend must make sure that they come from the
# proxy. In the future, it's gonna be safe to just use OAuth.
auth_request_set $user $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
auth_request_set $name $upstream_http_remote_name;
auth_request_set $email $upstream_http_remote_email;
proxy_set_header Remote-User $user;
proxy_set_header Remote-Groups $groups;
proxy_set_header Remote-Name $name;
proxy_set_header Remote-Email $email;
# If Authelia returns 401, then nginx redirects the user to the login portal.
# If it returns 200, then the request pass through to the backend.
# For other type of errors, nginx will handle them as usual.
error_page 401 =302 https://mfa.example.com/?rd=$target_url;
```
And
```
more nginx/restconfig.conf
client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 360;
proxy_send_timeout 360;
proxy_connect_timeout 360;

# Basic Proxy Config
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
#proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
#proxy_buffers 64 256k;

# If behind reverse proxy, forwards the correct IP
set_real_ip_from 10.0.0.0/8;
set_real_ip_from 172.16.0.0/12;
set_real_ip_from 192.168.0.0/16;
set_real_ip_from fc00::/7;
real_ip_header X-Forwarded-For;
real_ip_recursive on;
```

**Comment by Blason** [comment]
That is correct. However when I stop MFA portal works fine and when I enable I get this error. Hence I am sure this is related to Authelia

**Comment by james-d-elliott** [comment]
Since there are no error/warnings in Authelia the problem most likely exists before it makes it to Authelia in actual fact. We do not reply with a HTTP 400 Bad Request in any of our endpoints except for OIDC which is unrelated.

Your nginx logs should have more information or Authelia logs should have more information that could help, but either your nginx error logs are filtering a lot of errors or  you didn't provide them and you just provided access logs maybe?

**Comment by Blason** [comment]
Hello,

In fact no error logs are appearing for Nginx.

root@waf:~# tail -f /var/log/nginx/fs/error.log

```

103.153.225.95 - - [03/Mar/2022:17:18:38 +0530] "GET / HTTP/2.0" 400 226 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
```

And no apache logs on my apache server neither error or access.

**Comment by james-d-elliott** [comment]
The only other place errors could be is in the browser, or there is missing logs either  via you not providing them or some setting  or situation preventing the log messages from appearing where you'd expect.

My guess is you have a global error_log and that's where the log messages are, however I can't say for certain how nginx handles that.

**Comment by Blason** [comment]
This is the complete debug file collected from Nginx

https://pastebin.com/K3521Cnk

**Comment by Blason** [comment]
Well one thing bothers me is - If I remove the Authelia config same setup works fine and If I enable I do get this error. From debug logs I observed that "/?" is being sent which server does not like?

**2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 http upstream request: "/?"**
2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 http upstream process header
2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 malloc: 000055FB6EAD9340:16384
2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 recv: eof:0, avail:-1
2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 recv: fd:6 392 of 16384
2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 http proxy status 400 "400 Bad Request"
2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 http proxy header: "Date: Thu, 03 Mar 2022 18:44:14 GMT"
2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 http proxy header: "Server: Apache"
2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 http proxy header: "Content-Length: 226"
2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 http proxy header: "Connection: close"
2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 http proxy header: "Content-Type: text/html; charset=iso-8859-1"

And this is what the header looks like
```
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="99", "Google Chrome";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: none
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
```

**Comment by james-d-elliott** [comment]
Yeah, and that request is not being made to Authelia, it's being made to the Apache server. Not the bad request with ID 1894982 or 84557 is the HTTP 400 Bad Request, and one of the headers for that request is `Server: Apache`. That is not a header Authelia sets.

2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 http proxy status 400 "400 Bad Request"
2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 http proxy header: "Date: Thu, 03 Mar 2022 18:44:14 GMT"
2022/03/04 00:14:14 [debug] 1894982#1894982: *84557 http proxy header: "Server: Apache"

**Comment by james-d-elliott** [comment]
I'm assuming you solved this, it would be good to post  your solution, or if you've not maybe jump in the chat?
