### ISSUE TITLE
Cannot register SoloKeys 2 as webauthn device in 4.34.1

### ISSUE THREAD

**Issue by HubbeKing** [authelia/authelia#2956]
### Description
The new webauthn support added in 4.34.0 does not work with all keys - the public key length for webauthn devices is set too short in the table definitions.
I have one of the new SoloKeys 2 keys, currently being shipped to kickstarter backers. Attempting to register it with Authelia throws an error, looking at the container logs reveals the following:
```
time="2022-03-04T07:42:09Z" level=error msg="Unable to load Webauthn devices for assertion challenge for user 'hubbe': error upserting Webauthn device for user 'hubbe' kid '<REDACTED>': Error 1406: Data too long for column 'kid' at row 1" method=POST path=/api/secondfactor/webauthn/attestation
```

The redacted `kid` value is a an alphanumeric string, 496 characters long. I suspect this is due to a differing key algorithm in the SoloKeys 2, but I am not entirely certain. Documentation for it is open source, available at https://github.com/solokeys/solo2

I have unfortunately not been able to reproduce the issue with another device, I can register both my YubiKey 5 and my SoloKeys 1 device without issue.
### Expected Behaviour

Authelia should support Webauthn devices with longer public keys. I am uncertain if the specification for Webauthn specifies a maximum length, but evidently keys do exist with lengths > VARCHAR(100)

### Reproduction Steps

1. Attempt to log in to 2FA protected endpoint
2. Try to register a security key
3. Plug in SoloKeys 2 or other key using the same public key algorithm(s?) it does
4. Observe failure

### Additional Information

Known working keys:
- Yubikeys 5C
- Yubikeys 5 NFC
- SoloKeys 1 (https://github.com/solokeys/solo)

Known not working keys:
- SoloKeys 2 (https://github.com/solokeys/solo2)

**Comment by james-d-elliott** [comment]
Interesting, did they work pre-Webauthn?

**Comment by HubbeKing** [comment]
Yes, the SoloKeys 2 works on the 4.33.x releases without issue.

**Comment by james-d-elliott** [comment]
I'm preparing a fix now in the linked PR, seems super strange since we had the same length back then, guessing they're using a differing algo for it FIDO2 as you suggest.

If they were previously registered via U2F they should still work as well, can you confirm if this is the case?

**Comment by HubbeKing** [comment]
My attempt to upgrade authelia from `4.33.2` to `4.34.1` or `fix-webauthn-kid-len` threw an error, unfortunately.
```
time="2022-03-04T08:44:15Z" level=error msg="Failure running the storage provider startup check: error during schema migrate: error applying migration version 2 to version 1 for rollback: schema migration 2 (Webauthn) failed: Error 1050: Table '_bkp_DOWN_V0002_totp_configurations' already exists. rollback caused by: schema migration 2 (Webauthn) failed: Error 1050: Table '_bkp_UP_V0002_totp_configurations' already exists"
```

Which seems... very very strange. I'm gonna restore some backups from yesterday and check with those.

**Comment by HubbeKing** [comment]
Looking at the `u2f_devices` table on an authelia `4.33.2` install shows that the `public_key` column is of type `blob`
```
MariaDB [authelia]> describe u2f_devices;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| username    | varchar(100) | NO   | MUL | NULL    |                |
| description | varchar(30)  | NO   |     | Primary |                |
| key_handle  | blob         | NO   |     | NULL    |                |
| public_key  | blob         | NO   |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
```

Attempting to upgrade to `fix-webauthn-kid-len` with the SoloKeys 2 registered there throws this error:
```
time="2022-03-04T08:54:42Z" level=error msg="Failure running the storage provider startup check: error during schema migrate: migration rollback complete. rollback caused by: schema migration 2 (Webauthn) failed: Error 1406: Data too long for column 'kid' at row 1"
```

I guess the previous error was just from a failed prior migration?

**Comment by james-d-elliott** [comment]
The public key is a blob in the migration too. Also yeah we left that migration table there as a backup incase people need to revert, name _bkp_UP_V0002_totp_configurations to anything else, or delete it, same with _bkp_UP_V0002_u2f_devices. It's just so if the data is mangled in the migration it shouldn't be lost.

**Comment by james-d-elliott** [comment]
Oh! You meant the key_handle (equivalent to kid), that is true it was a blob, interesting. Was  sure it was a VARCHAR 100.

**Comment by james-d-elliott** [comment]
@HubbeKing I fixed the issues with the fix, can you give it another shot? If you need help with the tables, the ones that may need a rename or DROP start with _bkp.

**Comment by HubbeKing** [comment]
Okay, the migration from schema v1 to v3 worked with the SoloKeys 2 registered, and the SoloKeys 2 now works correctly.
Using the "Lost your device?" function to re-register the SoloKeys 2 also works.

**Comment by james-d-elliott** [comment]
Awesome. I fixed the v2 migration too, which will solve that strange issue you had. the v3 migration is basically a meta migration for anyone already on v2.
