### ISSUE TITLE
Password reset email LDAP FreeIPA password update error. LDAP error code 13.

### ISSUE THREAD

**Issue by chanrwm** [authelia/authelia#2961]
New to Authelia and just finished setup behind a SWAG/nginx proxy docker and FreeIPA LDAP server VM and hoping to get some help here. Authentication works fine users but on the password reset, I get a "There was an issue resetting the password" pop up. Looking at the logs there appears to be a token reuse problem and the LDAP server is requesting a secure connection for the password update operation. The LDAP server is behind my firewall and nginx and I do not have the certificate_directory or tls sections filled out in my configuration.yml. Also have a Nextcloud docker installed and it is able to update the password in LDAP. The documentation for that system it says the LDAP password update is transmitted in plain text. 

Just a little lost here and not sure what is going on. Is the problem I'm seeing here because Authelia trying to send an LDAP password update via TLS when I don't have any certs set in the config? I've tried setting the /certificates_directory in the config and dropping my public SWAG generated cert PEM files in the directory but I got an error adding those in so far. Is there a way around this or is it possible to use a different LDAP operation (i.e. nextcloud plain text password update, not sure what that is doing) so this error doesn't trip off?  Or should I be trying to set up the certs for Authelia instead? Thanks!

Logs errors:
> `time="2022-03-03T18:38:59-07:00" level=error msg="Token is not in DB, it might have already been used" method=POST path=/api/reset-password/identity/finish remote_ip=ip stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:61 (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/middlewares/identity_verification.go:188 IdentityVerificationFinish.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:52 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.5/router.go:414 (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14 LogRequestMiddleware.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/strip_path.go:21 StripPathMiddleware.func1\ngithub.com/valyala/fasthttp@v1.32.0/server.go:2298 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.32.0/workerpool.go:223 (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.32.0/workerpool.go:195 (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581 goexit"
> 
> time="2022-03-03T18:39:02-07:00" level=error msg="unable to update password. Cause: LDAP Result Code 13 \"Confidentiality Required\": Operation requires a secure connection.\n" method=POST path=/api/reset-password remote_ip=ip stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:61 (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/handlers/handler_reset_password_step2.go:38 ResetPasswordPost\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:52 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.5/router.go:414 (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14 LogRequestMiddleware.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/strip_path.go:21 StripPathMiddleware.func1\ngithub.com/valyala/fasthttp@v1.32.0/server.go:2298 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.32.0/workerpool.go:223 (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.32.0/workerpool.go:195 (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581 goexit"`

My configuration.yml

> `server:
>   host: 0.0.0.0
>   port: 9091
>   path: "authelia"
>   read_buffer_size: 4096
>   write_buffer_size: 4096
>   enable_pprof: false
>   enable_expvars: false
>   disable_healthcheck: false
>   tls:
>     key: ""
>     certificate: ""
> 
> log:
>   level: info
> 
> authentication_backend:
>   disable_reset_password: false
>   refresh_interval: 5m
>   ldap:
>     implementation: custom
>     url: ldap://192.168.1.180
>     start_tls: false
>     tls:
>       skip_verify: false
>       minimum_version: TLS1.2
>     base_dn: dc=domain,dc=com
>     username_attribute: uid
>     additional_users_dn: cn=users,cn=accounts
>     users_filter: (&({username_attribute}={input})(objectClass=person))
>     additional_groups_dn: cn=groups,cn=accounts
>     groups_filter: (&(member=uid={input},cn=users,cn=accounts,dc=domain,dc=com)(objectclass=groupofnames))
>     group_name_attribute: cn
>     mail_attribute: mail
>     display_name_attribute: givenName
>     user: uid=admin,cn=users,cn=accounts,dc=domain,dc=com
>     password: "password"`

**Comment by james-d-elliott** [comment]
FreeIPA is configured to require LDAPS for password resets from what I can tell, their error is just not overly helpful.

**Comment by chanrwm** [comment]
My Nextcloud docker doesn't have any certs set up there either tho so it must be doing a different password update operation that doesn't require LDAPS. Yea going through FreeIPA its a little confusing where I can change the config.

**Comment by james-d-elliott** [comment]
My guess is they are modifying the attribute directly instead of using the Password Modify extended operation (OID 1.3.6.1.4.1.4203.1.11.1). Generally this is not a good idea as the password may not be properly hashed or have the password policies apply.

**Comment by chanrwm** [comment]
You are right James, nextcloud does not hash or check the password policies when the per user password change is set. So is the proper way to do this to get the self-signed certs that IPA installed with (Like the ones in /var/lib/ipa/certs) or to generate a new set using certmonger, and put them in the authelia docker certificates_directory?

**Comment by james-d-elliott** [comment]
Yep, you need to place the certificate that FreeIPA uses and put it in a directory specified by  that option or disable check in the tls section, I recommend the certificate.

**Comment by chanrwm** [comment]
Yea that's what I did, I pulled the httpd.crt from /var/lib/ipa/certs and put it in the /config/certificates on the Authelia docker. I checked from the docker the crt was readable with cat /config/certificates/httpd.crt loading properly and it wasn't some symbolic link. I set the server_name and skip_verify:true. Tried without server_name and that didn't work either, still getting the same LDAP 13.  Same error as before.  Is there a naming format I need to follow so the crt gets used?

>```
cat /config/certificates/httpd.crt
 -----BEGIN CERTIFICATE-----
MIIFMzCCA5ugAwIBAgIBCTAN.....
```

My updated configuration.yml:
```
certificates_directory: /config/certificates
server:
  host: 0.0.0.0
  port: 9091
  path: "authelia"
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: info

totp:
  issuer: domain.com
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  ldap:
    implementation: custom
    url: ldap://192.168.1.180
    start_tls: false
    tls:
      server_name: ipa.domain.com
      skip_verify: true
      minimum_version: TLS1.2
    base_dn: dc=domain,dc=com
    username_attribute: uid
    additional_users_dn: cn=users,cn=accounts
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: cn=groups,cn=accounts
    groups_filter: (&(member=uid={input},cn=users,cn=accounts,dc=domain,dc=com)(objectclass=groupofnames))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: givenName
    user: uid=admin,cn=users,cn=accounts,dc=domain,dc=com
    password: password
```

**Comment by james-d-elliott** [comment]
What was the error?

**Comment by chanrwm** [comment]
Exactly the same as before. Token not in DB errors then LDAP 13. 

>``` time="2022-03-04T18:36:48-07:00" level=info msg="Listening for non-TLS connections on '0.0.0.0:9091' paths '/' and '/authelia'"
> time="2022-03-04T18:37:16-07:00" level=error msg="Token is not in DB, it might have already been used" method=POST path=/api/reset-password/identity/finish remote_ip=ipstack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:61 (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/middlewares/identity_verification.go:188 IdentityVerificationFinish.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:52 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.5/router.go:414 (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14 LogRequestMiddleware.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/strip_path.go:21 StripPathMiddleware.func1\ngithub.com/valyala/fasthttp@v1.32.0/server.go:2298 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.32.0/workerpool.go:223 (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.32.0/workerpool.go:195 (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581 goexit"
> 
> time="2022-03-04T18:37:19-07:00" level=error msg="Token is not in DB, it might have already been used" method=POST path=/api/reset-password/identity/finish remote_ip=ip stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:61 (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/middlewares/identity_verification.go:188 IdentityVerificationFinish.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:52 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.5/router.go:414 (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14 LogRequestMiddleware.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/strip_path.go:21 StripPathMiddleware.func1\ngithub.com/valyala/fasthttp@v1.32.0/server.go:2298 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.32.0/workerpool.go:223 (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.32.0/workerpool.go:195 (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581 goexit"
> 
> time="2022-03-04T18:37:19-07:00" level=error msg="unable to update password. Cause: LDAP Result Code 13 \"Confidentiality Required\": Operation requires a secure connection.\n" method=POST path=/api/reset-password remote_ip=ip stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:61 (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/handlers/handler_reset_password_step2.go:38 ResetPasswordPost\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:52 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.5/router.go:414 (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14 LogRequestMiddleware.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/strip_path.go:21 StripPathMiddleware.func1\ngithub.com/valyala/fasthttp@v1.32.0/server.go:2298 (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.32.0/workerpool.go:223 (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.32.0/workerpool.go:195 (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581 goexit"```

**Comment by james-d-elliott** [comment]
Did you update the LDAP provider URL to `ldaps://`? It's FreeIPA complaining about the lack of TLS not Authelia, because you were not using an LDAPS connection.

**Comment by chanrwm** [comment]
I left it the same since I thought Authelia was going to do a retry and upgrade to ldaps when it needed to for some reason. Changing it worked. Thanks so much James!

**Comment by james-d-elliott** [comment]
No worries, enjoy and let us know if you have other issues.
