### ISSUE TITLE
Remember me checkbox if duration equal 0

### ISSUE THREAD

**Issue by GeoCookie** [authelia/authelia#2978]
Hi there,

It seemed to me that if option `remember_me_duration` was set to 0, the "Remember me" checkbox was not visible on the login screen. Did I dream of this ?

Currently, it is visible
![image](https://user-images.githubusercontent.com/43962716/157240368-6f097fd4-9127-4d13-8ec6-d3f82dea3151.png)

![image](https://user-images.githubusercontent.com/43962716/157240413-d7ec5fa3-02a9-4cdf-bc52-d290320df853.png)

As always, thank you for your hard work.

**Comment by james-d-elliott** [comment]
No you did not and it did change, just it wasn't documented initially and actually was not documented in a recent change which inadvertently required it to be set to `-1` to disable it. I'll document that change now.

**Comment by GeoCookie** [comment]
I saw your edit on the website documentation. Thank you

On my side, I changed the value of Remember_me_duration to `-1` but I still see the "Remember me" option. I don't see anything about it in the trace logs. Any idea ?

PS : It is still the old value on config.template.yml file
![image](https://user-images.githubusercontent.com/43962716/157444144-8377d3a1-00fa-4970-89bc-649a7d7078bf.png)

**Comment by james-d-elliott** [comment]
I'll take a look, seems strange that doesn't work based on what changed.

**Comment by james-d-elliott** [comment]
Oh I see why. Easily fixed.

**Comment by ToqQrrl** [comment]
Hello ... i've commented in #2985 and openned a new issue for this (#2996).
