### ISSUE TITLE
Version 4.34.4 : I can not disable "Remember Me" although the remember_me_duration value is set to -1

### ISSUE THREAD

**Issue by ToqQrrl** [authelia/authelia#2996]
It would seem that the WebUI is still showing the "Remember Me" checkbox and I can not disable "Remember Me" although the remember_me_duration value is set to -1 in the "session" section of the configuration.yml file.

I'm on version 4.34.4.

I have tried it on more that one computer in case it was a cache issue but it is not.

_Originally posted by @ToqQrrl in https://github.com/authelia/authelia/issues/2985#issuecomment-1065915355_

**Comment by Magelo** [comment]
I have the same issue with "Remember Me". on version 4.34.4 too.

**Comment by james-d-elliott** [comment]
Strange that this didn't fix it, let me take a closer look

**Comment by james-d-elliott** [comment]
Can you try: `authelia/authelia:fix-remember-me-disable`

**Comment by Magelo** [comment]
using "remember_me_duration: -1" and authelia/authelia:fix-remember-me-disable

the checkbox "Remember Me" is now removed. In other words, it's working as configured.

**Comment by james-d-elliott** [comment]
No worries, and sorry that the original fix didn't resolve it! I'll look at merging this today along with another fix.

**Comment by ToqQrrl** [comment]
Thank you James for your support ... good work my friend !
