### ISSUE TITLE
One-Time password device registration is showed even when it's disabled

### ISSUE THREAD

**Issue by aureq** [authelia/authelia#2998]
### Description

I've deployed Authelia `4.34.4` via Helm `authelia-0.8.15`. I've disable TOTP and WebAuthn is enabled. The backend user database is OpenLDAP.

I went to setup a new user and was welcomed with the usual login/password form. The login details were accepted as expected and I was able to proceed to the next screen.

On the next screen, and despite TOTP being disable, the default device registration option showed is One-Time Password. Upon clicking on the `Methods` link, only `Security-Key | Webauthn` is available as expected.

![image](https://user-images.githubusercontent.com/1161681/158039701-5593cc47-7b35-4ae8-914c-31057a5d38ed.png)

### Expected Behaviour

If TOTP is disabled then device registration method should default to Webauthn. Maybe the `Methods` link should also be hidden since there's only 1 method available.

### Reproduction Steps

1. Deploy Authelia with TOTP disable and WebAuthn enabled and a valid user database
2. Access the Authelia interface and authenticate with an unregistered user
3. The device registration method showed is `One-Time Password`

**Comment by james-d-elliott** [comment]
Yep I can see how this would occur. I didn't think of this when we implemented it. Thanks for reporting!

**Comment by james-d-elliott** [comment]
Can you check if the `authelia/authelia:fix-default-auth-method` image fixes it for me (should be built in about 2 or 3 mins)? I am pretty sure it will. It should address both of your points. In addition it should make #2838 easier.

**Comment by aureq** [comment]
Thanks a lot @james-d-elliott 

Deplying `authelia/authelia:fix-default-auth-method` now shows `Security Key | Webauthn` which is great.

I noticed that clicking on the `Methods` link doesn't do anything, so it may be confusing for some users.

Thank you for being so reactive to this.

**Comment by james-d-elliott** [comment]
I'll take a look, was expecting the methods button to vanish.

**Comment by james-d-elliott** [comment]
@aureq a new version has been pushed that should fix that issue. I'll check it doesn't break with multiple methods (which is unlikely since that is checked during integration testing).

**Comment by aureq** [comment]
Thank you James. I confirm this appears to be working fine when only 1 authentication method is set. I also checked with 2 methods (totp and webauthn) and everything looked fine to me as well.

![image](https://user-images.githubusercontent.com/1161681/158044550-12e83f40-2162-40d0-a535-372687f0d7b6.png)

Thanks a lot.

**Comment by james-d-elliott** [comment]
Nice! Thanks for helping me test. I will merge and release this just as soon as someone else gets a chance to review it. Provided we agree that this is a fix and not a feat. If it's a feat it may take a bit longer, but I'll let you know either way.

**Comment by aureq** [comment]
Awesome ! Either way, I'm fine. I don't think this is a critical issue. When I clicked on `Register Device` when `One-Time Password` was selected, I got an error message in the top right corner of the browser. Changing the method did the trick for me.

**Comment by aureq** [comment]
Thank you @james-d-elliott and @clems4ever

**Comment by james-d-elliott** [comment]
No worries, few minor fixes to merge. I'm preparing to release .6 now.

**Comment by ITJamie** [comment]
Is there a way to set the "default" method now? I want the default to be push/duo

**Comment by aureq** [comment]
@ITJamie I think if you only enable Duo, this method only will show up in the UI.

**Comment by james-d-elliott** [comment]
Not yet no, this is made easier by this fix, so it will land in the next feature release 4.35.0 as long as we get around to it which is likely.
