### ISSUE TITLE
Auto-reload pages if a user has just authenticated

### ISSUE THREAD

**Issue by aureq** [authelia/authelia#3000]
### Description

It's common for users to open multiple tabs/pages at once(*) in their browser, some of which may be protected by Authelia. If the user is not authenticated, each protected page will display the login form as expected.

Once the user has authenticated, the Authelia redirects the user to the requested page. However, the user has to reload/refresh all the other tabs/pages that are still prompting for the user's credentials.

A possible improvement to this would be to automatically reload/refresh all other pages/tabs once the authentication has successfully completed on one of the pages(**). This way, the user doesn't have to refresh/reload each page/tab and can easily access the pages requested.

Maybe one area to be mindful of is redirect loops between Authelia and a protected resource.

### Note

(*) My browser is set up so the homepage is a collection of pages, of which many (7 in total) are protected by Authelia.
(**) FWIW, Google already implements this when users sign in on `https://accounts.google.com`

**Comment by james-d-elliott** [comment]
The only potential way this would be possible if a user had multiple portals open that required authentication which I believe is what you're suggesting (it is not possible if they are on a page that is *NOT* Authelia's portal at all). 

We could  potentially poll the backend periodically to check if the user had authenticated if the browser sufficiently sends the correct cookie on those requests and doesn't require a refresh. Or even just check at the moment the user changes the window focus to the window in question.

An alternative which would be faster but harder to implement is a websocket which allows sending state between portals almost instantly.

**Comment by aureq** [comment]
Yes, absolutely. The Authelia portal would have to be opened (Sorry if this wasn't clear enough).

I initially thought of polling the backend, but maybe it's easier to monitor for a cookie (maybe a different from `authelia_session`) and if this cookie has a specific value, then a javascript function would refresh the page. This would eliminate the need of an API and/or websocket.

**Comment by james-d-elliott** [comment]
I thought about this more in depth. There exists two actual options for this:

1. polling an endpoint periodically or on window focus (i.e. user  views the window so we check if they're signed in enough)
2. creating a websocket which communicates state changes regarding the users session, which must also be communicated over some third party means when running in a multi-authelia scenario such as over redis.

The issue with option 2 is it's *highly* complex and prone to breakage. We can't *know* what kind of load balancing the system is using to load balance between Authelia instances, so to my knowledge which is admittedly not the best in this area we have to handle all sorts of load balancing scenarios with Authelia that may not even be possible. We could stipulate what kind of load balancing we support and pigeonhole people into using it, but that does not seem practical.
