### ISSUE TITLE
SQLite storage with encryption key just keep crashing at startup

### ISSUE THREAD

**Issue by ssteo** [authelia/authelia#3023]
### Description
SQLite storage with encryption key keep crashing at startup

### Expected Behaviour
It should run properly and start.

### Reproduction Steps
Just generate a random string and use as encryption key value for SQLite storage

**Comment by james-d-elliott** [comment]
Can't reproduce, and this is tested behavior.

**Comment by ssteo** [comment]
@james-d-elliott  here's the encryption key that I've used and the logs below

storage:
  local:
    path: /config/db.sqlite3
  encryption_key: wGfn8cOrxCf28GW3f4wb


----
authelia    | time="2022-03-16T21:24:22Z" level=info msg="Authelia v4.34.4 is starting"
authelia    | time="2022-03-16T21:24:22Z" level=info msg="Log severity set to debug"
authelia    | time="2022-03-16T21:24:22Z" level=info msg="Storage schema is being checked for updates"
authelia    | time="2022-03-16T21:24:22Z" level=error msg="Failure running the storage provider startup check: the encryption key is not valid against the schema check value" stack="github.com/authelia/authelia/v4/internal/commands/root.go:92 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:78 cmdRootRun\ngithub.com/spf13/cobra@v1.3.0/command.go:860                 (*Command).execute\ngithub.com/spf13/cobra@v1.3.0/command.go:974                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.3.0/command.go:902                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10      main\nruntime/proc.go:255                                          main\nruntime/asm_amd64.s:1581                                     goexit"
authelia    | time="2022-03-16T21:24:22Z" level=debug msg="Notifier SMTP client attempting connection to email-smtp.eu-central-1.amazonaws.com:587"
authelia    | time="2022-03-16T21:24:22Z" level=debug msg="Notifier SMTP client connected successfully"
authelia    | time="2022-03-16T21:24:22Z" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: email-smtp.eu-central-1.amazonaws.com), attempting"
authelia    | time="2022-03-16T21:24:23Z" level=debug msg="Notifier SMTP STARTTLS completed without error"
authelia    | time="2022-03-16T21:24:23Z" level=debug msg="Notifier SMTP server supports authentication with the following mechanisms: PLAIN LOGIN"
authelia    | time="2022-03-16T21:24:23Z" level=debug msg="Notifier SMTP client attempting AUTH PLAIN with server"
authelia    | time="2022-03-16T21:24:23Z" level=debug msg="Notifier SMTP client authenticated successfully with the server"
authelia    | time="2022-03-16T21:24:23Z" level=fatal msg="The following providers had fatal failures during startup: storage" stack="github.com/authelia/authelia/v4/internal/commands/root.go:120 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:78  cmdRootRun\ngithub.com/spf13/cobra@v1.3.0/command.go:860                  (*Command).execute\ngithub.com/spf13/cobra@v1.3.0/command.go:974                  (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.3.0/command.go:902                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:255                                           main\nruntime/asm_amd64.s:1581                                      goexit"

**Comment by ssteo** [comment]
@james-d-elliott  I could not find any example of the `encryption_key` in the documentation, does it need to be in a specific format?

**Comment by james-d-elliott** [comment]
The database was already encrypted with another key. If you want to change it you'll have to have the old key and use `authelia storage encryption change-key` I think it is.

**Comment by james-d-elliott** [comment]
Anything above 20 characters is valid, recommended is 64+.

**Comment by ssteo** [comment]
Works now, thanks @james-d-elliott
