### ISSUE TITLE
synology: Authelia + Traefik; local network bypass not working ... due to Traefik network subnet?

### ISSUE THREAD

**Issue by wiffleman** [authelia/authelia#3030]
My setup: Docker configurated Authelia running behind Traefik for reverse proxy onto various services hosted on my Synology NAS. 
I'm attempting to set up a bypass such that when I'm on the local network (ie. 192.168.1.0/16; <mylocalip>), Authelia will not request authentication. I have added the following into my Authelia configuration files:

    - domain:
      - mydomain.com
      - "*.mydomain.com"
      policy: bypass
      networks:
      - 192.168.0.0/24
      - 172.24.0.0/12
      - 10.0.0.0/8
    - domain:
      - mydomain.com
      - "*.mydomain.com"
      policy: two_factor

When I set it up this way, I end up loosing all Authelia authentication altogether. Looking at debug logs, I notice that all of the incoming traffic is coming through the "172.24.0.0/12" subnet - which is the network that is being generated through Docker and routing through Traefik. Is this the source of my issues? From what I can gather, given that every single external connection to my Authelia is being routed through this subnet, setting a bypass to 172.24.0.0/12 basically bypasses for every external connection.

Is there another bypass solution for local network with the Traefik + Authelia setup?

Thanks

**Comment by james-d-elliott** [comment]
This is all dependent on the connecting IP that Traefik see's, which is basically soemthing configured at the docker level. We've seen this mostly occur when using Synology due to how they configure the network stack. I personally use traefik on ubuntu installed via the documented method on the docker website (not via snap) and it appropriately provides the IP address.

Another potential cause is if you run another proxy in front of Traefik. It has to set the X-Forwarded-For header correctly (the header Authelia uses), and Traefik has to be configured to trust that proxy.

**Comment by wiffleman** [comment]
> This is all dependent on the connecting IP that Traefik see's, which is basically soemthing configured at the docker level. We've seen this mostly occur when using Synology due to how they configure the network stack. I personally use traefik on ubuntu installed via the documented method on the docker website (not via snap) and it appropriately provides the IP address.
> 
> Another potential cause is if you run another proxy in front of Traefik. It has to set the X-Forwarded-For header correctly (the header Authelia uses), and Traefik has to be configured to trust that proxy.

Thanks - this is what I suspected. So if I leave the Traefik config the way it is now with my Synology, does this render Authelia bypass rules by network IPs impossbile?

**Comment by james-d-elliott** [comment]
Yes it likely does, they are very unlikely to be effective. The only workaround for this would be to add a proxy in front of it to set the `X-Forwarded-For` before it gets to the Synology. I'm not entirely sure if there is a fix for this on the Synology setup.

Potentially you're using Cloudflare? In which case you could attempt to workaround this issue by setting it at Cloudflare using transform rules, however you'd have to trust all X-Forwarded-For headers, which runs the risk of someone directly connecting to your Gateway IP and faking that header.

**Comment by james-d-elliott** [comment]
Found this: https://community.synology.com/enu/forum/1/post/134465

**Comment by wiffleman** [comment]
Cheers! Thanks for digging in. I can't see the replies in that thread chain .... nevertheless my knowledge on networking in general is quite superficial - even less so when talking about internal IPs routed through networks created under Docker. Might just have to take a loss on this and authenticate when needed.. it's really not a huge deal but I thought I had an easy out with local bypass with Authelia. Darn!

**Comment by nightah** [comment]
https://gist.github.com/pedrolamas/db809a2b9112166da4a2dbf8e3a72ae9

This has been known to work the other alternative is to run `macvlan` based Docker networking.

**Comment by nightah** [comment]
https://gist.github.com/pedrolamas/db809a2b9112166da4a2dbf8e3a72ae9

This has been known to work the other alternative is to run `macvlan` based Docker networking.

**Comment by ArthurMitchell42** [comment]
> https://gist.github.com/pedrolamas/db809a2b9112166da4a2dbf8e3a72ae9
> 
> This has been known to work the other alternative is to run `macvlan` based Docker networking.

Yes I've had a similar issue when setting up a bridge to a VPN. The macvlan is a good way to go here exposing Traefik & Authelia, just a thought that by pushing it onto the same subnet as you mail LAN you will loose a bit of security though.
