### ISSUE TITLE
Space in search BaseDN causes request to fail with GLAuth.

### ISSUE THREAD

**Issue by ghost** [authelia/authelia#306]
I wanted to try out GLAuth instead of OpenLDAP for use with Authelia. GLAuth works perfectly with ldaptools, but with Authelia I always get "Authentication failed", so I started to debug the requests and found out Authelia puts a space between the request BaseDN so instead of `dc=example,dc=com` it sends `dc=example, dc=com` which causes the request to fail. I wasn't sure whether to submit this to GLAuth or to Authelia, so I'll just submit it to both.

Example of working request "done with ldapsearch":

```
14:13:12.879190 Bind ▶ DEBU 054 Bind request: bindDN: cn=admin,ou=admins,dc=example,dc=com, BaseDN: dc=example,dc=com, source: 192.168.0.68:54638
14:13:12.879279 Bind ▶ DEBU 055 Bind success as %s from %s cn=admin,ou=admins,dc=example,dc=com 192.168.0.68:54638
14:13:12.879753 Search ▶ DEBU 056 Search request as %s from %s for %s cn=admin,ou=admins,dc=example,dc=com 192.168.0.68:54638 (objectclass=*)
14:13:12.879955 Search ▶ DEBU 057 AP: Search OK: %s (objectclass=*)
```

Example of broken request

```

14:13:27.437198 Bind ▶ DEBU 058 Bind request: bindDN: cn=admin,ou=admins,dc=example,dc=com, BaseDN: dc=example,dc=com, source: 192.168.0.68:54642
14:13:27.437283 Bind ▶ DEBU 059 Bind success as %s from %s cn=admin,ou=admins,dc=example,dc=com 192.168.0.68:54642
14:13:27.437730 Search ▶ DEBU 05a Search request as %s from %s for %s cn=admin,ou=admins,dc=example,dc=com 192.168.0.68:54642 (objectclass=*)
2018/12/15 14:13:27 handleSearchRequest error LDAP Result Code 50 "Insufficient Access Rights": Search Error: search BaseDN dc=example, dc=com is not in our BaseDN dc=example,dc=com
```

**Comment by clems4ever** [comment]
Hello @mgrandl , that's really weird. I'll have a look soon. Thank you for reporting in the meantime. I'll let you know when I know what happens.

Thanks.

**Comment by Denter-** [comment]
I got similar problem trying to integrate it with crowd-ldap module. 
In Authelia logs i get:
**: ERR_259 Attempt to search under non-existant entry:  ou=users, dc=crowd'**
In crowd-ldap I see:
**findSubTree()::dn=ou=users, dc=crowd**

I use crowd-ldap for other systems (like owncloud), and I know, that other systems don't have this space and it works normal.

**Comment by clems4ever** [comment]
@ghost, after digging into the code, I don't see how that's even possible the string has a space because the base DN is provided by the user in the configuration and used as is in the code. The second case of @Denter- would be more likely because we definitely concatenate two parts provided in the configuration file but looking at the code it seems right. I'm really wondering if this could be a space inserted when logging but then I would not understand your issue.

Did you eventually find a solution to your issue? Can you still reproduce with the latest version of Authelia?

**Comment by nightah** [comment]
Stale issue and user doesn't exist on GitHub anymore.
@Denter- i'd be curious to know if you experience the same issue with v4, if you like please feel free to give it a try.
