### ISSUE TITLE
Option to use empty templates

### ISSUE THREAD

**Issue by crazygolem** [authelia/authelia#3099]
### Description

I would find it helpful to have an option to use an empty (or minimal) variant of the templates used by authelia when config files are missing.

This should include the default users file-database, which currently sets up the 'authelia' user with a well-known password.

### Use Case

I am setting up authelia in a docker container, inspired by the "compose-lite" example, and would like to configure most of it using environment variables.

As it stands, the default entrypoint and command combination generates a configuration.yml that is not entirely suitable as the mere presence of some configuration keys prevents the configuration of alternatives via environment variables. E.g.: the presence of the `session.redis` configuration in the default template prevents from configuring the in-memory provider via environment variables.

I think this would allow an easier starting point for docker-based setups (my current environment, I am not familiar with the other use-cases), at least as an opt-in if the default behavior remains as currently. This would allow starting easily with a very simple setup where nothing is persisted, verify that the system works, and then iteratively add the other components as needed to make a proper setup.

I am aware that there is currently some configurations that are not available through environment variables, in particular the access control configuration. I don't have a clean solution for this, currently I am mounting a configuration file that only contains that section of the configuration. But I think this is a limitation caused by this configuration not being supported through environment variables, and not a point against the idea of empty/minimal configs (especially if implemented as an opt-in, where it can easily be documented).

Coincidentally, mounting the access control configuration on its own makes authelia behave almost as if this option was already available, as it doesn't generate the remaining missing configs and uses the environment variables instead, only the default file-based users db is generated.

As I see it, currently alternatives would be custom initialization scripts or a custom image based on `authelia/authelia` just to create the empty configs.

**Comment by james-d-elliott** [comment]
We can comment the redis, duo, and access control rules section, as well as JWT Token. Any other areas of issue?

**Comment by james-d-elliott** [comment]
See the linked PR, I identifier a few other sections.

**Comment by crazygolem** [comment]
I'm not entirely sure about the access control section, because it cannot be configured through environment variables at all currently. For the rest of the main config I didn't see anything that couldn't be overridden via environment variables.

There is still the users template though, which is not addressed in the PR: https://github.com/authelia/authelia/blob/master/internal/authentication/users_database.template.yml

Having a default user is not ideal, especially since it has a well-known password hardcoded. But again it doesn't seem possible to configure the default user through environment variables so I'm not too sure how to handle it best. Personally I would like to have an empty default users database, as it makes scripting the deployment a bit easier (I don't have to remove the default user before adding mines), but maybe that would be a bit too annoying for people that just want to try authelia out quickly. (And also I found out that authelia crashes if the `users` object is empty, so maybe addressing this now wouldn't be judicious anyway).

To be honest, I haven't looked into the other templates as I only needed to tweak the config and users db templates for my project until now.

**Comment by james-d-elliott** [comment]
ACL Rules are not really useful unless you explicitly configure them.

As far as  the user database it's not exactly best practice to allow the user to be configured via env, I potentially see the validity in adding a boolean value to the template which indicates the file is a  template, and the user must delete it. 

However if you're scripting you should generate the whole file, with a tool like ansible it's very easy to do. Considering Authelia only creates the config/user db when it doesn't exist why not just create the volume and the files within before deploying?

**Comment by james-d-elliott** [comment]
Further to the points above, if the config file exists and it only has access control rules, it will only set those, and will not be overridden. Allowing you to configure everything other than OIDC clients via ENV.

**Comment by crazygolem** [comment]
> Further to the points above, if the config file exists and it only has access control rules, it will only set those, and will not be overridden. Allowing you to configure everything other than OIDC clients via ENV.

That's what I'm doing currently, and it was a very nice find indeed :)

> Considering Authelia only creates the config/user db when it doesn't exist why not just create the volume and the files within before deploying?

So the idea in my project would be to start with an empty users list, and then add or remove users as needed. I'm using docker-compose and not ansible, and currently I just have a script that gets the content of the users file from the container, add or remove users, writes the file again into the container finally restarts the container so that authelia picks up the changes. It works fine, even to remove the default authelia user.

I also want to have the authelia state in a volume, and in particular the users file, just because it makes my setup look nicer. I still bind mount the ACL config as readonly, as they are fairly static (i.e. it depends on the infrastructure, not the state) and it feels close enough to configuring it in the compose file. With all this I don't need an init container to prepare the volume, and except for the users file authelia starts up nicely configured from just the environment variables (and the mounted ACL config).

Currently, what doesn't feel too nice for me is:
* Mounting the ACL config to get rid of the other configs feels like a nice coincidence, not a thoughtful solution (but I'm fine with that, works on my machine :D)
* Having a default user with a well-known password every time I start authelia from scratch feels really... insecure? like having admin:admin credentials on my website.
* Even if I was willing to prepare the users file in an init container or a custom Dockerfile, it would not currently work: authelia crashes at startup if the file only contains the top-level `users` key but nothing below it (maybe it's worth opening another issue for that?) So if I don't have a user initially, I couldn't even start up my project until the first user shows up.

> As far as the user database it's not exactly best practice to allow the user to be configured via env

Actually with docker it's quite standard to be able to, usually it's used only on first start and gets persisted in the state, then ignored on subsequent restarts (some DB containers for example do it like that, e.g. mariadb with MARIADB_USER and MARIADB_PASSWORD). This allows to securely bootstrap your system from your configs alone, you don't need to script anything, prepare extra init containers or bake the initial credentials into an image from a custom Dockerfile.
