### ISSUE TITLE
Authelia OIDC with self-hosted wiki.js

### ISSUE THREAD

**Issue by Pixma44** [authelia/authelia#3148]
Since I've been looking around for some hours until I figured it out, I wanted to share my configuration for making Wiki.js use Authelia as OIDC provider, To complete the documentation at https://www.authelia.com/docs/community/oidc-integrations.html

Context : I self-host wiki.js and Authelia with docker, using traefik as reverse proxy, a portainer for convenience.

Wiki.js (v2.5.277): 

client ID : wikijs
client Secret : some-autogenerated-secret
Application Authorization Endpoint URL : https://authelia.example.com/api/oidc/authorize
Application Token Endpoint URL : https://authelia.example.com/api/oidc/token
User Info Endpoint URL : https://authelia.example.com/api/oidc/userinfo
Issuer URL : https://authelia.example.com  # don't add a final "/"
email claim : email
LogoutURL : https://authelia.example.com/logout

Authelia (latest, at time of edit) 

configuration.yml 
...
- id: wikijs
        description: wiki.js
        secret: some-autogenerated-secret
        public: false
        authorization_policy: two_factor
        audience: []
        scopes:
          - openid
          - email
          - profile
        redirect_uris: 
            # this URL is given by wiki.js on the OpenID Connect config page as callback URL
          - https://wiki.example.com/login/#####################################/callback 
        userinfo_signing_algorithm: none
        response_modes:
          - form_post

Thanks for your amazing work !

**Comment by WladyX** [comment]
@Pixma44 Thank you very much for sharing this!! I got authentication with Authelia for wiki.js in no time thanks to you!

**Comment by james-d-elliott** [comment]
Thanks for this. Have you considered contributing to the community docs?

**Comment by Pixma44** [comment]
**Update for Authelia V4.35 as it made some change to the oidc provider.**
I jumped from 4.34.6 to 4.35.6.
(using wikijs 2.5.281)

OIDC fail with wikijs (an some other service) as expected. To make it work again, i had to : 
 - change the Application Authorization Endpoint URL : from "https://authelia.example.com/api/oidc/authorize" to https://authelia.example.com/api/oidc/authorization
 - Wikijs shown me an SQL error, for unknown reason the OIDC login tried to create a new user instead of reused the existing one. I had to delete the user in wikijs settings and then reconnect. As a result, the user's documents were transferred to the admin account, so it's a bit annoying. In my case it's a small issue as I'm the only user, but in a production env with a lot of users it could be a huge issue...

**Comment by Pixma44** [comment]
> Thanks for this. Have you considered contributing to the community docs?

I would be glad to , but can't find how (the links i found were outdated)

**Comment by james-d-elliott** [comment]
> * Wikijs shown me an SQL error, for unknown reason the OIDC login tried to create a new user instead of reused the existing one. I had to delete the user in wikijs settings and then reconnect. As a result, the user's documents were transferred to the admin account, so it's a bit annoying. In my case it's a small issue as I'm the only user, but in a production env with a lot of users it could be a huge issue...

Yeah understandable, this is the reason we made sure to list it as a beta. It is however unlikely such a breaking change will occur again, or any other breaking change (except the authorize endpoint /api/oidc/authorize and a few others will be removed in favor of the new ones).

For reference if you had asked I'd have helped figure out how to remap the user for you :)

**Comment by atomicangel** [comment]
Wanted to comment that I’m using Active Directory as my backend auth via Authelia and while it works for the most part I did have to turn on Self Registration for the initial user creation to go smoothly.

Two things besides that:
1) How do I auto redirect the wiki.example.com/login page automatically to Authelia and then also skip the consent page?

2) When Authelia does the initial redirect it gives an error stating that a parameter is incorrect/unneeded or malformed and when removing the referrer_uri part of the url it continues onward properly and I can fully authenticate properly. Do I need to make an issue for this or is it already documented?

**Comment by james-d-elliott** [comment]
You should probably show the error, and the parameter you're talking about since there is no `referrer_uri` part of any OAuth 2.0/OIDC specifications.

**Comment by dakky** [comment]
unfortunetly this does not ssems to work anymore.

I'm quite shure i configured everything as shown, but when logging in I see:

1. the authelia login page
2. after logging in and entering the OTP
3. I am asked wether I'd allow wikijs to see email/profile/openid
4. I get redirected after allowing to a wiki page telling me "oops something went wrong" and in the browser console I can see a http 500 error.

neither wiki (running in an docker container) nor authelia(also dockerized) do show anything in their console logs

**Comment by dakky** [comment]
ah stupid me ;)

in wiki.js the toggle "allow selfregistration" has to be set to ON ....

**Comment by atropos112** [comment]
I had a working OIDC version of wikijs because of your post @Pixma44 , sadly now its giving me 
```
Missing or invalid email address from profile.
```
any idea what could be causing this ? My understanding is if I give it the scopes you mentioned (including email) and have "email claim" set to email I will be good on the email front but somehow its still failing and logs on authelia's side and on wikijs side don't seem to be saying anything

**Comment by stanthewizzard** [comment]
With same settings
I have this message
The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy.

Thanks for help

**Comment by stanthewizzard** [comment]
I had it working:
connect openID/oauth2
wikiJS (same in authelia settings)
secret (same in authelia settings)
yours settings to access authelia (dns things)
email claim email
group claim group
juste for 1 time enable self registration

unlog
log with authelia button
done

**Comment by foorschtbar** [comment]
Found the issue, there was a single space in front of the "Issuer URL"...arrrggggggg

**Comment by stanthewizzard** [comment]
Hello 
with 4.8
it's not working anymore 

No solution on my side

**Comment by james-d-elliott** [comment]
The original issue was solved, these are all unrelated to this issue. I'd suggest opening a discussion with substantially more information.
