### ISSUE TITLE
Rotate file log

### ISSUE THREAD

**Issue by IcerOut** [authelia/authelia#3210]
### Description

Can some configuration be done to rotate the authelia log file (perhaps with something like `logrotate`) periodically, or when it gets too large?
At the moment a single file is used, and it can grow quite a bit over time. For example, this is over the past 2-3 months:
![image](https://user-images.githubusercontent.com/44326661/163721656-a1541296-a13f-48ac-a885-84fa5d08b76d.png)

I'm using the official docker container (`authelia/authelia`), but I'm guessing it's the same situation for the standalone package.

### Use Case

_N/A_

**Comment by nightah** [comment]
Our recommendation would be to utilise said tools that are readily available like `logrotate` along with Authelia as opposed to adding the rotation capability into Authelia itself, that way you can manage your rules in accordance with your own requirements.

**Comment by IcerOut** [comment]
For the standalone, that would probably be the cleanest solution.

But for the docker container, I think it would be simpler and more convenient to have logrotate installed and configured in the container (not in the application itself), like LinuxServer (and a few others) do with the logfiles in their containers, if that would be possible.


For LinuxServer, it seems to be installed and setup here:
https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/Dockerfile
with these configs:
https://github.com/linuxserver/docker-baseimage-alpine-nginx/tree/master/root/etc/logrotate.d

**Comment by james-d-elliott** [comment]
Actually best practice for docker containers is to output logs to stdout/stderr which is what we do by default. Then the docker daemon configuration is able to be tweaked to perform rotation. 

https://docs.docker.com/config/containers/logging/json-file/#options

**Comment by james-d-elliott** [comment]
@IcerOut check out #3330 and let me know if it's sufficient. Basically on every start the filename will be based on the exact time of the logging being initialized.

**Comment by IcerOut** [comment]
@james-d-elliott Yup, that would work well for me. 

With this, it'd just be a matter of going in 2-3 times a year to delete the older log files.
