### ISSUE TITLE
OpenID connections all failing with error Client credentials missing or malformed in both HTTP Authorization header and HTTP POST body

### ISSUE THREAD

**Issue by beastarman74** [authelia/authelia#3220]
### Description

Since 17th April 14:50 (UTC) my OpenID connections have all started to fail.  I am not aware of any changes to Authelia or any configuration changes either.  

The redirection to Authelia is successful as is the authentication including ToTP 2FA.  However the successful authentication then fails at the application end with the application reporting a few different errors with Gitea, Outline,  reporting "request_unauthorized" and Portainer and Bookstack a bit more detailed reporting "Access Request failed with error: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Client credentials missing or malformed in both HTTP Authorization header and HTTP POST body."

### Expected Behaviour
OpenID authenticates successfully as was working previously.

### Reproduction Steps
Attempt to login to an application that is enabled for OpenID authentication. 
1. Visit the application web page.
2. Click Login using OpenID option
3. Authenticate to Authelia
4. Accept the consent request
5. Application will fail to login and either show an error or just return to login screen.
6. Authelia log file states error message.

### Additional Information

- I have tried rolling back to the previous version of Authelia. As I initially assumed it was to do with Authelia v4.35.  However the issue remained in v4.34.6. 
- I stopped my cloudflared tunnel to ensure it was not related to this. 
- I have been through my configuration.yml and checked against the documentation to see if any migrations had been missed. 

Attached are redacted Authelia.log files (I have kept each captured error for each app in a different file), plus my configuration.yml.

Thanks for your help.
[outline authelia.log.txt](https://github.com/authelia/authelia/files/8514135/outline.authelia.log.txt)
[portainer authelia.log.txt](https://github.com/authelia/authelia/files/8514136/portainer.authelia.log.txt)
[bookstack authelia.log.txt](https://github.com/authelia/authelia/files/8514137/bookstack.authelia.log.txt)
[gitea authelia.log.txt](https://github.com/authelia/authelia/files/8514138/gitea.authelia.log.txt)
[configuration.yml.txt](https://github.com/authelia/authelia/files/8514143/configuration.yml.txt)

**Comment by james-d-elliott** [comment]
So first of all the Authorization header _MUST_ be present in requests to the userinfo endpoint with bearer auth. If this header is not being sent by the relying party or being removed by the reverse proxy would explain  the userinfo issue.

As far as the other issue I'm not entirely sure what could cause this. My guess based on the above issue and the fact the Authelia version _does not_ affect this and it _was previously working_ is that there is an issue at the reverse proxy, either in configuration or something else.

I can have a think about what we could potentially log to help figure this out however.

**Comment by james-d-elliott** [comment]
Also based on the information provided it is clearly unlikely to be a bug but rather an integration configuration issue in the proxy (either cloudflare or your reverse proxy).

**Comment by beastarman74** [comment]
Thanks for taking the time to look into it. I stupidly never thought it could be my reverse proxy (Nginx Proxy Manager).  

I will take a look and reapply configurations to Gitea etc .

**Comment by james-d-elliott** [comment]
No worries, not entirely  sure how we can debug this.. 4.35 should give us some pretty detailed log messages as to w hat's going on. The gitea one should be simple as the token is being issued and gitea is trying to use it to access the userinfo endpoint but it's not seeing it for some reason.

As far as portainer, I suspect once you find what is causing this issue we may be able to  see more clearly where the portainer issue may be.
