### ISSUE TITLE
session expiration doesn't redirect

### ISSUE THREAD

**Issue by YouveGotMeowxy** [authelia/authelia#3221]
I've recently installed  Authelia and have noticed that when the user's Authelia session has expired (even while actively using the service it is protecting) the service just seems to stop responding. There's no actual notice the Authelia's session expired. The only way to really know is to refresh the page and then the Authelia form shows up.

For example, I'll be using a log viewing app (Dozzle) and suddenly out of nowhere the logs just stop updating while I'm trying to use it/view them; no Authelia session expiration notice or anything. Then I refresh the page and Auth's login shows. Really strange behavior that Auth doesn't auto-load it's login form when the session expires, or at least maybe a toast notification, or something.

II know I could check the "remember me" box, and that might keep me logged in, but at the moment I don't want that. I use Bitwarden to fill my forms for me rather than check remember me boxes.

**Comment by james-d-elliott** [comment]
In the future please use the issue template. Please provide logs (preferably trace), version, reverse proxy.

Authelia's API is requested by the proxy on all HTTP requests. When remember me is unchecked the session will only expire if the time when the session was _**CREATED**_ is longer ago than what is configured in the `expiration` option or if the previous request to the current one occurred longer ago than what is configured in the `inactivity` option. All of which are up to your individual discretion. Regarding this portion of the issue (the fact the session is timing out, not the result of the timeout) I will consider it solved, if this doesn't resolve it in your mind please open a separate one.

**Comment by YouveGotMeowxy** [comment]
> In the future please use the issue template. Please provide logs (preferably trace), version, reverse proxy.
> 
> Authelia's API is requested by the proxy on all HTTP requests. When remember me is unchecked the session will only expire if the time when the session was _**CREATED**_ is longer ago than what is configured in the `expiration` option or if the previous request to the current one occurred longer ago than what is configured in the `inactivity` option. All of which are up to your individual discretion. Regarding this portion of the issue (the fact the session is timing out, not the result of the timeout) I will consider it solved, if this doesn't resolve it in your mind please open a separate one.

Hi James

I didn't know whether this was considered a "bug" enough to create an "issue" post; I thought it might possibly just be a misconfiguration so came here asking. I don't really know specifically which log(s) to show you in regards to this, Authelia's  only? Only Authelia's reverse proxy? or also the RP of one of the containers I've seen it happen with? Please be more specific as to what you need to see.

I was actually more interested in the former portion of this issue than the latter. I'd like to see a toast, or a redirection to the login form, or something, when it does timeout/expire so I'm not sitting there all the time wondering "what the hell is going on here? Why isn't the page loading? Arrrrgh!".

But also, shouldn't Authelia be able to detect that it's actually in use and not expire even after the period set in the expiration? It's strange to see things "just stop working" in realtime while you're actively using it.

**Comment by james-d-elliott** [comment]
I'd need to see the logs in Authelia when the issue is occurring for you. Specifically if we do not see any log messages being generated that are intended to redirect this may not be  technically be possible.  For example if the "requests" were being made over a  websocket.

As to the information I need, I need to be able to replicate this. So I need to know what proxy you are using, and the configuration for the affected application. It would also be good to see an example request with headers that's failing from the browser dev tools.

I think that what's happening is you're using nginx and it's an XHR which can't be handled gracefully in nginx as far as I am aware.

**Comment by YouveGotMeowxy** [comment]
ok, on a scale of 1/10 regarding computer skills, I'm at like MAYBE a 6, so you'll have to bear with me. :)

I am running [Linuxserver's Swag](https://hub.docker.com/r/linuxserver/swag) container to do all of my reverse proxying. And I think one container that would be good to help reproduce this that I consistently see it happening with is the [Dozzle](https://github.com/amir20/dozzle) log viewer container. When something in Authelia expires, trying to view any log updates essentially just leaves ya staring and the Dozzle screen with no new input happening. So doing F5 to refresh then takes me to the Authelia login form, which is really the only way that I am able to know that what happened was my Authelia sesh expired.

My Dozzle RP config:

```
## Version 2021/05/18
# make sure that your dns has a cname set for dozzle and that your dozzle container is named dozzle

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name dozzle.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for Authelia
    include /config/nginx/authelia-server.conf;

    location / {
        # enable for Authelia
        include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app dozzle;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        # Add Theme
        set $app dozzle;
        include /config/nginx/theme-park.conf;
        proxy_hide_header "x-webkit-csp";
        proxy_hide_header "content-security-policy";
    }
}
```

I think a quick way to test might be to have dozzle open and viewing the main screen, and set Authelia's idle timeout real short, say 3 minutes, then restart a container after you purposely let Authelia idle out. Normally w/out idling out the Dozzle screen would auto-refresh showing any new logs, but if you idle out it doesn't refresh the list. You can even click onto a container in the list and dozzle won't load the logs.

I'll try to get something in the actual Authelia logs and Dev console as well if I can, and post later.

**Comment by YouveGotMeowxy** [comment]
Ok, so after something expired in Authelia, which I think was the idle timeout clicking one of the logs in Dozzle shows this in the Dev console:

```
EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.
index.44f0ac0a.js:1 
 EventSource failed: {"isTrusted":true}
(anonymous)	@	index.44f0ac0a.js:1
error (async)		
p	@	index.44f0ac0a.js:1
setup	@	index.44f0ac0a.js:2
Et	@	vendor.19cb1035.js:4
lh	@	vendor.19cb1035.js:1
yc	@	vendor.19cb1035.js:1
O	@	vendor.19cb1035.js:1
S	@	vendor.19cb1035.js:1
v	@	vendor.19cb1035.js:1
G	@	vendor.19cb1035.js:1
run	@	vendor.19cb1035.js:1
$	@	vendor.19cb1035.js:1
O	@	vendor.19cb1035.js:1
S	@	vendor.19cb1035.js:1
v	@	vendor.19cb1035.js:1
I	@	vendor.19cb1035.js:1
A	@	vendor.19cb1035.js:1
v	@	vendor.19cb1035.js:1
I	@	vendor.19cb1035.js:1
b	@	vendor.19cb1035.js:1
x	@	vendor.19cb1035.js:1
v	@	vendor.19cb1035.js:1
I	@	vendor.19cb1035.js:1
b	@	vendor.19cb1035.js:1
x	@	vendor.19cb1035.js:1
v	@	vendor.19cb1035.js:1
I	@	vendor.19cb1035.js:1
b	@	vendor.19cb1035.js:1
x	@	vendor.19cb1035.js:1
v	@	vendor.19cb1035.js:1
Promise.then (async)		
Ac	@	vendor.19cb1035.js:4
ei	@	vendor.19cb1035.js:4
(anonymous)	@	vendor.19cb1035.js:1
po	@	vendor.19cb1035.js:1
is	@	vendor.19cb1035.js:1
(anonymous)	@	vendor.19cb1035.js:1
po	@	vendor.19cb1035.js:1
is	@	vendor.19cb1035.js:1
(anonymous)	@	vendor.19cb1035.js:1
po	@	vendor.19cb1035.js:1
is	@	vendor.19cb1035.js:1
(anonymous)	@	vendor.19cb1035.js:1
po	@	vendor.19cb1035.js:1
is	@	vendor.19cb1035.js:1
set value	@	vendor.19cb1035.js:1
B	@	vendor.19cb1035.js:8
(anonymous)	@	vendor.19cb1035.js:8
Promise.then (async)		
b	@	vendor.19cb1035.js:8
E	@	vendor.19cb1035.js:8
a	@	vendor.19cb1035.js:8
Et	@	vendor.19cb1035.js:4
nt	@	vendor.19cb1035.js:4
r	@	vendor.19cb1035.js:4
Show 26 more frames
```

and in authelia log:

```
{"level":"debug","msg":"Check authorization of subject username= groups= ip=10.0.0.2 and object https://dozzle.domain.com/assets/index.15cf6652.css (method GET).","time":"2022-04-25T01:54:12-05:00"}
{"level":"info","method":"GET","msg":"Access to https://dozzle.domain.com/assets/index.15cf6652.css (method GET) is not authorized to user \u003canonymous\u003e, responding with status code 401","path":"/api/verify","remote_ip":"10.0.0.2","time":"2022-04-25T01:54:12-05:00"}
{"level":"debug","msg":"Check authorization of subject username= groups= ip=10.0.0.2 and object https://dozzle.domain.com/api/logs/stream?id=d2687a0a5bdb\u0026lastEventId= (method GET).","time":"2022-04-25T01:54:25-05:00"}
{"level":"info","method":"GET","msg":"Access to https://dozzle.domain.com/api/logs/stream?id=d2687a0a5bdb\u0026lastEventId= (method GET) is not authorized to user \u003canonymous\u003e, responding with status code 401","path":"/api/verify","remote_ip":"10.0.0.2","time":"2022-04-25T01:54:25-05:00"}
```

**Comment by james-d-elliott** [comment]
I thought we logged if it was an XHR but guess we don't. If you provide your current version I will make a branch you can try that will log the specific requests. My guess is they are XHR's and there may not be anything we can do due to the way nginx's auth_request module works. However I'm also happy to spend some time trying to investigate it.

**Comment by YouveGotMeowxy** [comment]
> If you provide your current version I will make a branch you can try that will log the specific requests.

ty for looking into it. v4.34.6

**Comment by james-d-elliott** [comment]
Hey sorry to not get back sooner, I've not forgotten just not had much time to setup a test scenario. I'll try to do it this weekend.

**Comment by james-d-elliott** [comment]
Sadly there is no possible way to handle this with NGINX with apps that don't use the FetchAPI, or have improperly configured the FetchAPI.
