### ISSUE TITLE
Duo not auto disabled if no duo block in config

### ISSUE THREAD

**Issue by tombomb** [authelia/authelia#3233]
Recently updated my stack from [4.34.3] (2022-03-05) -> [ v4.35.0] (2022-04-18) and authula started blocking all trafic.

It seems that some where between these version authelia started requiring you to explicitly turn off DUO instead of just not having it in your config (as the documentation suggests should work).

I have no blocks for "duo_api:" yet its still failing to start with the error 

```
time="2022-04-22T18:33:36-04:00" level=error msg="Configuration: duo_api: option 'hostname' is required when duo is enabled but it is missing"
time="2022-04-22T18:33:36-04:00" level=error msg="Configuration: duo_api: option 'integration_key' is required when duo is enabled but it is missing"
time="2022-04-22T18:33:36-04:00" level=fatal msg="Can't continue due to the errors loading the configuration"
```

Adding the following to the config fixes this but I don't see this breaking change in any of the change logs in the recent releases 

```
duo_api:
  disable: true
```

Posting to see if this change was intended, and its just the docs that need to be updated. Or if something changed somewhere a botched this up.
https://www.authelia.com/docs/configuration/duo-push-notifications.html
```
Note: The configuration options in the following sections are noted as required. They are however only required when you have this section defined. i.e. if you don’t wish to use the [Duo](https://duo.com/) push notifications you can just not define this section of the configuration.
```

Thanks!
Tom

**Comment by james-d-elliott** [comment]
As long as the `hostname`, `integration_key` and `secret_key` are not configured by the configuration, environment, or secrets, it's automatically disabled on startup. I've tested this locally and it operates exactly like this, so you evidently have it configured somewhere.

```go
	if config.DuoAPI.Hostname == "" && config.DuoAPI.IntegrationKey == "" && config.DuoAPI.SecretKey == "" {
		config.DuoAPI.Disable = true
	}
```

**Comment by james-d-elliott** [comment]
Any feedback on this? I expect it's in your docker-compose as an ENV.
