### ISSUE TITLE
Authelia does not receive the original header if behind traefik

### ISSUE THREAD

**Issue by DunklerPhoenix** [authelia/authelia#3237]
### Description

I have two traefik instances. The first one runs on the same docker host as authelia.

host: bouncer.domain.com
```
   [http.middlewares]
      [http.middlewares.sslheader.headers.customrequestheaders]
         X-Forwarded-Proto = "https"
      [http.middlewares.authelia.forwardauth]
         address = "http://authelia:9091/api/verify?rd=https://bouncer.domain.com"
         trustForwardHeader = true
		 authResponseHeaders = "Remote-User,Remote-Groups,Remote-Name,Remote-Email"
      [http.middlewares.authelia-basic.forwardauth]
         address = "http://authelia:9091/api/verify?auth=basic"
         trustForwardHeader = true
		 authResponseHeaders = "Remote-User,Remote-Groups,Remote-Name,Remote-Email"
```

The second traefik instance should now authenticate an request via forwardauth to the authelia instance behind the first traefik instance .

host: s2.domain.com

  ```
 [http.middlewares]
      [http.middlewares.sslheader.headers.customrequestheaders]
         X-Forwarded-Proto = "https"
      [http.middlewares.authelia.forwardauth]
         address = "https://bouncer.domain.com/api/verify?rd=https://bouncer.domain.com"
         trustForwardHeader = true
		 authResponseHeaders = "Remote-User,Remote-Groups,Remote-Name,Remote-Email"
      [http.middlewares.authelia-basic.forwardauth]
         address = "https://bouncer.domain.com/api/verify?auth=basic"
         trustForwardHeader = true
		 authResponseHeaders = "Remote-User,Remote-Groups,Remote-Name,Remote-Email"
```

Every service on the host bouncer.domain.com works great and without any problems with authelia. 
Example:
`time="2022-04-23T21:37:35+02:00" level=info msg="Access to https://notes.domain.com/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://bouncer.domain.com?rd=https%3A%2F%2Fnotes.domain.com%2F&rm=GET" method=GET path=/api/verify remote_ip=My_PC_IP`

But if the host s2.domain.com makes an authforward request to host bouncer.domain.com authelia sees only bouncer.domain.com. It doesn't receive the original domain.
Example:
`time="2022-04-23T21:33:29+02:00" level=info msg="Access to https://bouncer.domain.com/api/verify?rd=https://bouncer.domain.com is forbidden to user admin" method=GET path=/api/verify remote_ip=host2_IP`

If I configure the traefik middleware on s2.domain.com with "authRequestHeaders" then the link on the unauthenticated page looks like this: 
https://bouncerdomain.com/?rd=https%3A%2F%2Fbouncer.domain.com%2Fapi%2Fverify%3Frd%3Dhttps%3A%2F%2Fbouncer.domain.com

host: s2.domain.com

  ```
 [http.middlewares]
      [http.middlewares.sslheader.headers.customrequestheaders]
         X-Forwarded-Proto = "https"
      [http.middlewares.authelia.forwardauth]
         address = "https://bouncer.domain.com/api/verify?rd=https://bouncer.domain.com"
         trustForwardHeader = true
		 authResponseHeaders = "Remote-User,Remote-Groups,Remote-Name,Remote-Email"
		 authRequestHeaders = "X-Original-URL,X-Forwarded-Method"
      [http.middlewares.authelia-basic.forwardauth]
         address = "https://bouncer.domain.com/api/verify?auth=basic"
         trustForwardHeader = true
		 authResponseHeaders = "Remote-User,Remote-Groups,Remote-Name,Remote-Email"
		 authRequestHeaders = "X-Original-URL,X-Forwarded-Method"
```

Do you have any ideas how I get this working without opening the authelia port?
Greetings

**Comment by DunklerPhoenix** [comment]
Little Update:
I opened the authelia port only for host 2 and tested it. Now authelia gets the domain, but it seems it can't receive the session. The session cookie is a wildcard cookie.:
`time="2022-04-23T22:11:10+02:00" level=info msg="Access to https://traefik-host2.domain.com/dashboard/ (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://bouncer.domain.com?rd=https%3A%2F%2Ftraefik-host2.domain.com%2Fdashboard%2F&rm=GET" method=GET path=/api/verify remote_ip=My_PC_IP`

**Comment by james-d-elliott** [comment]
As far as I am aware there is no way to do this with traefik. You need to forward the port plainly to the second instance there are multiple ways to do this.

**Comment by DunklerPhoenix** [comment]
Okay. Thank you. I'll open a port :)

**Comment by james-d-elliott** [comment]
Just thinking more on this. You may be able to run an nginx container specifically for forward auth endpoint. Would make it easy to have a whitelist.

**Comment by DunklerPhoenix** [comment]
What is your opinion:
Is it better to run one authelia instance and let other servers connect to it or
Is it better to run one authelia instance per server and let each instance connect to the backend (ldap, mysql, redis, etc)?

**Comment by james-d-elliott** [comment]
It depends if the database is accessible to all instances. The way I'd generally recommend is exposing the /api/verify endpoint plainly over nginx or caddy.
