### ISSUE TITLE
Display TOTP Authentificator Key under the QR Code

### ISSUE THREAD

**Issue by UbioZur** [authelia/authelia#3257]
### Description

The TOTP Authentificator Key could/should be displayed under the QR Code when trying to register a new device.
It is not always feasible to use a camera / phone to scan a QR code to get the Authentificator Key for TOTP.

That code is actually no where to be found in the page source, blocking every use case of requiring such key without a QR Code.

### Use Case

- Using Bitwarden for the TOTP.
- Not having access to a camera to scan the QR Code
- Trying to set up an Authelia account from a phone. Currently it is not possible to use the camera from Google Authentificator App (For example) to scan the screen to read the QR Code. 
- Keeping the keys as backup up from Google Authentificator (as it itself doesn't offer backup, and the TOTP would be lost with phone).

**Comment by nightah** [comment]
This feature exists in Authelia since [v4.25.0](https://github.com/authelia/authelia/releases/tag/v4.25.0)

You can see a mock of what it looks like [here](https://github.com/authelia/authelia/pull/1551#issuecomment-750701251).
You can copy either just the OTP secret or the full OTP URI with either of the buttons under the secret itself.

Is there something I'm missing or perhaps you are running an older version of Authelia?

**Comment by UbioZur** [comment]
![Screenshot_20220427-150209](https://user-images.githubusercontent.com/13650202/165745700-d7893378-508d-4139-a7d3-d3d8441c9010.png)

Did not show for me ( authelia/authelia:4.35 )
And nothing in the html code either.


Android chrome
Android brave
Fedora firefox

I will try to investigate a bit further tomorrow.

**Comment by UbioZur** [comment]
I have managed to show it (by deleting the sqlite database)

This is the secret it is showing me

`otpauth://totp/authelia.com:USERNAME?algorithm=SHA1&digits=6&issuer=authelia.com&period=30&secret=THEACTUALSECRET!`

Using the key button to copy, copy just the secret, using the copy button to copy copy the whole address.

So i guess there is a reason to need that whole path in some use case, but it's a bit less intuitive for those who just need the key (especially without label or tooltip for the buttons).
