### ISSUE TITLE
Cannot redirect to HTTP endpoint after authenticated.

### ISSUE THREAD

**Issue by jieweiyang** [authelia/authelia#3309]
### Description
After successful 2FA auth with TOTP, it just not redirect with below error.
![image](https://user-images.githubusercontent.com/24854603/167094581-98c62acf-d0b2-4e55-90e1-6df927f4a3d0.png)

### Expected Behaviour

Redirect to target url http://prom.sample.cc after authenticated.

### Additional Information

Configure with NgnixProxyManager. 
Using authelia.conf/auth.conf/proxy.conf from below:
https://www.authelia.com/docs/deployment/supported-proxies/nginx.html

Made below modificatons:

authelia.conf
`set $upstream_authelia http://my-intranet-ip:9091/api/verify; `

Error log as blelow:

2022-05-06T08:05:22.403471821Z time="2022-05-06T16:05:22+08:00" level=error msg="Scheme of target URL http://prom.sample.cc/ must be secure since cookies are only transported over a secure connection for security reasons" method=GET path=/api/verify

**Comment by nightah** [comment]
This is not a bug, this is working as intended.

Authelia can only protect `https` services as the cookie is set to `Secure` to prevent cookie theft.

https://www.authelia.com/docs/security/measures.html#protection-against-cookie-theft
