### ISSUE TITLE
Support disabling "Lost your device"

### ISSUE THREAD

**Issue by SysAdmLS** [authelia/authelia#3353]
### Description
Please implement a setting to disable the "Lost your device" button/workflow.

### Use Case
As described in https://github.com/authelia/authelia/issues/135 this feature could be abused to bypass 2FA when the attacker has gained access to the users email account. A quick and easy fix for this would be to support disabling/removing the "Lost your device" option in the configuration.yml as it's already possible with the normal password https://www.authelia.com/docs/configuration/authentication/#disable_reset_password.

The user then has to contact the Admin for registering a new device (Admin delete his device from totp_configurations/webauthn_devices table on the database).
A nice addition would be a way to reset someones devices without the need of accessing the database.

**Comment by james-d-elliott** [comment]
We're planning to do a lot of work in this area in the near future. However I don't know if the ability to disable this will be part of that or ever. What's more likely is that a user will be required to perform 2FA to  remove/add devices once they have registered their first device, or admins will be able to change the default behavior to enforce this.

We may add an ability laster in time for admins to delete devices from the web interface and enhance this option to prevent users from doing it themselves however this will never be implemented I don't believe unless it has a web UI as we do not want to encourage direct modification of the database.

**Comment by james-d-elliott** [comment]
Think this can easily be merged as part of #135
