### ISSUE TITLE
LDAP connection account can only be "admin" should be changeable

### ISSUE THREAD

**Issue by mamema** [authelia/authelia#3356]
## Feature Request
1. IMPORTANT: Do not report security vulnerabilities via GitHub issues. Please click 'choose a different type' and see the dedicated report a security vulnerability link.
2. Remember to customize the title above.
3. Replace the below sections (not this section) starting with <!- - and ending with - 

### Description

The LDAP connection account (openldap) only works if it's called "admin"

### Use Case

For SSO cases, the backend systems often have "admin" as account, so it would be nice to use this account to login to authelia and backend.
As the LDAP connection account has higher/different rights, i do not want to use this account also to login to backends, but i cannot change this because of the description above.

**Comment by james-d-elliott** [comment]
You can customize the account used by authelia here; https://www.authelia.com/docs/configuration/authentication/ldap.html#user

Context: https://github.com/authelia/authelia/blob/v4.35.4/config.template.yml#L320-L321

**Comment by mamema** [comment]
which isn't working. Two identical accounts, both with LDAP admin permission flag, one is called "admin" other is called "admin2", admin is working admin2 is not

**Comment by james-d-elliott** [comment]
There is potentially a bug, but it's likely a configuration issue on openldap. Can you please:

1. Explain specifically what you mean by "isn't working". 
2. Provide Authelialogs.
3. Provide the version of Authelia.
4. Provide the version and installation method of openldap.
5. Utilize the `ldapsearch` tool to validate it can actually obtain search results.

**Comment by james-d-elliott** [comment]
Did you solve this?

**Comment by mamema** [comment]
no, not really, but as i was not able to bring my openldap docker to accept a second admin account, i'm closing this request. So in theory authelia accepts other admin account names, but found no clear explanation how to do it in openldap

**Comment by james-d-elliott** [comment]
The only reason you should need an admin account is for changing passwords. Otherwise a standard account which can read the directory should suffice.
