### ISSUE TITLE
e-mail address instead of username to login

### ISSUE THREAD

**Issue by JonasGutermuth** [authelia/authelia#3383]
### Description

Please add a setting to enable login with email instead/in addition to username. This email should be case insensitive to grant access with:

- John.Doe@example.com
- john.doe@example.com

In both File and LDAP mode. 

### Use Case
It is common use to login with multiple combinations of email/username
 - Github: Email or username
 - Google: Email or phone
 - Facebook: Email or phone
 -  instagram: Email, phone or username

**Comment by james-d-elliott** [comment]
Both already exist. For the file mode the username can be whatever you want. In LDAP you just have to ensure the filter is correct.

**Comment by JonasGutermuth** [comment]
Thank you for your quick response. 

LDAP mode:
 - [x] case insensitive
 - [x]  email and username combined login
 - [x] username or email login  

File mode:
 - [ ] case insensitive
 - [ ]  email and username combined login 
 - [x] username or email login

**Comment by james-d-elliott** [comment]
> case insensitive possible

The sensitivity is determined by the  LDAP backend however it's fairly common for all attributes in LDAP to be case-insensitive during queries.

All of the scenarios listed have been tested with LDAP.

> File mode:

Correct. Using the File Provider you must select between a username/email as the login attribute, and it is case sensitive. We also have no data on how people are using this, there is no restriction currently that prevents someone having an email-like username or their email as a username or upper/lowercase mix in the username with duplicates in another casing, so changing this functionality is probably something to be cautious about.

**Comment by james-d-elliott** [comment]
I'll take a look at this while I look at revamping the file provider.
