### ISSUE TITLE
error loading module 'json' from file !

### ISSUE THREAD

**Issue by xlvchao** [authelia/authelia#3457]
My config :
![image](https://user-images.githubusercontent.com/33950671/171492479-df1ee3da-dcec-477b-806c-16646536b92a.png)

The question is :
![image](https://user-images.githubusercontent.com/33950671/171492531-161fc8b7-ce58-4381-97d7-5eea8d7ab648.png)

**Comment by nightah** [comment]
I assume you resolved this because you lodged #3458 shortly after, can this be closed?
