### ISSUE TITLE
Redirect omits ending / in URI, causing error

### ISSUE THREAD

**Issue by blasphemite** [authelia/authelia#3459]
Running via docker, using forward auth from Caddy 2. 

With the following configuration, visiting https://host.example.com redirects to `https://www.example.com/auth?rd=https%3A%2F%2Fhost.example.com%2F&rm=GET` (omitting the second / in `/auth/`), which fails to reach Authelia. If I manually correct `/auth/` in the URI everything works as expected. I've verified the env variable is being passed to the container correctly. Cleared browser cache, etc.

Environment variables:
```
...
AUTHELIA_DEFAULT_REDIRECTION_URL=https://www.example.com/auth/
AUTHELIA_SERVER_HOST=0.0.0.0
AUTHELIA_SERVER_PORT=9091
AUTHELIA_SERVER_PATH=auth
...
```

Authelia configuration.yaml:
```
...
  rules:
    - domain: host.example.com
      policy: one_factor
...
```

Caddyfile: 
```
...
host.example.com {
  forward_auth authelia:9091 {
    uri /api/verify?rd=https://www.example.com/auth
    copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
  }
  reverse_proxy http://nginx:80
}
www.example.com {
  @auth-portal path /auth /auth/*
  handle @auth-portal {
    reverse_proxy http://authelia:9091
  }
}
...
```

**Comment by james-d-elliott** [comment]
Adjust `uri /api/verify?rd=https://www.example.com/auth` to `uri /api/verify?rd=https://www.example.com/auth/` and report back.

**Comment by blasphemite** [comment]
ack duh. ty
