### ISSUE TITLE
Configuration option for revealing IP address in footer

### ISSUE THREAD

**Issue by lriley2020** [authelia/authelia#3461]
### Description

When Authelia sends emails to users for events such as TOTP setup, the email has a footer at the bottom, reading 
```
This email was generated by a request from the IP address xx.xx.xx.xx.
```
Is there, or could there be a configuration option to remove this footer, as I'd quite like not to reveal my IP address every time an email is sent from Authelia? Thanks in advance!

### Use Case

People , especially those who use features such as Cloudflare proxy already, may want to hide the public IP of their server

**Comment by james-d-elliott** [comment]
https://www.authelia.com/docs/configuration/notifier/#template_path

**Comment by lriley2020** [comment]
Thanks! Sorry for not checking the docs thoroughly enough!

**Comment by james-d-elliott** [comment]
No worries!
