### ISSUE TITLE
Authelia logo

### ISSUE THREAD

**Issue by alexanderadam** [authelia/authelia#3484]
It would be great to have the Authelia logos somewhere (i.e. as SVG or other vector formats).
This way it would be easier to integrate them in FOSS OTP apps (_i.e. [andOTP](https://github.com/andOTP/andOTP#andotp----android-otp-authenticator), [FreeOTP+](https://github.com/helloworld1/FreeOTPPlus) and [Aegis](https://github.com/beemdevelopment/Aegis)_).

**Comment by james-d-elliott** [comment]
https://www.authelia.com/reference/guides/branding/
