### ISSUE TITLE
There was an issue resetting the password

### ISSUE THREAD

**Issue by tfjield** [authelia/authelia#3516]
I'm just setting up authelia and I'm a complete noob.  I've got it up and running in a QNAP docker container, and it seems to be working.  I'm using a file-based authentication.  But when I try to change the password, I enter my user name, and it says it sent an email (which it did).  In the email there is a link, and I click on it, and it asks me for a new password.  After entering the passwords and clicking Reset, an error pops up:

`There was an issue resetting the password`

In the log, I see the following:

`time="2022-06-14T18:52:13Z" level=error msg="no identity verification process has been initiated" method=POST path=/api/reset-password remote_ip=192.168.1.99 stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:87          (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/handlers/handler_reset_password_step2.go:20 ResetPasswordPOST\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:53          AutheliaMiddleware.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25                   SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35                   SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16                   SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.9/router.go:414                                      (*Router).Handler\ngithub.com/valyala/fasthttp@v1.37.0/http.go:153                                      (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.37.0/server.go:2338                                   (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.37.0/workerpool.go:224                                (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.37.0/workerpool.go:196                                (*workerPool).getCh.func1\nruntime/asm_amd64.s:1571                                                             goexit"`

Any idea what this means, and how do I fix it?

**Comment by james-d-elliott** [comment]
This usually occurs when a browser other than the one used to initiate the process was used.

**Comment by james-d-elliott** [comment]
Can you see the `authelia_session` cookie in the dev tools?

**Comment by tfjield** [comment]
Nope.  No cookies.

**Comment by tfjield** [comment]
Could it be the domain?  I'm access authelia locally within my LAN.

**Comment by tfjield** [comment]
I forwarded a port and tested it from outside my LAN and there is a cookie called `session`, but no `authelia_session`.

**Comment by james-d-elliott** [comment]
Yeah the domain must be the same internally and externally. Can you show the session area of your config? 

You can redact it like this (where example.com is the part of your domain that you purchased, if the domain in this configuration area is a subdomain please leave the subdomain prefix):

```yaml
session:
  name: authelia_session
  domain: example.com
  same_site: lax
  secret: ***
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
```

**Comment by tfjield** [comment]
It's exactly the same but with a subdomain because I'm using a DDNS.  Could the DDNS be the problem?

**Comment by nightah** [comment]
I believe DDNS just like DuckDNS do not allow you to set the root domain as the session domain.

If you set everything under a subdomain and set your Authelia session domain to said subdomain it should work, for example, `mysite.ddns.org` which means you could protect `auth.mysite.ddns.org` `example1.mysite.ddns.org`.

**Comment by james-d-elliott** [comment]
If you need more support feel free to open a [discussion](https://github.com/authelia/authelia/discussions), visit the matrix/discord, or reply here.
