### ISSUE TITLE
Reset password expiration

### ISSUE THREAD

**Issue by JonasGutermuth** [authelia/authelia#3569]
## Feature Request
The JWT-Token submitted by the reset link is hard coded to expire after 5 minutes. https://github.com/authelia/authelia/blob/master/internal/model/identity_verification.go#L16 

### Description

It would be helpful to change this value in the configuration file. Maybe by adding:
```
session:
  jwt_timeout: 20m
```
### Use Case

Some of our customer's mail providers are very slow. So they can't reset the password in time.

**Comment by james-d-elliott** [comment]
Plan will be once we rework the process to use a manually entered OTP that we can add something like  this.

**Comment by james-d-elliott** [comment]
This will be rolled up into #3801 where we'll overhaul areas surrounding this. We'll reopen this issue it doesn't end up being part of the final design.
