### ISSUE TITLE
Redirection URL truncates retains only the first querystring parameter

### ISSUE THREAD

**Issue by balalogic** [authelia/authelia#3576]
### Description

Authelia seems to eliminate all but the first querystring parameter within the redirect URL. I'm currently using Authelia 4.35.6 integrated with nginx 1.22.0-alpine and have managed to configure MFA correctly using the sample configuration files within the Wiki. The only problem so far being the "removal" of querystring parameters within the URL encoded redirect string. In other words given -

Authelia endpoint: https://auth.example.com
Protected endpoint: https://protected.example.com?param1=x&param2=y

### Expected Behaviour

Redirect URL should contain all parameters destined for the target site -
https://auth.example.com?rd=https%3A%2F%2Fprotected.example.com%3Fparam1%3Dx%26param2%3Dy

### Current Behaviour

Redirect URL is truncated beyond the first Querystring parameter
https://auth.example.com?rd=https%3A%2F%2Fprotected.example.com%3Fparam1%3Dx

### Reproduction Steps

1. Open an incognito window in your browser.
2. Attempt to access a protected URL. If the URL does not have querystring parameters, manually append your own to the querystring.
3. You should be navigated to Authelia's logon page. Notice the redirection URL in the browser's address bar.

### Additional Information

_N/A_

**Comment by james-d-elliott** [comment]
Followed the reproduction steps and I cannot replicate:

`https://auth.example.com/?rd=https%3A%2F%2Fwhoami.example.com%2F%3Fa%3Dtest%26b%3Dtwo&rm=GET`

**Comment by james-d-elliott** [comment]
This is 100% not an Authelia bug. We may need to adjust our docs, or maybe it's a bug with nginx we can't work around. If you can run the `debug-header` container with log level debug it will reveal more I believe. I'll convert this to a Q&A discussion for now since I recall nginx having some issue with properly encoding URLs into query parameters.
