### ISSUE TITLE
SQL error when attempting to refresh sessions by request ID

### ISSUE THREAD

**Issue by nick-oconnor** [authelia/authelia#3600]
https://github.com/authelia/authelia/blob/e0da4c0dde894a112cb9cee6d6ee66cab6974cac/internal/storage/sql_provider_queries.go#L289 contains an extra `"` character, preventing sessions from being refreshed. The `"` should be removed.

**Comment by nick-oconnor** [comment]
This appears to have been fixed in master. I'd appreciate a release containing the fix. Thanks!

**Comment by james-d-elliott** [comment]
It will be released in a day or two.

**Comment by james-d-elliott** [comment]
For reference there is another open issue and another yet to be resolved issue with refresh sessions. Once the release is pushed we will have time to isolate and fix it. I'll link the issue once I'm at my desk

**Comment by nick-oconnor** [comment]
Sounds good! I assume you're referring to #3537? I'm running into that one now too...

**Comment by james-d-elliott** [comment]
Yep that's it!
