### ISSUE TITLE
 I hope authelia can add 钉钉 Login free 

### ISSUE THREAD

**Issue by nihao364097872** [authelia/authelia#3626]
https://open.dingtalk.com/abilities/24

**Comment by james-d-elliott** [comment]
The site is in a language none of the developers understand, and it can't easily be translated via means such as https://translate.google.com's website translate. I don't see us being able to determine if it's an appropriate integration let alone implement it securely.

If these factors could easily be overcome we may potentially reconsider, but if they cannot I don't think it's a good idea for security, and as such I'm sorry but I'm closing this issue as something we will not be doing.
