### ISSUE TITLE
Oauth2 login without ldap or yaml file

### ISSUE THREAD

**Issue by japrogramer** [authelia/authelia#3654]
## Feature Request
I have an application that creates a client_id and a client_secret for oauth2 apps.
I want to use one of this key pairs with Authelia so that I can authenticate other apps
which seat behind a proxy.

I don't have an ldap or a yml file with the usernames and hashed passwords, for first factor.
Instead I was hoping to use the oauth2 app for authentication with authelia.
Similar to how oauth2-proxy works.

### Use Case

I would like this because, oauth2-proxy does not integrate well with many servers, like caddy but authelia does.

**Comment by james-d-elliott** [comment]
See #2728
