### ISSUE TITLE
Make Authelia OTP field be 1 field

### ISSUE THREAD

**Issue by Skullduggeryism** [authelia/authelia#3665]
### Description

Make Authelia OTP field be 1 field

### Use Case

Currently, each digit of the OTP is a separate text input field.  I use 1Password for storing my MFA/2FA secrets, and on Desktop Chrome, it's able to autofill that field fine.  However, when using Chrome on a mobile device (specifically Android), it will attempt to autofill just the first digit.  I believe that if that OTP field were just one field, that would fix this issue.

It would be a nice if there were an option for this, or a theme/skin that did this.

**Comment by Skullduggeryism** [comment]
> Using TOTP via a password manager that stores your passwords and TOTP codes at the same time completely undermines the concept of multi factor auth. If you do it this way, you end up with one actual factor only. The first factor is knowledge (password) and the 2nd factor must be either the possession factor (something you have) or the inherence factor (something you are). Thus TOTP should run on a device like your cell phone. If both, passwords and TOTP are in your password safe anyway, you can simply deactivate TOTP. Problem solved.

Problem solved? You gave me your opinion in lieu of actually addressing the specific technical issue. I appreciate the security lesson, but I have accepted the trade-off between true second factor versus the one-timeness that 1Password TOTP offers me. Plus, 1password requires multiple factors (vault, password, secret key).

**Comment by HannesJo0139** [comment]
I see. It still is a bypass of the 2nd factor and I'm not sure if it should be supported. I understand the multiple input fields as a feature. However, does 1Password maybe have a keyboard shortcut to copy the TOTP code? I used that feature with KeepassXC for testing. Tap CTRL + T, click on the first input field, CTRL + V, thats all.

**Comment by Skullduggeryism** [comment]
> I see. It still is a bypass of the 2nd factor and I'm not sure if it should be supported. I understand the multiple input fields as a feature. However, does 1Password maybe have a keyboard shortcut to copy the TOTP code? I used that feature with KeepassXC for testing. Tap CTRL + T, click on the first input field, CTRL + V, thats all.

You don't think my particular use-case should be supported?  Why would you even care?

**Comment by HannesJo0139** [comment]
Correct. You placed a feature request and it is open for everyone to discuss. People may agree or disagree. Sorry if you don't like it.

**Comment by james-d-elliott** [comment]
It's something we discussed in the past for a more legitimate reason. But we can discuss it again.

> I believe that if that OTP field were just one field, that would fix this issue.

This is not actually a fix, it's a workaround for a bug in 1Password.

> It would be a nice if there were an option for this, or a theme/skin that did this.

I'll mock up an example (though it's by no means a priority, contributions welcome) and we can let the community decide in a poll which will include images, information on how to try it out, and detail the reasons for/against each idea. We'll either support the multiple fields or the single field, not both.

**Comment by Skullduggeryism** [comment]
> It's something we discussed in the past for a more legitimate reason. But we can discuss it again.
> 
> > I believe that if that OTP field were just one field, that would fix this issue.
> 
> This is not actually a fix, it's a workaround for a bug in 1Password.

Fair enough.

> > It would be a nice if there were an option for this, or a theme/skin that did this.
> 
> I'll mock up an example (though it's by no means a priority, contributions welcome) and we can let the community decide in a poll which will include images, information on how to try it out, and detail the reasons for/against each idea. We'll either support the multiple fields or the single field, not both.

Hmm.  It's certainly not my intention to alter the course of Authelia development to fit my particular use-case.  I was hoping a theme/skin could do the trick.

**Comment by jicho** [comment]
@Skullduggeryism can it be your 1PW version? I'm using 1PW 8.8 and it has no issues in Safari (macOS) when I use the autofill option.

And... on iOS I can paste the 2FA code without any issues. All digits are filled when I past the code.

**Comment by dougmaitelli** [comment]
> This is not actually a fix, it's a workaround for a bug in 1Password.

I don't think it is a 1Password bug, same behavior happens on Bitwarden just on mobile, exactly same thing. I believe it is some bug with Android Chrome Webview.

**Comment by TheToto** [comment]
I have the same problem when i try to copy/paste my OTP code on my Android phone, from the OTP app. It will paste to the first field only.

**Comment by Ohelig** [comment]
Seems to be a known issue with the otp input component Authelia uses. https://www.npmjs.com/package/react-otp-input & https://github.com/devfolioco/react-otp-input/issues/371
The package seems abandoned, no commits for 18 months. There is a newer maintained one at https://www.npmjs.com/package/react18-input-otp that fixes the Android paste issues (at least, in my test it did).

**Comment by Skullduggeryism** [comment]
> Seems to be a known issue with the otp input component Authelia uses. https://www.npmjs.com/package/react-otp-input & [devfolioco/react-otp-input#371](https://github.com/devfolioco/react-otp-input/issues/371) The package seems abandoned, no commits for 18 months. There is a newer maintained one at https://www.npmjs.com/package/react18-input-otp that fixes the Android paste issues (at least, in my test it did).

Can you explain how you were able to use the newer version of react in Authelia?  I'm interested in testing it out.

**Comment by Skullduggeryism** [comment]
> @Skullduggeryism can it be your 1PW version? I'm using 1PW 8.8.0 (latest beta) and it has no issues in Safari (macOS) when I use the autofill option.
> 
> And... on iOS I can paste the 2FA code without any issues. All digits are filled when I past the code.

I realized I never replied to this, I'm using 1PW v8 and it doesn't autofill the Authelia 2FA prompt, and when pasting, only pastes the first digit in the first box.

**Comment by james-d-elliott** [comment]
Try this: https://github.com/authelia/authelia/pull/4548

**Comment by Ohelig** [comment]
> Try this: #4548

Using the docker image in that PR fixed the problem for me. The input fields are smaller than they were before though.
<img src="https://user-images.githubusercontent.com/5841980/206931289-c47794d3-f62d-475b-9ed5-cac946032c39.png" width=30% height=30%>
<img src="https://user-images.githubusercontent.com/5841980/206931296-a870bc1a-3501-41f9-ab09-002d54e308dc.png" width=30% height=30%>

**Comment by james-d-elliott** [comment]
Looks like they put some inline styles which can't be removed so we'll have to use `!important`. Also I'm not entirely sure I like this: https://github.com/ritikbanger/react18-input-otp/commit/688c574b1eccaf6b07d252e0bfb696f9f56ff986#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7

**Comment by james-d-elliott** [comment]
The layout is fixed if you repull.

**Comment by Skullduggeryism** [comment]
Hmm, I get an interesting error when attempting to connect externally

`time="2022-12-11T20:29:43-05:00" level=error msg="Request timeout occurred while handling request from client." error="read tcp 172.26.0.18:9092->172.26.0.100:45766: i/o timeout" method=GET path=/ remote_ip=172.26.0.100 stack="github.com/authelia/authelia/v4/internal/server/handlers.go:72 handleError.func2\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2824             (*Server).writeErrorResponse\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2266             (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224          (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196          (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                       goexit" status_code=408`

172.26.0.18 is the authelia container
172.26.0.100 is traefik2

**Comment by james-d-elliott** [comment]
Unrelated to this.

**Comment by Skullduggeryism** [comment]
Confirmed OTP copy/paste is working with this build.  Thank you very much.

**Comment by tkuester** [comment]
Not fully sure if this is the proper way to resurrect this, but some additional thoughts. Just on Occam's Razor, I believe a single input field is the superior design choice.

* A single field may be simpler for users that depend on assistive technology such as a screen reader or keyboard navigation.
* JavaScript (or other automation) that shifts keyboard focus to other fields automatically is a somewhat hostile user experience that seems to violate design best practices.
* Multiple input fields seems to require more complicated logic than a single input field -- and complicated logic in security critical code seems to be frowned upon (even if it's just the frontend)

Thanks in advance for the consideration, and apologies if I've incorrectly resurrected this @james-d-elliott !
