### ISSUE TITLE
Input Autofocus

### ISSUE THREAD

**Issue by n4kre** [authelia/authelia#367]
Hi @clems4ever,

I observed that Authelia (version 3.15.0) does not have an autofocus feature for user input fields – e.g., login screen, password reset field, TOTP field, etc.

This could be cool to improve user experience, as it would save a lot of clicks. :)

**Comment by clems4ever** [comment]
Good remark, thanks!

**Comment by clems4ever** [comment]
I'm closing this issue in favor of #511 as I won't address v3.
