### ISSUE TITLE
Add 'Message-ID' header to outgoing e-mails

### ISSUE THREAD

**Issue by Leyvur** [authelia/authelia#3683]
### Description

It would be useful to add a unique `Message-ID` header to e-mails sent by authelia. For example:

> `Message-ID: <1234.foo.5678@authelia.example>`

### Use Case

E-mails without a `Message-ID` header often trigger the spamassassin/rspamd rule `MISSING_MID`.
As a result, authelia's e-mails are delayed or not delivered at all. Here is an example of the bad spam rating:

> X-Rspamd-Bar: +++
> X-Rspamd-Report: MIME_GOOD(-0.1) **MISSING_MID(2.5)** HEADER_DATE_EMPTY_DELIMITER(1) BAYES_HAM(-0.023147)
> X-Rspamd-Score: 3.376852

Delayed e-mails can cause problems with time-sensitive authentication processes. For example, see issue #3569

**Comment by nightah** [comment]
What underlying mail service do you have configured in Authelia, is it a self-hosted mail service?

I believe that the first mail server generates the `Message-ID`. Looking at my e-mails from Authelia all have a `Message-ID` present.

**Comment by james-d-elliott** [comment]
I agree with Amir on this one, it's generally the responsibility of the MSA to append this information to the email. Are you using the SUBMISSION/SUBMISSIONS port of your SMTP server? Authelia operates more like a MUA than a MSA/MTA.

That being said there is an error with the Date header that can easily be fixed.

**Comment by Leyvur** [comment]
My mail provider is uberspace.de and I had tested it with both port 465 and 587.

I tried to do more research on this header but found it to be a controversial topic.

**RFC 2822** states *(emphasis by me)*:
> Though optional, every message *SHOULD* have a "Message-ID:" field.

**RFC 2476**:
> The MSA *MAY* add or replace the 'Message-ID' field, if it lacks it, or it is not valid syntax (as defined by [MESSAGE-FORMAT]).

If I understand it correctly: The message creator (in this case the MUA/authelia) should always generate this header, because it is not guaranteed that the MSA will add it. But the MSA can modify the field if needed.
Besides, I think if the MSA would always add the 'Message-ID' field, the rspamd rule `MISSING_MID` would be meaningless.

So I would like to leave my feature request open, and would be happy if the header could be added!

**Comment by james-d-elliott** [comment]
See #3684. We're planning to add a template with access to a UUID and misc other information about SMTP. By default it will not have a `Message-ID` for now, but it's easy (with the example) to add it.

Regarding the RFC's:

Those RFC's are obsolete by about 18 years (i.e. they've been replaced). Also keep in mind the terminology they use is `MUST`, `SHOULD`,  and `MAY`; among others. RFC2119 defines these terms in particular: https://datatracker.ietf.org/doc/html/rfc2119#section-3

```
SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.
```

> The message creator (in this case the MUA/authelia) should always generate this header, because it is not guaranteed that the MSA will add it.

This is ironically one of the things the revised specs cleared up: https://datatracker.ietf.org/doc/html/rfc6409#section-8.3

This would indicate the message _SHOULD_ have a `Message-ID`, MSA's _SHOULD_ add it if not present or malformed. However the only thing missing clarity is exactly who is responsible. 

> I think if the MSA would always add the 'Message-ID' field, the rspamd rule `MISSING_MID` would be meaningless.

Not entirely accurate. The rspamd rule is meant to be applied (in my opinion) to server-to-server delivery, not client-to-server delivery. It's generally accepted that authenticated users are subject to less stringent rules. A message received from an unauthenticated server is effectively anonymous email other than the EHLO process.

**Comment by Leyvur** [comment]
> See #3684. We're planning to add a template with access to a UUID and misc other information about SMTP. By default it will not have a `Message-ID` for now, but it's easy (with the example) to add it.

Great, I think that's a nice solution!

> MSA's _SHOULD_ add it if not present or malformed

Thank you for the detailed explanation, I was not aware of the revised RFC (as you can tell, I don't often deal with email in such detail).

I'll let my provider know about this, maybe they are willing to adjust the configuration of their mail servers. If that's not possible, I'm looking forward to adding the header myself with your improved template system!

**Comment by james-d-elliott** [comment]
No worries at all about the specs, in my opinion they're a mess since they've both been revised 3 times and have no clarity about several areas.

**Comment by james-d-elliott** [comment]
See https://www.authelia.com/reference/guides/notification-templates/#envelope-template

Will be part of the next release (4.36.3)
