### ISSUE TITLE
How to use multiple ldap attributes in display_name_attribute?

### ISSUE THREAD

**Issue by baba2k** [authelia/authelia#3757]
Hi,

how to use multiple ldap attributes in display_name_attribute?

Something like that: display_name_attribute: givenName + " " + sn

Thanks!

Best

**Comment by nightah** [comment]
You cannot at the moment. Though what you're looking to do is typically what the `displayName` attribute is used for, it's usually the first name + last name.

**Comment by baba2k** [comment]
Hi @nightah,

too bad! Normally in ldap there are the first and last name in two separate fields. Therefore I would like to connect the fields givenName and sn (surName).

**Comment by james-d-elliott** [comment]
This would be part of #2868 if implemented. We'd not implement this in LDAP itself, rather allow users to obtain and map more attributes.
