### ISSUE TITLE
Feat: Password Reset Regulation

### ISSUE THREAD

**Issue by zoriax** [authelia/authelia#3859]
### Description
It could be necessary to have more security in the Reset Password form. A simple captcha and an option to prevent lot of attempts should (must) be implemented here :

![image](https://user-images.githubusercontent.com/12936546/185396394-549a6c66-63b6-4cec-8e11-e4c98caa9f0e.png)

Here with a bot or worst, with a simple "enter" you can spam thousand of e-mail to users. So for me it's a bug.

### Expected Behaviour
Captcha, attempts limitation and form reset should be implemented by design.

### Reproduction Steps
As mentioned, enter username and press enter a lot of time :-)

**Comment by james-d-elliott** [comment]
In the future if you think there's a security issue please follow our [security policy](https://github.com/authelia/authelia/security/policy). However this does not affect security, and while you may consider it a bug, the feature is not advertised and does not result in a functionality not working; thus we will classify it as a feature request.

**Comment by Ohelig** [comment]
In the meantime, you can achieve this with fail2ban. Follow the [existing documentation](https://www.authelia.com/overview/security/measures/#more-protections-measures-with-fail2ban) for using fail2ban, but replace your `authelia.conf` file with
```
# Fail2Ban filter for Authelia

# Make sure that the HTTP header "X-Forwarded-For" received by Authelia's backend
# only contains a single IP address (the one from the end-user), and not the proxy chain
# (it is misleading: usually, this is the purpose of this header).

# the failregex rule counts every failed 1FA attempt (first line, wrong username or password) and failed 2FA attempt
# second line) as a failure.
# the ignoreregex rule ignores info and warning messages
# the third line catches incorrect usernames entered at the password reset form
# the fourth line catches attempts to spam via the password reset form or totp reset form. This requires debug logging to be enabled

[Definition]
failregex = ^.*Unsuccessful 1FA authentication attempt by user .*remote_ip="?<HOST>"? stack.*
            ^.*Unsuccessful (TOTP|Duo|U2F) authentication attempt by user .*remote_ip="?<HOST>"? stack.*
            ^.*user not found.*path=/api/reset-password/identity/start remote_ip="?<HOST>"? stack.*
            ^.*Sending an email to user.*path=/api/.*/start remote_ip="?<HOST>"?

ignoreregex = ^.*level=info.*
              ^.*level=warning.*
```

**Comment by nightah** [comment]
@Ohelig please feel free to PR said changes to the docs, I think it'd be a very welcome addition.

**Comment by Ohelig** [comment]
> @Ohelig please feel free to PR said changes to the docs, I think it'd be a very welcome addition.

https://github.com/authelia/authelia/pull/4630

**Comment by james-d-elliott** [comment]
See #4730

**Comment by james-d-elliott** [comment]
@all-contributors please add @Ohelig for docs
