### ISSUE TITLE
Question: configuration of userinfo endpoint for OpenID

### ISSUE THREAD

**Issue by Northguy** [authelia/authelia#3869]
I am trying to integrate the Social Login features of another project (Komga) with Authelia. I was able to configure Bookstack with oAuth, but I seem unable to use Authelia with Komga. I am unsure where my mistake or misconception is. The error I am receiving from Komga (Spring Boot security)

`org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_user_info_response] An error occurred while attempting to retrieve the UserInfo Resource from 'https://authenticate.<<mydomain>>/api/oidc/userinfo': response contains invalid content type 'application/jwt'. The UserInfo Response should return a JSON object (content type 'application/json') that contains a collection of name and value pairs of the claims about the authenticated End-User. Please ensure the UserInfo Uri in UserInfoEndpoint for Client Registration 'authelia' conforms to the UserInfo Endpoint, as defined in OpenID Connect 1.0: 'https://openid.net/specs/openid-connect-core-1_0.html#UserInfo'`

Can someone point me in the right direction? Is this something that I need to configure on the Authelia side, or on the Komga side?

My configuration for spring security is quite minimal:

```spring:
  security:
    oauth2:
      client:
        registration:
          authelia:
            client-id: komga-auth
            client-secret: <<my secret>>
            client-name: Authelia
            scope: openid, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseScheme}://{baseHost}{basePort}{basePath}/login/oauth2/code/authelia"
            
        provider:
          authelia:
            issuer-uri: https://authenticate.<<mydomain>>
            user-name-attribute: email
```

**Comment by Northguy** [comment]
Heaving read this: https://github.com/spring-projects/spring-security/issues/9583 it seems that Authelia is correct and that Spring has a gap to fill?

**Comment by james-d-elliott** [comment]
Try setting [userinfo_signing_algorithm](https://www.authelia.com/configuration/identity-providers/open-id-connect/#userinfo_signing_algorithm) to none, this changes the response to JSON.

**Comment by Northguy** [comment]
@james-d-elliott , thank you so much. Overlooked that one. Thanks for pointing it out.

**Comment by Vageesh-Jayaraman** [comment]
Try this: [https://github.com/spring-projects/spring-security/issues/11639#issuecomment-3040909884](https://github.com/spring-projects/spring-security/issues/11639#issuecomment-3040909884)


> I am trying to integrate the Social Login features of another project (Komga) with Authelia. I was able to configure Bookstack with oAuth, but I seem unable to use Authelia with Komga. I am unsure where my mistake or misconception is. The error I am receiving from Komga (Spring Boot security)
> 
> `org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_user_info_response] An error occurred while attempting to retrieve the UserInfo Resource from 'https://authenticate.<<mydomain>>/api/oidc/userinfo': response contains invalid content type 'application/jwt'. The UserInfo Response should return a JSON object (content type 'application/json') that contains a collection of name and value pairs of the claims about the authenticated End-User. Please ensure the UserInfo Uri in UserInfoEndpoint for Client Registration 'authelia' conforms to the UserInfo Endpoint, as defined in OpenID Connect 1.0: 'https://openid.net/specs/openid-connect-core-1_0.html#UserInfo'`
> 
> Can someone point me in the right direction? Is this something that I need to configure on the Authelia side, or on the Komga side?
> 
> My configuration for spring security is quite minimal:
> 
> ```
>   security:
>     oauth2:
>       client:
>         registration:
>           authelia:
>             client-id: komga-auth
>             client-secret: <<my secret>>
>             client-name: Authelia
>             scope: openid, email
>             authorization-grant-type: authorization_code
>             redirect-uri: "{baseScheme}://{baseHost}{basePort}{basePath}/login/oauth2/code/authelia"
>             
>         provider:
>           authelia:
>             issuer-uri: https://authenticate.<<mydomain>>
>             user-name-attribute: email
> ```
