### ISSUE TITLE
Possible to disable "Forgot Password"?

### ISSUE THREAD

**Issue by davama** [authelia/authelia#387]
Currently as stated here, https://github.com/clems4ever/authelia/issues/361 any password could be used. 

Is it possible to disable this feature altogether? 

Thanks!

**Comment by clems4ever** [comment]
It's not yet possible unfortunately but it should not be hard to implement by not registering the API endpoints and tweaking a bit the UI to remove the link when the feature is disabled.

I'll have a look.

**Comment by davama** [comment]
Thank you!

**Comment by tgruenert** [comment]
It would nice to see this posibility. 
Additional in my use case it would be perfect if i could define a link which redirects to my existing password reset function. we have more requiremenents as these are implemented at authelia at this moment.

**Comment by davama** [comment]
If there were password complexity, then this would be issue null

I prefer the complexity part instead of disable but more options are always good 👍

See #361

**Comment by naggie** [comment]
If you need to do it now, inject some CSS with nginx `sub_filter` to set the element to `display:none` : 

Nginx location:
<img width="667" alt="image" src="https://user-images.githubusercontent.com/208440/77565993-f154e080-6ebc-11ea-927f-55affd0c200f.png">

Override.css:

<img width="197" alt="image" src="https://user-images.githubusercontent.com/208440/77566055-0762a100-6ebd-11ea-895a-a198299c3f55.png">

**Comment by davama** [comment]
@naggie 
That’s brilliant!
Thanks 👍

**Comment by james-d-elliott** [comment]
@davama @naggie @tgruenert we're working on this feature right now, you should see a release today or at latest tomorrow.

**Comment by james-d-elliott** [comment]
Feel free to try it out with the docker image authelia/authelia:feature-disable-forgot-password

Configuration is:

```
authentication_backend:
  disable_reset_password: true
```

**Comment by tgruenert** [comment]
Dear @james-d-elliott ,
thank you for your response on this task. I am happy to confirm that the feature disabling is working as excepted. Thanks a lot for that. Happy to see a merge to next release ;-).

**Comment by james-d-elliott** [comment]
It's now merged into master. Expect to see this in 4.12.0 release later today or so.

**Comment by james-d-elliott** [comment]
@davama @tgruenert @naggie this is now part of release 4.12.0 (will be published in about 20 mins).

https://docs.authelia.com/configuration/authentication/

**Comment by naggie** [comment]
Works great, thanks @james-d-elliott -- I've removed my hack!

**Comment by davama** [comment]
Thank you @james-d-elliott
