### ISSUE TITLE
OTP "Register device" not sending redirection URL to e-mail

### ISSUE THREAD

**Issue by mirek-benes** [authelia/authelia#3909]
### Description

User is connecting to the target application via Authelia authenticator for the first time.
He successfully logs in.
He is asked to register device for 2FA One-Time Password.
User clicks to "Register device".
Receives an e-mail with the registration link in format ://auth.domain.cz/one-time-password/register?token=tokenstring
After registering new device authelia redirects user to "default_redirection_url".
We are using Authelia for multiple applications, therefore default_redirection_url is set to "403 deny page".
The result is that user is redirected to "403 deny page" after every successful device registration.

### Expected Behaviour

User should be redirected to the target application after successful device registration.

### Additional Information

The link in OTP e-mail doesn't contain information about the target URL (missing rd=targeturl) so Authelia uses the default_redirection_url.

**Comment by james-d-elliott** [comment]
Making this part of #3801 since it will resolve the issue.
