### ISSUE TITLE
OIDC token renewal failing from Outline (error logs don't contain enough info)

### ISSUE THREAD

**Issue by szinn** [authelia/authelia#3913]
### Description

Followed the integration instructions between Outline and Authelia. Logging in works and everything seems fine. However, Outline calls to refresh an expiring token and gets an Invalid Authentication error. Authelia has

```time="2022-08-26T21:47:37Z" level=trace msg="Request hit" method=POST path=/api/oidc/token remote_ip=10.40.2.97
time="2022-08-26T21:47:37Z" level=error msg="Access Request failed with error: The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client. The refresh token has not been found: not_found" method=POST path=/api/oidc/token remote_ip=10.40.2.97 stack="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_token.go:27                   OpenIDConnectTokenPOST\ngithub.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:113 time="2022-08-26T21:47:37Z" level=trace msg="Replied (status=400)" method=POST path=/api/oidc/token remote_ip=10.40.2.97
```

The error level doesn't provide enough detail to understand exactly what isn't valid in the call.

### Expected Behaviour

More details in the error message to indicate what isn't valid.
### Reproduction Steps

Configure Authelia/Outline integration as described in the integrations section of Outline (https://www.authelia.com/integration/openid-connect/outline/) Log into Authelia. Log into Outline. Wait and eventually the error log lines will show in both applications.

**Comment by james-d-elliott** [comment]
Seems like Outline is using a refresh token that isn't being issued which in my opinion is a bug on their end. You can band-aid this by adding the `offline_access` scope to both Outlines config and Authelia's config per the OIDC integration docs. But realistically they should perform authorization again if the refresh token isn't issued, and definitely shouldn't if the scope isn't requested to facilitate the refresh token.

Not entirely sure how you consider this a bug with Authelia though.

**Comment by szinn** [comment]
Thanks for the info - I can follow up with Outline team. It could be considered a low-priority bug as the error log entry doesn't contain enough detail to actually figure out what the real problem is. I will check and see what they are doing but they might actually be doing an authorization again already which is likely why it continues to work.

**Comment by james-d-elliott** [comment]
> Thanks for the info - I can follow up with Outline team. It could be considered a low-priority bug as the error log entry doesn't contain enough detail to actually figure out what the real problem is. I will check and see what they are doing but they might actually be doing an authorization again already which is likely why it continues to work.

Well I can kind of see how it may not be straight forward. I'm not entirely sure how we can make it clearer in this instance as a third party using a theoretically blank refresh token to try to refresh the access token is kind of odd. The key part of the log which made it clear to me was `The refresh token has not been found: not_found`. I'll update that community driven doc though to make sure it actually works.
