### ISSUE TITLE
auth request unexpected status: 304

### ISSUE THREAD

**Issue by shioku** [authelia/authelia#394]
Hi,

i have the following problem with nextcloud behind a nginx proxy when authelia is active.

If i try to upload a file i get an unexpected error in nextcloud.
Testfile in the following logs is: nextcloud.log

**The following lines are loggin in the nginx access.log:**

127.0.0.1 - - [08/Sep/2019:22:42:06 +0200] "GET /api/verify HTTP/1.0" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"

192.168.60.20 - - [08/Sep/2019:22:42:06 +0200] "PUT /remote.php/webdav/nextcloud.log HTTP/2.0" 500 688 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"

**and the follwing line in the nginx error.log:**

2019/09/08 22:42:06 [error] 3685#3685: *1 auth request unexpected status: 304 while sending to client, client: 192.168.60.20, server: nextcloud.mydomain, request: "PUT /remote.php/webdav/nextcloud.log HTTP/2.0", host: "nextcloud.mydomain"

Authelia runs as Docker Container on localhost.

I tried to disable caching with different options in the following locations:

- nginx.conf
- site config - nextcloud proxy (nextcloud.<mydomain>)
- site config - authelia proxy to docker (login.<mydomain>)

If i remove the authelia config and access nextcloud via proxy everything works.
Everything except uploading seems to work.

**Comment by clems4ever** [comment]
I need more info to be able to help you. Please paste your nginx config, authelia config and a snippet of Authelia logs where we can see the issue.

**Comment by shioku** [comment]
Hello, 
following are snippets of the logs.
The file "test.txt" was uploaded on 2019/09/29 14:23:14.


**Access Log:**

> 192.168.9.10 - - [29/Sep/2019:14:23:09 +0200] "GET /index.php/apps/files_external/userglobalstorages/1?testOnly=false HTTP/2.0" 200 199 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
127.0.0.1 - - [29/Sep/2019:14:23:09 +0200] "GET /api/verify HTTP/1.0" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
192.168.9.10 - - [29/Sep/2019:14:23:09 +0200] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/2.0" 200 257 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
192.168.9.10 - - [29/Sep/2019:14:23:09 +0200] "GET /index.php/apps/recommendations/api/recommendations HTTP/2.0" 200 1621 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
127.0.0.1 - - [29/Sep/2019:14:23:10 +0200] "GET /api/verify HTTP/1.0" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
127.0.0.1 - - [29/Sep/2019:14:23:10 +0200] "GET /api/verify HTTP/1.0" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
192.168.9.10 - - [29/Sep/2019:14:23:10 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
192.168.9.10 - - [29/Sep/2019:14:23:10 +0200] "GET /index.php/apps/files_external/userglobalstorages/1?testOnly=false HTTP/2.0" 200 199 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
127.0.0.1 - - [29/Sep/2019:14:23:14 +0200] "GET /api/verify HTTP/1.0" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
192.168.9.10 - - [29/Sep/2019:14:23:14 +0200] "PUT /remote.php/webdav/Test.txt HTTP/2.0" 500 186 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
127.0.0.1 - - [29/Sep/2019:14:23:14 +0200] "GET /api/verify HTTP/1.0" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
192.168.9.10 - - [29/Sep/2019:14:23:14 +0200] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/2.0" 200 257 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
127.0.0.1 - - [29/Sep/2019:14:23:39 +0200] "GET /api/verify HTTP/1.0" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"
192.168.9.10 - - [29/Sep/2019:14:23:39 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0"

**Error Log:**

> 2019/09/29 14:23:14 [error] 7208#7208: *2146 auth request unexpected status: 304 while sending to client, client: 192.168.9.10, server: nextcloud.example.com, request: "PUT /remote.php/webdav/Test.txt HTTP/2.0", host: "nextcloud.example.com"

**Authelia:**

> debug: date='Sun Sep 29 2019 12:23:09 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_3' sessionId='mysessionid' ip='127.0.0.1' message='Header x-original-url is set to https://nextcloud.example.com/index.php/apps/files/ajax/getstoragestats.php?dir=%2F'
debug: date='Sun Sep 29 2019 12:23:09 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_3' sessionId='mysessionid' ip='127.0.0.1' message='domain=nextcloud.example.com, path=/index.php/apps/files/ajax/getstoragestats.php, user=myuser, groups=mygroups, ip=127.0.0.1'
debug: date='Sun Sep 29 2019 12:23:09 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_3' sessionId='mysessionid' ip='127.0.0.1' message='Inactivity period was 0.205 sec and max period was 3600 sec.'
debug: date='Sun Sep 29 2019 12:23:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_1' sessionId='mysessionid' ip='127.0.0.1' message='Headers = {"host":"login.example.com","x-forwarded-proto":"https","x-real-ip":"127.0.0.1","x-forwarded-for":"127.0.0.1, 192.168.9.10, 127.0.0.1","x-forwarded-ssl":"on","x-forwarded-host":"login.example.com","x-forwarded-uri":"/api/verify","connection":"close","x-original-url":"https://nextcloud.example.com/index.php/apps/files_external/userglobalstorages/1?testOnly=false","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0","accept":"*/*","accept-language":"de,en-US;q=0.7,en;q=0.3","accept-encoding":"gzip, deflate, br","requesttoken":"cVH...Yg=","ocs-apirequest":"true","x-requested-with":"XMLHttpRequest","cookie":"__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=29D...55C; nc_token=BqW...wDo; nc_session_id=id_1; authelia_session=s%3...NI8; oce...yoi=gt4...e50; oc_sessionPassphrase=eP%...vfL"}'
debug: date='Sun Sep 29 2019 12:23:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_1' sessionId='mysessionid' ip='127.0.0.1' message='Header x-original-url is set to https://nextcloud.example.com/index.php/apps/files_external/userglobalstorages/1?testOnly=false'
debug: date='Sun Sep 29 2019 12:23:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_1' sessionId='mysessionid' ip='127.0.0.1' message='domain=nextcloud.example.com, path=/index.php/apps/files_external/userglobalstorages/1, user=myuser, groups=mygroups, ip=127.0.0.1'
debug: date='Sun Sep 29 2019 12:23:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_1' sessionId='mysessionid' ip='127.0.0.1' message='Inactivity period was 0.342 sec and max period was 3600 sec.'
debug: date='Sun Sep 29 2019 12:23:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_2' sessionId='mysessionid' ip='127.0.0.1' message='Headers = {"host":"login.example.com","x-forwarded-proto":"https","x-real-ip":"127.0.0.1","x-forwarded-for":"127.0.0.1, 192.168.9.10, 127.0.0.1","x-forwarded-ssl":"on","x-forwarded-host":"login.example.com","x-forwarded-uri":"/api/verify","connection":"close","x-original-url":"https://nextcloud.example.com/ocs/v2.php/apps/notifications/api/v2/notifications","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0","accept":"application/json, text/plain, */*","accept-language":"de,en-US;q=0.7,en;q=0.3","accept-encoding":"gzip, deflate, br","requesttoken":"cVH...Yg=","cookie":"__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=29D...55C; nc_token=BqW...wDo; nc_session_id=id_1; authelia_session=s%3...NI8; oce...yoi=gt4...e50; oc_sessionPassphrase=eP%...vfL"}'
debug: date='Sun Sep 29 2019 12:23:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_2' sessionId='mysessionid' ip='127.0.0.1' message='Header x-original-url is set to https://nextcloud.example.com/ocs/v2.php/apps/notifications/api/v2/notifications'
debug: date='Sun Sep 29 2019 12:23:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_2' sessionId='mysessionid' ip='127.0.0.1' message='domain=nextcloud.example.com, path=/ocs/v2.php/apps/notifications/api/v2/notifications, user=myuser, groups=mygroups, ip=127.0.0.1'
debug: date='Sun Sep 29 2019 12:23:10 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_2' sessionId='mysessionid' ip='127.0.0.1' message='Inactivity period was 0.017 sec and max period was 3600 sec.'
debug: date='Sun Sep 29 2019 12:23:14 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_4' sessionId='mysessionid' ip='127.0.0.1' message='Headers = {"host":"login.example.com","x-forwarded-proto":"https","x-real-ip":"127.0.0.1","x-forwarded-for":"127.0.0.1, 192.168.9.10, 127.0.0.1","x-forwarded-ssl":"on","x-forwarded-host":"login.example.com","x-forwarded-uri":"/api/verify","connection":"close","x-original-url":"https://nextcloud.example.com/remote.php/webdav/Test.txt","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0","accept":"*/*","accept-language":"de,en-US;q=0.7,en;q=0.3","accept-encoding":"gzip, deflate, br","content-type":"text/plain","if-none-match":"*","content-disposition":"attachment; filename=\"Test.txt\"","requesttoken":"cVH...Yg=","ocs-apirequest":"true","x-requested-with":"XMLHttpRequest","cookie":"__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=29D...55C; nc_token=BqW...wDo; nc_session_id=id_1; authelia_session=s%3...NI8; oce...yoi=gt4...e50; oc_sessionPassphrase=eP%...vfL"}'
debug: date='Sun Sep 29 2019 12:23:14 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_4' sessionId='mysessionid' ip='127.0.0.1' message='Header x-original-url is set to https://nextcloud.example.com/remote.php/webdav/Test.txt'
debug: date='Sun Sep 29 2019 12:23:14 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_4' sessionId='mysessionid' ip='127.0.0.1' message='domain=nextcloud.example.com, path=/remote.php/webdav/Test.txt, user=myuser, groups=mygroups, ip=127.0.0.1'
debug: date='Sun Sep 29 2019 12:23:14 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_4' sessionId='mysessionid' ip='127.0.0.1' message='Inactivity period was 4.257 sec and max period was 3600 sec.'
debug: date='Sun Sep 29 2019 12:23:14 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_5' sessionId='mysessionid' ip='127.0.0.1' message='Headers = {"host":"login.example.com","x-forwarded-proto":"https","x-real-ip":"127.0.0.1","x-forwarded-for":"127.0.0.1, 192.168.9.10, 127.0.0.1","x-forwarded-ssl":"on","x-forwarded-host":"login.example.com","x-forwarded-uri":"/api/verify","connection":"close","x-original-url":"https://nextcloud.example.com/index.php/apps/files/ajax/getstoragestats.php?dir=%2F","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0","accept":"application/json, text/javascript, */*; q=0.01","accept-language":"de,en-US;q=0.7,en;q=0.3","accept-encoding":"gzip, deflate, br","requesttoken":"cVH...Yg=","ocs-apirequest":"true","x-requested-with":"XMLHttpRequest","cookie":"__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=29D...55C; nc_token=BqW...wDo; nc_session_id=id_1; authelia_session=s%3...NI8; oce...yoi=gt4...e50; oc_sessionPassphrase=eP%...vfL"}'
debug: date='Sun Sep 29 2019 12:23:14 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_5' sessionId='mysessionid' ip='127.0.0.1' message='Header x-original-url is set to https://nextcloud.example.com/index.php/apps/files/ajax/getstoragestats.php?dir=%2F'
debug: date='Sun Sep 29 2019 12:23:14 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_5' sessionId='mysessionid' ip='127.0.0.1' message='domain=nextcloud.example.com, path=/index.php/apps/files/ajax/getstoragestats.php, user=myuser, groups=mygroups, ip=127.0.0.1'
debug: date='Sun Sep 29 2019 12:23:14 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_5' sessionId='mysessionid' ip='127.0.0.1' message='Inactivity period was 0.3 sec and max period was 3600 sec.'
debug: date='Sun Sep 29 2019 12:23:39 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_6' sessionId='mysessionid' ip='127.0.0.1' message='Headers = {"host":"login.example.com","x-forwarded-proto":"https","x-real-ip":"127.0.0.1","x-forwarded-for":"127.0.0.1, 192.168.9.10, 127.0.0.1","x-forwarded-ssl":"on","x-forwarded-host":"login.example.com","x-forwarded-uri":"/api/verify","connection":"close","x-original-url":"https://nextcloud.example.com/ocs/v2.php/apps/notifications/api/v2/notifications","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0","accept":"application/json, text/plain, */*","accept-language":"de,en-US;q=0.7,en;q=0.3","accept-encoding":"gzip, deflate, br","requesttoken":"cVH...Yg=","cookie":"__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=29D...55C; nc_token=BqW...wDo; nc_session_id=id_1; authelia_session=s%3...NI8; oce...yoi=gt4...e50; oc_sessionPassphrase=eP%...vfL"}'
debug: date='Sun Sep 29 2019 12:23:39 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_6' sessionId='mysessionid' ip='127.0.0.1' message='Header x-original-url is set to https://nextcloud.example.com/ocs/v2.php/apps/notifications/api/v2/notifications'
debug: date='Sun Sep 29 2019 12:23:39 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_6' sessionId='mysessionid' ip='127.0.0.1' message='domain=nextcloud.example.com, path=/ocs/v2.php/apps/notifications/api/v2/notifications, user=myuser, groups=mygroups, ip=127.0.0.1'
debug: date='Sun Sep 29 2019 12:23:39 GMT+0000 (UTC)' method='GET', path='/api/verify' requestId='id_6' sessionId='mysessionid' ip='127.0.0.1' message='Inactivity period was 25.191 sec and max period was 3600 sec.'

**Comment by shioku** [comment]
**Authelia Config:**

```###############################################################
#                   Authelia configuration                    #
###############################################################

# The port to listen on
port: 9091

# Log level
#
# Level of verbosity for logs
logs_level: debug

# Default redirection URL
#
# If user tries to authenticate without any referer, Authelia
# does not know where to redirect the user to at the end of the
# authentication process.
# This parameter allows you to specify the default redirection
# URL Authelia will use in such a case.
#
# Note: this parameter is optional. If not provided, user won't
# be redirected upon successful authentication.
default_redirection_url: https://example.com/

# TOTP Issuer Name
#
# This will be the issuer name displayed in Google Authenticator
# See: https://github.com/google/google-authenticator/wiki/Key-Uri-Format for more info on issuer names
totp:
  issuer: example.com

# Duo Push API
#
# Parameters used to contact the Duo API. Those are generated when you protect an application
# of type "Partner Auth API" in the management panel.
duo_api:
<removed>

# The authentication backend to use for verifying user passwords
# and retrieve information such as email address and groups
# users belong to.
#
# There are two supported backends: `ldap` and `file`.
authentication_backend:
  # LDAP backend configuration.
  #
  # This backend allows Authelia to be scaled to more
  # than one instance and therefore is recommended for
  # production.
  ldap:
    <removed>

  # File backend configuration.
  #
  # With this backend, the users database is stored in a file
  # which is updated when users reset their passwords.
  # Therefore, this backend is meant to be used in a dev environment
  # and not in production since it prevents Authelia to be scaled to
  # more than one instance.
  #
  ## file:
  ##   path: ./users_database.yml


# Access Control
#
# Access control is a list of rules defining the authorizations applied for one
# resource to users or group of users.
#
# If 'access_control' is not defined, ACL rules are disabled and the `bypass`
# rule is applied, i.e., access is allowed to anyone. Otherwise restrictions follow
# the rules defined.
#
# Note: One can use the wildcard * to match any subdomain.
# It must stand at the beginning of the pattern. (example: *.mydomain.com)
#
# Note: You must put patterns containing wildcards between simple quotes for the YAML
# to be syntaxically correct.
#
# Definition: A `rule` is an object with the following keys: `domain`, `subject`,
# `policy` and `resources`.
#
# - `domain` defines which domain or set of domains the rule applies to.
#
# - `subject` defines the subject to apply authorizations to. This parameter is
#    optional and matching any user if not provided. If provided, the parameter
#    represents either a user or a group. It should be of the form 'user:<username>'
#    or 'group:<groupname>'.
#
# - `policy` is the policy to apply to resources. It must be either `bypass`,
#   `one_factor`, `two_factor` or `deny`.
#
# - `resources` is a list of regular expressions that matches a set of resources to
#    apply the policy to. This parameter is optional and matches any resource if not
#    provided.
#
# Note: the order of the rules is important. The first policy matching
# (domain, resource, subject) applies.
access_control:
  # Default policy can either be `bypass`, `one_factor`, `two_factor` or `deny`.
  # It is the policy applied to any resource if there is no policy to be applied
  # to the user.
  default_policy: deny

  rules:
    # All Subdomains
    - domain: '*.example.com'
      policy: two_factor
      subject: 'group:mygroup'

# Configuration of session cookies
#
# The session cookies identify the user once logged in.
session:
  # The name of the session cookie. (default: authelia_session).
  name: authelia_session

  # The secret to encrypt the session cookie.
  secret: <removed>

  # The time in ms before the cookie expires and session is reset.
  expiration: 86400000 # 24 hours

  # The inactivity time in ms before the session is reset.
  inactivity: 3600000 # 1 hour

  # The domain to protect.
  # Note: the authenticator must also be in that domain. If empty, the cookie
  # is restricted to the subdomain of the issuer.
  domain: example.com

  # The redis connection details
  #redis:
    #host: 127.0.0.1
    #port: 6379
    #password: authelia

# Configuration of the authentication regulation mechanism.
#
# This mechanism prevents attackers from brute forcing the first factor.
# It bans the user if too many attempts are done in a short period of
# time.
regulation:
  # The number of failed login attempts before user is banned.
  # Set it to 0 to disable regulation.
  max_retries: 3

  # The time range during which the user can attempt login before being banned.
  # The user is banned if the authenticaction failed `max_retries` times in a `find_time` seconds window.
  find_time: 120

  # The length of time before a banned user can login again.
  ban_time: 300

# Configuration of the storage backend used to store data and secrets.
#
# You must use only an available configuration: local, mongo
storage:
  # The directory where the DB files will be saved
  local:
    path: /var/lib/authelia/store

  # Settings to connect to mongo server
  #mongo:
    #url: mongodb://127.0.0.1
    #database: authelia
    #auth:
      #username: authelia
      #password: authelia

# Configuration of the notification system.
#
# Notifications are sent to users when they require a password reset, a u2f
# registration or a TOTP registration.
# Use only an available configuration: filesystem, gmail
notifier:
  # For testing purpose, notifications can be sent in a file
  ## filesystem:
  ##   filename: /tmp/authelia/notification.txt

  # Use your email account to send the notifications. You can use an app password.
  # List of valid services can be found here: https://nodemailer.com/smtp/well-known/
  ## email:
  ##   username: user@example.com
  ##   password: yourpassword
  ##   sender: admin@example.com
  ##   service: gmail

  # Use a SMTP server for sending notifications
  smtp:
    <removed>
```

**Comment by shioku** [comment]
**nginx server block:**

```
server {
        # Listener
        listen 443 ssl http2; listen [::]:443 ssl http2;
        server_name nextcloud.example.com;

        # SSL-Config
        include /etc/nginx/config/ssl.conf;

        # Location
        location / {
                # Authelia - Auth Request
                include /etc/nginx/config/authelia_auth_request.conf;

                # Target
                proxy_pass                              https://nextcloud.example.com;

                # Proxy-SSL
                proxy_ssl_trusted_certificate           /etc/nginx/ssl/CA.crt;
                proxy_ssl_verify                        on;
                proxy_ssl_server_name                   on;

                # Proxy-Parameter
                proxy_set_header Host                   $host;
                proxy_set_header X-Real-IP              $remote_addr;
                proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto      $scheme;

                # Location-Parameter
                client_max_body_size                    0;

                # Hide Headers - because they are already set by nextcloud
                proxy_hide_header X-Content-Type-Options;
                proxy_hide_header X-Frame-Options;
        }

        # Location for CardDAV
        location /.well-known/carddav {
                return 301 $scheme://$host/remote.php/dav;
        }

        # Location for CalDAV
        location /.well-known/caldav {
                return 301 $scheme://$host/remote.php/dav;
        }

        # Authelia - Location
        include /etc/nginx/config/authelia_auth_location.conf;

}

```

**authelia_auth_request**

```
# Send a subsequent request to Authelia to verify if the user is authenticated
# and has the right permissions to access the resource.
auth_request /auth_verify;

# Set the X-Forwarded-User and X-Forwarded-Groups with the headers
# returned by Authelia for the backends which can consume them.
# This is not safe, as the backend must make sure that they come from the
# proxy. In the future, it's gonna be safe to just use OAuth.
auth_request_set            $user $upstream_http_remote_user;
proxy_set_header            X-Forwarded-User $user;

auth_request_set            $groups $upstream_http_remote_groups;
proxy_set_header            X-Forwarded-Groups $groups;

# Set the `target_url` variable based on the request. It will be used to build the portal
# URL with the correct redirection parameter.
auth_request_set            $target_url $scheme://$http_host$request_uri;

# If Authelia returns 401, then nginx redirects the user to the login portal.
# If it returns 200, then the request pass through to the backend.
# For other type of errors, nginx will handle them as usual.
# NOTE: do not forget to include /#/ representing the hash router of the web application.
error_page                  401 =302 https://login.example.com/#/?rd=$target_url;

```

**authelia_auth_location.conf**

```
location /auth_verify {
        internal;

        # [OPTIONAL] The IP of the client shown in Authelia logs.
        proxy_set_header            X-Real-IP $remote_addr;

        # [REQUIRED] Needed by Authelia to check authorizations of the resource.
        # Provide either X-Original-URL and X-Forwarded-Proto or
        # X-Forwarded-Proto, X-Forwarded-Host and X-Forwarded-Uri or both.
        # Those headers will be used by Authelia to deduce the target url of the user.
        #
        # X-Forwarded-Proto is mandatory since Authelia uses the "trust proxy" option.
        # See https://expressjs.com/en/guide/behind-proxies.html
        proxy_set_header            X-Original-URL $scheme://$http_host$request_uri;

        proxy_set_header            X-Forwarded-Proto $scheme;
        proxy_set_header            X-Forwarded-Host $http_host;
        proxy_set_header            X-Forwarded-Uri $request_uri;

        # [OPTIONAL] The list of IPs of client and proxies in the chain.
        proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass_request_body     off;
        proxy_set_header            Content-Length "";
        proxy_pass                  https://login.example.com/api/verify;

}
```

**Comment by shioku** [comment]
Updated to v4 and it seems to work now.

i removed my workaround with a location of "/remote.php/webdav/" where authelia was disabled after the update, restarted the nginx service and tested to upload a file to nextcloud which was uploaded without error and seems to be fine.
