### ISSUE TITLE
segmentation violation Error

### ISSUE THREAD

**Issue by crypticviper** [authelia/authelia#3946]
Hello,

I tried to set up authelia on my local setup (RaspberryPi running OMV 6.x using docker/portainer). However, I keep getting the below error in my container logs.

time="2022-09-02T23:53:20+02:00" level=info msg="Authelia v4.36.6 is starting"
time="2022-09-02T23:53:20+02:00" level=info msg="Log severity set to debug"
time="2022-09-02T23:53:20+02:00" level=info msg="Storage schema is being checked for updates"
time="2022-09-02T23:53:20+02:00" level=info msg="Storage schema is already up to date"
time="2022-09-02T23:53:20+02:00" level=debug msg="notification provider: startup check skipped as it is disabled"
time="2022-09-02T23:53:20+02:00" level=debug msg="The NTP startup check was skipped due to there being no configured 2FA access control rules"
time="2022-09-02T23:53:20+02:00" level=info msg="Shutting down"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaf4dc0]
goroutine 1 [running]:
github.com/valyala/fasthttp.(*Server).Shutdown(0x0)
	github.com/valyala/fasthttp@v1.39.0/server.go:1819 +0x38
github.com/authelia/authelia/v4/internal/commands.runServers(0x2d6e000, {0x313a810, 0x313a828, 0x3142360, {{0x0, 0x0}, 0x0, 0x0, 0x0, {{{...}, ...}, ...}}, ...}, ...)
	github.com/authelia/authelia/v4/internal/commands/root.go:162 +0x478
github.com/authelia/authelia/v4/internal/commands.cmdRootRun(0x2d5a580, {0x2c9a340, 0x0, 0x2})
	github.com/authelia/authelia/v4/internal/commands/root.go:86 +0x334
github.com/spf13/cobra.(*Command).execute(0x2d5a580, {0x2d18008, 0x2, 0x2})
	github.com/spf13/cobra@v1.5.0/command.go:876 +0x6f4
github.com/spf13/cobra.(*Command).ExecuteC(0x2d5a580)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x450
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	github.com/authelia/authelia/v4/cmd/authelia/main.go:10 +0x18

At first, based on some googling I thought this was something to do with the notifier, but even after disabling the notifier startup check, I still get this error. Below is one such issue I came across.

https://github.com/authelia/authelia/issues/626

Any leads on this would greatly help! Thanks in advance.

**Comment by james-d-elliott** [comment]
This appears to be detecting a signal from the OS to shutdown (sigint or sigterm) and our shutdown process is incorrect. Try this tag in a few mins: authelia/authelia:fix-shutdown-nil-ptr

If you're not using docker you can get the built files here: https://buildkite.com/authelia/authelia/builds/13919

**Comment by crypticviper** [comment]
Thanks for the quick reply. With this new image, the error is more descriptive although it was still unable to startup. At first, I thought the port is being used by some other container but doesn't look like it (I tried many other unused ports like 22222, 8888, etc and the result was the same).

But the problem seemed to be the configuration.yaml file. I had host set to my server IP (instead of 0.0.0.0) as per some tutorial I was following. Changing it back to 0.0.0.0 seems to have fixed this issue.

Again, thanks a bunch for helping out. It's a great project!

Below are the logs with the new image (just for reference in case someone else comes across this issue)

time="2022-09-03T08:02:25+02:00" level=debug msg="Shutdown started due to context completion"
time="2022-09-03T08:02:25+02:00" level=info msg="Shutting down"
time="2022-09-03T08:02:25+02:00" level=error msg="Error occurred waiting for shutdown" error="unable to initialize tcp listener: listen tcp 192.168.50.5:9091: bind: cannot assign requested address" stack="github.com/authelia/authelia/v4/internal/commands/root.go:184 runServers\ngithub.com/authelia/authelia/v4/internal/commands/root.go:86  cmdRootRun\ngithub.com/spf13/cobra@v1.5.0/command.go:876                  (*Command).execute\ngithub.com/spf13/cobra@v1.5.0/command.go:990                  (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.5.0/command.go:918                  main\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_arm.s:824                                         goexit"

**Comment by tmager** [comment]
I ran into this same crash with a different configuration problem (read-only ephemeral FS without setting `disable_healthcheck`) - can confirm, the `fix-shutdown-nil-ptr` change fixes it and allows the error message to come through correctly.

**Comment by james-d-elliott** [comment]
@crypticviper looks like it's because you changed the server host. You should put it back to `0.0.0.0`.

**Comment by crypticviper** [comment]
Thanks, will close this issue now.
