### ISSUE TITLE
Could not set language to zh-CN and zh-TW

### ISSUE THREAD

**Issue by jim-kirisame** [authelia/authelia#3960]
### Description

I can't switch the language of the web page to zh-CN and zh-TW, via:

- query string: https://example.org/?lng=zh-CN
- browser language 

The language of page just stay in en-US. But other language is ok, like ru and de.

### Expected Behaviour

Language could switch to zh-CN or zh-TW

### Reproduction Steps

1. Set language to zh-CN via query string, like https://example.org/?lng=zh-CN
2. It does not work
3. Set language to ru via query string, like https://example.org/?lng=ru
4. It works

### Additional Information

I'm using the latest docker image, Authelia v4.36.6

**Comment by james-d-elliott** [comment]
We do not officially support the query string. Please provide your browser, browser version, and show your language settings, and the output of `navigator.languages` when entered into the web console.

**Comment by jim-kirisame** [comment]
I have try in Firefox 103.0.2 and Edge 105.0.1343.27, both language is chinese.

Firefox:
```
navigator.languages
Array(6) [ "zh-CN", "zh", "zh-TW", "zh-HK", "en-US", "en" ]
```

Edge: 
```
navigator.languages
(4) ['zh-CN', 'en', 'en-GB', 'en-US']
```

**Comment by james-d-elliott** [comment]
Thanks, I can replicate this, seems strange, i18next is completely skipping over all zh languages even though they're clearly configured. I'm betting it's some weird issue with non explicit language support.

**Comment by james-d-elliott** [comment]
Ahh I can see what's causing it I think. It's `nonExplicitSupportedLngs` I think with any of the following languages `pt-PT`, `nl-NL`, `zh-CH`, `zh-TW`. It looks like if we don't also add `pt`, `nl, and `zh` to the supported list then there will be an issue. If I confirm this I will add the respective languages as copies of the others (with `zh-CH` being the copy used for `zh`). I'll have to figure out how to keep them in sync with Crowdin.
