### ISSUE TITLE
Support multiple LDAP urls

### ISSUE THREAD

**Issue by couloum** [authelia/authelia#4015]
Hi,

I have configured Authelia to use LDAP as backend, with implementation `activedirectory`. I have actually 2 AD available so I can do maintenances on 1 AD and have the 2nd process all requests.
However it seems that we can only specify 1 url in the ldap section. Therefore, if the AD on which we point is not available, authelia is not able to log users in anymore.

Would it be possible to specify multiple urls for ldap so that if one fail, another is used?

Thank you

**Comment by james-d-elliott** [comment]
It would be technically possible, however it's currently not supported. The library itself doesn't implement this, and we'd have to implement some failover logic which is not exactly simple.

**Comment by davama** [comment]
@couloum 
What we do is have nginx proxy the multiple ldap servers with the `stream {}` block and point authelia to nginx for ldap.

so from authelia’s perspective, it points to one ldap server, but nginx takes care of the load balancing/failover.

Hope thats useful

**Comment by nightah** [comment]
Yep I'm apprehensive to support implementing this because we would have to maintain code for the failover/selection logic.


Reverse proxies/load balancers exist for a reason. You can utilise NGINX, Traefik, HAProxy or many of the other alternatives to achieve this outcome.

Maybe we document examples for utilising some of the above, though having said that examples would be littered all over google for load balancing/failing over tcp services.

**Comment by couloum** [comment]
Indeed, I can implement this kind of setup using the load balancer on the servers where authelia is located.

Thank you both for your replies.

**Comment by couloum** [comment]
Hi,

I just thought about a potential issue in our setup regarding SSL certs when using load balancer. As we will point to 1 endpoint, we will use 1 DNS entry to point to the load balancer. But the remote AD have 1 certificate each. Therefore, the SSL returned won't match the DNS entry used to point to the LB.

The solution would be that both our AD present the same SSL cert, but I'm not sure if this is possible. Also, it would break existing servers where software points to 2 distinct AD servers.

**Comment by james-d-elliott** [comment]
You actually have a few effective options, from most preferable to least:

1. Sign all LDAPS certificates with a SAN which is a DNS record or IP Address of your Load Balancer (or both). Then use a TCP load balancer.
2. Use a dedicated LDAP load balancer that supports LDAPS to LDAPS, or a TLS TCP load balancer. Then the balancer has a certificate for it's  relevant server name that's trusted by Authelia, and the LDAP servers have their current certificates which are trusted by the load balancer.
3. Skip TLS verification in Authelia.

You'd have to assign a SAN to all certificates. The SAN would be the load balancer. The only thing we're potentially willing
