### ISSUE TITLE
Invalid key: identity_providers.oidc.cor

### ISSUE THREAD

**Issue by TMD20** [authelia/authelia#4107]
### Version

v4.36.8

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Description

The example from here does not work for me two of the keys just refuse to be parsed
https://www.authelia.com/configuration/identity-providers/open-id-connect/#configuration

time="2022-09-29T20:06:05-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-29T20:06:05-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-29T20:06:05-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-29T20:06:05-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"

I was unable to find any other reports of this issue so not sure what is going on

### Reproduction

use the example syntax listed 
and try to run the program

**Comment by james-d-elliott** [comment]
I can't reproduce this. Please include the entire logs, and the configuration.

**Comment by TMD20** [comment]
Configuration with private info removed
https://paste.passtheheadphones.me/?97434ccfcb3c8b45#EdxahKEKKdzqfbrHcR3t8oeP3jZ3Vq5BAjQHPxjPUx3q

`time="2022-09-30T02:29:23-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:29:23-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:29:23-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2022-09-30T02:29:36-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-30T02:29:36-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:29:36-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:29:36-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2022-09-30T02:30:02-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-30T02:30:02-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:30:02-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:30:02-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2022-09-30T02:30:54-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-30T02:30:54-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:30:54-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:30:54-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2022-09-30T02:31:54-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-30T02:31:54-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:31:54-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:31:54-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2022-09-30T02:32:41-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-30T02:32:41-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:32:41-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:32:41-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2022-09-30T02:32:41-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-30T02:32:41-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:32:41-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:32:41-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2022-09-30T02:32:42-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-30T02:32:42-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:32:42-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:32:42-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2022-09-30T02:32:42-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-30T02:32:42-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:32:42-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:32:42-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2022-09-30T02:32:43-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-30T02:32:43-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:32:43-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:32:43-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2022-09-30T02:32:45-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-30T02:32:45-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:32:45-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:32:45-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2022-09-30T02:32:49-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-30T02:32:49-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:32:49-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:32:49-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2022-09-30T02:32:55-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-30T02:32:55-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:32:55-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:32:55-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
time="2022-09-30T02:33:09-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins"
time="2022-09-30T02:33:09-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.allowed_origins_from_client_redirect_uris"
time="2022-09-30T02:33:09-05:00" level=error msg="Configuration: configuration key not expected: identity_providers.oidc.cors.endpoints"
time="2022-09-30T02:33:09-05:00" level=fatal msg="Can't continue due to the errors loading the configuration"
`
the docker container crashes, and I have it set on restart always so it just repeats the same error over and over

**Comment by james-d-elliott** [comment]
The configuration options it's complaining about are commented. Check your file paths.

**Comment by TMD20** [comment]
I think I was on 4.34 or similar and this version requires 4.36 to work.

So after changing the tag on my docker I got it to work
