### ISSUE TITLE
[feature request] add option to send Authorization basic auth header to backend, but on form based login

### ISSUE THREAD

**Issue by helmut72** [authelia/authelia#4110]
### Description

Would be great to have an option to send `Authorization` basic auth header to the backend on form based login. As an option. I'm aware that isn't required for most of other web apps.

### Use Case

Have  [SOGo Groupware](https://sogo.nu) also included in my SSO setup. Also other web apps, which provides basic auth popup window only could be converted to a fancy login page, if it's a web app with only a webinterface. At least I know some switch or camera webinterfaces with basic auth popup window, which could be make accessable from the outside with a fancy login page from Authelia.

### Details

SOGo is a Groupware system. It provides Calendar and Contacts next to Mail with a Webinterface. Using SOGo's login page provides SOGo with an username+password to authenticate against an (independent) IMAP (eg. Dovecot) and SMTP (eg. Postfix) server to receive, show and send mails in SOGo's webinterface. All at all a typical Groupware solution like MS Exchange, but doesn't need that much resources. It runs on a Raspberry Pi.

As an alternative to SOGo's login page SOGo also provides SAML. But then everything becomes really complicated, because SOGo doesn't have an username+password to authenticate against the mail server and nevertheless Authelia doesn't support SAML.

Another alternative is using `SOGoTrustProxyAuthentication=YES` option, where SOGo accept authentication from the Reverse Proxy, **but also accepts an Authorization Basic Auth header from the Reverse Proxy.** I have tested it with a Firefox addon, where I added the Authorization header. SOGo searched in the LDAP setup for my other user informations and all works like using SOGo's login page.

Now I can use basic auth in Authelia. But having a basic auth popup window isn't a great user (and admin - I'm both in my family) experience. Also Authelia isn't session aware between basic auth and other 2 login types, form based or OIDC logins. See https://github.com/authelia/authelia/issues/3498

Thank you.

**Comment by james-d-elliott** [comment]
If this feature request is to forward an Authorization header that already exists then I think that is something we'd consider.

If it's to save a password for reuse either entered by the user at login or by a configuration page I'm not sure that's something we want to implement. This is what I'd personally consider (and most people in the security industry probably consider) an egregiously bad security practice. Having a users password accessible in plain text is just not a good idea.

I'd recommend using the `SOGoTrustProxyAuthentication=YES` option and map authelia's response header of `Remote-User` to the `x-webobjects-remote-user` request header.

**Comment by helmut72** [comment]
> I'd recommend using the SOGoTrustProxyAuthentication=YES option and map Authelia's Remote-User response header to the X-WebObjects-Remote-User request header.

Then SOGo can't authenticate to Dovecot (IMAP) to receive mails. A "solution" is running Dovecot password-less. This isn't useful, because I also connect full mail clients to IMAP. Running 2 Dovecot instances, one password-less for SOGo, is a waste of resources. Especially on low hardware like a Raspberry Pi. Also access 2 Dovecot instances to one data store grows complexity and is forced to get new problems.
Even in a common configuration, SOGo saves the password from the login page to access and use IMAP/SMTP server. Therefore the admin trust SOGo at all and if the admin decide to use Authelia for the auth part, admin also trust Authelia.

Of course I describe a specifc problem with SOGo or any other common Groupware suites, that use 3rd party parts like Dovecot. Also there are other use cases that integrates old styled apps, even old or consumer network switches and webcams into a complete SSO solution.

> If it's to save a password for reuse either entered by the user at login or by a configuration page I'm not sure that's something we want to implement.

Unfortunately this is what I ask for. But it would be great that the admin is abled to decide if he want to store a basic auth header in Authelia for specific apps or not. If it's disabled for other apps, it's doesn't affect them.

If Authelia is really compromised it doesn't matter if Authelia get the password in the login sequence only or use it for the whole session for a specific. It just makes Authelia even more flexible.

**Comment by james-d-elliott** [comment]
> Unfortunately this is what I ask for. But it would be great that the admin is abled to decide if he want to store a basic auth header in Authelia for specific apps or not. If it's disabled for other apps, it's doesn't affect them.
> 
> If Authelia is really compromised it doesn't matter if Authelia get the password in the login sequence only or use it for the whole session for a specific. It just makes Authelia even more flexible.

To be clear it is the same as storage of the password in plain text. I'll discuss this with the other team members though.

**Comment by deathbybandaid** [comment]
Another use-case for this would be deluge, as it doesn't make use of api keys for 3rd-party app usage.

Implementing this would allow me to have a seamless login to deluge, and the ability to set a long password-key for an "api-like" access

**Comment by james-d-elliott** [comment]
You could easily do this in your proxy by adding the appropriate header. A third party solution could decide to do this based on our `Remote-User` header as well, matching a header to the specific username + url combination. If users are interested in help with this you can either ask the developer of the specific third-party application or start a [Discussion](https://github.com/authelia/authelia/discussions).

In talking to the team we have no intention of implementing a feature that would automatically be considered a High/Critical CVE regardless of what other solutions decide to do to compromise the security of their users.

**Comment by james-d-elliott** [comment]
> Because basic auth window **looks awful** instead of a form based auth page. It's about the look and feel only. Nothing more nothing less.

Then don't use `auth=basic`. It's intended that the user provide the basic auth scheme if it's configured like that.

**Comment by helmut72** [comment]
> > Because basic auth window **looks awful** instead of a form based auth page. It's about the look and feel only. Nothing more nothing less.
> 
>  It's intended that the user provide the basic auth scheme if it's configured like that.

But then Authelia also store the password in cleartext, because it's impossible to forward any data wiithout being stored. Result is:
> would automatically be considered a High/Critical CVE

**Comment by james-d-elliott** [comment]
Supporting Information regarding our stance: https://cwe.mitre.org/data/definitions/257.html
