### ISSUE TITLE
HAPROXY:  be_authelia returns http code 100 if client request includes 'expect' header

### ISSUE THREAD

**Issue by systemmonkey42** [authelia/authelia#4132]
### Version

v4.36.6

### Deployment Method

Docker

### Reverse Proxy

HAProxy

### Reverse Proxy Version

2.6.6

### Description

WEBDAV Client gets unexpected disconnect.

The was traced to the client making a PUT request with `expect: 100` in the headers.

The 'expect: 100' header was forwarded via `auth-request.lua` to authelia which responded with a `100-continue`.

`auth-request.lua` didn't handle this, and returned an error which resulting in the connection being dropped.

### Reproduction

```
curl -I -s -H 'Host: authorized.host.com' -H 'expect: 100' -H 'X-Forward-Scheme: https' "http://<authelia_be>:9091"
```

### Expectations

Authenication is set to bypass for the webdav server, so expectation is a 200 OK.

### Logs

```shell
router_1    | 2022-10-03T01:13:34+00:00 localhost haproxy[231]: Invalid status code in auth-request backend 'be_authelia': 100
router_1    | 2022-10-03T01:13:34+00:00 localhost haproxy[231]: x.x.x.x:17415 [03/Oct/2022:01:13:34.319] http-ssl~ http-ssl/<NOSRV> 1/-1/-1/-1/1 302 166 - - LR-- 4/3/0/0/0 0/0 "PUT /Sync/file.tmp HTTP/1.1"
```

### Configuration

```yaml
Generic working config
```

### Documentation

I resolved this issue locally by ensuring `auth-request.lua` strips any `expect` headers when forwarding the request to the authelia backend.

Ideally the `auth-request.lua` script should know what headers are required, and only forward those to ensure unexpected headers don't affect authentication.

(Note the 'expect' header was still forwarded to the DAV server when authentication was complete.)

**Comment by james-d-elliott** [comment]
1. Use the `/api/verify` endpoint not the `/` endpoint.
2. Show the actual authelia logs with trace logging which prove the `/api/verify` endpoint is returning a status code other than `200`.
3. I can't replicate this with Authelia via the following test which matches your exact description:

```go
func TestShouldNotReturn100(t *testing.T) {
	mock := mocks.NewMockAutheliaCtx(t)
	defer mock.Close()

	mock.Ctx.Request.Header.Set("X-Forwarded-Proto", "https")
	mock.Ctx.Request.Header.Set("X-Forwarded-Host", "bypass.example.com")
	mock.Ctx.Request.Header.Set("X-Forwarded-URI", "/")
	mock.Ctx.Request.Header.Set("Expect", "100")

	VerifyGET(verifyGetCfg)(mock.Ctx)

	assert.Equal(t, 200, mock.Ctx.Response.StatusCode())
}
```

**Comment by systemmonkey42** [comment]
I apologize for my poor instructions.

1) Yes, I used the correct api, but transcribed it badly.
2) The correct header was `expect: 100-continue`.  again transcribed incorrectly.
3) Authelia is not in error.  `auth-request.lua` is.  If `auth-request.lua` is not something you maintain, then I am in the wrong place..
4) Yes, curl will return a valid result because it handles the 100-continue internally.

I have `ngrep` running to capture the network conversation:
```
T <haproxy-ip>:40714 -> <authelia-ip>:9091 [AP] #94
HEAD /api/verify HTTP/1.1.
x-forwarded-proto: https.
x-real-ip: <user public ip>.
authorization: Basic webdav-password.
x-forwarded-host: server.mydomain.com.
pragma: no-cache.
x-forwarded-port: 80.
x-forwarded-uri: /Sync/file.tmp.
expect: 100-continue.
cache-control: no-store,no-cache.
x-forwarded-for: <user public ip>.
x-forwarded-method: .
host: <authelia-ip>:9091.
accept: */*.
user-agent: haproxy-lua-http/1.0.
connection: close.
.

##
T <authelia-ip>:9091 -> <ha-proxy-ip>:40714 [AP] #96
HTTP/1.1 100 Continue.
```

The closest I could get to simulating it via `curl` was;
```
$ curl -vs -I -H 'Host: server.mydomain.cf' -H 'expect: 100-continue' -H 'X-Forwarded-Proto: https' 'http://authelia-ip:9091/api/verify'
* Uses proxy env variable no_proxy == 'localhost'
*   Trying authelia-ip:9091...
* TCP_NODELAY set
* Connected to authelia-ip (authelia-ip) port 9091 (#0)
> HEAD /api/verify HTTP/1.1
> Host: server.mydomain.com
> User-Agent: curl/7.68.0
> Accept: */*
> expect: 100-continue
> X-Forwarded-Proto: https
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
HTTP/1.1 100 Continue

* Mark bundle as not supporting multiuse
HTTP/1.1 200 OK
Date: Wed, 05 Oct 2022 02:54:38 GMT
X-Content-Type-Options: nosniff
Referrer-Policy: strict-origin-when-cross-origin
Permissions-Policy: interest-cohort=()
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
Set-Cookie: authelia_session=cookie_dough; expires=Thu, 06 Oct 2022 02:54:38 GMT; domain=mydomain.com; path=/; HttpOnly; secure; SameSite=Lax
Connection: close

<
* Closing connection 0
```

Note that curl recognised the `100-continue` internally and continues waiting for the final response.

On the other hand, `auth-request.lua`  simply disconnects as soon as it receives it.

Authelia didn't log anything, since, as far as it was concerned, it answered the request for the '100-continue' response, and carried on.

**Comment by systemmonkey42** [comment]
Thanks for the link to SPOE.  I might look at what is involved in using that.

**Comment by james-d-elliott** [comment]
Well, we don't support SPOE yet, it requires us to implement a protocol.
