### ISSUE TITLE
Ability to disable "saveUninitialized" option for sessions

### ISSUE THREAD

**Issue by zegerhoogeboom** [authelia/authelia#417]
The express-session package is used to store sessions and the default config is: 
```
 const sessionOptions: ExpressSession.SessionOptions = {
      name: configuration.session.name,
      secret: configuration.session.secret,
      resave: false,
      saveUninitialized: true,
      cookie: {
        secure: true,
        httpOnly: true,
        maxAge: configuration.session.expiration,
        domain: configuration.session.domain
      },
    };
```

The `saveUninitialized` option is fixed to `true` but I'd like to disable this as any call to the `/api/verify` endpoint (possibly the same goes for any endpoint, but haven't checked) that doesn't include any auth also generates a session. I currently have a misconfigured service that does this every 5s, generating a new session every 5s. Of course we'll fix this specific case but especially as this is a public endpoint, anyone could spam sessions into our Redis this way.

Could an optional configuration option be added for this? (i.e. `configuration.session.save_uninitialized`)

**Comment by clems4ever** [comment]
Hello @zegerhoogeboom , I'd rather not change that because of a misconfigured client. I can provide you with a patched version with the hotfix (saveUninitialized: false) if you can't do it on your own though.

What do you think?

**Comment by zegerhoogeboom** [comment]
Outside of the misconfigured client, the bigger worry is the ability of attackers to spam the Redis session cache by just spamming the login form with wrong credentials as it's a public facing endpoint and the login-ban system being by username instead of by IP address.

I could patch it myself if I really need it, thanks for the offer.

**Comment by clems4ever** [comment]
Alright, Authelia does not use this option anymore at HEAD but I will check if the problem still remains because you're right that an attacker could easily DDoS the cache.

**Comment by clems4ever** [comment]
@zegerhoogeboom , I verified that uninitialized sessions are not  saved in redis using Authelia v4.
