### ISSUE TITLE
Errors loading the configuration (error decoding secret) with 4.37

### ISSUE THREAD

**Issue by crypticviper** [authelia/authelia#4247]
### Version

v4.37.0

### Deployment Method

Docker

### Reverse Proxy

NGINX Proxy Manager

### Description

I get errors post 4.37 (docker image version) update. Switching back to 4.36 worked for me.

time="2022-10-23T09:56:33+02:00" level=error msg="Configuration: error occurred during unmarshalling configuration: 1 error(s) decoding:\n\n* error decoding 'identity_providers.oidc.clients[1].secret': could not decode '$plaintext$XXXXX*' to a *schema.PasswordDigest: plaintext decode error: provided encoded hash has an invalid format" time="2022-10-23T09:56:33+02:00" level=fatal msg="Can't continue due to the errors loading the configuration"

Docker compose:

`services:
  authelia:
    image: authelia/authelia:4.37
    container_name: auth
    volumes:
      - /srv/myvolume/config/authelia:/config
    expose:
      - 9091
    networks:
      - mynetwork
    restart: unless-stopped`

### Reproduction

Just try to deploy the docker-compose mentioned in the issue description.

### Expectations

Docker container should start normally without fatal errors.

### Logs

```shell
Provided in the issue description.
```

**Comment by james-d-elliott** [comment]
I've merged a fix to this in master. Fixed by 745459edd7c9523b9abad7d7c652fcb53d46eba3. You can either use the `master` tag, or wait for 4.37.1 which should be out tomorrow.

**Comment by crypticviper** [comment]
Thanks for the quick reply. I tested it with `master` tag, and it works fine now.
