### ISSUE TITLE
[feature request] Provide more informations to OIDC from LDAP

### ISSUE THREAD

**Issue by helmut72** [authelia/authelia#4295]
### Description

Provide more informations to OIDC from LDAP.

### Use Case

LDAP is there for central user management. Why should a user upload his profile picture or insert his phone number many times in every app. It's like different passwords or without OIDC this many logins in the past: users are lazy, also to fill all informations in every app.

### Details

Would be cool if more fields like profile picture, phone number, address... will be read from LDAP to be send to an app. Profile picture comes from `jpegPhoto` in LDAP, phone number from `phone` and so on..

Some fields which Nextcloud supports:

![](https://cdn1.vogel.de/unsafe/800x0/smart/images.vogel.de/vogelonline/bdb/1401400/1401425/original.jpg)

### Documentation

OIDC supports everything:
https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

**Comment by james-d-elliott** [comment]
NextCloud's OIDC actually supports none of those: https://github.com/pulsejet/nextcloud-oidc-login

**Comment by james-d-elliott** [comment]
Also this is being considered a duplicate of https://github.com/authelia/authelia/issues/2868

**Comment by helmut72** [comment]
Nextcloud supports at least photoURL with `'photoURL' => 'picture',`. Also I mentioned Nextcloud as an example. If the IDP doesn't support it, it doesn't make sense to ask app developers to support more attributes, a "hen egg problem". ;) 

Therefore I've started here to support more attributes.

> Also this is being considered a duplicate of #2868

Sorry, have used the wrong keywords for searching. Yes, I mean this. Thanks for the info that it's in the pipeline.

**Comment by james-d-elliott** [comment]
Yeah jpegPhoto is a byte string not a URL.

**Comment by helmut72** [comment]
This is the reason why I especially mentioned jpegPhoto as an example for the feature request. ;) Authelia need to read jpegPhoto from LDAP and provide an URL to the jpg for the app.
