### ISSUE TITLE
OpenLDAP queries fail when Security Factor is set to 256

### ISSUE THREAD

**Issue by zealousGnu** [authelia/authelia#4332]
### Version

v4.37.2

### Deployment Method

Bare-metal

### Reverse Proxy

NGINX

### Description

Setting openldap security strength factors to 256 causes all searches from authelia to fail.

https://openldap.org/doc/admin21/slapdconfig.html has an example of how to set SSF levels

### Reproduction

On the Ldap server in cn=config set ssf levels to 256

for example in dn: olcDatabase={1}mdb,cn=config
```
olcAccess: {4} to * by ssf=256 self write by ssf=256 anonymous auth by ssf=256
  users read by ssf=256 * none
```

### Configuration

```yaml
Same as in my other issue.
```

**Comment by james-d-elliott** [comment]
This is a feature request since SSF is basically a feature level. As far as I can tell this feature level is not documented / documented well by OpenLDAP. Once they do we'll consider making a PR to the LDAP library that we don't maintain to add support.

**Comment by james-d-elliott** [comment]
Actually, this looks invalid. Seems from several other similar issues that you also need to increase your TLS settings on OpenLDAP to AES256. Also frankly it's rude to not include logs or a config.

**Comment by james-d-elliott** [comment]
https://www.openldap.org/lists/openldap-technical/201210/msg00059.html

**Comment by james-d-elliott** [comment]
As there is no response in 3 weeks this ticket is closed as not planned. This may be fixed by https://github.com/authelia/authelia/commit/e1f9718e173d3ab77822889c4861b0a1f63f0830 but you did not complete the issue template or respond so this is the  only support possible.
