### ISSUE TITLE
Support For Additional OIDC Profile Claims

### ISSUE THREAD

**Issue by stonedprogrammer** [authelia/authelia#4338]
### Description

Currently, per https://www.authelia.com/integration/openid-connect/introduction/#scope-definitions, Authelia only supports the `preferred_username` and `name` claims under the `profile` scope. However, some applications don't support just the `name` claim. As such, I am requesting support for additional claims be added, such as `given_name` and `family_name`.

### Use Case

As an example, I use [PowerDNS-Admin](https://github.com/PowerDNS-Admin/PowerDNS-Admin) which does support OIDC, however it only supports a FirstName LastName system, where the two are separate, instead of using the `name` claim to fetch the full name. This means that the names in the system are incorrect. This is purely anecdotal, however I believe that there are other applications out there that separate out the names instead of using only the `name` claim. Adding these two claims would allow those applications to properly grab a user's name properly.

**Comment by james-d-elliott** [comment]
https://github.com/authelia/authelia/issues/2868
