### ISSUE TITLE
Session token tied to client IP address

### ISSUE THREAD

**Issue by lprat** [authelia/authelia#4345]
### Description

Hi, 

To make it harder to replay a stolen cookie, can you tied session token to client IP address ?
In the event that the client is compromised and the client use auth webautn (FIDO2 key), if attacker must use IP of victim (session token tied to client IP address), the work of attacker is harder because he must use victim computer like a proxy (to have good ip address).
It's not the perfect solution, but with a new feature discussed in issue [#1388](https://github.com/authelia/authelia/issues/1388), can be a good way to use the concept of depth of defense.

Thanks

### Use Case

Can you add option in configuration to activate it. In my opinion, it's just useful for webtauthn (other cases, in my scenario, attacker can steal the secret of authentication -> like password, TOTP can replay during 60s, ... )

### Details

When request with session token have an address IP different that's used during authentication then logout user (and send notification to email contact or/and administrator of authelia).

**Comment by james-d-elliott** [comment]
#595
