### ISSUE TITLE
Support update Access-Control via API.

### ISSUE THREAD

**Issue by zslucky** [authelia/authelia#4350]
### Description

In some scenarios we want to update Access-Control programmatically via api.

### Use Case

1. Some admin system want to control the permission in their system.
2. In my case, I create a Low-Code platform, and all services are dynamically created, so I need to config many things programmatically. 

### Details

see above

### Documentation

not open sourced yet...

**Comment by james-d-elliott** [comment]
This will be implemented as a portion of #303  and #966
