### ISSUE TITLE
Change background image

### ISSUE THREAD

**Issue by Sparklingx** [authelia/authelia#4397]
### Description

option to change the background image of  username, password input page

### Use Case

to look  cool

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
The displayed image can already be changed: https://www.authelia.com/configuration/miscellaneous/server/#asset_path
