### ISSUE TITLE
OIDC client restricts user or group usage

### ISSUE THREAD

**Issue by NPCDW** [authelia/authelia#4409]
### Description

I created an OIDC client, all users can use this client, but I only want users in one group to use it.

I tried using "access_control.rules" to restrict, but OIDC seems to be independent and cannot be restricted by it

### Use Case

users_database_example.yml

```
users:
  authelia:
  test:
  guest:
```
I just want "authelia" to use OIDC client, the other two users are users of other OIDC client

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
#2621
