### ISSUE TITLE
TLS for LDAP doesn't upgrade

### ISSUE THREAD

**Issue by prabirshrestha** [authelia/authelia#4425]
### Version

v4.37.0

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.9.5

### Description

Issue when migrating from 4.36.9 to 4.37.0 due to no automatic upgrades of LDAP TLS from 1.2 to 1.3 when server only supports 1.3.

### Reproduction

* Configure TLS profile for Synology DSM v7.1 to modern compatibility. 

![image](https://user-images.githubusercontent.com/287744/203704338-a7b03f29-011c-44eb-897b-5633b23f0059.png)

* Enable Secure LDAP in Synology LDAP Server.

*  Configure the ldap.tls section as below
```
ldap:
  tls:
      skip_verify: false
      server_name: somedomain.com
```

* Run Authelia v4.37.0. It fails to start with error `tls: protocol version not supported`.

### Expectations

This used to work when using authelia v4.36.9 but as soon as you update to v4.37.0 it starts to break.

Once I set the minimum tls version to 1.3 it starts to run correctly.

```
    tls:
      skip_verify: false
      server_name: somedomain.com
      minimum_version: TLS1.3
```

Not sure if this is a bug or excepted but few things that could be improved here as I had to read docs but couldn't find hints on this possible edge case. Few options:
* Updates docs in LDAP section or in FAQ about minimum_version when one sees the following error or improve the error message to make necessary changes.
* Auto upgrade version.

(Feel free to close this issue if it is expected).

### Logs (Authelia)

```shell
level=error msg="Failure running the user provider startup check: dial failed with error: LDAP Result Code 200 \"Network Error\": remote error: tls: protocol version not supported" stack="github.com/authelia/authelia/v4/internal/commands/root.go:287 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
time="2022-11-23T21:42:28-08:00" level=debug msg="The NTP startup check was skipped due to there being no configured 2FA access control rules"
time="2022-11-23T21:42:28-08:00" level=fatal msg="The following providers had fatal failures during startup: user" stack="github.com/authelia/authelia/v4/internal/commands/root.go:309 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Log a new issue and fill in the form.

**Comment by james-d-elliott** [comment]
Actually, never mind. I see what you're saying.
