### ISSUE TITLE
Not works with active directory

### ISSUE THREAD

**Issue by xorira** [authelia/authelia#444]
Hello! I am using authelia in a docker container.
I can not authorize the user using the active directory
path of config file authelia_config.yml

>   ldap:
    # The url of the ldap server
    url: ldap://10.100.1.2
    # The base dn for every entries
    base_dn: dc=Homelan,dc=local
    # The users filter used to find the user DN
    # {0} is a matcher replaced by username.
    # 'cn={0}' by default.
    users_filter: CN={0}
        # An additional dn to define the scope to all users
    additional_users_dn: CN=users
    # An additional dn to define the scope of groups
    additional_groups_dn: ou=groups
    # The groups filter used for retrieving groups of a given user.
    # {0} is a matcher replaced by username.
    # {dn} is a matcher replaced by user DN.
    # {uid} is a matcher replaced by user uid.
    # 'member={dn}' by default.
    groups_filter: ((&(member={dn})(objectclass=group))
    # The attribute holding the name of the group
    group_name_attribute: cn
    # The attribute holding the mail address of the user
    mail_attribute: mail
    # The username and password of the admin user.
    user: 2FA@Homelan.local
    password: P@ssw0rd!
    # The groups filter used for retrieving groups of a given user.
    # {0} is a matcher replaced by username.
    # {dn} is a matcher replaced by user DN.
    # {uid} is a matcher replaced by user uid.
    # 'member={dn}' by default.
    groups_filter: ((&(member={dn})(objectclass=group))
    # The attribute holding the name of the group
    group_name_attribute: cn
    # The attribute holding the mail address of the user
    mail_attribute: mail
    # The username and password of the admin user.
    user: 2FA@Homelan.local
    password: P@ssw0rd! <

errors in logs
> info: date='Sat Nov 16 2019 18:58:09 GMT+0000 (UTC)' message='Starting Authelia...'
info: date='Sat Nov 16 2019 18:58:09 GMT+0000 (UTC)' message='Listening on port 9091...'
debug: date='Sat Nov 16 2019 18:58:23 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='81689d7d-3540-4210-a537-73d74d291991' sessionId='QFPKz5vje8ePRTFcgPySFR4HAWwwfifD' ip='::ffff:192.168.88.205' message='Headers = {"host":"192.168.20.53:9091","connection":"keep-alive","content-length":"67","accept":"application/json","origin":"http://192.168.20.53:9091","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36","content-type":"application/json","referer":"http://192.168.20.53:9091/","accept-encoding":"gzip, deflate","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"}'
debug: date='Sat Nov 16 2019 18:58:23 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='81689d7d-3540-4210-a537-73d74d291991' sessionId='QFPKz5vje8ePRTFcgPySFR4HAWwwfifD' ip='::ffff:192.168.88.205' message='Session QFPKz5vje8ePRTFcgPySFR4HAWwwfifD has no authentication information. Its internal id is: QFPKz5vje8ePRTFcgPySFR4HAWwwfifD its current cookie is: {"originalMaxAge":3600000,"expires":"2019-11-16T19:58:23.684Z","secure":true,"httpOnly":true,"domain":"example.ru","path":"/"}'
debug: date='Sat Nov 16 2019 18:58:23 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='81689d7d-3540-4210-a537-73d74d291991' sessionId='QFPKz5vje8ePRTFcgPySFR4HAWwwfifD' ip='::ffff:192.168.88.205' message='Authentication session QFPKz5vje8ePRTFcgPySFR4HAWwwfifD was undefined. Resetting... If it's unexpected, make sure you are visiting the expected domain.'
info: date='Sat Nov 16 2019 18:58:23 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='81689d7d-3540-4210-a537-73d74d291991' sessionId='QFPKz5vje8ePRTFcgPySFR4HAWwwfifD' ip='::ffff:192.168.88.205' message='Starting authentication of user "example"'
info: date='Sat Nov 16 2019 18:58:23 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='81689d7d-3540-4210-a537-73d74d291991' sessionId='QFPKz5vje8ePRTFcgPySFR4HAWwwfifD' ip='::ffff:192.168.88.205' message='No regulation applied.'
debug: Using ldap client options: {"url":"ldap://10.100.1.2"}
debug: LDAP: Bind user '2FA@Homelan.local'
debug: Computed users filter is CN=example
debug: LDAP: searching for user dn of example
debug: LDAP: retrieved user dn is CN=example,CN=Users,DC=Homelan,DC=local
debug: Using ldap client options: {"url":"ldap://10.100.1.2"}
debug: LDAP: Bind user 'CN=example,CN=Users,DC=Homelan,DC=local'
debug: LDAP: Unbind user 'CN=example,CN=Users,DC=Homelan,DC=local'
debug: Computed users filter is CN=example
debug: LDAP: searching for user dn of example
debug: Computed users filter is CN=example
debug: LDAP: searching for user dn of example
debug: LDAP: retrieved user dn is CN=example,CN=Users,DC=Homelan,DC=local
debug: LDAP: retrieved user dn is CN=example,CN=Users,DC=Homelan,DC=local
debug: Computed groups filter is ((&(member=CN=example,CN=Users,DC=Homelan,DC=local)(objectclass=group))
debug: LDAP: Unbind user '2FA@Homelan.local'
debug: LDAP: emails of user 'example' are example@gmail.com
error: date='Sat Nov 16 2019 18:58:23 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='81689d7d-3540-4210-a537-73d74d291991' sessionId='QFPKz5vje8ePRTFcgPySFR4HAWwwfifD' ip='::ffff:192.168.88.205' message='Reply with error 200: invalid nested parens'
debug: date='Sat Nov 16 2019 18:58:23 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='81689d7d-3540-4210-a537-73d74d291991' sessionId='QFPKz5vje8ePRTFcgPySFR4HAWwwfifD' ip='::ffff:192.168.88.205' message='Error: invalid nested parens
    at that.withSession.catch (/usr/src/server/src/lib/authentication/backends/ldap/LdapUsersDatabase.js:33:45)
    at tryCatcher (/usr/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/src/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/src/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/src/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/src/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/usr/src/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/src/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/usr/src/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)'

**Comment by clems4ever** [comment]
Hello @xorira , I have no active directory at hand unfortunately.

Do you use the Docker version of Authelia? Would you be able to test your AD against v4 of Authelia?There is an alpha version published on Dockerhub to do that.

**Comment by clems4ever** [comment]
@xorira there is an unbalanced number of parenthesis in your groups filter. Please fix that and test again.

**Comment by xorira** [comment]
@clems4ever  after update docker container to latest, new error

`[root@localhost ~]# docker logs -f authelia
Selected public_html directory is  ./public_html
time="2019-11-19T16:51:37Z" level=info msg="Authelia is listening on :9091"
time="2019-11-19T16:51:52Z" level=error msg="Error while checking password for user example: Cannot find user DN of user example. Cause: LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('" method=POST path=/api/firstfactor remote_ip=192.168.88.205 stack="/go/src/app/internal/middlewares/authelia_context.go:58          (*AutheliaCtx).Error\n/go/src/app/internal/handlers/handler_firstfactor.go:38          FirstFactorPost\n/go/src/app/internal/middlewares/authelia_context.go:43          AutheliaMiddleware.func1.1\n/go/pkg/mod/github.com/fasthttp/router@v0.5.2/router.go:326      (*Router).Handler\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/header.go:123     (*ResponseHeader).StatusCode\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/server.go:2018    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:223 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1357                       goexit"
time="2019-11-19T16:52:41Z" level=error msg="Error while checking password for user example: Cannot find user DN of user example. Cause: LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('" method=POST path=/api/firstfactor remote_ip=192.168.88.205 stack="/go/src/app/internal/middlewares/authelia_context.go:58          (*AutheliaCtx).Error\n/go/src/app/internal/handlers/handler_firstfactor.go:38          FirstFactorPost\n/go/src/app/internal/middlewares/authelia_context.go:43          AutheliaMiddleware.func1.1\n/go/pkg/mod/github.com/fasthttp/router@v0.5.2/router.go:326      (*Router).Handler\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/header.go:123     (*ResponseHeader).StatusCode\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/server.go:2018    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:223 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1357                       goexit"
time="2019-11-19T16:54:00Z" level=error msg="Error while checking password for user example: Cannot find user DN of user example. Cause: LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('" method=POST path=/api/firstfactor remote_ip=192.168.88.205 stack="/go/src/app/internal/middlewares/authelia_context.go:58          (*AutheliaCtx).Error\n/go/src/app/internal/handlers/handler_firstfactor.go:38          FirstFactorPost\n/go/src/app/internal/middlewares/authelia_context.go:43          AutheliaMiddleware.func1.1\n/go/pkg/mod/github.com/fasthttp/router@v0.5.2/router.go:326      (*Router).Handler\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/header.go:123     (*ResponseHeader).StatusCode\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/server.go:2018    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:223 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1357                       goexit"
time="2019-11-19T16:57:48Z" level=error msg="Error while checking password for user example: Cannot find user DN of user example. Cause: LDAP Result Code 201 \"Filter Compile Error\": ldap: filter does not start with an '('" method=POST path=/api/firstfactor remote_ip=192.168.88.205 stack="/go/src/app/internal/middlewares/authelia_context.go:58          (*AutheliaCtx).Error\n/go/src/app/internal/handlers/handler_firstfactor.go:38          FirstFactorPost\n/go/src/app/internal/middlewares/authelia_context.go:43          AutheliaMiddleware.func1.1\n/go/pkg/mod/github.com/fasthttp/router@v0.5.2/router.go:326      (*Router).Handler\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/header.go:123     (*ResponseHeader).StatusCode\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/server.go:2018    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:223 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1357                       goexit"
`

**Comment by xorira** [comment]
If i use Ldapsearch

```
[root@localhost ~]#  ldapsearch -H ldap://10.100.1.2 -x -W  -D "2FA@Homelan.local" -b "cn=users,dc=Homelan,dc=local" "(cn=example)"
Enter LDAP Password:
# extended LDIF
#
# LDAPv3
# base <cn=users,dc=Homelan,dc=local> with scope subtree
# filter: (cn=example)
# requesting: ALL
#

# example, Users, Homelan.local
dn: CN=example,CN=Users,DC=Homelan,DC=local
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: example
givenName: example
distinguishedName: CN=example,CN=Users,DC=Homelan,DC=local
instanceType: 4
whenCreated: 20191112234831.0Z
whenChanged: 20191114171634.0Z
displayName: example
uSNCreated: 16423
memberOf: CN=authelia,OU=Groups,DC=Homelan,DC=local
memberOf:: Q0490JDQtNC80LjQvdC40YHRgtGA0LDRgtC+0YDRiyDQtNC+0LzQtdC90LAsQ049VXN
 lcnMsREM9SG9tZWxhbixEQz1sb2NhbA==
memberOf:: Q0490J/QvtC70YzQt9C+0LLQsNGC0LXQu9C4INGD0LTQsNC70LXQvdC90L7Qs9C+ING
 A0LDQsdC+0YfQtdCz0L4g0YHRgtC+0LvQsCxDTj1CdWlsdGluLERDPUhvbWVsYW4sREM9bG9jYWw=

```

**Comment by clems4ever** [comment]
Same issue as https://github.com/clems4ever/authelia/issues/451

**Comment by xorira** [comment]
@clems4ever 
now there are no errors in the logs, but there is no redirect on the page with 2fa choice
```
o/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1357                       goexit"
Selected public_html directory is  ./public_html
time="2019-11-20T09:07:46Z" level=info msg="Authelia is listening on :9091"
time="2019-11-20T09:08:14Z" level=debug msg="Mark authentication attempt made by user example" method=POST path=/api/firstfactor remote_ip=10.100.1.2
time="2019-11-20T09:08:14Z" level=debug msg="Credentials validation of user example is ok" method=POST path=/api/firstfactor remote_ip=10.100.1.2
time="2019-11-20T09:08:14Z" level=debug msg="Required level for the URL https://home.example.ru is 2" method=POST path=/api/firstfactor remote_ip=10.100.1.2
time="2019-11-20T09:09:19Z" level=debug msg="Mark authentication attempt made by user example" method=POST path=/api/firstfactor remote_ip=10.100.1.2
time="2019-11-20T09:09:19Z" level=debug msg="Credentials validation of user example is ok" method=POST path=/api/firstfactor remote_ip=10.100.1.2


```

**Comment by clems4ever** [comment]
Can you check whether there is an error in the browser console?

**Comment by xorira** [comment]
same situation
![image](https://user-images.githubusercontent.com/57842440/69455377-56ff5780-0d79-11ea-9e9b-ae52a5694508.png)

authelia_config.yml
```
# (domain, resource, subject) applies.
access_control:
  # Default policy can either be `bypass`, `one_factor`, `two_factor` or `deny`.
  # It is the policy applied to any resource if there is no policy to be applied
  # to the user.
  default_policy: two_factor

```

**Comment by clems4ever** [comment]
Ok not much to say about the latest images. Do you have any logs from the AD? It's like it cannot be contacted by Authelia. Can we prove that a connection has been made to the AD?

**Comment by xorira** [comment]
@clems4ever On ad logs all good -  bind\unbind
Tcpdump from any interface from host with authelia

[ldap11.zip](https://github.com/clems4ever/authelia/files/3888757/ldap11.zip)

**Comment by xorira** [comment]
after i downgrade to authelia v3 logs more complete
```
`debug: Using ldap client options: {"url":"ldap://10.100.1.2"}
debug: LDAP: Bind user 'CN=example,CN=Users,DC=Homelan,DC=local'
debug: LDAP: Unbind user 'CN=example,CN=Users,DC=Homelan,DC=local'
debug: Computed users filter is (sAMAccountName=example)
debug: LDAP: searching for user dn of example
debug: Computed users filter is (sAMAccountName=example)
debug: LDAP: searching for user dn of example
debug: LDAP: retrieved user dn is CN=example,CN=Users,DC=Homelan,DC=local
debug: LDAP: retrieved user dn is CN=example,CN=Users,DC=Homelan,DC=local
debug: Computed groups filter is (&(member=CN=example,CN=Users,DC=Homelan,DC=local)(objectclass=group))
debug: LDAP: emails of user 'example' are example@gmail.com
debug: LDAP: groups of user example are [authelia]
debug: LDAP: Unbind user '2FA@Homelan.local'
info: date='Wed Nov 27 2019 17:32:15 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='b7217f7f-9dbd-4c98-b02a-605476b40214' sessionId='6cjYwcFPJhvlg2rdxbAvr6rrdUhLeAzB' ip='::ffff:192.168.88.205' message='Backend lookup successful. Retrieved information about user example are {"groups":["authelia"],"emails":["example@gmail.com"]}'
debug: date='Wed Nov 27 2019 17:32:15 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='b7217f7f-9dbd-4c98-b02a-605476b40214' sessionId='6cjYwcFPJhvlg2rdxbAvr6rrdUhLeAzB' ip='::ffff:192.168.88.205' message='Mark successful authentication to regulator.'
debug: date='Wed Nov 27 2019 17:32:15 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='b7217f7f-9dbd-4c98-b02a-605476b40214' sessionId='6cjYwcFPJhvlg2rdxbAvr6rrdUhLeAzB' ip='::ffff:192.168.88.205' message='Header x-target-url is set to undefined'
debug: date='Wed Nov 27 2019 17:32:15 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='b7217f7f-9dbd-4c98-b02a-605476b40214' sessionId='6cjYwcFPJhvlg2rdxbAvr6rrdUhLeAzB' ip='::ffff:192.168.88.205' message='Sending status 204 due to missing header 'x-target-url''
debug: date='Wed Nov 27 2019 17:32:15 GMT+0000 (UTC)' method='GET', path='/api/state' requestId='bd0b8cf7-38dc-48a4-9349-27439fbc5af1' sessionId='VJxZF_NubFe5JhTugalRvOd8hQRk03TV' ip='::ffff:192.168.88.205' message='Headers = {"host":"192.168.20.53:9091","connection":"keep-alive","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","accept":"*/*","referer":"http://192.168.20.53:9091/","accept-encoding":"gzip, deflate","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7","cookie":"PHPSESSID=roik5hqi4hgnp3ujo9lboveve4; XSRF-TOKEN=eyJpdiI6ImcwU1RzSEVYQzFYYnp3TzljNmkrcWc9PSIsInZhbHVlIjoiQ0UraVwvSlU2Y1wvbnB3b2RmUGN1MExJYjNxK3NtU2JrNVM0UmFlWUxzM2IxcnMza0ZRcnBpM1VGc3NDYVwvU3Y5QyIsIm1hYyI6IjhhMDU3OGUwNmIzNjJjYThjM2QzZDVhNDgwZDkxNjEwN2RmMWYwYzMwZWFmOTY2NzExMWU1Njk5MjM3ODc5MjQifQ%3D%3D; heimdall_session=eyJpdiI6Ik90VGpJUEhkMklyRTBnTyt4SGt4eEE9PSIsInZhbHVlIjoiZ294dXF1WVZSY1dWZDhMdnVsNnk5XC9tc25UbVUwakJoc0UwK0ZmZHl3MENRUEtxZkhXWTZqQnVQSCtmclE2bDgiLCJtYWMiOiIxNTc4NGI4NzgwZmNjMjMxZjFhOTM0YTY3YTIwODNhY2MxZjQxYjA3NjE0MDVkNGI4MDhmZjI0ZjBiOWQ1OTQwIn0%3D","if-none-match":"W/\"4d-Ih2hIJ41BY/p4An0DJ5FugMbeN4\""}'
debug: date='Wed Nov 27 2019 17:32:15 GMT+0000 (UTC)' method='GET', path='/api/state' requestId='bd0b8cf7-38dc-48a4-9349-27439fbc5af1' sessionId='VJxZF_NubFe5JhTugalRvOd8hQRk03TV' ip='::ffff:192.168.88.205' message='Session VJxZF_NubFe5JhTugalRvOd8hQRk03TV has no authentication information. Its internal id is: VJxZF_NubFe5JhTugalRvOd8hQRk03TV its current cookie is: {"originalMaxAge":3600000,"expires":"2019-11-27T18:32:15.420Z","secure":true,"httpOnly":true,"domain":"example.ru","path":"/"}'
debug: date='Wed Nov 27 2019 17:32:15 GMT+0000 (UTC)' method='GET', path='/api/state' requestId='bd0b8cf7-38dc-48a4-9349-27439fbc5af1' sessionId='VJxZF_NubFe5JhTugalRvOd8hQRk03TV' ip='::ffff:192.168.88.205' message='Authentication session VJxZF_NubFe5JhTugalRvOd8hQRk03TV was undefined. Resetting... If it's unexpected, make sure you are visiting the expected domain.'
^C

```
`

**Comment by clems4ever** [comment]
@xorira , can you please remove the link and paste the logs in the thread instead?

Do you still have the same problem with v3?

**Comment by nightah** [comment]
@clems4ever the logging in v4 with debug turned on does seem to be very different to v3, for example I can't see groups etc.

However, I have just successfully tested both v3 and v4 with Active Directory as the LDAP backend and had authentication, passing groups, Duo all work without any issues.

@xorira here's the `authentication_backend:` section of that working config for v4.
```yaml
# The authentication backend to use for verifying user passwords
# and retrieve information such as email address and groups
# users belong to.
#
# There are two supported backends: `ldap` and `file`.
authentication_backend:
  # LDAP backend configuration.
  #
  # This backend allows Authelia to be scaled to more
  # than one instance and therefore is recommended for
  # production.
  ldap:
    # The url of the ldap server
    url: ldap://adserverhere

    # The base dn for every entries
    base_dn: dc=example,dc=com

    # An additional dn to define the scope to all users
    additional_users_dn: ou=Managed Users

    # The users filter used to find the user DN
    # {0} is a matcher replaced by username.
    # 'cn={0}' by default.
    users_filter: (sAMAccountName={0})

    # An additional dn to define the scope of groups
    additional_groups_dn: ou=Managed Groups

    # The groups filter used for retrieving groups of a given user.
    # {0} is a matcher replaced by username.
    # {dn} is a matcher replaced by user DN.
    # 'member={dn}' by default.
    groups_filter: (member={dn})

    # The attribute holding the name of the group
    group_name_attribute: cn

    # The attribute holding the mail address of the user
    mail_attribute: mail

    # The username and password of the admin user.
    user: user@example.com
    password: passwordhere

    # File backend configuration.
    #
    # With this backend, the users database is stored in a file
    # which is updated when users reset their passwords.
    # Therefore, this backend is meant to be used in a dev environment
    # and not in production since it prevents Authelia to be scaled to
    # more than one instance.
    #
    ## file:
    ##   path: /etc/authelia/users_database.yml
```

**Comment by clems4ever** [comment]
@nightah , noted for the logs. Note that we now also have a trace level. However the kind of log you require should be in debug so we'll fix this for the future.

**Comment by clems4ever** [comment]
@xorira , have you solved your issue so far?

**Comment by nightah** [comment]
@xorira I'm going to close this issue off, I've successfully been able to get v4 working with AD as per the information provided above.
If you need additional assistance getting this working, my suggestion is to get on gitter and I can provide slightly more real-time support.
