### ISSUE TITLE
Vaultwarden@Authelia

### ISSUE THREAD

**Issue by Ramalama2** [authelia/authelia#4458]
Hey @dani-garcia & @james-d-elliott @clems4ever @night 
https://github.com/dani-garcia/vaultwarden/issues/2942

I think Vaultwarden combined with Authelia would benefit from each other:

- The one is a 2FA auth server for websites
- The other is a full featured password manager
For me that sounds like this 2 projects are made for each other.

What i mean in special is:
- Authelia could use the user backend from vaultwarden, as authelia doesn't offers good self hosting backend solutions, and ldap isn't one of them.
- Vaultwarden could use 2FA for the Admin interface from authelia, as there isn't 2FA still implemented.

There opens for sure a ton of more features and possibilities, but to keep it simple that 2 above would already make both solutions benefit from each other.

But it's up to you guys, i just wanted to start a conversation.
Because there may be a chance, that you like that idea.

Cheers :-)

**Comment by james-d-elliott** [comment]
1. Please do not blanket ping people directly like this. Only ping people when the context makes it unclear who you're talking to.
2. Please do not circumvent the issue templates.
3. There are two good self hosting authentication backends. The YAML provider is simple to use, and easy to integrate with, and optionally offers live reload. The LDAP provider is robust and great for anyone already with LDAP or who wants to get started with a industry standard authentication provider, and supports live reload.
4. We're unlikely to add support an authentication backend that doesn't have a widely adopted specification. I also don't see this feature being advertised by vaultwarden however we can continue this in the discussion created on the vaultwarden side.
