### ISSUE TITLE
4.37.3: MySQL/MariaDB: Storage Error/Corrupt DB error on improperly upgraded engine

### ISSUE THREAD

**Issue by jclendineng** [authelia/authelia#4519]
### Fix

https://github.com/authelia/authelia/issues/4519#issuecomment-1343297516

### Cause

https://github.com/authelia/authelia/issues/4519#issuecomment-1343398206

### Version

v4.37.3

### Deployment Method

Docker

### Reverse Proxy

SWAG

### Description

I get this error upgrading from 4.37.2 to 4.37.3:

{"level":"info","msg":"Storage schema migration from 6 to 7 is being attempted","time":"2022-12-08T09:23:52-05:00"}
{"level":"error","msg":"Failure running the storage provider startup check: error during schema migrate: error applying migration version 7 to version 6 for rollback: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted. rollback caused by: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":281,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:23:52-05:00"}
{"level":"fatal","msg":"The following providers had fatal failures during startup: storage","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":309,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:23:52-05:00"}

I thought maybe my DB (MariaDB) was corrupted so I dropped the DB (I have backups) and let authelia re-set it up on the new update, exact same issue, so I know its not a corrupt DB.

### Reproduction

Use MariaDB, clean install, set up a DB called "authelia" and assign a user to it.  Set up the DB in the authelia config, and start it up using version 4.37.2.  Everything works.  Upgrade to 4.37.3, it crashes, drop all DB tables, and start authelia with version 4.37.3, still crashes.

### Configuration (Authelia)

```yaml
#                   Authelia configuration                    #
###############################################################

jwt_secret: "xxx"
default_redirection_url: https://xxx/

server:
  host: 0.0.0.0
  port: 9091
  buffers.read: 4096
  buffers.write: 4096
  path: "authelia"

log:
  level: info
  format: json
  file_path: /config/log/authelia.log
  keep_stdout: false

totp:
  issuer: xxx
  period: 30
  skew: 1

ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 1s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  password_reset.disable: true
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: xxx
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: two_factor
  networks:
  - name: xxx
    networks:
      - 'xxx'
  - name: xxx
    networks:
      - 'xxx/xx'
  rules:
  - domain: [xxx]
    policy: bypass
  - domain: 'xxx'
    policy: bypass
    networks:
      - 'xxx'
      - 'xxx'
  - domain: 'xxx'
    policy: two_factor

session:
  name: authelia_session
  secret: "xxx"
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  domain: xxx
  redis:
    host: xxx
    port: 6379
    password: "xxx"
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 2w

storage:
  encryption_key: "xxx"
  mysql:
    host: xxx
    port: 3306
    database: authelia
    username: authelia
    password: "xxx"
    timeout: 5s

notifier:
  disable_startup_check: true
  smtp:
    username: xxx
    password: "xxx"
    host: xxx
    port: 587
    sender: xxx
    identifier: xxx
    subject: "[xxx] {title}"
    startup_check_address: xxx
    disable_require_tls: false
    disable_html_emails: false
    tls:
      server_name: xxx
      skip_verify: false
      minimum_version: TLS1.2
```

### Logs (Authelia)

```shell
{"level":"info","msg":"Shutting down","time":"2022-12-08T09:39:04-05:00"}
{"error":"bad connection","level":"error","msg":"Error occurred closing the database connection","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":197,"Name":"runServices"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":89,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:04-05:00"}
{"level":"info","msg":"Storage schema is being checked for updates","time":"2022-12-08T09:39:05-05:00"}
{"level":"info","msg":"Storage schema migration from 6 to 7 is being attempted","time":"2022-12-08T09:39:05-05:00"}
{"level":"error","msg":"Failure running the storage provider startup check: error during schema migrate: error applying migration version 7 to version 6 for rollback: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted. rollback caused by: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":281,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:05-05:00"}
{"level":"debug","msg":"notification provider: startup check skipped as it is disabled","time":"2022-12-08T09:39:05-05:00"}
{"level":"fatal","msg":"The following providers had fatal failures during startup: storage","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":309,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:05-05:00"}
{"level":"info","msg":"Storage schema is being checked for updates","time":"2022-12-08T09:39:05-05:00"}
{"level":"info","msg":"Storage schema migration from 6 to 7 is being attempted","time":"2022-12-08T09:39:05-05:00"}
{"level":"error","msg":"Failure running the storage provider startup check: error during schema migrate: error applying migration version 7 to version 6 for rollback: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted. rollback caused by: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":281,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:05-05:00"}
{"level":"debug","msg":"notification provider: startup check skipped as it is disabled","time":"2022-12-08T09:39:05-05:00"}
{"level":"fatal","msg":"The following providers had fatal failures during startup: storage","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":309,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:05-05:00"}
{"level":"info","msg":"Storage schema is being checked for updates","time":"2022-12-08T09:39:06-05:00"}
{"level":"info","msg":"Storage schema migration from 6 to 7 is being attempted","time":"2022-12-08T09:39:06-05:00"}
{"level":"error","msg":"Failure running the storage provider startup check: error during schema migrate: error applying migration version 7 to version 6 for rollback: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted. rollback caused by: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":281,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:06-05:00"}
{"level":"debug","msg":"notification provider: startup check skipped as it is disabled","time":"2022-12-08T09:39:06-05:00"}
{"level":"fatal","msg":"The following providers had fatal failures during startup: storage","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":309,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:06-05:00"}
{"level":"info","msg":"Storage schema is being checked for updates","time":"2022-12-08T09:39:07-05:00"}
{"level":"info","msg":"Storage schema migration from 6 to 7 is being attempted","time":"2022-12-08T09:39:07-05:00"}
{"level":"error","msg":"Failure running the storage provider startup check: error during schema migrate: error applying migration version 7 to version 6 for rollback: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted. rollback caused by: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":281,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:07-05:00"}
{"level":"debug","msg":"notification provider: startup check skipped as it is disabled","time":"2022-12-08T09:39:07-05:00"}
{"level":"fatal","msg":"The following providers had fatal failures during startup: storage","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":309,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:07-05:00"}
{"level":"info","msg":"Storage schema is being checked for updates","time":"2022-12-08T09:39:08-05:00"}
{"level":"info","msg":"Storage schema migration from 6 to 7 is being attempted","time":"2022-12-08T09:39:08-05:00"}
{"level":"error","msg":"Failure running the storage provider startup check: error during schema migrate: error applying migration version 7 to version 6 for rollback: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted. rollback caused by: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":281,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:08-05:00"}
{"level":"debug","msg":"notification provider: startup check skipped as it is disabled","time":"2022-12-08T09:39:08-05:00"}
{"level":"fatal","msg":"The following providers had fatal failures during startup: storage","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":309,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:08-05:00"}
{"level":"info","msg":"Storage schema is being checked for updates","time":"2022-12-08T09:39:10-05:00"}
{"level":"info","msg":"Storage schema migration from 6 to 7 is being attempted","time":"2022-12-08T09:39:10-05:00"}
{"level":"error","msg":"Failure running the storage provider startup check: error during schema migrate: error applying migration version 7 to version 6 for rollback: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted. rollback caused by: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":281,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:10-05:00"}
{"level":"debug","msg":"notification provider: startup check skipped as it is disabled","time":"2022-12-08T09:39:10-05:00"}
{"level":"fatal","msg":"The following providers had fatal failures during startup: storage","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":309,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:10-05:00"}
{"level":"info","msg":"Storage schema is being checked for updates","time":"2022-12-08T09:39:13-05:00"}
{"level":"info","msg":"Storage schema migration from 6 to 7 is being attempted","time":"2022-12-08T09:39:13-05:00"}
{"level":"error","msg":"Failure running the storage provider startup check: error during schema migrate: error applying migration version 7 to version 6 for rollback: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted. rollback caused by: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":281,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:13-05:00"}
{"level":"debug","msg":"notification provider: startup check skipped as it is disabled","time":"2022-12-08T09:39:13-05:00"}
{"level":"fatal","msg":"The following providers had fatal failures during startup: storage","stack":[{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":309,"Name":"doStartupChecks"},{"File":"github.com/authelia/authelia/v4/internal/commands/root.go","Line":87,"Name":"cmdRootRun"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":920,"Name":"(*Command).execute"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":1044,"Name":"(*Command).ExecuteC"},{"File":"github.com/spf13/cobra@v1.6.1/command.go","Line":968,"Name":"(*Command).Execute"},{"File":"github.com/authelia/authelia/v4/cmd/authelia/main.go","Line":10,"Name":"main"},{"File":"runtime/proc.go","Line":250,"Name":"main"},{"File":"runtime/asm_amd64.s","Line":1594,"Name":"goexit"}],"time":"2022-12-08T09:39:13-05:00"}
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
The error is from MySQL\MariaDB, we're just logging it. At this stage there is not enough information to reproduce, we do integration tests against the latest MySQL and MariaDB. Provide versions, and consider providing a dump privately so we can.

**Comment by james-d-elliott** [comment]
And permissions of the user

**Comment by jpslv** [comment]
I have the exact same problem as op.

**Comment by viper2g1** [comment]
I also have the same exact issue

**Comment by boomam** [comment]
Same issue for me here - 
```
Failure running the storage provider startup check: error during schema migrate: error applying migration version 7 to version 6 for rollback: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted. rollback caused by: schema migration 7 (ConsistencyFixes) failed: Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted"
```

Same [fix](https://github.com/authelia/authelia/issues/4519#issuecomment-1343297516) from @uisgebach also resolved the issue.

**Comment by Livefour2day** [comment]
Exactly the same issue for me on Unraid

**Comment by james-d-elliott** [comment]
Thanks for the fix. This is evidently a third party bug.

**Comment by james-d-elliott** [comment]
For reference this appears to occur when you upgrade MySQL or MariaDB without following their [upgrade instructions](https://dev.mysql.com/doc/refman/8.0/en/upgrading.html), assuming that link will contain information related, if it doesn't then it's a documentation bug on their end.

The short of it is that MySQL/MariaDB has a system schema which stores metadata about the other schemas in the database. This schema has a specific engine type, charsets, tables, etc. If they change this schema between versions (usually major versions, I'd guess), then this needs to be upgraded like described in https://github.com/authelia/authelia/issues/4519#issuecomment-1343297516 by running `mysql_upgrade` with the appropriate MySQL/MariaDB credentials.

**Comment by boomam** [comment]
@james-d-elliott  
> For reference...  

Question, this issue aside, how does postgres compare to mariadb from a performance point of view for Authelia?  

Equally, is there a migration path you would recommend?
Or would it just be a case of re-registering MFAs and the like, and not migrating data at all?

**Comment by masterwishx** [comment]
> `$ mysql_upgrade -u root -p`
> in the mariadb docker console.
> After that the error was gone.

Having same issue , Thanks for fixing ....

**Comment by james-d-elliott** [comment]
I've updated the post regarding the cause here: https://github.com/authelia/authelia/issues/4519#issuecomment-1343398206

I've also clearly outlined the fact that running `mysql_upgrade` after updating your MySQL/MariaDB container/package is **_REQUIRED by the MySQL/MariaDB developers_**, users who upgrade automatically will continue to have issues if they neglect this step. This is here: https://www.authelia.com/reference/integrations/database-integrations/#upgrades

**Comment by masterwishx** [comment]
> I've updated the post regarding the cause here

just confirmed same error, i got that its not authelia but MariaDB issue after updated , strange but its the first time happening in my case ...

**Comment by james-d-elliott** [comment]
> just confirmed same error, i got that its not authelia but MariaDB issue after updated , strange but its the first time happening in my case ...

It is because the changes they make internally that require `mysql_upgrade` seem to only affect specific features, in this case using the `CREATE PROCEDURE` statement at all.

**Comment by boomam** [comment]
To ask the dumb question - if rolling back a version of Authelia fixes the issue, but *also* doing the mysql upgrade command fixes it with the current Authelia version, to me that seems like something changed in what Authelia is doing in regards to the mysql/mariadb database?  

Reading through the issue opened on the [lsio/mariadb](https://github.com/linuxserver/docker-mariadb/issues/111) git page, from what I can tell its something that is certainly exacerbated by whatever they are/aren't doing automatically, but to ask the question, database wise, what *has* changed between the latest Authelia release, and one release back in regards to what it does database wise?

**Comment by jclendineng** [comment]
This fixed it for me! Not sure why LSIO MariaDB isn't doing this on update, I might submit a feature request to them. Thanks again for tracking this down...really helpful.

**Comment by james-d-elliott** [comment]
There is already one lodged and linked above to log an error/warning. I *personally* think this is a user responsibility that should just be well and clearly documented and they're complicating their container unnecessarily however.

**Comment by mluciotti** [comment]
> I had the same problem. After a short search for "Cannot load from mysql.proc" i tried `$ mysql_upgrade -u root -p` in the mariadb docker console. After that the error was gone.

Could someone please elaborate on how to run this command for an UnRaid user? Would this be through the UnRaid's terminal or something with the MariaDB docker?

**Comment by SVG62** [comment]
> У меня такая же проблема. После непродолжительного поиска «Не удается загрузить из mysql.proc» я попробовал `$ mysql_upgrade -u root -p` в консоли докера mariadb. После этого ошибка исчезла/

There was a similar error after a version upgrade, the command in the console "mysql_upgrade -u root -p" solved the problem with access to guacamole

**Comment by james-d-elliott** [comment]
As previously discussed this is an issue on the MySQL/MariaDB side, As such this is being closed. Users are welcome to open a [discussion](https://github.com/authelia/authelia/discussions) if they need further related assistance or can reach out to the developers or distributors of MySQL/MariaDB.

**Comment by insomnia23z** [comment]
For those of you that this following command didnt work:: $ mysql_upgrade -u root -p

I was able to resolve the issue by removing mariaDB from linuxserver's Repository (IBRACORP tutorial)
then installing 
MariaDB-Official by mgutt's Repository (you can create a new db and then edit the authelia config)
Then launched Authelia and it didnt crash!! 3hrs of trying to figure out a solution and it was so easy... after reading the compatible Authelia mariaDB versions.

**Comment by james-d-elliott** [comment]
It probably resulted in the data being wiped, which would indeed fix the issue. If you're pinning images per the guide all of the versions of MariaDB/MySQL are the same in how reliable they'll be, for the most part.

**Comment by ryu091** [comment]
> I had the same problem. After a short search for "Cannot load from mysql.proc" i tried `$ mysql_upgrade -u root -p` in the mariadb docker console. After that the error was gone.

I just wanted to say thank you.. and saving this comment for future reference.

**Comment by psycmos** [comment]
The error that i have:

The following providers had fatal failures during startup: storage" stack="github.com/authelia/authelia/v4/internal/commands/root.go:309 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"





> > I had the same problem. After a short search for "Cannot load from mysql.proc" i tried `$ mysql_upgrade -u root -p` in the mariadb docker console. After that the error was gone.
> 
> I just wanted to say thank you.. and saving this comment for future reference.

It works to me too! 
I used IBRACORP Authelia TUTORAL and Linuxserver's Repository and the command "mysql_upgrade -u root -p` in the mariadb docker console." solve the issue!

**Comment by jrsecor** [comment]
> For those of you that this following command didnt work:: $ mysql_upgrade -u root -p
> 
> I was able to resolve the issue by removing mariaDB from linuxserver's Repository (IBRACORP tutorial) then installing MariaDB-Official by mgutt's Repository (you can create a new db and then edit the authelia config) Then launched Authelia and it didnt crash!! 3hrs of trying to figure out a solution and it was so easy... after reading the compatible Authelia mariaDB versions.
> 
> I then also stopped autoupdates for all apps and removed mariadb from updating to avoid headaches.

For future reference, I was able to solve this by just creating a new database through adminer (essentially just authelia2) and then just changing the line in the configuration.yml for authelia to point to that db instead after giving the authelia user access to the new db. Basically just two lines to change. May be a bit simpler than reinstalling a different version (in case you have other dbs used for other apps). Regardless, thanks for getting me on the right track!

**Comment by james-d-elliott** [comment]
This topic is about the error `Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted.` not other errors. Please stop posting off-topic information. It's confusing users and potentially leading to other issues.

**Comment by james-d-elliott** [comment]
We really appreciate users trying to help out. I can't stress this enough.

However in this particular case I'm deciding to permanently lock this issue for the following reasons:

1. I've asked on multiple occasions that only the error `Error 1728 (HY000): Cannot load from mysql.proc. The table is probably corrupted.` is discussed here and:
    1. Other issues either subsequent to the improper upgrade of MySQL itself (i.e. unrelated to Authelia) or unrelated issues are discussed here which is off-topic.
    2. This distracts from the actual resolution making it confusing and potentially more damaging for users database state than the original lack of proper maintenance procedures being followed. 
2. The answer is explicitly provided here and part of our supported databases documentation.
3. GitHub Issues are for discussing bugs and features, but this is neither. This is related to users either automatically upgrading or manually upgrading MySQL/MariaDB without following the correct upgrade process. The appropriate location to discuss this is [GitHub Discussions](https://github.com/authelia/authelia/discussions).

So we can best support users with this specific issue or  we suggest that any user having a subsequent issue to this does the following:

1. Opens a [New Discussion](https://github.com/authelia/authelia/discussions/new?category=q-a).
2. Describes their particular issue situation including the logs so that users can accurately see the symptoms.
3. Describes what they have already tried.
4. Optionally describes their intended and/or attempted fixes.
