### ISSUE TITLE
Default group filter ignores most AD groups

### ISSUE THREAD

**Issue by ybizeul** [authelia/authelia#4551]
### Version

v4.37.3

### Deployment Method

Kubernetes

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.7.1

### Description

A filter has been recently added to require `sAMAccountType=268435456`

https://github.com/authelia/authelia/blob/e97a84860044cd88f0d63ec139945a6df8761828/internal/configuration/schema/authentication.go#L194

This seems to be fine for Global scoped group, but not Domain local, which seem to be the case of admin created groups (not sure about the actual reason)

![image](https://user-images.githubusercontent.com/182035/206991748-b8e1b96b-a326-40b5-8a03-d11721233eaf.png)

![IMG_3075](https://user-images.githubusercontent.com/182035/206991852-17152b28-fa1c-4527-b62a-3248fade0d21.png)

filetering on `sAMAccountType=268435456` prevents a match against the "Family" group here.

### Reproduction

Deploy Authelia with LDAP pointing to Active Directory, and try authenticating against a new group in the domain.

### Expectations

Group filter should be able to fetch all user groups, not only Global scope.

### Logs (Authelia)

```shell
time="2022-12-12T08:41:02+01:00" level=trace msg="Computed groups filter is (&(member=CN=Yann Bizeul,CN=Users,DC=home,DC=lab)(sAMAccountType=268435456))"
time="2022-12-12T08:41:02+01:00" level=trace msg="Performing group search" attr="[cn]" base_dn="cn=Users,DC=home,DC=lab" deref=0 filter="(&(member=CN=Yann Bizeul,CN=Users,DC=home,DC=lab)(sAMAccountType=268435456))" scope=2
time="2022-12-12T08:41:02+01:00" level=trace msg="Profile details for user 'yann' => groups: [Domain Admins Storage Admins], emails [yann@tynsoe.org]" method=POST path=/api/firstfactor remote_ip=10.0.1.120
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
I'm not entirely sure if matching the group in this instance is appropriate according to Microsoft docs. Domain Local groups are only *meant* to be a match when the requesting server (authelia) is a member of the domain (which it isn't since we don't support kerberos tickets): `A group object whose membership is added to the authorization context only if the server receiving the context is a member of the same domain as the resource group.`

Could you explain what the purpose is behind using a domain local group instead of a global group?

**Comment by ybizeul** [comment]
Well that's as far as my knowledge of Active Directory goes.

Those groups were created "Domain Local" for some reason, I can definitely re-create them with Global if that's how it's supposed to be !

**Comment by james-d-elliott** [comment]
I'd recommend using `(&(member={dn})(|(sAMAccountType=268435456)(sAMAccountType=536870912)))` for your groups filter. I think there is enough ambiguity for us to make this the default in 4.38 as it still excludes distribution groups.
