### ISSUE TITLE
Authelia v4 is unable to send email via Office365 SMTP

### ISSUE THREAD

**Issue by Iwan-Authelia** [authelia/authelia#464]
Hi,

I've used the same config and ldap as for V3 and got this error;

ERRO[0037] Error while checking password for user iwan: Cannot find user DN of user iwan. Cause: LDAP Result Code 201 "Filter Compile Error": ldap: filter does not start with an '('  method=POST path=/api/firstfactor remote_ip=127.0.0.1 

Ldap config;

authentication_backend:
  ldap:
    url: ldap://127.0.0.1
    base_dn: dc=example,dc=com
    additional_users_dn: ou=people
    users_filter: uid={0}
    additional_groups_dn: ou=groups
    groups_filter: (&(member={dn})(objectclass=groupOfNames))
    group_name_attribute: cn
    mail_attribute: mail
    user: cn=admin,dc=example,dc=com
    password: xxxx

root@auth:/usr/src# ldapwhoami -vvv -h 127.0.0.1 -D "uid=iwan,ou=people,dc=example,dc=com" -x -W
ldap_initialize( ldap://127.0.0.1 )
Enter LDAP Password:
dn:uid=iwan,ou=people,dc=example,dc=com
Result: Success (0)
root@auth:/usr/src#

**Comment by nightah** [comment]
@Iwan-Authelia you need to enclose your users_filer with parenthesis `users_filter: uid={0}` should become `users_filter: (uid={0})`.

The config template has also been updated to reflect this example: https://github.com/clems4ever/authelia/blob/1c35be7c27e0275010169c2bec478a861faa76a8/config.template.yml#L69

**Comment by Iwan-Authelia** [comment]
Thanks @nightah 

That fixed this error. I also took 'secure' out of the SMTP section which now shows;

notifier:
  smtp:
    username: admin@example.com
    password: <password>
    host: smtp.office365.com
    port: 587
    sender: admin@example.com

however this error is produced;

DEBU[0003] Sending an email to user iwan (iwan.boskamp@example.com) to confirm identity for registering a device.  method=POST path=/api/secondfactor/totp/identity/start remote_ip=127.0.0.1
ERRO[0014] 504 5.7.4 Unrecognized authentication type [ME1PR01CA0088.ausprd01.prod.outlook.com]  method=POST path=/api/secondfactor/totp/identity/start remote_ip=127.0.0.1 stack="/go/src/app/internal/middlewares/authelia_context.go:58          (*AutheliaCtx).Error\n/go/src/app/internal/middlewares/identity_verification.go:73     IdentityVerificationStart.func1\n/go/src/app/internal/middlewares/require_first_factor.go:14      RequireFirstFactor.func1\n/go/src/app/internal/middlewares/authelia_context.go:43          AutheliaMiddleware.func1.1\n/go/pkg/mod/github.com/fasthttp/router@v0.5.2/router.go:326      (*Router).Handler\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/header.go:123     (*ResponseHeader).StatusCode\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/server.go:2018    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:223 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1357                       goexit"

Could be related to this;

Beginning November 1st, 2019, Office 365 is slowly turning off the TLS cipher algorithm 3DES. If you are using devices or applications that only support 3DES, TLS will start failing. As TLS is mandatory for the SMTP AUTH client submission (also known as Authenticated SMTP or SMTP AUTH for short), you may experience emails no longer sending. You will need to upgrade or update all of your devices and applications to use the new TLS version and ciphers.

**Comment by nightah** [comment]
The issue appears to be specifically with Office 365, it requires LOGIN to be as per RFC 4616.

@clems4ever reference: https://github.com/go-gomail/gomail/issues/16

**Comment by clems4ever** [comment]
> @Iwan-Authelia you need to enclose your users_filer with parenthesis `users_filter: uid={0}` should become `users_filter: (uid={0})`.
> 
> The config template has also been updated to reflect this example:
> 
> https://github.com/clems4ever/authelia/blob/1c35be7c27e0275010169c2bec478a861faa76a8/config.template.yml#L69
> 
> It's also worthwhile reading the https://github.com/clems4ever/authelia/blob/master/BREAKING.md as there are other changes you need to consider.

I will add the retro compatibility to avoid having this kind of issue in the future. It's easy to do.

**Comment by clems4ever** [comment]
> The issue appears to be specifically with Office 365, it requires LOGIN to be as per RFC 4616.
> 
> @clems4ever reference: [go-gomail/gomail#16](https://github.com/go-gomail/gomail/issues/16)

LOGIN is supported by the official Golang SMTP library. You just need to provide the credentials in Authelia conf normally.

@Iwan-Authelia , do you confirm you set up the credentials in the notifications section of the configuration?

**Comment by Iwan-Authelia** [comment]
@clems4ever Yes, credentials are set and correct.

Interestingly, I've tried it in the V3 version as well and the credentials only work when secure: false is set.
In the V4 version I had to delete the secure: from the config and it does not work with office365.com

I have, for now, relayed the email via an internal mailserver which works fine but it would be good to be able to use the office365.com smtp server.

**Comment by clems4ever** [comment]
Hello @Iwan-Authelia , I completely agree that it should work with office365.com. I will definitely have a look.

**Comment by james-d-elliott** [comment]
I was under the impression Golang SMTP library only supported CRAM-MD5 and PLAIN login:

https://golang.org/src/net/smtp/auth.go
https://golang.org/src/net/smtp/example_test.go

I am working on a feature branch on my fork to see if I can get the same thing to work, as well as StartTLS. It's adaptive so it will check the Extensions available on the SMTP server and only auth/starttls if it supports it.

https://github.com/james-d-elliott/authelia/tree/feature/notification-smtp-adaptive-auth-and-starttls

**Comment by james-d-elliott** [comment]
@Iwan-Authelia I've not verified my fix wth O365. If you're using the docker image can you see if it works with mine? Image is docker.io/jamesdelliott/authelia:smtp-adaptive-auth or jamesdelliott/authelia:smtp-adaptive-auth

**Comment by clems4ever** [comment]
@Iwan-Authelia , the PR is merged now so you will be able to test with master tag in few minutes.
