### ISSUE TITLE
Customize login page text

### ISSUE THREAD

**Issue by wez** [authelia/authelia#4657]
### Description

In a similar vein as https://github.com/authelia/authelia/issues/1630, I'd like to be able to adjust the text on the login page so that it is clearer for users to see what is being logged into and increase their trust in a world that is filled with phishing attacks.

### Use Case

My users don't know what Authelia is, and I'd like to make it clear which password they need to enter and why. Right now the login page is very plain; having the ability to adjust:

* "Sign In" -> "Sign In to the XYZ network", or "XYZ Sign In", or really any text that clarifies what is being signed into
* Augment (not necessarily replace) the "Powered by Authelia" footer with some text like "Contact XYZ for help"

Bonus points:

* Some templating expansion options: if we know that we're going to redirect somewhere, having the ability to show that domain on the page through a template token of some kind would help orient folks.  For example, if I visit a domain that needs auth, but step away to eat dinner before I auth, when I later return to my computer, the login page doesn't tell me where I would end up: my context is lost and I'm not sure what I was doing.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Can already be done via localization overrides.

**Comment by wez** [comment]
* At the bottom of #1630 it was requested for an issue to be opened to follow up on it, which is what this issue is/was
* This issue has been shut down with a rather terse response
* There's no link from here to the information needed to achieve this goal
* I couldn't find documentation on how to do this

I totally get that OSS collaborators have limited time (I've been in this for a long time myself), but wanted to share that my first impression is: "these guys are pretty abrupt, do I want to stick with authelia?", which probably isn't what you intended.
