### ISSUE TITLE
Safari build in OTP no longer works

### ISSUE THREAD

**Issue by bitte-ein-bit** [authelia/authelia#4660]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

v2.6

### Description

Before updating Safari could enter the OTP automatically if added to the keychain. Now it no longer can, since autocomplete is now set to `off`. Using Developer mode and changing the autocomplete to `one-time-code` makes it behave as before.

I suspect this change: https://github.com/authelia/authelia/pull/4548

### Reproduction

* Add user + password + otp to MacOS keychain (or iOS devices)
* Log in, user + password is completed, OTP is just waiting for input with no direct way to retrieve the OTP token

### Expectations

as before, I'd like to place my thumb twice on the thumb reader and be signed in completely. 

### Logs (Authelia)

```shell
N/A - UI issue
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
I'm about to merge a fix. However it should be noted saving OTP's and Passwords in the same manager is not a great idea generally.
