### ISSUE TITLE
Error accessing iOS apps with Authelia turned ON - 

### ISSUE THREAD

**Issue by parikhparth23** [authelia/authelia#4661]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX Proxy Manager

### Reverse Proxy Version

1.26.1

### Description

I am getting the following error:

`Wallabag`
```
time="2022-12-28T13:01:24-08:00" level=info msg="Access to https://appname.mydomain.com/oauth/v2/token
(method unknown) is not authorized to user <anonymous>,
responding with status code 401" method=GET path=/api/verify remote_ip=CLOUDFLARE_IP
 ```
 
 `Finamp`
 ```
 time="2022-12-28T13:13:26-08:00" 
level=info 
msg="Access to 
https://appname.mydomain.com/Users/de59719040574174890635ff97e7cfc6/Items?IncludeItemTypes=MusicAlbum&ParentId=7e64e319657a9516ec78490da03edccb&Recursive=true&SortBy=SortName&SortOrder=Ascending&Fields=parentId%2CindexNumber%2CsongCount%2CchildCount%2CproviderIds%2Cgenres%2Ctags%2CEtag%2CalbumPrimaryImageTag%2CparentPrimaryImageItemId&StartIndex=0&Limit=100 (method unknown) is not authorized to user <anonymous>, responding with status code 401" 
method=GET path=/api/verify remote_ip=CLOUDFLARE_IP
```
 
I am able to get Authelia login screen from the Website/Browser but when using the iOS apps I get the error.
 
 I am trying to access the following apps:
 [Wallabag](https://apps.apple.com/fr/app/wallabag-2-official/id1170800946?l=en&mt=8)
 [Piwigo](https://apps.apple.com/us/app/piwigo/id472225196)
 [Finamp](https://apps.apple.com/us/app/finamp/id1574922594) - Jellyfin offline client
 
 I followed this tutorial: https://www.youtube.com/watch?v=4UKOh3ssQSU
 Authelia Configs: https://dbt3ch.com/books/authelia-for-nginx-proxy-manager
 
 

### Reproduction

You will need to have Nginx Proxy Manager, CloudFlare, Portainer/Docker image of Authelia

Follow this YouTube tutorial - https://www.youtube.com/watch?v=4UKOh3ssQSU
and use this Authelia Configs: https://dbt3ch.com/books/authelia-for-nginx-proxy-manager

I am able to get Authelia login screen from the website but when using the iOS apps I get the error.

### Expectations

Even the iOS apps should work fine without any issues.

### Configuration (Authelia)

```yaml
Please use all the configs mentioned here - https://dbt3ch.com/books/authelia-for-nginx-proxy-manager
```

### Logs (Authelia)

```shell
`Wallabag`


time="2022-12-28T13:01:24-08:00" level=info msg="Access to https://appname.mydomain.com/oauth/v2/token
(method unknown) is not authorized to user <anonymous>,
responding with status code 401" method=GET path=/api/verify remote_ip=CLOUDFLARE_IP
 ```
 
 `Finamp`

 ```
 time="2022-12-28T13:13:26-08:00" 
level=info 
msg="Access to 
https://appname.mydomain.com/Users/de59719040574174890635ff97e7cfc6/Items?IncludeItemTypes=MusicAlbum&ParentId=7e64e319657a9516ec78490da03edccb&Recursive=true&SortBy=SortName&SortOrder=Ascending&Fields=parentId%2CindexNumber%2CsongCount%2CchildCount%2CproviderIds%2Cgenres%2Ctags%2CEtag%2CalbumPrimaryImageTag%2CparentPrimaryImageItemId&StartIndex=0&Limit=100 (method unknown) is not authorized to user <anonymous>, responding with status code 401" 
metho
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
This is not an issue with authelia, one of the following must be true:

1. The iOS app must support redirections and session cookies.
2. The protected app needs to support OpenID Connect
3. You must craft rules to allow the app to work with app auth but the website to still require auth, as with apps which use a API key to talk via the website api.
