### ISSUE TITLE
CSP blocks javascript on the oidc autorization page

### ISSUE THREAD

**Issue by levkoburburas** [authelia/authelia#4669]
### Version

v4.37.5

### Deployment Method

Other

### Reverse Proxy

NGINX

### Description

This code:
https://github.com/authelia/authelia/blob/633680e8e5e8188b0f5667b5c77eb692f0e58a0d/internal/server/handlers.go#L139
applies Content-Security-Policy headers with "default-src 'none'" for all oidc pages generated by `github.com/ory/fosite`

which in turn blocks the execution of the inline javascript which redirects users back to the client:
https://github.com/ory/fosite/blob/e570564951ec312d5dc1c1c21180ca3e759c5075/authorize_helper.go#L24

![image](https://user-images.githubusercontent.com/62853952/210153942-575751c0-e226-42cf-a286-817e9be0c360.png)

The workaround is to remove "Content-Security-Policy" is assigned by server and set the "correct value" in the `nginx proxy` configuration. 

```
proxy_hide_header Content-Security-Policy;
add_header Content-Security-Policy "default-src 'self' 'unsafe-inline';" always;
```

### Reproduction

Use **OpenID Connect**  with a client that supports only  `form_post`  response_mode.

### Logs (Authelia)

```shell
identity_providers:
  oidc:
    clients:
      -
        response_modes:
          - form_post

```
```


### Logs (Proxy / Application)

_No response_

### Documentation

_No response_

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by levkoburburas** [comment]
Pull request #4670 which solves this issue.

**Comment by james-d-elliott** [comment]
That's unfortunate, unsafe inline is not really an answer. I appreciate the PR however it's likely this can be entirely handled by the `FormPostHTMLTemplateProvider` without the need for any additional machinery except for setting the header itself (probably with a sha256).

**Comment by levkoburburas** [comment]
> That's unfortunate, unsafe inline is not really an answer. I appreciate the PR however it's likely this can be entirely handled by the `FormPostHTMLTemplateProvider` without the need for any additional machinery except for setting the header itself (probably with a sha256).

@james-d-elliott, by the workaround I meant the solution without changing the code (Maybe someone will need it).
I created the pull request https://github.com/authelia/authelia/pull/4670, which solves this in a safe way.

**Comment by james-d-elliott** [comment]
Can you checkout the `fix-oidc-formpost-csp` tag and let me know if this fixes it? We can focus on the feature portion after the functional portion is fixed.

@all-contributors please add @levkoburburas for code, ideas, bug

**Comment by james-d-elliott** [comment]
aeneasr is also super busy. He's been in the top 5 comitters on GitHub for years now.
