### ISSUE TITLE
Authelia  error on non normative response from ProtonMail Birdge

### ISSUE THREAD

**Issue by seandonohoo** [authelia/authelia#4717]
### Version

v4.37.5

### Deployment Method

Kubernetes

### Reverse Proxy

NGINX

### Reverse Proxy Version

4.4.2

### Description

I'm currently working on trying to get Authelia to work with Proton Mail bridge. Proton mail bridge requires SMTP authentication. I've turned off certificate checking for the moment. 

When attempting to register a device an email tries to get sent but it cannot as Authelia doesn't know how to handle the SMTP response. 

I've confirmed that this works using telnet so I know its not the mail bridge authentication issue. 

### Reproduction

1. Login as the user
2. Click register device
3. Unexpected error

### Configuration (Authelia)

```yaml
AUTHELIA_NOTIFIER_SMTP_DISABLE_REQUIRE_TLS: "false"
      AUTHELIA_NOTIFIER_SMTP_HOST: "protonmail-bridge-smtp.mail.svc.cluster.local"
      AUTHELIA_NOTIFIER_SMTP_PORT: 25
      AUTHELIA_NOTIFIER_SMTP_SENDER: "Authelia <home@${SECRET_DOMAIN}>"
      AUTHELIA_NOTIFIER_SMTP_USERNAME: "${SECRET_SMTP_USERNAME}"
      AUTHELIA_NOTIFIER_SMTP_TLS_SKIP_VERIFY: "true"
```

### Logs (Authelia)

```shell
time="2023-01-06T19:57:22Z" level=debug msg="Sending an email to user SANTIZED USER to confirm identity for registering a device." method=POST path=/api/secondfactor/totp/identity/start remote_ip=SANTIZED
time="2023-01-06T19:57:22Z" level=debug msg="creating client with 6 options: [0x55de1fd8e280 0x55de1fd8e200 0x55de1fd8e180 0x55de1fd8e140 0x55de1fd8ef20 0x55de1fd8e0e0]"
time="2023-01-06T19:57:22Z" level=error msg="notifier: smtp: failed to dial connection: SMTP AUTH failed: unexpected server response: 2.0.0 Authentication succeeded" method=POST path=/api/secondfactor/totp/identity/start remote_ip=SANITIZED stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:65      (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/middlewares/identity_verification.go:88 IdentityVerificationStart.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/require_first_factor.go:15  Require1FA.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54                (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25               SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35               SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16               SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                                 (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                                  (*Response).StatusCode\ngithub.com/authelia/authelia/v4/internal/middlewares/metrics.go:22               NewMetricsRequest.func1.1\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                               (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                            (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                            (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                         goexit"
```

### Documentation

https://github.com/shenxn/protonmail-bridge-docker

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
`2.0.0 Authentication succeeded` is not a valid AUTH response.

**Comment by seandonohoo** [comment]
@james-d-elliott I'd say a bug with one of the most popular modern languages 😂 . Kidding aside this is the only SMTP protocol that I've seen added the 2.0.0 in front. I'll open a bug report with Proton to see why they have this. From the telnet output I've confirmed it does have 235 in the very front but 2.0.0 is added. 

`235 2.0.0 Authentication succeeded`

**Comment by james-d-elliott** [comment]
I think it's a bug with go-mail: https://github.com/wneessen/go-mail/issues/94

I think ProtonMail is just returning a non-normative but still technically compliant response.

**Comment by seandonohoo** [comment]
Yup the AUTH scheme is LOGIN.

**Comment by james-d-elliott** [comment]
The tag `build-deps-go-smtp` should fix this issue. It'll be included in [4.38.0](https://github.com/authelia/authelia/milestone/17) but if you'd like me to create a branch with 4.37.5 + the fix it's easy for me to do.

**Comment by james-d-elliott** [comment]
@seandonohoo if you've not seen this just pinging you to ensure you do. Would be good to confirm the fix works even though the lib author did so generously.

**Comment by seandonohoo** [comment]
Will be checking shortly @james-d-elliott

**Comment by seandonohoo** [comment]
@james-d-elliott confirmed that this is now working with the branch of "build-deps-go-smtp"

**Comment by james-d-elliott** [comment]
Thanks. If you'd like a temporary build prior to 4.38 let me know and I'll cherry pick the fixes into 4.37.5.

**Comment by seandonohoo** [comment]
@james-d-elliott would you be able to get a temporary build for this going now that 'build-deps-go-smtp' is gone?

**Comment by james-d-elliott** [comment]
You can use [v4.38.0-beta1](https://hub.docker.com/layers/authelia/authelia/v4.38.0-beta1/images/sha256-53faae6b6a0616f71f1f77069237d92969433b0037b9825be12852e013812bd0?context=explore)

**Comment by day-mon** [comment]
@james-d-elliott I am going through this same issue with beta2. I cant do reset emails.

**Comment by james-d-elliott** [comment]
It's been confirmed working by 3 parties.

**Comment by day-mon** [comment]
![Jun_2023_18_12_06_06](https://github.com/authelia/authelia/assets/27317976/87cb7c38-e6e3-4f57-be7b-6d10532e5f5c)

Heres the error I am encountering

**Comment by james-d-elliott** [comment]
The server has an invalid certificate. Not the same error in the slightest.

**Comment by day-mon** [comment]
Sorry about a false flag but would you have any idea on how to fix this?
