### ISSUE TITLE
Bootloop if SMTP certificate expired

### ISSUE THREAD

**Issue by r748** [authelia/authelia#4767]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.9.6

### Description

I just spent a couple hours trying to figure out, why my authelia container constantly kept restarting, as logs did not show any errors. It turns out, the reason was an expired SSL certificate of the SMTP server configured in the notification section of the authelia config. Disabling SMTP and using filesystem notifications resolved the issue.

### Reproduction

Configure SMTP and use an expired certificate on the server.

### Expectations

Errors leading to a restart of the container should be shown in the log.

### Configuration (Authelia)

```yaml
notifier:
#  filesystem:
#    filename: /config/notification.txt
  smtp:
    username: auth@xxx.com
    password: PASSWORD
    host: smtp.xxx.com
    port: 465
    sender: auth@xxx.com
```

### Logs (Authelia)

```shell
time="2023-01-14T15:19:36+01:00" level=info msg="Authelia v4.37.5 is starting"
time="2023-01-14T15:19:36+01:00" level=info msg="Log severity set to debug"
time="2023-01-14T15:19:38+01:00" level=info msg="Authelia v4.37.5 is starting"
time="2023-01-14T15:19:38+01:00" level=info msg="Log severity set to debug"
time="2023-01-14T15:19:39+01:00" level=info msg="Authelia v4.37.5 is starting"
time="2023-01-14T15:19:39+01:00" level=info msg="Log severity set to debug"
time="2023-01-14T15:19:40+01:00" level=info msg="Authelia v4.37.5 is starting"
time="2023-01-14T15:19:40+01:00" level=info msg="Log severity set to debug"
time="2023-01-14T15:19:42+01:00" level=info msg="Authelia v4.37.5 is starting"
time="2023-01-14T15:19:42+01:00" level=info msg="Log severity set to debug"
time="2023-01-14T15:19:44+01:00" level=info msg="Authelia v4.37.5 is starting"
time="2023-01-14T15:19:44+01:00" level=info msg="Log severity set to debug"
time="2023-01-14T15:19:48+01:00" level=info msg="Authelia v4.37.5 is starting"
time="2023-01-14T15:19:48+01:00" level=info msg="Log severity set to debug"x
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
1. You didn't include your full configuration. See `Provide a complete configuration file (the template will automatically put this content in a code block)` which exists in the template.
2. The reasons for it failing ARE shown in the log. You're just not looking at the log where you've [configured it](https://www.authelia.com/configuration/miscellaneous/logging/). You've set a file, but not configured it to keep stdout.
