### ISSUE TITLE
Make first factor failures non-success status codes for easy log filtering

### ISSUE THREAD

**Issue by Drakulix** [authelia/authelia#478]
Hey @clems4ever,
I have noticed another inconvenience. :sweat_smile: 

Failures in authelia's first factor authentication currently return a 200 status code.
Which is imo not good practice, as the login call was really not 'successful', and very inconvenient for logging authentication failures.

I have traefik configured to log client errors (status codes 400-499), which works nicely for Basic Auth, but fails to detect any failures using authelia's web interface.

I am feeding my logs into fail2ban. I know, that authelia's has its own banning feature, but I am using fail2ban for multiple services on my system (including other traefik services) and would like to reuse it for authelia as well.

From what I have seen browsing the source code, you are using axios on the frontend side, which [should still work fine with 400 codes](https://github.com/clems4ever/authelia/blob/master/web/src/services/Client.ts#L7) and take the same branch.

On the backend side, it seems that [Error](https://github.com/clems4ever/authelia/blob/master/internal/middlewares/authelia_context.go#L49) and [ReplyError](https://github.com/clems4ever/authelia/blob/master/internal/middlewares/authelia_context.go#L62) would need to be adjusted to return different status codes.

Do you think this approach would work, or might that break other parts of authelia? I am not to familiar with go, but I guess I could make a quick PR, if that is all this takes? (And you are agreeing with this request of course.)

(Note: The same might apply to the second factor, but I have not tested that *yet*)

**Comment by clems4ever** [comment]
Hello @Drakulix , the response/return codes were harmonized on purpose following https://github.com/clems4ever/authelia/issues/133. Now, I can definitely understand that some people would want to rely on fail2ban to block IPs. By the way the big difference with authelia banning mechanism is that Authelia ban user accounts while fail2ban block IPs.

I'm ok with the change and I'd be glad to review it.

**Comment by james-d-elliott** [comment]
@Drakulix implemented in master. Will be in the next release or authelia/authelia:master image.
