### ISSUE TITLE
Create and document self-sufficient docker-compose setups

### ISSUE THREAD

**Issue by clems4ever** [authelia/authelia#480]
Using suites is too complicated for non dev people so we need to provide self-sufficient docker-compose setups to deploy the stack in seconds in order to demo authelia.

Having a "lite" and "complete" flavors would be great.

- Create docker-compose bundle for highly available setup and document it
- Create docker-compose bundle for standalone setup and document it

**Comment by thepenguinthatwants** [comment]
It would be nice to learn how to deploy on one server setup using docker-compose and traefik 2.0 without separate ldap setup to authenticate own self hosted services.

**Comment by nightah** [comment]
@thepenguinthatwants I'll be looking to close this off in the next week or so.
For feel free to check out #580 I suspect the Traefik 2.0 example would be quite helpful to you.

Authelia is also capable of being deployed with a file based database, please see https://github.com/authelia/authelia/blob/master/docs/deployment-dev.md for more information.

If you have any issues with that please don't hesitate to open a separate ticket or jump on [Matrix](https://riot.im/app/#/room/#authelia:matrix.org) for assistance!

**Comment by nightah** [comment]
@thepenguinthatwants please feel free to attempt the new compose deployment methods that we have introduced. Any and all feedback is welcomed!
