### ISSUE TITLE
Portainer OpenID Connect Error

### ISSUE THREAD

**Issue by ajb3932** [authelia/authelia#4804]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

Caddy

### Description

Hi,
I'm hoping this is an easy fix. I have Authelia OpenID working fine for other applications such as Proxmox. However when I set up Portainer it seems to work but when I log in I get suck in a loop. I inititally thought it was a time issue so I set NTP up but I still receive this error. FYI I'm using cloudflare tunnels, not a reverse proxy.

Looking at the logs I get the error message:
```
time="2023-01-20T11:27:49Z" 
level=error 
msg="Authorization Response for Request with id 'REDACTED' on client with id 'portainer' could not be created: The Authorization Server requires End-User authentication. Failed to validate OpenID Connect request because prompt was set to 'login' but auth_time ('2023-01-20 11:27:46 +0000 UTC') happened before the authorization request ('2023-01-20 11:27:47.760624351 +0000 UTC') was registered, indicating that the user was not re-authenticated which is forbidden."
```

This is my id config:
```
      - id: portainer
        description: Portainer
        secret: '$plaintext$REDACTED'
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - https://REDACTED
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signing_algorithm: none
```

And my Portainer config:
![image](https://user-images.githubusercontent.com/45558436/213688387-9aadf710-efb7-45b2-a19e-8c13797a98cc.png)

Many thanks for looking into this.

### Reproduction

Using the config specified in the issue.

### Expectations

Being able to log in to Portainer.

### Logs (Authelia)

```shell
time="2023-01-20T11:27:47Z" level=debug msg="Authorization Request with id 'REDACTED' on client with id 'portainer' is being processed" method=GET path=/api/oidc/authorization remote_ip=REDACTED
time="2023-01-20T11:27:47Z" level=debug msg="Authorization Request with id 'REDACTED' on client with id 'portainer' using consent mode 'explicit' proceeding to generate a new consent session" method=GET path=/api/oidc/authorization remote_ip=REDACTED
time="2023-01-20T11:27:47Z" level=debug msg="Authorization Request with id 'REDACTED' on client with id 'portainer' using consent mode 'explicit' authentication level 'one_factor' is sufficient for client level 'one_factor'" method=GET path=/api/oidc/authorization remote_ip=REDACTED
time="2023-01-20T11:27:47Z" level=debug msg="Authorization Request with id 'REDACTED' on client with id 'portainer' using consent mode 'explicit' is being redirected to 'https://auth.REDACTED/consent?id=cb86eadc-8a00-4e8f-87f0-a36dd03741da'" method=GET path=/api/oidc/authorization remote_ip=REDACTED
time="2023-01-20T11:27:49Z" level=debug msg="Authorization Request with id 'REDACTED' on client with id 'portainer' is being processed" method=GET path=/api/oidc/authorization remote_ip=REDACTED
time="2023-01-20T11:27:49Z" level=debug msg="Authorization Request with id 'REDACTED' on client with id 'portainer' was successfully processed, proceeding to build Authorization Response" method=GET path=/api/oidc/authorization remote_ip=REDACTED
time="2023-01-20T11:27:49Z" level=error msg="Authorization Response for Request with id 'REDACTED' on client with id 'portainer' could not be created: The Authorization Server requires End-User authentication. Failed to validate OpenID Connect request because prompt was set to 'login' but auth_time ('2023-01-20 11:27:46 +0000 UTC') happened before the authorization request ('2023-01-20 11:27:47.760624351 +0000 UTC') was registered, indicating that the user was not re-authenticated which is forbidden." method=GET path=/api/oidc/authorization remote_ip=REDACTED stack="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_authorization.go:89           OpenIDConnectAuthorization\ngithub.com/authelia/authelia/v4/internal/middlewares/http_to_authelia_handler_adaptor.go:113 NewHTTPToAutheliaHandlerAdaptor.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54                            (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35                           SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25                           SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16                           SecurityHeaders.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/cors.go:216                             (*CORSPolicy).Middleware.func1\ngithub.com/fasthttp/router@v1.4.14/router.go:414                                             (*Router).Handler\ngithub.com/valyala/fasthttp@v1.43.0/http.go:154                                              (*Response).StatusCode\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2338                                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224                                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196                                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1594                                                                     goexit"
```

### Documentation

https://www.authelia.com/integration/openid-connect/portainer/

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
#2596

#3396

#4394

**Comment by ajb3932** [comment]
Thanks for pointing this out to me. Just to make it clear to anyone who might come accross this in the future. 
I have solved this by adding TOTP (two_factor) to my Portainer auth.
From what I gather adding TOTP forces a time sync which fixed the issue.

**Comment by ajb3932** [comment]
Or at least it did fix it until I logged out and tried to log in again.

**Comment by james-d-elliott** [comment]
As long as you logout of authelia before logging into portainer it will technically work, even though it's not ideal. I'm not entirely sure the condition under which it asks for login. As you may / may not have noticed, we're nearing the end of the core OpenID Connect features, and prompt handling is unlikely to be far off its just one of the more UI heavy features.

**Comment by Redwid** [comment]
The logout and login doesn't work for me.
Is that anything that could be done to fix that issue?
I'm on authelia 4.38.16 and on Portainer 2.21.3

In logs there is 1 sec difference between two time stamps:
{code}
time="2024-10-15T16:46:20+01:00" level=error msg="Authorization Response for Request with id 'db80f510-1065-4d80-b188-3fe9058cb250' on client with id 'portainer' could not be created: The Authorization Server requires End-User authentication. Failed to validate OpenID Connect request because prompt was set to 'login' but auth_time ('2024-10-15 15:46:18 +0000 UTC') happened before the authorization request ('2024-10-15 16:46:19 +0100 IST') was registered, indicating that the user was not re-authenticated which is forbidden." method=GET path=/api/oidc/authorization remote_ip=192.168.1.1
{code}

**Comment by YabaiKai** [comment]
Anyone having issues with OAuth using Cloudflare as your registrar, ensure that you either:

Disable bot protection under [Your Domain] -> Security -> Bots -> Bot Fight Mode (disable)
Do not proxy your Authelia server through Cloudflare.
