### ISSUE TITLE
Allow reset password using email when search: email: true

### ISSUE THREAD

**Issue by Cajuteq** [authelia/authelia#4814]
### Description

When we allow users to use email to connect using the configuration
```
search:
  email: true
```
The email should also be authorized to be used in the password reset area

### Use Case

We have users who only uses email in the connecting step and who never uses the user_id, when they try to reset their password, a lot of then doesn't have a clue of why it doesn't work; and when told to use the user_id instead of email, they don't remember it because they never used it !

### Details

All UX fields asking for the username should be affected by the `email: true` configuration.

### Documentation

The documentation should be updated to reflect the change. 
`Allows users to login using their email address` could become `Allows users to use their email address instead of their username`

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
This is already the way it operates.

**Comment by Cajuteq** [comment]
You're right, they and I (while testing) should have made a typo, I tested again and it works well. Apologize for the inconvenience

**Comment by james-d-elliott** [comment]
No worries at all.
