### ISSUE TITLE
Www-Authenticate not sent with 401

### ISSUE THREAD

**Issue by nealey** [authelia/authelia#4905]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

Caddy

### Reverse Proxy Version

N/A

### Description

401 status codes MUST be accompanied by a `Www-Authorize` header.

This is preventing `gvfsd-dav` from prompting the user for credentials.

### Reproduction

With authelia running on port 9091. `users.yaml` content can be the default generated one, it just needs any valid content.

```sh
curl -H 'X-Forwarded-Proto: https' -I 'http://localhost:9091/api/verify'
```

### Expectations

401 status should be accompanied with a `Www-Authorize` header

### Configuration (Authelia)

```yaml
jwt_secret: test
session:
  domain: localhost
authentication_backend:
  file:
    path: /config/users.yaml
storage:
  encryption_key: testtesttesttesttest
  local:
    path: /config/db.sqlite3
notifier:
  filesystem:
    filename: /config/emails.txt
access_control:
  default_policy: one_factor
  rules:
    - domain: allow
      policy: bypass
```

### Logs (Authelia)

```shell
INFO[0000] Authelia v4.37.5 is starting                 
INFO[0000] Log severity set to info                     
INFO[0000] Storage schema is being checked for updates  
INFO[0000] Storage schema is already up to date         
INFO[0000] Initializing server for non-TLS connections on '[::]:9091' path '/' 
INFO[0001] Access to https://localhost:9091/api/verify (method unknown) is not authorized to user <anonymous>, responding with status code 401  method=HEAD path=/api/verify remote_ip=172.17.0.1
```

### Logs (Proxy / Application)

```shell
n/a
```

### Documentation

* [RFC 9110 15.5.2](https://httpwg.org/specs/rfc9110.html#status.401)

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Please confirm this is the entire config, and either provide more information or reproduce it with valid request (i.e. including the rd parameter). Unless this breaks legitimate use cases or presents a security issue this will absolutely not be changing until v5 as it's a critically breaking change.

**Comment by nealey** [comment]
Hello, thank you. I don't personally need a fix right away, but this issue does cause authelia to be incompatible with the Gnome/Freedesktop code for WebDAV mounts.

I discovered this trying to get Nautilus (the Gnome file manager) to mount a webdav filesystem authenticated by Authelia. Nautilus sends a message to `gvfsd`, which calls its `gvfsd-dav` helper to mount the remote filesystem.  Because `gvfsd-dav` needs the `Www-Authorize` header to present a prompt to the user, it fails, presenting the user with a dialog indicating the server responded with "Unauthorized". Here's what that looks like:

```
homelab_authelia.1.sdadkrkkxyan@sweetums    | time="2023-02-09T00:20:23Z" level=trace msg="Request hit" method=GET path=/api/verify remote_ip=192.12.184.6
homelab_authelia.1.sdadkrkkxyan@sweetums    | time="2023-02-09T00:20:23Z" level=trace msg="Headers=GET /api/verify?rd=https://auth.woozle.org/ HTTP/1.1\r\nUser-Agent: gvfs/1.50.3\r\nHost: drive.woozle.org\r\nAccept-Encoding: gzip, deflate, br\r\nAccept-Language: en-us, en;q=0.9\r\nX-Forwarded-For: 192.12.184.6\r\nX-Forwarded-Host: drive.woozle.org\r\nX-Forwarded-Method: OPTIONS\r\nX-Forwarded-Proto: https\r\nX-Forwarded-Uri: /\r\n\r\n" method=GET path=/api/verify remote_ip=192.12.184.6
homelab_authelia.1.sdadkrkkxyan@sweetums    | time="2023-02-09T00:20:23Z" level=trace msg="Using X-Fowarded-Proto, X-Forwarded-Host and X-Forwarded-URI headers to construct targeted site URL" method=GET path=/api/verify remote_ip=192.12.184.6
homelab_authelia.1.sdadkrkkxyan@sweetums    | time="2023-02-09T00:20:23Z" level=trace msg="Checking if we need check the authentication backend for an updated profile for ." method=GET path=/api/verify remote_ip=192.12.184.6
homelab_authelia.1.sdadkrkkxyan@sweetums    | time="2023-02-09T00:20:23Z" level=debug msg="Check authorization of subject username= groups= ip=192.12.184.6 and object https://drive.woozle.org/ (method OPTIONS)."
homelab_authelia.1.sdadkrkkxyan@sweetums    | time="2023-02-09T00:20:23Z" level=trace msg="ACL MISS Position 1 for subject username= groups= ip=192.12.184.6 and object https://drive.woozle.org/ (method OPTIONS)"
homelab_authelia.1.sdadkrkkxyan@sweetums    | time="2023-02-09T00:20:23Z" level=trace msg="ACL MISS Position 2 for subject username= groups= ip=192.12.184.6 and object https://drive.woozle.org/ (method OPTIONS)"
homelab_authelia.1.sdadkrkkxyan@sweetums    | time="2023-02-09T00:20:23Z" level=trace msg="ACL MISS Position 3 for subject username= groups= ip=192.12.184.6 and object https://drive.woozle.org/ (method OPTIONS)"
homelab_authelia.1.sdadkrkkxyan@sweetums    | time="2023-02-09T00:20:23Z" level=trace msg="ACL MISS Position 4 for subject username= groups= ip=192.12.184.6 and object https://drive.woozle.org/ (method OPTIONS)"
homelab_authelia.1.sdadkrkkxyan@sweetums    | time="2023-02-09T00:20:23Z" level=trace msg="ACL MISS Position 5 for subject username= groups= ip=192.12.184.6 and object https://drive.woozle.org/ (method OPTIONS)"
homelab_authelia.1.sdadkrkkxyan@sweetums    | time="2023-02-09T00:20:23Z" level=trace msg="ACL HIT Position 6 for subject username= groups= ip=192.12.184.6 and object https://drive.woozle.org/ (method OPTIONS)"
homelab_authelia.1.sdadkrkkxyan@sweetums    | time="2023-02-09T00:20:23Z" level=info msg="Access to https://drive.woozle.org/ (method OPTIONS) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://auth.woozle.org/?rd=https%3A%2F%2Fdrive.woozle.org%2F&rm=OPTIONS" method=GET path=/api/verify remote_ip=192.12.184.6
homelab_authelia.1.sdadkrkkxyan@sweetums    | time="2023-02-09T00:20:23Z" level=trace msg="Replied (status=401)" method=GET path=/api/verify remote_ip=192.12.184.6
```

And what that looks like to the client:

```
% curl --http1.1 -I -H 'Accept:' https://drive.woozle.org/
HTTP/1.0 200 Connection established
Proxy-agent: tinyproxy/1.11.1

HTTP/1.1 401 Unauthorized
Alt-Svc: h3=":443"; ma=2592000
Content-Length: 104
Content-Type: text/html; charset=utf-8
Date: Thu, 09 Feb 2023 03:47:07 GMT
Location: https://auth.woozle.org/?rd=https%3A%2F%2Fdrive.woozle.org%2F&rm=HEAD
Permissions-Policy: interest-cohort=()
Referrer-Policy: strict-origin-when-cross-origin
Server: Caddy
Set-Cookie: authelia_session=ySea!TbOJQDIRb8tDrXyAn*-j8vsF4j1; expires=Thu, 09 Feb 2023 04:47:07 GMT; domain=woozle.org; path=/; HttpOnly; secure; SameSite=Strict
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

```

My entire swarm setup is available at https://git.woozle.org/neale/stacks/src/branch/main/homelab

---

The configuration file I provided was an attempt to pare down the complexity of the setup in order to more easily reproduce the problem. Here is a `curl` command with an `rd=` parameter which also triggers the issue, with that same config file. It is important to prevent `curl` from sending an `Accept` header, since authelia returns a 302 code when this header is present.

```
% curl -H 'Accept:' -H 'X-Forwarded-Proto: https' -H 'X-Forwarded-Method: OPTIONS' -I 'http://localhost:9091/a
pi/verify?rd=https%3A%2F%2Flocalhost%2F&rm=OPTIONS'
HTTP/1.1 401 Unauthorized
Date: Thu, 09 Feb 2023 03:51:14 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 170
X-Content-Type-Options: nosniff
Referrer-Policy: strict-origin-when-cross-origin
Permissions-Policy: interest-cohort=()
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
Location: https://localhost/?rd=https%3A%2F%2Flocalhost%3A9091%2Fapi%2Fverify%3Frd%3Dhttps%253A%252F%252Flocalhost%252F%26rm%3DOPTIONS&rm=OPTIONS
Set-Cookie: authelia_session=zI1LCKICPTdsKOBkgayGQmEmDbmcCmgT; expires=Thu, 09 Feb 2023 04:51:15 GMT; domain=localhost; path=/; HttpOnly; secure; SameSite=Lax

```

**Comment by nealey** [comment]
If it helps to see this with all the different layers in play, this command on a Linux box with a user logged in to a Gnome 3 session will illustrate that `gvfsd` does not prompt for a password when it gets a 401 status code but no `Www-Authenticate` header. This runs against my setup (caddy + authelia)

```sh
GVFS_HTTP_DEBUG=all /usr/lib/gvfsd-dav ssl=true user=neale host=drive.woozle.org 
```

**Comment by james-d-elliott** [comment]
You should be able to fix this with the `http://localhost:9091/api/verify?auth=basic` URL instead based on what you described.

**Comment by james-d-elliott** [comment]
If you could try the `v4.38.0-beta1` or one of the builds linked in the blog post the additional config should look like this:

```yaml
server:
  endpoints:
    authz:
      forward-auth:
        implementation: ForwardAuth
        authn_strategies: []
      forward-auth/scheme-basic:
        implementation: ForwardAuth
        authn_strategies:
        - HeaderAuthorization
```

Then use the URL `http://localhost:9091/api/authz/forward-auth/scheme-basic`.

**Comment by nealey** [comment]
Okay, I believe this is going to work. I haven't had a lot of time yet to test, mostly because of the complicated Caddyfile required. While the Caddyfile is not an Authelia problem, per se, I think it would be helpful to list what will be required, for anyone else who is trying to get WebDAV working.

Caddy must do the following:

* If an `Authorization` header is present in the request, rewrite that to `Proxy-Authorization`
* If no `Authorization` header is in the request, do not send a `Proxy-Authorization` header
* If the client is a WebDAV client (not sure how to determine this yet), use the `forward-auth-scheme-basic` (`/` does not seem to be allowed in the key name) endpoint
* Otherwise, use the `forward-auth` endpoint

I hope sometime soon I will have time to work out how to write a Caddyfile to do all this, but it may be a while.

**Comment by james-d-elliott** [comment]
Nothing should have to change with the example I posted right above your comment. It sends 401's with WWW-Authenticate headers.

**Comment by nealey** [comment]
Since the initial issue was about sending the WWW-Authenticate header, and this upcoming release supports doing exactly that, I think this issue can be closed.

Finagling configuration for a specific WebDAV client with Caddy is probably better suited for the discussions board.

Thank you!
