### ISSUE TITLE
Reset password notification contains wrong text

### ISSUE THREAD

**Issue by electrofloat** [authelia/authelia#4915]
### Version

v4.37.5

### Deployment Method

Bare-metal

### Reverse Proxy

NGINX

### Description

When using filesystem notifier
And the user clicks on 'reset password' on the login page
And the user enters their username and clicks on reset
Then the notification.txt created and contains wrong text:
```
Body: This email has been sent to you in order to validate your identity.

If you did not initiate the process your credentials might have been compromised and you should reset your password and contact an administrator.

To setup your 2FA please visit the following URL: 
```

This text is for when the user wants to setup 2FA and not for password reset.

### Reproduction

See description above

### Expectations

In the notification.txt the body of the email should explain that the user (someone) requested password reset, and follow the link to do so.

According to: https://www.authelia.com/reference/guides/notification-templates/#envelope-template
{{ .LinkURL }} and {{ .LinkText }} are only valid in IdentityVerification template, so one cannot create a custom template for password reset only to override the body (or the documentation is wrong)

### Logs (Authelia)

```shell
DEBU[0405] Sending an email to user authelia ({Test User authelia@authelia.com}) to inform that the password has changed. method=POST path=/api/reset-password remote_ip=
```

### Documentation

https://www.authelia.com/reference/guides/notification-templates/#envelope-template

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
The email you're being sent is the identity verification email. But yep the plaintext version is not quite accurate, while the HTML version is fine.
