### ISSUE TITLE
Embed web application in Authelia binary

### ISSUE THREAD

**Issue by clems4ever** [authelia/authelia#494]
This could be done according to: https://www.thepolyglotdeveloper.com/2017/03/bundle-html-css-javascript-served-golang-application/

**Comment by kusold** [comment]
You may want to follow this discussion: https://github.com/golang/go/issues/35950

**Comment by clems4ever** [comment]
Thank you for the link @kusold !

**Comment by J7mbo** [comment]
@clems4ever We can bundle code in the binary in Go. Having done this myself, I used [statik](https://github.com/rakyll/statik). I mean all it's really doing is converting to binary data, saving to a go file, and that go file is then compiled into the binary, which then you access and deserialize via the library functions.

**Comment by nightah** [comment]
I could be wrong but when I initially investigated thing a while ago, none of the other libraries work with fasthttp. It works with the base net/http library.

I was actually waiting for the de-facto go standard in that link @kusold provided too before we considered implementing.
