### ISSUE TITLE
Authelia itself listen on a unix socket

### ISSUE THREAD

**Issue by feinedsquirrel** [authelia/authelia#4987]
### Description

It is already possible to configure communication with e.g. Redis and PostgreSQL over a unix socket.

I've been wondering if Authelia supports listening on a unix socket itself. So far, my research has turned up a negative, specifically `internal/server/server.go`.

It would be awesome if I could proxy-pass to a local unix socket.

### Use Case

Unix sockets are considered to be faster than the http interface for on-machine communication (e.g. with the reverse proxy). They also allow an admin to easily assign file ownership and permissions to who can connect to the authelia socket.

### Details

I came across [this commit](https://github.com/grafana/grafana/pull/8221/files#diff-059f97ccda689ebea0e2f9981cd736d77b1fa01a719d95abae333ad40fb0b9c4R69) where unix socket listening was added to grafana. With my limited understanding of golang, it seems like it shouldn't be too difficult to add listening on a unix socket; it seems the primary code for this would be added to the if statement in `internal/server/server.go`.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
We currently do not support it. However I'd not put a lot of merit in the idea of it  being considered faster, in practice the TCP overhead on modern hardware is very very low when dealing purely with HTTP. However we're willing to see if this is beneficial either way.

Please checkout this build: https://buildkite.com/authelia/authelia/builds/18921

Configuration looks like:

```yaml
server:
  ## The following MUST be commented.
  # host: 0.0.0.0
  # port: 9091
  
  ## TCP Socket equivalent.
  # address: tcp://0.0.0.0:9091
  
  ## Unix Socket.
  address: unix:///path/to/authelia.sock
```

To merge this we'd probably need a list of proxies in our supported list which support a unix socket app in this way, as well as some metrics (both with TLS only on the proxy and via the proxy) which indicate there is an easily measurable benefit in supporting this.

**Comment by james-d-elliott** [comment]
@feinedsquirrel any chance to look into this more?

**Comment by feinedsquirrel** [comment]
I'll have to test this evening when I get back home. Any potential speed bonus was always just that, a bonus to me. Being able to control ownership of the unix socket file seems more important, personally. I'll let you know as soon as I can test it. Thanks!

**Comment by feinedsquirrel** [comment]
Ok, I think I'm really close. I'm going to play a little more with file permissions tomorrow before I make a final report. One of the changes I'm considering may require an additional line in #4982 so I am holding off on making a new commit there until after I get this one buttoned down.
One thing I've realized is that some other services I use that I proxy_pass from nginx to a unix socket have file mode 666 on their socket. I think there is a way to tighten that some. Otherwise, there may not be much of a reason to implement this. I'll have more info tomorrow.

**Comment by james-d-elliott** [comment]
This is what the umask service directive in the unit is for.
