### ISSUE TITLE
"CREATE INDEX IF NOT EXISTS" not supported by MySQL?

### ISSUE THREAD

**Issue by n4kre** [authelia/authelia#512]
Hi @clems4ever,

Great you released Authelia v4! :)

However, I faced a some troubles – will open different issues.

When trying to migrate from a v3 Mongo DB to v4 MySQL DB, it looked like the following syntax is not valid in MySQL: ```CREATE INDEX IF NOT EXISTS```.

**Comment by clems4ever** [comment]
Hello @n4kre , long time no see!
This is issue is strange since MySQL table creation is covered in tests and I never seen that one. What version of MySQL do you use?

**Comment by n4kre** [comment]
I switched to PostgreSQL :)
But that was the standard MySQL 5.7, not MariaDB: MySQL does not seem to suppot this functionality (https://dev.mysql.com/doc/refman/5.7/en/create-index.html), while MariaDB does (https://mariadb.com/kb/en/library/create-index/).
Maybe this is helpful for supporting MySQL as well: https://stackoverflow.max-everyday.com/2017/07/mysql-create-index-if-not-exists/

**Comment by clems4ever** [comment]
Alright, I indeed test Mariadb and not MySQL. I will add a suite for MySQL as well and fix the issue. Sorry for that.

**Comment by james-d-elliott** [comment]
`SELECT COUNT(1) Exists FROM INFORMATION_SCHEMA.STATISTICS WHERE table_schema=DATABASE() AND table_name='table' AND index_name='name';`

Should work for mysql and mariadb, but pretty sure it will not for PostgreSQL and may not for sqlite.
