### ISSUE TITLE
OpenID access control

### ISSUE THREAD

**Issue by cyl3x** [authelia/authelia#5140]
### Description

I have tried my best to restrict access to some of my oidc clients without success. I'm not even sure if this should be possible (yet) as there seems to be no information/warning in the documentation :smile: 

### Use Case

It would be nice to be able to restrict access to OIDC clients as well, as most OIDC clients are unable to restrict user access themselves

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
This is a very vague issue and there are already very similar issues which I'll close this in favor of:
- #2621
- #3987

It should also be noted that this is also a somewhat unclean feature to implement as there is no way to detect several elements about the request from OIDC. We are only able to accurately determine the domain, user identity, and their remote IP (and only DURING the authorization). If any of these criteria change then we're not updated about these situations, and we can't do much even if we did excluding widely unsupported areas of the spec (front/back-channel logout, session management, etc).
