### ISSUE TITLE
Support multiple Authelia instances with single storage backend

### ISSUE THREAD

**Issue by mback2k** [authelia/authelia#5184]
### Description

I am currently running one Authelia instance next to each ReverseProxy (NGINX) instance in our environment.

Let's assume their instance name and DNS alias looks like this:
- revproxy1.example.com
- revproxy2.example.com
- revproxy3.example.com
- ...

If a user now registers a WebAuthn security key on `revproxy1.example.com`, he/she cannot re-use it on any of the other instances, because the rpid is set to `revproxy1.example.com`. Authelia will prompt the user to use his/her registered security key as 2nd factor, but will then fail to validate it:
![image](https://user-images.githubusercontent.com/231943/230359013-3f75269c-7585-41a7-8cf0-b5d2378b4f32.png)

I think an easy solution could potentially be to filter the registered WebAuthn devices during prompting by matching the Host header to the RPID column in the database and therefore allow the user to re-register the device for each Authelia instance. On the other hand I am using a shared storage to avoid users having to register their TOTP device multiple times.

### Use Case

Running multiple independent Authelia instances each paired with one NGINX reverse proxy and still supporting WebAuthn.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
This will not likely be implemented as described unfortunately, this is a very exotic use case and there are already a lot of complex scenarios to handle when it comes to RPID's. 

If users wish to have the instances load-balanced with multiple proxies and authelia instances as long as the Authelia URL is the same then this will operate as normal, this is a relatively standard high-availability use case.

This may potentially be possible via #4633 however it will unlikely be a supported or tested use-case unless a compelling reason can be given or becomes apparent.

**Comment by mback2k** [comment]
Okay, thanks, but #4633 actually looks promising to potentially solve this as you wrote via "registration of the same key multiple times, once for each RPID". Any ETA on that one?

**Comment by james-d-elliott** [comment]
It's coming with 4.38, plan is to hopefully finalize all the dependent parts this weekend and the following week as I will finally have spare time.

**Comment by james-d-elliott** [comment]
Can be merged with #275 indirectly, subscribe for a close notification, if interested.
