### ISSUE TITLE
Password hash generated by hash-password script is not accepted by the backend

### ISSUE THREAD

**Issue by Stolz** [authelia/authelia#521]
I had the old (Node) version working fine with Docker, first_factor auth and file backend. I'm now trying to upgrade my set up to V4 (Go) but I get this error when I try to log in

    level=error msg="Error while checking password for user test: Authelia only supports salted SHA512 hashing" method=POST path=/api/firstfactor remote_ip=x.x.x.x stack="/go/src/app/internal/middlewares/authelia_context.go:58          (*AutheliaCtx).Error\n/go/src/app/internal/handlers/handler_firstfactor.go:42          FirstFactorPost\n/go/src/app/internal/middlewares/authelia_context.go:43          AutheliaMiddleware.func1.1\n/go/pkg/mod/github.com/fasthttp/router@v0.5.2/router.go:326      (*Router).Handler\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/header.go:123     (*ResponseHeader).StatusCode\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/server.go:2018    (*Server).serveConn\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:223 (*workerPool).workerFunc\n/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/workerpool.go:195 (*workerPool).getCh.func1\n/usr/local/go/src/runtime/asm_amd64.s:1357                       goexit"

I've generated the password hash using the go-based hash-password script

    git clone git@github.com:authelia/authelia.git --depth=1
    cd authelia
    source bootstrap.sh
    authelia-scripts hash-password test --log-level debug

For what I can tell, the only difference with my old hash (generate with the Node script) and the new one is that the old one started with `{CRYPT}$6$rounds=500000$...` whereas the new one starts with `$6$rounds=500000$...`. I've tried prefixing the new one with `{CRYPT}` as well with identical results. I've also tried using my old hash, just in case, but it still triggers the same error.

Here is my configuration

    host: 0.0.0.0
    port: 9091
    logs_level: debug
    jwt_secret: redacted
    default_redirection_url: https://home.example.com
    
    totp:
      issuer: example.com
    
    authentication_backend:
      file:
        path: /etc/authelia/users.yml
    
    access_control:
      default_policy: one_factor
    
    session:
      domain: example.com
      secret: redacted
      expiration: 3600000 # 1 hour
      inactivity: 300000 # 5 minutes
    
    regulation:
      max_retries: 4
      find_time: 120
      ban_time: 900
    
    storage:
      local:
        path: /var/lib/authelia/db.sqlite3
    
    notifier:
      smtp:
        host: smtp.gmail.com
        port: 587
        username: redacted
        password: redacted
        sender: no-reply@example.com
  
And here is my /etc/authelia/users.yml file

    users:
      test:
        password: "$6$rounds=500000$...redacted...yAI26"
        email: test@example.com
        groups:
          - admins
          - dev

I'm using the latest version from Docker:

    docker exec -it  authelia ./authelia version
    build git tag: v4.0.0
    build git commit: e0d4ed2a076e9326344d55c45cf64c09724fdb17
    build time: 2019-12-10 10:19:41

**Comment by nightah** [comment]
The integration tests have the user database prefixed with `{CRYPT}` like such:

https://github.com/authelia/authelia/blob/511b0b3c62a1c6bec13ee063f1c9cfbeb352f8fe/internal/suites/Standalone/users.yml#L3

The only other difference I can see is you're using double quotes instead of single.
I believe @clems4ever said that the {CRYPT} prefixed shouldn't be required in the golang version but I'm not certain if any changes needed to be made for that.

**Comment by Stolz** [comment]
Thanks for info @nightah . I've tried with single quotes with and without `{CRYPT}` prefix, but I still get the same error

**Comment by clems4ever** [comment]
@nightah is right about the prefix {CRYPT} being optional. I will try to display more info in the logs to see where could the error be. I'll let you know once it reaches master.

**Comment by clems4ever** [comment]
Well, my mistake it {CRYPT} is not optional but I will make it so. https://github.com/authelia/authelia/blob/2fb20882d927291ad59d6f67492c69294a87798c/internal/authentication/file_user_provider.go#L71

**Comment by clems4ever** [comment]
This should help find out what's going on: https://github.com/authelia/authelia/pull/522
It also makes {CRYPT} optional.

**Comment by clems4ever** [comment]
@Stolz , PR is merged. Please retry and let us know what you see in the logs.

**Comment by Stolz** [comment]
Thanks for the quick response. I've updated my version to

    docker exec -it authelia ./authelia version
    build git tag: unknown
    build git commit: 6e946dc85909961b888edcda7903551452bc9957
    build time: 2019-12-28 09:03:28

And now I don't see any error message ...

    time="2019-12-29T02:54:56+08:00" level=debug msg="Credentials validation of user test is ok" method=POST path=/api/firstfactor remote_ip=x.x.x.x
    time="2019-12-29T02:54:56+08:00" level=debug msg="Mark authentication attempt made by user test" method=POST path=/api/firstfactor remote_ip=x.x.x.x

... but after login nothing happens. I stay in the login page with no pop-up message whatsoever and no cookie is created. I can see in the browser console that `POST /api/firstfactor` API endpoint returns a 200 response and the `GET api/state` endpoint also returns a 200 response with this info

    {"status":"OK","data": "username":"","authentication_level":0,"default_redirection_url":"https://home.example.com"}}

I use Authelia together with Traefik and with the old version after successful login a cookie was created and I was redirected to wherever I pass in the `rd=` URL parameter. New version does not have same behavior. Traefik gets a 500 error and when I manually visit the Authelia page if I input wrong credentials I get a pop-up message but if I enter proper credentials nothing happens.

Since I don't have any error message regarding the token I don't know if this issue can be considered solved or not. Feel free to close it if you think the behavior I'm getting is not related to the token.

**Comment by nightah** [comment]
@Stolz could you please share your Traefik config for the authelia portal and the protected endpoint?

**Comment by nightah** [comment]
@Stolz do you still need assistance with this? If so could you please share your Traefik configuration per the above comment?

**Comment by clems4ever** [comment]
@Stolz , please reopen this issue if you're still facing the issue.
