### ISSUE TITLE
Add an option to force STARTTLS in SMTP notifier

### ISSUE THREAD

**Issue by clems4ever** [authelia/authelia#524]
In order to avoid downgrade attacks, we want to add a flag in Authelia configuration to force connection upgrade and send an error message in the logs if the server does not advertise STARTTLS.

**Comment by james-d-elliott** [comment]
Would it be preferable to have an option to allow insecure connections, or an option to force them?

Example. If we have an option called disableForcedStartTLS this would mean the default is forced, and the exception would be forced. Or do we want an option called forcedStartTLS where users would have to opt for it to be on? 

I like the first more, as it's more secure. People generally don't add configuration changes unless they have to. This would mean in cases where it breaks for people they would have to.

**Comment by clems4ever** [comment]
I agree with your proposal, first option is better from a security standpoint. Let's go with that.

**Comment by james-d-elliott** [comment]
I gave this a whole lot more thought and I made a mistake with #514. The change to make secure a bool was a mistake, this means by default the SMTP server does not need a valid certificate, it's only when they set the value of the variable. It would likely be better to leave it as a string for now, make blank/nil equal to True etc. This is mainly due to the key name.

I also think replacing it with disableCertificateValidation (either by a hard change or deprecating the older secure key) would be a good idea.

**Comment by clems4ever** [comment]
@james-d-elliott , do the replacement, #414 has been merged only one day ago so it's fine and it's not even released. You can do the change without deprecation notice for this case.

**Comment by james-d-elliott** [comment]
Another thing I've found in my research is this: https://golang.org/src/net/smtp/auth.go?s=2004:2066#L62

PlainAuth doesn't support sending over plain text except when the severs mailname is localhost, 127.0.0.1, or ::1. This means for us to implement optional TLS we'd have to implement a version of PlainAuth that allows it. Do we want to:

1. Implement our own Plain Auth
2. Make Login Auth function the same as Plain Auth when it comes to TLS (removing the ability to choose at config level)
3. Make Login Auth function differently.

I don't like option 3, but I'm not worried if that's the direction you want to go. We could also theoretically have the disableRequireTLS block the ability to send an email (which would have purpose if the user is NOT authenticating) in option 2 or 3.

**Comment by clems4ever** [comment]
I think it's a good restriction from a security point of view and I'd rather not implement what should not be in the first place (even for testing purpose).

So, given what you found we should already be safe regarding downgrade attacks however I think you can still add a unit test to cover the case of an error is actually thrown if the connection is not TLS so that we ensure non-regression for the future. That way whatever the maintainers of the library decide in the future, we'll always be safe (or at least alarmed) in Authelia.

For testing purpose we could advertise non authenticated connections or authenticated connections over TLS with self-signed certificates and that's it. What do you think?

**Comment by clems4ever** [comment]
In the case of unauthenticated connections though, we should have a way to enforce the use of TLS. I think there should be an option for that. Something like `enforce_tls` could be fine (defaulting to true obviously) and with a comment saying that this option only applies to non authenticated connections only since LOGIN and PLAIN are not available over unsecure connections.
