### ISSUE TITLE
Table authelia.authentication_logs doesn't exist in engine

### ISSUE THREAD

**Issue by DJBenson** [authelia/authelia#5333]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX Proxy Manager

### Description

I am getting corruption of my MariaDB database which I have fixed once by simply dropping the authentication_logs table and recreating it from the schema but it has once again been corrupted - it seems to be when the container or container host is restarted.

### Reproduction

Unsure

### Logs (Authelia)

```shell
msg="Unable to mark 1FA authentication attempt by user 'first.last': error inserting authentication attempt for user 'first.last': Error 1932 (42S02): Table 'authelia.authentication_logs' doesn't exist in engine"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
You've not really provided the required information or enough context to understand your issue. When which container is restarted?

**Comment by DJBenson** [comment]
The Authelia and MariaDB containers share the same host so it's one and the same. 

I don't know exactly when it's happening as the only indication it's happened is I can no longer log in to any of my protected services (as per the error above) - it seems to coincide with me restarting the VM which hosts Docker which in turn hosts the services mentioned above.

The corruption is exactly as I said, the authentication_logs table is corrupted somehow and throws the above error - I do not get such errors on any other databases and it is always this one table which is corrupted.

**Comment by james-d-elliott** [comment]
You said restarting "the container" seems to cause it, that's what I was asking about. As far as I can see though from further elaboration I'm not sure I see this being an Authelia bug at all, if the MySQL database becomes corrupt during a restart that's an issue with your restart process or the SQL container itself.

**Comment by james-d-elliott** [comment]
If you do not supply the full debug or trace logs this issue will be closed.

**Comment by DJBenson** [comment]
You're suggesting MySQL corrupts one table which is only used by Authelia. Ok.

**Comment by james-d-elliott** [comment]
The only information provided about the table and the corruption is that the table does not exist. I'm suggesting there is no reasonable explanation that would conclude that Authelia is dropping this table. The only time the table is dropped is a completely manual process. 

With effectively zero logs we have absolutely nothing to go on. You completely disregarded the issue template and did not supply the full logs. The error quite clearly shows that the table does not exist, it's not corrupt. It's either dropped by another party, deleted from the underlying filesystem, or something else is going on. 

Then you're suggesting correlation is causation which is a very bad argument for it being an Authelia issue. It'd be the same as me saying "well everyone else is using Authelia and no one else with MySQL had this issue".

**Comment by DJBenson** [comment]
It doesn't say the table doesn't exist. It says the table doesn't exist in the engine.

The table is visible on disk and via phpmyadmin but is locked due to whatever happened. Nobody and nothing has dropped the table.

I've given as much information as is presented in the logs. If that's not enough then I don't really know what else to say. I followed the template and provided what I knew about the issue.

Responses like you've provided really put people off projects like this.

No need to respond. I've fixed the issue again and if it keeps happening I'll just move away from the project, I suspect it's no skin off either of our noses.

**Comment by james-d-elliott** [comment]
The template very clearly asks users to provide the complete debug logs. There will be more log lines if this was provided.

If the table still exists but is not mounted by the database engine and there are no logs as to why it's not mounting the table, then it seems even more unlikely to be an Authelia issue. 

> Responses like you've provided really put people off projects like this.
> 
> No need to respond. I've fixed the issue again and if it keeps happening I'll just move away from the project, I suspect it's no skin off either of our noses.

I actually don't agree with this. I'd rather people have their issues solved. But it's not unreasonable to expect users to act professionally and respectfully. You have not done either of these things from the very moment you created this issue. 

If you refuse to provide information in the template and then refuse to do it when asked, I think it's an indication that maybe there's an issue with your approach or attitude rather than  with everyone else.

**Comment by james-d-elliott** [comment]
> If the table still exists but is not mounted by the database engine and there are no logs on the MariaDB end as to why it's not mounting the table, then it seems even more unlikely to be an Authelia issue. We have no control over which tables the engine mounts.

Also in addition to this, Authelia does nothing during a restart related to SQL other than close the connection. If the issue does not occur without a restart then:

1. The database is operating as per normal without the restart.
2. Closing a connection in the event of a clean shutdown shouldn't cause any issues.
3. The data itself if properly saved to disk by the engine should not be corrupt if the engine is operating normally and the shutdown was clean.
