### ISSUE TITLE
Kasm-Workspaces OpenID docs not on website

### ISSUE THREAD

**Issue by HaroldVB** [authelia/authelia#5336]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX Proxy Manager

### Reverse Proxy Version

1

### Description

Hi, I've recently written OpenID documentation for Kasm Workspaces. But it doesn't seem to be showing up on authelia.com in OpenID integrations. How can we resolve this issue, did I make a mistake?

### Reproduction

Visit the following link, Kasm Workspaces does not show up in the list of OpenID integrations.

[https://www.authelia.com/integration/openid-connect/introduction/](url)

### Expectations

I would expect the documentation to be available on the Authelia website. I took the Apache Guac documentation as an example.

### Logs (Authelia)

```shell
I have no logs
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] This is a bug report and not a support request
- [X] I have read the security policy and this bug report is not a security issue or security related issue
- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration
- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide
- [X] I have checked for related proxy or application logs and included them if available
- [x] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
The issue tracker is for bugs with authelia.
