### ISSUE TITLE
Add support for squid proxy

### ISSUE THREAD

**Issue by munntjlx** [authelia/authelia#551]
Just curious if it there are any plans to support squid?

**Comment by nightah** [comment]
At a quick glance I can't see a similar module to nginx's [http_auth_request_module](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html) for squid.

If there was something similar I'd be more than happy to put together a Suite and look to support this. If no such module/helper exists, one would need to be written in perl to support that required function, contributions are definitely appreciated here!

Alternatively you could wait for https://github.com/authelia/authelia/issues/467 but that doesn't necessarily give you exactly what you're asking.

**Comment by clems4ever** [comment]
@munntjlx , would you be able to provide the helper forwarding authentication to Authelia so that we can integrate it in a suite and make support of squid official?

**Comment by james-d-elliott** [comment]
We'd reconsider this if something was written to perform this on squid.
