### ISSUE TITLE
"Remember Me" check box unintuitive behaviour

### ISSUE THREAD

**Issue by Iyeyasu** [authelia/authelia#552]
### Description

When the "Remember Me" check box is checked, Authelia creates a "Session" type cookie, which is deleted when the browser is closed. This is pretty much the opposite what you'd expect from the check box.

### Tested On

Authelia 4.0
Authelia master
Firefox 72.0.1
Chromium 79.0.3945.117

### Steps to reproduce:

1. Go to your Authelia login screen
2. Check the "Remember Me" checkbox
3. Login
4. Open Developer Tools -> Storage
5. Confirm that the authelia_session cookie's "Expires" field is set to "Session"
6. Restart the browser
7. Confirm that Authelia is no longer logged in

(Optional)

8. Uncheck the "Remember Me" checkbox
8. Login
9. Confirm that the authelia_session cookie's "Expires" field is correctly set to future date

**Comment by clems4ever** [comment]
That's certainly a bug. I will try to reproduce and let you know.
Thanks.

**Comment by james-d-elliott** [comment]
I've confirmed the fact it's set to expire on session. When remember me is checked shouldn't it remember the session for the duration set in the configuration? Or should it remember it forever?

If it's the duration in the config the issue is we're setting the duration to 0, which I would have thought was forever, but it may be setting it for the session length.

**Comment by nightah** [comment]
It should be for what's specified in the configuration which I believe the default is set to 1 year.

**Comment by nightah** [comment]
@james-d-elliott on second thought and while double checking the code briefly, the Remember Me value was hard coded to be 1 year session expiration based on when the cookie was issued. I do not believe it was ever tied back in to the configuration.

It might actually make more sense to make that value configurable and settable from the config as part of the fix.

@clems4ever iirc the initial implementation assumed that 1 year is a long enough period to almost be considered "forever" right?

**Comment by james-d-elliott** [comment]
Yeah, it seems the duration of 0 is not actually unlimited in fasthttp, it is equal to the end of the session. Not sure if it's a bug there, or if this is intended. My fix branch reverses the behavior in Authelia which is more in line with what I'd expect.

If we were to fix this via configuration it would be worth it to carefully consider how to do this correctly. 

Something like this:
`session:
   name: authelia_session
   secret: big_secret
   expiration: 3600
   inactivity: 300
   remember_me_expiration: 31556952`

Or this if you want non remembered sessions to expire on browser close:
`session:
   name: authelia_session
   secret: big_secret
   expiration: 0
   inactivity: 300
   remember_me_expiration: 31556952`

**Comment by james-d-elliott** [comment]
Yeah I've got a second local branch too that I'm experimenting with the change being only to the duration (set to 31556952 * time.Second - aka 1 year). Replacing this value with a configuration option that defaults to 1 year is probably the most desirable. If people want to set expiration to 0 for non remembered sessions that can realistically be a choice, but could produce strange results.

**Comment by nightah** [comment]
Yeah I think the scenario for expiring non-remembered sessions on browser close can lend itself to a lot of confusion.

The Authelia configuration has a sane defaults for both for the expiration and and inactivity timers, it's much more likely if someone closes their browser that one of those will trigger and invalidate the session anyway, instead of having yet another configuration option for a small edge case.

**Comment by james-d-elliott** [comment]
This is probably the correct fix, unless we want to set a configuration option. 

https://github.com/james-d-elliott/authelia/commit/27064e3254c9681a0a8db31e517998277166a9c1

docker.io/jamesdelliott/authelia:fix-remember-me-cookie-behaviour

**Comment by nightah** [comment]
That will return it to the pre-4.x behaviour.

I haven’t checked but is there an “indefinite” value for the session? If so we should probably set it to that and then no configuration parameter is required.

If there’s appetite to allow configuration of the Remember Me period we could revisit this in another PR.

**Comment by james-d-elliott** [comment]
This seems to suggest the cookie spec has no room for that: https://stackoverflow.com/questions/3290424/set-a-cookie-to-never-expire 

This also suggests the same: https://docs.microsoft.com/en-us/previous-versions/ms178194(v=vs.140)?redirectedfrom=MSDN

> For a cookie to effectively never expire, you can set the expiration date to be 50 years from now.

**Comment by nightah** [comment]
Happy for you to submit the PR with 1 year as the default. 

Once I’m in front of a PC later this afternoon I can test and merge.
