### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by trmz** [authelia/authelia#5546]
### Version

v4.37.5

### Deployment Method

Bare-metal

### Reverse Proxy

HAProxy

### Reverse Proxy Version

2.6.13-1~bpo10+1

### Description

Just had a crash with "panic: runtime error: makeslice: len out of range". 
Authelia version v4.37.5 on Debian 10, behind HAProxy v2.6.13-1~bpo10+1.
HAProxy logs just show the expected SC-- due to Authelia dying. 
Also in the mix, but likely unrelated : Redis server v=7.0.11 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=3af367a78d5e21e9

Note that I'm refreshing users_database.yml every minute via cron. 
If I had to guess, watch: true probably isn't gracefully handling the file being changed mid-read. 
Logs from process start aren't available. 

Hadn't seen this error at all with watch: false, so it's off again now. 
Will look at an alternate method of reloading Authelia 'til this bug can be fixed. 

### Reproduction

Can't reproduce on-demand, but try setting watch: true and rewriting users_database.yml semi-frequently. 

### Logs (Authelia)

```shell
INFO[3475] Reloaded file successfully                    file=/etc/authelia/users_database.yml
INFO[3535] Reloaded file successfully                    file=/etc/authelia/users_database.yml
panic: runtime error: makeslice: len out of range

goroutine 15 [running]:
github.com/go-crypt/x/bcrypt.DecodeSecret(...)
        github.com/go-crypt/x@v0.1.10/bcrypt/bcrypt.go:166
github.com/go-crypt/crypt/algorithm/bcrypt.decode(0x1, {0xc0014ddb60, 0x2, 0xc00032d301?})
        github.com/go-crypt/crypt@v0.2.3/algorithm/bcrypt/decoder.go:129 +0x1c5
github.com/go-crypt/crypt/algorithm/bcrypt.DecodeVariant.func1({0xc001a1e6e0?, 0xc0004e6b40?})
        github.com/go-crypt/crypt@v0.2.3/algorithm/bcrypt/decoder.go:84 +0x210
github.com/go-crypt/crypt.(*Decoder).decode(0xc0004d15e0, {0xc001a1e6e0, 0x1c})
        github.com/go-crypt/crypt@v0.2.3/decoder.go:156 +0x3f9
github.com/go-crypt/crypt.(*Decoder).Decode(...)
        github.com/go-crypt/crypt@v0.2.3/decoder.go:129
github.com/go-crypt/crypt.decode({0xc001a1e6e0?, 0xc000ea3478?})
        github.com/go-crypt/crypt@v0.2.3/decode.go:31 +0xfb
github.com/go-crypt/crypt.Decode(...)
        github.com/go-crypt/crypt@v0.2.3/decode.go:17
github.com/authelia/authelia/v4/internal/authentication.UserDetailsModel.ToDatabaseUserDetailsModel({{0xc001a1e6e0, 0x1c}, {0xc001609ea0, 0xc}, {0xc001a1e640, 0x1b}, {0xc0003be090, 0x1, 0x1}, 0x0}, ...)     
        github.com/authelia/authelia/v4/internal/authentication/file_user_provider_database.go:314 +0x3d
github.com/authelia/authelia/v4/internal/authentication.(*DatabaseModel).ReadToFileUserDatabase(0xc00058d310, 0xc001015600)
        github.com/authelia/authelia/v4/internal/authentication/file_user_provider_database.go:246 +0x105
github.com/authelia/authelia/v4/internal/authentication.(*FileUserDatabase).Load(0xc001015600)
        github.com/authelia/authelia/v4/internal/authentication/file_user_provider_database.go:66 +0x145
github.com/authelia/authelia/v4/internal/authentication.(*FileUserProvider).Reload(0xc001015280)
        github.com/authelia/authelia/v4/internal/authentication/file_user_provider.go:52 +0x105
github.com/authelia/authelia/v4/internal/commands.runServiceFileWatcher.func1()
        github.com/authelia/authelia/v4/internal/commands/root.go:243 +0x4ce
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

### Logs (Proxy / Application)

```shell
11728:M 09 Jun 2023 10:54:37.180 * Background saving terminated with success
11728:M 09 Jun 2023 10:59:38.038 * 100 changes in 300 seconds. Saving...
11728:M 09 Jun 2023 10:59:38.039 * Background saving started by pid 4346
4346:C 09 Jun 2023 10:59:38.057 * DB saved on disk
4346:C 09 Jun 2023 10:59:38.058 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
11728:M 09 Jun 2023 10:59:38.139 * Background saving terminated with success
11728:M 09 Jun 2023 11:04:39.016 * 100 changes in 300 seconds. Saving...
11728:M 09 Jun 2023 11:04:39.017 * Background saving started by pid 4373
4373:C 09 Jun 2023 11:04:39.035 * DB saved on disk
4373:C 09 Jun 2023 11:04:39.036 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
11728:M 09 Jun 2023 11:04:39.118 * Background saving terminated with success
11728:M 09 Jun 2023 11:09:40.017 * 100 changes in 300 seconds. Saving...
11728:M 09 Jun 2023 11:09:40.018 * Background saving started by pid 4447
4447:C 09 Jun 2023 11:09:40.036 * DB saved on disk
4447:C 09 Jun 2023 11:09:40.037 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
11728:M 09 Jun 2023 11:09:40.118 * Background saving terminated with success
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Please provide the complete logs as required by the issue tempalte.

**Comment by trmz** [comment]
How many log entries back from the panic do you want ?
Managed to log with level:trace from startup to panic, but the uncompressed file is ~1.2GB. 

Note that previously I was rewriting the file in a mostly non-atomic way, and the panic occurred every few hours. 
Switched to writing the file in a way that it should appear atomic to Authelia, and that helped immensely - took a couple days for it to crash again. 
Seems consistent with my original guess that Authelia is reading the file as it changes. 


Not familiar with Go - does Authelia attempt any exclusive lock on read ? 
Probably not, and reasonably so ? 
Does it slurp the entire file contents, or read a chunk, do some work, read some more ? 
Do you test Authelia in environments with moderate+ disk contention ? 

I'll see if I can limit I/O, to see whether panic occurrences increase. 
Would be nice to strace it to the panic, but don't have space for that atm.

**Comment by james-d-elliott** [comment]
> How many log entries back from the panic do you want ?
> Managed to log with level:trace from startup to panic, but the uncompressed file is ~1.2GB.

The logs should be provided per the instructions in the issue template which include the minimum requirement when it comes to large log files:

> Logs (Authelia)
> 
> Provide complete logs with the log level set to debug or trace. Complete means from application start until the issue occurring. This is clearly explained in the [Logs](https://www.authelia.com/r/troubleshooting#logs) section of the troubleshooting guide.
> 
> The template will automatically put this content in a code block so you can just paste it.

As far as everything else:

> Seems consistent with my original guess that Authelia is reading the file as it changes.

I mean what else would you expect when looking at the docs? https://www.authelia.com/configuration/first-factor/file/#watch

Authelia is notified by the kernel when a file is modified (inotifiy write) and initiates a read at that point. If multiple writes occur in quick succession it only initiates this read the first time (many kernel versions send multiple inotify events for a single write).

> Not familiar with Go - does Authelia attempt any exclusive lock on read ?
> Probably not, and reasonably so ?
> Does it slurp the entire file contents, or read a chunk, do some work, read some more ?
> Do you test Authelia in environments with moderate+ disk contention ?

We use the `os` package for file reading in most instances. This is a high level package which by default behaves exactly the same on every OS. As such it doesn't perform fs locks by default as not every OS supports it and some don't support it in remotely similar ways. I believe this performs a read of the entire file contents. 

We can probably implement fs locks via low level sys calls but we'll need to see the specific use case where this is needed. Specifically why are you not writing the file completely when you modify it?

**Comment by james-d-elliott** [comment]
Which lock type does the application writing the file respect?

**Comment by trmz** [comment]
Hey, thanks for the info and patience.  

So previously, was writing ~140 users / 765 lines / 25,000 bytes with ">" in a bash script - unsafe, tbf. 
Switched to Perl's Path::Tiny->move(), as part of a broader script that fetches updated info. 
Docs for that library note : 

> If the destination already exists and is a directory, and the source is not a directory, then the source file will be renamed into the directory specified by the destination.
> 
> If possible, move() will simply rename the file. Otherwise, it copies the file to the new location and deletes the original. If an error occurs during this copy-and-delete process, you may be left with a (possibly partial) copy of the file under the destination name.

I wrongly assumed it was _renaming_ the file successfully, which should show up to Authelia "mostly" atomically. 
auditd revealed that the rename method was failing, so it was quietly falling back to the copy-delete method. 
> arch=x86_64 syscall=rename success=no exit=EACCES(Permission denied)

Now corrected : 
> arch=x86_64 syscall=rename success=yes exit=0 


I'm optimistic we'll no longer see this panic error, but will report back with more detailed info if so. 
Hope this helps anyone else who might encounter this.

Ideally, wish Authelia could support DB / Postgres backend for First Factor, but I recognize that's a massive feature request so this'll do for a while.  :)

**Comment by james-d-elliott** [comment]
> So previously, was writing ~140 users / 765 lines / 25,000 bytes with ">" in a bash script - unsafe, tbf.

This also does not respect file locks, either created via flock or fcntl (or lockf). Unless you're using Windows (or System V which I think has a workaround) both parties must respect the locks for them to work. The stdout redirection ironically doesn't even respect the POSIX locks on pretty much any *nix variant except maybe System V if you're not running as root.

> I'm optimistic we'll no longer see this panic error, but will report back with more detailed info if so.
Hope this helps anyone else who might encounter this.

Delete + Create should work flawlessly. We ignore deleted inotify events, and only reload on change/create inotify events. This should be completely atomic.

**Comment by james-d-elliott** [comment]
This occurs it looks like when the secret portion of the hash is less than the minimum salt length (i.e. incomplete/invalid). I can make a fix for the panic itself most likely, however the underlying cause is an invalid hash.

**Comment by james-d-elliott** [comment]
The bug has theoretically been fixed upstream. Will merge once I've verified the fix.
