### ISSUE TITLE
SMTP Notifier Content-Type: multipart/alternative; order does not respect RFC 2046

### ISSUE THREAD

**Issue by aaww01** [authelia/authelia#5617]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Reverse Proxy Version

2.10.3

### Description

Authelia smtp notifier is building multipart MIME messages using Content-Type: multipart/alternative with the HTML template's content followed by Plain TEXT template's content.

According to RFC 2046, the order of the parts in a multipart MIME message is important with section 5.1.4 stating:

> As with "multipart/mixed", the order of body parts is
   significant.  In this case, the alternatives appear in an order of
   increasing faithfulness to the original content.  In general, the
   best choice is the LAST part of a type supported by the recipient
   system's local environment.

The effect of this implementation is that in GMAIL, it displays the Plain TEXT version of the message in lieu of the HTML version despite it being present in the message body, with no control over the preference.  On other email applications such as Thunderbird, the user can choose to prefer the HTML or Plain TEXT version.

### Reproduction

1. Configuring an authelia user with a gmail / google workspace account
2. Clicking Reset password or Register device for that user account to generate an smtp notification to the gmail/google workstpace account email address.
3. View the resulting email

### Expectations

The email body is generated by including the plain text version followed by the HTML version so that RFC 2046 is respected.

### Configuration (Authelia)

```yaml
Issue is not related to Authelia's configuration; disable_html_emails is false, and view source of the email bears this out.
```

### Logs (Authelia)

```shell
t{"level":"info","msg":"Storage schema is being checked for updates","time":"2023-06-28T13:13:55-04:00"}
{"level":"info","msg":"Storage schema is already up to date","time":"2023-06-28T13:13:55-04:00"}
{"level":"debug","msg":"Create Server Service (metrics) skipped","time":"2023-06-28T13:13:55-04:00"}
{"level":"info","msg":"Listening for non-TLS connections on '[::]:9091' path '/'","server":"main","service":"server","time":"2023-06-28T13:13:55-04:00"}
{"level":"info","msg":"Startup complete","time":"2023-06-28T13:13:55-04:00"}
{"file":"/config/portal/users_database.yml","level":"info","msg":"Watching file for changes","service":"watcher","time":"2023-06-28T13:13:55-04:00","watcher":"users"}
{"level":"debug","method":"POST","msg":"Sending an email to user test1 (user@example.com) to confirm identity for registering a device.","path":"/api/reset-password/identity/start","remote_ip":"10.x.y.z","time":"2023-06-28T13:14:10-04:00"}
```

### Documentation

https://datatracker.ietf.org/doc/html/rfc2046

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Fixed in 0bb657e11cfa6b9f16cd28340291b121fa1579bc

**Comment by james-d-elliott** [comment]
Actually on closer inspection this report is invalid. For starters in 4.37.5 we write the HTML content AFTER the text content, and you did not include the full logs.

**Comment by aaww01** [comment]
That's what I thought... but pulling code from Github, I ended up with the code in smtp_notifier.go showing HTML then Plain text.
In fact the master branch is showing this; see lines 131+ here: https://github.com/authelia/authelia/blob/master/internal/notification/smtp_notifier.go

**Comment by james-d-elliott** [comment]
Please include all of the logs: https://www.authelia.com/reference/guides/troubleshooting

**Comment by aaww01** [comment]
I appreciate the response, please bear with me as I am a complete n00b at this whole github thing.
I should have specified that I am building from source as there is some theme customization required for the implementation.

Apparently git clone Authelia gives me the master branch which is different from v4.37.5, but oddly, running version command in my resulting docker container gives this output:
authelia version untagged-v4.37.5-dirty (master, 0036cc8)

**Comment by james-d-elliott** [comment]
That's the expected version format for unreleased / alpha / beta / etc versions. We include the most information in these cases to make it easier to debug with users who prefer living on the edge.
