### ISSUE TITLE
Assistance: Building on CentOS7 using go

### ISSUE THREAD

**Issue by davama** [authelia/authelia#565]
Hello,

Since V4 was released Ive been wanting to try it again. Using [doc](https://github.com/authelia/authelia/blob/master/docs/deployment-production.md#deployment-for-production) 
Unfortunately I could not build.

```
[config@authelia ~]$ cd authelia/
[config@authelia authelia]$ source bootstrap.sh 
[BOOTSTRAP] Checking if Go is installed...
go: finding github.com/kr/pty v1.1.8
go: go.mongodb.org/mongo-driver@v1.1.3: unrecognized import path "go.mongodb.org/mongo-driver" (https fetch: Get https://go.mongodb.org/mongo-driver?go-get=1: proxyconnect tcp: tls: oversized record received with length 20527)
go: finding github.com/facebookgo/stack v0.0.0-20160209184415-751773369052
go: finding github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: gopkg.in/ldap.v3@v3.1.0: unrecognized import path "gopkg.in/ldap.v3" (https fetch: Get https://gopkg.in/ldap.v3?go-get=1: proxyconnect tcp: tls: oversized record received with length 20527)
go: finding github.com/spf13/cobra v0.0.5
go: finding github.com/ogier/pflag v0.0.1
go: gopkg.in/yaml.v2@v2.2.4: unrecognized import path "gopkg.in/yaml.v2" (https fetch: Get https://gopkg.in/yaml.v2?go-get=1: proxyconnect tcp: tls: oversized record received with length 20527)
go: finding github.com/golang/mock v1.3.1
go: finding github.com/go-stack/stack v1.8.0
go: finding github.com/lib/pq v1.2.0
go: finding github.com/valyala/fasthttp v1.6.0
go: finding github.com/duosecurity/duo_api_golang v0.0.0-20190308151101-6c680f768e74
go: finding github.com/simia-tech/crypt v0.2.0
go: finding github.com/tstranex/u2f v1.0.0
go: finding github.com/go-sql-driver/mysql v1.4.1
go: finding github.com/golang/snappy v0.0.1
go: finding github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: finding github.com/tebeka/selenium v0.9.9
go: finding github.com/onsi/ginkgo v1.10.3
go: finding github.com/deckarep/golang-set v1.7.1
go: finding github.com/sirupsen/logrus v1.4.2
go: finding github.com/Gurpartap/logrus-stack v0.0.0-20170710170904-89c00d8a28f4
go: finding github.com/mattn/go-sqlite3 v1.11.0
go: google.golang.org/appengine@v1.6.5: unrecognized import path "google.golang.org/appengine" (https fetch: Get https://google.golang.org/appengine?go-get=1: proxyconnect tcp: tls: oversized record received with length 20527)
go: finding github.com/fasthttp/session v1.1.3
go: finding github.com/tidwall/pretty v1.0.0
go: finding github.com/onsi/gomega v1.7.1
go: finding github.com/stretchr/testify v1.4.0
go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: finding github.com/pquerna/otp v1.2.0
go: finding github.com/Workiva/go-datastructures v1.0.50
go: finding github.com/otiai10/copy v1.0.2
go: finding github.com/asaskevich/govalidator v0.0.0-20190424111038-f61b66f89f4a
go: finding github.com/xdg/stringprep v1.0.0
go: finding github.com/fasthttp/router v0.5.2
go: finding github.com/cespare/reflex v0.2.0
go: error loading module requirements
```
```
[config@authelia authelia]$ go version
go version go1.11.5 linux/amd64
```
**Interesting note:**
my vm is behind a http proxy

I had attempted with go verion `1.13` but that was worse....

```
[config@authelia authelia]$ go version
go version go1.13.5 linux/amd64
[config@authelia authelia]$ source bootstrap.sh 
[BOOTSTRAP] Checking if Go is installed...
go: github.com/Gurpartap/logrus-stack@v0.0.0-20170710170904-89c00d8a28f4: Get https://proxy.golang.org/github.com/%21gurpartap/logrus-stack/@v/v0.0.0-20170710170904-89c00d8a28f4.mod: proxyconnect tcp: tls: first record does not look like a TLS handshake
```

Any input is much appreciated.

Thanks,
Dave

**Comment by james-d-elliott** [comment]
Those errors look like they are errors related to the proxy. Are you able to do go get's to download go modules? Is there any way to test it without the proxy?

**Comment by nightah** [comment]
Your issue aside @davama we actually release static binaries now that you can run, this is to say without having to build yourself.

You can find these at https://github.com/authelia/authelia/releases/latest if you looking for the latest tagged/versioned release.

Or if you want to grab the latest untagged version; ie HEAD @ master you can grab this from the Authelia pipeline over at Buildkite. For example here's the amd64 static binary for HEAD as of posting this comment:
https://buildkite.com/authelia/authelia/builds/218#33d620b1-f1d1-4101-af76-e1959cba3bda
Make sure you click "Artifacts".

**Comment by clems4ever** [comment]
@davama , I have never faced such issue but this might help: https://github.com/docker/for-linux/issues/415.
Are you running the command inside a container or a VM?

**Comment by davama** [comment]
Thank you all for the responses. @nightah  Look forward to formal doc for the alternate install methods :+1: 

@clems4ever i am attempting to install this on a bare metal (currently a VM to test ) We dont use docker and dont want to over engineer this setup if not necessary.

I tried the static binary and here are my results: :+1: for the binary!

```
[root@authelia ~]# ./authelia-linux-amd64 --config /etc/authelia.yml 
INFO[0000] Logging severity set to debug                
FATA[0000] Unable to initialize SQL database: Error 1049: Unknown database 'authelia'  stack="github.com/authelia/authelia@/internal/storage/mysql_provider.go:65 NewMySQLProvider\ngithub.com/authelia/authelia@/cmd/authelia/main.go:72               startServer\ngithub.com/authelia/authelia@/cmd/authelia/main.go:108              main.func1\ngithub.com/spf13/cobra@v0.0.5/command.go:830                        (*Command).execute\ngithub.com/spf13/cobra@v0.0.5/command.go:914                        (*Command).ExecuteC\ngithub.com/spf13/cobra@v0.0.5/command.go:864                        main\ngithub.com/spf13/cobra@v0.0.5/command.go:864                        (*Command).Execute\nruntime/proc.go:203                                                 main\nruntime/asm_amd64.s:1357                                            goexit"
```
So i created the DB `authelia` :
```
[root@authelia ~]# mysql -u authelia -pauthelia
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 12
Server version: 5.5.64-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> create database authelia;
Query OK, 1 row affected (0.00 sec)

MariaDB [(none)]> Bye
```
But another wall :disappointed: 
```
[root@authelia ~]# ./authelia-linux-amd64 --config /etc/authelia.yml 
INFO[0000] Logging severity set to debug                
FATA[0000] Unable to initialize SQL database: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IF NOT EXISTS time ON authentication_logs (time)' at line 1  stack="github.com/authelia/authelia@/internal/storage/mysql_provider.go:65 NewMySQLProvider\ngithub.com/authelia/authelia@/cmd/authelia/main.go:72               startServer\ngithub.com/authelia/authelia@/cmd/authelia/main.go:108              main.func1\ngithub.com/spf13/cobra@v0.0.5/command.go:830                        (*Command).execute\ngithub.com/spf13/cobra@v0.0.5/command.go:914                        (*Command).ExecuteC\ngithub.com/spf13/cobra@v0.0.5/command.go:864                        main\ngithub.com/spf13/cobra@v0.0.5/command.go:864                        (*Command).Execute\nruntime/proc.go:203                                                 main\nruntime/asm_amd64.s:1357                                            goexit"

```

Im assuming im on the right track. Any input is always appreciated!

-Dave

**Comment by clems4ever** [comment]
Probably related to https://github.com/authelia/authelia/issues/512. Only Mariadb and Postgres are supported right now. I will fix MySQL soon though.

**Comment by davama** [comment]
> Probably related to #512. Only Mariadb and Postgres are supported right now. I will fix MySQL soon though.

I see. but i am using mariadb but according to the #512 it has not been tested.
I am willing to help out in the test if possible.

I'll also grab the latest HEAD binary.

One question about the HEAD binary, are they always up to date? Just like you can just clone from git and have the latest HEAD branch
 
Thanks

**Comment by clems4ever** [comment]
@davama , sorry I did not see that you were using Mariadb from the logs. However, Mariadb is definitely tested in the integration tests. I think I see the issue: you're using version 5.5.64 of Mariadb while the latest is 10.5.0. Some features might definitely be missing in the version you're using. Authelia is using the latest in the tests.

Regarding the binaries, they are generated for each release, not from the HEAD of the master branch.

**Comment by davama** [comment]
had a hunch about the mariadb version... now using 10.4
```
[root@authelia ~]# mysql --version
mysql  Ver 15.1 Distrib 10.4.11-MariaDB, for Linux (x86_64) using readline 5.1
```
Here are my updates:
```
[root@authelia ~]# ./authelia-linux-amd64 --config /etc/authelia.yml 
INFO[0000] Logging severity set to debug                
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9715a8]

goroutine 1 [running]:
main.startServer()
	github.com/authelia/authelia@/cmd/authelia/main.go:80 +0x2f8
main.main.func1(0xc0002ec000, 0xc0002a4280, 0x0, 0x2)
	github.com/authelia/authelia@/cmd/authelia/main.go:108 +0x20
github.com/spf13/cobra.(*Command).execute(0xc0002ec000, 0xc000020190, 0x2, 0x2, 0xc0002ec000, 0xc000020190)
	github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ec000, 0xc00016df48, 0x1, 0x1)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	github.com/authelia/authelia@/cmd/authelia/main.go:122 +0x142
```
marida db logs: (not very interesting maybe)
```
2020-01-21 16:28:31 8 [Warning] Aborted connection 8 to db: 'authelia' user: 'authelia' host: 'localhost' (Got an error reading communication packets)
2020-01-21 16:28:31 8 [Warning] Aborted connection 8 to db: 'authelia' user: 'authelia' host: 'localhost' (This connection closed normally)
```

**Comment by clems4ever** [comment]
It's likely a configuration issue around the notifier section. Can you show us your Authelia configuration?

The stack trace is definitely a bug that needs to be fixed, Authelia should not crash without an error message. I'll handle it.

**Comment by clems4ever** [comment]
I see the bug leading to the stack trace, I'll provide a fix today. It seems that the notifier is not defined in your configuration.
I advise you to start from the config template available at the root of the repo if it's not already the case.

**Comment by davama** [comment]
I had commented out the snmp part.
now all is good.

```
[root@authelia ~]# vi /etc/authelia.yml 
[root@authelia ~]# ./authelia-linux-amd64 --config /etc/authelia.yml 
INFO[0000] Logging severity set to debug                
DEBU[0000] Notifier SMTP client initializing TLS configuration 
Selected public_html directory is  ./public_html
INFO[0000] Authelia is listening on 127.0.0.1:9091     
```

Now to add the nginx proxy, but that is outside of this issue.
Thank you for the quick responses!!

Closing

**Comment by nightah** [comment]
Also thought I would chime in there.

The releases on the GitHub releases page are generated based on tagged releases.

If you are for whatever reason utilising a feature, need a bug fix or something that hasn’t made it in to a release yet you definitely can grab the binary from Buildkite per my earlier comment, which is generated for each commit to master.

So if you go to the latest build in Buildkite you can grab the HEAD @ master binary.

**Comment by davama** [comment]
> If you are for whatever reason utilising a feature, need a bug fix or something that hasn’t made it in to a release yet you definitely can grab the binary from Buildkite per my earlier comment, which is generated for each commit to master.
So if you go to the latest build in Buildkite you can grab the HEAD @ master binary.

@nightah that makes sense. 
But a **release** is not the same as some bug fix patch that is committed to master post-relaese

> which is generated for each commit to master.
So if you go to the latest build in Buildkite you can grab the HEAD @ master binary.

So this means any patch applied pre-release will be automatic compiled in the HEAD binary file. Yes?

**Comment by nightah** [comment]
> So this means any patch applied pre-release will be automatic compiled in the HEAD binary file. Yes?

It depends completely on the commit in question.
Essentially our Build pipeline will build a binary for every single commit to master. If there's a bugfix that has not yet been specified in a tagged release, but exists in our repo, you can benefit from it.
All you need to do is find the corresponding build to the commit which you can see both in the GitHub commit history or the Buildkite build, and grab the binary in question.

**Comment by davama** [comment]
Got it!
Thank you kindly for the clarification!
