### ISSUE TITLE
Wrong warning message logs_file is deprecated ... replaced by server.host

### ISSUE THREAD

**Issue by 0verEngineer** [authelia/authelia#5650]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Description

level=warning msg="Configuration: configuration key 'logs_file' is deprecated in 4.30.0 and has been replaced by 'server.host': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"

### Reproduction

have `host: 0.0.0.0` instead of `server.host: 0.0.0.0` in the config

### Logs (Authelia)

```shell
level=warning msg="Configuration: configuration key 'logs_file' is deprecated in 4.30.0 and has been replaced by 'server.host': this has been automatically mapped for you but you will need to adjust your configuration to remove this message"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Thanks for  reporting but it's already fixed 13a45bd36079a9758eebb7226879e9c4586a13a9
