### ISSUE TITLE
Generic access control list

### ISSUE THREAD

**Issue by c-dst** [authelia/authelia#5653]
### Description

I am looking to create a generic access control list for users.
Which allows different users to have access to a domain but only a restricted part of the URL path.

### Use Case

This could allows different users to have access to a same domain but only a restricted part of the URL path with no need to update the ACLs when a new user is added.

### Details

Example: 
 User 1 (login : user1) should only be able to access https://my.mydomain.tld/user1/
 User 2 (login : user2) should only be able to access https://my.mydomain.tld/user2/

I have several users, and I don't want to create an acl for every new user, so is it possible to declare a generic acl like :

 - domain: 
     - my.mydomain.tld 
   policy: one_factor 
   resources: 
     - '^/{{ username }}/.*$' 
   subject: 
     - "user:{{ username}}"

Where {{ username }} would be a template representing the authenticated username.

### Documentation

 - 

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Template features exist in c7f4d5999d0b0b22594dcc917516257e4fe81747 and see the docs for other available options; [resources](https://www.authelia.com/configuration/security/access-control/#resources), [domain_regex](https://www.authelia.com/configuration/security/access-control/#domain_regex), and [named groups](https://www.authelia.com/configuration/security/access-control/#named-regex-groups).
