### ISSUE TITLE
api tokens to bypass 2fa

### ISSUE THREAD

**Issue by Yvonne-Aizawa** [authelia/authelia#5665]
### Description

I would love it if there were a way to authenticate with api keys. These should be created from the ui. they can be either provided in a get parameter or in the http headers.

### Use Case

Automation mainly. When i want to access stuff in a script. i cant since i have 2fa enabled for stuff. if i were to be able to use a token i could automate it. It would also be handy for uptime detectors since those just see authelia instead of the service behind it

### Details

things that would need to be added
- a way to create/delete auth tokens (hopefully from UI)
- a way to use the tokens. either in get/post params. or in http headers

things that would be nice
- setting paths an api token can be used on

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Duplicate #2023
