### ISSUE TITLE
Run Authelia with systemd

### ISSUE THREAD

**Issue by mqmq0** [authelia/authelia#568]
Hello Everyone,

Its not an issue rather I ask for a little help. I cannot for the love of god figure out whats wrong with my systemd service to run Authelia on startup:

```
[Unit]
Description= Authelia SSO Service

[Service]
User=authelia
Group=authelia
WorkingDirectory=/var/www/authelia
ExecStart=/bin/bash /var/www/authelia/cmd/authelia-scripts/authelia-scripts serve /etc/authelia/config.yml

[Install]
WantedBy=multi-user.target

```
I always got this as a result:

> -- Unit authelia.service has finished starting up.
> --
> -- The start-up result is RESULT.
_**> jan 21 22:02:29 asd authelia-scripts[1312]: stat cmd/authelia-scripts/*.go: no such file or directory**_
> jan 21 22:02:29 asd systemd[1]: authelia.service: Main process exited, code=exited, status=1/FAILURE

If I run the Exec command from whatever directory I get the same error. I have to CD into the /var/www/authelia to be able to start it.
I tried to write a simple .sh script: cd into the direct, THEN run the start command.
I tried thing like this:
`ExecStart=/bin/bash cd /var/www/authelia && /var/www/authelia/cmd/authelia-scripts/authelia-scripts serve /etc/authelia/config.yml`

But nothing  helps.
What am I missing?

**Comment by davama** [comment]
Not sure but here is mine:

```
# /usr/lib/systemd/system/authelia.service
Description=2FA Single Sign-On Authentication Server
Requires=mariadb.service redis.service
After=network.target

[Service]
User=authelia
Group=authelia
ExecStart=/usr/local/sbin/authelia --config /etc/authelia/config.yml
Restart=always

[Install]
WantedBy=multi-user.target

```

**Comment by nightah** [comment]
@mqmq0 is there any reason why you are actually running `authelia-scripts` instead of the `authelia` binary?

authelia-scripts is can be utilised to serve our a compiled binary but you're better off just grabbing the pre-compiled binaries and pointing to that.

**Comment by nightah** [comment]
The reason that error is coming up is because you don’t have a compiled binary.

You should instead be grabbing a compiler binary either from GitHub or Buildkite and changing your systemd service to point to that instead of authelia-scripts.

@davama’s example is a great starting point.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mqmq0** [comment]
Could you please point me to one off these compiled binaries?

**Comment by davama** [comment]
Look at Assest
https://github.com/authelia/authelia/releases

**Comment by nightah** [comment]
Basically what @davama has suggested, https://github.com/authelia/authelia/releases/latest always points to the latest release.

**Comment by nightah** [comment]
@mqmq0 #576 is pending but I've included a systemd unit file in this PR which you should be able to adapt to your own use: https://github.com/authelia/authelia/blob/987028c4322a3753dc1be743fd30d7b025c90cef/authelia.service.

In future the unit will included alongside the static binaries.

Please let me know if the feedback has helped you fix your issue.

**Comment by mqmq0** [comment]
So, I downloaded the latest release. Unpacked it and ran like this:
`./authelia-linux-amd64 --config /etc/authelia/config.yml`
**Works fine.**
Out of curiosity I went to another folder, (cd /) and ran:
 `/var/www/authelia-linux-amd64 --config /etc/authelia/config.yml`

but I get:

```
2020/01/23 21:25:53 0.001 #0000000100000001 - lanip:9091<->otherlanip:54998 - GET http://authelia.mydomain.com/ - cannot open file "./public_html": open ./public_html: no such file or directory
2020/01/23 21:25:54 0.001 #0000000200000001 - lanip9091<->otherlanip:55000 - GET http://authelia.mydomain.com/public_html/index.html - cannot open file "/public_html/index.html": open /public_html/index.html: no such file or directory
```
Then I tried the systemd again.

I made a unit file like this(dont mind the #commented lines... i tried a lot of things):

```
[Service]
#User=authelia
#Group=authelia
#WorkingDirectory=/var/www/authelia
#Type=simple
Environment=PUBLIC_DIR=/var/www/public_html
ExecStart=/var/www/authelia-linux-amd64 --config /etc/authelia/configuration.yml
#SyslogIdentifier=authelia

[Install]
WantedBy=multi-user.target
```

I get this hefty error in return from `journalctl`

```
-- Subject: Unit authelia.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The start-up result is RESULT.
jan 23 21:21:59 asd systemd[1716]: authelia.service: Failed to execute command: No such file or directory
jan 23 21:21:59 asd systemd[1716]: authelia.service: Failed at step EXEC spawning /var/www/authelia/cmd/authelia-scripts/authelia-scripts: No such file or directory
-- Subject: Process /var/www/authelia/cmd/authelia-scripts/authelia-scripts could not be executed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The process /var/www/authelia/cmd/authelia-scripts/authelia-scripts could not be executed and failed.
--
-- The error number returned by this process is 2.
jan 23 21:21:59 asd systemd[1]: authelia.service: Main process exited, code=exited, status=203/EXEC
jan 23 21:21:59 asd systemd[1]: authelia.service: Failed with result 'exit-code'.
jan 23 21:21:59 asd systemd[1]: authelia.service: Service hold-off time over, scheduling restart.
jan 23 21:21:59 asd systemd[1]: authelia.service: Scheduled restart job, restart counter is at 5.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Automatic restarting of the unit authelia.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
jan 23 21:21:59 asd systemd[1]: Stopped Authelia.
-- Subject: Unit authelia.service has finished shutting down
```
 
Almost there, I think, I'm just missing something around the WorkingDir/Enviroment variables.

**Comment by nightah** [comment]
The unit file you are modifying doesn’t appear to be the one that is loaded.

You can tell this by the error message `The process /var/www/authelia/cmd/authelia-scripts/authelia-scripts could not be executed and failed.` because it’s trying to utilise authelia-scripts which isn’t what you have in the unit file you have pasted above.

You need to copy your unit file to `/usr/lib/systemd/system` and then run `sustemcto daemon-reload`.

You also can identify the location of the loaded unit when you issue the command `systemctl status authelia` right at the very top it’ll show you the location of the loaded unit which is usually a symlink to the location I mentioned above.

**Comment by nightah** [comment]
How did you go @mqmq0, if you need more real time support can I suggest you come and join us at [Matrix](https://riot.im/app/#/room/#authelia:matrix.org).

**Comment by mqmq0** [comment]
Finally:
```
● authelia.service
   Loaded: loaded (/etc/systemd/system/authelia.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-01-25 17:45:05 CET; 5s ago

```
Indeed, the wrong unit file I tried to modify

`/lib/systemd/system/authelia.service `
but the one I needed is
`/etc/systemd/system/authelia.service`

I got lost somewhere between the two...

Thank you Amir & davama!

Also, neat stuff this Matrix and Riot is. Potential next project :)
