### ISSUE TITLE
SIGSEGV when running under Aarch64

### ISSUE THREAD

**Issue by semiviral** [authelia/authelia#5706]
### Version

v4.37.5

### Deployment Method

Bare-metal

### Reverse Proxy

Caddy

### Reverse Proxy Version

N/A

### Description

Attempting to run the Authelia binary when in an Aarch64 environment results in a runtime error. This is tested with the `.rpm`, the `.deb` (via APT), and both via `systemd` *and* running directly in CLI.

### Reproduction

1. Be on an Aarch64 platform.
2. Download the Authelia binary by (ostensibly) any means.
3. Run the binary.

### Expectations

The binary runs successfully, reporting configuration errors rather than spooky SIGSEGV.

### Configuration (Authelia)

```yaml
N/A: Fails with all configurations.
```

### Logs (Authelia)

```shell
root@mymachine:~# /usr/bin/authelia --config /etc/authelia/configuration.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaaaacd10b728]

goroutine 1 [running]:
math/big.(*Int).BitLen(...)
        math/big/int.go:467
crypto/rsa.(*PublicKey).Size(...)
        crypto/rsa/rsa.go:54
github.com/authelia/authelia/v4/internal/configuration/validator.validateOIDC(0x4000275a00, 0x4000116330)
        github.com/authelia/authelia/v4/internal/configuration/validator/identity_providers.go:40 +0x2d8
github.com/authelia/authelia/v4/internal/configuration/validator.ValidateIdentityProviders(...)
        github.com/authelia/authelia/v4/internal/configuration/validator/identity_providers.go:16
github.com/authelia/authelia/v4/internal/configuration/validator.ValidateConfiguration(0x4000376900, 0x4000116330)
        github.com/authelia/authelia/v4/internal/configuration/validator/configuration.go:66 +0x588
github.com/authelia/authelia/v4/internal/commands.loadConfig({0x4000221d70, 0x1, 0x1}, 0x1, 0x1)
        github.com/authelia/authelia/v4/internal/commands/configuration.go:97 +0x16c
github.com/authelia/authelia/v4/internal/commands.newCmdWithConfigPreRun.func1(0x40000be000?, {0x400025ae20?, 0x2?, 0x2?})
        github.com/authelia/authelia/v4/internal/commands/configuration.go:56 +0x16c
github.com/spf13/cobra.(*Command).execute(0x40000be000, {0x400003c0a0, 0x2, 0x2})
        github.com/spf13/cobra@v1.6.1/command.go:905 +0x550
github.com/spf13/cobra.(*Command).ExecuteC(0x40000be000)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        github.com/authelia/authelia/v4/cmd/authelia/main.go:10 +0x20
```

### Logs (Proxy / Application)

```shell
N/A
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Duplicate #5138

**Comment by semiviral** [comment]
> Duplicate #5138

Perhaps? Unfortunately, the 'file permissions' conclusion seems entirely incorrect. Things work fine on earlier Authelia versions (I can't recall which version I had to backport to); additionally, setting the file perms to 0777 for the entire `*/authelia/**` directory tree does not resolve the issue.

**Comment by james-d-elliott** [comment]
It's almost certainly the same issue, the inability to read the file and lack of appropriate logging are the cause, and the most likely cause of the inability to read it is file permissions (could also probably be the wrong path or general IO). You can try with the build with fixed logging to nail it down more clearly: https://buildkite.com/authelia/authelia/builds/19506

**Comment by semiviral** [comment]
That build outputs much clearer errors! I was able to resolve the issue, thanks.

**Comment by james-d-elliott** [comment]
What was the cause if not the permissions?

**Comment by semiviral** [comment]
I had copied over configuration from an old machine to a new machine—and failed to update the paths in the environment file! Pretty silly mistake, but a little difficult to catch with such a cryptic error message.
