### ISSUE TITLE
Automate deb packaging of Authelia

### ISSUE THREAD

**Issue by nightah** [authelia/authelia#573]

**Comment by james-d-elliott** [comment]
https://www.debian.org/doc/manuals/maint-guide/

**Comment by DblK** [comment]
Leaving information about a great software goreleaser and it has a specific customization about deb package:
https://goreleaser.com/customization/nfpm/
or simply use the binary https://nfpm.goreleaser.com/ if you do not want to use goreleaser for everything ;)

Should help you to focus on Authelia instead of digging in package manager specification ;)
Hope that helps!

**Comment by aos** [comment]
Is this still a thing you'd all like? I can probably work on this. If you just need a `deb` package published with every release, it shouldn't be too much work.

One caveat though: it will be difficult to push it to mainline Debian and Ubuntu repositories. But we can most likely also add it as a PPA that users can add if they'd like: `sudo add-apt-repository ppa:....`

**Comment by nightah** [comment]
I think a deb package we can distribute via GitHub and a PPA is fine initially.

I understand there likely will be challenges having it accepted into the mainline repos primarily because it requires a TU to pick up the packaging or vet someone willing to become a TU for maintenance.

**Comment by mattfox** [comment]
With regards to hosting the Debian repo, I invite you to use the repo hosting service I've built- https://www.getbalto.com/ . As an example, you'd get a site and software repo like the one for Helm, the Kubernetes package manager, at https://helm.baltorepo.com/stable/debian/ .

A couple of advantages over a PPA would be- there's basic download analytics, you could also use it to offer RPM packages in the future, you can customize the site with your logo and colours, and the solution doesn't have "personal" in the name ;) . The monthly download transfer for Balto open source plans is 10 GB but that can be flexible.

You're right about the difficulty of getting anything in the mainline repos, but an advantage of having your own repo is that you can always offer your latest version. The mainline repos, if Authalia was available there, only accept bugfix updates once they freeze for release.

**Comment by aos** [comment]
Hi there -- just a small update. I've put together the tooling necessary to build the package here: https://github.com/aos/authelia-debian

Still testing and working some kinks out. I've used the AUR package as a reference point: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=authelia

I'd like to automate it so that I don't have to run this manually on every new release, or maybe pull it into the authelia organization and have it run as GH action. Something to think about it for now.

**Comment by mattfox** [comment]
I used this tooling to push the .deb up to a repository here: https://authelia.baltorepo.com/stable/debian/

Changes to support this are in a PR here: https://github.com/aos/authelia-debian/pull/1

**Comment by mattfox** [comment]
In building the package I found [an issue](https://github.com/aos/authelia-debian/issues/2). So right now consider the package at the repo a concept, not a working solution.

**Comment by mattfox** [comment]
I've prepared a solution. It's a different method than aos' solution that builds the binary then packages it. Instead, this pulls the published releases from the Github releases page then extracts the binaries, the systemd unit and example config file and packages those together. This is the same pattern I use as the maintainer for the Helm Debian package. For Helm, I've generally issued a new package within 24 hours of a new release, but I plan to automate the work to make it more consistent and would do so for Authelia too.

The tooling is on Github at https://github.com/BaltoRepo/authelia-linux-packages and it pushes to the repository on my service Balto: https://authelia.baltorepo.com/stable/debian/packages/authelia/ . For testing, refer to the installation instructions on that page.

The only functionality for the package beyond what's in the official releases is a postinstall script to register the systemd unit at installation, and prerm script to unregister it.

The package and repo doesn't target any specific Debian or Ubuntu releases, as this is unnecessary for Go software that doesn't depend on other Debian packages.

If this is an acceptable solution, I can make a pull request to update the documented installation instructions.

**Comment by hwittenborn** [comment]
@nightah Are you needing source Debian packages, or just binary ones?

If you only need binary ones, [I've got a project](https://github.com/hwittenborn/makedeb) that can use the [PKGBUILD format](https://wiki.archlinux.org/title/PKGBUILD) to build a package.

[The syntax](https://git.archlinux.org/pacman.git/plain/proto/PKGBUILD.proto) for the file is pretty straightforward to understand, and might be easier for you to maintain.

**Comment by nightah** [comment]
@hwittenborn I attempted to install `makedeb` from the AUR and failed with both the stable and alpha builds.

Ideally what we would probably create a deb for versioned releases and each commit I think binary should be fine in this scenario.

**Comment by hwittenborn** [comment]
@nightah Would you know what failed?

If you were using the AUR packages for Authelia, the issue probably lied in the the dependency names, as they differ between Arch and Debian, and need to be converted (which can be done, I just need to add definitions for the affected packages to a side project makedeb uses).

If you were using a new PKGBUILD specifically for Debian, would you be able to paste the logs of what happened?

**Comment by nightah** [comment]
Installing `makedeb` itself failed. It looks like your `PKGBUILD` isn't written properly, it's attempting to extract `data.tar.xz` however that doesn't exist in the sources.

Is `makedeb` intended to only run on Debian/Unbuntu based systems?

**Comment by hwittenborn** [comment]
Ah, that makes more sense.

I recently migrated the backend that the AUR package was pulling from, and the package stopped working as a result.

I can get the PKGBUILDs pointed to valid sources in about 10 minutes or so, I just need to finish up some stuff first.

**Comment by nightah** [comment]
Let's move the discussion over to https://github.com/hwittenborn/makedeb/issues/7 please.

**Comment by nightah** [comment]
I'm currently evaluating all the options that have been suggested to determine the best way forward and what to automate/include in our CI/CD pipeline.

@aos I've had a look at your tooling, can you explain what actually should be updated in the repo on each build?
I'm mainly thinking about the changelog and other files other build which I'm not very familiar with but probably are pretty important to build `.deb` packages.

From what I can tell the existing tooling builds the packages from source, I think it might make more sense in this scenario just to utilise our binary release/artifacts from within the build to package into a `.deb` file just to reduce complexity and CPU cycles.

**Comment by aos** [comment]
Hey @nightah Sorry I've been neglected this a bit. The only thing that needs to happen for my tool is to update the `debian/changelog` with a new entry above the current one. Yes, it does build the package from source. I basically just translated the PKGBUILD by hand to what Debian knows. Take a look at the `debian/control` for exactly what's happening.

I've pushed updates to it and it works and builds correctly. I'm happy to update it and change it to work with your existing workflow. Ideally I'd rather not have a separate repo for this and build it into your existing process (I see you use buildkite?). Happy to work with you on this!

**Comment by hwittenborn** [comment]
@nightah I've [done some testing on my end](https://github.com/hwittenborn/authelia-pkgbuild-deb), and I'm able to get `authelia-bin` [built with makedeb](https://drone.hunterwittenborn.com/hwittenborn/authelia-pkgbuild-deb/16/1/2), but the `authelia` package [keeps tripping up](https://drone.hunterwittenborn.com/hwittenborn/authelia-pkgbuild-deb/10/1/2) on the `go` command for some reason. Specifically, I'm seeing this in the CI's logs:

```
build command-line-arguments: cannot load embed: malformed module path "embed": missing dot in first path element
```

I'm thinking it could be related to the available Go package on Ubuntu, but I'm not really sure.

**Comment by nightah** [comment]
I've had a brief look at your testing repo. This might actually be the easiest way to plug in to our existing CI/CD pipeline, assuming I can get makedeb working on Arch and the output works as intended.

The fact that the PKGBUILD doesn't need any changes means we can just use our upstream AUR one.

The error you're seeing for the `authelia` package is definitely because of the version of Golang. You need go >= 1.16 which includes embed. Anything lower won't have it included therefore the build from source will fail.

**Comment by hwittenborn** [comment]
Sounds great!

Just a heads up in case you didn't see it, but there's also a Docker image you can use if it helps out all. Either way, I'd stick with the alpha release for the time being, as I don't know how well the stable one will work rn (and I haven't gotten around to updating the stable release on the AUR to work yet).

If you do end up using makedeb, lmk if you're on the alpha release too and I'll try to get a beta branch published so you're not risking your pipelines breaking constantly.

**Comment by nightah** [comment]
So it seems to work but there's a caveat.

It packages the files with whatever ownership exists on the system, so when they're installed the files do not have `root:root` permissions. I even tried this with your Docker container with the same outcome. We could force `makedeb` to run as root but that will have other unintended consequences.

I feel like this is something that needs to be fixed/handled in makedeb.

**Comment by hwittenborn** [comment]
I'm seeing the issue for some packages on my end too, not really sure why it's happening though.

When building on an Arch Linux system, file ownership is correct, right?

There appears to be something wrong with `fakeroot` on Debian, as doing something like `fakeroot -- touch file` followed by `ls -alF` isn't setting the proper permissions either.

I'll try to figure out if there's just something wrong with my implementation or something, I'll get back to you as soon as I can figure something out.

**Comment by hwittenborn** [comment]
I just talked to some people on Ubuntu's IRC, and it looks like this is the issue:

`makepkg` creates the package and build the archive with correct permissions. Apparently the archive can have set permissions that don't get applied until it's extracted. From my understanding of it, if the package is extracted under a normal user, that user's permissions get applied to all the files, as it doesn't have anything else to put them under.

Problem is makedeb uses the folder layout that makepkg sets up, but those files end up being under the current build user.

I'm gonna add a flag that allows `makedeb` to be run as root, but `makepkg` as a normal user. It would look something like this for running as root:

```
sudo makedeb -u *user*
```

I'll see if this properly sets permissions for the built file, but at the least it should allow the files to be set to the `root` user/group.

I'll send an update when it's all ready.

**Comment by hwittenborn** [comment]
Just a heads up - I'm about to do some testing that's gonna break the alpha builds for a bit.

Again, I'll send an update when everything's ready.

**Comment by hwittenborn** [comment]
Did some coding for a bit, and I got it all working now.

The AUR release probably isn't going to work right now, so you'll need to still with the Debian or Docker release for the time being.

You can check the logs of the latest build [here](https://drone.hunterwittenborn.com/hwittenborn/authelia-pkgbuild-deb/21). The permission check of the installed files is at the end of the third step.

**Comment by nightah** [comment]
No problems just let me know when makedeb-alpha is updated on the AUR.

I plan on using our existing CI/CD tooling and we have an Arch based Docker image used for updating the Arch releaseswhich I'll embed with makedeb to manage the packaging.

**Comment by hwittenborn** [comment]
Not to be a downer or anything, but would you be able to stick with the Debian or Docker release for now?

For the ownership issues to be fixed, I had to implement a [patched version of makepkg](https://github.com/hwittenborn/makepkg). Specifically, I had to disable its fakeroot functionality, as that has to be done in makedeb now so the correct permissions persist into the built package. I also had to allow makepkg to be able to run under root, as the new version of makedeb runs makepkg inside the fakeroot.

I'm not quite sure atm how I could port over the patched makepkg version and have it work, as it can't co-exist with the version from `pacman`, and the only other alternative I can think of being able to implement right now is adding `pacman` to makedeb's `conflicts=()` array, but that's not really an option I think I can just force upon users.

The only other option I can think of is submitting a request for makepkg to support running as root and optionally disabling the fakeroot environment, but that wouldn't be immediate, nor guranteed to even happen.

I can try to figure out something, such as maybe running makedeb under a Snap, but I'm not sure how to get everything over into Arch itself.

**Comment by hwittenborn** [comment]
Doing some more testing, and it looks like I can get it working without the patched version of `makepkg`, so I should be able to get this back up and running on the AUR shortly.

**Comment by hwittenborn** [comment]
Everything should be good to go now.

I did some testing of building it on Arch, and then installing it on a Debian distro right after, and everything's checking out fine.

**Comment by nightah** [comment]
Confirmed that this now works thanks @hwittenborn.

**Comment by mattfox** [comment]
Looks like the next step is to set up a repository to make the package available via `apt`.

As I mentioned above, I'd like to offer Balto Repo to make this easy for you and to show download metrics and offer info about the package on the web. It could be here: https://authelia.baltorepo.com/stable/debian/ (the package there already is a version I was making, but it can be deleted in favour of hwittenborn's)

If you'd like this option- the method to upload to the repo can be copied from https://github.com/BaltoRepo/authelia-linux-packages/blob/master/push.sh, and I can send the push token to someone via a personal message.

**Comment by nightah** [comment]
Thanks for that @mattfox.
If we looked at Balto is there any chance we would be able to host it at an authelia based subdomain like `apt.authelia.com`?

**Comment by mattfox** [comment]
Yes, that could be arranged.

**Comment by nightah** [comment]
Great, if you have the opportunity to jump on either our Matrix or Discord channel we can figure out the specifics and look to include the changes as part of either the linked or a separate PR.

**Comment by hwittenborn** [comment]
@nightah I've published a beta release of makedeb if you'd like to switch over to that.

Probably help to avoid any issues when I'm testing stuff like crazy.

**Comment by nightah** [comment]
Looks like we worked this out sorry for the ping, was an issue with makedeb.
