### ISSUE TITLE
Create Helm Chart for Authelia v4

### ISSUE THREAD

**Issue by nightah** [authelia/authelia#575]

**Comment by james-d-elliott** [comment]
I think we should package our charts and create a repo for our users so they can just do this:

`helm repo add authelia https://charts.authelia.com`

To install our stable chart:
```
helm repo update
helm install authelia/stable
```

To install our beta chart:
```
helm repo update
helm install authelia/beta
```
This is a decent guide on packaging charts: https://blog.softwaremill.com/hosting-helm-private-repository-from-github-ff3fa940d0b7

**Comment by Ornias1993** [comment]
@james-d-elliott I just did the same for myself, including CI and release automation...
It could be up-and-running in a day:
1. Create a repo
2. copy my repo: https://github.com/Ornias1993/helm-charts
3. Adapt the readme and gh-pages text
4. remove other/older charts
5. Push it all
6. enable gh-pages with custom domain.

New PR's would go into the dev branch and get CI checked, new version get PR'ed/merged/pushed into the release branch and new releases get generated if the chart-version has changed.

**Comment by james-d-elliott** [comment]
WIP: https://github.com/authelia/chartrepo/

**Comment by james-d-elliott** [comment]
This is closed as it's well and truly a working chart at this point while beta. Ongoing discussion can occur in the chartrepo linked above.
