### ISSUE TITLE
Adjust email subject line

### ISSUE THREAD

**Issue by davama** [authelia/authelia#578]
Hello,

Noticed that the SUBJECT in the emails that get sent when user makes an adjustment to his account are in the following syntax:

`[Authelia] Reset/Register bla bla`

Would it be possible/reasonable to adjust the string *Authelia* to the `totp: issuer` string in the config or maybe some other `mail : issuer` ?

Thanks!

**Comment by james-d-elliott** [comment]
Theoretically this is possible. My opinion is by no means authoritative but we would probably be able to implement this via https://golang.org/pkg/strings/#Replacer using a configuration value in mail. Make all subjects generated via the Replacer, and add the configuration option notification: smtp: subject.

My idea would be to add a configuration value that defaults to the current in the form of "[Authelia] {Title}" and add other replacements (either as part of initial implementation or later) such as {TOTPIssuer}, {Username}, etc. So for example you could do "[My Org] {Title}" to replace "Authelia" with "My Org".

Would probably need @clems4ever  to sign off on this idea, and it would be a low priority.

**Comment by davama** [comment]
@james-d-elliott thank you for the reply!

>  it would be a low priority

Assuming it's approved, that is understandable.

Thanks! :+1:

**Comment by clems4ever** [comment]
I think it's indeed a good idea to give more context to the receiver.

**Comment by james-d-elliott** [comment]
I'll take this up in the next week or so. I have some additional tweaks I want to do in the SMTP area so will see what I can come up with.

**Comment by james-d-elliott** [comment]
So what I decided on was removing "[Authelia]" from the hard coded values provided to the notifier. Then using a replacer to replace '{title}' with the text excluding "[Authelia]". This means you can customize everything other than the part that came after "[Authelia]". The default will remain the same making this change non-breaking.

**Comment by davama** [comment]
Awesome!
Thank you

**Comment by nkukard** [comment]
Really hope this enhancement gets pulled in! :)

Thanks!

**Comment by james-d-elliott** [comment]
@davama @nkukard released with 4.13.0

**Comment by davama** [comment]
Works great!
thank you
