### ISSUE TITLE
Document secret configuration via environment variables

### ISSUE THREAD

**Issue by aroberts** [authelia/authelia#579]
This was fixed as #310, but the env vars are no longer read after the port to go.

**Comment by nightah** [comment]
The code wasn't backported to v4 until recently https://github.com/authelia/authelia/commit/c95c7210d8140ffd37c5d70233e42cf9010faa4b.

I think the issue you are probably seeing is that the variables are now prefixed with `AUTHELIA`.

Please give that a try and let me know if you still have issues.

**Comment by aroberts** [comment]
Ah, I did indeed miss that. I'm running a 4.2 instance, I'll verify tonight and close if I get it working

**Comment by aroberts** [comment]
Confirmed that I can pass secrets via envvars. It looks like the relevant code is here:

https://github.com/authelia/authelia/blob/bb7781fd2b2ea563a6705423660a80e8542c5b13/internal/configuration/reader.go

I'm leaving this ticket open as a request for documentation. Thanks for your help!
