### ISSUE TITLE
Add documentation for multi root cookie domain configuration

### ISSUE THREAD

**Issue by mind-ar** [authelia/authelia#5801]
### Description

Add documentation for multi root cookie domain configuration

### Use Case

none

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Was there something specific you saw missing? https://authelia-next.netlify.app/configuration/session/introduction/

**Comment by mind-ar** [comment]
Hi @james-d-elliott , no, sorry, i didn't see it in https://www.authelia.com/configuration/session/introduction and i remembered that i forgot to include it in the multi-root PR.
Closing it :)
