### ISSUE TITLE
Default redirection not working

### ISSUE THREAD

**Issue by adriaanh** [authelia/authelia#581]
First of all: thanks for all the work. I started using it recently and it has been working great!
 
However, I noted that the default_redirection_url is not working correctly. When I go to my Authelia URL (i.e. auth.example.com) and after succesfull login (even 2FA), I do not get redirected to the default redirection URL, while I have this configurated. Am I doing something wrong here, or is this a minor bug?

```
# Default redirection URL
# If user tries to authenticate without any referer, Authelia
# does not know where to redirect the user to at the end of the
# authentication process.
# This parameter allows you to specify the default redirection
# URL Authelia will use in such a case.
# Note: this parameter is optional. If not provided, user won't
# be redirected upon successful authentication.
default_redirection_url: https://home.example.com

```

**Comment by james-d-elliott** [comment]
Thanks for reporting. This does look like a bug, I'll confirm it when I can.

**Comment by clems4ever** [comment]
Hello, this will be fixed with: https://github.com/authelia/authelia/pull/600.

**Comment by adriaanh** [comment]
Cool, thanks!

**Comment by clems4ever** [comment]
If you wish you can test the feature with the docker tag: fix-default-redirect. It's gonna be available until the PR gets merged.

https://hub.docker.com/layers/authelia/authelia/fix-default-redirect/images/sha256-5954f95cf2e00b64b697580c18e0e8ba10d584576b1065be82b3f8d54fcb424a

**Comment by adriaanh** [comment]
I tested just now, and it is working! However I noticed that it required 2FA, while my default setting is one_factor. The domain it forwarded to is also one_factor. Might be good to align the deafult_redirect with the default_policy or rules attached to the default redirect if set, example:

- Default redirect is: home.example.com
- Default rule is: two_factor
- Specific rule for home.example.com: one_factor
- Authelia should not ask for two_factor after initial login

**Comment by nightah** [comment]
Can you paste a redacted version of your `configuration.yml` please?

**Comment by adriaanh** [comment]
See below. Note that I don't have any access rules implemented, just default one_factor. With this configuration, Authelia was asking for 2FA before redirecting me to the default_redirection_url.

```
###############################################################
#                   Authelia configuration                    #
###############################################################

# The host and port to listen on
host: 0.0.0.0
port: 9091

# Level of verbosity for logs: info, debug, trace
logs_level: debug

# The secret used to generate JWT tokens when validating user identity by
# email confirmation.
# jwt_secret: # set with env var AUTHELIA_JWT_SECRET

# Default redirection URL
#
# If user tries to authenticate without any referer, Authelia
# does not know where to redirect the user to at the end of the
# authentication process.
# This parameter allows you to specify the default redirection
# URL Authelia will use in such a case.
#
# Note: this parameter is optional. If not provided, user won't
# be redirected upon successful authentication.
default_redirection_url: https://home.example.com

# TOTP Issuer Name
#
# This will be the issuer name displayed in Google Authenticator
# See: https://github.com/google/google-authenticator/wiki/Key-Uri-Format for more info on issuer names
totp:
  issuer: example.com

# The authentication backend to use for verifying user passwords
# and retrieve information such as email address and groups
# users belong to.
#
# There are two supported backends: `ldap` and `file`.
authentication_backend:
 
  # File backend configuration.
  #
  # With this backend, the users database is stored in a file
  # which is updated when users reset their passwords.
  # Therefore, this backend is meant to be used in a dev environment
  # and not in production since it prevents Authelia to be scaled to
  # more than one instance.
  #
   file:
     path: /config/users_database.yml

# Access Control
#
access_control:
  default_policy: one_factor

# Configuration of session cookies
#
# The session cookies identify the user once logged in.
session:
  # The name of the session cookie. (default: authelia_session).
  name: authelia_session

  # The secret to encrypt the session cookie.
  ## secret:  #set with env var AUTHELIA_SESSION_SECRET

  # The time in seconds before the cookie expires and session is reset.
  expiration: 3600 # 1 hour

  # The inactivity time in seconds before the session is reset.
  inactivity: 300 # 5 minutes

  # The domain to protect.
  # Note: the authenticator must also be in that domain. If empty, the cookie
  # is restricted to the subdomain of the issuer.
  domain: example.com

  # The redis connection details
  redis:
    host: authelia_redis
    port: 6379
    ## password: # set with env var AUTHELIA_SESSION_REDIS_PASSWORD

# Configuration of the authentication regulation mechanism.
#
# This mechanism prevents attackers from brute forcing the first factor.
# It bans the user if too many attempts are done in a short period of
# time.
regulation:
  # The number of failed login attempts before user is banned.
  # Set it to 0 to disable regulation.
  max_retries: 3

  # The time range during which the user can attempt login before being banned.
  # The user is banned if the authentication failed `max_retries` times in a `find_time` seconds window.
  find_time: 120

  # The length of time before a banned user can login again.
  ban_time: 300

# Configuration of the storage backend used to store data and secrets.
#
# You must use only an available configuration: local, sql
storage:
  # The directory where the DB files will be saved
   local:
     path: /var/lib/authelia/db.sqlite3

# Configuration of the notification system.
#
# Notifications are sent to users when they require a password reset, a u2f
# registration or a TOTP registration.
# Use only an available configuration: filesystem, gmail
notifier:

  smtp:
    username: mail@example.com
    ## password: password set with env var AUTHELIA_NOTIFIER_SMTP_PASSWORD
    host: smtp.gmail.com
    port: 587
    sender: mail@example.com
    ## disable_require_tls: false
    ## disable_verify_cert: false
    ## trusted_cert: ""
```

**Comment by clems4ever** [comment]
@adriaanh , the default redirection url is used only if Authelia does not find the target URL of your user (probably because the user visited the login portal directly instead of the website). Given, the target url is unknown to Authelia, there is no way for Authelia to know whether 1FA is sufficient and that's why it requires 2FA.
However if you don't complete 2FA after 1FA has been validated and you visit your website at this point, you should be authenticated correctly and able to see your website.

Now, the configuration file you provided does not represent the use case you mentioned earlier. In the config file you set the default_policy to one_factor. In that case, I agree that the default redirection should happen after 1FA. If it's not, it's a bug.

Do you confirm that the issue happens in that specific case?

**Comment by clems4ever** [comment]
I confirm the bug. It's here:
https://github.com/authelia/authelia/blob/6245dd68e96af68e477bcc18bd289f35be5f50a7/internal/handlers/handler_firstfactor.go#L135

**Comment by adriaanh** [comment]
Thanks for the response. In can confirm the issue happens in the specific case you mentioned.

**Comment by clems4ever** [comment]
This PR should solve the issue: https://github.com/authelia/authelia/pull/611

**Comment by nightah** [comment]
@adriaanh you can try the fix with the following image: `authelia/authelia:one-factor-default-policy`.

**Comment by adriaanh** [comment]
Yes, works like a charm!
