### ISSUE TITLE
OpenFGA for Authorization

### ISSUE THREAD

**Issue by gedw99** [authelia/authelia#5814]
### Description

Users need Authentication and Authorization. There have been so many attempts, but it looks like openFGA is the way to go.

https://openfga.dev/
https://github.com/openfga/language
https://github.com/craigpastro/openfga-dsl-parser
It uses a DSL parser that is nice and flexible that we can leverage
 ### 

### Use Case

One system for both :)

### Details

Good high level backstory on all this.

https://auth0.com/blog/auth0s-openfga-open-source-fine-grained-authorization-system/

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
What specifically makes OpenFGA desirable to you? Also I don't feel like the writers of the OpenFGA spec claim it to be an AuthN technology anywhere. How does it facilitate AuthN other than an AuthZ method similar to other IAM/IDP solutions?
