### ISSUE TITLE
[WIKI] Use Authelia 2FA through basic auth

### ISSUE THREAD

**Issue by ViRb3** [authelia/authelia#582]
I needed to use Authelia's 2FA from clients that only support regular basic auth so I created a setup with OpenResty which allows that by combining the password and TOTP. I don't know if this is of any interest, but it might be a good wiki article for other people with the same requirement. The project can be found here:
https://github.com/ViRb3/authelia-basic-auth-2fa

**Comment by clems4ever** [comment]
Hello @ViRb3 , nice project, it's interesting. Thank you for sharing your work!
We could definitely integrate that use case somewhere in the documentation. We'll soon deeply rework the doc though so let's integrate it once it's done.
