### ISSUE TITLE
TOTP timer animation does not work on Firefox and Edge

### ISSUE THREAD

**Issue by ViRb3** [authelia/authelia#583]
This is how the TOTP timer looks like on Firefox, it is completely static:

![image](https://user-images.githubusercontent.com/2650170/73125790-cde7e500-3fa2-11ea-91d5-de9bff8a57dd.png)

Not sure what is wrong as the drawing calculations are updated properly:

![image](https://user-images.githubusercontent.com/2650170/73125800-ee17a400-3fa2-11ea-84a2-1ae3bfae7245.png)

**Comment by james-d-elliott** [comment]
Thanks for reporting the issue. I can confirm that it doesn't work in Firefox (does in Chrome).

**Comment by clems4ever** [comment]
Damn, I will put something less fancy I guess :)

**Comment by ViRb3** [comment]
I'm by no means a front-end person, but please check the following post, especially the answer:
https://stackoverflow.com/questions/55386593/firefox-svg-stroke-dasharray-with-unit-px

**Comment by davama** [comment]
If it matters, i see this also with MS Edge browser...

**Comment by davama** [comment]
Any updates on this?
Thank you

**Comment by clems4ever** [comment]
Hello @davama , sorry, theses days have been a bit crazy due to the covid crisis.
I'll replace that logo, hopefully today, to make it compatible with all browsers. I'll ask you to test on Edge once done if you will.

Thanks.

**Comment by davama** [comment]
@clems4ever 
It has been very crazy 😓

Yes, im here to help with testing

Thank you for the response 👍

**Comment by james-d-elliott** [comment]
@ViRb3 @davama I've solved this in Firefox locally. Should also resolve edge but I've not tested.

**Comment by james-d-elliott** [comment]
Okay this is fixed for both Edge and Firefox in the following docker image: authelia/authelia:feature-topt-tuning

Feel free to try it and let us know if it works. Keeping in mind it's beta, not finalized yet, and contains other unreleased changes since the 4.8.0 release.

**Comment by davama** [comment]
@james-d-elliott 
thanks for the update!
We dont use docker so not sure how else i could test. We use the compiled binary.
Any input?
Thanks

**Comment by james-d-elliott** [comment]
Yes, I do! @nightah setup an amazing build system. Grab your artifact from here: https://buildkite.com/authelia/authelia/builds/1013

**Comment by james-d-elliott** [comment]
This has been fixed in 4.9.0. Enjoy @ViRb3 @davama

**Comment by davama** [comment]
@james-d-elliott   
it works! :+1: 
thank you

**Comment by ViRb3** [comment]
All looking good here as well, thanks a ton @james-d-elliott!
