### ISSUE TITLE
endless redirect loop after HAPROXY update - Now lua errors in log

### ISSUE THREAD

**Issue by mamema** [authelia/authelia#5833]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

HAProxy

### Reverse Proxy Version

0.63.1 - haproxy-devel-2.8.d12

### Description

After update of pfsense haproxy package, my long running authelia config has the infamous redirection loop

in the haproxy log, lua errors are found:

i've update / reapplied the lua scripts from the examples area in the github of authelia

`http-request set-var(txn.txnhost) hdr(host)
	http-request set-var(req.scheme) str(https)  if  { ssl_fc } aclcrt_fe_http
	http-request set-var(req.scheme) str(http)  if  !{ ssl_fc } aclcrt_fe_http
	http-request set-var(req.questionmark) str(?)  if  { query -m found } aclcrt_fe_http
	http-request set-var(req.method) str(CONNECT)  if  { method CONNECT } aclcrt_fe_http
	http-request set-var(req.method) str(GET)  if  { method GET } aclcrt_fe_http
	http-request set-var(req.method) str(HEAD)  if  { method HEAD } aclcrt_fe_http
	http-request set-var(req.method) str(OPTIONS)  if  { method OPTIONS } aclcrt_fe_http
	http-request set-var(req.method) str(POST)  if  { method POST } aclcrt_fe_http
	http-request set-var(req.method) str(TRACE)  if  { method TRACE } aclcrt_fe_http
	http-request set-var(req.method) str(PUT)  if  { method PUT } aclcrt_fe_http
	http-request set-var(req.method) str(PATCH)  if  { method PATCH } aclcrt_fe_http
	http-request set-var(req.method) str(DELETE)  if  { method DELETE } aclcrt_fe_http
	http-request set-header X-Forwarded-Method %[var(req.method)]  if   aclcrt_fe_http
	http-request set-header X-Real-IP %[src]  if   aclcrt_fe_http
	http-request set-header X-Forwarded-Proto %[var(req.scheme)]  if   aclcrt_fe_http
	 http-request set-header X-Forwarded-Host %[req.hdr(Host)]  if   aclcrt_fe_http
	http-request add-header X-Forwarded-Port %[dst_port]  if   aclcrt_fe_http
	http-request set-header X-Forwarded-Uri %[path]%[var(req.questionmark)]%[query]  if   aclcrt_fe_http
	 http-request lua.auth-request be_authelia_ipvANY /api/verify  if  protected-frontends aclcrt_fe_http
	http-request redirect location https://example.com/?rd=https://%[base]%[var(req.questionmark)]%[query]  if  protected-frontends !{ var(txn.auth_response_successful) -m bool } aclcrt_fe_http
	http-response set-header Content-Security-Policy "frame-ancestors 'self';"  if   aclcrt_fe_http
	http-response set-header Success %[var(txn.auth_response_code)]  if   aclcrt_fe_http`

this was working before the haproxy update

### Reproduction

i'm not sure how this can be reproduced, as pfsense/haproxy just has been updated

### Logs (Authelia)

```shell
ime="2023-08-11T12:34:43+02:00" level=trace msg="Request hit" method=GET path=/api/state remote_ip=192.168.0.2
time="2023-08-11T12:34:43+02:00" level=trace msg="Replied (status=200)" method=GET path=/api/state remote_ip=192.168.0.2
time="2023-08-11T12:34:43+02:00" level=trace msg="Request hit" method=POST path=/api/user/info remote_ip=192.168.0.2
time="2023-08-11T12:34:43+02:00" level=trace msg="Request hit" method=GET path=/api/configuration remote_ip=192.168.0.2
time="2023-08-11T12:34:43+02:00" level=trace msg="Available methods are [totp webauthn mobile_push]" method=GET path=/api/configuration remote_ip=192.168.0.2
time="2023-08-11T12:34:43+02:00" level=trace msg="Replied (status=200)" method=GET path=/api/configuration remote_ip=192.168.0.2
time="2023-08-11T12:34:43+02:00" level=trace msg="Replied (status=200)" method=POST path=/api/user/info remote_ip=192.168.0.2
time="2023-08-11T12:34:43+02:00" level=trace msg="Request hit" method=POST path=/api/checks/safe-redirection remote_ip=192.168.0.2
time="2023-08-11T12:34:43+02:00" level=trace msg="Replied (status=200)" method=POST path=/api/checks/safe-redirection remote_ip=192.168.0.2
authelia
```

### Logs (Proxy / Application)

```shell
Aug 11 12:21:50 pfSense haproxy[64798]: Lua function 'auth-request': [state-id 0] runtime error: table index is nil from [C]: in method 'get_stats', /var/etc/haproxy/luascript_auth-request.lua:136: in global 'auth_request', /var/etc/haproxy/luascript_auth-request.lua:28: in function line 27.
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
There is no information indicating a bug with authelia included, and the error shown is a error in the lua script.
