### ISSUE TITLE
Access to a 2-factor domain is forbidden if cookie is single-factor

### ISSUE THREAD

**Issue by aroberts** [authelia/authelia#587]
I run a mix of single-factor and 2fa protected services. If I am authenticated via a single-factor cookie, then when I try to access a 2fa-protected service, I get a 403 instead of a login or second-factor challenge.

**Comment by james-d-elliott** [comment]
Thanks for reporting. I am getting the same, but if I refresh it redirects me correctly.

**Comment by james-d-elliott** [comment]
Interestingly, I can no longer get this to happen. I've cleared my cache and tried a private window...

**Comment by nightah** [comment]
I'm not able to replicate this behaviour, here's what I attempted.
1. Clear all cookies associated with Authelia
2. Visit a `one_factor` protected endpoint
3. Authenticate and successfully get redirected to protected endpoint
4. Visit a `two_factor` protected endpoint
5. Authenticate with 2fa and successfully get redirected to protected endpoint

@aroberts can you please try clear your cookies and provide a breakdown of the steps to replicate.
Also just for clarity what reverse proxy are you using and can you please provide a redacted version of your configuration please?

**Comment by aroberts** [comment]
I think it's possible that I had an old cookie with an invalid token. After clearing the cookies I'm not able to reproduce this in the way I was before. Sorry about that, I'll close this out.
