### ISSUE TITLE
Inconsistencies in Argon2 memory configuration

### ISSUE THREAD

**Issue by josef-dijon** [authelia/authelia#5936]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Reverse Proxy Version

1.24.0

### Issue

Setting a reasonable value for the argon2 `memory` parameter in the Authelia `configuration.yml` file results in extreme memory usage and very long processing times when checking or creating password hashes.

### Fix

The `--memory` argument for `authelia hash-password` should take a value in KB, not MB. Maybe... See Solution Space below.

## Context

I have a small Docker homelab that I'm setting up, and I'm using Authelia for authentication along side my reverse proxy (nginx). It's almost definitely going to be just me using it, so I felt that the `users_database.yml` method of user/hash store was adequate for my purposes.

I wanted to tune my Argon hashing to be light weight in terms of memory, so started with a memory limit of 4096kB, and tuned the iterations up, targeting around half a second user time (as I've seen recommended for good security).

Using this command:

```
$ time -v authelia crypto hash generate argon2 \
  --iterations 150 \
  --key-size 32 \
  --memory 4096 \
  --parallelism 4 \
  --salt-size 16 \
  --password password
```

Yields this output:

```
Digest: $argon2id$v=19$m=4096,t=150,p=4 ...
real    0m 0.36s
user    0m 0.52s
sys     0m 0.06s
```

This seems great, but when I plugged these Argon args into my `configuration.yml`, I noticed that my Authelia login and password reset operations were hanging indefinitely, and that the Authelia process was sitting on +100% CPU, 512MB RAM (the limits I've configured in Docker during testing) and that the memory was spilling over into swap by the gigabytes.

The reason for this is that I was doing my timing tests (in the container) using this command:

Command 1: `authelia crypto hash generate argon2 <args>...`

And after a little digging through the source code, the internals of Authelia actually use this command when using values from `configuration.yml`:

Command 2: `authelia hash-password <args>...`

Command 2 takes a memory parameter `--memory` in MB, not kibibytes as everywhere else seems to suggest. This meant in my final configuration, I was actually asking Argon to do 150 iterations with 4GB of memory, in a container limited to 512MB. No wonder it was having a bad time...

## Solution Space

My initial thought was that Command 2 should be changed to take the `--memory` argument in kibibytes, which would be in line with the documentation, the default configuration, and most tutorials/documentation I've seen around.

However, this should probably *not* be done, since anyone using Authelia with the `users_database.yml` authentication backend will all of a sudden have their Argon2 settings yield near instant hashing times (1 iteration of 1024KB), which would constitute a transparent reduction in security.

## Some Speculation

I suspect the reason this hasn't been noticed until now because most home users are using `configuration.yml` settings like these:

```
password:
  algorithm: argon2id
  iterations: 1
  key_length: 32
  salt_length: 16
  memory: 1024
  parallelism: 8
```

I've seen this (or very similar) configuration recommended in several different Youtube tutorials, blogs and the like.

This setting of 1024MB for `--memory` and just 1 iteration, yields a hash time circa 1 second (on my machine), which is mostly unnoticeable and will appear to work "nominally" apart from the >1GB memory usage spike during hashing operations. Even then, the memory spike would only really be noticeable if the user has a memory constraint on their Docker container less than 1GB, or, their system is close to using all available memory, and memory is spilling into swap. This would present as ~1-2 second authentication operations via the Authelia web front end, with the potential for intermittent very long or apparent hanging authentication operations.

## Workaround

I am using the following configuration:

```
password:
  algorithm: argon2id
  iterations: 35
  key_length: 32
  salt_length: 16
  memory: 32
  parallelism: 4
```

`memory: 32` is required to satisfy the `memory >= parallelism * 8` requirement (reported by CLI if you give it less memory).

These settings give me consistent hash times around ~0.5s, meaning authentication in the web front end is very snappy :) It also means I can limit my Docker container to around ~64MB of memory.

### Reproduction

The following is run inside a stock Authelia Docker container using the authelia/authelia:latest image.

1. Run the following command:
```
time -v authelia crypto hash generate argon2 --iterations 1 --key-size 32 --memory 1024 --parallelism 4 --salt-size 16 --variant argon2id --password password
```

2. Observe output similar to this:
```
Digest: $argon2id$v=19$m=1024,t=1,p=4$YsLnlyVc5YLmRUqtvjm3JQ$hNphHxGeB2ANspT+RUbc5mUT8YJvYCmnuUUgwBeVbo0
        Command being timed: "authelia crypto hash generate argon2 --iterations 1 --key-size 32 --memory 1024 --parallelism 4 --salt-size 16 --variant argon2id --password password"
        User time (seconds): 0.05
        System time (seconds): 0.01
        Percent of CPU this job got: 126%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0m 0.05s
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 160736
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 8270
        Voluntary context switches: 353
        Involuntary context switches: 115
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

3. Run the following alternate command:
```
time -v authelia hash-password --iterations 1 --key-length 32 --memory 1024 --parallelism 4 --salt-length 16 -- password
```

4. Observe resulting output. In particular, note that the memory usage is now in the ~4GB range, and that the process took a lot longer to complete than in step 2.

```
Digest: $argon2id$v=19$m=1048576,t=1,p=4$SzLsq+XmS/8SH4oyaHUh4w$HaaS+8zmd2X8PH1UWEgZCs0j6m3nqV7Sct1Ok6bX/xM
        Command being timed: "authelia hash-password --iterations 1 --key-length 32 --memory 1024 --parallelism 4 --salt-length 16 -- password"
        User time (seconds): 1.15
        System time (seconds): 0.39
        Percent of CPU this job got: 184%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0m 0.84s
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 4488944
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 18192
        Voluntary context switches: 377
        Involuntary context switches: 6813
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

### Expectations

- The results of running the two commands described in the reproduction section should yield roughly the same results
- Using the configuration.yml snippet pasted below should yield results similar to those obtained via the `authelia crypto hash generate argon2` facility
- The default value for memory in the `authelia hash-password` facility should be more appropriate. Right now it's set to 65GB. Although without anchoring solutions, I believe this is a reasonable value if the `--memory` arg were changed from MB to KB

### Configuration (Authelia)

```yaml
...

authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /data/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: argon2id
      iterations: 150
      key_length: 32
      salt_length: 16
      memory: 4096
      parallelism: 4

...
```

### Logs (Authelia)

```shell
N/A
```

### Logs (Proxy / Application)

```shell
N/A
```

### Documentation

N/A

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
We'll fix this by removing the deprecated `hash-pasword` function. As far as the configuration it's not being changed as the correct configuration is [clearly documented](https://www.authelia.com/configuration/first-factor/file/).

**Comment by james-d-elliott** [comment]
Also for reference the logs _are not optional_.

**Comment by oliverpool** [comment]
I think you missed the `--memory 1024` flag in your reproducer:
```
docker run authelia/authelia:4.37.5 authelia hash-password --memory 1024 test
Digest: $argon2id$v=19$m=1048576,t=3,p=4$ETeatZKmYC7b547kc3OZSQ$7rDm8NsG/xgwxHi39okXxyAfBfWjvGNWAbAOgYVRhrU
```

```
docker run authelia/authelia:4.37.5 authelia crypto hash generate argon2 --memory 1024 --password test
Digest: $argon2id$v=19$m=1024,t=3,p=4$MVXpKRu2MYicY0Ndf63GJg$9i0cWeUhjYVNuc6mT1LlaKD+bRj61pDohDD1Sy4Eqzg
```
`$m=1048576` vs `$m=1024` looks suspicious.


Apparently the `hash-password`  was removed in e3e31e3cbc2a2c030dc51f7cd6a15ccdfc956873 (the day following the 4.37.5 release), this issue might not be relevant anymore :shrug:

**Comment by josef-dijon** [comment]
So if I understand correctly, `hash-password` has been removed, which results in the following changes.

4.37.5:
Memory config of 1024 invoked Argon with 1GB.
After 4.37.5: Argon is invoked with 1MB of memory with the same settings.

This doesn't seem great, since most users will see a silent loss of security when updating to the latest version. Or am I missing something?

**Comment by james-d-elliott** [comment]
The `--help` for hash password indicates that it's in MB, this is expected. This issue is being closed as invalid.

**Comment by josef-dijon** [comment]
Ok sure. But config file is supposed to be in KB isn't it?

It's currently (4.37.5) in MB.

**Comment by james-d-elliott** [comment]
No it isn't. Use the supported and documented configuration. I have linked it but you're not using it.

**Comment by josef-dijon** [comment]
So why then, if I set memory to 1024 in the config file does the Argon process consume GB of memory? As I described in the original report?

**Comment by james-d-elliott** [comment]
Because you are using an old configuration and not reading what I'm saying.

**Comment by james-d-elliott** [comment]
Or alternatively there may be old hashes which need to be rehashed to use the new setting.

**Comment by josef-dijon** [comment]
I think there's some miscommunication happening here. I have read your messages, and looked at the docs. All line up with the things in my report and your comments that `hash-password` has recently been deprecated, which fixes the bug where the config file was being read as MB and not as KB, as per the docs.

I'm only now trying to get acknowledgement that you've considered the fact that after your fix, users will silently have a 1024x drop in Argon hashing security.

**Comment by james-d-elliott** [comment]
> 4.37.5: Memory config of 1024 invoked Argon with 1GB. After 4.37.5: Argon is invoked with 1MB of memory with the same settings.
> 
> This doesn't seem great, since most users will see a silent loss of security when updating to the latest version. Or am I missing something?

Just saw this. This is inaccurate. The old configuration maps to the new values automatically if you're still using it. If you're using the new configuration and not the old it's in KB as defined in the spec.

**Comment by josef-dijon** [comment]
Also, you did say the configuration is not being changed, so I'm confused by what you by "old" and "new" configuration mapping.

**Comment by james-d-elliott** [comment]
Security related topics will be discussed in accordance with the security policy in the future, however it's not the case that there will be a drop in security. In your case it seems like the cost went up, not down.

As far as the change to configuration in 4.37.0 we added several additional algorithms, it made more sense to separate them, the configuration I linked is the up to date configuration and is in KB. The old configuration which was collapsed like you have it was in MB.

**Comment by josef-dijon** [comment]
Ok, thank you for clarifying.

I'm not concerned about my config, because I've done the relevant tests and tuned Argon as I described in the report. I'll do those tests again after I change to the new configuration.

In the future, if you want to get the best out of people, especially those that are clearly just trying to help, a little bit of kindness goes a long way :)

**Comment by james-d-elliott** [comment]
> In the future, if you want to get the best out of people, especially those that are clearly just trying to help, a little bit of kindness goes a long way :)

I can understand and agree with that. My irritation was based on what I in hindsight suspect was just a lack of awareness about our security policy. I'm sure in hindsight it's obvious why it was completely unclear about your intent to just help when you claimed to have read the security policy then seemed to blatantly disregard it from the outset.

**Comment by james-d-elliott** [comment]
Also for reference I apologize for my irritation, while it may be understandable I could have handled it better.

**Comment by oliverpool** [comment]
If I understand correctly, the following config is deprecated (and undocumented)

```yaml
    password: # deprecated, do not use !
      algorithm: argon2id
      iterations: 150
      key_length: 32
      salt_length: 16
      memory: 4096 # in MB
      parallelism: 4
```

it gets internally converted to the new config (which is properly documented):
```yaml
    password:
      algorithm: argon2
      argon2: # <- this key is important
        variant: argon2id
        iterations: 150
        memory: 4194304 # in KB
        parallelism: 4
        key_length: 32
        salt_length: 16
```

https://github.com/authelia/authelia/blob/v4.37.5/internal/configuration/validator/authentication.go#L301-L303

**Comment by james-d-elliott** [comment]
Mostly correct, The old deprecated config is documented just in older versions of the docs (i.e. not in your face).
