### ISSUE TITLE
2FA Push: Duo Enrollment

### ISSUE THREAD

**Issue by james-d-elliott** [authelia/authelia#594]
For consideration and investigation, duo self enrollment for Authelia would be a nice to have addition. Possibly worth considering side by side with #593 (allowing for one only in the config, not both). 

https://duo.com/docs/duoweb

**Comment by clems4ever** [comment]
Enrollment with Duo would be a nice to have indeed but note that I generally prefer keeping control over my data. So I use Duo more like a push notification enabler than my actual identity provider (which in my case is the AD integrated with Authelia).

**Comment by nightah** [comment]
I think the Enrollment process is the only piece of the puzzle that's missing to have a fully featured Duo integration.

Right now a user is likely created in the source LDAP and needs to be manually created in Duo and linked. By supporting Enrollment a user which previous has no notion of Duo for Push 2fa could easily select it as an authentication option and be created accordingly by Authelia.

The only issue I can see is potentially when more than 10 users are created in the free plan, but I suspect the API implementations will likely provide appropriate error messaging for these scenarios.

**Comment by james-d-elliott** [comment]
Our current lib supports it. https://github.com/duosecurity/duo_api_golang/blob/master/authapi/authapi.go#L130-L149
