### ISSUE TITLE
Authelia privacy_policy feature not working

### ISSUE THREAD

**Issue by tltglitch** [authelia/authelia#6031]
### Version

v4.37.5

### Deployment Method

Bare-metal

### Reverse Proxy

HAProxy

### Description

Cant seem to get the privacy policy link to work with authelia. Has this feature been removed ?

i am using the sample config file below:
https://github.com/authelia/authelia/blob/master/config.template.yml

### Reproduction

N/A

### Configuration (Authelia)

```yaml
privacy_policy:
  enabled: true
  policy_url: 'https://example.com/privacy'
```

### Build Information

```shell
N/A
```

### Logs (Authelia)

```shell
Sep 25 12:07:09 u systemd[1]: Started Authelia authentication and authorization server.
Sep 25 12:07:09 u authelia[169140]: time="2023-09-25T12:07:09-04:00" level=error msg="Configuration: configuration key not expected: privacy_policy.enabled"
Sep 25 12:07:09 u authelia[169140]: time="2023-09-25T12:07:09-04:00" level=error msg="Configuration: configuration key not expected: privacy_policy.policy_url"
Sep 25 12:07:09 u authelia[169140]: time="2023-09-25T12:07:09-04:00" level=fatal msg="Can't continue due to the errors loading the configuration"
Sep 25 12:07:09 u systemd[1]: authelia.service: Main process exited, code=exited, status=1/FAILURE
Sep 25 12:07:09 u systemd[1]: authelia.service: Failed with result 'exit-code'.
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
It doesn't exist in that version only master and the betas.
