### ISSUE TITLE
How to redirect back to my web app (nextcloud) after logged in authelia

### ISSUE THREAD

**Issue by Akruidenberg** [authelia/authelia#608]
I´ve been testing Authelia and it works very well. However, the only thing i don't get working is redirecting back to my web app after authentication. 

For testing I'm  using an file backend in place of an ldap server, with an sqlite3 database. Only redis is configured. I´m using Traefik 1.X as a proxy server. everything is working as aspected, the only thing is redirecting back to my web app.

There is not a lot of information available about this subject. Now after authlia is logged in with 2fa, it won't redirect me back to my web app. (for example nextcloud)

How to get this working with my configuration?

**Comment by clems4ever** [comment]
Hello, great you like it!

So I guess you had a look at the following configuration, right? https://github.com/authelia/authelia/blob/master/docs/proxies/traefik1.x.md

It's probable that your target URL gets considered as unsafe by the component performing open redirects protection. The criterion to consider an URL to be safe are: URL must have a https scheme (http is not allowed) and the sub domain of the URL must be part of the domain protected by Authelia (which is defined by the session.domain key in the config).

**Comment by Akruidenberg** [comment]
> Hello, great you like it!
> 
> So I guess you had a look at the following configuration, right? https://github.com/authelia/authelia/blob/master/docs/proxies/traefik1.x.md
> 
> It's probable that your target URL gets considered as unsafe by the component performing open redirects protection. The criterion to consider an URL to be safe are: URL must have a https scheme (http is not allowed) and the sub domain of the URL must be part of the domain protected by Authelia (which is defined by the session.domain key in the config).

Yes, i reallyt did look at the traefik instructions. I´m using traefik with some basic security headers.
I´m using docker labels for that. I´m using my own domain with a letsencrypt cert. Traefik is redirecting to https by default. 

Do you need more informaation for this sitiuation?

**Comment by Akruidenberg** [comment]
i´ve removed all my security header labels from my containers to test, bit it does not work.
also i´ve tried to set the defaultentrypoint in the traefik.toml file to https only. no progress. 
I dont know what to do next. Maybe its a bug? Also, the master tag of docker gave me the same results.

**Comment by nightah** [comment]
@Akruidenberg could you please share a redacted version of your Authelia and Traefik configuration both for your auth portal and the protected endpoint?

**Comment by Akruidenberg** [comment]
[config.txt](https://github.com/authelia/authelia/files/4143883/config.txt)
[docker-compose.txt](https://github.com/authelia/authelia/files/4143884/docker-compose.txt)
[traefik.txt](https://github.com/authelia/authelia/files/4143886/traefik.txt)

**Comment by Akruidenberg** [comment]
any help?

**Comment by nightah** [comment]
Line 49 of your docker-compose seems to have a single quote:
`traefik.frontend.auth.forward.address: http://authelia:9091/api/verify?rd=https://login.${DOMAINBASE}/'`

Can you try remove that? Also once you have done that for the sake of ensuring the correct label exists can you post an output of `docker inspect cloudcmd` please?

**Comment by Akruidenberg** [comment]
[test.txt](https://github.com/authelia/authelia/files/4152402/test.txt)

**Comment by nightah** [comment]
The quote is still there in the inspect you just posted, I assume that was before you made the change?

**Comment by Akruidenberg** [comment]
works without the quote. closed
