### ISSUE TITLE
SIGSEGV crash when passing a nonexistent secret file path through ENV variable 

### ISSUE THREAD

**Issue by sphakka** [authelia/authelia#6082]
### Version

v4.37.5

### Deployment Method

Bare-metal

### Reverse Proxy

NGINX

### Description

I stumbled upon this because of a misspelled file path.  It looks like authelia doesn't handle well ENV variables for secrets that point to nonexistent files and crashes with error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x55f3fc6a43a6]
goroutine 1 [running]:
   
   math/big.(*Int).BitLen(...)
           math/big/int.go:467
   crypto/rsa.(*PublicKey).Size(...)
           crypto/rsa/rsa.go:54
  ...
```
Indeed, it tries to digest an RSA key from a file without checking first if the fail exists! 

### Reproduction

With a valid, but possibly incomplete, config -- here I'm configuring OIDC
with the provided MWE below.

1. Prepare a valid RSA private key file `/etc/authelia/secrets/oidc.private.pem` to be pointed at by ENV var `AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE`.
1. Export the above variable with the correct path:
   ```bash
   $ export AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE=/etc/authelia/secrets/oidc.private.pem
   ```
1. Validate the MWE config (OK):
   ```bash
   $ authelia validate-config
   Configuration parsed and loaded with errors:
       - option 'jwt_secret' is required
   ...
   ```
1. Now, export the above variable with the wrong path:
   ```bash
   $ export AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE=/nonexistent/file
   ```
1. Validate the MWE config (KO):
   ```bash
   $ authelia validate-config
   panic: runtime error: invalid memory address or nil pointer dereference
   [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x560e5a8a43a6]

   goroutine 1 [running]:
   math/big.(*Int).BitLen(...)
           math/big/int.go:467
   crypto/rsa.(*PublicKey).Size(...)
           crypto/rsa/rsa.go:54
   github.com/authelia/authelia/v4/internal/configuration/validator.validateOIDC(0xc00037f930, 0xc000289620)
           github.com/authelia/authelia/v4/internal/configuration/validator/identity_providers.go:40 +0x2c6
   github.com/authelia/authelia/v4/internal/configuration/validator.ValidateIdentityProviders(...)
           github.com/authelia/authelia/v4/internal/configuration/validator/identity_providers.go:16
   github.com/authelia/authelia/v4/internal/configuration/validator.ValidateConfiguration(0xc000374d80, 0xc000289620)
           github.com/authelia/authelia/v4/internal/configuration/validator/configuration.go:66 +0x612
   github.com/authelia/authelia/v4/internal/commands.loadConfig({0xc00028c1f0, 0x1, 0x1}, 0x1, 0x1)
           github.com/authelia/authelia/v4/internal/commands/configuration.go:97 +0x189
   github.com/authelia/authelia/v4/internal/commands.cmdValidateConfigRunE(0xc0003e7200?, {0x560e5c7fe410?, 0x0?, 0x0?})
           github.com/authelia/authelia/v4/internal/commands/validate.go:38 +0x55
   github.com/spf13/cobra.(*Command).execute(0xc0003e7200, {0x560e5c7fe410, 0x0, 0x0})
           github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
   github.com/spf13/cobra.(*Command).ExecuteC(0xc000158000)
           github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
   github.com/spf13/cobra.(*Command).Execute(...)
           github.com/spf13/cobra@v1.6.1/command.go:968
   main.main()
       github.com/authelia/authelia/v4/cmd/authelia/main.go:10 +0x1e
   ```

### Expectations

Authelia should handle gracefully nonexistent file paths and, instead of panicking, raise a simple "file not found" error.

### Configuration (Authelia)

```yaml
# MWE
---
identity_providers:
  oidc:
    hmac_secret: secret
...
```

### Build Information

```shell
Last Tag: v4.37.5
State: tagged clean
Branch: v4.37.5
Commit: 566a0d7fc71b450123ad33d350cd3890d311da82
Build Number: 17068
Build OS: linux
Build Arch: amd64
Build Date: Wed, 21 Dec 2022 19:54:54 +1100
Extra:
```

### Logs (Authelia)

```shell
[n.a.]
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Thanks for reporting but this is a duplicate of #5138 which has already had a fix merged.
