### ISSUE TITLE
LDAP authentication users_filter always requires placeholder {username_attribute}

### ISSUE THREAD

**Issue by Zepmann** [authelia/authelia#6088]
### Version

v4.37.5

### Deployment Method

Other

### Reverse Proxy

HAProxy

### Reverse Proxy Version

2.8.3

### Description

Relevant configuration:
```
username_attribute: uid
users_filter: (&({mail_attribute}={input})(objectClass=person))
```

If `users-filter` has a value that does not contain `{username_attribute}`, Authelia refuses to run.

### Reproduction

Apply the relevant configuration.

Start Authelia with the relevant configuration.

### Expectations

It is expected that Authelia runs without issue if `users_filter` does not contain `{username_attribute}`.

Some LDAP servers (such as [lldap](https://github.com/lldap/lldap/blob/main/docs/migration_guides/v0.5.md#multiple-users-with-the-same-email)) use the `mail` attribute as a unique value that can only be used by a single record while still having a separate unique internal user identifier (`uid`). In a situation in which the user only uses their email address to authenticate, only the `mail` attribute should be part of the filter.

It is undesirable to set `username_attribute: mail`, since email addresses are expected to sometimes change (while still remaining unique). Usernames do (should) not change.

### Build Information

```shell
Last Tag: v4.37.5
State: tagged clean
Branch: v4.37.5
Commit: 566a0d7fc71b450123ad33d350cd3890d311da82
Build Number: 17068
Build OS: linux
Build Arch: amd64
Build Date: Wed, 21 Dec 2022 19:54:54 +1100
Extra:
```

### Logs (Authelia)

```shell
ERRO[0000] Configuration: authentication_backend: ldap: option 'users_filter' must contain the placeholder '{username_attribute}' but it is required
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Us having a strict requirement for something is not a bug, it's an intended feature. Feel free to use a filter which uses both the username and the mail attributes.
