### ISSUE TITLE
Protocols support state is unclear

### ISSUE THREAD

**Issue by phozzy** [authelia/authelia#615]
Hi!
It is not clear from documentation, or if there is a documentation about it then it is not easy to find, what types of protocols do you support:
* Auth0
* OpenIDC
* SAML
* other protocols?

It would be nice to document it.
Thanks!

**Comment by clems4ever** [comment]
Hello @phozzy , I'm not an expert in Auth0 but I think it is an OIDC provider and not a protocol, right?

So to answer the question no protocol is supported yet but OIDC is in my shortlist.
The only integration we have with a thirdparty is with Duo which is only used to provide the push notification feature and this is advertised in the README.

We'll add a mention about OIDC and SAML in the doc, thanks for the report.
