### ISSUE TITLE
Add support for Docker Registry authentication via Authelia

### ISSUE THREAD

**Issue by Ereaey** [authelia/authelia#6180]
### Description

I've encountered difficulties when attempting to integrate Docker Registry with Authelia for authentication. It seems there isn't a direct way to accomplish this based on the current Docker Registry documentation. Adding support or clear guidelines for this integration would benefit many users.

### Use Case

- Set up Docker Registry with standard configurations.
- Install and configure Authelia for authentication.
- Follow the procedure for token-based authentication as detailed [here](https://distribution.github.io/distribution/about/configuration/#token).
- Realize that the process requires a certificate which is not readily retrievable when using Authelia.
- Attempt other potential solutions or workarounds to integrate both services.
- Observe unsuccessful integration due to lack of clear guidelines or direct support.

### Details

Develop a clear mechanism or method within Authelia to retrieve the necessary certificate for Docker Registry integration.
Offer comprehensive documentation detailing the steps for successful integration, especially considering the certificate requirement.

### Documentation

https://distribution.github.io/distribution/about/configuration/#token

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Certificate retrieval is not related to Authelia, you or your proxy provision all certificates that authelia uses, we do not automatically generate any of them.

Regarding authentication this can already be done I believe via basic auth which is supported and the only mechanism docker actually supports. You will just need to rewrite the Authoization header from the client to Proxy-Authorization until 4.38 is released.

See #2023 for token based auth.

**Comment by jpbaril** [comment]
@Ereaey Did you succeed in using token-based auth for Docker registry?
If so, could you please share you configs ?

I read https://www.authelia.com/configuration/miscellaneous/server-endpoints-authz/ and https://www.authelia.com/reference/guides/proxy-authorization but not being a real sysadmin I'm pretty much lost without a tutorial or detailed example.

Thank you
