### ISSUE TITLE
Error when creating password with docker run

### ISSUE THREAD

**Issue by Akruidenberg** [authelia/authelia#619]
When i run this commands to create an hash password for my users_database file, the following error appeared:

**docker run authelia/authelia authelia hash-password yourpassword**

**docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"authelia1\": executable file not found in $PATH": unknown.**

How to fix this error?

**Comment by clems4ever** [comment]
It's an issue with PATH variable not including the directory containing authelia binary.
The following command works: `docker run authelia/authelia ./authelia hash-password yourpassword`.

I'll provide a fix to use an absolute path instead. Thank you for the report.
