### ISSUE TITLE
Listening on [::] even though host is set to 0.0.0.0

### ISSUE THREAD

**Issue by cinderblockgames** [authelia/authelia#6247]
### Version

v4.37.5, v4.37.4, v4.37.3

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Reverse Proxy Version

2.10.5

### Description

Despite setting `host` to `0.0.0.0`, Authelia is listening on `[::]`.

### Reproduction

```
##
## Server Configuration
##
server:

  ## The address to listen on.
  host: 0.0.0.0
```

### Build Information

```shell
Last Tag: v4.37.5
State: tagged clean
Branch: v4.37.5
Commit: 566a0d7fc71b450123ad33d350cd3890d311da82
Build Number: 17068
Build OS: linux
Build Arch: amd64
Build Date: Wed, 21 Dec 2022 19:54:54 +1100
Extra:
```

### Logs (Authelia)

```shell
time="2023-11-09T21:18:50Z" level=info msg="Authelia v4.37.5 is starting"
time="2023-11-09T21:18:50Z" level=info msg="Log severity set to debug"
time="2023-11-09T21:18:50Z" level=debug msg="Registering client immich with policy one_factor (one_factor)"
time="2023-11-09T21:18:50Z" level=info msg="Storage schema is being checked for updates"
time="2023-11-09T21:18:50Z" level=info msg="Storage schema is already up to date"
time="2023-11-09T21:18:52Z" level=debug msg="LDAP Supported OIDs. Control Types: 2.16.840.1.113730.3.4.9, 1.2.840.113556.1.4.473, 1.3.6.1.4.1.4203.1.9.1.1, 2.16.840.1.113730.3.4.5, 2.16.840.1.113730.3.4.4, 1.3.6.1.4.1.42.2.27.8.5.1, 2.16.840.1.113730.3.4.18, 2.16.840.1.113730.3.4.2, 1.3.6.1.4.1.4203.1.10.1, 1.3.6.1.1.22, 1.2.840.113556.1.4.319, 1.2.826.0.1.3344810.2.3, 1.3.6.1.1.13.2, 1.3.6.1.1.13.1, 1.3.6.1.1.12. Extensions: 1.3.6.1.4.1.1466.20037, 1.3.6.1.4.1.4203.1.11.1, 1.3.6.1.4.1.4203.1.11.3, 1.3.6.1.1.8"
time="2023-11-09T21:18:52Z" level=debug msg="notification provider: startup check skipped as it is disabled"
time="2023-11-09T21:18:52Z" level=debug msg="The NTP startup check was skipped due to there being no configured 2FA access control rules"
time="2023-11-09T21:18:52Z" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Thanks for reporting however this is unfortunately part of the go stdlib (see https://github.com/golang/go/issues/48723) and we're not going to put any effort into working around it without a reason, especially since it'd be a breaking change on our end. As no information on what adverse affects this has was included this issue is being closed as a wont-fix. 

Users may be able to work around this once 90d190121d538318ca2b1358f77b890a1cbe1b9d is released (though it's technically available in `v4.38.0-beta3`) using the new address syntax and specifying `tcp4` as the scheme.

**Comment by cinderblockgames** [comment]
Turns out, no adverse effect -- I was having an unrelated issue due to HAProxy that was causing some confounding.

**Comment by james-d-elliott** [comment]
Yeah as I just editted, listening on `[::]:9091` also listens on `0.0.0.0:9091`, I believe by standard but at least in golang.
