### ISSUE TITLE
Support translations

### ISSUE THREAD

**Issue by Akruidenberg** [authelia/authelia#625]
It would be nice if we can translate the login screen into multiple languages.

**Comment by clems4ever** [comment]
That's a valid point @Akruidenberg .

**Comment by clems4ever** [comment]
And in my opinion, the entire application should be translated, not only the login screen.

**Comment by james-d-elliott** [comment]
Maybe a solution: https://crowdin.com/

**Comment by james-d-elliott** [comment]
This was implemented by #2697
