### ISSUE TITLE
Budibase integration tutorial

### ISSUE THREAD

**Issue by felixcapuano** [authelia/authelia#6264]
### Description

Hello everyone!
I want to write a tutorial for OIDC integration with Budibase.
It's not very complicated but nice to have in the documentation.

### Use Case

😎 As a "no code buddy" want to integrate Budibase with Authelia authetication

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by felixcapuano** [comment]
#6265 let me know what you think

**Comment by james-d-elliott** [comment]
FR"s are for the authelia binary mostly. But we're happy to work with you on the PR.
