### ISSUE TITLE
Can't go over one factor authentication

### ISSUE THREAD

**Issue by blastbeng** [authelia/authelia#636]
Hi,
I've configured authelia using nginx reverse proxy by following this guide:

https://github.com/authelia/authelia/blob/master/docs/proxies/nginx.md

Authelia is working good, but the problem is that i can't go over the one factor authentication, I configured authelia as follow:

```
default_redirection_url: https://protected.myhost.com/
access_control:
  default_policy: deny

  rules:
    - domain: login.myhost.com
      policy: two_factor

    - domain: protected.myhost.com
      policy: two_factor
```

But when logging in using login.myhost.com i'm getting:

```
Feb 18 10:54:46 myhost.com systemd[1]: Started Authelia authentication and authorization server.
Feb 18 10:54:46 myhost.com authelia[457933]: time="2020-02-18T10:54:46+01:00" level=info msg="Logging severity set to debug"
Feb 18 10:54:46 myhost.com authelia[457933]: Selected public_html directory is  /usr/share/webapps/authelia
Feb 18 10:54:46 myhost.com authelia[457933]: time="2020-02-18T10:54:46+01:00" level=info msg="Authelia is listening on 0.0.0.0:9197"
Feb 18 11:03:10 myhost.com authelia[457933]: time="2020-02-18T11:03:10+01:00" level=debug msg="Credentials validation of user myuser is ok" method=POST path=/api/firstfactor remote_ip=xx.xx.xx.xx
Feb 18 11:03:10 myhost.com authelia[457933]: time="2020-02-18T11:03:10+01:00" level=debug msg="Mark authentication attempt made by user myuser" method=POST path=/api/firstfactor remote_ip=xx.xx.xx.xx
```

And logging from protected.myhost.com results in:

```
Feb 18 11:07:37 myhost.com authelia[457933]: time="2020-02-18T11:07:37+01:00" level=debug msg="Credentials validation of user myuser is ok" method=POST path=/api/firstfactor remote_ip=xx.xx.xx.xx
Feb 18 11:07:37 myhost.com authelia[457933]: time="2020-02-18T11:07:37+01:00" level=debug msg="Mark authentication attempt made by user myuser" method=POST path=/api/firstfactor remote_ip=xx.xx.xx.xx
Feb 18 11:07:37 myhost.com authelia[457933]: time="2020-02-18T11:07:37+01:00" level=debug msg="Required level for the URL https://protected.myhost.com/ is 2" method=POST path=/api/firstfactor remote_ip=xx.xx.xx.xx
Feb 18 11:07:37 myhost.com authelia[457933]: time="2020-02-18T11:07:37+01:00" level=warning msg="https://phpmyadmin.myhost.com/ requires more than 1FA, cannot be redirected to" method=POST path=/api/firstfactor remote_ip=xx.xx.xx.xx
```

So I imagine that the problem is that I can't figure out how to add the 2Fa authentication in authelia since I cannot even login at login.myhost.com.... 
I have authelia running on 0.0.0.0:9197 and accessing via 127.0.0.1:9197 or externalip:9197 results in the same as accessing from login.myhost.com, the login is successful but I don't get redirected to anything

Where is the problem inside my configuration?

If you need, I can also attach the full authelia config, I'm not using DUO api, i want to use google authenticator

**Comment by nightah** [comment]
Please post your full Authelia configuration along with the Authelia and nginx logs for when you visit the protected endpoint and authenticate.

**Comment by blastbeng** [comment]
Sorry, i think i solved this, the problem was that i still had this in my config

`  # The domain to protect.
  # Note: the authenticator must also be in that domain. If empty, the cookie
# is restricted to the subdomain of the issuer.
  domain: example.com`

changing to myhost.com worked
