### ISSUE TITLE
Support Symlink Files for TLS Certificates

### ISSUE THREAD

**Issue by Junto026** [authelia/authelia#6438]
### Description

I use certbot to renew SSL certificates.  With each renewal, certbot dumps the new cert files into an /archive directory with new file names, but updates a symlink file to always point to the most recent.  

So for example, /archive/fullchain1.pem could be the certificate, and the /live/fullchain.pem file will be a symlink which points to the file in /archive.  When the certificate is renewed, the new certificate will be /archive/fullchain2.pem and the /live/fullchain.pem symlink will be updated to point to the new file.

Authelia throws an error if you try to configure the /live/fullchain.pem symlink file as the certificate file.  The exact error is:

time="2023-12-19T10:22:08-05:00" level=error msg="Error occurred waiting for shutdown" error="unable to load tls server certificate '/letsencrypt/live/fullchain.pem' or private key '/letsencrypt/live/privkey.pem': cannot load TLS key pair from certFile=\"/letsencrypt/live/fullchain.pem\" and keyFile=\"/letsencrypt/live/privkey.pem\": tls: private key does not match public key" stack="github.com/authelia/authelia/v4/internal/commands/root.go:201 runServices\ngithub.com/authelia/authelia/v4/internal/commands/root.go:89  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  main\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_arm64.s:1172                                      goexit"

### Use Case

Be able to use symlink files for server tls certificate configuration.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Authelia already supports this, you'll find the same error if you unlink the files. 

Please try with `cert.pem`.

**Comment by Junto026** [comment]
You're right.  It's even working with the fullchain.pem now.  I don't know what was wrong before but apparently it wasn't the symlink.  Thx for your responsiveness as always!

**Comment by Junto026** [comment]
You're right. It's even working with the fullchain.pem now. I don't know what was wrong before but apparently it wasn't the symlink. Thx for your responsiveness as always!

**Comment by james-d-elliott** [comment]
The key modulus and/or public exponent did not match between the private and public keys with the two files provided meaning they were not a matching set. That's the cause of an error like this.

**Comment by Junto026** [comment]
I saw that but couldn’t figure out how that could be. 

It happened again today and it turns out a background file sync operation must be modifying those files in some way.  It seems to mess up the symlinks but not the actual certificate files…I’ve disabled that sync  and haven’t had issues since.
