### ISSUE TITLE
Duo Push - No Logging When Duo Has no Matching User

### ISSUE THREAD

**Issue by kevdogg** [authelia/authelia#650]
I'm a little new to Authelia so I'm probably configuring something wrong.

I registered for new account on Duo.  The name associated with the duo account is the same name that I use to authenticate with Authelia.  I'm using however a users.yml file for authentication -- and not LDAP.

After creating Duo Account and choosing Applications->Partner Auth API, I received three credentials 
1. Integration Key
2. Secret Key
3. API Hostname

I'm using authelia:latest docker image controlled with docker-compose.
To the configuration.yml file I've added:
duo_api:
  hostname: <hostname from #3 above>
  integration_key: <Integration Key from #1 above>
  secret_key: <Secret Key from #2 above>

I'm getting this error however with the authelia portal 
<img width="1397" alt="Screen Shot 2020-02-26 at 12 07 05 PM" src="https://user-images.githubusercontent.com/5242583/75374554-20fad380-5892-11ea-840f-739807477402.png">

Not sure how to address problems.  I looked in nginx athelia access and error log files, but didn't see anything mentioned in the log.  Log level is info. 

Thanks for any help.

**Comment by clems4ever** [comment]
Hello @kevdogg , we'll need more information to be able to help you. Can you first tell whether you get the error instantaneously when you're redirected to second factor or do you get it after a certain amount of time?

We'll also need the logs of a failed authentication in `debug` mode to help you further.

**Comment by kevdogg** [comment]
Thanks for quick response.
Error occurs immediately or instantaneously.
Ive changed to debug mode in the configuration.yml file and restarted container - however where are the pertinent log files?

docker logs authelia (doesn't show any relevance)
docker -it authelia /bin/sh --> no logs in container at /var/log
/var/log/ngninx --> no logs updated for authelia.access.log or authelia.error.log

**Comment by clems4ever** [comment]
Logs are sent to stdout so `docker logs` should give you something, at least one sentence showing that Authelia starts listening.

**Comment by kevdogg** [comment]
Here are the logs after restarting the container and then trying to select the Push Notification option
(I'm not sure they help)

```
# docker logs authelia
time="2020-02-26T14:27:35-06:00" level=info msg="Logging severity set to debug"
time="2020-02-26T14:27:35-06:00" level=debug msg="Notifier SMTP client initializing TLS configuration"
Selected public_html directory is  ./public_html
time="2020-02-26T14:27:35-06:00" level=info msg="Authelia is listening on 0.0.0.0:8080"
time="2020-02-26T14:27:51-06:00" level=error msg="Access to https://bw.<domain>.com/admin is not authorized to user " method=GET path=/api/verify remote_ip=10.0.1.185 stack="github.com/authelia/authelia@/internal/handlers/handler_verify.go:264     VerifyGet\ngithub.com/authelia/authelia@/internal/middlewares/authelia_context.go:46 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v0.5.2/router.go:326                           (*Router).Handler\ngithub.com/valyala/fasthttp@v1.6.0/header.go:123                          (*ResponseHeader).StatusCode\ngithub.com/valyala/fasthttp@v1.6.0/server.go:2018                         (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.6.0/workerpool.go:223                      (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.6.0/workerpool.go:195                      (*workerPool).getCh.func1\nruntime/asm_amd64.s:1357                                                  goexit"
time="2020-02-26T14:27:56-06:00" level=debug msg="Credentials validation of user kevdog is ok" method=POST path=/api/firstfactor remote_ip=10.0.1.185
time="2020-02-26T14:27:56-06:00" level=debug msg="Mark authentication attempt made by user kevdog" method=POST path=/api/firstfactor remote_ip=10.0.1.185
time="2020-02-26T14:27:56-06:00" level=debug msg="Required level for the URL https://bw.<domain>.com/admin is 2" method=POST path=/api/firstfactor remote_ip=10.0.1.185
time="2020-02-26T14:27:56-06:00" level=warning msg="https://bw.<domain>.com/admin requires more than 1FA, cannot be redirected to" method=POST path=/api/firstfactor remote_ip=10.0.1.185
time="2020-02-26T14:28:00-06:00" level=debug msg="Save new preferred 2FA method of user kevdog to mobile_push" method=POST path=/api/user/info/2fa_method remote_ip=10.0.1.185
```

**Comment by clems4ever** [comment]
There should be an error message in the log when authentication with push notification fails. If it's not the case it probably means the request does not even make it to Authelia.

Can you check the browser console to see if there is an error message when authentication fails? Can you also retry the authentication with `trace` level so that we know for sure whether the request arrives to Authelia.

**Comment by kevdogg** [comment]
Logs with trace didn't reveal anything new unfortunately.

Browser console however revealed:

<img width="550" alt="Screen Shot 2020-02-26 at 3 13 44 PM" src="https://user-images.githubusercontent.com/5242583/75388549-cfab0e00-58aa-11ea-8e57-a11cec20a38c.png">

**Comment by james-d-elliott** [comment]
@kevdogg 401 is a HTTP unauthorized. Can you add the authelia.example.com domain to the top of your access_control: rules: section with the policy of bypass (where example.com is your domain)?

Example:

`
access_control:
  default_policy: deny
  rules:
      - domain: 'authelia.example.com'
        policy: bypass
`

**Comment by kevdogg** [comment]
@james-d-elliott 
Ok I added that to my configuration.yml file, however same error in the browser console. No difference I can see. I'm still getting the 401 error -- I get almost immediately when selecting the push notification option on the main authelia site.

**Comment by james-d-elliott** [comment]
Okay we figured it out on the support chat. The issue was there was no individual user setup in DUO. The problem is we don't generate logs from this. The docs do cover this but not very clearly. 

To replicate change your user in DUO so your name cannot be matched. It will not return any detailed log messages.

I propose the following @clems4ever  @nightah:
1. More logging
2. Step by step process for DUO setups

**Comment by nightah** [comment]
I think the more logging makes perfect sense.

I believe but have not confirmed, Duo should be providing us something meaningful back in the request we make that in turn fails.

Short of this it might make more sense for us to look a a proper enrolment process for Duo that way if a user cannot be matched the person in question will be prompted to set it up.
