### ISSUE TITLE
Sessions are no longer encrypted in session storage in v4

### ISSUE THREAD

**Issue by clems4ever** [authelia/authelia#652]
I found out that sessions are no longer encrypted in v4.

**Comment by james-d-elliott** [comment]
Can confirm with redis.

**Comment by james-d-elliott** [comment]
Looks like fasthttp/sessions doesn't support it out of the box. Only supports MessagePack and Base64.

https://github.com/fasthttp/session/blob/master/encrypt.go

**Comment by clems4ever** [comment]
Indeed, we can certainly override the methods to add encryption easily.
