### ISSUE TITLE
Request timeout occurred while handling request from client

### ISSUE THREAD

**Issue by VeloAddict** [authelia/authelia#6577]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

NGINX Proxy Manager

### Reverse Proxy Version

2.11.1

### Description

If i open open the containers directly http://ip:port it works fast.
If i remove Authelia from NPM and access the container via domain https://my.domain.com it works fast.
If i add back Authelia config to NPM it times out.
It used to work fine but since updated to docker 25 it started to be slow and timeout.

Output from logs:

```
time="2024-01-21T16:31:04Z" level=error msg="Request timeout occurred while handling request from client." error="read tcp 172.17.0.3:9091->172.17.0.1:43038: i/o timeout" method=GET path=/ remote_ip=172.17.0.1 stack="github.com/authelia/authelia/v4/internal/server/handlers.go:71 handleError.func2\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2824             (*Server).writeErrorResponse\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2266             (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224          (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196          (*workerPool).getCh.func1\nruntime/asm_arm64.s:1172                                       goexit" status_code=408
```

### Reproduction

Running in docker with nginx proxy manager.

### Build Information

```shell
Last Tag: v4.37.5
State: tagged clean
Branch: v4.37.5
Commit: 566a0d7fc71b450123ad33d350cd3890d311da82
Build Number: 17068
Build OS: linux
Build Arch: arm64
Build Date: Wed, 21 Dec 2022 19:54:54 +1100
Extra:
```

### Logs (Authelia)

```shell
time="2024-01-21T16:31:04Z" level=error msg="Request timeout occurred while handling request from client." error="read tcp 172.17.0.3:9091->172.17.0.1:43038: i/o timeout" method=GET path=/ remote_ip=172.17.0.1 stack="github.com/authelia/authelia/v4/internal/server/handlers.go:71 handleError.func2\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2824             (*Server).writeErrorResponse\ngithub.com/valyala/fasthttp@v1.43.0/server.go:2266             (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:224          (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.43.0/workerpool.go:196          (*workerPool).getCh.func1\nruntime/asm_arm64.s:1172                                       goexit" status_code=408
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
I can't replicate this and the bug report has not been completed correctly (missing the complete logs). In addition as you mentioned it was working fine, you didn't change anything on the authelia side only on docker. It' more likely a configuration issue there so we'd be happy to provide support in a [discussion](https://github.com/authelia/authelia/discussions/new/choose).

**Comment by james-d-elliott** [comment]
We'll be happy to provide support in a discussion as previously mentioned.
