### ISSUE TITLE
Smart Card Authentication

### ISSUE THREAD

**Issue by lyzstrik** [authelia/authelia#6607]
### Description

I would like to propose the addition of smart card authentication functionality to Authelia. Currently, Authelia offers robust authentication options, but integrating smart card authentication would add an extra layer of security for users while maintaining a simple and user-friendly experience.

### Use Case

- Enable users to securely authenticate using compatible smart cards.
- Seamless integration with Authelia's existing authentication flow.
- Provide a user-friendly solution, even for non-technical users.
- Increase the level of security.
- Associate a smart card with a user account.
- PKI management.
- Add Certificate Revocation List (CRL) management.
- Smart card management with LDAP.

### Details

I would like to propose the addition of smart card authentication functionality to Authelia. Currently, Authelia offers robust authentication options, but integrating smart card authentication would add an extra layer of security for users while maintaining a simple and user-friendly experience. The use of smart card authentication has become a standard security practice in many professional environments. This method provides a dual-layer of protection by combining something the user knows (the smart card PIN) with something they possess (the smart card itself). This significantly reduces the risks associated with password loss or inadvertent disclosure.

I am prepared to develop the necessary module to support this functionality. However, I don't know if they already have plugins or modules that already accomplish this. Thank you for guiding me.

Adding smart card authentication would enhance Authelia's security while offering a user-friendly solution. I am open to any suggestions or further guidance to successfully implement this proposal.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
How would Authelia communicate with the Smart Cards?

**Comment by james-d-elliott** [comment]
I think this could do with some links to documentation on the relevant libs and/or APIs that could be leveraged to prove it's possible in this scenario. In particular we'd need a javascript or web request based go library that retrieves the proof of possession so that we could use the go backend to verify it. 

I'd also be interested in the proof method used with smart cards as I am not entirely familiar, assuming it's similar to WebAuthn where the smart cards private key is used to sign an opaque challenge.

**Comment by BryanJacobs** [comment]
The easiest way to use a smart card for web authentication today is to put https://github.com/BryanJacobs/FIDO2Applet/ on the card and use it as a passkey.

The second-easiest way is to put a PIV applet on it and have it do TLS client authentication (mTLS) with a web server. If Authelia is acting as the web server it could capture the client certificate; if not, the web server itself could pass down a header.

Personally, I think FIDO2 is a better overall user experience than PIV, but PIV is more powerful in terms of centralized features (such as key revocation and delegated CAs).

I'm not sure what the compelling advantage for the user is here though, to be honest.

**Comment by james-d-elliott** [comment]
Yeah I think I agree with that. Rather than reinventing the wheel I think these options are very standard. If someone wants to implement a mTLS solution like this then we'd welcome it. An existing FR exists for Passkeys and they're likely to be added soon.
