### ISSUE TITLE
Provide endpoint to force reload of database from users_database.yml after editing

### ISSUE THREAD

**Issue by adrw** [authelia/authelia#6617]
### Description

Provide an endpoint that a service could call to force reloading of the users_database.yml into the running Authelia service.

### Use Case

My application currently reads and writes to the users_database.yml when a new user signs up but there's no way to tell Authelia about the change. Currently I end up having to restart the Docker container which leads to downtime on each user signup. If there's an endpoint to force refresh then the service could stay running.

Alternatively, a non-LDAP, non-YAML authentication backend would be preferable but is more work. For example, a standard JSON REST API that an application could implement which Authelia would use to query user authentication information.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Authelia will automatically reload it if you enable the [watch](https://www.authelia.com/configuration/first-factor/file/#watch) option. Adding an API for this is not really something we'd be likely to do before adding an admin UI and a method to authenticate administrators.

**Comment by adrw** [comment]
Perfect, I think watch will work! Thanks!
