### ISSUE TITLE
Add uuid from LDAP that Authelia provides in the HEADERS (like Remote-User)

### ISSUE THREAD

**Issue by olaxe** [authelia/authelia#6634]
### Description

I would like to have another field from the LDAP authentication (UUID) in Authelia variable so I can setup Nginx to have it in the headers.

### Use Case

I can manage a change of login for my users. 
Easier to respect PII (Personally identifiable information) when I need to comply with user request to remove its personal data (GDPR).
The goal is to use this uuid and not the log as the main ID for web apps.
In order to achieve that, it will be easier if Authelia can provide a variable so I can setup in the Nginx RP:
proxy_set_header Remote-Uuid $uuid;

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
We can add it but it's still personally identifiable information under the GDPR if that data links to a natural person (see their note about identification numbers) equal to the username. 

We'd just need examples of such attributes. Obviously in Active Directory the ObjectGUID field.

**Comment by olaxe** [comment]
It sounded better in my head. I meant I can keep UUID (a little longer) for extra processing after data anonymization of all PII fields before complete deletion.

I propose the same principle as for other fields: (reference: https://www.authelia.com/configuration/first-factor/ldap/)
extra_attribute: <if not declared, not used and if declared the variable become available for Nginx or any RP)

So an Active Directory config can also configure its own field if he needs it

**Comment by james-d-elliott** [comment]
Going to close this and make it part of: https://github.com/authelia/authelia/issues/2868

Idea being people can just arbitrarily decide which attributes are mapped where.
