### ISSUE TITLE
Properly support listening on Unix socket + using a non-`/` router path

### ISSUE THREAD

**Issue by fghzxm** [authelia/authelia#6689]
### Description

**Note:** This issue is filed against Authelia version `untagged-v4.37.5 (v4.38.0-beta3, 5d1fe75)`.

When Authelia is configured to listen on a Unix domain socket, using the configuration syntax
```yaml
server:
  address: 'unix:///path/to/socket.sock'
```
there's no way to also specify a UI router path that Authelia should accept in addition to `/`. For example, if I wanted to let Authelia accept the router path `/auth` (so that I can navigate to `https://my-domain.example.com/auth/` to see the login portal), I can't simply set
```yaml
server:
  # this won't work
  address: 'unix:///path/to/socket.sock/auth'
```
because that would instead mean I want Authelia to listen on the Unix socket `/path/to/socket.sock/auth`.

The current behavior is that, when `address` is set to `unix:///path/to/socket.sock`, Authelia takes `/path/to/socket.sock` to be the Unix socket address _and_ an additional router path. This means I can technically achieve my goal by setting
```yaml
server:
  address: 'unix:///auth'
```
but most people who're looking to use Unix sockets probably don't want to be forced to put their sockets under `/`.

### Use Case

Both Unix sockets and non-`/` router paths have their respective use cases which are orthogonal, and the use cases of this feature are their intersection.

### Details

I can think of two ways to solve this problem:
- undeprecate the `server.path` configuration, or
- iterate over over `session.cookies.*.authelia_url` and automatically infer additional router paths.

In either case, the functionality to specify an additional router path in `server.address` should probably be reverted.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
https://github.com/authelia/authelia/discussions/categories/pre-release-feedback

**Comment by fghzxm** [comment]
Hey, you could've at least pointed me to https://github.com/authelia/authelia/discussions/6460 and told me it's already in master :)
________________________________

**Comment by james-d-elliott** [comment]
We have an official feedback process for the beta which has been clearly communicated in every location we've invited users to join in the beta. It's quite disappointing that some users can't follow these instructions when we put all this effort into involving the community in this process. 

It's especially disappointing and discouraging when a user then is able to find what they think they're looking for with a simple search and make a snide comment about it, or when they quite clearly know they're reporting a bug but avoid doing so open a FR instead to avoid providing minimal helpful information.

We want users to report issues but in a way that's actually constructive, helpful, and time efficient. You may want to consider all of this carefully in future interactions with the community, I hope you do at least.

**Comment by fghzxm** [comment]
Hi James,

I'm very sorry for upsetting you. I've been using beta versions of Authelia for a while, but I didn't join the Matrix channel or the Discord server, so I was quite out of touch with the wider community. Previously whenever I had a difficulty configuring Authelia, I was able to find the answer by searching GitHub issues, and I didn't know that beta feedback is reported using a different GitHub feature (discussion) from that used by release and master feedback.

I'll remember to first get in touch on Matrix the next time I provide feedback.

As for my previous comment, I'm terribly sorry if it came off as rude to you. English is not my first language, and I'm not the best communicator even in my native language. I've had incidents where I spoke something in English in what I presumed to be an informal tone and ended up being perceived as offensive. I'll remember to err on the side of being formal the next time I talk to the community.

I hope I can repair my relationship with the community and clean up any misunderstandings.

Fred
________________________________

**Comment by james-d-elliott** [comment]
There are additional avenues for feedback. I linked one of them (which also includes all of the important information including warnings about the storage database, breaking changes, etc), and all advertisements of the beta include a link to the feedback discussion forum and alternative ways to provide feedback.

**Comment by james-d-elliott** [comment]
Regarding tone that makes sense the way you explain it. No worries about repairing with the community, I was just a bit irritated and I don't hold grudges. My issue was mainly that a few people seem to have not read or not following the feedback instructions even though each avenue of advertisement lists it. It also appeared like you were avoiding giving bug report information using a feature request but that could just be a misunderstanding. No hard feelings and hope I didn't come over rude either. 

The feedback forum I linked is also appropriate. for discussing the beta
