### ISSUE TITLE
Make Redis configurable via `address` instead of `host` + `port` too

### ISSUE THREAD

**Issue by georglauterbach** [authelia/authelia#6708]
### Description

The database can be configured via the `address` field, which allows for the address common syntax. I noticed Redis is not yet configurable this way.

### Use Case

I see an awful lot of

```ini
[INFO] <AUTHELIA IP>:46014 - 49024 "AAAA IN redis.authentication.svc.cluster. udp 61 false 1232" NOERROR qr,aa,rd 124 0.000151221s
```

in my coreDNS logs, as Authelia tries to get the `AAAA` record (why it does that, I am not 100% sure). Then I looked into the configuration, and saw that Redis still uses `host` + `port`, which means I cannot set `tcp4://`.

### Details

N/A

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
We plan to do this as part of the session rework see #6174.

**Comment by georglauterbach** [comment]
Ah, that's why I didn't find an existing issue; I was searching for Redis in the issue tracker only. Nice!

**Comment by james-d-elliott** [comment]
Yeah it wasn't redis specific. But I want to do one change rather than two. Specifically I'd like to split the concept of sessions and the cache where redis or such can be reused.
