### ISSUE TITLE
Allow different OIDC clients to use different group policies or ldap users_filter

### ISSUE THREAD

**Issue by rexzhang** [authelia/authelia#6740]
### Description

I tried using ACL to achieve similar functionality, unsuccessfully

### Use Case

We have:
- user:u1/u2/u3
- group: g1(u1+u2)/g2(u2+u3)
- app1/app2

want to:
- Allow only users under g1 to use app1（g2‘s user to use app2)
- All apps use *OpenID Connect* with ldap

### Details

if passible: add a parameter `ldap_users_filter`/`allow_groups` into `identity_providers.oidc.clients[]`

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
#2621
