### ISSUE TITLE
I18n: add spanish translation for `settings` namespace

### ISSUE THREAD

**Issue by mind-ar** [authelia/authelia#6745]
### Description

Add spanish translation for `settings` namespace added in 4.38

### Use Case

spanish translation

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by hendrik1120** [comment]
@james-d-elliott I think this issue has been resolved by #6966

**Comment by james-d-elliott** [comment]
Thanks @hendrik1120, closed by 39b228b9d75755787789f2d9eb309a35f188f1dc
