### ISSUE TITLE
Issue running standalone server on osx 10.15.3 (catalina)

### ISSUE THREAD

**Issue by harperaa** [authelia/authelia#681]
Using latest source files from this time (3/2/20).  Using source bootstrap.sh then 
$ authelia-scripts suites setup Standalone

Several notes on gitter page...working with Amir on this, he suggested I file an issue.

Building nginx-backend
Step 1/3 : FROM nginx:alpine
---> 48c8a7c47625
Step 2/3 : ADD html /usr/share/nginx/html
---> c5036c8fb47d
Step 3/3 : ADD nginx.conf /etc/nginx/nginx.conf
---> 6270b1f089a2
Successfully built 6270b1f089a2
Successfully tagged authelia_nginx-backend:latest
Creating authelia_authelia-frontend_1 ... done
Creating authelia_authelia-backend_1 ... done
Creating authelia_nginx-portal_1 ... done
Creating authelia_smtp_1 ... done
Creating authelia_nginx-backend_1 ... done
.........................................Timeout of 300s reached... Killing process...

here is log from frontend

Allens-Mac:authelia allenharper$ docker logs -f authelia_authelia-frontend_1
yarn install --frozen-lockfile
yarn install v1.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.0.7: The platform "linux" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > react-ga@2.7.0" has unmet peer dependency "prop-types@^15.6.0".
warning " > react-loading@2.0.3" has unmet peer dependency "prop-types@^15.6.0".
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/app/node_modules/postcss-flexbugs-fixes/bugs/'".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by harperaa** [comment]
(authelia) Allens-Mac:authelia allenharper$ docker -v
Docker version 19.03.5, build 633a0ea
(authelia) Allens-Mac:authelia allenharper$ go version
go version go1.14 darwin/amd64
(authelia) Allens-Mac:authelia allenharper$

**Comment by nightah** [comment]
I'll see if I can have a look tonight to determine what the issue is with OSX deployments, the normalising of the UID/GID may be a little to simple to actually allow this.

I have a pretty old Macbook so assuming I can get everything to work on there we should have a way forward to get this to work with OSX in general.

**Comment by nightah** [comment]
@harperaa I do recall that we actually resolved the issue for your deployment method.

We have now also introduced docker compose bundles to allow quick deployment into new environments.
