### ISSUE TITLE
Lite example has an error in it - see notes

### ISSUE THREAD

**Issue by HeneryH** [authelia/authelia#6812]
### Version

v4.37.5

### Deployment Method

Docker

### Reverse Proxy

Traefik

### Description

The forward auth in the Lite example is
`      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/authz/forward-auth?authelia_url=https://authelia.example.com'  # yamllint disable-line rule:line-length`
which does not work, searching showed me
`      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.${FQDN}'  # yamllint disable-line rule:line-length`
which does work

### Reproduction

x

### Build Information

```shell
x
```

### Logs (Authelia)

```shell
x
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Please use the examples relevant to the version you're using (see tag v4.37.5), please don't report mistakes in the documentation here, and always include the required information in the future it's not optional.

**Comment by HeneryH** [comment]
OK, never mind then.  Leave the error.

**Comment by james-d-elliott** [comment]
It's not an error.

**Comment by james-d-elliott** [comment]
The example for 4.37.5 quite clearly is correct: https://github.com/authelia/authelia/blob/v4.37.5/examples/compose/lite/docker-compose.yml
