### ISSUE TITLE
Encrypt TOTP secrets and identity verification tokens stored in DB

### ISSUE THREAD

**Issue by clems4ever** [authelia/authelia#682]
TOTP secrets and Identity Verifications tokens are currently stored in plain text in the database. They should be stored encrypted for adding an extra layer of security to protect against exfiltration of the DB or part of it.

Stealing identity verification tokens has a lower probability compared to TOTP secrets as the attacker could only steal the ones issued for less than 15 minutes since they expire after that time. Moreover those operations (reset password and register a device) are rather rare in common scenarii. A successful attack could lead the attacker to register a new device or reset a password. In both cases, such an attack would break one of the 2-factors so this could lead the attacker to get access to single_factor-protected endpoints. In the worst case, a user has issued both tokens in a short period of time and the attacker could then get access to 2FA-protected endpoints.

TOTP secrets on the other hand are static and don't expire. Therefore, a successful indirect attack on the DB could compromise the security of users relying on TOTP as the attacker could then generate one-time passwords as if she is the actual user. It's still an attack on only the second factor but the various scenarii listed above also applies here and could lead to an attack giving access to 2FA-protected endpoints.

I suggest we store those 2 fields encrypted using AES in DB.

**Comment by davama** [comment]
@clems4ever 

Could this be an option setting?

**Comment by clems4ever** [comment]
It can but why would you need it? Do you read those tokens from DB?

**Comment by davama** [comment]
> Do you read those tokens from DB?

....yes

To update google auth tokens on personal files, for ssh 2fa

**Comment by clems4ever** [comment]
So it's just because it's not displayed in the UI at the end of the enrollment, right?
In v4, only the QRCode is displayed. What if the secret was also displayed as it was in v3?

**Comment by davama** [comment]
I see what you are saying.

At least right now, we access the db and simply compare if the secret has changed. If it has then update the google auth file secret token.

Displaying on the webpage im assuming is once, the moment user clicks on the email link. Because then the session expires. So not sure how one could automate that


Im sure im a one off here 😓

**Comment by nightah** [comment]
> > Do you read those tokens from DB?
> 
> ....yes
> 
> To update google auth tokens on personal files, for ssh 2fa

So this wouldn’t actually be an issue if we provided a PAM module to interface with Authelia.

**Comment by clems4ever** [comment]
@davama , I see your problem, you're synchronizing the secret between two systems, gotcha. @nightah , yes now I remember the discussions around PAM.

So, @davama , in the meantime even if this secret is encrypted in DB you can keep your current workflow but decrypt the key in your tool with the encryption key before writing to your file. No big deal, it should be doable with a bit of bash or any language you use for your sync tool.

**Comment by davama** [comment]
> So this wouldn’t actually be an issue if we provided a PAM module to interface with Authelia.

yes!

> So, @davama , in the meantime even if this secret is encrypted in DB you can keep your current workflow but decrypt the key in your tool with the encryption key before writing to your file. No big deal, it should be doable with a bit of bash or any language you use for your sync tool.

Agreed!

Thank you both!

**Comment by james-d-elliott** [comment]
I think this is dependent on #913 as we need to do this to efficiently determine if we need to encrypt existing data.

**Comment by james-d-elliott** [comment]
@davama I'm working on this now. I can relatively easily provide a command that will export this data. I was thinking the best way to do this would be exporting it as a CSV or otpauth format.

So for example:

```
# authelia storage export totp-configurations--format uri

otpauth://totp/Authelia:johndoe?secret=HXDMVJECJJWSRB3HWIZR4IFUGFTMXBOZ&issuer=Authelia&algorithm=SHA1&digits=6&period=30

# authelia storage export totp-configurations --format csv
issuer,username,algorithm,digits,period,secret
Authelia,johndoe,SHA1,6,30,HXDMVJECJJWSRB3HWIZR4IFUGFTMXBOZ
```

Where `Authelia` is the totp issuer config option, johndoe is the username, and  the rest is the configuration from the DB.

**Comment by james-d-elliott** [comment]
Side note, while the PAM module would be nice, this will make it easy for you to export it. Also the encryption algorithm we use is fairly well documented, we create a sha256 sum of the encryption key, and use that for AES-GCM 256bit encryption.

**Comment by davama** [comment]
@james-d-elliott 
Just got around to trying your export feature and it’s fantastic!!
Thank you thank you thank you

for future googlers

```
authelia storage totp export --mysql.password blableeblue -c /etc/authelia/configuration.yml  --format csv
```

**Comment by james-d-elliott** [comment]
Check this change out if interested: https://github.com/authelia/authelia/pull/2673

Also yes we will be doing some work documenting the CLI.
