### ISSUE TITLE
Access Denied Page

### ISSUE THREAD

**Issue by jmhauer** [authelia/authelia#683]
Is there a way to show a special 'Access Denied Page' if a user tries to reach a domain he isn't allowed to access?
In my case the user is redirected to the _Hi user_ page after he succesfully logs in. There you are asked if you want to register a new device for security key or One-Time Password. I think some users may be confused because they are asked to register a new device for two factor authentication even if there is no two factor authentication required.

**Comment by clems4ever** [comment]
Hello @jmhauer , can you give more information on the authentication scenario? I need at least the target URL and the URL of the portal (scheme included). The access_control part of the configuration would be useful too.

**Comment by jmhauer** [comment]
I try to access test-app.test-id.example.com, the login page is login.test-id.example.com.
If no user is logged in and I try to reach test-app.test-id.example.com, I am redirected to the login page. This works fine. After the login was successfull (with a user that is not allowed to access test-app.test-id.example.com) I am redirected to https://login.test-id.example.com/2fa/one-time-password?rd=https%3A%2F%2Ftest-app.test-id.example.com%2F (This is the same page, that is shown if I just login at the login page, without trying to reach a protected page before)
And there is no indication for the user, that he is not allowed to access the original page (test-app.test-id.example.com).

the access control parts looks like:
```
access_control:
    default_policy: deny
    rules:
    - domain: "test-app.test-id.example.com"
      subject: "group:test"
      policy: one_factor
```

**Comment by clems4ever** [comment]
Hello @jmhauer , there is indeed a small issue. The problem is here: https://github.com/authelia/authelia/blob/0dea0fc82ebab1276fd671a7570f627ba3dc3113/internal/handlers/response.go#L14.

We should test the highest level of all rules instead of just testing the default policy. I'll provide a fix.
