### ISSUE TITLE
Authelia failing to start because of GLIBC dips

### ISSUE THREAD

**Issue by adpavlov** [authelia/authelia#6892]
### Version

v4.38.1

### Deployment Method

Bare-metal

### Reverse Proxy

NGINX

### Description

```
/usr/bin/authelia-linux-amd64 version
/usr/bin/authelia-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/authelia-linux-amd64)
/usr/bin/authelia-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/authelia-linux-amd64)
/usr/bin/authelia-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/authelia-linux-amd64)
```

glibc-2.28-251.el8.x86_64 installed in system.
Seems like similar to #2475 BTW, the latest working version for GLIBC < 2.28 is v4.36.6

### Reproduction

install latest version

### Build Information

```shell
not working
```

### Logs (Authelia)

```shell
not created
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by adpavlov** [comment]
Rhel8. It’s not a big deal to use older version of authelia, but is there any requirement file for dependencies?

**Comment by nightah** [comment]
The glibc version that we build changes with our [crossbuild container](https://github.com/authelia/crossbuild/blob/master/Dockerfile#L1).

You should be able to run `ldd /path/to/authelia` to see any dynamically linked libraries that are necessary.

**Comment by js94x** [comment]
I do experience the same problem after updating to Authelia 4.38.x on Ubuntu 20.04 (Debian package version is 4.38.2-1)

At first I downgraded to the latest 4.37 version, but I think the incompatibility should be mentioned somewhere.

```
$ /usr/bin/authelia --config /etc/authelia/configuration.yml
/usr/bin/authelia: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/authelia)
/usr/bin/authelia: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/authelia)
/usr/bin/authelia: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/authelia)

$ ldd /usr/bin/authelia
/usr/bin/authelia: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/authelia)
/usr/bin/authelia: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/authelia)
/usr/bin/authelia: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/authelia)
	linux-vdso.so.1 (0x00007ffd059c1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7d85349000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7d88759000)

$ dpkg -l | grep libc
...
ii  libc-bin                         2.31-0ubuntu9.14                           amd64        GNU C Library: Binaries
ii  libc-dev-bin                     2.31-0ubuntu9.14                           amd64        GNU C Library: Development binaries
ii  libc6:amd64                      2.31-0ubuntu9.14                           amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64                  2.31-0ubuntu9.14                           amd64        GNU C Library: Development Libraries and Header Files
...
```

Compared to 4.37.x:
```
$ apt install authelia=4.37.5-1

$ ldd /usr/bin/authelia 
	linux-vdso.so.1 (0x00007ffc9e9fe000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f94127b2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f94127ac000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f94125ba000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f94155f3000)
```

**Comment by nightah** [comment]
We have just updated our build tooling to support what is considered `oldstable` in Debian and Ubuntu.

This will be built with glibc 2.31 and will land in Authelia v4.38.4. Hopefully to be released tonight.

**Comment by adpavlov** [comment]
> We have just updated our build tooling to support what is considered `oldstable` in Debian and Ubuntu.
> 
> This will be built with glibc 2.31 and will land in Authelia v4.38.4. Hopefully to be released tonight.

Unfortunately it doesn't cover RHEL8 which under RH support till 2029 at least

**Comment by james-d-elliott** [comment]
Thanks for letting us know, unfortunately we can't build binaries for every OS especially with our focus on security and we have to draw the line somewhere. There are options available to you however. Authelia can run in a docker container which I'm sure RHEL8 supports, it can be built from source (maybe RHEL support will do this for you I'm not sure), or you can update to a release with a newish glibc version. 

Looking at most major distros which offer support and security patches the oldest version that's widely supported is 2.35 though it's not unreasonable for us to support 2.34 for RHEL9 (which is just over 4 years old). It is however unreasonable to support 2.28 which is nearly 8 years old.

We currently build from 2.36 which supports back to 2.34 at minimum, RHEL9 supports this with 2.34.
