### ISSUE TITLE
Update from v4.37.5 to v4.38 fails 

### ISSUE THREAD

**Issue by budimanjojo** [authelia/authelia#6941]
### Version

v4.38.4

### Deployment Method

Kubernetes

### Reverse Proxy

NGINX

### Description

Updating to v4.38.0 to v4.38.4 all fails with this error: `error="error during schema migrate: failed to commit the transaction with: commit error: unexpected EOF`

I really don't know what's the problem here. I also have made sure to fix all the configuration key changes to get rid of the warnings (all the "configuration key xxx is deprecated in 4.38.0") and still get the same errors.

### Reproduction

This is my configuration.yaml file: https://github.com/budimanjojo/home-cluster/blob/57dbfe07cc702bb7569567b1bc694298bbd99a7b/cluster/apps/authentication-system/authelia/base/config/configuration.yaml

### Build Information

```shell
Last Tag: v4.38.4
State: tagged clean
Branch: v4.38.4
Commit: 1ea41b80d3a44e30d299acf04e6e18afd3836455
Build Number: 27782
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Mon, 18 Mar 2024 23:09:30 +1100
Extra:
```

### Logs (Authelia)

```shell
time="2024-03-18T21:27:45+07:00" level=info msg="Authelia v4.38.4 is starting"
time="2024-03-18T21:27:45+07:00" level=info msg="Log severity set to debug"
time="2024-03-18T21:27:45+07:00" level=debug msg="Registering client proxmox with policy two_factor (two_factor)"
time="2024-03-18T21:27:45+07:00" level=debug msg="Registering client minio with policy two_factor (two_factor)"
time="2024-03-18T21:27:45+07:00" level=debug msg="Registering client nextcloud with policy two_factor (two_factor)"
time="2024-03-18T21:27:45+07:00" level=debug msg="Registering client immich with policy two_factor (two_factor)"
time="2024-03-18T21:27:45+07:00" level=info msg="Storage schema is being checked for updates"
time="2024-03-18T21:27:45+07:00" level=info msg="Storage schema migration from 7 to 15 is being attempted"
time="2024-03-18T21:27:45+07:00" level=debug msg="Storage schema migrated from version 7 to 8"
time="2024-03-18T21:27:45+07:00" level=debug msg="Storage schema migrated from version 8 to 9"
time="2024-03-18T21:27:45+07:00" level=debug msg="Storage schema migrated from version 9 to 10"
time="2024-03-18T21:27:45+07:00" level=debug msg="Storage schema migrated from version 10 to 11"
time="2024-03-18T21:27:45+07:00" level=debug msg="Storage schema migrated from version 11 to 12"
time="2024-03-18T21:27:45+07:00" level=debug msg="Storage schema migrated from version 12 to 13"
time="2024-03-18T21:27:45+07:00" level=debug msg="Storage schema migrated from version 13 to 14"
time="2024-03-18T21:27:45+07:00" level=debug msg="Storage schema migrated from version 14 to 15"
time="2024-03-18T21:27:45+07:00" level=info msg="Storage schema migration from 7 to 15 is complete"
time="2024-03-18T21:28:55+07:00" level=error msg="Error occurred running a startup check" error="error during schema migrate: failed to commit the transaction with: commit error: unexpected EOF, rollback error: sql: transaction has already been committed or rolled back" provider=storage stack="github.com/authelia/authelia/v4/internal/commands/root.go:107 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.0/command.go:983                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.0/command.go:1115                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.0/command.go:1039                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
time="2024-03-18T21:28:55+07:00" level=debug msg="LDAP Supported OIDs. Control Types: none. Extensions: 1.3.6.1.4.1.4203.1.11.1"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
What postgres version are you using?

**Comment by budimanjojo** [comment]
@james-d-elliott I think I managed to get the problem now, thanks for the hint about postgres log.
The problem occurs because of having `shared_preload_libraries: vectors.so` in my postgres cluster (because I shared database between `immich` and `authelia`).

I'm closing this issue, sorry for the false alert.

**Comment by james-d-elliott** [comment]
All good glad you fixed it! Was definitely a weird log sequence
