### ISSUE TITLE
wrong error message for old config of "host" value

### ISSUE THREAD

**Issue by tribor** [authelia/authelia#7016]
### Version

v4.38.6, v4.37.2

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Description

"logs_file" instead of "host"

- configuration key 'logs_file' is deprecated in 4.30.0 and has been replaced by 'server.host': this has been automatically mapped for you but you will need to adjust your configuration to remove this message

### Reproduction

in configuration.yaml ```host: 0.0.0.0```

### Expectations

...configuration key 'host' is deprecated...

### Build Information

```shell
Last Tag: v4.37.2
State: tagged clean
Branch: v4.37.2
Commit: ab742a6e90c350cbe242204df92320e1c44f1c38
Build Number: 15573
Build OS: linux
Build Arch: amd64
Build Date: Fri, 28 Oct 2022 21:29:24 +1100
Extra:
```

### Logs (Authelia)

```shell
see above
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
I can't replicate this in 4.38.6. I get the below log message.

```
configuration key 'host' is deprecated in 4.30.0 and has been replaced by 'server.host': you are not required to make any changes as this has been automatically mapped for you, but to stop this warning being logged you will need to adjust your configuration, and this configuration key and auto-mapping is likely to be removed in 5.0.0
```
