### ISSUE TITLE
My user filter is no longer possible in authelia v4.7.0

### ISSUE THREAD

**Issue by naggie** [authelia/authelia#735]
In my configuration, previously I had:

`users_filter: "(|(samaccountname={0})(mail={0}))"`

This is so users can log in with their username or email address; this turned out to be necessary after users kept failing to log in with the wrong one.

With v4.7.0 it seems that only one username attribute is supported with `username_attribute`.

Is there any way that I can still support this query or is a change necessary?

Out of curiosity, why was this change made?

Thanks!
Callan

**Comment by nightah** [comment]
It was changed due to #561.

Because the username is the primary key in SQL this would mean that both the username and email will essentially be known to Authelia as two different users for totp secrets etc.

There could likely be an option to enable UPN logins like AD, but it would definitely require a change, contributions are definitely welcome.

**Comment by naggie** [comment]
ok -- I think I'll switch to supporting just the username part again with an explanatory message, as the side affects seem like more effort. Thanks.

**Comment by naggie** [comment]
I ended up writing a bit of javascript to normalise the username entered such that it does not include our corporate domains. Note event triggering required for react:

```
setInterval(function() {
    var input = document.getElementById("username-textfield");

    if (!input) {
        return;
    }

    var value = input.value.replace("@example.com","");

    // trigger existing react stuff
    // https://stackoverflow.com/questions/23892547/what-is-the-best-way-to-trigger-onchange-event-in-react-js#46012210
    var nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, "value").set;
    nativeInputValueSetter.call(input, value);

    var event = new Event('input', { bubbles: true});
    input.dispatchEvent(event);
}, 200);

```
It's a hack so if anyone else has the same problem, note it may fail as authelia is updated.

**Comment by james-d-elliott** [comment]
Thanks for the hack @naggie. I am thinking the idea I had to automatically include it in the filter was a oversight in this particular use case, the reason for it was to simplify things. I might add a boolean type to the config to either disable the automatic rule or to switch the logical AND to a logical OR, I think the first option is perferable. Thoughts?

**Comment by james-d-elliott** [comment]
You can try out option one with this docker image: authelia/authelia:regression-ldap-user-filter

You will need to set something like this for your example:

```
username_attribute: sAMAccountName
users_filter: "(|(sAMAccountName={0})(mail={0}))"
disable_auto_users_filter: true
```

```
username_attribute: sAMAccountName
users_filter: "(|({1}={0})(mail={0}))"
disable_auto_users_filter: true
```

**Comment by naggie** [comment]
It seems the `username_attribute` used to look up the username from the LDAP response which clears up any ambiguity from grabbing it from the form.

I think that having the original method in combination with the `username_attribute` could work well -- as far as I can see there's no reason why the original filter method with a more complex query can't be used, so long as we use `username_attribute` to fish out the intended username.

A disadvantage is a small amount of redundancy but I think that's fine considering the benefits.

**Comment by nightah** [comment]
@naggie please upgrade `v4.10.0` and have a look at the [docs](https://docs.authelia.com/configuration/authentication/ldap.html)/[config template](https://github.com/authelia/authelia/blob/5fc3b26cf5b2aa53e55eb4b1156450f57807b8de/config.template.yml#L95-L108) for the new syntax.

Please let us know if you continue to have any issues.

**Comment by naggie** [comment]
The new syntax + mechanism is ideal and works great, thank you!
