### ISSUE TITLE
INACCURATE DOCS: Docs claim `AUTHELIA_TOPT_DISABLE`  environment variable is valid

### ISSUE THREAD

**Issue by MrChadMWood** [authelia/authelia#7607]
### Version

v4.38.9

### Deployment Method

Docker

### Reverse Proxy

Caddy

### Description

[Documentation](https://www.authelia.com/configuration/methods/environment/) claims `AUTHELIA_TOPT_DISABLE`  environment variable is valid.
But this issue states that it is invalid: https://github.com/authelia/authelia/issues/7606

From the docs:
![image](https://github.com/user-attachments/assets/fc182c02-e7fe-4f25-bfb3-22650f4e85b0)

### Reproduction

1. Try following docs
2. Create issue once it does not work
3. See issue get closed because it is invalid, get no response.

### Build Information

```shell
Last Tag: v4.38.9
State: tagged clean
Branch: v4.38.9
Commit: 2798576ee25a56fd4c14814acd087b6e92f3978b
Build Number: 30034
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Sun, 16 Jun 2024 19:47:16 +1000
Extra:

Go:
    Version: go1.22.2
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2024-07-30T21:22:25Z" level=warning msg="Configuration: configuration environment variable not expected: AUTHELIA_TOPT_DISABLE"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
This is a support question. The docs do not contain `AUTHELIA_TOPT_DISABLE ` anywhere including in your screenshot.

**Comment by james-d-elliott** [comment]
Please only report bugs with the Authelia application itself. Issues which match one of the following criteria should not be reported here (for the purpose of keeping the issue tracking clear and concise) but should be a [discussion](https://github.com/authelia/authelia/discussions/new/choose) instead:

    Bugs with third-party software.
    Mistakes in the documentation (which should be reported via the [Documentation Feedback](https://github.com/authelia/authelia/discussions/new?category=documentation-feedback) discussions).
    Potential bugs where it is not somewhat clear that it's a bug with Authelia itself, a third party, or a misunderstanding/assumption about functionality.

**Comment by james-d-elliott** [comment]
Apologies I was exhausted and irritable, use `AUTHELIA_TOTP_DISABLE` like it shows in the docs.

**Comment by MrChadMWood** [comment]
No problem, we’re all human. I can do better about reviewing my own typing. To be honest, I was more or less just upset that I could not apologize for my own sass once the thread got locked. All is good hopefully. Have a great day.

**Comment by james-d-elliott** [comment]
Likewise!
