### ISSUE TITLE
SSO - Point in the right direction?

### ISSUE THREAD

**Issue by timothydlister** [authelia/authelia#763]
Hey everyone,

So I've been very excited about learning Authelia and finally have it working with Traefik, LDAP, and Let's Encrypt. Thank you everyone that's contributed documentation.

If I'm understanding the features correctly, Authelia can provide SSO against protected applications? My hope is that once users get through 2FA that their LDAP creds can be automatically passed through to protected applications that are also integrated with LDAP to the same directory.  Is this correct? Is there any documentation or something someone would recommend I learn/read on this topic?

It seems like this is where options like "authRequestHeaders and "authResponseHeaders" come into play.

My hope is setup SSO against things like GitLab, WikiJS, etc.

Thank you kindly for any pointers.

**Comment by timothydlister** [comment]
Shoot. That didn't take long for me to figure out. Looks like Oauth is what I want, or an IDM. I think I figured this and doesn't seem like the right place to be posting this question anyway. Thanks!

**Comment by nightah** [comment]
@timothydlister that could be OAuth/OpenID or SAML there's actually a couple different ways to implement this.

It's definitely on our roadmap and there's open issues for these things: #189 #493.

**Comment by timothydlister** [comment]
@nightah thanks for the response! I'm definitely just starting to learn about these components.
