### ISSUE TITLE
Create a change password workflow

### ISSUE THREAD

**Issue by rajivmordani** [authelia/authelia#7638]
### Description

Need ability to change a password when you know the old password.

### Use Case

User knows old password and has to rotate that. Need to have a change password in addition to reset password.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
Duplicate #3548
