### ISSUE TITLE
Relying party support for OIDC

### ISSUE THREAD

**Issue by rajivmordani** [authelia/authelia#7639]
### Description

Need to be able to support "login with google" use case with Authelia OIDC.

### Use Case

Need to support other OIDC / OAuth2 providers other than using just Authelia as the OIDC provider.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
#2728
