### ISSUE TITLE
Add inspect menu to totp credentials in user settings 

### ISSUE THREAD

**Issue by Crowley723** [authelia/authelia#7660]
### Description

Add "details" menu to totp credentials, similar to webauthn credentials.

### Use Case

#7650 
> Creation time/last used time doesn't need to be very specific, having the exact date and time when a credential was created/used isn't a super big issue. [isn't super helpful]
> For webauthn credentials, users still have the ability to see the exact date and time by inspecting the credential.

I think that it might be worth adding an inspect menu for the totp credentials as well, this would allow us to hide the algorithm type, digits, and time interval as well as give users the ability to see the long form date of when their credential was created.

I don't think people need to have immediate access to totp digital count, algorithm, and time interval and it clutters the widget. Additionally, users can have only one totp credential so (currently) there is no benefit to being able to distinguish between multiple (via digits, algorithm, interval)

This should be a fairly straightforward change.

### Details

Move 
- long form created date
- long form last used date
- totp digit count
- totp algorithm 
- totp time interval
- created by user(?)
- times used(?)
- any other relevant information
Into a info dialog similar to the webauthn credentials

This would help minimize clutter on the widget.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by Crowley723** [comment]
Might be a good first issue.

**Comment by james-d-elliott** [comment]
SGTM, can push it through as a ux fix if you ask me.
