### ISSUE TITLE
Configurable TOTP Window Size

### ISSUE THREAD

**Issue by zjzeit** [authelia/authelia#768]
I have a TOTP device ([Protectimus Slim Mini](https://www.protectimus.com/protectimus-slim-mini/)) but the problem is the clock on the device has skewed just outside the boundaries defined by the TOTP spec. Is it possible to set a configurable `window` size value as an option in `configuration.yml` to increase the window size of acceptable TOTP values?

In this case, `window` is defined as the number of 60-second intervals the TOTP value is accepted and passes authentication.

I did this in Authelia v3 by modifying the `WINDOW:` value in the file `./server/src/lib/authentication/totp/TotpHandler.js`

I am using the docker image authelia/authelia:4.8.0

**Comment by james-d-elliott** [comment]
@zjzeit I am implementing an example of this until we decide how this is best implemented, feel free to try it, but expect the functionality to change in the future. Docker image is: authelia/authelia:feature-topt-tuning

See here for the config example: https://github.com/authelia/authelia/blob/feature-topt-tuning/config.template.yml#L38-L45

**Comment by james-d-elliott** [comment]
This has been released in 4.9.0. Enjoy @zjzeit

Here are the docs. I'd recommend changing skew to 2 in your case it will allow for up to 60+ seconds in either direction. https://docs.authelia.com/configuration/one-time-password.html

**Comment by zjzeit** [comment]
Thank you for the quick resolution!
