### ISSUE TITLE
configuration.yml validation

### ISSUE THREAD

**Issue by ZyanKLee** [authelia/authelia#776]
**User-Story**
As an admin of an authelia installation using CI/CD mechanics, I would like to validate configuration files to be valid before they are deployed.

**Problem**
In v4.7.0 `logs_level` got renamed to `log_level` - yamllint for example does not know about config key names, so this change would have slipped through the safety net when dependabot or renovate the docker image version in a docker-compose.yml.

**Solution**
During the CI steps of linting various file types, I would like to add another step to verify the config file to be valid on a more thorough level, to avoid breaking changes to the config file slipping through by accident.

A subcommand / tool that knows about available configuration parameters can be used to validate if the config is still valid with the new version.

**Examples**
* prometheus promtool: https://github.com/prometheus/prometheus/tree/master/cmd/promtool
* CloudFormation Linter: https://github.com/aws-cloudformation/cfn-python-lint

**Comment by james-d-elliott** [comment]
@ZyanKLee Thanks for the nicely formatted issue. This is something I've been thinking about but have not had the time to research yet. A lot of the libraries we use have untapped functionality that can often solve problems like this easily.

Considering authelia already has tools to upgrade from v3, and we've made a few config changes lately it makes sense to implement something like this.

**Comment by clems4ever** [comment]
So just to be sure we're on the same page @ZyanKLee , when an invalid keys appear, Authelia should just fail when starting which is enough to detect an issue in CI, if it's not the case, it's a bug. Regarding, `logs_level` becoming `log_level` and still be valid, it's a problem with Viper not throwing on unexpected keys in the yaml.

I had a quick look to the library and it seems we cannot provide an option to throw on unexpected keys. I'll have a more thorough look and create an issue on their side if I don't find a way. In the meantime, we'll see if we can do something about it on our side.

**Comment by ZyanKLee** [comment]
@james-d-elliott + @clems4ever thanks for your answers.
starting authelia in CI systems might not always be feasible, as required resources like ldap / active directory servers and other "exeternal" stuff might not be available. So having a "script" that compares the config file with a schema of "allowed" or implemented configuration parameters would be beneficial in those cases.

**Comment by nightah** [comment]
@ZyanKLee while an alternative is being investigated, have you perhaps tried just `diff`ing the config in your CI to determine if any keys have changed? Generally speaking if you store the config template and replace the template with the new one issued you'll be able to quickly identify any new configuration parameters along with any changes to existing keys.

Having said that, we do announce all of these changes in the [release notes](https://github.com/authelia/authelia/releases) and [BREAKING.md](https://github.com/authelia/authelia/blob/master/BREAKING.md), admittedly there have been a few more breaking changes recently but we're hoping to try and reduce disruption as much as possible in future.

**Comment by ZyanKLee** [comment]
Don't worry, I had no trouble with the recent config key change. I just thought this would be a nice feature addition.

**Comment by nightah** [comment]
Ah of course, perhaps I misunderstood the issue.

It’s definitely something we will look into per the previous comments :).

**Comment by james-d-elliott** [comment]
@ZyanKLee this is implemented for testing if you'd like. Can check it out with the following links:

Docs: https://github.com/authelia/authelia/blob/config-key-validation/docs/configuration/index.md#validation
Artifacts: https://buildkite.com/authelia/authelia/builds/1503
Docker Image: authelia/authelia:config-key-validation

**Comment by ZyanKLee** [comment]
Hey @james-d-elliott , thanks for the great work on this request. I just tested the docker image with our configuration and I'm really happy about it.
Especially the fact that the validator detected missing LDAP passwords and other secrets which we provide via env variables was a great discovery.

**Comment by james-d-elliott** [comment]
Keep in mind if you run the validator without those currently in your ENV it wont work (you can safely ignore them if you know they are planned for ENV). Also File based secrets is coming in the same release. ENV secrets are being removed in a future version. If you need help converting once 4.15 is out, there will be information in the docs, or we can help.

**Comment by james-d-elliott** [comment]
Release 4.15.0 has been committed and is currently being deployed (should be available in 20 mins). It includes this feature, and a linked PR DRAFT has been opened to remove the old ENV types in 4.18.0 for which you can comment if you feel it's a mistake.

@ZyanKLee
