### ISSUE TITLE
ldap auth fails

### ISSUE THREAD

**Issue by miquelangeld** [authelia/authelia#784]
Hi, I installed authelia using this document https://github.com/authelia/authelia/wiki/npm-and-Fail2Ban
I configured LDAP to use our active directory, but the authentication fails. I sniffed some traffic and I don't understand whats going on:
The first bind is for the user that we use to get access to the active directory
bindRequest(1) "CN=LDAP,CN=Managed Service Accounts,DC=test,DC=local" simple 
The response is OK
bindResponse(1) success 
Then:
searchRequest(2) "ou=HEadquarter, ou=Users dc=test, dc=local" wholeSubtree 
which is the OU that I specified in additional_users_dn
But the response is weird 
searchResEntry(2) "CN=anotheruser,OU=Oficina Central,OU=Usuarios,DC=gb,DC=local"  | searchResDone(2) sizeLimitExceeded  [1 result]
which is another user, not the one that I used in the form.

In the log i get this:
message='Reply with error 200: Size Limit Exceeded'

**Comment by miquelangeld** [comment]
Seems that the problem was with the users_filter now I'm getting another this error
error: Error with input userTest. Cause:TypeError: Cannot read property 'indexOf' of undefined
error: date='Thu Mar 26 2020 15:03:17 GMT+0000 (UTC)' method='POST', path='/api/firstfactor' requestId='d7257f33-21d4-4a5d-8e63-303305ff8a3e' sessionId='AWkieIdOjafesYjQ7msYYO1zui66QMEv' ip='10.255.255.17' message='Reply with error 200: Special character used in LDAP query.'

**Comment by nightah** [comment]
@miquelangeld thanks for pointing that out the references for those wiki articles.
That is actually for v3 deployment and has been phased out.

Can I please suggest that you follow https://docs.authelia.com/getting-started.html to install Authelia and any associated issues are lodged in reference to a v4 deployment.

https://docs.authelia.com/ should provide all the necessary information for you to configure based on the type of deployment that you choose.

If you have any questions please don't hesitate to reach out.

**Comment by nightah** [comment]
@miquelangeld have you had any luck with this?

If you need assistance with v4 please don't hesitate to jump on [Matrix](https://riot.im/app/#/room/#authelia:matrix.org).

**Comment by clems4ever** [comment]
Hello @miquelangeld , any news? I'm closing this issue since it's not really actionable at the moment but do not hesitate to come back to us on Matrix or via a new Github issue if you're struggling setting up Authelia v4.

**Comment by miquelangeld** [comment]
Thanks and sorry for the delay in my answer. I will try with v4. Thanks for your help, and i will jump to MAtrix for further help-
