### ISSUE TITLE
Add "developer" config directly to the container

### ISSUE THREAD

**Issue by CyborTronik** [authelia/authelia#7880]
### Description

Trying to run authelia locally in a docker setup for development, and got a few issues with it:

1. Too much setup and configs just to get it up
2. (the most important) Locally I have no domain, and the trick is that for development often need to access it in 2 ways: from localhost *can do port binding, and from docker network *usually is done by hostname.

### Use Case

* Run a docker instance with min config for dev integrations (ideally everything with some defaults)
* Access the docker instance by hostname and localhost (via port binding), so no strict domain name

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by Crowley723** [comment]
What is it your trying to achieve?


Authelia has a pretty nice development environment. You can take a look [here if you're interested](https://www.authelia.com/contributing/development/environment/)

**Comment by Crowley723** [comment]
You could probably achieve what you want by creating a testing suite. Those are self-contained test environments. Done correctly, you can configure tests for them, and it will run them for you.

**Comment by CyborTronik** [comment]
Currently is less usable in a test environment due to the complex setup and additional files that need to be defined. It doesn't mean not possible, it means you should learn and stress about a test/dev container, exactly like a production thing. The idea of this request is to improve the UX for developers, when they can quickly do their thing, be happy about it, and use more authelia after that in other environments due to pleasant experience. It helps with promotion among developers.

**Comment by james-d-elliott** [comment]
> So the idea would be that I run the app and the auth service in an automatic way and the app can access the auth on the docker network, while I'm trying to access the auth endpoints locally (in IDE) to get the JWT for app requests

This is already possible. You can configure Authelia for any specific test scenario you'd like as long as it uses HTTPS, including on localhost or a port combination.

We provide several "test" configurations in the examples/compose directories. The lite compose example could be considered a minimal setup. 

We also provide internal/suites where you could look at one of the simpler suites like the two factor, one factor only, standalone, multi cookie domain, or oidc suites. We can't provide a configuration for every single scenario but several example setups exist. The suites are exactly what we utilize to perform our comprehensive integration testing. Each of the suite_*.go files represents a list of test environments which use `login.example.com:8080` as the root URL of authelia.

Can you please be specific about what change to the authelia code would facilitate this abstract idea.

**Comment by CyborTronik** [comment]
I was wondering if it could be as simple as:
"""
  auth:
    image: quay.io/keycloak/keycloak:21.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080
    command: start-dev 
"""
And it seems that I cannot use it for now anyway due to incomplete OAuth support.

**Comment by james-d-elliott** [comment]
Apologies but I don't believe at this time such a thing fits with the base design model of Authelia. All of the configuration is static, so the benefits of something like this are very minimal. 

That being said, as we provide means to configure Authelia from an administration UI this idea may make more sense, so I'll move this appropriately in a few days. However for security reasons and spec compliance reasons we'll never support implicit session or oauth2 redirect domains.

> And it seems that I cannot use it for now anyway due to incomplete OAuth support.

This is very vague and for that reason seems kind of unprofessional. There are nearly 100 OAuth specs. As far as I'm aware we 100% support the OAuth 2.0 Authorization Server role with the current best security practices.

**Comment by james-d-elliott** [comment]
I'm closing this as the request is very abstract and isn't clear in nature.
