### ISSUE TITLE
SMTP -  SMTP AUTH failed: unexpected server response username:

### ISSUE THREAD

**Issue by shifouhaiyaocuoguoyigeyewan** [authelia/authelia#8006]
### Version

v4.38.10

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Reverse Proxy Version

1.24.0

### Description

I'm trying to set up Authelia's smtp config with the custom mail server but I'm getting the error in Authelia.
The error:
msg="Error occurred running a startup check" error="failed to dial connection: SMTP AUTH failed: unexpected server response: username:"

### Reproduction

configure Authelia to use custom mail server(smtp.aliyun-inc.com MX AliMail Server) as the smtp notifier

### Expectations

The startup check should pass nearly instantly and authelia should successfully start.

### Configuration (Authelia)

```yaml
notifier:

  disable_startup_check: false

  smtp:

    address: 'submissions://smtp.example.com:465'

    timeout: '10s'

    username: 'example@example.biz'

    password: 'example'

    sender: '统一身份认证 <example@example.biz>'

    identifier: 'Office248'

    subject: '[统一身份认证] {title}'

    disable_require_tls: false

    disable_html_emails: false

    disable_starttls: false

    tls:
      server_name: 'smtp.example.com'
      skip_verify: false
      minimum_version: 'TLS1.2'
      maximum_version: 'TLS1.3'
```

### Build Information

```shell
Last Tag: v4.38.10
State: tagged clean
Branch: v4.38.10
Commit: b7d5e3ff29917bd0842c8509b4a8338d19f2934e
Build Number: 31324
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Wen, 09 Oct 2024 07:07:41 +1000
Extra: 

Go:
    Version: go1.23.1
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2024-10-09T07:09:56Z" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml]" filters="[]"
time="2024-10-09T07:09:56Z" level=debug msg="Logging Initialized" fields.level=debug file= format= keep_stdout=false
time="2024-10-09T07:09:56Z" level=debug msg="Process user information" gid=0 gids="1,2,3,4,6,10,11,20,26,27" name=root uid=0 username=root
time="2024-10-09T07:09:56Z" level=warning msg="Configuration: access_control: no rules have been specified so the 'default_policy' of 'one_factor' is going to be applied to all requests"
time="2024-10-09T07:09:56Z" level=info msg="Authelia v4.38.10 is starting"
time="2024-10-09T07:09:56Z" level=info msg="Log severity set to debug"
time="2024-10-09T07:09:56Z" level=info msg="Storage schema is being checked for updates"
time="2024-10-09T07:09:56Z" level=info msg="Storage schema is already up to date"
time="2024-10-09T07:09:56Z" level=debug msg="LDAP Supported OIDs. Control Types: 2.16.840.1.113730.3.4.18, 2.16.840.1.113730.3.4.2, 1.3.6.1.4.1.4203.1.10.1, 1.3.6.1.1.22, 1.2.840.113556.1.4.319, 1.2.826.0.1.3344810.2.3, 1.3.6.1.1.13.2, 1.3.6.1.1.13.1, 1.3.6.1.1.12. Extensions: 1.3.6.1.4.1.1466.20037, 1.3.6.1.4.1.4203.1.11.1, 1.3.6.1.4.1.4203.1.11.3, 1.3.6.1.1.8"
time="2024-10-09T07:09:56Z" level=error msg="Error occurred running a startup check" error="failed to dial connection: SMTP AUTH failed: unexpected server response: username:" provider=notification stack="github.com/authelia/authelia/v4/internal/commands/root.go:128 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.1/command.go:985                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
time="2024-10-09T07:09:57Z" level=fatal msg="One or more providers had fatal failures performing startup checks, for more detail check the error level logs" providers="[notification]" stack="github.com/authelia/authelia/v4/internal/commands/root.go:150 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:88  (*CmdCtx).RootRunE\ngithub.com/spf13/cobra@v1.8.1/command.go:985                  (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                 (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/internal/atomic/types.go:194                          (*Uint32).Load\nruntime/asm_amd64.s:1695                                      goexit"
```

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by shifouhaiyaocuoguoyigeyewan** [comment]
i try to  connect to the server over telnet or the openssl s_client ,and get  that info :
[root@Office248 authelia]# openssl s_client -connect smtp.mxhichina.com:465 -crlf -quiet
depth=2 C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
verify return:1
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign Organization Validation CA - SHA256 - G3
verify return:1
depth=0 C = CN, ST = ZheJiang, L = HangZhou, O = "Alibaba (China) Technology Co., Ltd.", CN = mail.aliyun.com
verify return:1
220 smtp.aliyun-inc.com MX AliMail Server
[root@Office248 authelia]# openssl s_client -connect smtp.example.com:465 -crlf -quiet
depth=2 C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
verify return:1
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign Organization Validation CA - SHA256 - G3
verify return:1
depth=0 C = CN, ST = ZheJiang, L = HangZhou, O = "Alibaba (China) Technology Co., Ltd.", CN = mail.aliyun.com
verify return:1
220 smtp.aliyun-inc.com MX AliMail Server
EHLO Office248
250-smtp.aliyun-inc.com
250-8BITMIME
250-AUTH=PLAIN LOGIN XOAUTH2 XALIOAUTH
250-AUTH PLAIN LOGIN XOAUTH2 XALIOAUTH
250-PIPELINING
250 DSN
AUTH LOGIN
334 dXNlcm5hbWU6
...
I also used the swaks tool to test the email authentication and successfully send emails, but I still don't know why the error occurs.

**Comment by james-d-elliott** [comment]
The error occurs because the email provider uses an abandoned draft spec instead of a final spec. The email library we use has adjusted their acceptance of these abandoned draft SMTP implementations to be more accepting and that behavior can be seen in the `:master` tag.

Authelia however has no formal support of draft specifications other than experimentally i.e. they can break and that's a problem for the implementer to solve (i.e. the AllMail server at smtp.aliyun-inc.com in this instance). At such a time that the experimental support of these abandoned drafts affects the ability to support a final spec we will abandon the support for it; regardless of it being this particular system or another; and it will not be considered a breaking change.

**Comment by shifouhaiyaocuoguoyigeyewan** [comment]
Thanks for your answer, I changed my email provider and that allowed my program to start successfully.
