### ISSUE TITLE
enhancement: give user feedback for password in ldap password history

### ISSUE THREAD

**Issue by Crowley723** [authelia/authelia#8122]
### Description

Give user feedback that the requested password change/reset failed due to the password being in the ldap password history.

Extends #2731 

### Use Case

User tries to reset password to an old password, user should be notified why the password change/reset failed.

### Details

Error notification at password reset/change time.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by davama** [comment]
Just fyi

our ldap backend is openldap
And of course willing to test 

thank you!

**Comment by james-d-elliott** [comment]
Duplicate of #2926
