### ISSUE TITLE
Restrict possible authentication methods

### ISSUE THREAD

**Issue by SerialVelocity** [authelia/authelia#82]
Hey,

It would be nice to be able to configure the two-factor auth that is used. For instance:
  - Just U2F
  - Just TOTP
  - Either

Cheers,
Ben

**Comment by clems4ever** [comment]
Hello @SerialVelocity , thank you for the proposal. It makes sense that one would like to use only one method but is it really a blocker, right now? I will implement it if I have other feedbacks saying so. 
However, I think that disabling the second factor is another subject and so I will create another ticket.

**Comment by SerialVelocity** [comment]
This is only a blocker for me because data isn't being written by NEDB to local storage. So not a high priority like you guessed :)

**Comment by nbently** [comment]
We would love to see this feature as we're using Authelia to protect a monitoring stack and do not want to allow users the option to create their own 2FA OTPs or U2F keys (only use Duo).

**Comment by james-d-elliott** [comment]
> 

You can now configure individual methods allowed per authelia instance. I still think this idea has merit but more in a "custom policy" kind of way.
