### ISSUE TITLE
Authelia, Traefik and Trac

### ISSUE THREAD

**Issue by LsHallo** [authelia/authelia#842]
Hello,
I'm working in a corporate environment and authelia is working well so far with our traefik instance (on docker) and we use it to authenticate our dev website. Now we want to secure our trac ([https://trac.edgewall.org/](https://trac.edgewall.org/)) which uses the REMOTE_USER header to identify the user after he has successfully authenticated. ([https://trac.edgewall.org/wiki/TracInstall#ConfiguringAuthentication](https://trac.edgewall.org/wiki/TracInstall#ConfiguringAuthentication))
I've looked at issue #208 but couldn't gather how to configure my instance so that trac gets the user as the header. Hoping someone who has more knowledge can help.

**Comment by LsHallo** [comment]
Here are all the config files: https://gist.github.com/LsHallo/c2751c38ec71fab93daadb652fbc8e72

**Comment by LsHallo** [comment]
I've confirmed with curl that if I set the REMOTE_USER header and request the index page of trac while bypassing authelia that it returns the correct page as if I am logged in. I now only need to know how to tell authelia to set that header when redirecting back to trac.

**Comment by nightah** [comment]
You need to use a different reverse proxy if you want to customise the header, I’d probably recommend nginx.

https://github.com/containous/traefik/issues/6047

Traefik doesn’t provide as much flexibility for header manipulation.

**Comment by nightah** [comment]
Just to elaborate a little further Authelia sets the `Remote-User` and `Remote-Groups` headers based on the user that is authenticated.

To have this come through based on your Traefik configuration you would need to add the following label to your Authelia container:
`”- traefik.http.middlewares.authelia.forwardauth.authresponseheaders=Remote-User"`

Now the issue is that trac expects REMOTE_USER so you would need to modify the header to make this work.

**Comment by LsHallo** [comment]
Thank you that was what was missing. I've used the example plugin given in the trac documentation to accept Remote-User as well. Works like a charm. Thank you again!

**Comment by LsHallo** [comment]
Here is the code from the plugin for any one else seeing this issue
```
from trac.core import *
from trac.config import BoolOption
from trac.web.api import IAuthenticator

class MyRemoteUserAuthenticator(Component):

    implements(IAuthenticator)

    obey_remote_user_header = BoolOption('trac', 'obey_remote_user_header', 'false', 
               """Whether the 'Remote-User:' HTTP header is to be trusted for user logins 
                (''since ??.??').""") 

    def authenticate(self, req):
        if self.obey_remote_user_header and req.get_header('Remote-User'): 
            return req.get_header('Remote-User') 
        return None
```

**Comment by nightah** [comment]
I’ll update the examples and documentation to include that header for the Traefik variants.
