### ISSUE TITLE
High memory usage in docker w/ file-based user database

### ISSUE THREAD

**Issue by 726a67** [authelia/authelia#845]
I've noticed an inordinate amount of memory usage reported following successful authentications when running Authelia inside of a docker container and utilizing a file-based user database.

Before authentication:

```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
01aa33590ab0        authelia            0.00%               11.09MiB / 15.41GiB   0.07%               1.18kB / 0B         0B / 0B             11
```

After authentication:
```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
01aa33590ab0        authelia            0.01%               1.049GiB / 15.41GiB   6.81%               22.7kB / 4.98kB     0B / 0B             11
```
I am using the default password hashing configuration (argon2id w/ default settings). It's possible that the libraries used to provide this configuration are not properly releasing memory after it has been allocated.

**Comment by clems4ever** [comment]
Hello @726a67 , thanks for reporting that issue. As discussed, this issue is likely due to Argon2 library not releasing memory properly after hashing. cc @james-d-elliott, @nightah .

We need to have a thorough look at that issue but if you cannot wait, a workaround would be to use sha512 as your password hashing algorithm but it would require resetting passwords of all users unfortunately.

Stay tune.

**Comment by james-d-elliott** [comment]
Yes I've been researching it. It's a possible issue with golang's argon2 implementation. It allocates to the heap and doesn't seem to ever GC. I'm thinking this may be due to lack of memory pressure but I'm not an expert on go's GC.

**Comment by 726a67** [comment]
@clems4ever, would you mind verifying the correct way to implement sha512 as the hashing algorithm? The [documentation](https://docs.authelia.com/configuration/authentication/file.html#password-hash-algorithm-tuning) states that it can be changed using the following configuration:

```
authentication_backend:
    file:
        path: /var/lib/authelia/users.yml
            password_hashing:
                algorithm: argon2id
```

And the [configuration file](https://github.com/authelia/authelia/blob/master/config.template.yml) itself says it can be changed like this:

```
file:
  path: ./users_database.yml
  password_options:
    algorithm: argon2id
```

But I've tried both configurations and neither seems to affect newly-set passwords -- my database file continues to show password entries in the following format:

`password: $argon2id$v=<hash>`

**Comment by james-d-elliott** [comment]
> 
> 
> @clems4ever, would you mind verifying the correct way to implement sha512 as the hashing algorithm? The [documentation](https://docs.authelia.com/configuration/authentication/file.html#password-hash-algorithm-tuning) states that it can be changed using the following configuration:
> 
> ```
> authentication_backend:
>     file:
>         path: /var/lib/authelia/users.yml
>             password_hashing:
>                 algorithm: sha512
> ```
> 
> And the [configuration file](https://github.com/authelia/authelia/blob/master/config.template.yml) itself says it can be changed like this:
> 
> ```
> file:
>   path: ./users_database.yml
>   password_options:
>     algorithm: sha512
> ```
> 
> But I've tried both configurations and neither seems to affect newly-set passwords -- my database file continues to show password entries in the following format:
> 
> `password: $argon2id$v=<hash>`

Your spacing was a little off. 

```
authentication_backend:
    file:
        path: /var/lib/authelia/users.yml
        password_hashing:
            algorithm: sha512
```

**Comment by james-d-elliott** [comment]
So what's actually happening is that it is GC'd but it's not freed in the OS since the OS doesn't have memory pressure. We can manually trigger this with debug.FreeOSMemory().

**Comment by james-d-elliott** [comment]
@726a67 So according to go docs: `FreeOSMemory forces a garbage collection followed by an attempt to return as much memory to the operating system as possible. (Even if this is not called, the runtime gradually returns memory to the operating system in a background task.).`

I'd really be interested in seeing if the memory is eventually freed over the course of maybe 1 hour. Is that something you'd be willing to test for me?

**Comment by nightah** [comment]
> So what's actually happening is that it is GC'd but it's not freed in the OS since the OS doesn't have memory pressure.

This is correct; [Go frees memory](https://golang.org/src/runtime/mem_linux.go) using `madvise` with the `MAPDV_FREE` flag if running on a Linux kernel >= 4.5.

http://man7.org/linux/man-pages/man2/madvise.2.html

>MADV_FREE (since Linux 4.5)
              The application no longer requires the pages in the range
              specified by addr and len.  The kernel can thus free these
              pages, but **the freeing could be delayed until memory pressure
              occurs**.

If you're running on Linux kernel < 4.5, then the runtime uses the `MADV_DONTNEED` flag.

>MADV_DONTNEED
Note that, when applied to shared mappings, MADV_DONTNEED
              might not lead to immediate freeing of the pages in the range.
              **The kernel is free to delay freeing the pages until an
              appropriate moment**.  The resident set size (RSS) of the
              calling process will be immediately reduced however.

This indeed is by design.

One thing to call out is if utilising a file based backend and argon2 algorithm, in the moment (usually < 1sec) when a user is logging in and Authelia is comparing the password hash, the amount of memory utilised will be based on the configured parameters and the default is 1GB.

So if you have a very busy server using a file based backend with argon2 the memory implications *could be large*, but we're talking a lot of users logging in within milliseconds of each other, otherwise the memory footprint is relatively static.

That memory is freed up in the next GC run for the kernel to use as it pleases, whether the kernel chooses to do so is another thing.

> We can manually trigger this with debug.FreeOSMemory().

We could do this but it's an inelegant way to handle something which I think has more to do with perception than it being an actual issue.

**Comment by 726a67** [comment]
@james-d-elliott 

> Your spacing was a little off. Notably this is an error in the docs as well. I'll fix it.
> 
> ```
> authentication_backend:
>     file:
>         path: /var/lib/authelia/users.yml
>         password_hashing:
>             algorithm: sha512
> ```

Just tried this and there's still no change reflected in the database file. Here's my current backend section:

```
authentication_backend:
  disable_reset_password: false
  file:
    path: /etc/authelia/users_database.yml
    password_hashing:
      algorithm: sha512
```
Passwords are still seemingly hashed w/ argon2, even after several manual resets.

> I'd really be interested in seeing if the memory is eventually freed over the course of maybe 1 hour. Is that something you'd be willing to test for me?

Tested this as well; the reported memory usage did not reduce over the course of two hours, although I haven't gone out of my way to generate any memory pressure.

**Comment by nightah** [comment]
You could use [stress-ng](http://manpages.ubuntu.com/manpages/bionic/man1/stress-ng.1.html) to test.
`stress-ng --vm-bytes $(awk '/MemFree/{printf "%d\n", $2 * 0.9;}' < /proc/meminfo)k --vm-keep -m 1`

**Comment by 726a67** [comment]
Using stress-ng to create some pressure did eventually cause authelia to report less memory usage.

**Comment by nightah** [comment]
I can confirm that irrespective of the algorithm set in the configuration, new passwords are always hashed in argon2.

This is a bug, I recall @james-d-elliott and I speaking about it briefly and we discussed setting the default to argon2, but you should still have the option to revert to sha512.

If the memory displayed bothers you, you can also tune down the argon2 utilisation, however given that you've tested the memory is recalled by the kernel with some pressure I don't think this is necessarily an issue.

We will definitely fix the sha512 bug though, cc @james-d-elliott.

**Comment by 726a67** [comment]
Agreed; since this seems to be largely an aesthetic issue, I'm not really worried about it. I'll keep an eye out for the sha512 bug fix. Thanks!

**Comment by james-d-elliott** [comment]
I will look into it. If it's acting like that I will fix it.

**Comment by james-d-elliott** [comment]
Wait, how are you hashing the password @726a67 ? Using reset password or?

**Comment by 726a67** [comment]
@james-d-elliott yeah, I’m using the password reset email/interface.

**Comment by james-d-elliott** [comment]
@726a67 it was a mismatch between the actual configuration key and the documentation. It's not 'password_hashing' it's just 'password'. When we implemented argon2id there were a lot of rapid changes and I personally missed updating the documentation on this one I think.


```
authentication_backend:
  disable_reset_password: false
  file:
    path: /etc/authelia/users_database.yml
    password:
      algorithm: sha512
```

**Comment by james-d-elliott** [comment]
@726a67 this is fixed by the following areas of documentation (see the important note in the second link):

https://docs.authelia.com/configuration/authentication/file.html#configuration

https://docs.authelia.com/configuration/authentication/file.html#password-hash-algorithm
