### ISSUE TITLE
Client Certificate authentication support

### ISSUE THREAD

**Issue by dzervas** [authelia/authelia#846]
I'm not sure if I'm asking the correct project, but here it is:

I use traefik with docker provider to proxy my services over SSL and I want a central authentication mechanism for all of my services - some of them support OAuth, some don't. Even if they don't I can use traefik to only let some users in. I think that's a good case for authelia.

Now what I would love is to issue a client certificate for each device that I have and get authenticated automatically - or even with 2FA.

Does authelia has support for that?
Do I need authelia to support that or I can delegate the client certificate handling to traefik (or any other service) - keep in mind that I want not only to check the validity of the cert, but to check if the user has the rights to login to jira as admin for example - I need to transfer data to the OAuth provider.
If authelia solves all of the above problems, I'm terminating the SSL connection to traefik (and that's difficult to change), so I guess the client certificate won't reach authelia (authelia will be behind traefik), is that a problem?

**Comment by clems4ever** [comment]
Hello @dzervas , there are multiple questions in your issue so I'll try to answer them all but let me know if I miss something or if I misunderstood one.

- Do Authelia support client certificate authentication? No.

- Can I transfer the authentication data to the backend service (or any OAuth provider)? Authelia is not an OAuth provider itself yet and there is only one way to forward authentication data to the backend or anything else. It is by reading X-Forwarded-User and X-Forwarded-Group headers populated by Authelia upon successful authentication. FYI, the issue for supporting OAuth2 or OIDC is still open and it's gonna be one of my top priorities for the next couple of weeks: https://github.com/authelia/authelia/issues/189.

- Can I do client certificate authentication with Traefik and 2nd factor with Authelia? No, Authelia needs to know the user in some way to evaluate ACLs so it needs the first factor and today it's not possible to mix authentication steps from several systems. One possibility would be to have a 3FA (client cert auth done by traefik, 1FA and 2FA by Authelia) but I think it's what you want to avoid, right?

Does that answer all your questions?

I'm sorry that I answered to all your questions with the negative but well, if you wish to contribute to make Authelia evolve faster, you're welcome to join us.

**Comment by dzervas** [comment]
Huh! such a great answer!

Ok, it seems that I’m missing some steps so I’ll just set it up and fiddle with it till I fail and write why/how here as a followup. Closing till then!

Thank you very much for the project & the support!

**Comment by clems4ever** [comment]
You're welcome @dzervas .
