### ISSUE TITLE
Authelia deletes configuration.yml file while testing in Docker

### ISSUE THREAD

**Issue by F1zzyD** [authelia/authelia#8513]
### Version

v4.38.17

### Deployment Method

Docker

### Reverse Proxy

NGINX Proxy Manager

### Reverse Proxy Version

2.12.2

### Description

While attempting to get the configuration.yml to finally work, Authelia will fail/refuse to reed the configuration.yml file it has been reading. The file is accessable, has correct permissions, and is properly routed for Authelia to read. However, Authelia will ignore it and revert to default configuration parameters without creating a new file. This makes it so I have to delete the file and start over from scratch......

### Reproduction

1. Test the configuration.yml file
2. Something doesn't work (shocker)
3. Run `docker compose down` so I can edit the configuration.yml file
4. Save the configuration.yml changes
5. Run `docker compose up`
6. Authelia ignores the configuration.yml file, uses default values, and complains that the configuration.yml file is not set up correctly
7. Say a few choice words and start over again...

### Expectations

Authelia should read the configuration.yml file....

### Configuration (Authelia)

```yaml
N/A
```

### Build Information

```shell
Cannot provide as Authelia has still not been ran successfully
```

### Logs (Authelia)

```shell
authelia exited with code 0
authelia  | time="2024-12-26T18:30:23Z" level=error msg="Configuration: secrets: error loading secret into key 'identity_validation.reset_password.jwt_secret': it's already defined in other configuration sources"
authelia  | time="2024-12-26T18:30:23Z" level=error msg="Configuration: secrets: error loading secret into key 'session.secret': it's already defined in other configuration sources"
authelia  | time="2024-12-26T18:30:23Z" level=error msg="Configuration: authentication_backend: you must ensure either the 'file' or 'ldap' authentication backend is configured"
authelia  | time="2024-12-26T18:30:23Z" level=error msg="Configuration: access_control: 'default_policy' option 'deny' is invalid: when no rules are specified it must be 'two_factor' or 'one_factor'"
authelia  | time="2024-12-26T18:30:23Z" level=error msg="Configuration: session: option 'cookies' is required"
authelia  | time="2024-12-26T18:30:23Z" level=error msg="Configuration: storage: postgres: option 'address' is required"
authelia  | time="2024-12-26T18:30:23Z" level=error msg="Configuration: storage: postgres: option 'username' and 'password' are required"
authelia  | time="2024-12-26T18:30:23Z" level=error msg="Configuration: storage: postgres: option 'database' is required"
authelia  | time="2024-12-26T18:30:23Z" level=error msg="Configuration: notifier: you must ensure either the 'smtp' or 'filesystem' notifier is configured"
authelia  | time="2024-12-26T18:30:23Z" level=fatal msg="Can't continue due to the errors loading the configuration" stack="github.com/authelia/authelia/v4/internal/commands/context.go:327 (*CmdCtx).ConfigValidateLogRunE\ngithub.com/authelia/authelia/v4/internal/commands/context.go:186 NewRootCmd.(*CmdCtx).ChainRunE.func1\ngithub.com/spf13/cobra@v1.8.1/command.go:970                     (*Command).execute\ngithub.com/spf13/cobra@v1.8.1/command.go:1117                    (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.8.1/command.go:1041                    (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10          main\ninternal/runtime/atomic/types.go:194                             (*Uint32).Load\nruntime/asm_amd64.s:1700                                         goexit"
```

### Logs (Proxy / Application)

```shell
N/A as Authelia has still not been ran successfully
```

### Generative AI

No

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment]
The `docker compose down`  is the most likely cause of this if the volume is not external. We don't delete the config file.
