### ISSUE TITLE
GDRP Banner not showing

### ISSUE THREAD

**Issue by Lansenou** [authelia/authelia#8537]
### Version

v4.38.17

### Deployment Method

Docker

### Reverse Proxy

NGINX

### Reverse Proxy Version

NPM 2.12.2

### Description

I'm using this configuration in my configuration.yml.

```yml
privacy_policy:
  enabled: true
  require_user_acceptance: true
  policy_url: 'https://example.com/privacy-policy/'
```

Which makes the html show as 
```html
<body data-basepath="" data-duoselfenrollment="false" data-logooverride="false" data-privacypolicyaccept="" data-privacypolicyurl="" data-rememberme="true" data-resetpassword="true" data-resetpasswordcustomurl="" data-theme="dark">
...
</body>
```

And thus produces the empty tags:
```html
<body data-privacypolicyaccept="" data-privacypolicyurl=""/>
```

I can see that the privacy_policy is validated & parsed correctly, if I for example change the privacy_policy url from https to http I receive an error.

### Reproduction

The other values I edit are immediately updated inside the body tag, for example if I switch my theme from dark to light, that is reflected when I restart authelia.

Configuration.yml
```yml
privacy_policy:
  enabled: true
  require_user_acceptance: true
  policy_url: 'https://example.com/privacy-policy/'
```

### Expectations

I would expect these html values to be filled with the privacy_policy values. Which would cause the GDPR banner to show on the login screen.

```html
<body data-privacypolicyaccept="true" data-privacypolicyurl="https://example.com/privacy-policy/"/>
```

### Build Information

```shell
Last Tag: v4.38.17
State: tagged clean
Branch: v4.38.17
Commit: 592ab519b4167dfe4462ee0a613d38d3e4b8efa0
Build Number: 35061
Build OS: linux
Build Arch: amd64
Build Compiler: gc
Build Date: Thu, 31 Oct 2024 09:37:31 +1100
Extra: 

Go:
    Version: go1.23.2
    Module Path: github.com/authelia/authelia/v4
    Executable Path: github.com/authelia/authelia/v4/cmd/authelia
```

### Logs (Authelia)

```shell
time="2024-12-30T18:37:18+01:00" level=debug msg="Loaded Configuration Sources" files="[/config/configuration.yml /config/configuration.acl.yml /config/configuration.oidc.yml]" filters="[template]"

time="2024-12-30T18:37:18+01:00" level=debug msg="Logging Initialized" fields.level=debug file=/config/authelia.log format= keep_stdout=true

time="2024-12-30T18:37:18+01:00" level=debug msg="Process user information" gid=0 gids="1,2,3,4,6,10,11,20,26,27" name=root uid=0 username=root

time="2024-12-30T18:37:18+01:00" level=info msg="Authelia v4.38.17 is starting"

time="2024-12-30T18:37:18+01:00" level=info msg="Log severity set to debug"

time="2024-12-30T18:37:18+01:00" level=debug msg="Registering client portainer with policy two_factor (two_factor)"

time="2024-12-30T18:37:18+01:00" level=debug msg="Registering client guacamole with policy two_factor (two_factor)"

time="2024-12-30T18:37:18+01:00" level=debug msg="Registering client synology-dsm with policy two_factor (two_factor)"

time="2024-12-30T18:37:18+01:00" level=info msg="Storage schema is being checked for updates"

time="2024-12-30T18:37:18+01:00" level=info msg="Storage schema is already up to date"

time="2024-12-30T18:37:18+01:00" level=debug msg="Create Server Service (metrics) skipped"

time="2024-12-30T18:37:18+01:00" level=info msg="Listening for non-TLS connections on '[::]:9091' path '/'" server=main service=server

time="2024-12-30T18:37:18+01:00" level=info msg="Startup complete"
```

### Documentation

My Docker compose has multiple configuration.yml in it like this, which works fine to split my oidc/acl logic.
docker-compose.yml
```yml
    environment:
      - X_AUTHELIA_CONFIG=/config/configuration.yml,/config/configuration.acl.yml,/config/configuration.oidc.yml
      - X_AUTHELIA_CONFIG_FILTERS=template
```

My guess is that somehow the convertion from the configuration value to the 'data-' is broken.

### Generative AI

No

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] This is a bug report and not a support request

- [X] I have read the security policy and this bug report is not a security issue or security related issue

- [X] I have either included the complete configuration file or I am sure it's unrelated to the configuration

- [X] I have either included the complete debug / trace logs or the output of the build-info command if the logs are not relevant

- [X] I have provided all of the required information in full with the only alteration being reasonable sanitization in accordance with the [Troubleshooting Sanitization](https://www.authelia.com/r/sanitize) reference guide

- [X] I have checked for related proxy or application logs and included them if available

- [X] I have checked for related issues and checked the documentation

**Comment by nightah** [comment]
@Lansenou can you please try the container tag: `fix-web-privacypolicy`.

**Comment by Lansenou** [comment]
@nightah That one works! :)

**Comment by nightah** [comment]
> @nightah That one works! :)

Great thanks for confirming, we will get this merged and try to release a hot fix in the next day or so.
