### ISSUE TITLE
[Guide] How to get Jira to auto-login with authelia SSO

### ISSUE THREAD

**Issue by dzervas** [authelia/authelia#858]
I'm writing this for anyone that wants to auto-login to Jira with authelia :)
My setup is traefik with docker provider and jira & authelia as containers
I'm using a paid (but cheap) Jira plugin, [EasySSO](https://marketplace.atlassian.com/apps/1212581/easy-sso-jira-kerberos-ntlm-saml?hosting=server&tab=overview) (I'm not affiliated in any way, just searched "http header" in marketplace)

You need to do the following:
  - Add `traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups` in the labels of authelia
  - Add `traefik.http.routers.jira.middlewares=authelia@docker` in the labels of Jira
  - Install EasySSO in Jira
  - Go to EasySSO preferences and add the "Remote-User" header under HTTP and tick the "Username" checkbox.
  - Profit!

**Comment by dzervas** [comment]
Closing as it's not a question

**Comment by james-d-elliott** [comment]
We can probably add this to our community docs. :)

**Comment by dzervas** [comment]
Do you take MRs? 😊
Better there than my blog!

**Comment by james-d-elliott** [comment]
We do. Here's the docs site: https://docs.authelia.com/community/
Here's the source: https://github.com/authelia/authelia/tree/master/docs/community

If you know markdown you can easily contribute to our docs.
