### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by shizunge** [authelia/authelia#866]
What is the minimal memory requirement of Authelia?

I encountered out of memory problem when running the Authelia example using docker:
https://github.com/authelia/authelia/tree/master/compose/local

- Here is my system (ubuntu 18.04 LTS):
\# uname --all
Linux vps_high_freq 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- My docker version is:
\# docker -v
Docker version 19.03.8, build afacb8b7f0

- Memory information (total 1G memory): 
\# free -m
              total        used        free      shared  buff/cache   available
Mem:            985         410         160          38         414         410
Swap:             0           0           0

- Authelia command which caused the problem and traces:
\# docker run authelia/authelia authelia hash-password $PASSWORD

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xed0ebb, 0x16)
	runtime/panic.go:1112 +0x72
runtime.sysMap(0xc004000000, 0x40000000, 0x1737bd8)
	runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x1721f60, 0x40000000, 0x1721f68, 0x20000)
	runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x1721f60, 0x20000, 0x0)
	runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x1721f60, 0x20000, 0x7ffff1d80100, 0x1737be8, 0x15)
	runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0x1721f60, 0x20000, 0x460101, 0x1721f60)
	runtime/mheap.go:865 +0x81
runtime.largeAlloc(0x40000000, 0x460101, 0x4)
	runtime/malloc.go:1152 +0x92
runtime.mallocgc.func1()
	runtime/malloc.go:1047 +0x46
runtime.systemstack(0x466054)
	runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	runtime/proc.go:1041

goroutine 1 [running]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:330 fp=0xc00019f6b0 sp=0xc00019f6a8 pc=0x466150
runtime.mallocgc(0x40000000, 0xdcca20, 0xc000035001, 0xc0001e6800)
	runtime/malloc.go:1046 +0x895 fp=0xc00019f750 sp=0xc00019f6b0 pc=0x40de75
runtime.makeslice(0xdcca20, 0x100000, 0x100000, 0xc000035090)
	runtime/slice.go:49 +0x6c fp=0xc00019f780 sp=0xc00019f750 pc=0x44d3ec
golang.org/x/crypto/argon2.initBlocks(0xc000035040, 0x800100000, 0x8, 0xc00028b510, 0xc)
	golang.org/x/crypto@v0.0.0-20190605123033-f99c8df09eb5/argon2/argon2.go:160 +0x59 fp=0xc00019f7e0 sp=0xc00019f780 pc=0x765d69
golang.org/x/crypto/argon2.deriveKey(0x2, 0xc00028b500, 0x4, 0x8, 0xc00028b510, 0xc, 0xc, 0x0, 0x0, 0x0, ...)
	golang.org/x/crypto@v0.0.0-20190605123033-f99c8df09eb5/argon2/argon2.go:115 +0x1d0 fp=0xc00019f8d0 sp=0xc00019f7e0 pc=0x765880
golang.org/x/crypto/argon2.IDKey(...)
	golang.org/x/crypto@v0.0.0-20190605123033-f99c8df09eb5/argon2/argon2.go:99
github.com/simia-tech/crypt.argon2idAlgorithm(0x7ffff1d8ef75, 0x4, 0xc0000b9540, 0x36, 0xc0002134c0, 0x10, 0xc0000b9540, 0x36)
	github.com/simia-tech/crypt@v0.4.2/argon2id.go:79 +0x2d8 fp=0xc00019fab8 sp=0xc00019f8d0 pc=0x76f848
github.com/simia-tech/crypt.Crypt(0x7ffff1d8ef75, 0x4, 0xc0000b9540, 0x36, 0xc00019fbf0, 0x1, 0x1, 0xc0000b9540)
	github.com/simia-tech/crypt@v0.4.2/crypt.go:26 +0xec fp=0xc00019fb80 sp=0xc00019fab8 pc=0x770aec
github.com/authelia/authelia/internal/authentication.HashPassword(0x7ffff1d8ef75, 0x4, 0x0, 0x0, 0xec307c, 0x8, 0x1, 0x100000, 0x8, 0x20, ...)
	github.com/authelia/authelia/internal/authentication/password_hash.go:137 +0x241 fp=0xc00019fc70 sp=0xc00019fb80 pc=0x780261
github.com/authelia/authelia/internal/commands.glob..func1(0x16a75a0, 0xc0002a6220, 0x1, 0x1)
	github.com/authelia/authelia/internal/commands/hash.go:47 +0x2b2 fp=0xc00019fd50 sp=0xc00019fc70 pc=0xb27ff2
github.com/spf13/cobra.(*Command).execute(0x16a75a0, 0xc0002a6200, 0x1, 0x1, 0x16a75a0, 0xc0002a6200)
	github.com/spf13/cobra@v0.0.7/command.go:842 +0x29d fp=0xc00019fe28 sp=0xc00019fd50 pc=0x5dbced
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000af340, 0xc00019ff48, 0x1, 0x1)
	github.com/spf13/cobra@v0.0.7/command.go:943 +0x317 fp=0xc00019ff00 sp=0xc00019fe28 pc=0x5dc997
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.7/command.go:883
main.main()
	github.com/authelia/authelia/cmd/authelia/main.go:129 +0x19d fp=0xc00019ff88 sp=0xc00019ff00 pc=0xc4ef6d
runtime.main()
	runtime/proc.go:203 +0x212 fp=0xc00019ffe0 sp=0xc00019ff88 pc=0x437f62
runtime.goexit()
	runtime/asm_amd64.s:1373 +0x1 fp=0xc00019ffe8 sp=0xc00019ffe0 pc=0x468261

goroutine 6 [runnable]:
text/template/parse.(*lexer).emit(...)
	text/template/parse/lex.go:157
text/template/parse.lexText(0xc0000bc6c0, 0xf0c440)
	text/template/parse/lex.go:269 +0x4f0
text/template/parse.(*lexer).run(0xc0000bc6c0)
	text/template/parse/lex.go:230 +0x37
created by text/template/parse.lex
	text/template/parse/lex.go:223 +0x190

goroutine 7 [runnable]:
text/template/parse.(*lexer).emit(...)
	text/template/parse/lex.go:157
text/template/parse.lexText(0xc0000bc750, 0xf0c440)
	text/template/parse/lex.go:269 +0x4f0
text/template/parse.(*lexer).run(0xc0000bc750)
	text/template/parse/lex.go:230 +0x37
created by text/template/parse.lex
	text/template/parse/lex.go:223 +0x190

**Comment by shizunge** [comment]
I add 1G swap space.
Now the command 
\# docker run authelia/authelia authelia hash-password $PASSWORD
passed, though it seems slow.

**Comment by shizunge** [comment]
It took more than 20 seconds to verify the password, and it consumes a large amount of memory (more than 600M). Is it expected?

Memory usage before verifying password.
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           985M        199M        350M        4.4M        434M        644M
Swap:          1.0G        265M        758M

Memory usage during verifying the password
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           985M        857M         59M        2.2M         67M         23M
Swap:          1.0G        468M        555M

**Comment by nightah** [comment]
Are you running this on an embedded device @shizunge?

https://docs.authelia.com/configuration/authentication/file.html#examples-for-specific-systems
Is probably what you're looking for, however, I'd recommend reading that doc page in it's entirety.

**Comment by shizunge** [comment]
That is useful! thanks!
