### ISSUE TITLE
TOTP notification configuration

### ISSUE THREAD

**Issue by mamema** [authelia/authelia#886]
i have an working duo push authelia v4 (latest) and want to configure additional totp config. There i'm failing.
i have 

users_filter: (cn={0})
username_attribute: uid

and

mail_attribute: email

the attribute mail was not working (red error message, when i click the enrollment link), even though i'm using openldap which states, that the attribute email is an alias of mail

after setting to attribute email, the message "sending email" is showing up, no red error. But i receive not email. The debug error log of authelia shows that this user has no email configured, which isn't true. 
So there must be an config issue. I need a head start here, please
 

found my own issue: had to forceibly add the mail attribute to openldao. Running now.

**Comment by james-d-elliott** [comment]
Glad you fixed it, let us know if you need more help!
