### ISSUE TITLE
Add an exporter to monitor Authelia in Prometheus

### ISSUE THREAD

**Issue by clems4ever** [authelia/authelia#93]
An exporter tracking the regulation system would allow an admin to check if there are lot of brute forces for example.
It would also help with scalability allowing one to estimate the number of Authelia instances required for a given amount of users.
Or also tracking Authelia's performance in realtime for monitoring and alerting purposes.

**Comment by edasque** [comment]
Tu a prévu d'ajouter ca quand?

**Comment by clems4ever** [comment]
Sorry we don't have any ETA on that one.

**Comment by rogierlommers** [comment]
Would be nice indeed!

**Comment by laurivosandi** [comment]
Please also add counters for ACL rules

**Comment by Tchoupinax** [comment]
Hey!
What's up with this feature?

**Comment by james-d-elliott** [comment]
Hey we've not made this feature a priority yet, we welcome someone trying to implement opentelemetry though:

https://github.com/open-telemetry/opentelemetry-go
