### ISSUE TITLE
Strip server header being sent by Authelia

### ISSUE THREAD

**Issue by clems4ever** [authelia/authelia#945]
Server exposes the `server` header containing `fasthttp`. Without proper configuration at the reverse proxy, this discloses some information to scanners and hackers about the server being run.

Let's just simply strip that header.

**Comment by nightah** [comment]
```
https://github.com/valyala/fasthttp/blob/32940977fb67c66fa367b7fc8f59cfa0e4f80be7/server.go#L338-L345
```

Could just enable this bool, cc @james-d-elliott probably worth considering this in the read/write buffer size PR?
Not sure that we would need it configurable, we could just explicitly disable in the code.

**Comment by james-d-elliott** [comment]
Yeah I already saw that, I'm adding it in its own PR since it's a little security related and should show in the change log. Or you could if you wanted.
