### ISSUE TITLE
Can't paste the TOTP code

### ISSUE THREAD

**Issue by jtrott** [authelia/authelia#956]
I've just updated to 4.15.1 and now I find I cannot paste the 6 digit code into the web interface.

It would be much more convenient to be able to paste in the code rather than having to type it, reduces typos also.

**Comment by james-d-elliott** [comment]
I agree. What OS and browser are you looking to paste from?

OS: Windows/Linux/Android/iOS/etc
Browser: Firefox/Chrome/Safari/etc

**Comment by jtrott** [comment]
Tested on macOS 10.15.4 using Safari and Firefox.

**Comment by nightah** [comment]
Hi @jtrott I'm unable to replicate this behaviour on:
- Windows 10
  - Chrome
- macOS 10.13.6
  - Chrome
  - Safari

Assuming the TOTP code is already in my clipboard and I hit the TOPT page, Ctrl+v or Shift+Insert works on Windows and Command+v on macOS.

Are you sure the TOTP input field is actually in focus when you try and paste?

**Comment by jtrott** [comment]
Sorry for incorrectly raising this issue, it was caused by an extension "Stop the Madness" which tries to prevent websites from taking control of regular macOS functions.
Disabling its functionality for the login url has fixed the issue.

**Comment by nightah** [comment]
No problems, glad you managed to sort it out.
