### ISSUE TITLE
Accessing the logged in username from nginx

### ISSUE THREAD

**Issue by jtrott** [authelia/authelia#957]
I've setup a new instance of 4.15.1 using the docker container and using the example configuration from https://docs.authelia.com/deployment/supported-proxies/nginx.html.

I have a simple test PHP file running on the nginx instance that is also the reverse proxy for authelia. I can't seem to find a combination of settings that will allow PHP running in nginx to access the logged in username.

I ran a packet capture on port 9091 and saw that authelia is returning the logged in user in the Remote-User header of the 200 OK response.

This header isn't visible using php-fpm in nginx, not in phpinfo(), $_SERVER, or getallheaders().

Is there a setting I have missed somewhere?

**Comment by james-d-elliott** [comment]
I'm not super familiar with how nginx passes headers back, did you follow the guide in the [docs](https://docs.authelia.com/deployment/supported-proxies/nginx.html)?

**Comment by nightah** [comment]
@jtrott the `auth.conf` in the config examples includes the following:
```nginx
# Set the X-Forwarded-User and X-Forwarded-Groups with the headers
# returned by Authelia for the backends which can consume them.
# This is not safe, as the backend must make sure that they come from the
# proxy. In the future, it's gonna be safe to just use OAuth.
auth_request_set $user $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
proxy_set_header X-Forwarded-User $user;
proxy_set_header X-Forwarded-Groups $groups;
```

This takes the `Remote-Users` and `Remote-Groups` headers from Authelia and sets them as `X-Forwarded-User` and `X-Forwarded-Groups` respectively.

**Comment by jtrott** [comment]
@james-d-elliott I was using the guide in the docs, as I referenced in my question.

I worked it out just now, I needed to add the include lines to my

location ~ [^/]\.php(/|$) {                                                                                                                                                                              
	fastcgi_split_path_info ^(.+?\.php)(/.*)$;                                                                                                                                                       
		if (!-f $document_root$fastcgi_script_name) {                                                                                                                                            
		return 404;                                                                                                                                                                              
	} 
	fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;                                                                                                                                                 
	fastcgi_index index.php;                                                                                                                                                                         
	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;                                                                                                                                
	include fastcgi_params;                                                                                                                                                                          
}                                                                                                                                                                                                        

block and then add in some fastcgi_param settings to pass through the nginx variables

    location ~ [^/]\.php(/|$) {                                                                                                                                                                                  │····························
        include default_headers;                                                                                                                                                                                 │····························
        include /etc/nginx/auth.conf; # Activates Authelia for specified route/location, please ensure you have setup the domain in your configuration.yml                                            │····························
        include /etc/nginx/proxy.conf; # Reverse proxy configuration                                                                                                                                             │····························
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;                                                                                                                                                               │····························
            if (!-f $document_root$fastcgi_script_name) {                                                                                                                                                        │····························
                return 404;                                                                                                                                                                                      
            }                                                                                                                                                                                                    
                                                                                                                                                                                                                 
            fastcgi_pass unix:/var/run/php-fpm/www.sock;                                                                                                                                                         
            fastcgi_param REMOTE_USER $user;                                                                                                                                                                     
            fastcgi_param REMOTE_GROUPS $groups;                                                                                                                                                                  
            fastcgi_index index.php;                                                                                                                                                                             
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;                                                                                                                                    
            include fastcgi_params;                                                                                                                                                                              
    }                                                                                                                                                                                                            

That has enabled the php index.php to access to REMOTE_USER and REMOTE_GROUPS variables. Possibly this has been complicated by my running the php web app locally on the nginx proxy instance?

**Comment by james-d-elliott** [comment]
Could be! I'm glad you solved it. We're updating our docs to include more examples.

Could you let me know if these changes would have helped you or not: 
- https://github.com/authelia/authelia/pull/963/files
- https://github.com/authelia/authelia/pull/962/files

**Comment by jtrott** [comment]
Nope, I tried those changes first thing but they made no different to the visibility of the username in php. The username from authelia is present in the $user variable in nginx, I just needed to find a way to send that variable over to php-fpm. This probably all works fine if you are using nginx as a reverse proxy for another remote web server, I haven't tested that case.

**Comment by james-d-elliott** [comment]
Okay I understand. I will see if we can add that to the docs! Thanks a lot. :)

**Comment by nightah** [comment]
So I think the issue here is that you're expecting the headers in your app on every request, is that right?

Authelia exposes the headers to the reverse proxy in the hit to `/api/verify` that's when the reverse proxy presents it back to the backend application too based on the provided examples.

**Comment by jtrott** [comment]
My app is a single php page that is trying to capture the request IP address and the username which I use to open up a port forward in my firewall. It's all working now, thanks.
