### ISSUE TITLE
File provider argon2id salt formatted incorrectly

### ISSUE THREAD

**Issue by dchidell** [authelia/authelia#996]
When using a file provider for authentication the salt is not encoded in base64. This is an issue with the authelia code base - the crypt library expects either a base64 encoded salt as input, or an empty salt which it then generates. 

This problem seems to manifest itself in two ways - when generating a password with the built in utility you can see clearly that the salt is not base64 encoded.

If a salt longer than 16 characters is input, the input is simply truncated.

```
docker run -it --rm authelia/authelia:latest authelia hash-password -s thisisatestsalt mypassword
Password hash: $argon2id$v=19$m=1048576,p=8$thisisatestsals$LUhYIsK1LRzeMMJismC3gDSSKkagFCWRjI2OSx0nULU
```

When attempting to decode a valid string generated via: https://argon2.online/ the validity check of the salt is performed without any base64 operations. This results in a valid argon2id hash being discarded due to length comparison issues (the base64 encoded string is longer than the expected 16 character salt), and the following error is displayed in the log (the below string is using a randomised salt):

`msg="Error while checking password for user test: Salt input of UmczWWdNUXZIcklWRTduSQ is invalid (22 characters), it must be 16 or fewer characters"`

This means the only utility capable of generating valid hash strings is the built-in tool, which deviates from the expected standard.

**Comment by james-d-elliott** [comment]
@dchidell thanks for reporting and being so clear with your explanation, I'll take a look at a fix this weekend. Should be an easy one.

**Comment by james-d-elliott** [comment]
I've fixed the initial bug already, but another interesting one came up. Do you know if there is a proper well documented standard for hash storage? The actual argon2id standard doesn't seem to have one: https://tools.ietf.org/html/draft-irtf-cfrg-argon2-10

Using that tool with the following settings I get this hash: `$argon2id$v=19$m=1024,t=2,p=1$bm9zYWx0bm8$38lWyOSIqg+kTCF/EBl+gA`

Password/Plain text input: `apple123`
Salt: `nosaltno`
Par: `1`
Memory: `1024`
Iter: `2`
Hash Len: `16`

If you add k=16 to that hash, their own tool doesn't validate it. `$argon2id$v=19$m=1024,t=2,p=1,k=16$bm9zYWx0bm8$38lWyOSIqg+kTCF/EBl+gA`

**Comment by james-d-elliott** [comment]
This is the reference implementation. https://github.com/P-H-C/phc-winner-argon2

It doesn't store k= with the hash, so it's only used to validate the length by non-standard means. However the reference implementation has a default hash len of 32. Which suggests no value should equal 32, not 16 (making their implementation slightly faulty in that area).

I'll be taking a closer look at the ref implementation for anything else we're doing wrong. One thing that I noticed was min salt length is 8, and max is 2^32-1. I don't think we'll use that maximum, but we may play around with a much higher maximum.

**Comment by dchidell** [comment]
Thanks for looking at this so promptly! It may also be worth mentioning here, that there's a small issue when generating the output with the built in 'hash-password' tool - it multiplies your input by 1024 for the memory limit, which by default results in a memory limit of 1048576kb. I think either the input should be in kb, or make sure the default value is 1 (which is then multiplied by 1024).

I wasn't sure if this was the best place to bring this up - if you wish I can open a separate issue to track it.

**Comment by james-d-elliott** [comment]
No worries at all. It's fine to discuss that here. We consciously configured Authelia that way, I hope the reasons for this are clear - I didn't sleep well. First and foremost we're relatively security focused and the products main appeal is security. We also want to make it more user friendly; in time that will mean a admin interface. Short term I think what we could do is make it so the user can specify the unit of measurement with the default as it is. If you had any other suggestions we'd certainly consider them.

We felt the cost should equate to about 500ms of hashing on a reasonably middle of the line system of today. We also cannot underestimate the fact users may not take the time to tune their settings. We did not want to compromise security by setting them too low, and make the defaults prohibitive for those with slower machines. The settings we chose reflect roughly 500ms on 2-3 year old medium to high end laptops (based on our testing of course).

It also didn't feel user friendly for users to have to configure in KB, so we opted for MB. Most people don't have MB of RAM now it's GB of RAM. So it didn't make sense to have the fine control at the loss of user experience.

**Comment by dchidell** [comment]
That makes sense! Thanks for clarifying on my above comment. I'd go on about memory usage, but I've read the garbage collection article which seems to illustrate the part there it's not a problem (which is great documentation to have).

Have checked over the code in PR #999 - I like the \n touches!

**Comment by james-d-elliott** [comment]
Yeah, we were worried about it too. We spent a lot of time researching the memory usage. Someone else brought up the new lines so instead of an alternate PR  touching the same code may as well fix it.

You can try the PR with the authelia/authelia:fix-salt-encoding

**Comment by dchidell** [comment]
Looks good! 

Only issue I can see (but have not checked the code so cannot offer an explanation) is that if the iterations are specified (via the t parameter in the has string) when the iterations is one, the authentications fail. If this t param is omitted then authentications succeed. However if the hash is generated with multiple iterations and the t param is specified as it was generated, then it succeeds.

**Comment by james-d-elliott** [comment]
The only thing close to a standard [doc](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md#argon2-encoding) I could find says this:

`The parameters shall appear in the m,t,p,keyid,data order. The keyid and data parameters are optional; the three others are NOT optional.`

**Comment by dchidell** [comment]
Yeah if you leave t=1 in there - it fails. If you remove t=1 it works fine. For other varients where t != 1, then specifying it works fine, seems to only be an issue if it's left as the default with t=2.

It's also worth noting in that case, that the hash-password tool does NOT insert the t param if it's equal to 1.

**Comment by james-d-elliott** [comment]
So the authentications fail in Authelia when this happens?

**Comment by dchidell** [comment]
That seems to have fixed it - both with and without the t param when t=1 now works (even if it's expected to be included).

The CLI hash-password tool is however still omitting the t param when it's equal to one. 

```
docker run -it --rm authelia/authelia:fix-salt-encoding authelia hash-password -p 1 -m 1 -l 16 -k 32 -i 1  blahblah
Password hash: $argon2id$v=19$m=1024,p=1$eXFRQWpSNDR3ck9UdEFHMw$aZWfGGUZAJS8+w4mkxGHORA3VaK8RSGnTFSWmbHCoCU

docker run -it --rm authelia/authelia:fix-salt-encoding authelia hash-password -p 1 -m 1 -l 16 -k 32 -i 2  blahblah
Password hash: $argon2id$v=19$m=1024,t=2,p=1$b3VubllDT1ZZbVJGQVdPdg$XIFL/5NsJhxfauvsfLZqyheaF4L6oDVXPTpBQEf/l0o
```

**Comment by james-d-elliott** [comment]
@dchidell yeah sadly that's upstream with https://github.com/simia-tech/crypt - I've lodged a PR to fix it. We're considering just migrating to using the internal go library so we have more control over it. We only use sha512 and argon2id so it's easy to do with standard lib now.
