### ISSUE TITLE
Automatic http to https redirection

### ISSUE THREAD

**Issue by deeztek** [authelia/authelia#998]
Normally I accomplish http to https redirection in my containers by utilizing the following labels:

 
      - "traefik.http.routers.example.entrypoints=http"
      - "traefik.http.routers.example.rule=Host(`host.domain.tld`)"
      - "traefik.http.routers.example.middlewares=example-https-redirect"
      - "traefik.http.routers.example-secure.entrypoints=https"
      - "traefik.http.routers.example-secure.rule=Host(`host.domain.tld`)"
      - "traefik.http.routers.example-secure.tls=true"
      - "traefik.http.routers.example-secure.tls.certresolver=le"
      - "traefik.http.routers.example-secure.service=example"
      - "traefik.http.middlewares.example-https-redirect.redirectscheme.scheme=https"

This works fine until I introduce authelia into the mix. If I try to visit http://host.domain.tld I get an "Unauthorized" message in the browser. Looking at Traefik logs I get the following error:

level=error msg="Scheme of target URL http://host.domain.tld/ must be secure since cookies are only transported over a secure connection for security reasons

If I try to access https://host.domain.tld it works fine and I get an Authelia login prompt as expected.

**Comment by james-d-elliott** [comment]
If you plan to secure all domains with https in Traefik I believe in 2.2 service under the command line you can do something like this (note the entrypoint http is just a redirect to https):

```yaml
    command:
      - '--api'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.redirections.entryPoint.to=https'
      - '--entrypoints.http.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.https=true'
      - '--entrypoints.https.address=:443'
      - '--log=true'
      - '--log.level=DEBUG'
      - '--log.filepath=/var/log/traefik.log'
```

**Comment by deeztek** [comment]
What you posted above does not work in Traefik 2.2. Traefik gets the following error:

command traefik error: failed to decode configuration from flags: field not found, node: redirections

**Comment by nightah** [comment]
I believe you need the `to` and `scheme` per:
https://github.com/authelia/authelia/blob/85933dd25def3b1bbbfc0ca2bd9b4a084a6e745c/compose/local/docker-compose.yml#L58-L59

**Comment by james-d-elliott** [comment]
What @nightah said was nearly on point, the mistake I made was I had http.http.redirections, instead of http.redirections:

```yaml
    command:
      - '--api'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.redirections.entryPoint.to=https'
      - '--entrypoints.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.https=true'
      - '--entrypoints.https.address=:443'
```

**Comment by nightah** [comment]
You actually need the `http.http` in that example because the EntryPoint is actually called http.

**Comment by james-d-elliott** [comment]
I edited my comment to remove confusion.

**Comment by nightah** [comment]
> This works fine until I introduce authelia into the mix. If I try to visit http://host.domain.tld I get an "Unauthorized" message in the browser. Looking at Traefik logs I get the following error:
> 
> level=error msg="Scheme of target URL http://host.domain.tld/ must be secure since cookies are only transported over a secure connection for security reasons

@deeztek it's worthwhile calling out if you don't plan to use the global redirection you might be able to resolve your issue by defining your middlewares in a specific order or using chain middlewares.

**Comment by deeztek** [comment]
> @deeztek it's worthwhile calling out if you don't plan to use the global redirection you might be able to resolve your issue by defining your middlewares in a specific order or using chain middlewares.

Well, not using a global https redirection is what I've been doing thus far by defining the https redirection in each container. I'm assuming you mean setting up the redirection in the traefik static config but for each service separately instead of globally. Maybe an example would be good. 

This whole discussion assumes that setting up the redirection in the traefik static config will solve the secure cookie issue that I originally encountered.

**Comment by nightah** [comment]
If you do want everything to globally redirect just follow the example here:
https://github.com/authelia/authelia/blob/85933dd25def3b1bbbfc0ca2bd9b4a084a6e745c/compose/local/docker-compose.yml#L51-L64

If you want to continue performing it at a container level you need to ensure that you middlewares are defined in a specific order (redirect before forward auth) on a container by container basis, or you can use [middleware chains](https://docs.traefik.io/middlewares/chain/).

Realistically these aren't Authelia problems, please have a look at the aforementioned Traefik docs for more information.

**Comment by deeztek** [comment]
> If you want to continue performing it at a container level you need to ensure that you middlewares are defined in a specific order (redirect before forward auth) on a container by container basis

redirect middleware before forward auth middleware as you suggest does not seem to work in the container level. I'm getting "Unauthorized" trying to access the site over http. The only way I can get it to work is by setting http to https redirection on a global level at the Traefik static config as suggested above.

**Comment by nightah** [comment]
I don't know if there's an arbitrary order for middlewares or not, but when debugging another issue it seemed to suggest that the order you define them in can have an impact: https://github.com/authelia/authelia/issues/372.

If that doesn't work I would suggest trying middleware chains because from my understanding that specifically is to ensure that they are executed in a specified order.

**Comment by deeztek** [comment]
Actually I was mistaken. Setting up https redirect before Authelia authentication does seem to work. Here's the container labels just in case someone finds them useful:

```
labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      #Routers
      - "traefik.http.routers.myservice.entrypoints=http"
      - "traefik.http.routers.myservice.rule=Host(`host.domain.tld`)"
      - "traefik.http.routers.myservice.middlewares=myservice-https-redirect"
      - "traefik.http.routers.myservice-secure.entrypoints=https"
      - "traefik.http.routers.myservice-secure.rule=Host(`host.domain.tld`)"
      - "traefik.http.routers.myservice-secure.tls=true"
      - "traefik.http.routers.myservice-secure.tls.certresolver=le"
      - "traefik.http.routers.myservice-secure.service=myservice"

      #Middleware definitions
      - "traefik.http.middlewares.myservice-https-redirect.redirectscheme.scheme=https"

      #Authelia authentication
      - "traefik.http.routers.myservice-secure.middlewares=authelia@docker"

      #Service definition
      - "traefik.http.services.myservice.loadbalancer.server.port=80"

      # Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
```

**Comment by nightah** [comment]
> Actually I was mistaken. Setting up https redirect before Authelia authentication does seem to work.

Thanks for clarifying. Glad you got it sorted.
